-- SERIES 2
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS nova_en_v3_s002;
DELIMITER $$
CREATE PROCEDURE nova_en_v3_s002()
BEGIN
  DECLARE v_count INT DEFAULT 0;
  DECLARE v_course BIGINT UNSIGNED; DECLARE v_level BIGINT UNSIGNED; DECLARE v_module BIGINT UNSIGNED; DECLARE v_chapter BIGINT UNSIGNED;
  DECLARE v_c_arman BIGINT UNSIGNED; DECLARE v_c_maya BIGINT UNSIGNED;
  DECLARE v_l_1 BIGINT UNSIGNED; DECLARE v_l_2 BIGINT UNSIGNED; DECLARE v_l_3 BIGINT UNSIGNED; DECLARE v_l_4 BIGINT UNSIGNED;
  DECLARE v_u_1 BIGINT UNSIGNED; DECLARE v_u_2 BIGINT UNSIGNED; DECLARE v_u_3 BIGINT UNSIGNED; DECLARE v_u_4 BIGINT UNSIGNED; DECLARE v_u_5 BIGINT UNSIGNED; DECLARE v_u_6 BIGINT UNSIGNED;
  DECLARE v_ev BIGINT UNSIGNED;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;
  SELECT COUNT(*),MIN(id) INTO v_count,v_course FROM courses WHERE learning_language='en' AND base_language='fa';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='en-fa course identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_level FROM levels WHERE course_id=v_course AND cefr_level='A1';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='en-fa A1 missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_module FROM modules WHERE level_id=v_level AND sort_order=1;
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='en-fa module 1 missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_c_arman FROM characters WHERE course_id=v_course AND name='Arman' AND gender='male';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Arman identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_c_maya FROM characters WHERE course_id=v_course AND name='Maya' AND gender='female';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Maya identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_chapter FROM chapters WHERE module_id=v_module AND sort_order=2;
  IF v_count=0 THEN
    INSERT INTO chapters (module_id,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_module,'Where Are You From?','اهل کجا هستی؟','Arman learns to ask and answer about origin.','آرمان یاد می‌گیرد درباره مبدأ بپرسد و پاسخ دهد.',4,1,1,2,'validated',JSON_OBJECT('series',2,'contractVersion','3.0.0','level','A1','generatedStatus','locally_validated')); SET v_chapter=LAST_INSERT_ID();
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) VALUES
      (v_course,'from','from','preposition','از / اهلِ',1,JSON_OBJECT('cefr','A1','sense','origin'),CAST('["در","با","برای"]' AS JSON),'I''m from Iran.','من اهل ایران هستم.',JSON_OBJECT('sourceSeries',2,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:from:origin')),
      (v_course,'Iran','Iran','proper_noun','ایران',1,JSON_OBJECT('cefr','A1','sense','country'),CAST('["لندن","نام","سلام"]' AS JSON),'I''m from Iran.','من اهل ایران هستم.',JSON_OBJECT('sourceSeries',2,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:iran:country')),
      (v_course,'London','London','proper_noun','لندن',1,JSON_OBJECT('cefr','A1','sense','city'),CAST('["ایران","نام","خداحافظ"]' AS JSON),'Welcome to London.','به لندن خوش آمدی.',JSON_OBJECT('sourceSeries',2,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:london:city'));
    INSERT INTO learning_units (course_id,unit_type,unit_key,display_form,translation,description_fa,cefr_level,difficulty,data,metadata) VALUES
      (v_course,'chunk','en:a1:where-are-you-from','Where are you from?','اهل کجا هستی؟','پرسیدن کشور یا مبدأ شخص','A1',1,JSON_OBJECT('function','ask_origin'),JSON_OBJECT('series',2)),
      (v_course,'chunk','en:a1:im-from','I''m from ...','من اهل ... هستم','گفتن کشور یا مبدأ','A1',1,JSON_OBJECT('function','state_origin'),JSON_OBJECT('series',2)),
      (v_course,'word_sense','en:a1:from:origin','from','از / اهلِ','from برای بیان مبدأ','A1',1,JSON_OBJECT('pos','preposition','sense','origin'),JSON_OBJECT('series',2)),
      (v_course,'word_sense','en:a1:iran:country','Iran','ایران','نام کشور ایران','A1',1,JSON_OBJECT('pos','proper_noun'),JSON_OBJECT('series',2)),
      (v_course,'word_sense','en:a1:london:city','London','لندن','نام شهر لندن','A1',1,JSON_OBJECT('pos','proper_noun'),JSON_OBJECT('series',2)),
      (v_course,'pronunciation','en:a1:pron:from-vowel','from — reduced vowel in connected speech',NULL,'شنیدن و تولید طبیعی from در عبارت کوتاه','A1',1,JSON_OBJECT('target','schwa_in_unstressed_syllables'),JSON_OBJECT('series',2));
    SELECT id INTO v_u_1 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:where-are-you-from';
    SELECT id INTO v_u_2 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:im-from';
    SELECT id INTO v_u_3 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:from:origin';
    SELECT id INTO v_u_4 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:iran:country';
    SELECT id INTO v_u_5 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:london:city';
    SELECT id INTO v_u_6 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:pron:from-vowel';
    INSERT INTO curriculum_outcomes (course_id,cefr_level,outcome_key,outcome_type,title,description_fa,required,status,evidence) VALUES
      (v_course,'A1','grammar:be-present-identity','grammar','Be in simple identity statements','کاربرد be در معرفی ساده',1,'in_progress',JSON_ARRAY()),
      (v_course,'A1','lexical:greetings-identity-origin','lexical','Origin chunks','عبارت‌های پایه مبدأ',1,'in_progress',JSON_ARRAY()),
      (v_course,'A1','pron:schwa-unstressed','pronunciation','Notice reduced vowels','توجه به واکه کاهش‌یافته',1,'in_progress',JSON_ARRAY()),
      (v_course,'A1','listening:key-identity-info','listening','Catch identity information','تشخیص اطلاعات هویتی در شنیدار',1,'in_progress',JSON_ARRAY())
      ON DUPLICATE KEY UPDATE status='in_progress';
    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES
      (v_chapter,v_c_maya,v_c_arman,'Where Are You From?','اهل کجا هستی؟','Maya asks Arman where he is from.','مایا از آرمان می‌پرسد اهل کجاست.','story','london_new_start',5,1,420,1,'validated',JSON_OBJECT('pedagogicalRole','exposure')),
      (v_chapter,v_c_maya,v_c_arman,'From + Place','From و مکان','Arman notices the origin pattern.','آرمان الگوی بیان مبدأ را دقیق‌تر یاد می‌گیرد.','story','london_new_start',6,1,420,2,'validated',JSON_OBJECT('pedagogicalRole','explicit_form')),
      (v_chapter,v_c_maya,v_c_arman,'A New Introduction','یک معرفی تازه','Arman combines name and origin.','آرمان نام و مبدأ را در یک معرفی تازه به کار می‌برد.','story','london_new_start',7,1,420,3,'validated',JSON_OBJECT('pedagogicalRole','retrieval')),
      (v_chapter,v_c_maya,v_c_arman,'Meet Someone New','آشنایی با یک نفر تازه','Arman handles a short introduction independently.','آرمان یک معرفی کوتاه را مستقل مدیریت می‌کند.','story','london_new_start',8,1,420,4,'validated',JSON_OBJECT('pedagogicalRole','mastery'));
    SELECT id INTO v_l_1 FROM lessons WHERE chapter_id=v_chapter AND sort_order=1; SELECT id INTO v_l_2 FROM lessons WHERE chapter_id=v_chapter AND sort_order=2; SELECT id INTO v_l_3 FROM lessons WHERE chapter_id=v_chapter AND sort_order=3; SELECT id INTO v_l_4 FROM lessons WHERE chapter_id=v_chapter AND sort_order=4;
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
      (v_l_1,v_c_maya,1,'character','Hello, Arman!','سلام آرمان!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,2,'learner','Hello, Maya!','سلام مایا!',1,'Hello, Maya!',JSON_ARRAY('Hello, Maya!','Hi, Maya!'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_maya,3,'character','Where are you from?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,4,'learner','I''m from Iran.','من اهل ایران هستم.',1,'I''m from Iran.',JSON_ARRAY('I''m from Iran.','I am from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_maya,5,'character','Nice to meet you again.','خوشحالم دوباره می‌بینمت.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,6,'learner','Nice to meet you too.','من هم از دیدنت خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_maya,7,'character','Welcome to London.','به لندن خوش آمدی.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,8,'learner','Thank you.','ممنون.',1,'Thank you.',JSON_ARRAY('Thank you.','Thanks.'),JSON_ARRAY(),JSON_OBJECT()),
      (v_l_2,v_c_maya,1,'character','Where are you from?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,2,'learner','I''m from Iran.','من اهل ایران هستم.',1,'I''m from Iran.',JSON_ARRAY('I''m from Iran.','I am from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_maya,3,'character','From Iran?','از ایران؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,4,'learner','Yes, from Iran.','بله، از ایران.',1,'Yes, from Iran.',JSON_ARRAY('Yes, from Iran.','Yes. I''m from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_maya,5,'character','And your name is Arman.','و اسمت آرمان است.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,6,'learner','Yes. I''m Arman.','بله. من آرمان هستم.',1,'Yes. I''m Arman.',JSON_ARRAY('Yes. I''m Arman.','Yes. My name is Arman.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_maya,7,'character','Great.','عالیه.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,8,'learner','Thank you.','ممنون.',1,'Thank you.',JSON_ARRAY('Thank you.','Thanks.'),JSON_ARRAY(),JSON_OBJECT()),
      (v_l_3,v_c_maya,1,'character','Hi! What''s your name?','سلام! اسمت چیه؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,2,'learner','My name is Arman.','اسم من آرمان است.',1,'My name is Arman.',JSON_ARRAY('My name is Arman.','I''m Arman.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_maya,3,'character','Where are you from?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,4,'learner','I''m from Iran.','من اهل ایران هستم.',1,'I''m from Iran.',JSON_ARRAY('I''m from Iran.','I am from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_maya,5,'character','Nice to meet you.','از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,6,'learner','Nice to meet you too.','من هم از آشنایی با تو خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_maya,7,'character','Goodbye, Arman.','خداحافظ آرمان.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,8,'learner','Goodbye!','خداحافظ!',1,'Goodbye!',JSON_ARRAY('Goodbye!','Bye!'),JSON_ARRAY(),JSON_OBJECT()),
      (v_l_4,v_c_maya,1,'character','Hello! I''m Maya.','سلام! من مایا هستم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,2,'learner','Hello! I''m Arman.','سلام! من آرمان هستم.',1,'Hello! I''m Arman.',JSON_ARRAY('Hello! I''m Arman.','Hi! I''m Arman.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_maya,3,'character','Where are you from?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,4,'learner','I''m from Iran.','من اهل ایران هستم.',1,'I''m from Iran.',JSON_ARRAY('I''m from Iran.','I am from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_maya,5,'character','Nice to meet you, Arman.','از آشنایی با تو خوشحالم آرمان.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,6,'learner','Nice to meet you too.','من هم از آشنایی با تو خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_maya,7,'character','See you later.','بعدا می‌بینمت.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,8,'learner','Goodbye!','خداحافظ!',1,'Goodbye!',JSON_ARRAY('Goodbye!','Bye!'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_1,'listen',1,'Where are you from?','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'new_word',2,'I''m from ...','عبارت بیان مبدأ را یک تکه یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:im-from","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',3,'from','به ریتم کوتاه عبارت دقت کن.',1,CAST('{"mode":"sound_notice","target":"schwa_in_unstressed_syllables","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',4,'I''m from Iran.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["I''m from Iran.","I am from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',5,'بگو اهل ایران هستی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اهل ایران هستی.","accepted":["I''m from Iran.","I am from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'meaning_choice',6,'I''m ___ Iran.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["from","in","to"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'reading_comprehension',7,'Arman: Hello! I''m Arman. I''m from Iran.','متن کوتاه را بخوان.',1,CAST('{"mode":"reading_input","text":"Arman: Hello! I''m Arman. I''m from Iran.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'reading_comprehension',8,'Where is Arman from?','اطلاعات درست را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Iran","London","Maya"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'word_order',9,'Iran from I''m','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["I''m","from","Iran"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',10,'برای اولین بار با کسی آشنا شدی؛ نام و کشورت را بگو.','در موقعیت تازه پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"برای اولین بار با کسی آشنا شدی؛ نام و کشورت را بگو.","accepted_intents":["I''m Arman. I''m from Iran.","My name is Arman. I''m from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'listen',11,'Nice to meet you.','گوش کن و معنی را تشخیص بده.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',12,'Nice to meet you too.','مستقل پاسخ بده.',1,CAST('{"mode":"short_response","accepted":["Nice to meet you too.","Nice to meet you."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
      (v_l_2,'listen',1,'Where are you from?','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'new_word',2,'from','معنی from در مبدأ را یاد بگیر.',1,CAST('{"mode":"word_teach","unit_key":"en:a1:from:origin","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',3,'from Iran','به شکل طبیعی عبارت دقت کن.',1,CAST('{"mode":"sound_notice","target":"schwa_in_unstressed_syllables","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',4,'I''m from Iran.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["I''m from Iran.","I am from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',5,'از حافظه بگو اهل ایران هستی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"از حافظه بگو اهل ایران هستی.","accepted":["I''m from Iran.","I am from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'meaning_choice',6,'Where ___ you from?','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["are","is","am"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'reading_comprehension',7,'Maya: Where are you from? Arman: I''m from Iran.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Maya: Where are you from? Arman: I''m from Iran.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'reading_comprehension',8,'What place does Arman say?','پاسخ را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Iran","Maya","Hello"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'word_order',9,'from you are Where','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["Where","are","you","from"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',10,'از یک نفر تازه بپرس اهل کجاست.','در موقعیت تازه پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"از یک نفر تازه بپرس اهل کجاست.","accepted_intents":["Where are you from?","Where are you from"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'listen',11,'I''m from Iran.','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',12,'Where are you from?','پرسش را مستقل بگو.',1,CAST('{"mode":"short_response","accepted":["Where are you from?","Where are you from"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
      (v_l_3,'listen',1,'Hello! I''m Arman.','مرور را با گوش دادن شروع کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'new_word',2,'My name is ...','عبارت نام را مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:my-name-is","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',3,'Hello','به تاکید واژه دقت کن.',1,CAST('{"mode":"sound_notice","target":"basic_word_stress","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',4,'My name is Arman.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["My name is Arman.","I''m Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',5,'نامت را بگو.','بدون دیدن پاسخ بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"نامت را بگو.","accepted":["My name is Arman.","I''m Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'meaning_choice',6,'___ name is Arman.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["My","From","Hello"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'reading_comprehension',7,'Hello! My name is Arman. I''m from Iran.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Hello! My name is Arman. I''m from Iran.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'reading_comprehension',8,'What is his name?','نام را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Arman","Iran","Maya"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'word_order',9,'Arman is name My','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["My","name","is","Arman"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',10,'در یک موقعیت تازه سلام کن، نامت را بگو و بگو اهل ایران هستی.','مستقل پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در یک موقعیت تازه سلام کن، نامت را بگو و بگو اهل ایران هستی.","accepted_intents":["Hello! I''m Arman. I''m from Iran.","Hi! My name is Arman. I''m from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'listen',11,'Goodbye!','مرور شنیداری.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',12,'Goodbye!','پایان تعامل را مستقل بگو.',1,CAST('{"mode":"short_response","accepted":["Goodbye!","Bye!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
      (v_l_4,'listen',1,'Where are you from?','اول گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'new_word',2,'Where are you from?','پرسش مبدأ را یک تکه مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:where-are-you-from","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',3,'from','به صدا دقت کن.',1,CAST('{"mode":"sound_notice","target":"schwa_in_unstressed_syllables","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',4,'Where are you from?','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Where are you from?","Where are you from"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',5,'بگو اهل ایران هستی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اهل ایران هستی.","accepted":["I''m from Iran.","I am from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'meaning_choice',6,'I''m from ___.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["Iran","hello","name"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'reading_comprehension',7,'Maya: Hello. Arman: Hi. I''m Arman. I''m from Iran.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Maya: Hello. Arman: Hi. I''m Arman. I''m from Iran.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'reading_comprehension',8,'Where is Arman from?','اطلاعات را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Iran","London","Hello"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'word_order',9,'Iran from am I','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["I","am","from","Iran"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',10,'بدون راهنما خودت را به یک نفر تازه معرفی کن و مبدأ را هم بگو.','آزمون انتقال.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بدون راهنما خودت را به یک نفر تازه معرفی کن و مبدأ را هم بگو.","accepted_intents":["I''m Arman. I''m from Iran.","My name is Arman. I am from Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'listen',11,'Nice to meet you.','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',12,'Nice to meet you too.','پاسخ مستقل بده.',1,CAST('{"mode":"short_response","accepted":["Nice to meet you too.","Nice to meet you."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());
    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,metadata) VALUES
      (v_l_1,v_u_1,'new',1,2,JSON_OBJECT('series',2)),(v_l_1,v_u_2,'new',1,2,JSON_OBJECT('series',2)),(v_l_1,v_u_3,'new',1,2,JSON_OBJECT('series',2)),(v_l_1,v_u_4,'new',1,2,JSON_OBJECT('series',2)),(v_l_1,v_u_5,'new',1,2,JSON_OBJECT('series',2)),(v_l_1,v_u_6,'new',1,2,JSON_OBJECT('series',2)),
      (v_l_4,v_u_1,'mastery',1,2,JSON_OBJECT('series',2)),(v_l_4,v_u_2,'mastery',1,2,JSON_OBJECT('series',2)),(v_l_4,v_u_3,'mastery',1,2,JSON_OBJECT('series',2)),(v_l_4,v_u_4,'mastery',1,2,JSON_OBJECT('series',2)),(v_l_4,v_u_5,'mastery',1,2,JSON_OBJECT('series',2)),(v_l_4,v_u_6,'mastery',1,2,JSON_OBJECT('series',2));
    SELECT id INTO v_ev FROM activities WHERE lesson_id=v_l_3 AND JSON_UNQUOTE(JSON_EXTRACT(config,'$.mode'))='scenario_transfer' ORDER BY sort_order LIMIT 1;
    UPDATE review_obligations SET status='fulfilled',fulfilled_chapter_id=v_chapter,evidence_activity_id=v_ev,metadata=JSON_OBJECT('evidence','retrieval_transfer','series',2) WHERE course_id=v_course AND due_series=2 AND status='due';
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata)
      SELECT v_course,x.unit_id,v_chapter,2+x.off,x.off,'due',JSON_OBJECT('sourceSeries',2) FROM (
        SELECT v_u_1 unit_id,1 off UNION ALL SELECT v_u_1,2 UNION ALL SELECT v_u_1,4 UNION ALL SELECT v_u_1,8 UNION ALL SELECT v_u_1,16 UNION ALL
        SELECT v_u_2,1 UNION ALL SELECT v_u_2,2 UNION ALL SELECT v_u_2,4 UNION ALL SELECT v_u_2,8 UNION ALL SELECT v_u_2,16 UNION ALL
        SELECT v_u_3,1 UNION ALL SELECT v_u_3,2 UNION ALL SELECT v_u_3,4 UNION ALL SELECT v_u_3,8 UNION ALL SELECT v_u_3,16 UNION ALL
        SELECT v_u_4,1 UNION ALL SELECT v_u_4,2 UNION ALL SELECT v_u_4,4 UNION ALL SELECT v_u_4,8 UNION ALL SELECT v_u_4,16 UNION ALL
        SELECT v_u_5,1 UNION ALL SELECT v_u_5,2 UNION ALL SELECT v_u_5,4 UNION ALL SELECT v_u_5,8 UNION ALL SELECT v_u_5,16 UNION ALL
        SELECT v_u_6,1 UNION ALL SELECT v_u_6,2 UNION ALL SELECT v_u_6,4 UNION ALL SELECT v_u_6,8 UNION ALL SELECT v_u_6,16
      ) x ON DUPLICATE KEY UPDATE due_series=VALUES(due_series);
    UPDATE curriculum_outcomes SET evidence=JSON_ARRAY_APPEND(COALESCE(evidence,JSON_ARRAY()),'$','EN-CH-0002'),status='in_progress' WHERE course_id=v_course AND cefr_level='A1' AND outcome_key IN ('can_do:introduce_name','reading:short_identity','grammar:be-present-identity','lexical:greetings-identity-origin','pron:schwa-unstressed','listening:key-identity-info');
  ELSEIF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='chapter identity not unique'; END IF;
  COMMIT;
END$$
DELIMITER ;
CALL nova_en_v3_s002();
DROP PROCEDURE IF EXISTS nova_en_v3_s002;
