-- SERIES 1
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS nova_de_v32_s0001;
DELIMITER $$
CREATE PROCEDURE nova_de_v32_s0001()
BEGIN
DECLARE v_count INT DEFAULT 0; DECLARE v_course BIGINT UNSIGNED; DECLARE v_level BIGINT UNSIGNED; DECLARE v_module BIGINT UNSIGNED; DECLARE v_chapter BIGINT UNSIGNED; DECLARE v_c_raha BIGINT UNSIGNED; DECLARE v_c_lena BIGINT UNSIGNED; DECLARE v_l_1 BIGINT UNSIGNED; DECLARE v_l_2 BIGINT UNSIGNED; DECLARE v_l_3 BIGINT UNSIGNED; DECLARE v_l_4 BIGINT UNSIGNED;
DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
START TRANSACTION;
SELECT COUNT(*),MIN(id) INTO v_count,v_course FROM courses WHERE learning_language='de' AND base_language='fa'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa course identity missing or not unique'; END IF;
SELECT COUNT(*),MIN(id) INTO v_count,v_level FROM levels WHERE course_id=v_course AND cefr_level='A1'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa A1 missing or not unique'; END IF;
SELECT COUNT(*),MIN(id) INTO v_count,v_module FROM modules WHERE level_id=v_level AND sort_order=1; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa module 1 missing or not unique'; END IF;
SELECT COUNT(*) INTO v_count FROM characters WHERE course_id=v_course AND name='Raha'; IF v_count=0 THEN INSERT INTO characters(course_id,name,gender,profile,metadata) VALUES(v_course,'Raha','female',JSON_OBJECT('role','زبان‌آموز و شخصیت اصلی','origin','Iran'),JSON_OBJECT('nativeV3',TRUE,'context','new arrival learning German in Berlin','originCountry','Iran')); END IF;
SELECT COUNT(*) INTO v_count FROM characters WHERE course_id=v_course AND name='Lena'; IF v_count=0 THEN INSERT INTO characters(course_id,name,gender,profile,metadata) VALUES(v_course,'Lena','female',JSON_OBJECT('role','دوست محلی رها'),JSON_OBJECT('nativeV3',TRUE,'context','Raha''s local friend in Berlin','originCountry','Germany')); END IF;
SELECT id INTO v_c_raha FROM characters WHERE course_id=v_course AND name='Raha' AND gender='female' LIMIT 1; SELECT id INTO v_c_lena FROM characters WHERE course_id=v_course AND name='Lena' AND gender='female' LIMIT 1;
SELECT COUNT(*),MIN(id) INTO v_count,v_chapter FROM chapters WHERE module_id=v_module AND sort_order=1;
IF v_count=0 THEN
INSERT INTO chapters(module_id,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES(v_module,'Hallo und Namen','سلام و نام','Raha erlebt ihre ersten kurzen, natürlichen Begegnungen in Berlin: begrüßen, den Namen sagen, nach dem Namen fragen und sich verabschieden.','رها اولین برخوردهای کوتاه و طبیعی خود را در برلین تجربه می‌کند: سلام کردن، گفتن نام، پرسیدن نام و خداحافظی.',4,1,1,1,'validated',JSON_OBJECT('series',1,'contractVersion','3.0.0','foundationRevision','3.2.0','qualityRevision','3.2.1'));
SET v_chapter=LAST_INSERT_ID();
INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES
(v_course,'Hallo','Hallo','interjection','سلام',1,JSON_OBJECT('cefr','A1','register','neutral-informal'),JSON_ARRAY('خداحافظ','ممنون','صبح بخیر'),'Hallo, Lena!','سلام لنا!','nova/audio/words/de-fa/753692ec36adb4c794c973945eb2a99c1649703ea6f76bf259abb4fb838e013e.mp3',NULL,JSON_OBJECT('sourceSeries',1,'definitionComplete',TRUE)),
(v_course,'Guten Morgen','Guten Morgen','chunk','صبح بخیر',1,JSON_OBJECT('cefr','A1','time','morning'),JSON_ARRAY('شب بخیر','خداحافظ','ممنون'),'Guten Morgen, Raha!','صبح بخیر رها!','nova/audio/words/de-fa/c872cd6d08e13b1c0d98910bb0b732c34c57aa770221667099dc0076af79c388.mp3',NULL,JSON_OBJECT('sourceSeries',1,'definitionComplete',TRUE)),
(v_course,'Tschüss','Tschüss','interjection','خداحافظ',1,JSON_OBJECT('cefr','A1','register','informal'),JSON_ARRAY('سلام','ممنون','خوش آمدی'),'Tschüss, Lena!','خداحافظ لنا!','nova/audio/words/de-fa/ae04312b91230acc75758bd35f9494d969718c47d62d16993902e01a83abd6f8.mp3',NULL,JSON_OBJECT('sourceSeries',1,'definitionComplete',TRUE)),
(v_course,'heißen','heißen','verb','نام داشتن؛ اسم ... بودن',1,JSON_OBJECT('cefr','A1','pattern','ich heiße / du heißt'),JSON_ARRAY('آمدن','صحبت کردن','زندگی کردن'),'Ich heiße Raha.','اسم من رهاست.','nova/audio/words/de-fa/d291857f6b4bf46279355394bf9394ead82239e293ab38596bff32a0d7078792.mp3',NULL,JSON_OBJECT('sourceSeries',1,'definitionComplete',TRUE)),
(v_course,'ich','ich','pronoun','من',1,JSON_OBJECT('cefr','A1','person','1sg'),JSON_ARRAY('تو','او','ما'),'Ich heiße Raha.','اسم من رهاست.','nova/audio/words/de-fa/84c92d8abf326bdb52f1fc6cd6856c41ae9bc1ef4f6056c2672e3d9d301782e1.mp3',NULL,JSON_OBJECT('sourceSeries',1,'definitionComplete',TRUE)),
(v_course,'du','du','pronoun','تو',1,JSON_OBJECT('cefr','A1','person','2sg','register','informal'),JSON_ARRAY('من','او','شما رسمی'),'Wie heißt du?','اسمت چیه؟','nova/audio/words/de-fa/601b2c2473811afea7864a21e4b965a970afa4ce9eaf85dbdf01414bca66c12c.mp3',NULL,JSON_OBJECT('sourceSeries',1,'definitionComplete',TRUE));
INSERT INTO sem_learning_units(course_id,unit_type,unit_key,display_form,translation,description_fa,cefr_level,difficulty,data,metadata) VALUES
(v_course,'word_sense','de:a1:hallo:greeting','Hallo','سلام','سلام روزمره و خنثی برای شروع یک برخورد کوتاه','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),(v_course,'chunk','de:a1:guten-morgen','Guten Morgen','صبح بخیر','سلام رایج در صبح','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),(v_course,'chunk','de:a1:ich-heisse','Ich heiße ...','اسم من ... است','الگوی اصلی معرفی نام','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),(v_course,'chunk','de:a1:wie-heisst-du','Wie heißt du?','اسمت چیه؟','پرسیدن نام با du در گفتگوی غیررسمی','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),(v_course,'chunk','de:a1:freut-mich','Freut mich.','از آشنایی با تو خوشحالم','واکنش کوتاه و طبیعی بعد از معرفی','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),(v_course,'pronunciation','de:a1:pron:h','h am Wortanfang','صدای h در ابتدای واژه','برای فارسی‌زبان: h در Hallo شنیده و تولید شود و حذف نشود.','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),(v_course,'can_do','de:a1:can:greet-name','Begrüßen und den Namen sagen','سلام کردن و گفتن نام','شروع و پایان یک آشنایی خیلی کوتاه و گفتن نام','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)) ON DUPLICATE KEY UPDATE display_form=VALUES(display_form),translation=VALUES(translation),description_fa=VALUES(description_fa);
INSERT IGNORE INTO sem_learning_unit_words(learning_unit_id,word_id,sort_order,component_role,metadata) SELECT lu.id,w.id,1,'head',JSON_OBJECT('series',1) FROM sem_learning_units lu JOIN words w ON w.course_id=v_course AND w.display_form='Hallo' WHERE lu.course_id=v_course AND lu.unit_key='de:a1:hallo:greeting' LIMIT 1;
INSERT INTO sem_curriculum_outcomes(course_id,cefr_level,outcome_key,outcome_type,title,description_fa,required,status,evidence,metadata) VALUES(v_course,'A1','can_do:greet_name','can_do','Begrüßen und Namen nennen','سلام و گفتن نام',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)),(v_course,'A1','pron:word_initial_h','pronunciation','h am Wortanfang','شنیدن و تولید h ابتدای واژه',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)),(v_course,'A1','reading:short_identity','reading','Kurze Identität lesen','خواندن معرفی کوتاه',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)),(v_course,'A1','listening:basic_greeting','listening','Begrüßung verstehen','فهم سلام و معرفی نام',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)) ON DUPLICATE KEY UPDATE status='in_progress';
INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES
(v_chapter,v_c_lena,v_c_raha,'Erstes Hallo','اولین سلام','Lena trifft Raha zum ersten Mal im Hausflur.','لنا برای اولین بار رها را در راهرو می‌بیند.','story','berlin_new_start',1,1,420,1,'validated',JSON_OBJECT('pedagogicalRole','exposure')),
(v_chapter,v_c_lena,v_c_raha,'Guten Morgen','صبح بخیر','Am nächsten Morgen begegnen sie sich wieder; Lena fragt nach Rahas Namen, weil die erste Begegnung kurz war.','صبح روز بعد دوباره همدیگر را می‌بینند؛ لنا چون دیدار اول کوتاه بوده نام رها را دوباره می‌پرسد.','story','berlin_new_start',2,1,420,2,'validated',JSON_OBJECT('pedagogicalRole','explicit_form')),
(v_chapter,v_c_lena,v_c_raha,'Kurz üben','تمرین کوتاه','Lena und Raha üben eine Mini-Begegnung; die Antworten werden zunehmend aus dem Gedächtnis abgerufen.','لنا و رها یک آشنایی کوتاه را تمرین می‌کنند و پاسخ‌ها کم‌کم از حافظه بازیابی می‌شوند.','story','berlin_new_start',3,1,420,3,'validated',JSON_OBJECT('pedagogicalRole','retrieval')),
(v_chapter,v_c_lena,v_c_raha,'Bereit für ein Treffen','آماده یک دیدار','Vor einem Treffen probt Raha nur kurz mit Lena; die eigentliche Meisterschaft wird danach in neuen Situationen geprüft.','رها پیش از یک دیدار فقط کوتاه با لنا تمرین می‌کند و سپس در موقعیت‌های تازه مستقلا سنجیده می‌شود.','story','berlin_new_start',4,1,480,4,'validated',JSON_OBJECT('pedagogicalRole','mastery'));
SELECT id INTO v_l_1 FROM lessons WHERE chapter_id=v_chapter AND sort_order=1 LIMIT 1; SELECT id INTO v_l_2 FROM lessons WHERE chapter_id=v_chapter AND sort_order=2 LIMIT 1; SELECT id INTO v_l_3 FROM lessons WHERE chapter_id=v_chapter AND sort_order=3 LIMIT 1; SELECT id INTO v_l_4 FROM lessons WHERE chapter_id=v_chapter AND sort_order=4 LIMIT 1;
INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,metadata) VALUES
(v_l_1,v_c_lena,1,'character','Hallo! Ich bin Lena.','سلام! من لنا هستم.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t01.mp3',NULL,NULL,NULL,JSON_ARRAY('Hallo','Ich','bin','Lena'),JSON_OBJECT('series',1)),(v_l_1,v_c_raha,2,'learner','Hallo! Ich bin Raha.','سلام! من رها هستم.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t02.mp3',NULL,'Hallo! Ich bin Raha.',JSON_ARRAY('Hallo! Ich bin Raha.','Hallo, ich bin Raha.'),JSON_ARRAY('Hallo','Ich','bin','Raha'),JSON_OBJECT('series',1)),(v_l_1,v_c_lena,3,'character','Freut mich, Raha.','از آشنایی با تو خوشحالم، رها.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t03.mp3',NULL,NULL,NULL,JSON_ARRAY('Freut','mich','Raha'),JSON_OBJECT('series',1)),(v_l_1,v_c_raha,4,'learner','Freut mich auch.','من هم خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t04.mp3',NULL,'Freut mich auch.',JSON_ARRAY('Freut mich auch.','Mich auch.'),JSON_ARRAY('Freut','mich','auch'),JSON_OBJECT('series',1)),(v_l_1,v_c_lena,5,'character','Willkommen in Berlin!','به برلین خوش آمدی!',1,'nova/audio/turns/de-fa/A1/s0001/l01/t05.mp3',NULL,NULL,NULL,JSON_ARRAY('Willkommen','in','Berlin'),JSON_OBJECT('series',1)),(v_l_1,v_c_raha,6,'learner','Danke!','ممنون!',1,'nova/audio/turns/de-fa/A1/s0001/l01/t06.mp3',NULL,'Danke!',JSON_ARRAY('Danke!','Vielen Dank!'),JSON_ARRAY('Danke'),JSON_OBJECT('series',1)),(v_l_1,v_c_lena,7,'character','Bis später, Raha!','بعدا می‌بینمت، رها!',1,'nova/audio/turns/de-fa/A1/s0001/l01/t07.mp3',NULL,NULL,NULL,JSON_ARRAY('Bis','später','Raha'),JSON_OBJECT('series',1)),(v_l_1,v_c_raha,8,'learner','Tschüss, Lena!','خداحافظ، لنا!',1,'nova/audio/turns/de-fa/A1/s0001/l01/t08.mp3',NULL,'Tschüss, Lena!',JSON_ARRAY('Tschüss, Lena!','Bis später, Lena!'),JSON_ARRAY('Tschüss','Lena'),JSON_OBJECT('series',1));
INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,metadata) VALUES
(v_l_2,v_c_lena,1,'character','Guten Morgen, Raha!','صبح بخیر رها!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t01.mp3',NULL,NULL,NULL,JSON_ARRAY('Guten','Morgen','Raha'),JSON_OBJECT('series',1)),(v_l_2,v_c_raha,2,'learner','Guten Morgen, Lena!','صبح بخیر لنا!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t02.mp3',NULL,'Guten Morgen, Lena!',JSON_ARRAY('Guten Morgen, Lena!','Guten Morgen!'),JSON_ARRAY('Guten','Morgen','Lena'),JSON_OBJECT('series',1)),(v_l_2,v_c_lena,3,'character','Wie heißt du noch mal?','اسمت دوباره چی بود؟',1,'nova/audio/turns/de-fa/A1/s0001/l02/t03.mp3',NULL,NULL,NULL,JSON_ARRAY('Wie','heißt','du','noch','mal'),JSON_OBJECT('series',1)),(v_l_2,v_c_raha,4,'learner','Ich heiße Raha.','اسم من رهاست.',1,'nova/audio/turns/de-fa/A1/s0001/l02/t04.mp3',NULL,'Ich heiße Raha.',JSON_ARRAY('Ich heiße Raha.','Ich bin Raha.'),JSON_ARRAY('Ich','heiße','Raha'),JSON_OBJECT('series',1)),(v_l_2,v_c_lena,5,'character','Raha, genau. Danke!','رها، درسته. ممنون!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t05.mp3',NULL,NULL,NULL,JSON_ARRAY('Raha','genau','Danke'),JSON_OBJECT('series',1)),(v_l_2,v_c_raha,6,'learner','Gern.','خواهش می‌کنم.',1,'nova/audio/turns/de-fa/A1/s0001/l02/t06.mp3',NULL,'Gern.',JSON_ARRAY('Gern.','Ja, gern.'),JSON_ARRAY('Gern'),JSON_OBJECT('series',1)),(v_l_2,v_c_lena,7,'character','Bis später!','بعدا می‌بینمت!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t07.mp3',NULL,NULL,NULL,JSON_ARRAY('Bis','später'),JSON_OBJECT('series',1)),(v_l_2,v_c_raha,8,'learner','Tschüss!','خداحافظ!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t08.mp3',NULL,'Tschüss!',JSON_ARRAY('Tschüss!','Bis später!'),JSON_ARRAY('Tschüss'),JSON_OBJECT('series',1));
INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,metadata) VALUES
(v_l_3,v_c_lena,1,'character','Wir üben kurz. Hallo! Wie heißt du?','یک تمرین کوتاه. سلام! اسمت چیه؟',1,'nova/audio/turns/de-fa/A1/s0001/l03/t01.mp3',NULL,NULL,NULL,JSON_ARRAY('Wir','üben','kurz','Hallo','Wie','heißt','du'),JSON_OBJECT('series',1)),(v_l_3,v_c_raha,2,'learner','Hallo! Ich heiße Raha. Und du?','سلام! اسم من رهاست. تو چی؟',1,'nova/audio/turns/de-fa/A1/s0001/l03/t02.mp3',NULL,'Hallo! Ich heiße Raha. Und du?',JSON_ARRAY('Ich heiße Raha. Und du?','Hallo, ich bin Raha. Und du?'),JSON_ARRAY('Hallo','Ich','heiße','Raha','Und','du'),JSON_OBJECT('series',1)),(v_l_3,v_c_lena,3,'character','Ich heiße Lena.','اسم من لناست.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t03.mp3',NULL,NULL,NULL,JSON_ARRAY('Ich','heiße','Lena'),JSON_OBJECT('series',1)),(v_l_3,v_c_raha,4,'learner','Freut mich, Lena.','از آشنایی با تو خوشحالم، لنا.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t04.mp3',NULL,'Freut mich, Lena.',JSON_ARRAY('Freut mich, Lena.','Freut mich.'),JSON_ARRAY('Freut','mich','Lena'),JSON_OBJECT('series',1)),(v_l_3,v_c_lena,5,'character','Freut mich auch.','من هم خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t05.mp3',NULL,NULL,NULL,JSON_ARRAY('Freut','mich','auch'),JSON_OBJECT('series',1)),(v_l_3,v_c_raha,6,'learner','Danke.','ممنون.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t06.mp3',NULL,'Danke.',JSON_ARRAY('Danke.','Vielen Dank.'),JSON_ARRAY('Danke'),JSON_OBJECT('series',1)),(v_l_3,v_c_lena,7,'character','Gut. Bis später!','خوبه. بعدا می‌بینمت!',1,'nova/audio/turns/de-fa/A1/s0001/l03/t07.mp3',NULL,NULL,NULL,JSON_ARRAY('Gut','Bis','später'),JSON_OBJECT('series',1)),(v_l_3,v_c_raha,8,'learner','Tschüss, Lena!','خداحافظ، لنا!',1,'nova/audio/turns/de-fa/A1/s0001/l03/t08.mp3',NULL,'Tschüss, Lena!',JSON_ARRAY('Tschüss, Lena!','Bis später, Lena!'),JSON_ARRAY('Tschüss','Lena'),JSON_OBJECT('series',1));
INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,metadata) VALUES
(v_l_4,v_c_lena,1,'character','Bereit für das Treffen?','برای دیدار آماده‌ای؟',1,'nova/audio/turns/de-fa/A1/s0001/l04/t01.mp3',NULL,NULL,NULL,JSON_ARRAY('Bereit','für','das','Treffen'),JSON_OBJECT('series',1)),(v_l_4,v_c_raha,2,'learner','Ja.','بله.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t02.mp3',NULL,'Ja.',JSON_ARRAY('Ja.','Ja, bereit.'),JSON_ARRAY('Ja'),JSON_OBJECT('series',1)),(v_l_4,v_c_lena,3,'character','Dann: Guten Morgen!','پس: صبح بخیر!',1,'nova/audio/turns/de-fa/A1/s0001/l04/t03.mp3',NULL,NULL,NULL,JSON_ARRAY('Dann','Guten','Morgen'),JSON_OBJECT('series',1)),(v_l_4,v_c_raha,4,'learner','Guten Morgen! Ich heiße Raha.','صبح بخیر! اسم من رهاست.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t04.mp3',NULL,'Guten Morgen! Ich heiße Raha.',JSON_ARRAY('Guten Morgen! Ich heiße Raha.','Hallo! Ich bin Raha.'),JSON_ARRAY('Guten','Morgen','Ich','heiße','Raha'),JSON_OBJECT('series',1)),(v_l_4,v_c_lena,5,'character','Freut mich.','از آشنایی با تو خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t05.mp3',NULL,NULL,NULL,JSON_ARRAY('Freut','mich'),JSON_OBJECT('series',1)),(v_l_4,v_c_raha,6,'learner','Freut mich auch.','من هم خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t06.mp3',NULL,'Freut mich auch.',JSON_ARRAY('Freut mich auch.','Mich auch.'),JSON_ARRAY('Freut','mich','auch'),JSON_OBJECT('series',1)),(v_l_4,v_c_lena,7,'character','Viel Erfolg!','موفق باشی!',1,'nova/audio/turns/de-fa/A1/s0001/l04/t07.mp3',NULL,NULL,NULL,JSON_ARRAY('Viel','Erfolg'),JSON_OBJECT('series',1)),(v_l_4,v_c_raha,8,'learner','Danke, Lena!','ممنون، لنا!',1,'nova/audio/turns/de-fa/A1/s0001/l04/t08.mp3',NULL,'Danke, Lena!',JSON_ARRAY('Danke, Lena!','Vielen Dank, Lena!'),JSON_ARRAY('Danke','Lena'),JSON_OBJECT('series',1));
INSERT INTO activities(lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
(v_l_1,'listen',1,'Hallo! Ich bin Lena.','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'new_word',2,'Hallo','معنی و کاربرد سلام را ببین.',1,CAST('{"mode":"word_teach","unit_key":"de:a1:hallo:greeting","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'pronunciation',3,'Hallo','h ابتدای Hallo را بشنو، توجه کن و بعد تولید کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'speak',4,'Hallo!','واضح تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Hallo!","Hallo."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'new_word',5,'Ich heiße ...','الگوی معرفی نام را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-heisse","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'speak',6,'بگو اسمت رهاست.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اسمت رهاست.","accepted":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'meaning_choice',7,'Ich ___ Raha.','فعل مناسب را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heiße","kommst","sprichst"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'reading',8,'Lena: Hallo! Ich bin Lena.','متن کوتاه را بخوان.',1,CAST('{"mode":"reading_input","text":"Lena: Hallo! Ich bin Lena.","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'reading_comprehension',9,'Wie heißt sie?','نام را از متن پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Lena","Raha","Berlin"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'word_order',10,'Ich heiße Raha','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["Raha","heiße","Ich"],"answer":["Ich","heiße","Raha"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'speak',11,'یک نفر تازه سلام می‌کند.','طبیعی جواب بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"یک نفر تازه سلام می‌کند. طبیعی جواب بده.","accepted_intents":["Hallo!","Guten Morgen!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_1,'speak',12,'خودت را با نام معرفی کن.','بدون پاسخ نمایان بگو.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"خودت را با نام معرفی کن.","accepted_intents":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
INSERT INTO activities(lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
(v_l_2,'listen',1,'Guten Morgen!','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'new_word',2,'Guten Morgen','سلام مخصوص صبح را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:guten-morgen","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'pronunciation',3,'Hallo','h را دوباره بشنو و واضح تولید کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'speak',4,'Guten Morgen!','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Guten Morgen!","Guten Morgen."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'new_word',5,'Wie heißt du?','الگوی پرسیدن نام را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:wie-heisst-du","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'speak',6,'اسم طرف مقابل را بپرس.','از حافظه سوال را بساز.',1,CAST('{"mode":"recall_hidden","cue_fa":"اسم طرف مقابل را بپرس.","accepted":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'meaning_choice',7,'Wie ___ du?','شکل درست فعل را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heißt","heiße","spreche"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'reading',8,'Guten Morgen! Ich heiße Lena.','بخوان.',1,CAST('{"mode":"reading_input","text":"Guten Morgen! Ich heiße Lena.","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'reading_comprehension',9,'Wie heißt die Person?','نام را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["Lena","Raha","Morgen"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'word_order',10,'Wie heißt du','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["du","Wie","heißt"],"answer":["Wie","heißt","du"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'speak',11,'صبح با فرد تازه روبه‌رو شدی.','سلام مناسب بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"صبح با فرد تازه روبه‌رو شدی. سلام مناسب بده.","accepted_intents":["Guten Morgen!","Hallo!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_2,'speak',12,'او اسمش را نگفته.','اسمش را بپرس.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"طرف مقابل اسمش را نگفته؛ اسمش را بپرس.","accepted_intents":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
INSERT INTO activities(lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
(v_l_3,'listen',1,'Wie heißt du?','گوش کن و معنی را تشخیص بده.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'new_word',2,'Freut mich.','واکنش کوتاه بعد از معرفی را مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:freut-mich","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'pronunciation',3,'Hallo','h را بدون حذف تولید کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'speak',4,'بگو اسم من رهاست.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اسم من رهاست.","accepted":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'speak',5,'اسم فرد مقابل را بپرس.','از حافظه سوال کن.',1,CAST('{"mode":"recall_hidden","cue_fa":"اسم فرد مقابل را بپرس.","accepted":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'meaning_choice',6,'___! Ich heiße Raha.','سلام مناسب را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["Hallo","Tschüss","Danke"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'reading',7,'Hallo! Ich heiße Raha. Freut mich.','بخوان.',1,CAST('{"mode":"reading_input","text":"Hallo! Ich heiße Raha. Freut mich.","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'reading_comprehension',8,'Wie heißt die Person?','اطلاعات را استخراج کن.',1,CAST('{"mode":"reading_inference","options":["Raha","Lena","Berlin"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'word_order',9,'Ich heiße Raha','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["heiße","Raha","Ich"],"answer":["Ich","heiße","Raha"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'speak',10,'در آسانسور با فردی آشنا شو.','سلام و نام را مستقل بگو.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در آسانسور با فردی آشنا شو؛ سلام کن و نامت را بگو.","accepted_intents":["Hallo! Ich heiße Raha.","Guten Morgen! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'speak',11,'فرد مقابل خودش را معرفی کرد.','واکنش طبیعی بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"فرد مقابل خودش را معرفی کرد؛ واکنش طبیعی بده.","accepted_intents":["Freut mich.","Freut mich auch."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_3,'speak',12,'دیدار تمام شد.','خداحافظی کن.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"دیدار تمام شد؛ خداحافظی کن.","accepted_intents":["Tschüss!","Bis später!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
INSERT INTO activities(lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
(v_l_4,'listen',1,'Bereit für das Treffen?','فقط گوش کن و موقعیت را بفهم.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'reading',2,'Treffen – 10:00','اطلاعیه کوتاه را بخوان.',1,CAST('{"mode":"reading_input","text":"Treffen – 10:00","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'reading_comprehension',3,'Wann ist das Treffen?','زمان را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["10:00","18:00","morgen"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'new_word',4,'Ich heiße ...','الگوی معرفی را فقط مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-heisse","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'pronunciation',5,'Hallo','h را بشنو، توجه کن و واضح تولید کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'speak',6,'Hallo! Ich heiße Raha.','یک بار واضح تولید کن.',1,CAST('{"mode":"repeat_visible","accepted":["Hallo! Ich heiße Raha.","Hallo! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'speak',7,'در کلاس با فرد تازه روبه‌رو می‌شوی.','بدون cue آلمانی سلام و معرفی کن.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در کلاس با فرد تازه روبه‌رو می‌شوی؛ سلام و معرفی کن.","accepted_intents":["Hallo! Ich heiße Raha.","Guten Morgen! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'speak',8,'او اسمش را نگفته.','اسمش را مستقل بپرس.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"او اسمش را نگفته؛ اسمش را مستقل بپرس.","accepted_intents":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'meaning_choice',9,'Ich ___ Raha.','انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heiße","heißt","kommst"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'word_order',10,'Guten Morgen','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["Morgen","Guten"],"answer":["Guten","Morgen"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'speak',11,'بعد از معرفی طرف مقابل واکنش نشان بده.','پاسخ طبیعی بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بعد از معرفی طرف مقابل واکنش نشان بده.","accepted_intents":["Freut mich.","Freut mich auch."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),(v_l_4,'speak',12,'بدون هیچ جمله آلمانی کمکی یک آشنایی کوتاه بساز.','سلام، نام، واکنش و خداحافظی را ترکیب کن.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بدون هیچ جمله آلمانی کمکی یک آشنایی کوتاه بساز: سلام، نام، واکنش و خداحافظی.","accepted_intents":["Hallo! Ich heiße Raha. Freut mich. Tschüss!","Guten Morgen! Ich bin Raha. Freut mich. Bis später!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
INSERT IGNORE INTO sem_lesson_learning_units(lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key IN('de:a1:hallo:greeting','de:a1:guten-morgen','de:a1:ich-heisse','de:a1:wie-heisst-du','de:a1:freut-mich','de:a1:pron:h','de:a1:can:greet-name');
INSERT IGNORE INTO sem_lesson_learning_units(lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key IN('de:a1:hallo:greeting','de:a1:guten-morgen','de:a1:ich-heisse','de:a1:wie-heisst-du','de:a1:freut-mich','de:a1:pron:h','de:a1:can:greet-name');
INSERT IGNORE INTO sem_turn_learning_units(turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:can:greet-name' WHERE t.lesson_id=v_l_4 AND t.sort_order=4 LIMIT 1;
INSERT IGNORE INTO sem_review_obligations(course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,lu.id,v_chapter,1+o.off,o.off,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units lu JOIN(SELECT 1 off UNION ALL SELECT 2 UNION ALL SELECT 4 UNION ALL SELECT 8 UNION ALL SELECT 16)o WHERE lu.course_id=v_course AND lu.unit_key IN('de:a1:hallo:greeting','de:a1:guten-morgen','de:a1:ich-heisse','de:a1:wie-heisst-du','de:a1:freut-mich','de:a1:pron:h','de:a1:can:greet-name');
END IF;
COMMIT;
END$$
DELIMITER ;
CALL nova_de_v32_s0001();
DROP PROCEDURE IF EXISTS nova_de_v32_s0001;
