-- SERIES 1
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS nova_de_v32_s0001;
DELIMITER $$
CREATE PROCEDURE nova_de_v32_s0001()
BEGIN
  DECLARE v_count INT DEFAULT 0;
  DECLARE v_course BIGINT UNSIGNED;
  DECLARE v_level BIGINT UNSIGNED;
  DECLARE v_module BIGINT UNSIGNED;
  DECLARE v_chapter BIGINT UNSIGNED;
  DECLARE v_c_raha BIGINT UNSIGNED;
  DECLARE v_c_lena BIGINT UNSIGNED;
  DECLARE v_l_1 BIGINT UNSIGNED;
  DECLARE v_l_2 BIGINT UNSIGNED;
  DECLARE v_l_3 BIGINT UNSIGNED;
  DECLARE v_l_4 BIGINT UNSIGNED;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;
  SELECT COUNT(*),MIN(id) INTO v_count,v_course FROM courses WHERE learning_language='de' AND base_language='fa';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa course identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_level FROM levels WHERE course_id=v_course AND cefr_level='A1';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa A1 missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_module FROM modules WHERE level_id=v_level AND sort_order=1;
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa module 1 missing or not unique'; END IF;
  SELECT COUNT(*) INTO v_count FROM characters WHERE course_id=v_course AND name='Raha';
  IF v_count=0 THEN INSERT INTO characters (course_id,name,gender,profile,metadata) VALUES (v_course,'Raha','female',JSON_OBJECT('origin','Iran'),JSON_OBJECT('nativeV3',TRUE)); END IF;
  SELECT COUNT(*) INTO v_count FROM characters WHERE course_id=v_course AND name='Lena';
  IF v_count=0 THEN INSERT INTO characters (course_id,name,gender,profile,metadata) VALUES (v_course,'Lena','female',JSON_OBJECT('city','Berlin'),JSON_OBJECT('nativeV3',TRUE)); END IF;
  SELECT id INTO v_c_raha FROM characters WHERE course_id=v_course AND name='Raha' AND gender='female' LIMIT 1;
  SELECT id INTO v_c_lena FROM characters WHERE course_id=v_course AND name='Lena' AND gender='female' LIMIT 1;
  SELECT COUNT(*),MIN(id) INTO v_count,v_chapter FROM chapters WHERE module_id=v_module AND sort_order=1;
  IF v_count=0 THEN
    INSERT INTO chapters (module_id,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_module,'Hallo und Namen','سلام و نام','Natürliche erste Begegnungen in Berlin.','اولین آشنایی‌های طبیعی در برلین.',4,1,1,1,'validated',JSON_OBJECT('series',1,'contractVersion','3.0.0','foundationRevision','3.2.0'));
    SET v_chapter=LAST_INSERT_ID();
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES
      (v_course,'Hallo','Hallo','interjection','سلام',1,CAST('{"cefr":"A1","series":1}' AS JSON),CAST('["سلام","نام","زبان"]' AS JSON),'Hallo, Lena!','سلام لنا!','nova/audio/words/de-fa/753692ec36adb4c794c973945eb2a99c1649703ea6f76bf259abb4fb838e013e.mp3',NULL,CAST('{"sourceSeries":1,"definitionComplete":true}' AS JSON)),
      (v_course,'Guten Morgen','Guten Morgen','chunk','صبح بخیر',1,CAST('{"cefr":"A1","series":1}' AS JSON),CAST('["سلام","نام","زبان"]' AS JSON),'Guten Morgen, Raha!','صبح بخیر رها!','nova/audio/words/de-fa/c872cd6d08e13b1c0d98910bb0b732c34c57aa770221667099dc0076af79c388.mp3',NULL,CAST('{"sourceSeries":1,"definitionComplete":true}' AS JSON)),
      (v_course,'Tschüss','Tschüss','interjection','خداحافظ',1,CAST('{"cefr":"A1","series":1}' AS JSON),CAST('["سلام","نام","زبان"]' AS JSON),'Tschüss, Lena!','خداحافظ لنا!','nova/audio/words/de-fa/ae04312b91230acc75758bd35f9494d969718c47d62d16993902e01a83abd6f8.mp3',NULL,CAST('{"sourceSeries":1,"definitionComplete":true}' AS JSON)),
      (v_course,'heißen','heißen','verb','نام داشتن',1,CAST('{"cefr":"A1","series":1}' AS JSON),CAST('["سلام","نام","زبان"]' AS JSON),'Ich heiße Raha.','اسم من رهاست.','nova/audio/words/de-fa/d291857f6b4bf46279355394bf9394ead82239e293ab38596bff32a0d7078792.mp3',NULL,CAST('{"sourceSeries":1,"definitionComplete":true}' AS JSON)),
      (v_course,'ich','ich','pronoun','من',1,CAST('{"cefr":"A1","series":1}' AS JSON),CAST('["سلام","نام","زبان"]' AS JSON),'Ich heiße Raha.','اسم من رهاست.','nova/audio/words/de-fa/84c92d8abf326bdb52f1fc6cd6856c41ae9bc1ef4f6056c2672e3d9d301782e1.mp3',NULL,CAST('{"sourceSeries":1,"definitionComplete":true}' AS JSON)),
      (v_course,'du','du','pronoun','تو',1,CAST('{"cefr":"A1","series":1}' AS JSON),CAST('["سلام","نام","زبان"]' AS JSON),'Wie heißt du?','اسمت چیه؟','nova/audio/words/de-fa/601b2c2473811afea7864a21e4b965a970afa4ce9eaf85dbdf01414bca66c12c.mp3',NULL,CAST('{"sourceSeries":1,"definitionComplete":true}' AS JSON));
    INSERT INTO sem_learning_units (course_id,unit_type,unit_key,display_form,translation,description_fa,cefr_level,difficulty,data,metadata) VALUES
      (v_course,'word_sense','de:a1:hallo:greeting','Hallo','سلام','سلام روزمره و خنثی','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),
      (v_course,'chunk','de:a1:guten-morgen','Guten Morgen','صبح بخیر','سلام مخصوص صبح','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),
      (v_course,'chunk','de:a1:ich-heisse','Ich heiße ...','اسم من ... است','الگوی طبیعی معرفی نام','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),
      (v_course,'chunk','de:a1:wie-heisst-du','Wie heißt du?','اسمت چیه؟','پرسیدن نام در گفتگوی غیررسمی','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),
      (v_course,'chunk','de:a1:freut-mich','Freut mich.','از آشنایی با تو خوشحالم','واکنش کوتاه و طبیعی هنگام آشنایی','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),
      (v_course,'pronunciation','de:a1:pron:h','h am Wortanfang','صدای h در ابتدای واژه','شنیدن و تولید h آلمانی برای فارسی‌زبان','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)),
      (v_course,'can_do','de:a1:can:greet-name','Begrüßen und den Namen sagen','سلام کردن و گفتن نام','سلام و معرفی نام در دیدار تازه','A1',1,JSON_OBJECT('series',1),JSON_OBJECT('series',1)) ON DUPLICATE KEY UPDATE display_form=VALUES(display_form),translation=VALUES(translation),description_fa=VALUES(description_fa);
    INSERT IGNORE INTO sem_learning_unit_words (learning_unit_id,word_id,sort_order,component_role,metadata) SELECT lu.id,w.id,1,'head',JSON_OBJECT('series',1) FROM sem_learning_units lu JOIN words w ON w.course_id=v_course AND w.display_form='Hallo' WHERE lu.course_id=v_course AND lu.unit_key='de:a1:hallo:greeting' LIMIT 1;
    INSERT INTO sem_curriculum_outcomes (course_id,cefr_level,outcome_key,outcome_type,title,description_fa,required,status,evidence,metadata) VALUES
      (v_course,'A1','can_do:greet_name','can_do','Begrüßen und Namen nennen','سلام و گفتن نام',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)),
      (v_course,'A1','pron:word_initial_h','pronunciation','h am Wortanfang','صدای h در ابتدای واژه',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)),
      (v_course,'A1','reading:short_identity','reading','Kurze Identität lesen','خواندن معرفی کوتاه',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)),
      (v_course,'A1','listening:basic_greeting','listening','Begrüßung verstehen','فهم سلام پایه',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('series',1)) ON DUPLICATE KEY UPDATE status='in_progress';
    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES
      (v_chapter,v_c_lena,v_c_raha,'Erstes Hallo','اولین سلام','Lena begegnet Raha im Hausflur.','لنا در راهرو با رها آشنا می‌شود.','story','berlin_new_start',1,1,420,1,'validated',JSON_OBJECT('pedagogicalRole','exposure')),
      (v_chapter,v_c_lena,v_c_raha,'Wie heißt du?','اسمت چیه؟','Raha übt Namen und passende Begrüßungen.','رها نام و سلام مناسب را تمرین می‌کند.','story','berlin_new_start',2,1,420,2,'validated',JSON_OBJECT('pedagogicalRole','explicit_form')),
      (v_chapter,v_c_lena,v_c_raha,'Noch einmal vorstellen','معرفی دوباره','Raha ruft Begrüßung und Namen ohne direkte Vorlage ab.','رها سلام و نام را بدون الگوی مستقیم بازیابی می‌کند.','story','berlin_new_start',3,1,420,3,'validated',JSON_OBJECT('pedagogicalRole','retrieval')),
      (v_chapter,v_c_lena,v_c_raha,'Im Café','در کافه','Raha stellt sich in einem neuen Kontext selbstständig vor.','رها در موقعیت تازه کافه مستقل معرفی می‌کند.','story','berlin_new_start',4,1,420,4,'validated',JSON_OBJECT('pedagogicalRole','mastery'));
    SELECT id INTO v_l_1 FROM lessons WHERE chapter_id=v_chapter AND sort_order=1 LIMIT 1;
    SELECT id INTO v_l_2 FROM lessons WHERE chapter_id=v_chapter AND sort_order=2 LIMIT 1;
    SELECT id INTO v_l_3 FROM lessons WHERE chapter_id=v_chapter AND sort_order=3 LIMIT 1;
    SELECT id INTO v_l_4 FROM lessons WHERE chapter_id=v_chapter AND sort_order=4 LIMIT 1;
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES
      (v_l_1,v_c_lena,1,'character','Hallo! Ich bin Lena.','سلام! من لنا هستم.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t01.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_1,v_c_raha,2,'learner','Hallo, Lena! Ich bin Raha.','سلام لنا! من رها هستم.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t02.mp3',NULL,'Hallo, Lena! Ich bin Raha.',CAST('["Hallo, Lena! Ich bin Raha.","Hallo! Ich bin Raha."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_1,v_c_lena,3,'character','Freut mich, Raha.','از آشنایی با تو خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t03.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_1,v_c_raha,4,'learner','Freut mich auch.','من هم خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t04.mp3',NULL,'Freut mich auch.',CAST('["Freut mich auch.","Mich auch."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_1,v_c_lena,5,'character','Wie heißt du?','اسمت چیه؟',1,'nova/audio/turns/de-fa/A1/s0001/l01/t05.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_1,v_c_raha,6,'learner','Ich heiße Raha.','اسم من رهاست.',1,'nova/audio/turns/de-fa/A1/s0001/l01/t06.mp3',NULL,'Ich heiße Raha.',CAST('["Ich heiße Raha.","Ich bin Raha."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_1,v_c_lena,7,'character','Willkommen in Berlin!','به برلین خوش آمدی!',1,'nova/audio/turns/de-fa/A1/s0001/l01/t07.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_1,v_c_raha,8,'learner','Danke!','ممنون!',1,'nova/audio/turns/de-fa/A1/s0001/l01/t08.mp3',NULL,'Danke!',CAST('["Danke!","Vielen Dank!"]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1));
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES
      (v_l_2,v_c_lena,1,'character','Guten Morgen, Raha!','صبح بخیر رها!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t01.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_2,v_c_raha,2,'learner','Guten Morgen, Lena!','صبح بخیر لنا!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t02.mp3',NULL,'Guten Morgen, Lena!',CAST('["Guten Morgen, Lena!","Guten Morgen!"]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_2,v_c_lena,3,'character','Wie heißt du noch mal?','اسمت دوباره چی بود؟',1,'nova/audio/turns/de-fa/A1/s0001/l02/t03.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_2,v_c_raha,4,'learner','Ich heiße Raha.','اسم من رهاست.',1,'nova/audio/turns/de-fa/A1/s0001/l02/t04.mp3',NULL,'Ich heiße Raha.',CAST('["Ich heiße Raha.","Ich bin Raha."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_2,v_c_lena,5,'character','Und ich heiße Lena.','و اسم من لناست.',1,'nova/audio/turns/de-fa/A1/s0001/l02/t05.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_2,v_c_raha,6,'learner','Ja, Lena.','بله، لنا.',1,'nova/audio/turns/de-fa/A1/s0001/l02/t06.mp3',NULL,'Ja, Lena.',CAST('["Ja, Lena.","Genau, Lena."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_2,v_c_lena,7,'character','Bis später!','بعدا می‌بینمت!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t07.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_2,v_c_raha,8,'learner','Tschüss!','خداحافظ!',1,'nova/audio/turns/de-fa/A1/s0001/l02/t08.mp3',NULL,'Tschüss!',CAST('["Tschüss!","Bis später!"]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1));
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES
      (v_l_3,v_c_lena,1,'character','Hallo! Wie heißt du?','سلام! اسمت چیه؟',1,'nova/audio/turns/de-fa/A1/s0001/l03/t01.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_3,v_c_raha,2,'learner','Ich heiße Raha. Und du?','اسم من رهاست. تو چی؟',1,'nova/audio/turns/de-fa/A1/s0001/l03/t02.mp3',NULL,'Ich heiße Raha. Und du?',CAST('["Ich heiße Raha. Und du?","Ich bin Raha. Und du?"]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_3,v_c_lena,3,'character','Ich heiße Lena.','اسم من لناست.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t03.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_3,v_c_raha,4,'learner','Freut mich, Lena.','از آشنایی با تو خوشحالم لنا.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t04.mp3',NULL,'Freut mich, Lena.',CAST('["Freut mich, Lena.","Freut mich."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_3,v_c_lena,5,'character','Freut mich auch.','من هم خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t05.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_3,v_c_raha,6,'learner','Danke.','ممنون.',1,'nova/audio/turns/de-fa/A1/s0001/l03/t06.mp3',NULL,'Danke.',CAST('["Danke.","Vielen Dank."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_3,v_c_lena,7,'character','Bis morgen, Raha!','تا فردا رها!',1,'nova/audio/turns/de-fa/A1/s0001/l03/t07.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_3,v_c_raha,8,'learner','Tschüss, Lena!','خداحافظ لنا!',1,'nova/audio/turns/de-fa/A1/s0001/l03/t08.mp3',NULL,'Tschüss, Lena!',CAST('["Tschüss, Lena!","Bis morgen, Lena!"]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1));
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES
      (v_l_4,v_c_lena,1,'character','Guten Morgen! Ich bin Lena aus dem Café.','صبح بخیر! من لنا از کافه هستم.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t01.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_4,v_c_raha,2,'learner','Hallo! Ich heiße Raha.','سلام! اسم من رهاست.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t02.mp3',NULL,'Hallo! Ich heiße Raha.',CAST('["Hallo! Ich heiße Raha.","Guten Morgen! Ich bin Raha."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_4,v_c_lena,3,'character','Freut mich. Wie heißt du genau?','خوشحالم. دقیقا اسمت چیه؟',1,'nova/audio/turns/de-fa/A1/s0001/l04/t03.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_4,v_c_raha,4,'learner','Raha. Ich heiße Raha.','رها. اسم من رهاست.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t04.mp3',NULL,'Raha. Ich heiße Raha.',CAST('["Raha. Ich heiße Raha.","Ich heiße Raha."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_4,v_c_lena,5,'character','Schön, dich kennenzulernen.','از آشنایی با تو خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t05.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_4,v_c_raha,6,'learner','Freut mich auch.','من هم خوشحالم.',1,'nova/audio/turns/de-fa/A1/s0001/l04/t06.mp3',NULL,'Freut mich auch.',CAST('["Freut mich auch.","Mich auch."]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_4,v_c_lena,7,'character','Dann bis später!','پس بعدا می‌بینمت!',1,'nova/audio/turns/de-fa/A1/s0001/l04/t07.mp3',NULL,NULL,NULL,JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1)),
      (v_l_4,v_c_raha,8,'learner','Tschüss!','خداحافظ!',1,'nova/audio/turns/de-fa/A1/s0001/l04/t08.mp3',NULL,'Tschüss!',CAST('["Tschüss!","Bis später!"]' AS JSON),JSON_ARRAY(),NULL,NULL,NULL,JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_1,'listen',1,NULL,NULL,'Hallo!','اول گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'new_word',2,NULL,NULL,'Hallo','معنی و کاربرد را ببین.',1,CAST('{"mode":"word_teach","unit_key":"de:a1:hallo:greeting","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'pronunciation',3,NULL,NULL,'Hallo','به صدای h در ابتدای واژه گوش کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'speak',4,NULL,NULL,'Hallo!','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Hallo!","Hallo."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'new_word',5,NULL,NULL,'Ich heiße ...','این عبارت را برای گفتن نام یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-heisse","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'speak',6,NULL,NULL,'بگو اسمت رهاست.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اسمت رهاست.","accepted":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'meaning_choice',7,NULL,NULL,'Ich ___ Raha.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heiße","kommst","sprichst"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'reading',8,NULL,NULL,'Lena: Hallo! Ich bin Lena.','متن آلمانی را بخوان.',1,CAST('{"mode":"reading_input","text":"Lena: Hallo! Ich bin Lena.","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'reading_comprehension',9,NULL,NULL,'Wie heißt sie?','نام را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Lena","Raha","Berlin"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'word_order',10,NULL,NULL,'Ich heiße Raha','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["Raha","heiße","Ich"],"answer":["Ich","heiße","Raha"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'speak',11,NULL,NULL,'یک نفر تازه به تو سلام می‌کند. جواب بده.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"یک نفر تازه به تو سلام می‌کند. جواب بده.","accepted_intents":["Hallo!","Guten Morgen!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_1,'speak',12,NULL,NULL,'خودت را با نام معرفی کن.','بدون دیدن پاسخ بگو.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"خودت را با نام معرفی کن.","accepted_intents":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_2,'listen',1,NULL,NULL,'Guten Morgen!','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'new_word',2,NULL,NULL,'Guten Morgen','عبارت صبح بخیر را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:guten-morgen","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'pronunciation',3,NULL,NULL,'Guten Morgen','روی تکیه واژه‌ها دقت کن.',1,CAST('{"mode":"sound_notice","target":"basic_word_stress","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'speak',4,NULL,NULL,'Guten Morgen!','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Guten Morgen!","Guten Morgen."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'new_word',5,NULL,NULL,'Wie heißt du?','الگوی پرسیدن نام را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:wie-heisst-du","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'speak',6,NULL,NULL,'از یک نفر اسمش را بپرس.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"از یک نفر اسمش را بپرس.","accepted":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'meaning_choice',7,NULL,NULL,'Wie ___ du?','جای خالی را کامل کن.',1,CAST('{"mode":"sentence_blank","options":["heißt","heiße","heißt du"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'reading',8,NULL,NULL,'Guten Morgen! Ich heiße Lena.','بخوان.',1,CAST('{"mode":"reading_input","text":"Guten Morgen! Ich heiße Lena.","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'reading_comprehension',9,NULL,NULL,'Wie heißt die Person?','نام را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["Lena","Raha","Morgen"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'word_order',10,NULL,NULL,'Wie heißt du','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["du","Wie","heißt"],"answer":["Wie","heißt","du"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'speak',11,NULL,NULL,'صبح است؛ سلام مناسب بده.','پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"صبح است؛ سلام مناسب بده.","accepted_intents":["Guten Morgen!","Hallo!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_2,'speak',12,NULL,NULL,'در پایان دیدار خداحافظی کن.','پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در پایان دیدار خداحافظی کن.","accepted_intents":["Tschüss!","Bis später!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_3,'listen',1,NULL,NULL,'Wie heißt du?','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'reading',2,NULL,NULL,'Hallo! Ich heiße Raha.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Hallo! Ich heiße Raha.","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'new_word',3,NULL,NULL,'Freut mich.','عبارت آشنایی را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:freut-mich","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'speak',4,NULL,NULL,'Freut mich.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Freut mich.","Freut mich!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'speak',5,NULL,NULL,'بگو اسم من رهاست.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اسم من رهاست.","accepted":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'speak',6,NULL,NULL,'اسم طرف مقابل را بپرس.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"اسم طرف مقابل را بپرس.","accepted":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'meaning_choice',7,NULL,NULL,'___! Ich heiße Raha.','انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["Hallo","Tschüss","Morgen"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'reading_comprehension',8,NULL,NULL,'Lena: Guten Morgen! Ich heiße Lena.','نام را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Lena","Raha","Berlin"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'word_order',9,NULL,NULL,'Ich heiße Raha','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["heiße","Raha","Ich"],"answer":["Ich","heiße","Raha"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'pronunciation',10,NULL,NULL,'heiße','به صدای h ابتدای بخش واژه دقت کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'speak',11,NULL,NULL,'در راهرو با همسایه تازه آشنا شو و نامت را بگو.','پاسخ مستقل بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در راهرو با همسایه تازه آشنا شو و نامت را بگو.","accepted_intents":["Hallo! Ich heiße Raha.","Guten Morgen! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_3,'speak',12,NULL,NULL,'بعد از معرفی، مودبانه واکنش نشان بده.','پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بعد از معرفی، مودبانه واکنش نشان بده.","accepted_intents":["Freut mich.","Freut mich auch."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_4,'listen',1,NULL,NULL,'Guten Morgen! Ich bin Lena aus dem Café.','گوش کن و موقعیت تازه را بفهم.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'reading',2,NULL,NULL,'Café Morgenstern – Lena','تابلو و نام را بخوان.',1,CAST('{"mode":"reading_input","text":"Café Morgenstern – Lena","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'reading_comprehension',3,NULL,NULL,'Wer arbeitet im Café?','از متن پاسخ بده.',1,CAST('{"mode":"reading_inference","options":["Lena","Raha","Berlin"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'new_word',4,NULL,NULL,'Ich heiße ...','الگوی معرفی را در موقعیت جدید مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-heisse","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'pronunciation',5,NULL,NULL,'Hallo','صدای h را بشنو و سپس تولید کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"none","scored":false}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'speak',6,NULL,NULL,'Hallo! Ich heiße Raha.','یک بار تولید کن.',1,CAST('{"mode":"repeat_visible","accepted":["Hallo! Ich heiße Raha.","Hallo, ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'speak',7,NULL,NULL,'در کافه، بدون cue آلمانی خودت را معرفی کن.','پاسخ مستقل بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در کافه، بدون cue آلمانی خودت را معرفی کن.","accepted_intents":["Hallo! Ich heiße Raha.","Guten Morgen! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'speak',8,NULL,NULL,'طرف مقابل اسمش را نگفت؛ اسمش را بپرس.','پاسخ مستقل بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"طرف مقابل اسمش را نگفت؛ اسمش را بپرس.","accepted_intents":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'meaning_choice',9,NULL,NULL,'Ich ___ Raha.','انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heiße","heißt","kommst"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'word_order',10,NULL,NULL,'Guten Morgen','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["Morgen","Guten"],"answer":["Guten","Morgen"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'speak',11,NULL,NULL,'دیدار تمام شد؛ خداحافظی مناسب کن.','پاسخ بده.',1,CAST('{"mode":"recall_hidden","cue_fa":"دیدار تمام شد؛ خداحافظی مناسب کن.","accepted":["Tschüss!","Bis später!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1)),
      (v_l_4,'speak',12,NULL,NULL,'سلام، معرفی نام و واکنش مودبانه را در یک پاسخ کوتاه ترکیب کن.','ترکیب مستقل بساز.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"سلام، معرفی نام و واکنش مودبانه را در یک پاسخ کوتاه ترکیب کن.","accepted_intents":["Hallo! Ich heiße Raha. Freut mich.","Guten Morgen! Ich bin Raha. Freut mich."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT('series',1));
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    INSERT IGNORE INTO sem_turn_learning_units (turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:hallo:greeting' WHERE t.lesson_id=v_l_4 AND t.sort_order=2 LIMIT 1;
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    INSERT IGNORE INTO sem_turn_learning_units (turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:guten-morgen' WHERE t.lesson_id=v_l_4 AND t.sort_order=2 LIMIT 1;
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    INSERT IGNORE INTO sem_turn_learning_units (turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:ich-heisse' WHERE t.lesson_id=v_l_4 AND t.sort_order=2 LIMIT 1;
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    INSERT IGNORE INTO sem_turn_learning_units (turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:wie-heisst-du' WHERE t.lesson_id=v_l_4 AND t.sort_order=2 LIMIT 1;
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    INSERT IGNORE INTO sem_turn_learning_units (turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:freut-mich' WHERE t.lesson_id=v_l_4 AND t.sort_order=2 LIMIT 1;
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:h';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:h';
    INSERT IGNORE INTO sem_turn_learning_units (turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:pron:h' WHERE t.lesson_id=v_l_4 AND t.sort_order=2 LIMIT 1;
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:h';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:h';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:h';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:h';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:h';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_1,id,'new',1,2,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:can:greet-name';
    INSERT IGNORE INTO sem_lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,evidence_activity_ids,metadata) SELECT v_l_4,id,'mastery',1,1,JSON_ARRAY(),JSON_OBJECT('series',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:can:greet-name';
    INSERT IGNORE INTO sem_turn_learning_units (turn_id,learning_unit_id,evidence_type,metadata) SELECT t.id,lu.id,'mastery',JSON_OBJECT('series',1) FROM turns t JOIN sem_learning_units lu ON lu.course_id=v_course AND lu.unit_key='de:a1:can:greet-name' WHERE t.lesson_id=v_l_4 AND t.sort_order=2 LIMIT 1;
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:can:greet-name';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:can:greet-name';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:can:greet-name';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:can:greet-name';
    INSERT IGNORE INTO sem_review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1) FROM sem_learning_units WHERE course_id=v_course AND unit_key='de:a1:can:greet-name';
  END IF;
  COMMIT;
END$$
DELIMITER ;
CALL nova_de_v32_s0001();
DROP PROCEDURE IF EXISTS nova_de_v32_s0001;
