SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS nova_de_v3_s001;
DELIMITER $$
CREATE PROCEDURE nova_de_v3_s001()
BEGIN
  DECLARE v_course BIGINT UNSIGNED;
  DECLARE v_level BIGINT UNSIGNED;
  DECLARE v_module BIGINT UNSIGNED;
  DECLARE v_chapter BIGINT UNSIGNED;
  DECLARE v_raha BIGINT UNSIGNED;
  DECLARE v_lena BIGINT UNSIGNED;
  DECLARE v_jonas BIGINT UNSIGNED;
  DECLARE v_l_1 BIGINT UNSIGNED;
  DECLARE v_l_2 BIGINT UNSIGNED;
  DECLARE v_l_3 BIGINT UNSIGNED;
  DECLARE v_l_4 BIGINT UNSIGNED;
  DECLARE v_u_hallo BIGINT UNSIGNED;
  DECLARE v_u_danke BIGINT UNSIGNED;
  DECLARE v_u_tschuss BIGINT UNSIGNED;
  DECLARE v_u_ichheisse BIGINT UNSIGNED;
  DECLARE v_u_wieheisst BIGINT UNSIGNED;
  DECLARE v_u_freut BIGINT UNSIGNED;
  DECLARE v_u_morgen BIGINT UNSIGNED;
  DECLARE v_u_grammar BIGINT UNSIGNED;
  DECLARE v_u_pron_h BIGINT UNSIGNED;
  DECLARE v_u_pron_q BIGINT UNSIGNED;
  DECLARE v_u_cando BIGINT UNSIGNED;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;

  SELECT MIN(id) INTO v_course FROM courses WHERE learning_language='de' AND base_language='fa';
  IF v_course IS NULL THEN
    INSERT INTO courses (learning_language,base_language,title,title_translation,description,description_translation,status,metadata) VALUES ('de','fa','Deutsch für Persischsprachige','آلمانی برای فارسی‌زبان‌ها','Outcome-driven German course from absolute zero.','دوره آلمانی نتیجه‌محور از صفر مطلق.','active',JSON_OBJECT('contractVersion','3.0.0','freshNativeV3',TRUE));
    SET v_course=LAST_INSERT_ID();
  END IF;
  SELECT MIN(id) INTO v_level FROM levels WHERE course_id=v_course AND cefr_level='A1';
  IF v_level IS NULL THEN
    INSERT INTO levels (course_id,cefr_level,title,title_translation,description,description_translation,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_course,'A1','A1 Grundlagen','پایه A1','German for immediate simple interactions from absolute zero.','آلمانی پایه برای نیازهای فوری و تعامل‌های بسیار ساده.',1,2,1,'active',JSON_OBJECT('completionMode','dynamic_outcome_mastery'));
    SET v_level=LAST_INSERT_ID();
  END IF;
  SELECT MIN(id) INTO v_module FROM modules WHERE level_id=v_level AND sort_order=1;
  IF v_module IS NULL THEN
    INSERT INTO modules (level_id,title,title_translation,description,description_translation,emoji,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_level,'Erste Begegnungen','اولین آشنایی‌ها','Greetings, names and first face-to-face interactions.','سلام، نام و اولین تعامل‌های رو‌در‌رو.','👋',1,2,1,'active',JSON_OBJECT('dynamic',TRUE));
    SET v_module=LAST_INSERT_ID();
  END IF;
  SELECT MIN(id) INTO v_raha FROM characters WHERE course_id=v_course AND name='Raha';
  IF v_raha IS NULL THEN INSERT INTO characters (course_id,name,gender,voice_key,profile,metadata) VALUES (v_course,'Raha','female','raha',JSON_OBJECT('role','learner','origin','Iran'),JSON_OBJECT('course','de-fa')); SET v_raha=LAST_INSERT_ID(); END IF;
  SELECT MIN(id) INTO v_lena FROM characters WHERE course_id=v_course AND name='Lena';
  IF v_lena IS NULL THEN INSERT INTO characters (course_id,name,gender,voice_key,profile,metadata) VALUES (v_course,'Lena','female','lena',JSON_OBJECT('role','guide','city','Berlin'),JSON_OBJECT('course','de-fa')); SET v_lena=LAST_INSERT_ID(); END IF;
  SELECT MIN(id) INTO v_jonas FROM characters WHERE course_id=v_course AND name='Jonas';
  IF v_jonas IS NULL THEN INSERT INTO characters (course_id,name,gender,voice_key,profile,metadata) VALUES (v_course,'Jonas','male','jonas',JSON_OBJECT('role','resident','city','Berlin'),JSON_OBJECT('course','de-fa')); SET v_jonas=LAST_INSERT_ID(); END IF;

  SELECT MIN(id) INTO v_chapter FROM chapters WHERE module_id=v_module AND sort_order=1;
  IF v_chapter IS NULL THEN
    INSERT INTO chapters (module_id,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_module,'Hallo, ich heiße Raha','سلام، من رها هستم','Raha arrives in Berlin and learns the smallest useful first-contact conversation: greeting, saying a name, asking a name and parting.','رها به برلین می‌رسد و کوتاه‌ترین گفت‌وگوی مفید برای آشنایی اول را یاد می‌گیرد: سلام، گفتن نام، پرسیدن نام و خداحافظی.',4,1,1,1,'validated',JSON_OBJECT('series',1,'contractVersion','3.0.0','level','A1','storyline','berlin_new_start'));
    SET v_chapter=LAST_INSERT_ID();

    INSERT INTO learning_units (course_id,unit_type,unit_key,display_form,translation,description_fa,cefr_level,difficulty,data,metadata) VALUES
    (v_course,'word_sense','de:a1:hallo:greeting','Hallo','سلام','سلام خنثی و رایج برای شروع تعامل','A1',1,CAST('{"pos":"interjection","sense":"greeting"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'word_sense','de:a1:danke:thanks','Danke','ممنون','تشکر کوتاه و طبیعی','A1',1,CAST('{"pos":"interjection","sense":"thanks"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'word_sense','de:a1:tschuss:parting','Tschüss','خداحافظ','خداحافظی غیررسمی و رایج','A1',1,CAST('{"pos":"interjection","sense":"parting"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'chunk','de:a1:ich-heisse','Ich heiße ...','من ... هستم / اسم من ... است','الگوی پایه و طبیعی برای گفتن نام','A1',1,CAST('{"slots":["name"],"function":"self_introduction"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'chunk','de:a1:wie-heisst-du','Wie heißt du?','اسمت چیست؟','پرسش پایه و غیررسمی برای نام طرف مقابل','A1',1,CAST('{"register":"informal","function":"ask_name"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'chunk','de:a1:freut-mich','Freut mich.','از آشنایی خوشحالم.','عبارت رایج پس از معرفی','A1',1,CAST('{"function":"meeting_response"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'chunk','de:a1:guten-morgen','Guten Morgen.','صبح بخیر.','سلام صبحگاهی','A1',1,CAST('{"function":"greeting","time":"morning"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'grammar','de:a1:grammar:ich-du-heissen','ich heiße / du heißt',NULL,'برای گفتن نام خودت «ich heiße» و برای پرسیدن نام طرف مقابل «Wie heißt du?» را فعلا به صورت دو الگوی آماده یاد بگیر.','A1',1,CAST('{"function":"name_patterns"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'pronunciation','de:a1:pron:initial-h','word-initial h',NULL,'در Hallo و heiße صدای h ابتدای واژه شنیده می‌شود؛ آن را حذف نکن.','A1',1,CAST('{"target":"word_initial_h","examples":["Hallo","heiße"]}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'pronunciation','de:a1:pron:question-intonation','Wie heißt du? — question intonation',NULL,'در پرسش کوتاه Wie heißt du? لحن پرسشی را از صدا تقلید کن.','A1',1,CAST('{"target":"question_vs_statement_intonation","example":"Wie heißt du?"}' AS JSON),JSON_OBJECT('series',1)),
    (v_course,'can_do','de:a1:can-do:greet-introduce','greet and introduce your name',NULL,'سلام کن، نامت را بگو، نام طرف مقابل را بپرس و کوتاه خداحافظی کن.','A1',1,CAST('{"curriculum":"سلام و خداحافظی و عبارات ادب پایه"}' AS JSON),JSON_OBJECT('series',1));
    SELECT id INTO v_u_hallo FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:hallo:greeting';
    SELECT id INTO v_u_danke FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:danke:thanks';
    SELECT id INTO v_u_tschuss FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:tschuss:parting';
    SELECT id INTO v_u_ichheisse FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-heisse';
    SELECT id INTO v_u_wieheisst FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:wie-heisst-du';
    SELECT id INTO v_u_freut FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:freut-mich';
    SELECT id INTO v_u_morgen FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:guten-morgen';
    SELECT id INTO v_u_grammar FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:grammar:ich-du-heissen';
    SELECT id INTO v_u_pron_h FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:initial-h';
    SELECT id INTO v_u_pron_q FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:question-intonation';
    SELECT id INTO v_u_cando FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:can-do:greet-introduce';

    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'Hallo','Hallo','interjection','سلام',1,NULL,CAST('["Tschüss","Danke"]' AS JSON),'Hallo!','سلام!',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='Hallo' AND display_form='Hallo' AND part_of_speech='interjection');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'danke','Danke','interjection','ممنون',1,NULL,CAST('["Hallo","Tschüss"]' AS JSON),'Danke!','ممنون!',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='danke' AND display_form='Danke' AND part_of_speech='interjection');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'Tschüss','Tschüss','interjection','خداحافظ',1,NULL,CAST('["Hallo","Danke"]' AS JSON),'Tschüss!','خداحافظ!',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='Tschüss' AND display_form='Tschüss' AND part_of_speech='interjection');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'heißen','heiße','verb','نام داشتن / نامیده شدن',1,NULL,CAST('["sein","kommen"]' AS JSON),'Ich heiße Raha.','من رها هستم.',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='heißen' AND display_form='heiße' AND part_of_speech='verb');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'ich','ich','pronoun','من',1,NULL,CAST('["du","wir"]' AS JSON),'Ich heiße Raha.','من رها هستم.',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='ich' AND display_form='ich' AND part_of_speech='pronoun');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'du','du','pronoun','تو',1,NULL,CAST('["ich","wir"]' AS JSON),'Wie heißt du?','اسمت چیست؟',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='du' AND display_form='du' AND part_of_speech='pronoun');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'wie','Wie','adverb','چطور / چگونه',1,NULL,CAST('["wo","was"]' AS JSON),'Wie heißt du?','اسمت چیست؟',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='wie' AND display_form='Wie' AND part_of_speech='adverb');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'Guten Morgen','Guten Morgen','chunk','صبح بخیر',1,NULL,CAST('["Gute Nacht","Tschüss"]' AS JSON),'Guten Morgen, Lena.','صبح بخیر، لنا.',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='Guten Morgen' AND display_form='Guten Morgen' AND part_of_speech='chunk');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'Freut mich','Freut mich','chunk','از آشنایی خوشحالم',1,NULL,CAST('["Danke","Bis später"]' AS JSON),'Freut mich, Raha.','رها، از آشنایی با تو خوشحالم.',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='Freut mich' AND display_form='Freut mich' AND part_of_speech='chunk');
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) SELECT v_course,'Bis später','Bis später','chunk','بعدا می‌بینمت',1,NULL,CAST('["Guten Morgen","Danke"]' AS JSON),'Bis später!','بعدا می‌بینمت!',JSON_OBJECT('series',1,'contractVersion','3.0.0') WHERE NOT EXISTS (SELECT 1 FROM words WHERE course_id=v_course AND lemma='Bis später' AND display_form='Bis später' AND part_of_speech='chunk');

    INSERT INTO curriculum_outcomes (course_id,cefr_level,outcome_key,outcome_type,title,description_fa,required,status,evidence,metadata) VALUES
    (v_course,'A1','can_do:greet_part','can_do','سلام و خداحافظی پایه','زبان‌آموز بتواند در یک موقعیت تازه سلام و خداحافظی کوتاه و طبیعی انجام دهد.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',1)),
    (v_course,'A1','can_do:introduce_name','can_do','معرفی نام','زبان‌آموز بتواند نام خود را بگوید و نام طرف مقابل را بپرسد.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',1)),
    (v_course,'A1','grammar:name_patterns','grammar','الگوهای نام با ich/du','زبان‌آموز تفاوت کاربرد «Ich heiße ...» و «Wie heißt du?» را در عمل تشخیص دهد.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',1)),
    (v_course,'A1','reading:short_identity','reading','خواندن معرفی بسیار کوتاه','زبان‌آموز بتواند نام را از یک پیام بسیار کوتاه آلمانی پیدا کند.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',1)),
    (v_course,'A1','listening:first_contact','listening','فهم گفت‌وگوی آشنایی خیلی کوتاه','زبان‌آموز سلام، نام و خداحافظی را در گفت‌وگوی آهسته تشخیص دهد.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',1)),
    (v_course,'A1','pron:initial_h','pronunciation','شنیدن و تولید h ابتدای واژه','زبان‌آموز h ابتدای Hallo و heiße را حذف نکند.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',1)),
    (v_course,'A1','pron:question_intonation','pronunciation','لحن پرسشی کوتاه','زبان‌آموز لحن پرسشی Wie heißt du? را از مدل صوتی تقلید کند.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',1));

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_lena,v_raha,'Ein erstes Hallo','اولین سلام','Lena greets Raha after arrival.','لنا بعد از رسیدن رها به او سلام می‌کند.','story','berlin_new_start',1,1,450,1,'validated',JSON_OBJECT('pedagogicalRole','exposure')); SET v_l_1=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
    (v_l_1,v_lena,1,'character','Hallo!','سلام!',1,NULL,NULL,JSON_ARRAY(JSON_OBJECT('surface','Hallo','lemma','hallo','pos','interjection')),JSON_OBJECT('series',1)),
    (v_l_1,v_raha,2,'learner','Hallo!','سلام!',1,'Hallo!',JSON_ARRAY('Hallo!','Guten Tag!'),JSON_ARRAY(JSON_OBJECT('surface','Hallo','lemma','hallo','pos','interjection')),JSON_OBJECT('series',1)),
    (v_l_1,v_lena,3,'character','Ich heiße Lena. Wie heißt du?','من لنا هستم. اسم تو چیست؟',1,NULL,NULL,JSON_ARRAY(JSON_OBJECT('surface','Ich','lemma','ich','pos','pronoun'),JSON_OBJECT('surface','heiße','lemma','heiße','pos','verb'),JSON_OBJECT('surface','Lena','lemma','lena','pos','proper_noun'),JSON_OBJECT('surface','Wie','lemma','wie','pos','adverb'),JSON_OBJECT('surface','heißt','lemma','heißt','pos','verb'),JSON_OBJECT('surface','du','lemma','du','pos','pronoun')),JSON_OBJECT('series',1)),
    (v_l_1,v_raha,4,'learner','Ich heiße Raha.','من رها هستم.',1,'Ich heiße Raha.',JSON_ARRAY('Ich heiße Raha.','Ich bin Raha.'),JSON_ARRAY(JSON_OBJECT('surface','Ich','lemma','ich','pos','pronoun'),JSON_OBJECT('surface','heiße','lemma','heiße','pos','verb'),JSON_OBJECT('surface','Raha','lemma','raha','pos','proper_noun')),JSON_OBJECT('series',1)),
    (v_l_1,v_lena,5,'character','Freut mich, Raha.','رها، از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_1,v_raha,6,'learner','Freut mich auch.','من هم از آشنایی خوشحالم.',1,'Freut mich auch.',JSON_ARRAY('Freut mich auch.','Mich auch.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_1,v_lena,7,'character','Willkommen in Berlin!','به برلین خوش آمدی!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_1,v_raha,8,'learner','Danke!','ممنون!',1,'Danke!',JSON_ARRAY('Danke!','Danke schön!'),JSON_ARRAY(),JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'listen',1,NULL,NULL,'Hallo!','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'chunk',2,NULL,NULL,'Hallo','این سلام را همراه معنی و موقعیت استفاده یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:hallo:greeting","translation_fa":"سلام","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'pronunciation',3,NULL,NULL,'Hallo','به h ابتدای واژه گوش کن و همان صدا را تقلید کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"speech","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'speak',4,NULL,NULL,'Hallo!','با صدای بلند تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Hallo!","Guten Tag!"],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'listen',5,NULL,NULL,'Ich heiße Lena. Wie heißt du?','اول جمله را کامل گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'chunk',6,NULL,NULL,'Ich heiße ...','این الگو را یک تکه برای گفتن نام یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-heisse","translation_fa":"من ... هستم / اسم من ... است","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'reading_comprehension',7,NULL,NULL,'Ich heiße Raha.','نکته را بخوان.',1,CAST('{"mode":"micro_grammar","explanation_fa":"برای معرفی نام خودت فعلا الگوی کامل «Ich heiße + نام» را استفاده کن. لازم نیست هنوز صرف فعل را حفظ کنی.","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'speak',8,NULL,NULL,'بگو اسمت رهاست.','بدون دیدن جواب پاسخ بده.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اسمت رهاست.","accepted":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'meaning_choice',9,NULL,NULL,'Ich ___ Raha.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heiße","heißt","Tschüss"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'reading',10,NULL,NULL,'Lena: Hallo! Ich heiße Lena.','پیام کوتاه را بخوان.',1,CAST('{"mode":"reading_input","text":"Lena: Hallo! Ich heiße Lena.","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'reading_comprehension',11,NULL,NULL,'Wer schreibt die Nachricht?','از روی متن نام درست را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["Lena","Raha","Berlin"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'word_order',12,NULL,NULL,'Ich heiße Raha','واژه‌ها را مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["Raha","heiße","Ich"],"answer":["Ich","heiße","Raha"],"input":"tap_tokens","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_1,'speak',13,NULL,NULL,'در اولین دیدار سلام کن و نامت را بگو.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در ایستگاه برای اولین بار با یک نفر روبه‌رو می‌شوی. سلام کن و نامت را بگو.","accepted_intents":["Hallo! Ich heiße Raha.","Hallo! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_lena,v_raha,'Wie heißt du?','اسمت چیست؟','Raha learns to say and ask a name.','رها گفتن و پرسیدن نام را تمرین می‌کند.','story','berlin_new_start',2,1,480,2,'validated',JSON_OBJECT('pedagogicalRole','explicit_form')); SET v_l_2=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
    (v_l_2,v_lena,1,'character','Guten Morgen, Raha.','صبح بخیر، رها.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_2,v_raha,2,'learner','Guten Morgen, Lena.','صبح بخیر، لنا.',1,'Guten Morgen, Lena.',JSON_ARRAY('Guten Morgen, Lena.','Guten Morgen!'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_2,v_lena,3,'character','Wie heißt du noch mal?','اسمت دوباره چی بود؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_2,v_raha,4,'learner','Ich heiße Raha.','من رها هستم.',1,'Ich heiße Raha.',JSON_ARRAY('Ich heiße Raha.','Ich bin Raha.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_2,v_lena,5,'character','Ah, Raha. Freut mich.','آهان، رها. از آشنایی خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_2,v_raha,6,'learner','Freut mich auch.','من هم از آشنایی خوشحالم.',1,'Freut mich auch.',JSON_ARRAY('Freut mich auch.','Mich auch.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_2,v_lena,7,'character','Bis später!','بعدا می‌بینمت!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_2,v_raha,8,'learner','Bis später!','بعدا می‌بینمت!',1,'Bis später!',JSON_ARRAY('Bis später!','Tschüss!'),JSON_ARRAY(),JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'listen',1,NULL,NULL,'Guten Morgen, Raha.','فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'chunk',2,NULL,NULL,'Guten Morgen.','سلام صبحگاهی را یک تکه یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:guten-morgen","translation_fa":"صبح بخیر.","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'listen',3,NULL,NULL,'Wie heißt du noch mal?','پرسش نام را گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'chunk',4,NULL,NULL,'Wie heißt du?','این پرسش را برای نام طرف مقابل یک تکه یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:wie-heisst-du","translation_fa":"اسمت چیست؟","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'reading_comprehension',5,NULL,NULL,'Ich heiße ... / Wie heißt du?','تفاوت دو الگو را ببین.',1,CAST('{"mode":"micro_grammar","explanation_fa":"«Ich heiße ...» برای گفتن نام خودت است. «Wie heißt du?» برای پرسیدن نام یک نفر در موقعیت غیررسمی است.","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'pronunciation',6,NULL,NULL,'Wie heißt du?','لحن پرسشی را گوش کن و تقلید کن.',1,CAST('{"mode":"stress_rhythm","target":"question_vs_statement_intonation","input":"speech","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'speak',7,NULL,NULL,'Wie heißt du?','با صدای بلند تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'meaning_choice',8,NULL,NULL,'Wie ___ du?','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heiße","heißt","heißen"],"answer_index":1,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'speak',9,NULL,NULL,'نام طرف مقابل را بپرس.','بدون دیدن جواب بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"نام طرف مقابل را بپرس.","accepted":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'reading',10,NULL,NULL,'Guten Morgen! Ich heiße Lena.','پیام را بخوان.',1,CAST('{"mode":"reading_input","text":"Guten Morgen! Ich heiße Lena.","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'reading_comprehension',11,NULL,NULL,'Was ist der Name?','نام داخل پیام را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Morgen","Lena","Berlin"],"answer_index":1,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'word_order',12,NULL,NULL,'Wie heißt du','واژه‌ها را مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["du","Wie","heißt"],"answer":["Wie","heißt","du"],"input":"tap_tokens","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_2,'speak',13,NULL,NULL,'در کلاس تازه نام نفر کناری را بپرس.','پرسش طبیعی بگو.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در کلاس تازه کنار یک نفر نشسته‌ای. مودبانه و غیررسمی نامش را بپرس.","accepted_intents":["Wie heißt du?","Hallo! Wie heißt du?"],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_lena,v_raha,'Freut mich','از آشنایی خوشحالم','Raha retrieves meeting and parting chunks.','رها عبارت‌های آشنایی و خداحافظی را بازیابی می‌کند.','story','berlin_new_start',3,1,510,3,'validated',JSON_OBJECT('pedagogicalRole','retrieval')); SET v_l_3=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
    (v_l_3,v_lena,1,'character','Hallo, ich bin Lena.','سلام، من لنا هستم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_3,v_raha,2,'learner','Hallo, ich bin Raha.','سلام، من رها هستم.',1,'Hallo, ich bin Raha.',JSON_ARRAY('Hallo, ich bin Raha.','Hallo, ich heiße Raha.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_3,v_lena,3,'character','Wie heißt du?','اسمت چیست؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_3,v_raha,4,'learner','Ich heiße Raha.','من رها هستم.',1,'Ich heiße Raha.',JSON_ARRAY('Ich heiße Raha.','Ich bin Raha.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_3,v_lena,5,'character','Freut mich, Raha.','رها، از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_3,v_raha,6,'learner','Freut mich auch.','من هم از آشنایی خوشحالم.',1,'Freut mich auch.',JSON_ARRAY('Freut mich auch.','Mich auch.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_3,v_lena,7,'character','Bis später, Raha.','بعدا می‌بینمت، رها.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_3,v_raha,8,'learner','Tschüss, Lena.','خداحافظ، لنا.',1,'Tschüss, Lena.',JSON_ARRAY('Tschüss, Lena.','Bis später, Lena.'),JSON_ARRAY(),JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'listen',1,NULL,NULL,'Freut mich, Raha.','فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'chunk',2,NULL,NULL,'Freut mich.','این عبارت را یک تکه یاد بگیر و کلمه‌به‌کلمه ترجمه نکن.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:freut-mich","translation_fa":"از آشنایی خوشحالم.","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'speak',3,NULL,NULL,'Freut mich auch.','با صدای بلند تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Freut mich auch.","Mich auch."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'listen',4,NULL,NULL,'Bis später!','خداحافظی کوتاه را گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'chunk',5,NULL,NULL,'Tschüss!','یک خداحافظی رایج و غیررسمی را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:tschuss:parting","translation_fa":"خداحافظ!","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'meaning_choice',6,NULL,NULL,'___, Lena!','گزینه مناسب برای خداحافظی را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["Tschüss","Hallo","Danke"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'speak',7,NULL,NULL,'بعد از معرفی بگو از آشنایی خوشحالی.','بدون دیدن جواب بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بعد از معرفی بگو از آشنایی خوشحالی.","accepted":["Freut mich.","Freut mich auch."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'reading',8,NULL,NULL,'Hallo! Ich heiße Raha. Tschüss!','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Hallo! Ich heiße Raha. Tschüss!","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'reading_comprehension',9,NULL,NULL,'Welche Funktion hat „Tschüss“?','کارکرد عبارت آخر را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["خداحافظی","پرسیدن نام","تشکر"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'pronunciation',10,NULL,NULL,'heiße','به h ابتدای heiße و صدای طبیعی کل واژه دقت کن.',1,CAST('{"mode":"sound_notice","target":"word_initial_h","input":"speech","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'word_order',11,NULL,NULL,'Freut mich auch','واژه‌ها را مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["auch","mich","Freut"],"answer":["Freut","mich","auch"],"input":"tap_tokens","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'speak',12,NULL,NULL,'بعد از آشنایی پاسخ کوتاه بده.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"کسی پس از معرفی می‌گوید «Freut mich.» پاسخ طبیعی و کوتاه بده.","accepted_intents":["Freut mich auch.","Mich auch."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_3,'speak',13,NULL,NULL,'گفت‌وگوی کوتاه را تمام کن.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"می‌خواهی از آشنای تازه جدا شوی و بعدا دوباره او را می‌بینی. خداحافظی کن.","accepted_intents":["Bis später!","Tschüss!"],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_jonas,v_raha,'Eine neue Person','یک آدم تازه','Raha uses the same language with Jonas, a new person.','رها همان زبان را با یوناس، فردی تازه، به کار می‌برد.','story','berlin_new_start',4,1,540,4,'validated',JSON_OBJECT('pedagogicalRole','mastery','masteryCheck',TRUE)); SET v_l_4=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
    (v_l_4,v_jonas,1,'character','Hallo! Ich bin Jonas.','سلام! من یوناس هستم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_4,v_raha,2,'learner','Hallo! Ich heiße Raha.','سلام! من رها هستم.',1,'Hallo! Ich heiße Raha.',JSON_ARRAY('Hallo! Ich heiße Raha.','Hallo! Ich bin Raha.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_4,v_jonas,3,'character','Freut mich, Raha.','رها، از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_4,v_raha,4,'learner','Freut mich auch.','من هم از آشنایی خوشحالم.',1,'Freut mich auch.',JSON_ARRAY('Freut mich auch.','Mich auch.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_4,v_jonas,5,'character','Wie heißt du noch mal?','اسمت دوباره چی بود؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_4,v_raha,6,'learner','Ich heiße Raha.','من رها هستم.',1,'Ich heiße Raha.',JSON_ARRAY('Ich heiße Raha.','Ich bin Raha.'),JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_4,v_jonas,7,'character','Bis später!','بعدا می‌بینمت!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT('series',1)),
    (v_l_4,v_raha,8,'learner','Tschüss!','خداحافظ!',1,'Tschüss!',JSON_ARRAY('Tschüss!','Bis später!'),JSON_ARRAY(),JSON_OBJECT('series',1));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'listen',1,NULL,NULL,'Hallo! Ich bin Jonas.','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'speak',2,NULL,NULL,'Hallo! Ich heiße Raha.','با صدای بلند بگو.',1,CAST('{"mode":"repeat_visible","accepted":["Hallo! Ich heiße Raha.","Hallo! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'speak',3,NULL,NULL,'به یک فرد تازه سلام کن و نامت را بگو.','بدون دیدن جواب پاسخ بده.',1,CAST('{"mode":"recall_hidden","cue_fa":"به یک فرد تازه سلام کن و نامت را بگو.","accepted":["Hallo! Ich heiße Raha.","Hallo! Ich bin Raha."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"mastery"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'listen',4,NULL,NULL,'Wie heißt du noch mal?','پرسش را گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'reading_comprehension',5,NULL,NULL,'Ich heiße ... / Wie heißt du?','دو الگوی نام را مرور کن.',1,CAST('{"mode":"micro_grammar","explanation_fa":"برای نام خودت «Ich heiße ...» و برای نام طرف مقابل «Wie heißt du?» را بازیابی کن. این دو الگو اکنون باید بدون ترجمه کلمه‌به‌کلمه قابل استفاده باشند.","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'meaning_choice',6,NULL,NULL,'Ich ___ Raha.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["heiße","heißt","wie"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'word_order',7,NULL,NULL,'Wie heißt du','واژه‌ها را مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["heißt","du","Wie"],"answer":["Wie","heißt","du"],"input":"tap_tokens","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'reading',8,NULL,NULL,'Jonas: Hallo! Ich bin Jonas. Wie heißt du?','پیام کوتاه را بخوان.',1,CAST('{"mode":"reading_input","text":"Jonas: Hallo! Ich bin Jonas. Wie heißt du?","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'reading_comprehension',9,NULL,NULL,'Was möchte Jonas wissen?','از روی متن هدف پرسش را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["نام تو","شماره تو","شهر تو"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'pronunciation',10,NULL,NULL,'Wie heißt du?','لحن پرسشی را یک بار دیگر تقلید کن.',1,CAST('{"mode":"stress_rhythm","target":"question_vs_statement_intonation","input":"speech","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'speak',11,NULL,NULL,'یک نفر می‌گوید «Freut mich, Raha.» پاسخ بده.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"یک فرد تازه پس از شنیدن نامت می‌گوید «Freut mich, Raha.» پاسخ طبیعی بده.","accepted_intents":["Freut mich auch.","Mich auch."],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"mastery"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'speak',12,NULL,NULL,'در یک موقعیت تازه نام طرف مقابل را بپرس.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در خوابگاه با همسایه تازه آشنا شده‌ای. بعد از سلام، نامش را بپرس.","accepted_intents":["Wie heißt du?","Hallo! Wie heißt du?"],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"mastery"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'speak',13,NULL,NULL,'گفت‌وگو را کوتاه تمام کن.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بعد از معرفی باید بروی. یک خداحافظی کوتاه و طبیعی بگو.","accepted_intents":["Tschüss!","Bis später!"],"input":"speech","scored":true}' AS JSON),CAST('{"phase":"mastery"}' AS JSON));
    INSERT INTO activities (lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES (v_l_4,'chunk',14,NULL,NULL,'Danke!','تشکر کوتاه را برای پاسخ به خوشامدگویی مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:danke:thanks","translation_fa":"ممنون!","input":"none","scored":false}' AS JSON),CAST('{"phase":"lesson"}' AS JSON));

    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,metadata) VALUES (v_l_1,v_u_hallo,'new',1,1,JSON_OBJECT('series',1)),(v_l_1,v_u_ichheisse,'new',1,1,JSON_OBJECT('series',1)),(v_l_1,v_u_freut,'new',1,1,JSON_OBJECT('series',1)),(v_l_1,v_u_pron_h,'new',1,1,JSON_OBJECT('series',1)),(v_l_1,v_u_cando,'new',1,1,JSON_OBJECT('series',1));
    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,metadata) VALUES (v_l_2,v_u_morgen,'new',1,1,JSON_OBJECT('series',1)),(v_l_2,v_u_wieheisst,'new',1,1,JSON_OBJECT('series',1)),(v_l_2,v_u_grammar,'new',1,1,JSON_OBJECT('series',1)),(v_l_2,v_u_pron_q,'new',1,1,JSON_OBJECT('series',1)),(v_l_2,v_u_cando,'review',1,1,JSON_OBJECT('series',1));
    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,metadata) VALUES (v_l_3,v_u_freut,'review',1,1,JSON_OBJECT('series',1)),(v_l_3,v_u_tschuss,'new',1,1,JSON_OBJECT('series',1)),(v_l_3,v_u_pron_h,'review',1,1,JSON_OBJECT('series',1)),(v_l_3,v_u_cando,'review',1,1,JSON_OBJECT('series',1));
    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,metadata) VALUES (v_l_4,v_u_hallo,'mastery',1,1,JSON_OBJECT('series',1)),(v_l_4,v_u_danke,'mastery',1,1,JSON_OBJECT('series',1)),(v_l_4,v_u_tschuss,'mastery',1,1,JSON_OBJECT('series',1)),(v_l_4,v_u_ichheisse,'mastery',1,1,JSON_OBJECT('series',1)),(v_l_4,v_u_wieheisst,'mastery',1,1,JSON_OBJECT('series',1)),(v_l_4,v_u_cando,'mastery',1,1,JSON_OBJECT('series',1));

    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,lu.id,v_chapter,2,1,'due',JSON_OBJECT('originSeries',1,'evidenceRequired',TRUE) FROM learning_units lu WHERE lu.course_id=v_course AND JSON_EXTRACT(lu.metadata,'$.series')=1 ON DUPLICATE KEY UPDATE due_series=VALUES(due_series),status='due';
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,lu.id,v_chapter,3,2,'due',JSON_OBJECT('originSeries',1,'evidenceRequired',TRUE) FROM learning_units lu WHERE lu.course_id=v_course AND JSON_EXTRACT(lu.metadata,'$.series')=1 ON DUPLICATE KEY UPDATE due_series=VALUES(due_series),status='due';
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,lu.id,v_chapter,5,4,'due',JSON_OBJECT('originSeries',1,'evidenceRequired',TRUE) FROM learning_units lu WHERE lu.course_id=v_course AND JSON_EXTRACT(lu.metadata,'$.series')=1 ON DUPLICATE KEY UPDATE due_series=VALUES(due_series),status='due';
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,lu.id,v_chapter,9,8,'due',JSON_OBJECT('originSeries',1,'evidenceRequired',TRUE) FROM learning_units lu WHERE lu.course_id=v_course AND JSON_EXTRACT(lu.metadata,'$.series')=1 ON DUPLICATE KEY UPDATE due_series=VALUES(due_series),status='due';
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,lu.id,v_chapter,17,16,'due',JSON_OBJECT('originSeries',1,'evidenceRequired',TRUE) FROM learning_units lu WHERE lu.course_id=v_course AND JSON_EXTRACT(lu.metadata,'$.series')=1 ON DUPLICATE KEY UPDATE due_series=VALUES(due_series),status='due';

    UPDATE curriculum_outcomes SET status='covered', evidence=JSON_ARRAY(JSON_OBJECT('series',1,'lesson',4,'type','mastery_transfer')) WHERE course_id=v_course AND cefr_level='A1' AND outcome_key IN ('can_do:greet_part','can_do:introduce_name','reading:short_identity','listening:first_contact','pron:initial_h','pron:question_intonation');
    UPDATE curriculum_outcomes SET status='in_progress', evidence=JSON_ARRAY(JSON_OBJECT('series',1,'lesson',2,'type','controlled_and_transfer')) WHERE course_id=v_course AND cefr_level='A1' AND outcome_key='grammar:name_patterns';
  END IF;
  COMMIT;
END$$
DELIMITER ;
CALL nova_de_v3_s001();
DROP PROCEDURE nova_de_v3_s001;
