-- English (en-US) C2 curriculum for Persian-speaking learners.
-- Mastery-level continuation after C1: implicit meaning, effortless precision,
-- rhetorical control, synthesis, mediation, idiomatic range and flexible register.

INSERT IGNORE INTO curriculum_units (
  course_id, target_language_id, cefr_level_id, skill_id, topic_id,
  slug, title, learning_objective, sort_order, expected_lessons, status, metadata
)
SELECT
  c.id, c.target_language_id, lvl.id, s.id, t.id,
  u.slug, u.title, u.objective, u.sort_order, 3, 'approved',
  JSON_OBJECT('can_do', u.can_do, 'level_design', 'C2 mastery: effortless precision, pragmatic inference, idiomatic range, rhetorical control, synthesis and mediation')
FROM (
  SELECT 10 sort_order,'communication' skill_slug,'simple-messages' topic_slug,'c2-implicit-stance' slug,'Implicit Stance & Fine-Grained Inference' title,'Infer nuanced stance, tacit assumptions and undertones while calibrating certainty.' objective,'I can recover layered stance without presenting interpretation as fact.' can_do
  UNION ALL SELECT 20,'communication','simple-messages','c2-layered-narrative','Layered Narrative & Reflective Control','Tell complex narratives with retrospective reframing, controlled digression and reflective perspective.','I can tell a layered story and control shifts in perspective and meaning.'
  UNION ALL SELECT 30,'communication','questions','c2-lexical-precision','Lexical Precision & Semantic Boundaries','Choose precise, idiomatic vocabulary by controlling connotation, collocation and semantic scope.','I can choose the narrowest natural expression for a complex meaning.'
  UNION ALL SELECT 40,'communication','questions','c2-strategic-ambiguity','Strategic Ambiguity & Interpretive Control','Analyze deliberate ambiguity, underspecification, interpretive flexibility and textual loopholes.','I can distinguish useful flexibility from strategically evasive ambiguity.'
  UNION ALL SELECT 50,'social','polite-language','c2-pragmatic-meaning','Pragmatic Meaning, Face & Intent','Interpret pragmatic force, face management, directness, deference and relationship-sensitive meaning.','I can understand what sophisticated language is doing socially, not only what it says literally.'
  UNION ALL SELECT 60,'communication','simple-messages','c2-evidential-reasoning','Evidential Reasoning & Degrees of Commitment','Match confidence to evidence quality, attribution, corroboration and explanatory warrant.','I can express exactly how strongly different evidence supports a claim.'
  UNION ALL SELECT 70,'communication','requests','c2-causal-complexity','Causal Complexity & Counterfactual Explanation','Reason about multifactorial causation, mechanisms, confounders, pathways and counterfactuals.','I can build and limit a sophisticated causal explanation.'
  UNION ALL SELECT 80,'communication','simple-messages','c2-argument-diagnostics','Argument Diagnostics & Hidden Premises','Diagnose premises, inference, burden of proof, fallacies and the strongest available rebuttal.','I can locate exactly where a complex argument succeeds or fails.'
  UNION ALL SELECT 90,'communication','simple-messages','c2-qualification-scope','Qualification, Scope & Exception Handling','Control generalization through scope, qualifiers, boundary cases, contingencies and exceptions.','I can make claims as strong and as narrow as the evidence requires.'
  UNION ALL SELECT 100,'social','polite-language','c2-rhetorical-concession','Rhetorical Concession & Sophisticated Rebuttal','Steelman competing arguments, concede genuine strengths and rebut without distortion.','I can answer the strongest opposing case while preserving valid points.'
  UNION ALL SELECT 110,'communication','requests','c2-persuasive-framing','Persuasive Framing & Audience Design','Adapt framing, emphasis, sequence and appeals to a specific audience without distorting evidence.','I can design a persuasive message for an audience while preserving factual integrity.'
  UNION ALL SELECT 120,'communication','requests','c2-high-stakes-negotiation','High-Stakes Negotiation & Package Building','Negotiate leverage, packages, conditional concessions, reciprocity, fallbacks and non-negotiables.','I can negotiate several linked priorities and build a durable package.'
  UNION ALL SELECT 130,'work-study','jobs','c2-facilitating-complex-discussion','Facilitating Complex Discussion & Consensus Testing','Facilitate participation, synthesize disagreement, preserve dissent and test working consensus.','I can facilitate a difficult group discussion without mistaking silence for agreement.'
  UNION ALL SELECT 140,'work-study','jobs','c2-spontaneous-interaction','Spontaneous Interaction & Real-Time Repair','Manage overlap, word-retrieval gaps, reformulation, self-correction and turn-taking in real time.','I can maintain precise meaning during fast spontaneous interaction.'
  UNION ALL SELECT 150,'social','polite-language','c2-conflict-repair','Conflict Repair, Accountability & Boundary Work','Separate intent from impact, acknowledge responsibility, set boundaries and negotiate credible repair.','I can handle emotionally difficult conflict without collapsing into blame or avoidance.'
  UNION ALL SELECT 160,'work-study','jobs','c2-expert-feedback','Expert Feedback, Calibration & Coaching','Give diagnostic, criterion-based, actionable feedback while preserving learner ownership.','I can give expert feedback that identifies the underlying issue and a concrete next move.'
  UNION ALL SELECT 170,'work-study','jobs','c2-strategy-scenarios','Strategy, Scenarios & Second-Order Effects','Reason across scenarios, assumptions, second-order effects, path dependency and optionality.','I can evaluate strategic choices across several credible futures.'
  UNION ALL SELECT 180,'work-study','jobs','c2-crisis-response','Crisis Response, Uncertainty & Decision Thresholds','Communicate triage, containment, thresholds, escalation and reversibility under uncertainty.','I can make and explain crisis decisions without pretending uncertainty has disappeared.'
  UNION ALL SELECT 190,'work-study','jobs','c2-executive-networking','Executive Networking, Positioning & Reciprocity','Build reciprocal professional relationships, make relevant introductions and position expertise naturally.','I can network at a high level without making relationships feel transactional.'
  UNION ALL SELECT 200,'work-study','jobs','c2-leadership-judgment','Leadership Judgment, Ownership & Ambiguous Outcomes','Explain judgment, delegation, accountability, trade-offs and hindsight limits in ambiguous decisions.','I can discuss leadership decisions with ownership, nuance and calibrated hindsight.'
  UNION ALL SELECT 210,'work-study','school-study','c2-seminar-discourse','Seminar Discourse & Intellectual Positioning','Make precise interventions, interrogate premises, compare frameworks and derive implications in advanced discussion.','I can position a sophisticated academic intervention without overstating it.'
  UNION ALL SELECT 220,'work-study','school-study','c2-synthesizing-complex-sources','Synthesizing Dense & Conflicting Sources','Synthesize convergence, divergence, source tension, discrepancies and corroboration across dense material.','I can preserve meaningful source disagreement while building an integrated synthesis.'
  UNION ALL SELECT 230,'work-study','school-study','c2-comparative-theory','Comparative Theory & Conceptual Lenses','Compare constructs, paradigms, assumptions, explanatory scope and predictive purpose across theories.','I can compare theories without forcing unlike models onto one scale.'
  UNION ALL SELECT 240,'work-study','school-study','c2-methodological-critique','Methodological Critique & Epistemic Limits','Critique validity, reliability, selection, measurement, replication, causality and generalizability.','I can state exactly what a study supports and what remains epistemically out of reach.'
  UNION ALL SELECT 250,'communication','questions','c2-sustained-argument','Sustained Argument, Signposting & Rebuttal','Control a long argument through proposition, sequencing, cumulative evidence, counterexamples and rebuttal.','I can sustain a complex argument without losing coherence or scope.'
  UNION ALL SELECT 260,'work-study','jobs','c2-policy-briefing','Policy Briefing & Decision-Grade Communication','Compress complex evidence into a decision, criteria, trade-offs, implementation risks and review triggers.','I can produce decision-grade communication for a complex policy choice.'
  UNION ALL SELECT 270,'communication','simple-messages','c2-framing-propaganda','Framing, Persuasion & Propaganda Techniques','Analyze loaded language, omission, false balance, narrative structure and source interests.','I can identify how information is framed or manipulated without assuming all persuasion is propaganda.'
  UNION ALL SELECT 280,'communication','simple-messages','c2-breaking-news-uncertainty','Breaking News, Verification & Rapidly Changing Claims','Separate confirmed facts, provisional claims, eyewitness reports, corrections and retractions in fast-moving news.','I can update my interpretation as a developing story changes without hiding uncertainty.'
  UNION ALL SELECT 290,'daily-life','common-actions','c2-ai-governance','AI Governance, Accountability & Socio-Technical Risk','Discuss oversight, automation bias, auditability, deployment safeguards, externalities and remedies.','I can analyze AI governance beyond model performance alone.'
  UNION ALL SELECT 300,'daily-life','common-actions','c2-climate-systems','Climate Systems, Policy Trade-offs & Long Horizons','Reason about mitigation, adaptation, resilience, lock-in, transition and distribution over long horizons.','I can discuss climate policy as a system of long-term trade-offs and path-dependent choices.'
  UNION ALL SELECT 310,'social','simple-messages','c2-social-institutions','Social Institutions, Norms & Structural Change','Analyze rules, informal norms, legitimacy, incentives, compliance and structural change.','I can explain social patterns without reducing them to individual intentions.'
  UNION ALL SELECT 320,'social','likes-dislikes','c2-identity-discourse','Identity, Belonging & Discursive Positioning','Discuss identity, belonging, stereotypes, hybridity and contextual positioning without essentializing people.','I can discuss identity with nuance while recognizing real social effects of categories.'
  UNION ALL SELECT 330,'social','polite-language','c2-relationship-nuance','Relationship Nuance, Intimacy & Difficult Conversations','Handle subtext, resentment, vulnerability, reciprocity, boundaries and repair in close relationships.','I can conduct a difficult personal conversation with emotional and linguistic precision.'
  UNION ALL SELECT 340,'health-body','basic-health','c2-medical-communication','Medical Communication, Risk & Shared Decisions','Discuss prognosis, baseline risk, absolute and relative risk, contraindications and informed consent.','I can communicate medical uncertainty and preference-sensitive decisions precisely.'
  UNION ALL SELECT 350,'shopping-money','prices','c2-economic-policy','Economic Policy, Distribution & Incentive Effects','Analyze incidence, elasticity, subsidies, externalities, productivity and distributional effects.','I can explain economic policy trade-offs without collapsing them into one headline number.'
  UNION ALL SELECT 360,'travel-transport','transport','c2-cross-border-travel-resolution','Cross-Border Travel Disruption & Multi-Party Resolution','Resolve complex disruption by mapping carriers, liability, jurisdiction, entitlements, evidence and escalation.','I can manage a multi-party cross-border travel dispute and preserve a defensible claim.'
  UNION ALL SELECT 370,'communication','requests','c2-legal-administrative-language','Legal-Administrative Language, Procedure & Appeal','Navigate eligibility, procedure, merits, discretion, precedent, burden and available remedy.','I can interpret and challenge a complex administrative decision through the correct procedural route.'
  UNION ALL SELECT 380,'social','simple-messages','c2-public-consultation','Public Consultation, Stakeholders & Deliberative Trade-offs','Evaluate consultation design, representation, participation, mandates, legitimacy and stakeholder trade-offs.','I can discuss public consultation without confusing participation with representation or authority.'
  UNION ALL SELECT 390,'social','hobbies','c2-literary-interpretation','Literary Interpretation, Voice & Ambiguity','Interpret narrator reliability, motif, symbolism, voice, intertextuality and productive ambiguity.','I can develop a sophisticated literary reading while preserving legitimate ambiguity.'
  UNION ALL SELECT 400,'social','polite-language','c2-comedy-wordplay','Comedy, Wordplay, Irony & Layered Humor','Interpret deadpan delivery, understatement, callbacks, double meanings, timing and nonliteral intent.','I can understand and explain humor that depends on layered language and shared context.'
  UNION ALL SELECT 410,'communication','simple-messages','c2-figurative-language','Figurative Language, Connotation & Conceptual Metaphor','Analyze metaphor, idiom, image schemas, connotation and the framing effects of figurative choices.','I can recover the conceptual and emotional work done by figurative language.'
  UNION ALL SELECT 420,'communication','polite-language','c2-register-voice','Register, Voice & Stylistic Identity','Shift formality, stance, cadence, compression and deference while preserving a coherent voice.','I can adapt register deliberately without losing precision or stylistic identity.'
  UNION ALL SELECT 430,'communication','requests','c2-mediation-reframing','Mediation, Reframing & Interest-Based Resolution','Translate accusations into interests, constraints, neutral reframing and negotiable proposals.','I can mediate substantive disagreement without misrepresenting either side.'
  UNION ALL SELECT 440,'communication','questions','c2-complex-decision-matrix','Complex Decisions, Competing Criteria & Robust Choice','Make criteria, weighting, sensitivity, scenarios, thresholds and reversibility explicit in complex decisions.','I can locate exactly why reasonable people reach different decisions from the same evidence.'
  UNION ALL SELECT 450,'communication','simple-messages','c2-integrated-mastery','Integrated C2 Mastery Capstone','Integrate inference, synthesis, evaluation, mediation, reformulation, qualification and register adaptation under pressure.','I can use English flexibly, precisely and appropriately across a demanding integrated task.'
) u
JOIN courses c ON c.slug = 'fa-en-us'
JOIN cefr_levels lvl ON lvl.code = 'C2'
JOIN skills s ON s.slug = u.skill_slug
JOIN topics t ON t.slug = u.topic_slug;
