-- Contemporary Standard French B1 curriculum for Persian-speaking learners.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,2,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','fr-FR','grammar_focus',u.grammar_focus,'persian_learner_notes',u.notes)
FROM (
 SELECT 310 sort_order,'daily-life' skill_slug,'daily-routine' topic_slug,'b1-fr-souvenirs-et-recits' slug,'Quand j''étais petit, on venait ici' title,'Narrate memories by contrasting background, habits and bounded past events.' objective,'imparfait vs passé composé' grammar_focus,'پس‌زمینه و عادت گذشته را از رویداد مشخص در روایت جدا کن.' notes
 UNION ALL SELECT 320,'time-plans','time','b1-fr-projets-et-avenir','Dans quelques années, je travaillerai ailleurs','Discuss longer-term plans, predictions and conditions.','futur simple; si + présent','آینده ساده را با شرط واقعی و برنامه بلندمدت پیوند بده.'
 UNION ALL SELECT 330,'daily-life','common-actions','b1-fr-travail-et-organisation','C''est le dossier qui doit partir aujourd''hui','Organize work, identify people and things precisely, and negotiate priorities.','relative pronouns qui/que','qui و que را در زبان واقعی کار و ارجاع دقیق تثبیت کن.'
 UNION ALL SELECT 340,'travel-transport','transport','b1-fr-voyages-et-imprevus','On a dû changer d''itinéraire','Explain travel disruptions, causes, consequences and solutions.','cause/consequence connectors','علت و نتیجه را در روایت مشکل سفر به‌صورت منسجم بیان کن.'
 UNION ALL SELECT 350,'family-home','home','b1-fr-logement-et-reclamations','Je voudrais signaler un problème','Make polite housing complaints and request repairs with appropriate register.','conditional for polite requests','conditionnel را برای درخواست رسمی و شکایت مؤدبانه به‌کار ببر.'
 UNION ALL SELECT 360,'daily-life','common-actions','b1-fr-sante-et-bien-etre','Il faudrait que je dorme davantage','Describe ongoing wellbeing issues and understand or give recommendations.','il faut/il faudrait que + subjunctive','الگوهای پرکاربرد توصیه با subjonctif را کاربردی تمرین کن.'
 UNION ALL SELECT 370,'describing','objects','b1-fr-medias-et-opinions','Ce qui m''a plu, c''est le point de vue','Express nuanced opinions, concession and respectful disagreement about media.','même si; pourtant; opinion frames','مخالفت و پذیرش نسبی را با même si و pourtant طبیعی بیان کن.'
 UNION ALL SELECT 380,'daily-life','common-actions','b1-fr-relations-et-conseils','À ta place, je lui parlerais directement','Discuss misunderstandings and give tactful hypothetical advice.','si + imparfait, conditional present','شرط فرضی را برای توصیه و روابط روزمره تمرین کن.'
 UNION ALL SELECT 390,'shopping-money','shopping','b1-fr-services-et-demarches','J''aimerais savoir où en est ma demande','Follow administrative requests, missing documents and procedural updates.','passive voice in service language','مجهول را در زبان اداری و پیگیری فرایندها تشخیص بده و استفاده کن.'
 UNION ALL SELECT 400,'daily-life','daily-routine','b1-fr-b1-capstone-decisions','Si tout va bien, on aura une solution','Weigh options and produce a connected B1-level decision narrative.','B1 discourse linking and integrated tense control','در capstone علت، تضاد، شرط، آینده و نتیجه را در گفتار پیوسته ترکیب کن.'
) u JOIN courses c ON c.slug='fa-fr-fr' JOIN cefr_levels lvl ON lvl.code='B1' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug;
