-- German C1 curriculum, batch 1 (units 1-10) for Persian-speaking learners.
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',1)
FROM (
  SELECT 10 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'c1-de-claims-hedging' AS slug,'Aussagen präzise relativieren' AS title,'Aussagen nach Evidenzgrad, Reichweite und Unsicherheit differenzieren, Einschränkungen explizit machen und Übertreibungen vermeiden.' AS objective,3 AS expected_lessons,'insofern, als; soweit; nicht zuletzt vor dem Hintergrund, dass' AS grammar_focus
  UNION ALL SELECT 20,'communication','simple-messages','c1-de-reported-speech-attribution','Positionen distanziert wiedergeben','Fremde Aussagen präzise attribuieren, Distanz zur Aussage markieren, Quellenstatus kenntlich machen und indirekte Rede sicher einsetzen.',3,'Konjunktiv I; zufolge; der Darstellung nach'
  UNION ALL SELECT 30,'communication','simple-messages','c1-de-multi-source-synthesis','Mehrere Quellen synthetisieren','Mehrere Quellen nach Aussagekraft, Gemeinsamkeiten und Widersprüchen ordnen und zu einer kohärenten Synthese mit klaren Grenzen verbinden.',3,'wohingegen; zusammengenommen; daraus lässt sich ableiten'
  UNION ALL SELECT 40,'social','polite-language','c1-de-implicit-meaning-register','Implizite Bedeutung & Register erkennen','Implizite Haltungen, Abschwächungen und registerabhängige Signale erkennen und die eigene Formulierung an Beziehung, Kontext und Risiko anpassen.',3,'dürfte; wäre als ... zu verstehen; zwar ... jedoch'
  UNION ALL SELECT 50,'work-study','jobs','c1-de-strategic-recommendations','Strategische Empfehlungen begründen','Komplexe Handlungsoptionen anhand von Kriterien, Risiken und Nebenwirkungen bewerten und eine belastbare, konditionale Empfehlung formulieren.',3,'unter Abwägung von; vorausgesetzt, dass; angesichts dessen'
  UNION ALL SELECT 60,'social','polite-language','c1-de-consensus-facilitation','Konsens in komplexen Gruppen herstellen','Divergierende Interessen sichtbar machen, gemeinsame Mindestbedingungen identifizieren, Zielkonflikte moderieren und tragfähige Konsenspunkte formulieren.',3,'sofern; insofern; während zugleich'
  UNION ALL SELECT 70,'communication','simple-messages','c1-de-formal-analysis-writing','Analytisch & formal schreiben','Komplexe Sachverhalte in formalem Register verdichten, Nominalstil kontrolliert einsetzen, Argumente hierarchisieren und Schlussfolgerungen präzise formulieren.',3,'Nominalisierung; erweiterte Partizipialattribute; im Hinblick auf'
  UNION ALL SELECT 80,'communication','requests','c1-de-policy-interpretation','Richtlinien & institutionelle Texte einordnen','Formelle Richtlinien, Bedingungen, Ausnahmen und Ermessensspielräume präzise interpretieren und deren praktische Folgen verständlich erklären.',3,'sofern/soweit; vorbehaltlich; es obliegt + Dativ'
  UNION ALL SELECT 90,'communication','simple-messages','c1-de-crisis-communication','Krisenkommunikation präzise steuern','Unter Zeitdruck bestätigte Fakten, offene Fragen und Korrekturen klar trennen, Verantwortlichkeit übernehmen und Vertrauen durch nachvollziehbare Updates erhalten.',3,'nach aktuellem Stand; Passiv/Unpersönlichkeit; ohne ... zu + Infinitiv'
  UNION ALL SELECT 100,'communication','simple-messages','c1-de-evidence-briefing-capstone','C1-Capstone: Evidenzbasiert entscheiden','Komplexe Evidenz verdichten, Positionen korrekt attribuieren, Unsicherheit markieren, Optionen abwägen und eine adressatengerechte Entscheidungsvorlage präsentieren.',3,'Konjunktiv I + Hedging; Nominalstil; konditionale Empfehlung'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C1'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;

-- German C1 curriculum, batch 2 (units 11-20).
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',2)
FROM (
  SELECT 110 AS sort_order,'communication' AS skill_slug,'requests' AS topic_slug,'c1-de-stakeholder-requirements' AS slug,'Anforderungen präzise herausarbeiten' AS title,'Bedürfnisse von Lösungsvorstellungen trennen, Annahmen sichtbar machen, überprüfbare Kriterien bilden und widersprüchliche Anforderungen professionell klären.' AS objective,3 AS expected_lessons,'indirekte Präzisierungsfragen; falls/sofern; Nominalisierung' AS grammar_focus
  UNION ALL SELECT 120,'work-study','jobs','c1-de-scope-negotiation','Leistungsumfang souverän verhandeln','Leistungsumfang und Verantwortungsgrenzen präzisieren, Änderungen konditional verhandeln und Folgewirkungen auf Zeit, Aufwand und Qualität transparent machen.',3,'sofern; zwar ... jedoch; würde + Infinitiv'
  UNION ALL SELECT 130,'work-study','jobs','c1-de-knowledge-transfer','Wissen nachhaltig übergeben','Implizites Wissen sichtbar machen, Kontext und Ausnahmen dokumentieren, Erklärungen an den Adressaten anpassen und Wissen durch Anwendung verankern.',3,'nicht nur ... sondern auch; sodass; Partizipialattribute'
  UNION ALL SELECT 140,'social','polite-language','c1-de-objections-counterarguments','Einwände differenziert entkräften','Einwände fair rekonstruieren, berechtigte Teile anerkennen, Reichweite begrenzen und evidenzbasierte Gegenargumente ohne Überzeichnung formulieren.',3,'zwar ... jedoch; insofern ... als; ohne dass'
  UNION ALL SELECT 150,'work-study','jobs','c1-de-feedback-coaching','Anspruchsvolles Feedback entwicklungsorientiert geben','Beobachtung, Wirkung und Interpretation trennen, Perspektiven einholen und kritisches Feedback in konkrete Entwicklungsvereinbarungen überführen.',3,'mir ist aufgefallen, dass; wenn ich dich richtig verstehe; künftig wäre mir wichtig'
  UNION ALL SELECT 160,'communication','requests','c1-de-formal-escalation','Formell eskalieren, ohne zu verhärten','Ungeklärte Vorgänge sachlich dokumentieren, klare Handlungen und Termine benennen und formelle Konsequenzen kontrolliert formulieren.',3,'hiermit; unter Bezugnahme auf; sollte ... keine ... erfolgen'
  UNION ALL SELECT 170,'work-study','jobs','c1-de-delegation-accountability','Verantwortung wirksam delegieren','Ergebnis, Zuständigkeit, Handlungsspielraum und Rückkopplung so definieren, dass eigenständiges Arbeiten und klare Verantwortlichkeit zusammenpassen.',3,'es liegt bei + Dativ; im Rahmen von; während/wohingegen'
  UNION ALL SELECT 180,'communication','simple-messages','c1-de-ambiguity-clarification','Mehrdeutigkeit erkennen & klären','Mehrere mögliche Lesarten unterscheiden, Referenzen und implizite Annahmen prüfen und gemeinsames Verständnis ohne vorschnelle Zuschreibungen herstellen.',3,'meinen Sie damit, dass; je nachdem, wie; sofern ich Sie richtig verstehe'
  UNION ALL SELECT 190,'social','polite-language','c1-de-cross-cultural-pragmatics','Pragmatik kulturübergreifend steuern','Direktheit, Distanz und Höflichkeit kontextabhängig interpretieren, Fehlinterpretationen ohne Stereotype reduzieren und den eigenen Ton flexibel anpassen.',3,'wirkt auf mich; nicht zwingend; während ... eher'
  UNION ALL SELECT 200,'communication','simple-messages','c1-de-collaboration-capstone','C1-Capstone: Komplexe Zusammenarbeit steuern','Anforderungen konsolidieren, Arbeitsrahmen und Verantwortung klären, Mehrdeutigkeit auflösen und eine umsetzbare, verbindliche Vereinbarung herstellen.',3,'erst wenn/nur wenn; einerseits ... andererseits; damit'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C1'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;

-- German C1 curriculum, batch 3 (units 21-30).
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',3)
FROM (
  SELECT 210 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'c1-de-executive-presentations' AS slug,'Komplexe Inhalte überzeugend präsentieren' AS title,'Präsentationen nach Adressat und Entscheidung strukturieren, Kernbotschaften verdichten und kritische Rückfragen präzise in den Gesamtzusammenhang einordnen.' AS objective,3 AS expected_lessons,'worauf es ankommt; ohne ... zu; nicht X, vielmehr Y' AS grammar_focus
  UNION ALL SELECT 220,'work-study','jobs','c1-de-meeting-facilitation','Anspruchsvolle Besprechungen wirksam moderieren','Komplexe Besprechungen zielorientiert strukturieren, Entscheidungsreife prüfen, Abschweifungen begrenzen und Beschlüsse sowie nächste Schritte verbindlich festhalten.',3,'bevor/nachdem; soweit ich sehe; festhalten, dass'
  UNION ALL SELECT 230,'work-study','jobs','c1-de-partnership-negotiation','Partnerschaften strategisch verhandeln','Verhandlungsspielräume mehrdimensional erfassen, Konzessionen an Gegenleistungen knüpfen und langfristig tragfähige Paketlösungen entwickeln.',3,'je ... desto; unter der Voraussetzung, dass; nicht isoliert, sondern'
  UNION ALL SELECT 240,'communication','simple-messages','c1-de-data-interpretation','Daten vorsichtig und präzise interpretieren','Zusammenhang und Ursache unterscheiden, Stichproben und Verzerrungen einordnen, Effektstärken bewerten und Schlussfolgerungen proportional zur Evidenz formulieren.',3,'lässt darauf schließen; unter Berücksichtigung von; dürfte'
  UNION ALL SELECT 250,'communication','simple-messages','c1-de-proposal-writing','Überzeugende Vorschläge und Entscheidungsvorlagen schreiben','Entscheidungen, Optionen, Kriterien und Empfehlungen so strukturieren, dass eine kurze Vorlage nachvollziehbar zu einer konkreten Freigabe führt.',3,'ausgehend von; maßgeblich ist; wir empfehlen, sofern'
  UNION ALL SELECT 260,'social','polite-language','c1-de-conflict-mediation-power','Konflikte bei ungleichen Rollen moderieren','Konflikte bei ungleichen Rollen sachlich entpersonalisieren, Interessen sichtbar machen und Lösungen ermöglichen, die Hierarchie und Gesichtswahrung angemessen berücksichtigen.',3,'ohne zu unterstellen; weniger um ... als vielmehr; unter Wahrung von'
  UNION ALL SELECT 270,'communication','simple-messages','c1-de-change-communication','Veränderungen glaubwürdig kommunizieren','Veränderungsgründe konkret erklären, bestätigte und offene Punkte trennen, unterschiedliche Betroffenheit berücksichtigen und kontinuierliche Orientierung schaffen.',3,'was feststeht/was offen ist; nicht weil, sondern weil; solange/bis'
  UNION ALL SELECT 280,'communication','requests','c1-de-expert-interviews','Expertenwissen systematisch erschließen','Mit offenen Leitfragen, präzisen Nachfragen und reflektierendem Rückspiegeln Erfahrungswissen, Ausnahmen und implizite Annahmen systematisch erschließen.',3,'wie gehen Sie vor, wenn; was genau meinen Sie; wenn ich Sie richtig verstehe'
  UNION ALL SELECT 290,'work-study','jobs','c1-de-scenario-planning','Mit Szenarien unter Unsicherheit planen','Mehrere plausible Zukunftsszenarien aus relevanten Treibern entwickeln, Frühindikatoren definieren und robuste sowie anpassbare Entscheidungen vorbereiten.',3,'angenommen, dass; sowohl unter ... als auch; falls ... eintritt'
  UNION ALL SELECT 300,'communication','simple-messages','c1-de-strategic-alignment-capstone','C1-Capstone: Strategische Initiative ausrichten','Evidenz, Entscheidungsbasis, Zielbild, Zuständigkeiten und Überprüfungspunkte zu einer nachvollziehbaren und langfristig tragfähigen Initiative verbinden.',3,'entscheidend ist, ob; einerseits ... zugleich; unter der Bedingung, dass'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C1'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;

-- German C1 curriculum, batch 4 (units 31-40).
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',4)
FROM (
  SELECT 310 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'c1-de-academic-seminar-discussion' AS slug,'In Seminaren kritisch und präzise diskutieren' AS title,'Thesen und Belege trennen, Einwände fair aufnehmen, Reichweiten begrenzen und die eigene Position ohne Überzeichnung weiterentwickeln.' AS objective,3 AS expected_lessons,'zwar ... allerdings; daraus folgt nicht zwingend, dass; unter der Annahme, dass' AS grammar_focus
  UNION ALL SELECT 320,'communication','simple-messages','c1-de-source-evaluation','Quellen kritisch prüfen und Aussagen einordnen','Quellen nach Herkunft, Methode, Transparenz und Bestätigbarkeit beurteilen und den Status von Aussagen präzise zwischen bestätigt, unbestätigt und widerlegt unterscheiden.',3,'nur weil ... heißt das nicht, dass; nach allem, was sich belegen lässt; weder ... noch ... reicht aus'
  UNION ALL SELECT 330,'social','polite-language','c1-de-public-debate-value-conflicts','In öffentlichen Debatten Wertkonflikte fair verhandeln','Fakten-, Prioritäts- und Wertkonflikte auseinanderhalten, Gegenpositionen fair rekonstruieren, Gemeinsamkeiten benennen und echten Dissens sachlich sichtbar machen.',3,'nicht darüber, ob ... sondern darüber, wie; selbst wenn ... bleibt die Frage, ob; so weit gehe ich mit, dass'
  UNION ALL SELECT 340,'communication','simple-messages','c1-de-media-interviews-public-statements','Medieninterviews und öffentliche Aussagen souverän führen','Kernbotschaften halten, bestätigte Fakten von offenen Punkten trennen, Vorannahmen in Fragen korrigieren und Wissensgrenzen transparent kommunizieren.',3,'was ich bestätigen kann, ist; die Frage setzt voraus, dass; sobald ... werden wir'
  UNION ALL SELECT 350,'communication','requests','c1-de-administrative-appeals','Komplexe Verwaltungsentscheidungen anfechten','Bescheide systematisch prüfen, Begründungslücken dokumentieren und formelle Überprüfungsanträge mit klarer Bitte, relevanten Nachweisen und professionellem Ton formulieren.',3,'unter Bezugnahme auf; soweit aus dem Bescheid hervorgeht; ich bitte um Prüfung, ob'
  UNION ALL SELECT 360,'social','polite-language','c1-de-community-conflict-mediation','Konflikte in Nachbarschaft und Gemeinschaft moderieren','Unterschiedliche Wahrnehmungen in konkrete Beobachtungen übersetzen, legitime Interessen vermitteln und überprüfbare, anpassbare Vereinbarungen entwickeln.',3,'für die eine Seite ... für die andere; damit ... zugleich; falls sich zeigt, dass'
  UNION ALL SELECT 370,'work-study','jobs','c1-de-interdisciplinary-collaboration','Fachübergreifend präzise zusammenarbeiten','Zwischen Fachperspektiven gemeinsame Begriffe schaffen, abstrakte Ziele operationalisieren und Zielkonflikte so sichtbar machen, dass gemeinsame Entscheidungen möglich werden.',3,'wenn wir unter X dasselbe verstehen; aus fachlicher Sicht ... aus Umsetzungssicht; erst wenn ... lässt sich'
  UNION ALL SELECT 380,'social','polite-language','c1-de-ethical-tradeoffs','Ethische Zielkonflikte differenziert abwägen','Grundsätze, Betroffenengruppen und Folgewirkungen sichtbar machen, legitime Werte gegeneinander abwägen und unvollkommene Entscheidungen transparent begründen.',3,'je nachdem, welchen Grundsatz man höher gewichtet; auch wenn ... ist zu berücksichtigen; vertretbar wäre X nur dann, wenn'
  UNION ALL SELECT 390,'work-study','jobs','c1-de-influence-without-authority','Ohne formale Autorität wirksam Einfluss nehmen','Interessenlagen verstehen, freiwillige Unterstützung aufbauen, gegenseitigen Nutzen sichtbar machen und Widerstand in verhandelbare Bedingungen übersetzen.',3,'für euch wäre der Vorteil, dass; ich kann X anbieten, wenn ihr Y übernehmt; was müsste gegeben sein, damit'
  UNION ALL SELECT 400,'communication','simple-messages','c1-de-civic-decision-capstone','C1-Capstone: Öffentliche Entscheidung verantwortungsvoll begründen','Evidenzqualität, Wertkonflikte, Betroffenengruppen, Umsetzbarkeit und öffentliche Rechenschaft zu einer transparenten, verhältnismäßigen und revidierbaren Entscheidung verbinden.',3,'angesichts der Tatsache, dass; den Ausschlag gibt; wir entscheiden uns für X, behalten uns jedoch vor'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C1'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;
