-- German C2 curriculum, batch 1 (units 1-10) for Persian-speaking learners.
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',1)
FROM (
  SELECT 10 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'c2-de-implicit-stance-subtext' AS slug,'Implizite Haltung und Subtext entschlüsseln' AS title,'Implizite Haltung, Voraussetzungen und Distanzsignale aus Wortwahl, Ton und Kontext erschließen und die Deutung sprachlich belegen.' AS objective,3 AS expected_lessons,'weniger ... als vielmehr; als wäre/als ob; nicht zuletzt dadurch, dass' AS grammar_focus
  UNION ALL SELECT 20,'communication','simple-messages','c2-de-rhetorical-strategy-diagnostics','Rhetorische Strategien diagnostizieren','Framing, Zuspitzung, Auslassung, Gegenfolien und suggestive Verfahren erkennen und ihre Wirkung von der inhaltlichen Richtigkeit einer Aussage trennen.',3,'indem; nicht etwa ... sondern; so ... dass'
  UNION ALL SELECT 30,'communication','simple-messages','c2-de-lexical-precision-collocation','Lexikalische Präzision und Kollokationen beherrschen','Feine Bedeutungsunterschiede, Kollokationen, Konnotationen und Idiomatik kontrollieren und die Wortwahl präzise an Kontext und Haltung anpassen.',3,'im Unterschied zu; je nachdem, ob; sofern'
  UNION ALL SELECT 40,'social','polite-language','c2-de-register-social-positioning','Registerwechsel und soziale Positionierung steuern','Register, soziale Distanz und Rollenbezug flexibel steuern, ohne Präzision, Authentizität oder professionelle Grenzen zu verlieren.',3,'wäre ... angebracht; es empfiehlt sich; je ... desto'
  UNION ALL SELECT 50,'social','polite-language','c2-de-irony-indirect-critique','Ironie, Untertreibung und indirekte Kritik verstehen','Ironie, Untertreibung, Doppeldeutigkeit und indirekte Kritik aus Kontextsignalen erschließen und ihre pragmatische Stärke beim Wiedergeben erhalten.',3,'als ob; nicht gerade; kaum ... ohne dass'
  UNION ALL SELECT 60,'communication','simple-messages','c2-de-argument-premises-fallacies','Prämissen, Fehlschlüsse und Argumentlogik prüfen','Prämissen offenlegen, Fehlschlüsse lokalisieren, Beweislasten trennen und genau benennen, an welcher Stelle eine Schlussfolgerung nicht trägt.',3,'selbst wenn; daraus folgt nicht, dass; nur dann, wenn'
  UNION ALL SELECT 70,'communication','simple-messages','c2-de-systems-causality-feedback','Systemische Kausalität und Rückkopplungen erklären','Mehrfachursachen, Rückkopplungen, Pfadabhängigkeit, Zeitverzögerungen und gegenläufige Effekte in komplexen Systemen differenziert erklären.',3,'Kontrafaktischer Plusquamperfekt; unter der Annahme, dass; zumal'
  UNION ALL SELECT 80,'communication','simple-messages','c2-de-polyphonic-source-synthesis','Mehrstimmige Quellen synthetisieren, ohne sie zu glätten','Mehrere Quellen mit unterschiedlichen Deutungsrahmen verdichten, Gemeinsamkeiten und Spannungen sichtbar halten und künstlichen Konsens vermeiden.',3,'während ...; sowohl ... als auch ... ohne ... zu; in dem Maße, in dem'
  UNION ALL SELECT 90,'social','polite-language','c2-de-high-stakes-discursive-intervention','In heiklen Gesprächen präzise intervenieren','In angespannten Gesprächen den richtigen Eingriffspunkt wählen, Eskalation reduzieren, Gesicht wahren und zugleich klare Verantwortung und nächste Schritte sichern.',3,'bevor; ohne dass; was ... angeht'
  UNION ALL SELECT 100,'communication','simple-messages','c2-de-interpret-reframe-position-capstone','C2-Capstone: Interpretieren, reframen und präzise Position beziehen','Subtext, Rhetorik, Wortwahl, Argumentlogik und Quellenperspektiven zu einer Gesamtdeutung verbinden und die eigene Position begründet und flexibel rekalibrieren.',3,'unter Einbeziehung von; weder ... noch ... sondern; sofern ... zugleich'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C2'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;

-- German C2 curriculum, batch 2 (units 11-20).
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',2)
FROM (
  SELECT 110 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'c2-de-evidentiality-epistemic-calibration' AS slug,'Evidenz gewichten und epistemische Sicherheit kalibrieren' AS title,'Quelle, Evidenzgrad und Sicherheit einer Aussage getrennt bewerten und Schlussfolgerungen exakt an die Stärke der Belege anpassen.' AS objective,3 AS expected_lessons,'dürfte + Infinitiv; demnach; soweit sich ... beurteilen lässt' AS grammar_focus
  UNION ALL SELECT 120,'communication','simple-messages','c2-de-modal-commitment-precision','Modalität und Verpflichtungsgrad präzise steuern','Zwischen Möglichkeit, Wahrscheinlichkeit, Notwendigkeit, Empfehlung und Verpflichtung differenzieren und den Grad des Commitments sprachlich kontrollieren.',3,'nicht zwingend ... wohl aber; es ist nicht auszuschließen, dass; unter dem Vorbehalt, dass'
  UNION ALL SELECT 130,'communication','simple-messages','c2-de-semantic-scope-ambiguity','Semantischen Geltungsbereich und Mehrdeutigkeit auflösen','Geltungsbereiche von Negation, Quantoren und Referenzen präzise bestimmen, konkurrierende Lesarten vergleichen und unbeabsichtigte Ambiguität auflösen.',3,'nicht alle / alle nicht; je nachdem, worauf; insofern ... als'
  UNION ALL SELECT 140,'communication','simple-messages','c2-de-cohesion-reference-dense-texts','Kohäsion und Referenzketten in dichten Texten verfolgen','Referenzketten, Rückverweise, Anschlussstellen und Gedankensprünge in komplexen Texten verfolgen und sprachliche Kohäsion von argumentativer Kohärenz unterscheiden.',3,'wobei; dessen/deren; dadurch, dass'
  UNION ALL SELECT 150,'communication','simple-messages','c2-de-lossless-compression-summarization','Komplexe Inhalte verdichten, ohne Nuancen zu verlieren','Komplexe Texte so verdichten, dass Kernthese, Einschränkungen, Gegenpositionen und Unsicherheitsgrade erhalten bleiben.',3,'unter Beibehaltung von; ohne ... zu; insofern ... als'
  UNION ALL SELECT 160,'social','polite-language','c2-de-audience-reformulation-technical-public','Fachliche Inhalte adressatengerecht reformulieren','Fachinhalte für nichtfachliche Zielgruppen verständlich reformulieren, ohne Präzision, Unsicherheiten oder zentrale Bedingungen zu verlieren.',3,'statt ... zu; so ..., dass; ohne dabei ... zu'
  UNION ALL SELECT 170,'social','polite-language','c2-de-metacommunication-misunderstanding-repair','Missverständnisse metakommunikativ reparieren','Missverständnisse diagnostizieren, Bezugspunkte explizit machen, Formulierungen präzisieren und Gespräche ohne unnötige Eskalation reparieren.',3,'Was ich meinte, war; nicht ... sondern vielmehr; falls das anders angekommen ist'
  UNION ALL SELECT 180,'communication','simple-messages','c2-de-terminology-negotiation-concept-boundaries','Begriffe aushandeln und Konzeptgrenzen trennscharf setzen','Arbeitsdefinitionen explizit aushandeln, Begriffsgrenzen prüfen und stille Begriffsverschiebungen in Fachargumentationen erkennen.',3,'Unter X verstehe ich; sofern wir X als Y verstehen; einerseits ... andererseits'
  UNION ALL SELECT 190,'social','polite-language','c2-de-live-debate-interruption-reframing','In Live-Debatten unter Zeitdruck präzise reagieren','Unterbrechungen und Einwürfe unter Zeitdruck aufnehmen, fair reframen und knapp reagieren, ohne die argumentative Linie oder wichtige Bedingungen zu verlieren.',3,'bevor wir ... möchte ich; wenn ich daran anknüpfen darf; selbst wenn ... bleibt'
  UNION ALL SELECT 200,'communication','simple-messages','c2-de-expert-public-precision-capstone','C2-Capstone: Fachliche Präzision öffentlich vermitteln','Komplexe Evidenz, Unsicherheit, Zielgruppenbezug und Zeitdruck zugleich steuern und daraus klare, differenzierte öffentliche Antworten entwickeln.',3,'unter der Voraussetzung, dass; einerseits ... andererseits; weder ... noch ... sondern vielmehr'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C2'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;

-- German C2 curriculum, batch 3 (units 21-30).
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',3)
FROM (
  SELECT 210 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'c2-de-presupposition-accommodation' AS slug,'Präsuppositionen erkennen und kontrolliert übernehmen' AS title,'Implizite Voraussetzungen erkennen, ihre Gültigkeit prüfen und Antworten formulieren, ohne strittige Annahmen automatisch zu übernehmen.' AS objective,3 AS expected_lessons,'Die Frage setzt voraus, dass; selbst wenn wir annehmen, dass; nicht ohne Weiteres voraussetzen' AS grammar_focus
  UNION ALL SELECT 220,'communication','simple-messages','c2-de-steelmanning-concession','Gegenpositionen fair stärken und präzise konzidieren','Die stärkste Version einer Gegenposition rekonstruieren, berechtigte Punkte zugestehen und den verbleibenden Dissens ohne Strohmannargumente präzise markieren.',3,'zwar ... aber; selbst zugestanden, dass; der stärkste Einwand lautet'
  UNION ALL SELECT 230,'communication','simple-messages','c2-de-descriptive-normative-reasoning','Deskriptive und normative Aussagen sauber trennen','Faktenbehauptungen, Sollensaussagen und Wertprämissen auseinanderhalten und normative Schlussfolgerungen transparent begründen.',3,'daraus folgt nicht, dass man ... sollte; unter der Wertannahme, dass; nicht nur empirisch, sondern auch normativ'
  UNION ALL SELECT 240,'social','polite-language','c2-de-institutional-register-precision','Institutionelle Sprache präzise und verantwortbar einsetzen','Zwischen Empfehlung, Anordnung, Zuständigkeit, Ermessen und rechtlicher Verbindlichkeit unterscheiden und institutionelle Aussagen entsprechend präzise formulieren.',3,'ist befugt, ... zu; sieht vor, dass; im Rahmen des Ermessens'
  UNION ALL SELECT 250,'communication','simple-messages','c2-de-metaphor-idiom-pragmatic-transfer','Metaphern, Idiomatik und pragmatische Wirkung übertragen','Metaphern, Idiome und Konnotationen funktional deuten und ihre kommunikative Wirkung in natürlicher, nicht bloß wörtlicher Form wiedergeben.',3,'bildlich gesprochen; damit schwingt mit, dass; sinngemäß, nicht wortwörtlich'
  UNION ALL SELECT 260,'communication','simple-messages','c2-de-narrative-perspective-temporal-control','Narrative Perspektive und zeitliche Ordnung souverän steuern','Perspektivwechsel, Rückblenden, Vorgriffe und parallele Abläufe so markieren, dass damaliger Wissensstand, spätere Erkenntnis und zeitliche Ordnung klar bleiben.',3,'zu diesem Zeitpunkt; erst im Rückblick; währenddessen / zugleich'
  UNION ALL SELECT 270,'communication','simple-messages','c2-de-academic-stance-citation-distance','Akademischen Standpunkt und Quellenabstand präzise markieren','Zwischen Quellenreferat, eigener Interpretation, Zustimmung, Vorbehalt und Widerspruch sauber unterscheiden und wissenschaftliche Positionierung transparent machen.',3,'X zufolge; dagegen lässt sich einwenden, dass; vorbehaltlich + Genitiv'
  UNION ALL SELECT 280,'social','polite-language','c2-de-principled-disagreement-negotiation','Grundsätzlichen Dissens präzise und kooperativ verhandeln','Gemeinsamkeiten und echte Unvereinbarkeiten unterscheiden, Dissens klar benennen und Kooperation auch ohne künstlichen Vollkonsens ermöglichen.',3,'wir sind uns einig, dass ... strittig bleibt jedoch; in diesem Punkt kommen wir nicht zusammen; auch ohne Einigkeit über ... können wir'
  UNION ALL SELECT 290,'social','polite-language','c2-de-oral-synthesis-pressure','Komplexe Inhalte unter Zeitdruck mündlich synthetisieren','Mehrere Informationen und Einschränkungen unter Zeitdruck zu einer prägnanten, strukturierten und anschlussfähigen mündlichen Antwort verdichten.',3,'kurz gesagt; entscheidend ist dabei, dass; wenn ich es auf drei Punkte reduziere'
  UNION ALL SELECT 300,'communication','simple-messages','c2-de-judgment-language-capstone','C2-Capstone: Urteil, Perspektive und Sprache integrieren','Präsuppositionen, Evidenz, Werte, Gegenpositionen, Register, Perspektive und Zeitdruck in einem klaren, verantwortbaren Gesamturteil zusammenführen.',3,'in der Gesamtabwägung; unter Berücksichtigung dessen, dass; das bedeutet nicht, dass ... wohl aber, dass'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C2'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;

-- German C2 curriculum, batch 4 (units 31-40).
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus,'batch',4)
FROM (
  SELECT 310 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'c2-de-evidential-calibration' AS slug,'Evidenz präzise gewichten' AS title,'Die Tragfähigkeit von Evidenz differenziert einschätzen, Beobachtung, Interpretation und Schlussfolgerung auseinanderhalten und Aussagen exakt an den Beleggrad anpassen.' AS objective,3 AS expected_lessons,'etwas legt nahe, dass ...; ohne dass daraus zwingend folgt, dass ...; unter dem Vorbehalt, dass ...' AS grammar_focus
  UNION ALL SELECT 320,'communication','simple-messages','c2-de-counterfactual-reasoning','Kontrafaktisch sauber argumentieren','Kontrafaktische Gegenproben nutzen, notwendige und hinreichende Bedingungen unterscheiden und alternative Erklärungen prüfen, ohne Kausalität zu überzeichnen.',3,'selbst wenn ... wäre/hätte, ...; angenommen, ... dann ...; notwendig, aber nicht hinreichend für ...'
  UNION ALL SELECT 330,'communication','simple-messages','c2-de-definitional-disputes','Begriffe aushandeln statt aneinander vorbeizureden','Definitionsbedingte Konflikte erkennen, tragfähige Arbeitsdefinitionen und Begriffsgrenzen aushandeln und transparent machen, wie unterschiedliche Definitionen die Schlussfolgerung verändern.',3,'unter X verstehen wir hier ...; je nachdem, wie ... definiert wird, ...; nicht so sehr X als vielmehr Y'
  UNION ALL SELECT 340,'social','polite-language','c2-de-register-and-implicature','Register und Implikatur sicher lesen','Wörtliche Bedeutung, Implikatur, Unterton und Registerwirkung präzise unterscheiden und Antworten an Beziehung, Vorwissen und kommunikative Situation anpassen.',3,'das klingt weniger nach X als nach Y; so ... auch sein mag, ...; es wäre zu kurz gegriffen, ... als ... zu verstehen'
  UNION ALL SELECT 350,'social','polite-language','c2-de-legal-administrative-nuance','Verbindlichkeit und Spielraum präzise ausdrücken','In fortgeschrittener Verwaltungs- und Institutionssprache Pflicht, Ermessen, Empfehlung, Zulässigkeit und Ausnahmefälle sprachlich sauber voneinander abgrenzen.',3,'ist ... vorgesehen / kann ... vorgesehen werden; soweit ...; es steht ... frei, ... / es obliegt ...'
  UNION ALL SELECT 360,'social','polite-language','c2-de-humor-irony-repair','Ironie erkennen und Missverständnisse elegant reparieren','Kontextabhängige Ironie und Doppeldeutigkeit erkennen, Missverständnisrisiken einschätzen und fehlgeschlagenen Humor so reparieren, dass Wirkung und Absicht getrennt geklärt werden.',3,'das war eher ... gemeint als ...; falls das ... angekommen ist, ...; bei aller Ironie ...'
  UNION ALL SELECT 370,'communication','simple-messages','c2-de-compressed-synthesis','Komplexes verdichten, ohne es zu verfälschen','Mehrere komplexe Positionen knapp synthetisieren, Kernthese, entscheidende Einschränkungen und echte Unterschiede bewahren und relevante Details von verzichtbaren unterscheiden.',3,'während X ..., liegt Y ...; gemeinsam ist den Positionen, dass ...; auf den Punkt gebracht, ohne ...'
  UNION ALL SELECT 380,'social','polite-language','c2-de-mediation-across-frameworks','Zwischen unterschiedlichen Denkrahmen vermitteln','Unterschiedliche Bezugsrahmen und Maßstäbe explizit machen, funktionale begriffliche Anschlussstellen finden und Verständigung ermöglichen, ohne reale Wertkonflikte zu glätten.',3,'in der Logik von ... bedeutet X ...; was X als ... bezeichnet, entspricht bei Y eher ...; der Dissens bleibt bestehen, verschiebt sich aber von ... zu ...'
  UNION ALL SELECT 390,'communication','simple-messages','c2-de-live-reformulation','Gedanken spontan präzisieren und neu rahmen','Aussagen während des Sprechens flüssig nachschärfen, Reichweite und Haltung korrigieren und missverständliche Formulierungen neu fassen, ohne den Gesprächsfluss zu verlieren.',3,'genauer gesagt / präziser formuliert ...; nicht X schlechthin, sondern ...; ich würde insofern korrigieren, als ...'
  UNION ALL SELECT 400,'communication','simple-messages','c2-de-expert-briefing-capstone','C2-Capstone: Ein komplexes Expertengespräch steuern','Evidenzgewichtung, Kontrafaktik, Definition, Implikatur, Verbindlichkeit, Reparatur, Synthese, Mediation und spontane Reformulierung in einem kontrollierten Expertengespräch integrieren.',3,'unter Abwägung von ... lässt sich ...; sofern man unter X ... versteht, ...; andernfalls ...; ich würde das insofern anders zuspitzen, als ...'
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='C2'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;
