-- Complete German A2 curriculum for Persian-speaking learners.
INSERT IGNORE INTO curriculum_units(course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,l.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,u.expected_lessons,'approved',
JSON_OBJECT('language_specific',TRUE,'target_variant','de-DE','grammar_focus',u.grammar_focus)
FROM (
  SELECT 10 AS sort_order,'social' AS skill_slug,'polite-language' AS topic_slug,'a2-de-catching-up' AS slug,'Wiedersehen & Neuigkeiten' AS title,'Kurze Gespräche über Neuigkeiten, Arbeit, Lernen und Freizeit führen.' AS objective,2 AS expected_lessons,'Perfekt zur kurzen Rückschau; seit + Dativ für Zeitspannen' AS grammar_focus
  UNION ALL SELECT 20 AS sort_order,'foundations' AS skill_slug,'introductions' AS topic_slug,'a2-de-personal-background' AS slug,'Mein Hintergrund' AS title,'Über Wohnort, Ausbildung, Arbeit und frühere Lebensorte sprechen.' AS objective,2 AS expected_lessons,'Präteritum von sein und haben; seit / vor + Zeitangabe' AS grammar_focus
  UNION ALL SELECT 30 AS sort_order,'family-home' AS skill_slug,'family' AS topic_slug,'a2-de-family-relationships' AS slug,'Familie & Beziehungen' AS title,'Familienmitglieder, Beziehungen und Ähnlichkeiten beschreiben.' AS objective,2 AS expected_lessons,'Possessivartikel im Nominativ/Akkusativ; Komparativ mit als' AS grammar_focus
  UNION ALL SELECT 40 AS sort_order,'family-home' AS skill_slug,'home' AS topic_slug,'a2-de-home-neighborhood' AS slug,'Wohnung & Nachbarschaft' AS title,'Wohnung und Nachbarschaft genauer beschreiben und Vor- oder Nachteile nennen.' AS objective,3 AS expected_lessons,'Wechselpräpositionen bei Ortsangaben; es gibt + Akkusativ' AS grammar_focus
  UNION ALL SELECT 50 AS sort_order,'daily-life' AS skill_slug,'daily-routine' AS topic_slug,'a2-de-routines-frequency' AS slug,'Gewohnheiten & Häufigkeit' AS title,'Alltagsroutinen genauer beschreiben und sagen, wie oft etwas passiert.' AS objective,2 AS expected_lessons,'Adverbien der Häufigkeit; Zeitangaben im Satz: Verbzweit' AS grammar_focus
  UNION ALL SELECT 60 AS sort_order,'daily-life' AS skill_slug,'common-actions' AS topic_slug,'a2-de-last-weekend' AS slug,'Letztes Wochenende' AS title,'Über abgeschlossene Aktivitäten am letzten Wochenende sprechen.' AS objective,3 AS expected_lessons,'Perfekt mit haben und sein; Partizip II häufiger Verben' AS grammar_focus
  UNION ALL SELECT 70 AS sort_order,'daily-life' AS skill_slug,'common-actions' AS topic_slug,'a2-de-past-events' AS slug,'Was ist passiert?' AS title,'Eine kurze Folge vergangener Ereignisse verständlich erzählen.' AS objective,3 AS expected_lessons,'Perfekt in Ereignisfolgen; weil-Sätze mit Verb am Ende' AS grammar_focus
  UNION ALL SELECT 80 AS sort_order,'time-plans' AS skill_slug,'time' AS topic_slug,'a2-de-sequencing-time' AS slug,'Reihenfolge & Zeit' AS title,'Handlungen mit Zeit- und Reihenfolgewörtern verbinden.' AS objective,2 AS expected_lessons,'bevor / nachdem als Zeitverknüpfung; zuerst, dann, später, am Ende' AS grammar_focus
  UNION ALL SELECT 90 AS sort_order,'time-plans' AS skill_slug,'future-plans' AS topic_slug,'a2-de-future-arrangements' AS slug,'Feste Termine' AS title,'Feste Termine und nahe Zukunftspläne vereinbaren.' AS objective,2 AS expected_lessons,'Präsens mit zukünftiger Zeitangabe; am / um / von ... bis' AS grammar_focus
  UNION ALL SELECT 100 AS sort_order,'time-plans' AS skill_slug,'future-plans' AS topic_slug,'a2-de-plans-intentions' AS slug,'Pläne & Absichten' AS title,'Absichten und persönliche Pläne erklären und begründen.' AS objective,3 AS expected_lessons,'vorhaben + zu-Infinitiv; weil für Begründungen' AS grammar_focus
  UNION ALL SELECT 110 AS sort_order,'social' AS skill_slug,'polite-language' AS topic_slug,'a2-de-invitations' AS slug,'Einladen & Verabreden' AS title,'Jemanden einladen, höflich zu- oder absagen und Alternativen vorschlagen.' AS objective,3 AS expected_lessons,'möchtest du / hast du Lust; würde gern für höfliche Reaktionen' AS grammar_focus
  UNION ALL SELECT 120 AS sort_order,'describing' AS skill_slug,'weather' AS topic_slug,'a2-de-seasons-weather-plans' AS slug,'Wetter & Jahreszeiten' AS title,'Wetter vergleichen und Pläne davon abhängig machen.' AS objective,2 AS expected_lessons,'wenn-Sätze für Bedingungen; Komparativ bei Wetterbeschreibungen' AS grammar_focus
  UNION ALL SELECT 130 AS sort_order,'food-drink' AS skill_slug,'food-basics' AS topic_slug,'a2-de-food-quantities' AS slug,'Lebensmittel & Mengen' AS title,'Mengen beim Einkaufen und Kochen verstehen und nennen.' AS objective,3 AS expected_lessons,'viel / wenig und viele / wenige; Maßeinheiten + von' AS grammar_focus
  UNION ALL SELECT 140 AS sort_order,'food-drink' AS skill_slug,'food-basics' AS topic_slug,'a2-de-cooking-recipes' AS slug,'Kochen & Rezepte' AS title,'Einfache Rezepte verstehen und kurze Kochanweisungen geben.' AS objective,3 AS expected_lessons,'Imperativ du/Sie; zuerst, dann, danach zum Strukturieren' AS grammar_focus
  UNION ALL SELECT 150 AS sort_order,'food-drink' AS skill_slug,'restaurants' AS topic_slug,'a2-de-restaurant-service' AS slug,'Im Restaurant' AS title,'Bestellen, nach Zutaten fragen und ein einfaches Serviceproblem lösen.' AS objective,3 AS expected_lessons,'Konjunktiv II: ich hätte / könnte ich; etwas / nichts / noch etwas' AS grammar_focus
  UNION ALL SELECT 160 AS sort_order,'shopping-money' AS skill_slug,'shopping' AS topic_slug,'a2-de-clothes-sizes' AS slug,'Kleidung & Größen' AS title,'Nach Größe, Farbe und Passform fragen und Kleidung anprobieren.' AS objective,2 AS expected_lessons,'passen / stehen + Dativ; zu + Adjektiv: zu groß, zu eng' AS grammar_focus
  UNION ALL SELECT 170 AS sort_order,'shopping-money' AS skill_slug,'shopping' AS topic_slug,'a2-de-compare-products' AS slug,'Produkte vergleichen' AS title,'Produkte nach Preis, Größe, Qualität und Nutzen vergleichen.' AS objective,3 AS expected_lessons,'Komparativ + als; Adjektivsteigerung mit mehr / -er' AS grammar_focus
  UNION ALL SELECT 180 AS sort_order,'shopping-money' AS skill_slug,'prices' AS topic_slug,'a2-de-best-choice' AS slug,'Die beste Wahl' AS title,'Zwischen mehreren Optionen wählen und eine Empfehlung begründen.' AS objective,2 AS expected_lessons,'Superlativ: am besten / der beste; weil-Satz zur Begründung' AS grammar_focus
  UNION ALL SELECT 190 AS sort_order,'travel-transport' AS skill_slug,'transport' AS topic_slug,'a2-de-trip-planning' AS slug,'Eine Reise planen' AS title,'Eine einfache Reise mit Ziel, Verkehrsmittel, Dauer und Budget planen.' AS objective,3 AS expected_lessons,'möchten / wollen für Reisepläne; mit + Dativ und nach/in + Ort' AS grammar_focus
  UNION ALL SELECT 200 AS sort_order,'travel-transport' AS skill_slug,'transport' AS topic_slug,'a2-de-tickets-timetables' AS slug,'Fahrkarten & Fahrpläne' AS title,'Fahrpläne verstehen und eine Fahrkarte kaufen oder ändern.' AS objective,3 AS expected_lessons,'trennbare Verben: abfahren / ankommen; um, ab, bis bei Zeitangaben' AS grammar_focus
  UNION ALL SELECT 210 AS sort_order,'travel-transport' AS skill_slug,'places-town' AS topic_slug,'a2-de-accommodation' AS slug,'Hotel & Unterkunft' AS title,'Einchecken, nach Ausstattung fragen und einfache Wünsche äußern.' AS objective,3 AS expected_lessons,'ist ... im Preis inbegriffen?; höfliche Bitte mit könnte ich' AS grammar_focus
  UNION ALL SELECT 220 AS sort_order,'travel-transport' AS skill_slug,'transport' AS topic_slug,'a2-de-travel-problems' AS slug,'Probleme unterwegs' AS title,'Verspätungen, verpasste Verbindungen und verlorene Dinge erklären.' AS objective,3 AS expected_lessons,'Perfekt für Reiseprobleme; müssen / sollen für nächste Schritte' AS grammar_focus
  UNION ALL SELECT 230 AS sort_order,'travel-transport' AS skill_slug,'directions' AS topic_slug,'a2-de-detailed-directions' AS slug,'Genauere Wegbeschreibung' AS title,'Mehrschrittige Wegbeschreibungen mit Orientierungspunkten verstehen und geben.' AS objective,3 AS expected_lessons,'bis zu / an ... vorbei / über; wohin + Akkusativ bei Richtung' AS grammar_focus
  UNION ALL SELECT 240 AS sort_order,'work-study' AS skill_slug,'jobs' AS topic_slug,'a2-de-work-duties' AS slug,'Aufgaben bei der Arbeit' AS title,'Arbeitsaufgaben, Regeln und einfache Verantwortlichkeiten beschreiben.' AS objective,3 AS expected_lessons,'müssen / dürfen / nicht dürfen; weil bei Begründungen' AS grammar_focus
  UNION ALL SELECT 250 AS sort_order,'work-study' AS skill_slug,'school-study' AS topic_slug,'a2-de-study-habits' AS slug,'Lernen & Fortschritt' AS title,'Lerngewohnheiten, Schwierigkeiten und einfache Lerntipps besprechen.' AS objective,3 AS expected_lessons,'sollte für Ratschläge; wenn-Sätze für Lernstrategien' AS grammar_focus
  UNION ALL SELECT 260 AS sort_order,'daily-life' AS skill_slug,'common-actions' AS topic_slug,'a2-de-abilities-skills' AS slug,'Fähigkeiten & Können' AS title,'Über heutige und frühere Fähigkeiten sprechen.' AS objective,2 AS expected_lessons,'können im Präsens und konnte im Präteritum; gut / besser / am besten' AS grammar_focus
  UNION ALL SELECT 270 AS sort_order,'health-body' AS skill_slug,'basic-health' AS topic_slug,'a2-de-symptoms-pharmacy' AS slug,'Beschwerden & Apotheke' AS title,'Häufige Beschwerden beschreiben und einfache Hinweise in der Apotheke verstehen.' AS objective,3 AS expected_lessons,'seit + Dativ bei Beschwerden; sollte / dürfen bei Gesundheitstipps' AS grammar_focus
  UNION ALL SELECT 280 AS sort_order,'health-body' AS skill_slug,'basic-health' AS topic_slug,'a2-de-appointments-advice' AS slug,'Termine & Rat' AS title,'Einen Termin vereinbaren oder verschieben und einfachen Rat geben.' AS objective,2 AS expected_lessons,'könnte ich für höfliche Terminfragen; sollte / müsste für Rat und Notwendigkeit' AS grammar_focus
  UNION ALL SELECT 290 AS sort_order,'describing' AS skill_slug,'people' AS topic_slug,'a2-de-personality-appearance' AS slug,'Aussehen & Persönlichkeit' AS title,'Aussehen und Persönlichkeit mit einfachen Details beschreiben.' AS objective,3 AS expected_lessons,'aussehen + Adjektiv / wie; Komparative bei Personenbeschreibungen' AS grammar_focus
  UNION ALL SELECT 300 AS sort_order,'travel-transport' AS skill_slug,'places-town' AS topic_slug,'a2-de-describe-places' AS slug,'Orte beschreiben' AS title,'Orte genauer beschreiben und Städte oder Viertel vergleichen.' AS objective,3 AS expected_lessons,'Komparativ und Superlativ bei Orten; es gibt / liegen / befinden sich' AS grammar_focus
  UNION ALL SELECT 310 AS sort_order,'social' AS skill_slug,'hobbies' AS topic_slug,'a2-de-experiences' AS slug,'Erfahrungen im Leben' AS title,'Über Erfahrungen mit schon, noch nie und Perfekt sprechen.' AS objective,3 AS expected_lessons,'Perfekt mit schon / noch nie; warst du schon ...?' AS grammar_focus
  UNION ALL SELECT 320 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'a2-de-phone-messages' AS slug,'Telefonieren & Nachrichten' AS title,'Kurze Telefonate führen, Nachrichten hinterlassen und wichtige Details bestätigen.' AS objective,3 AS expected_lessons,'dass-Satz in indirekten Mitteilungen; könnten Sie / soll ich für Telefonanfragen' AS grammar_focus
  UNION ALL SELECT 330 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'a2-de-online-communication' AS slug,'Chats & kurze Updates' AS title,'Kurze praktische Online-Nachrichten verstehen und schreiben.' AS objective,2 AS expected_lessons,'Zeitformen in kurzen Updates; weil / deshalb in Nachrichten' AS grammar_focus
  UNION ALL SELECT 340 AS sort_order,'social' AS skill_slug,'likes-dislikes' AS topic_slug,'a2-de-opinions-reasons' AS slug,'Meinung & Begründung' AS title,'Eine einfache Meinung äußern, zustimmen oder widersprechen und einen Grund nennen.' AS objective,3 AS expected_lessons,'ich finde / ich glaube + dass; weil und deshalb' AS grammar_focus
  UNION ALL SELECT 350 AS sort_order,'communication' AS skill_slug,'requests' AS topic_slug,'a2-de-everyday-problems' AS slug,'Alltagsprobleme lösen' AS title,'Ein alltägliches Problem erklären, um Hilfe bitten und Lösungen vorschlagen.' AS objective,3 AS expected_lessons,'könnte / würde für höfliche Lösungen; wenn-Satz für Bedingungen' AS grammar_focus
  UNION ALL SELECT 360 AS sort_order,'communication' AS skill_slug,'simple-messages' AS topic_slug,'a2-de-integrated-capstone' AS slug,'A2 Alltag: Alles zusammen' AS title,'Mehrere vertraute A2-Aufgaben in einer zusammenhängenden Alltagssituation bewältigen.' AS objective,4 AS expected_lessons,'Perfekt, Modalverben und Nebensätze im Zusammenspiel; Präsens für Pläne und höfliche Bitten' AS grammar_focus
) u
JOIN courses c ON c.slug='fa-de-de'
JOIN cefr_levels l ON l.code='A2'
JOIN skills s ON s.slug=u.skill_slug
JOIN topics t ON t.slug=u.topic_slug;
