-- Standard Korean C1 curriculum, batch 1, for Persian-speaking learners.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,2,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','ko-KR','batch',1,'grammar_focus',u.grammar_focus)
FROM (
 SELECT 510 sort_order,'communication' skill_slug,'questions' topic_slug,'c1-ko-implicit-meaning-and-subtext' slug,'말보다 맥락이 더 많은 걸 말해요' title,'Interpret implication, presupposition and interpersonal subtext in advanced spoken Korean.' objective,'-기는커녕; -는 셈이다; -다는 말은; 맥락상' grammar_focus
 UNION ALL SELECT 520,'communication','questions','c1-ko-precision-reformulation','정확히 말하면 의미가 조금 달라집니다','Reformulate claims with lexical precision, scope control and advanced clarification.','정확히 말하면; -라기보다; 범위를 한정하면; 다시 표현하자면'
 UNION ALL SELECT 530,'communication','questions','c1-ko-stance-and-hedging','확신의 정도를 말에 드러내야 해요','Control epistemic stance, hedging and degrees of commitment in academic and professional Korean.','-다고 볼 여지가 있다; -을 가능성을 배제할 수 없다; 단정하기에는'
 UNION ALL SELECT 540,'communication','questions','c1-ko-argument-structure','주장보다 논리의 연결이 중요합니다','Build, challenge and repair complex arguments using warrants, counterexamples and logical relations.','-는다는 점에서; -에 비추어 보면; 설령 -더라도; 논거'
 UNION ALL SELECT 550,'communication','requests','c1-ko-formal-mediation-and-face','체면을 지키면서도 핵심은 분명히 말합니다','Mediate disagreement while managing face, hierarchy and accountability in high-stakes Korean interactions.','-는 말씀은 이해합니다만; 외람되지만; -아/어 주셨으면 합니다; 체면'
 UNION ALL SELECT 560,'communication','questions','c1-ko-source-synthesis-and-framing','자료를 합칠 때 관점의 차이도 남겨야 해요','Synthesize multiple sources while preserving attribution, framing differences and unresolved contradictions.','-에 따르면; -라는 관점에서; 반면; 종합하면; 출처'
 UNION ALL SELECT 570,'communication','requests','c1-ko-register-shifting','같은 내용도 장면에 따라 다르게 말합니다','Shift flexibly between formal, professional and intimate registers while preserving intent.','하십시오체/해요체/해체; 높임법; 완곡화; 담화 표지'
 UNION ALL SELECT 580,'communication','requests','c1-ko-institutional-and-bureaucratic-korean','규정의 문구와 실제 적용은 다를 수 있어요','Navigate institutional Korean, interpret regulations and question procedures precisely and respectfully.','-에 의거하여; -에 해당하다; -는 바; 이의 제기; 적용'
 UNION ALL SELECT 590,'communication','questions','c1-ko-humor-irony-and-cultural-nuance','진담인지 농담인지 말투에서 드러나기도 해요','Interpret irony, understatement, playful teasing and culture-dependent pragmatic cues without overgeneralizing.','반어; 과장; 완곡한 비꼼; -기는요; -다니'
 UNION ALL SELECT 600,'time-plans','future-plans','c1-ko-c1-seoul-policy-forum-capstone','서울 정책 포럼에서 근거와 맥락을 함께 조정해 봅시다','Integrate C1 inference, precision, stance, argumentation, mediation, source synthesis, register and institutional language in a Seoul policy forum.','C1 담화 통합: 함축·근거·논증·중재·격식·출처'
) u JOIN courses c ON c.slug='fa-ko-kr' JOIN cefr_levels lvl ON lvl.code='C1' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;
