-- Standard Korean C2 curriculum, batch 1, for Persian-speaking learners.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,2,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','ko-KR','batch',1,'grammar_focus',u.grammar_focus)
FROM (
 SELECT 610 sort_order,'communication' skill_slug,'requests' topic_slug,'c2-ko-register-orchestration' slug,'말투의 높낮이보다 관계의 결을 조율합니다' title,'Orchestrate speech level, stance and interpersonal distance dynamically across complex Korean interactions.' objective,'담화 내 높임 전환; 굳이 -자면; -다고 할까; 메타화용 표지' grammar_focus
 UNION ALL SELECT 620,'communication','questions','c2-ko-compressed-argumentation','짧게 말해도 논증의 뼈대는 남아 있어야 합니다','Interpret and produce compressed arguments with ellipsis, nominalization and recoverable inferential links.','-는 셈이다; -기 마련이다; 명사화; 담화 생략; 전제 복원'
 UNION ALL SELECT 630,'communication','questions','c2-ko-strategic-ambiguity-irony','모호함도 때로는 의도적으로 설계됩니다','Distinguish strategic ambiguity, irony, understatement and plausible deniability from ordinary vagueness.','-다고 해서; -다기보다; -기는커녕; 반어; 의도적 비명시성'
 UNION ALL SELECT 640,'communication','requests','c2-ko-institutional-accountability','누가 무엇을 근거로 책임지는지 끝까지 추적합니다','Handle evidentiality, attribution and accountability in legal, administrative and institutional Korean.','-에 의거하면; -는 것으로 확인되다; -다고 볼 여지가 있다; 책임 귀속'
 UNION ALL SELECT 650,'communication','questions','c2-ko-methodological-critique','결론보다 방법이 무엇을 허용하는지 따집니다','Critique research design, causal claims and methodological limits with calibrated academic Korean.','-다고 단정하기 어렵다; -을 배제할 수 없다; -라는 한계가 있다; 타당도'
 UNION ALL SELECT 660,'communication','questions','c2-ko-media-framing-intertextuality','텍스트는 혼자 말하지 않고 다른 텍스트를 불러옵니다','Analyze framing, quotation, intertextual reference and attribution across sophisticated Korean media discourse.','인용의 재맥락화; -라는 프레임; 전제 공유; 출처 귀속'
 UNION ALL SELECT 670,'communication','requests','c2-ko-high-stakes-negotiation','양보와 약속을 같은 것으로 취급하지 않습니다','Negotiate concessions, commitments and face-threatening disagreements with precise high-stakes Korean.','-는 한; -을 전제로; 양보하더라도; 합의의 조건; 조건부 수용'
 UNION ALL SELECT 680,'communication','questions','c2-ko-essayistic-rhythm-style','문장의 리듬도 논리와 태도를 만듭니다','Control literary-essayistic rhythm, parallelism, nominalization and rhetorical emphasis in sophisticated written Korean.','병렬 구조; 명사화; 문장 길이 변주; 수사적 반복; 논설체'
 UNION ALL SELECT 690,'communication','questions','c2-ko-sociolinguistic-indexicality','말투는 내용뿐 아니라 사회적 위치도 가리킵니다','Analyze sociolinguistic indexicality, identity positioning and style-shifting in standard Korean without stereotyping dialects or groups.','지표성; 스타일 전환; 정체성 수행; 메타언어적 평가'
 UNION ALL SELECT 700,'time-plans','future-plans','c2-ko-c2-seoul-deliberation-capstone','서울 공론장에서 복잡성을 줄이지 않고 합의를 설계합니다','Integrate C2 register control, compressed inference, ambiguity analysis, evidence, negotiation, style and sociolinguistic awareness in a public deliberation capstone.','C2 통합: 지표성·책임 귀속·조건부 합의·방법론적 유보·재맥락화'
) u JOIN courses c ON c.slug='fa-ko-kr' JOIN cefr_levels lvl ON lvl.code='C2' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;
