-- Istanbul Turkish C1 curriculum, batch 1.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,2,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','tr-TR','batch',1,'grammar_focus',u.grammar_focus)
FROM (
 SELECT 510 sort_order,'communication' skill_slug,'simple-messages' topic_slug,'c1-tr-evidential-calibration' slug,'Kesin demek için erken' title,'Calibrate certainty, distinguish direct evidence from inference, and mark epistemic distance in advanced discussion.' objective,'-miş olmalı; görünüşe göre; eldeki verilere göre; kesin demek için erken' grammar_focus
 UNION ALL SELECT 520,'communication','simple-messages','c1-tr-argument-architecture','İddia, gerekçe ve sınır','Build structured arguments with claims, warrants, counterpoints and explicit scope limits.','şu gerekçeyle; bununla birlikte; şu ölçüde; asıl mesele'
 UNION ALL SELECT 530,'communication','simple-messages','c1-tr-reported-stance','Ne dedi, neyi ima etti?','Report others'' claims, distance from them, and preserve differences between quotation, paraphrase and interpretation.','-dığını ileri sürmek; aktarmak; ima etmek; bana göre'
 UNION ALL SELECT 540,'communication','requests','c1-tr-register-shifting','Aynı mesaj, farklı bağlam','Shift register across professional, institutional and familiar contexts without changing core meaning.','rica ederim; memnun olurum; mümkünse; daha doğrudan / daha ihtiyatlı ifade'
 UNION ALL SELECT 550,'communication','simple-messages','c1-tr-nominalization-density','Yoğun ama anlaşılır anlatım','Use nominalizations and dense information packaging while preserving clarity and natural Turkish rhythm.','-me/-ma adlaştırma; -iş; -lık; zincirleme isim gruplarını dengeleme'
 UNION ALL SELECT 560,'social','likes-dislikes','c1-tr-concession-reframing','Haklısın, ama çerçeveyi değiştirelim','Concede valid points, reframe disagreement and redirect discussion toward underlying criteria.','-mekle beraber; her ne kadar; buna karşılık; mesele ... değil ...'
 UNION ALL SELECT 570,'communication','requests','c1-tr-institutional-mediation','İki taraf arasında anlam köprüsü','Mediate between institutional viewpoints, preserve intent and translate jargon into actionable language.','bir başka deyişle; ... açısından; bunu şu şekilde çevirebiliriz; kastedilen'
 UNION ALL SELECT 580,'daily-life','daily-routine','c1-tr-idiomatic-precision','Doğal ama ölçülü ifade','Use idiomatic Turkish collocations and discourse phrases precisely without sounding forced or overly literal.','kalıp birliktelikler; söylem belirteçleri; bağlama göre deyimsellik'
 UNION ALL SELECT 590,'communication','simple-messages','c1-tr-policy-synthesis','Farklı kaynaklardan tek sonuç','Synthesize multiple sources, reconcile tensions and formulate balanced recommendations.','birlikte değerlendirildiğinde; buna karşılık; ortak olarak; sonuç olarak'
 UNION ALL SELECT 600,'travel-transport','places-town','c1-tr-c1-expert-roundtable-capstone','Uzmanlar yuvarlak masada','Integrate C1 evidentiality, argument structure, reporting, register, mediation, lexical precision and synthesis in an expert roundtable.','C1 söylem bütünlüğü; ihtiyatlı iddia; yeniden çerçeveleme; sentez'
) u
JOIN courses c ON c.slug='fa-tr-tr' JOIN cefr_levels lvl ON lvl.code='C1' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;
