-- Istanbul Turkish B1 expansion batch 6: home repair follow-up, volunteer mediation, event-notice reading, sports-membership problem solving.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,3,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','tr-TR','batch',6,'grammar_focus',u.grammar_focus,'third_lesson','independent-production-mediation')
FROM (
 SELECT 570 sort_order,'family-home' skill_slug,'home' topic_slug,'b1-tr-rental-repair-followup' slug,'Evdeki tamiratı takip edip çözüm istemek' title,'Explain a recurring home-repair problem, relay the technician information and negotiate a practical follow-up.' objective,'connected problem account, reported information, sequencing and realistic conditions' grammar_focus
 UNION ALL SELECT 580,'communication','simple-messages','b1-tr-volunteer-orientation-relay','Gönüllülük görevini anlayıp bilgiyi aktarmak','Understand a volunteer orientation, relay key instructions to another person and confirm a practical role.','reported instructions, purpose, sequencing and clarification'
 UNION ALL SELECT 590,'communication','simple-messages','b1-tr-event-notice-and-plan-change','Bir duyuruyu anlayıp planı değiştirmek','Read a practical event notice, identify the key change, explain it to someone else and adjust a shared plan.','reading for key information, reported change, cause-result and plan adjustment'
 UNION ALL SELECT 600,'health-body','basic-health','b1-tr-sports-membership-problem','Spor üyeliği sorununu açıklayıp çözmek','Handle a routine sports-club membership problem, clarify what happened and agree on a practical solution.','problem explanation, reported information, polite clarification and practical solution'
) u
JOIN courses c ON c.slug='fa-tr-tr' JOIN cefr_levels lvl ON lvl.code='B1' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;