-- Istanbul Turkish B1 expansion batch 4: workplace feedback, public service, digital support, volunteer mediation.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,3,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','tr-TR','batch',4,'grammar_focus',u.grammar_focus,'third_lesson','independent-production-mediation')
FROM (
 SELECT 490 sort_order,'work-study' skill_slug,'jobs' topic_slug,'b1-tr-workplace-feedback-and-adjustment' slug,'Geri bildirimi anlayıp çalışma planını değiştirmek' title,'Understand routine workplace feedback, report the main point and agree on a realistic adjustment plan.' objective,'reported feedback, reasons, sequencing and realistic conditions' grammar_focus
 UNION ALL SELECT 500,'travel-transport','places-town','b1-tr-public-service-appointment','Resmî bir randevuda süreci açıklamak','Handle a routine public-service appointment, explain missing information and relay the next practical step.','reported instructions, purpose, polite clarification and sequencing'
 UNION ALL SELECT 510,'communication','simple-messages','b1-tr-digital-support-and-instructions','Teknik bir sorunu anlatıp çözüm adımlarını aktarmak','Describe a familiar digital problem, follow or relay support instructions and explain whether the solution worked.','problem description, reported instructions, sequencing and result'
 UNION ALL SELECT 520,'communication','simple-messages','b1-tr-volunteer-event-mediation','Gönüllü bir etkinlikte planı aktarıp görevleri koordine etmek','Mediate a simple volunteer-event plan, report a change, coordinate roles and solve a practical scheduling problem.','mediation, reported change, reasons, role coordination and realistic conditions'
) u
JOIN courses c ON c.slug='fa-tr-tr' JOIN cefr_levels lvl ON lvl.code='B1' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;
