-- Istanbul Turkish B2 curriculum, batch 1.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,2,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','tr-TR','batch',1,'grammar_focus',u.grammar_focus)
FROM (
 SELECT 410 sort_order,'communication' skill_slug,'simple-messages' topic_slug,'b2-tr-nuanced-stance' slug,'Tam olarak öyle demiyorum' title,'Express a nuanced stance, qualify claims and distinguish partial agreement from endorsement.' objective,'-mekle birlikte; açısından; bana kalırsa' grammar_focus
 UNION ALL SELECT 420,'communication','simple-messages','b2-tr-causes-and-consequences','Bunun tek bir nedeni yok','Explain multi-factor causes, consequences and causal uncertainty in connected discourse.','-dığı için; nedeniyle; yol açmak; bağlı olmak'
 UNION ALL SELECT 430,'time-plans','future-plans','b2-tr-hypothetical-alternatives','Başka türlü olsaydı ne yapardık?','Explore unreal present and past alternatives, trade-offs and counterfactual consequences.','-saydı/-seydi; olurdu; yapmış olsaydık'
 UNION ALL SELECT 440,'communication','requests','b2-tr-formal-negotiation','Şu koşulla kabul edebiliriz','Make formal requests, set conditions and negotiate compromises politely but clearly.','rica etsek; mümkünse; şartıyla; karşılığında'
 UNION ALL SELECT 450,'communication','simple-messages','b2-tr-summarizing-viewpoints','İki görüşün ortak noktası şu','Summarize multiple viewpoints, identify common ground and preserve important distinctions.','bir yandan... öte yandan; ortak nokta; özetlemek gerekirse'
 UNION ALL SELECT 460,'daily-life','daily-routine','b2-tr-relative-detail','Geçen hafta tanıştığım kişi','Build denser descriptions with participial relative clauses and maintain referent clarity.','-(y)An and -DIK relative clauses'
 UNION ALL SELECT 470,'communication','simple-messages','b2-tr-passive-processes','Karar nasıl alındı?','Describe procedures and institutional actions with passive forms while keeping agency clear when relevant.','passive -Il/-In; tarafından; süreç anlatımı'
 UNION ALL SELECT 480,'communication','simple-messages','b2-tr-inference-and-evidence','Bundan şu sonucu çıkarabiliriz','Draw cautious inferences from evidence and distinguish observation from interpretation.','-miş olmalı; anlaşılan; sonucunu çıkarmak'
 UNION ALL SELECT 490,'social','likes-dislikes','b2-tr-concession-and-disagreement','Haklısın, yine de...','Disagree constructively, concede valid points and redirect discussion without sounding abrupt.','-se de; yine de; buna rağmen; mesele şu ki'
 UNION ALL SELECT 500,'travel-transport','places-town','b2-tr-b2-community-forum-capstone','Mahalle forumunda ortak karar','Integrate B2 stance, causality, counterfactuals, negotiation, synthesis, passive processes and evidence in a public discussion.','B2 communicative integration'
) u
JOIN courses c ON c.slug='fa-tr-tr' JOIN cefr_levels lvl ON lvl.code='B2' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;
