-- Istanbul Turkish B1 expansion batch 3: health follow-up, study mediation, consumer resolution, neighborhood change.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,3,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','tr-TR','batch',3,'grammar_focus',u.grammar_focus,'third_lesson','independent-production-mediation')
FROM (
 SELECT 450 sort_order,'health-body' skill_slug,'basic-health' topic_slug,'b1-tr-health-followup-and-advice' slug,'Değişikliği anlatıp tavsiyeyi aktarmak' title,'Describe how a common health problem has changed, relay simple professional advice and explain a realistic follow-up plan.' objective,'change over time, reported advice and realistic conditions' grammar_focus
 UNION ALL SELECT 460,'work-study','school-study','b1-tr-study-group-mediation','Dersi kaçıran arkadaşına bilgiyi aktarmak','Mediate class instructions for an absent classmate, explain task order and coordinate a small study-group plan.','reported instructions, sequencing and purpose'
 UNION ALL SELECT 470,'shopping-money','shopping','b1-tr-purchase-complaint-resolution','Sorunu anlatıp uygun çözümü istemek','Give a coherent account of a product problem, provide relevant purchase details and negotiate a practical solution politely.','short problem narrative, polite requests and realistic solution conditions'
 UNION ALL SELECT 480,'travel-transport','places-town','b1-tr-neighborhood-change-discussion','Mahalledeki değişimi anlatıp öneri sunmak','Describe a visible neighborhood change, explain a personal view with reasons and propose one realistic community action.','past-versus-present contrast, supported opinion and practical proposal'
) u
JOIN courses c ON c.slug='fa-tr-tr' JOIN cefr_levels lvl ON lvl.code='B1' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;
