-- Istanbul Turkish C2 curriculum, batch 1.
INSERT IGNORE INTO curriculum_units (course_id,target_language_id,cefr_level_id,skill_id,topic_id,slug,title,learning_objective,sort_order,expected_lessons,status,metadata)
SELECT c.id,c.target_language_id,lvl.id,s.id,t.id,u.slug,u.title,u.objective,u.sort_order,2,'approved',JSON_OBJECT('language_specific',TRUE,'target_variant','tr-TR','batch',1,'grammar_focus',u.grammar_focus)
FROM (
 SELECT 610 sort_order,'communication' skill_slug,'simple-messages' topic_slug,'c2-tr-epistemic-layering' slug,'Bilginin katmanlarını ayırmak' title,'Distinguish observed facts, inferred explanations, reported claims and provisional judgments with precise epistemic control.' objective,'doğrudan gözlem; çıkarım; rivayet; ihtiyatlı hüküm; -miş görünmek' grammar_focus
 UNION ALL SELECT 620,'communication','simple-messages','c2-tr-counterfactual-causality','Olmasaydı ne olurdu?','Use counterfactual reasoning to test causal claims, separate correlation from mechanism, and articulate alternative causal paths.','eğer ... olmasaydı; -miş olurdu; varsayımsal karşılaştırma; nedensel mekanizma'
 UNION ALL SELECT 630,'communication','simple-messages','c2-tr-semantic-boundaries','Kavramın sınırını çizmek','Negotiate definitions, distinguish neighboring concepts, and show how conclusions change when category boundaries shift.','şu anlamda; X derken; kapsamına almak; birbirinden ayırmak; tanıma bağlı olarak'
 UNION ALL SELECT 640,'communication','simple-messages','c2-tr-implicature-and-pragmatics','Söylenen ile kastedilen','Interpret implicature, stance, irony and politeness cues while preserving plausible alternative readings.','ima; dolaylılık; yüz koruma; ironi; bağlama göre okuma'
 UNION ALL SELECT 650,'communication','requests','c2-tr-legal-institutional-nuance','Bağlayıcı mı, tavsiye mi?','Distinguish obligation, authorization, recommendation and procedural discretion in legal-administrative language.','zorunludur; yetkilidir; uygun görülür; takdir yetkisi; koşula bağlı yükümlülük'
 UNION ALL SELECT 660,'communication','simple-messages','c2-tr-rhetorical-compression','Az sözle çok katman','Compress complex arguments into concise high-register Turkish without deleting qualifications, causal links or contrast.','yoğunlaştırma; eksiltme; buna rağmen; dolayısıyla; özlü ama eksiksiz ifade'
 UNION ALL SELECT 670,'communication','requests','c2-tr-cross-framework-mediation','Aynı sorun, iki ayrı çerçeve','Mediate between incompatible professional frameworks by translating criteria, preserving trade-offs and locating shared decision points.','X açısından; Y diline çevirirsek; ortak payda; ölçüt eşleme; ödünleşim'
 UNION ALL SELECT 680,'communication','simple-messages','c2-tr-live-reformulation','Anında yeniden kurmak','Reformulate a complex claim in real time to repair ambiguity, adjust register and preserve substantive commitments.','başka türlü söylersem; daha doğrusu; şu ayrımı koruyarak; kastım şu'
 UNION ALL SELECT 690,'communication','simple-messages','c2-tr-multi-source-synthesis','Kaynakları tek hükümde birleştirmek','Synthesize partially conflicting sources, weight evidence quality and produce a conclusion that preserves unresolved disagreement.','birlikte değerlendirildiğinde; ağırlık vermek; çelişkiyi korumak; ortak eğilim'
 UNION ALL SELECT 700,'travel-transport','places-town','c2-tr-c2-expert-briefing-capstone','C2 uzman brifingi','Integrate epistemic layering, counterfactual causality, definitional control, pragmatics, normative nuance, mediation, reformulation and synthesis in a high-stakes expert briefing.','C2 bütünleşik söylem; kanıt tartımı; canlı reformülasyon; çerçeve arabuluculuğu; ölçülü sonuç'
) u
JOIN courses c ON c.slug='fa-tr-tr' JOIN cefr_levels lvl ON lvl.code='C2' JOIN skills s ON s.slug=u.skill_slug JOIN topics t ON t.slug=u.topic_slug AND t.skill_id=s.id;
