-- Generated by nova/tts/nova_word_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to words.audio_url and words.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
CREATE TEMPORARY TABLE nova_word_audio_updates (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
CREATE TEMPORARY TABLE nova_word_audio_exclusions (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_word_audio_updates (word_key,lemma,display_form,part_of_speech,translation,text_sha256,audio_url,audio_duration_ms) VALUES
('b1398bd622f4a1688b7be11dbae642b2bef85c78b2e37866b4dabf87f479fe25','Adresse','Adresse','noun','نشانی','79e5cf20de0ba4547fa0d44be6753dbcf6b68f53d1ad2622e5a01cf77ae5905a','nova/audio/words/de-fa/b1/adresse-db0b21f107d6.mp3',1068),
('65558e6b0e89111ef3bc5abd7c26f14b5ce32e97ec5147af10e588a95c1dc5e1','alles','alles','pronoun','همه‌چیز','0ef6ec226337643d31f41812a186ba494b0fc2c9a2fcc45bb3c8cf9a8a0b56c4','nova/audio/words/de-fa/65/alles-753bc8890a84.mp3',836),
('1ec48811c0c2d34cf8829a2d22ee0e8192c9623749474fee856669f3aa2d9993','auch','auch','adverb','هم','f1b7384743db3616cedb2810f40be29bbc3157001a2a7d77f58175bd9f9c02c6','nova/audio/words/de-fa/1e/auch-84d19246fdce.mp3',697),
('ba0f527bfeaa616272efecf64940577f0dcf8fab401eaa23cf404e4c3e048fff','auf','auf','preposition','برای','424c8eda8e3a16a7acb116eaf727794dae25ef5a16bf7dd483e929bd2534391a','nova/audio/words/de-fa/ba/auf-609f7b5de33c.mp3',697),
('efbe26a97d9668fe8745319657c1bc7b7319b37975790ea419a950ba7e9dfac1','aus','aus','preposition','از','2337c37f0721980bcb9acc9fd678f19226f71959ea0f7fae447be7ada79a6a49','nova/audio/words/de-fa/ef/aus-00084d613f0a.mp3',743),
('4958ea238dc19787e8cfa4a0075b2ffb35cd826193a9d90187ed3cbaf03aaf00','Ausgang','Ausgang','noun','خروجی','8728cf4697c2072eb7812d533f662ebc1bf03fb157af0f5b5d9669c179016f90','nova/audio/words/de-fa/49/ausgang-5f7a9c79db38.mp3',975),
('b7343ecec962719b995acee1c4979cc336aa17dfb6ebd5d47e11fc6ffe96b452','Berlin','Berlin','proper_noun','برلین','dad114b6ed7342bac65c79575f6c7ff761ec26b52c1f5f7a9110532973d05df2','nova/audio/words/de-fa/b7/berlin-4606d60337b7.mp3',1115),
('b3978912cccebef3860f1cb73d766a425dfaf8e5469ae5e27ce3d3d953ff0fb8','bis','bis','preposition','تا','96147cdbfd6955d797f628fb510283afaecc1aa5a8735f3fe209ff22746b6258','nova/audio/words/de-fa/b3/bis-7b5fbd7e2f60.mp3',789),
('b8b183cd16c930bb353691ad05d3d8bd11cbb25b01ad6cf5792ce659c292e4f1','bisschen','bisschen','noun','کمی','4845e17a83e25b3088674f1b325120c4c888f40463d03d28b8eb28958b903050','nova/audio/words/de-fa/b8/bisschen-7ebc799be109.mp3',1115),
('1bcab91d670896148f3d3474807b291045542f24d93d3c30f003c46ad5ccfa0c','bitte','bitte','interjection','لطفاً','cca501495f4d40c2a3c570b1f6a372d1b4013c0ed01f6bead1eb64031692503c','nova/audio/words/de-fa/1b/bitte-70d6d2ab17bc.mp3',1068),
('ce49e0940d12b7e847c023b35def812fb53beaf53161127eb4100d68d1359a5f','brauchen','brauchen','verb','لازم داشتن','16a104d33063b4f60d6dbe76337d334cc78414e32bcf792808c19f23abcbde31','nova/audio/words/de-fa/ce/brauchen-8cc7b320c50e.mp3',1068),
('34ab66eae301972626f6618728887fbaa16a6b2106b03e732edb469da46b0d69','da','da','adverb','آنجا','aa58b21b01d6b8a99c1a5856962dbac36c758a79dc0a77c2e013ce2c39ecdc8a','nova/audio/words/de-fa/34/da-1fe34ac66e8d.mp3',743),
('a77be5f1e30586b401ba0c5ff909a74a703314c481f9a09f2b3dffe12e0802b3','Dank','Dank','noun','سپاس','40febf26099508c0d4725f0fdafdc6c810d3f88d6b40cbb91bbbaaf709c8c2e7','nova/audio/words/de-fa/a7/dank-b4851884cef7.mp3',836),
('1366bdf5283c221d21f5ae2f41afc34abf3f402e81db81a2bf3394260f2f7e5b','danke','danke','interjection','ممنون','ff1fd0804def10ad2c64ecd154df22c2d73326ed3e65989e9ce35c01200edd81','nova/audio/words/de-fa/13/danke-ccfeda3d847a.mp3',975),
('17178b308d2a11443b9208aa93380687abee24c351a344668dd02344cdb10407','dann','dann','adverb','پس','06cb6c291501e7d4dd2577fe8753defd6300fb30a11fe2e9f8c74b0a93863621','nova/audio/words/de-fa/17/dann-4088528dd2f3.mp3',1068),
('448fdffa99a054f4ac9eaea89544750f853e825d3adeb1cba19e3a3b3a70f2fa','das','das','pronoun','این','0a7cb27e52927eacabbb7ecc738b0fea50b3967945257c43a67eb753cb465bd0','nova/audio/words/de-fa/44/das-694b91a22352.mp3',975),
('e0c8e2d0ce251d95a53e91888e6d44e057721ffc5a99271439301f3b08637642','dein','dein','determiner','مال تو','37464907b09fda64bf5d81e59e038716f41c458c48c696bb0a615a15f3e3caea','nova/audio/words/de-fa/e0/dein-808a5f68546c.mp3',836),
('f1db31875f020e2c11775e8ad825d74063628c76e8a1d38aee99c0c0886608f0','der','der','article','حرف تعریف مذکر','5050d80d22ecd471ea55df7034042c1e041341ff4066e7f6ff38e20b720df8ea','nova/audio/words/de-fa/f1/der-c16275113775.mp3',836),
('f90238c4a34c64ffa450979791ceb918a7847052103af3fea7aab2fa1c76538a','die','die','article','حرف تعریف مؤنث','a8d79f40ddb79de569d778f1c0b832f9cc266b32274b702cff4ba2b8a0dd1549','nova/audio/words/de-fa/f9/die-34f34726b556.mp3',882),
('2d76f4bebfd2be7bd099ae219338fdec3ca7afd4cef80812af4170ca83b5e1a0','dort','dort','adverb','آنجا','39c21f5b3b359f1e66524755f6ffe25dd2d980176d0048191970365971ae5791','nova/audio/words/de-fa/2d/dort-0391b5151db4.mp3',836),
('5b75fa9139460c4887e6bf61fad80764b82c1434aa04c52cf4486a0a3412f2eb','draußen','draußen','adverb','بیرون','2bf128fb4ef828d38d75079e154396032bd4e122cafda29593141ff09d56a753','nova/audio/words/de-fa/5b/draussen-753dcaf473b0.mp3',1207),
('bb6bd200ca400740a5bc3472453cb70d9fdb6768cd0944446b93b20f012627c5','du','du','pronoun','تو','601b2c2473811afea7864a21e4b965a970afa4ce9eaf85dbdf01414bca66c12c','nova/audio/words/de-fa/bb/du-7a9dcf25ace8.mp3',650),
('7876116fa5e0cf07d24cc70a10526ecc4e430e1fd59d72d748b837a1c96b830d','ein','ein','article','یک','4c3c3030130a4a1b174aa4b0eda1ab26f1ac0c3b88d8fb30e015e3172f356810','nova/audio/words/de-fa/78/ein-466870d04424.mp3',975),
('60bf31402426d31d151ba7fcadb4ae82eee36438372d952cdf473b46c4e5b0dd','Eingang','Eingang','noun','ورودی','d8af5ec4b4ff618a742fa013f137fa37afdb82228968330b48d91d7435633244','nova/audio/words/de-fa/60/eingang-c8f785feb8f2.mp3',1068),
('8545dcd4d8f1890265cbc158fcb9911b73b3f13c37f6ddcdc2d4038b021bce4c','es','es','pronoun','آن','c0bc1e08f9743b2d50d5f1607503bf4e849af0e729fca896515bea955d70a33e','nova/audio/words/de-fa/85/es-e7be53e3b683.mp3',929),
('20c1c12af796d8d8e7c0aab3bfd19f0914582284677dc28ec9ca0f4cb17a2eb6','fahren','fahren','verb','رفتن با وسیله','2372b70bf01af83236aed0ed0d6fc921c655370fa36702a26655e792800a98d1','nova/audio/words/de-fa/20/fahren-d8bbf8206d04.mp3',1022),
('88f3987e139219c24c9f5e9439f629c228ba5cc995ce848d3d86069c4fd219d5','freuen','freuen','verb','خوشحال کردن','6a04bb01375a4d3367d42cb087185fd9c017dc2b18e7bc9e98b25e8e810a2ea8','nova/audio/words/de-fa/88/freuen-baddfa139a82.mp3',1115),
('7dd1bc20b6226437e4dd65769f86cb8910501a830252a707c5364b3cb8870ec3','für','für','preposition','برای','cd23c4c603b344f63dd96d80bc9a0af209d7380ce4faa01bc350e742c364b490','nova/audio/words/de-fa/7d/fuer-7a3996ceb8f4.mp3',975),
('4de6d840c69f59ccf8a0d94708365e65787329d8e64eaf289d2d8ceecf68a9cd','gehen','gehen','verb','رفتن','837ceb63da7920ad96d1be7382221cc7cea1e1d50afdbb4ef3ca2458ba4c8818','nova/audio/words/de-fa/4d/gehen-46443e8f1b10.mp3',1068),
('e804fda131ba85c10564d0dad00298807b8238a5a6ebe5f35be435d6fa683c43','gern','gern','adverb','با میل','bfa14a61e77ecedfe37f4361982d7de5b0c644b9872589044776d68bb2e1f0e9','nova/audio/words/de-fa/e8/gern-81a2f092d33e.mp3',1022),
('c4310c4ae8dae3015c36966a5cd7e1cf637685d84ed65c1fe2fdf85411c1ea9f','geschehen','geschehen','verb','رخ دادن','f12d0fd74696c60377468420eb3975774610f268d501af256d676edd6fd18b75','nova/audio/words/de-fa/c4/geschehen-65fc87b96da9.mp3',975),
('42c072a1f6af083b71a29e9656dcc9c16c1dc3cd884073a96b7030ce3a0db102','gleich','gleich','adverb','به‌زودی','95796228d26d94817ca0766c13ff3018ce6029b1d2be3d659aaa5fb6a5529309','nova/audio/words/de-fa/42/gleich-863dc7f02bae.mp3',929),
('6ee226efb84ac1abc0f97eaacfbd70a51a1fc402d2db733eb89bc044035be4e2','gut','gut','adjective','خوب','77562953d4c8dc074e55e73375e64f65fef94dcddd39381abb5be1ee250e2b1f','nova/audio/words/de-fa/6e/gut-41d5da8b14be.mp3',743),
('875c472faf74f24f66b451e8d4260e595ce1a082089b7ec7e814c066f3c139b6','haben','haben','verb','داشتن','ba9d261f6e9cec059a82b9aa869a70efdfed466cb8f35640bd28dc9c9e87d551','nova/audio/words/de-fa/87/haben-ce2e86a2a282.mp3',1115),
('f479a4e6ddac4ccd62acb7cea47d9a2a8e14b248ab0b658a0cbb9b16baa112b8','hallo','hallo','interjection','سلام','d3751d33f9cd5049c4af2b462735457e4d3baf130bcbb87f389e349fbaeb20b9','nova/audio/words/de-fa/f4/hallo-d335bccfb3fe.mp3',1022),
('d31502e216c97154882b81820f939582e2cedf5d1dedd521e5c5a3fe0af8c55a','Hausnummer','Hausnummer','noun','شمارهٔ خانه','f5cff23f21bc897eb1336e7f180d48735c9f58158068b97d9fd59168069c1b5f','nova/audio/words/de-fa/d3/hausnummer-7fa0422cf11e.mp3',1068),
('c7de5aa68d6f2004350e5111a1891d8d3b0df291a2231263192835973a17c566','heißen','heißen','verb','نام داشتن','d291857f6b4bf46279355394bf9394ead82239e293ab38596bff32a0d7078792','nova/audio/words/de-fa/c7/heissen-c65c900e303b.mp3',1115),
('f8cb8bfdf87bf819046268145e5435ef104fcf5e7060e5e6f5635e5a4022474d','helfen','helfen','verb','کمک کردن','7d00e0f8e43792fdb209ef48c7f471fe204f7e1c3786264e0ebc657cf89cbc0d','nova/audio/words/de-fa/f8/helfen-306767eb5115.mp3',975),
('b3d9fa69277680884c2433cebc991eb80846d7261f38eafac44a20a53dddd290','hier','hier','adverb','اینجا','529cbc8f212773f23d5eceabfdd3e1736c7c063518b43711d03d229866b12d76','nova/audio/words/de-fa/b3/hier-87fade0d8c4c.mp3',1115),
('e7f726c58523a25a8e582394fb120993f4995ee1b3bb83e0e14a82d4ee9a5a82','Hilfe','Hilfe','noun','کمک','95472f650a2b647ff8fa66450c77b281ac2846cbe9d8df6354cbcd8c5e589455','nova/audio/words/de-fa/e7/hilfe-f9fe7e67a073.mp3',1022),
('7338b1d9234e415bcce9d5ae2bb51be9e2998e04697356ed430c4c7767e7fd97','ich','ich','pronoun','من','84c92d8abf326bdb52f1fc6cd6856c41ae9bc1ef4f6056c2672e3d9d301782e1','nova/audio/words/de-fa/73/ich-4d924e30779b.mp3',882),
('7d611f75f38cd6412472fba80a84fafa76a0a07adf535f6f367f6bad180911e0','in','in','preposition','در','582967534d0f909d196b97f9e6921342777aea87b46fa52df165389db1fb8ccf','nova/audio/words/de-fa/7d/in-1027ff46c930.mp3',743),
('a9a57703d51295ba9b3976d7440abbcabf2a6b8c9469f37995488c6a28328bde','Iran','Iran','proper_noun','ایران','18d4e170765cc48842d847de1d0545a2e379e9c87b2af2a6f761681309939ce5','nova/audio/words/de-fa/a9/iran-73a39a4005c1.mp3',836),
('24a103f9406dacdb7512fd4763aa131b0f74a9f1bfc9ce434d462d45558e89ac','ja','ja','interjection','بله','3702fc1866630796050c50e9c829bd32fde7cc4c883f28e3e4ca430307c485b0','nova/audio/words/de-fa/24/ja-c7f60a4f4cf0.mp3',836),
('e6a777662f080bc281d0a6015ac263eaedb363fe01061c9af55b46fe8c3e80bc','Jonas','Jonas','proper_noun','یوناس','9b67e15f271a91f875a2cad35cb8196b79e726f9c5b28e091037d739abc2d7fa','nova/audio/words/de-fa/e6/jonas-a8eeded5e4aa.mp3',975),
('ef3c5c0133d13c200d945e7cd14cda63ff82b49da2dee33cc98d67cb4fe9d839','kennenlernen','kennenlernen','verb','آشنا شدن','4777a22201988c5b2673d0ccf5eb4e9ff8396011b58b8399e87b7722f598c4d3','nova/audio/words/de-fa/ef/kennenlernen-472ef9cd75de.mp3',1300),
('8e242d48d07da37be0c71909368fa88b1e500cd8064f7fedd840a82eb2e8fc2c','klar','klar','adjective','روشن','05045ef3745c9d71468da641ccf02aad1874585562b7cd606ddc06d43a596b01','nova/audio/words/de-fa/8e/klar-3a499db3846e.mp3',929),
('e4f2a8359283325db21ecc036e65b7af6b62ea3a1b45aef3eec8d0b57ff86965','klingen','klingen','verb','به نظر رسیدن','649fec1d87ae8c5c4d717b823f18d59dcb302037cdef85056e64529c0dd35502','nova/audio/words/de-fa/e4/klingen-3ac8e5b1e7b9.mp3',1022),
('0273a4f9912a918ef28fcd0c6d17f9bba7488058b58afb6e56b7cc1f81bb414d','Koffer','Koffer','noun','چمدان','c87ecc82c4d9bc7e4813b247f2703d2a51da3ffb4ddd00b270b9662df6a539cf','nova/audio/words/de-fa/02/koffer-56b021a2a958.mp3',1022),
('14617a7a4d5810513d2ef053d423c61a1937db372071c71fe538e14d4e5615a6','kommen','kommen','verb','آمدن','529f00bc62dff975aab2f1a4700be67e7c93fe78dca238b5347152391219afee','nova/audio/words/de-fa/14/kommen-18f0f6e138a5.mp3',975),
('f70ab4d6af607a9bf72c3b07be866480b732dca7cef71b10335ffd1b4e48a721','Lena','Lena','proper_noun','لنا','92c138b84412fa98ec92b3fdf75f22157d757c8a50de63de2c8ef333c433e085','nova/audio/words/de-fa/f7/lena-9d88086c7add.mp3',836),
('96db001483be818f8a6f7beace851c576626d6d9d62035dc38f00b7a175ff006','los','los','adverb','راه بیفت','cb6e53541e37a1d6076e5b516510607a5f3af6c4c4d7f5ce7ac2ffbd18b340a2','nova/audio/words/de-fa/96/los-9e2aad3e838f.mp3',882),
('9bd807283efe7ce274f07b1ddf9e47e3f2d41d8ea990e7e3988bd2877e56d673','mein','mein','determiner','مال من','25352d33fff0003db2f3df1f4211b8d04eb3e63779d5af061943a0fe05d9f2ee','nova/audio/words/de-fa/9b/mein-cd7c8d38a5b8.mp3',1068),
('89b49d1aaa50f646b0aace5376446d90e6ad7af1137e6633cd5ba6833b140b99','morgen','morgen','adverb','فردا','eb26d4fa531af429ed3f011d6a57fa3379590a5c83adcb93839e36cbe1599531','nova/audio/words/de-fa/89/morgen-1c56d973e5c9.mp3',1115),
('d38c785e67f159edb7b5783a8ca8944e189201a8c0d2a9955e09f896bb0a5239','möchten','möchten','verb','خواستن','d1dcd50f900b4111b00fb2d2198ecd6b328217984ac787058c8ebab25268ca81','nova/audio/words/de-fa/d3/moechten-d1c61412fc66.mp3',1068),
('a1236e4f7edf20f3940201b88397486b0090591a67687cf47d11231ecc9e1647','nach','nach','preposition','به','d941a36dbe67051b56940bde18552222ec741260a9e71cb2a0cb8da396eb7045','nova/audio/words/de-fa/a1/nach-8b1b5f1467f0.mp3',975),
('e63143d951ae63f53fca6c8bc0a29bb1c953b076e695e6492561b5d1af58aa42','nett','nett','adjective','مهربان','d6250021d71ab3632c52093f9e5cdac28b0b1fb4f567f844003a021b38827709','nova/audio/words/de-fa/e6/nett-51a2bea52dae.mp3',836),
('37af0eb6135ee813e430126d977da594a76243455e941c6539c04ca6997c5223','neu','neu','adjective','جدید','b1688cbab7e2c8ad7cf619047e25eed6c9e344ed970badcdacd0e9ec73b08626','nova/audio/words/de-fa/37/neu-d60fc7563edd.mp3',882),
('c9bbd2f4ea13b6e79e1be07c90bfee1cb2bb8b2520f0b25d97be5283ede758f5','Neukölln','Neukölln','proper_noun','نوی‌کلن','98a26a7e0b34d6afa2bec149b1bb3af9e6364b625883c9b3590e9d4facb4bbfe','nova/audio/words/de-fa/c9/neukoelln-febda394a093.mp3',1068),
('b6357fe7018233a8b615df743feed5b16274473999416c81df0f1794d9b37ec4','Nummer','Nummer','noun','شماره','9732e51294688edd0fe5d5ee09cb94532d02bf1c59bb71a54962a3a845d903d7','nova/audio/words/de-fa/b6/nummer-f274a714d0fc.mp3',1161),
('e5ec97802818469236c0fed58ceebf1defd87b8d8feb426a03db38dbbf55c91c','Raha','Raha','proper_noun','رها','bc1532ce0d50e8f914bb459f4afcb6431e4b1381969141bf19e218d57bc27ff4','nova/audio/words/de-fa/e5/raha-4a75ba29f9da.mp3',1068),
('34e3a3d87ab4750fb0c639d0ccbf824f101b464b6f0103900e3809c26ff0746b','richtig','richtig','adjective','درست','953ae3742f333d144636d3a3cd3447453a645d2b76bb09b2200ce764fdc6c2e4','nova/audio/words/de-fa/34/richtig-1f798f354468.mp3',1022),
('a2f970ae7e7ea751df7c415c28ea97f304aa0ec72b2070a2bfc92ac34e3c3040','schwer','schwer','adjective','سنگین','c3c27bacd0e0b53f4e9bea3068736f4b8c08c8b7d35a479baef03e6b1a3c1d37','nova/audio/words/de-fa/a2/schwer-a83631f2a3e3.mp3',975),
('940e06b4fb936c67d093207c3e422aeef45714aea158e70a36c9f6e7b6ce3962','schön','schön','adjective','خوب','1a028e829b255703ecd9ade6ac712e048486eecfbf49d89994839481c772937d','nova/audio/words/de-fa/94/schoen-d394002ff78b.mp3',882),
('416195e5c9069bf09d7559b8de64f83e859e99b1c61f8689f9fa8406c0978d17','sehr','sehr','adverb','خیلی','907114a73986290c82ce7e52f82008a500876df239fd85106f18f91c62b39b9d','nova/audio/words/de-fa/41/sehr-1140f6f40958.mp3',1022),
('54360aaea8c1c8bcf97af4891b0b3567a0f6de077c66d22e359ebaf46f8306e6','sein','sein','verb','بودن','f0abec8675ebc5503c13051760a3052b3f50baf79c5825b6767ec69e82ce501d','nova/audio/words/de-fa/54/sein-50b4d3102f4f.mp3',1022),
('4a365b064a5f244eaafd564880325579cd68e5e7555ead5cb247dbea76e4858f','sie','sie','pronoun','آن','70f0b8e6e13410a6852579add968e46ea8d34d48390f56e70629391bb3534f14','nova/audio/words/de-fa/4a/sie-c0378ea94733.mp3',975),
('3ad86d8fb18c4340d300aced7d842fe3840b3d8a9436d21b68b4a7502504f7ff','speichern','speichern','verb','ذخیره کردن','899da8912848674e7cb9f6538046e92243d1cfb889e389cd21e551ebc1400b13','nova/audio/words/de-fa/3a/speichern-263c4151e6cc.mp3',1068),
('95ef52f48632cf6aff3f4dcc662cf2c3606fc40d8abb48ad7e827c5ba3912cde','Taxi','Taxi','noun','تاکسی','7793c31446e339002451c04738d3480f636a4a3ecc1750c1e23d7907fce3e20f','nova/audio/words/de-fa/95/taxi-107c58ec0db8.mp3',975),
('8b431fc659072c1b8f8600e19efa426d0a337929ca6464b0eb7dba2b7709abc4','Teheran','Teheran','proper_noun','تهران','d4dddc09735e988a6faf0403a937d4953cbf0600fdbac36098611d089527a24f','nova/audio/words/de-fa/8b/teheran-2c7450b15983.mp3',1115),
('0fcc013f7e77709b53f8bb63edf7f4c9f4808d343cad1539feba6255024800c4','Telefon','Telefon','noun','تلفن','fa6906d76ee94d4e8d05a2424fb89005840522ab6dec0ee8055247424977169e','nova/audio/words/de-fa/0f/telefon-3b2578a90556.mp3',1207),
('98e241a61d46ea678bd79d53925a29b964fed85492e0a3d52d6592b3e1e81a3f','viel','viel','determiner','بسیار','8e695edf2a3232521df271fbb9d1e7500cb7008e1a5972b817543f9b4c1adcea','nova/audio/words/de-fa/98/viel-5c5819078284.mp3',882),
('113e2457861e960dfb55a695a217c398cbaedb6eb141e909c662c787953295c6','Viertel','Viertel','noun','محله','ccc8d9c77e6ad775b51f8a071fd51b69d824458b55fc9f6ac5439ac52ff13029','nova/audio/words/de-fa/11/viertel-6ed222e81551.mp3',929),
('80a755d6d710e9a096aef994af8abc4416e8e783b765b83f4589caf8abae0bf8','vor','vor','preposition','جلوی','929f1ca4b2be58d78c26a4fc235d1eefe5e6545232f54fb3e916c564f5754c0e','nova/audio/words/de-fa/80/vor-54f2ec78dae5.mp3',882),
('c7f8ce0c6861e7fa33799f085d625d4e87553af8f368fefacb044a1ab7d88539','warten','warten','verb','منتظر ماندن','227835ebcc7b746ea42de04ec07fab5ccc09b6d6feb2f32543acb2f6231ca53c','nova/audio/words/de-fa/c7/warten-8938ff769374.mp3',1068),
('eb9186e769102c0a531e45f1a266762f3f93ed71efec5aa0264118cd3f2f3784','welche','welche','determiner','کدام','5e368aac938176f8e07881aac04cd81a4467dfcdae9b48eee7b528fa3fd1282d','nova/audio/words/de-fa/eb/welche-fb7f37c3b58a.mp3',929),
('9956891bcddac146fd37f894e0722d3821bacd3771012782b1e5844fe6ccb515','wie','wie','adverb','چطور','4a3f1139f614aab2af8d024c1c3a638ec4d3a00b99f9237ea02b6a69fd74b577','nova/audio/words/de-fa/99/wie-cefcd823d878.mp3',882),
('74bd55d261f442e7f157124d7a15ca0091438e2b73de09cc317f1206c5326d9a','willkommen','willkommen','adjective','خوش‌آمده','6cece6c1ea57f6ef2ca36fcf2cbba7f67cb7ff09f2699664c27294744d3e7a69','nova/audio/words/de-fa/74/willkommen-7c2c2b5e9368.mp3',1161),
('a16d275c3c9a45c5a54db2c537903030199453943af7e5bbfcc05dec06f12273','wir','wir','pronoun','ما','999da4de4d657b8e65d59368748cf17f16cf07f23ee9c164eb43de2c362f606b','nova/audio/words/de-fa/a1/wir-66b2985bf103.mp3',975),
('8166d2c558cbdee2e16cc34581abb75a6ef1f77be0ab8851e6dd4ab489b5b8c5','wo','wo','adverb','کجا','f8f26225fd1d7a1c68981c944df40164266c067a05e6c0cc0a90b8a6cef94b67','nova/audio/words/de-fa/81/wo-0760ea5ac9a8.mp3',789),
('2187ee5263e4c1653544011e7e8d4f9822c4ad46215aceb6a5fea7b80135049a','woher','woher','adverb','از کجا','c58061e325595c5714b8d7c3d89c299ee3d7ec975f6f9ed80632f7e83633fcfd','nova/audio/words/de-fa/21/woher-13730c45ca34.mp3',975),
('7193364b1884f8f9ae10486744af235a1056b3f327edc66615904a64339d9e3c','wohin','wohin','adverb','به کجا','5d0f856ff3a6f5417820c18e482c687f748bea61b20a5fcde30e51795f84c58c','nova/audio/words/de-fa/71/wohin-8a930a7ad356.mp3',975),
('6a9d135c165ec8f0b67625566135265670280dc8f527407a2656155d04d4b70c','wohnen','wohnen','verb','زندگی کردن','4944af70480b82a6c3002d53da795b40fcb6e33323b120a550ed034825360bae','nova/audio/words/de-fa/6a/wohnen-827d4c1da5c5.mp3',929),
('8c41991ad07d25033685add966a887dad5a6dc7425bde810121cafe8eb5fab28','Wohnung','Wohnung','noun','خانه','c91145d16d21c165362dbbdbe19e864d978f0030df1177b1689c231d27298191','nova/audio/words/de-fa/8c/wohnung-abbe9bdc8a9c.mp3',975),
('091e8df3cdc2f59ad0c6b1989d0c5b0f1ef964bf97076a35d6cc3faedfefc31f','zeigen','zeigen','verb','نشان دادن','46c96d17bab4baad86e1f19cd66156ce5d76919d43908c890cb7a0f14d23669d','nova/audio/words/de-fa/09/zeigen-6ef293454692.mp3',1022),
('236089cb9cbbdd43ae8bc83dee2e0237fa7ee546bcf03a8b1a15847ee0822bb1','zu','zu','preposition','به','82cefa8283d30fda9c86f8a976b95d79b395d4cff62a3c8242c7153039bfcde6','nova/audio/words/de-fa/23/zu-0d35cdce246a.mp3',836),
('f56d9be8582471aa6e111cdc9b2078edb52680cc17cc7aedc5cee9bf48116e22','Zuhause','Zuhause','noun','خانه','6f5c5f0e5a9f2cdeff0604bc74cd637f336ff8a3db81882715706cc3278c6383','nova/audio/words/de-fa/f5/zuhause-1a31d35a3a30.mp3',1161),
('5dca2eae30c83521edadca9306f35b7f0eaddca49844892e20dbf05943bc431c','zwölf','zwölf','numeral','دوازده','70f5f8852578418e8af276a8806ffdb14df1de652506a73149f9dec5bd353b13','nova/audio/words/de-fa/5d/zwoelf-11060f2fcea6.mp3',1022);

DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_word_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_cleared INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova de-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_word_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_updates AS u
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY u.lemma
     AND BINARY w.display_form=BINARY u.display_form
     AND BINARY w.part_of_speech=BINARY u.part_of_speech
     AND BINARY w.translation=BINARY u.translation
     AND SHA2(w.display_form,256)=u.text_sha256
    GROUP BY u.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Word locators did not match exactly once.';
  END IF;

  SELECT COUNT(*) INTO v_excluded_expected FROM nova_word_audio_exclusions;
  SELECT COUNT(*) INTO v_excluded_invalid
  FROM (
    SELECT x.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_exclusions AS x
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY x.lemma
     AND BINARY w.display_form=BINARY x.display_form
     AND BINARY w.part_of_speech=BINARY x.part_of_speech
     AND BINARY w.translation=BINARY x.translation
     AND SHA2(w.display_form,256)=x.text_sha256
    GROUP BY x.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_exclusions;
  IF v_excluded_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio cleanup aborted: one or more excluded Word locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE words AS w
  JOIN nova_word_audio_exclusions AS x
    ON BINARY x.lemma=BINARY w.lemma
   AND BINARY x.display_form=BINARY w.display_form
   AND BINARY x.part_of_speech=BINARY w.part_of_speech
   AND BINARY x.translation=BINARY w.translation
   AND x.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=NULL,
      w.audio_duration_ms=NULL
  WHERE w.course_id=v_course
    AND (w.audio_url IS NOT NULL OR w.audio_duration_ms IS NOT NULL);
  SET v_cleared=ROW_COUNT();

  UPDATE words AS w
  JOIN nova_word_audio_updates AS u
    ON BINARY u.lemma=BINARY w.lemma
   AND BINARY u.display_form=BINARY w.display_form
   AND BINARY u.part_of_speech=BINARY w.part_of_speech
   AND BINARY u.translation=BINARY w.translation
   AND u.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=u.audio_url,
      w.audio_duration_ms=u.audio_duration_ms
  WHERE w.course_id=v_course;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_words, v_changed AS changed_words,
         v_excluded_expected AS excluded_words, v_cleared AS cleared_words;
END$$
DELIMITER ;
CALL apply_nova_word_audio();
DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
