-- Generated by nova/tts/nova_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to turns.audio_url and turns.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
CREATE TEMPORARY TABLE nova_turn_audio_updates (
  cefr_level VARCHAR(8) NOT NULL,
  module_order INT UNSIGNED NOT NULL,
  chapter_order INT UNSIGNED NOT NULL,
  lesson_order INT UNSIGNED NOT NULL,
  turn_order INT UNSIGNED NOT NULL,
  character_name VARCHAR(120) NOT NULL,
  turn_role VARCHAR(16) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL,
  PRIMARY KEY (cefr_level,module_order,chapter_order,lesson_order,turn_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_turn_audio_updates (cefr_level,module_order,chapter_order,lesson_order,turn_order,character_name,turn_role,text_sha256,audio_url,audio_duration_ms) VALUES
('A1',1,1,1,1,'Lena','character','357a57fe73d6c63bb1923e970f79a924db3a3609eb9797547784a94ee38fc3df','nova/audio/turns/de-fa/A1/m01/c01/l01/t01-lena-1493be49480b.mp3',511),
('A1',1,1,1,2,'Raha','learner','357a57fe73d6c63bb1923e970f79a924db3a3609eb9797547784a94ee38fc3df','nova/audio/turns/de-fa/A1/m01/c01/l01/t02-raha-cf1d47820f31.mp3',604),
('A1',1,1,1,3,'Lena','character','72aeafe8ca349fbec39677f7cf069380c9004ada302cce31b93f35c5e7d7b0ec','nova/audio/turns/de-fa/A1/m01/c01/l01/t03-lena-6dd96e829a8a.mp3',882),
('A1',1,1,1,4,'Raha','learner','8cedecf7efa81938a37503347b16f373d96413589af8edbdec93b2ff8c3ad19f','nova/audio/turns/de-fa/A1/m01/c01/l01/t04-raha-68ecb220eb18.mp3',1068),
('A1',1,1,1,5,'Lena','character','a0e0b6ca00a4fc7504106fae267e4e9054861fae40b0a957ee04637923e74034','nova/audio/turns/de-fa/A1/m01/c01/l01/t05-lena-507063996839.mp3',1440),
('A1',1,1,1,6,'Raha','learner','dacc874c2bd53ebe5e4e58ff2d986849d5e178e70f823dc9efe9615301ea4b02','nova/audio/turns/de-fa/A1/m01/c01/l01/t06-raha-d82f9768278d.mp3',743),
('A1',1,1,1,7,'Lena','character','603fd66fdedb0ee0c08f49e6d1be499a327bc844cc717889059cdda4ab4d6385','nova/audio/turns/de-fa/A1/m01/c01/l01/t07-lena-eec08611dc8f.mp3',1022),
('A1',1,1,1,8,'Raha','learner','3a7e225e0e49a58a1562cc97e3de2c7118ff17386d99496a7f766b35a3433911','nova/audio/turns/de-fa/A1/m01/c01/l01/t08-raha-16ccc74c89a8.mp3',1022),
('A1',1,1,2,1,'Lena','character','2753e4860651be83bea82179f42ddb29947635c5ea61b047a06924f8c758f042','nova/audio/turns/de-fa/A1/m01/c01/l02/t01-lena-de77aab6c3f3.mp3',650),
('A1',1,1,2,2,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l02/t02-raha-90602ab12d6c.mp3',1254),
('A1',1,1,2,3,'Lena','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c01/l02/t03-lena-71e0b54b140b.mp3',1300),
('A1',1,1,2,4,'Raha','learner','f8a40acf4bd11b129252bfd1d72c523c0a097789e5d57c585dbb7eb9a5f96e6c','nova/audio/turns/de-fa/A1/m01/c01/l02/t04-raha-16dca2285e05.mp3',1022),
('A1',1,1,2,5,'Lena','character','b0989bcc61736fd4e1043d197ee824583ec62a9046be3c3d1bb198068305e699','nova/audio/turns/de-fa/A1/m01/c01/l02/t05-lena-4799dedc7f14.mp3',1440),
('A1',1,1,2,6,'Raha','learner','fb3477536c437fbff9e868eca2c707b355b26224ec1370b1edbf34c8d8ec995f','nova/audio/turns/de-fa/A1/m01/c01/l02/t06-raha-9f171767a63e.mp3',1486),
('A1',1,1,2,7,'Lena','character','826906e3158ba614a5467a953a88af6e4fe8d306540d80227c690efcbddb9dc3','nova/audio/turns/de-fa/A1/m01/c01/l02/t07-lena-0de67b2b05d2.mp3',1486),
('A1',1,1,2,8,'Raha','learner','b197bbc0d88d2e8e6ce929918c5c11477760a36862ee7b67923ee5ceaa31cb4b','nova/audio/turns/de-fa/A1/m01/c01/l02/t08-raha-c5bf21660933.mp3',1022),
('A1',1,1,3,1,'Lena','character','6ce7c885728f88dc6966483fc294056004e1165336e94006b56e038e6ba28c13','nova/audio/turns/de-fa/A1/m01/c01/l03/t01-lena-58c967a0809d.mp3',1300),
('A1',1,1,3,2,'Raha','learner','8c3dcfe2aa7d1bcb671c308d440d7341268290ab37a923d59654a2cd9144eadd','nova/audio/turns/de-fa/A1/m01/c01/l03/t02-raha-7d33dca579f5.mp3',929),
('A1',1,1,3,3,'Lena','character','e5263f2c58b912b2c8e49ffc15f0284857a2859a79007d2fec6798e937305801','nova/audio/turns/de-fa/A1/m01/c01/l03/t03-lena-838ae8ec7008.mp3',1718),
('A1',1,1,3,4,'Raha','learner','ae5c0ac25a8b1ca9c0dfb007444a769df2161af292777288ad608a0930220dc5','nova/audio/turns/de-fa/A1/m01/c01/l03/t04-raha-908065ddec6d.mp3',2183),
('A1',1,1,3,5,'Lena','character','908af5964eb9eedd90a0ea6cb06988a0feb8f5c25dac230dd357c549d06098c5','nova/audio/turns/de-fa/A1/m01/c01/l03/t05-lena-13f2d07e8643.mp3',1347),
('A1',1,1,3,6,'Raha','learner','2770e3d026ef5c0d0804312c22ac067ad3820a568f37c79f9d9361815647d0f5','nova/audio/turns/de-fa/A1/m01/c01/l03/t06-raha-a33f0d528591.mp3',882),
('A1',1,1,3,7,'Lena','character','6892503ab703cfa442b46d1110bd26454b56ef0ea99c49fb99091dc7873c0d41','nova/audio/turns/de-fa/A1/m01/c01/l03/t07-lena-3c47da7f2fec.mp3',789),
('A1',1,1,3,8,'Raha','learner','6e079501d7d8fc6ea8f31958b84424887017c8b4d6165a9250e982d1ce893889','nova/audio/turns/de-fa/A1/m01/c01/l03/t08-raha-876898e77a0d.mp3',1115),
('A1',1,1,4,1,'Lena','character','ce369b547debae3de85388e69795e67bc2394de0cfa0807a3f80aa9586364bcd','nova/audio/turns/de-fa/A1/m01/c01/l04/t01-lena-853ade6f3563.mp3',1533),
('A1',1,1,4,2,'Raha','learner','0d066a8b233ed7cea9c46409136b974ee7758dad3ad9afe63ed02899f4a0d54a','nova/audio/turns/de-fa/A1/m01/c01/l04/t02-raha-d0a645557108.mp3',1161),
('A1',1,1,4,3,'Lena','character','b09ef7c260ad768c20b8939f9a70f528313ce4f80a3e9450644bdb0cb5868e2e','nova/audio/turns/de-fa/A1/m01/c01/l04/t03-lena-b62a568b5b79.mp3',1486),
('A1',1,1,4,4,'Raha','learner','6c854fa89a036eb7b76960984e9fe1cbb73f9f7a393ce8c76c6656498b71b6f1','nova/audio/turns/de-fa/A1/m01/c01/l04/t04-raha-187fc73bcafd.mp3',1718),
('A1',1,1,4,5,'Lena','character','7f20b8f8f6084736ab1fbdf4c949fd2b6f3df7211ce7d6b041ad6e30a1ec4b02','nova/audio/turns/de-fa/A1/m01/c01/l04/t05-lena-8294f63f0c42.mp3',1625),
('A1',1,1,4,6,'Raha','learner','dae124448d15e8fa171dea5f545cc6641a0ca14e268071083f931dc93816f551','nova/audio/turns/de-fa/A1/m01/c01/l04/t06-raha-06c14bc77529.mp3',929),
('A1',1,1,4,7,'Lena','character','0461f787d0c10bce89b4929870ebd3848437bfaeea8e1c3c4eb25ba65f386073','nova/audio/turns/de-fa/A1/m01/c01/l04/t07-lena-96a409d2bff9.mp3',1347),
('A1',1,1,4,8,'Raha','learner','fdd3e155feb43d84a2370005464114c382bd3ca30ee78b47e5b7bb51197b741a','nova/audio/turns/de-fa/A1/m01/c01/l04/t08-raha-2ffecdb6d927.mp3',1207),
('A1',1,2,1,1,'Jonas','character','188ec8cd820a903e3230627954a4b726d62f7a89b13b7e9d6f35ef7c2a663e65','nova/audio/turns/de-fa/A1/m01/c02/l01/t01-jonas-8da9dfe7ea45.mp3',1068),
('A1',1,2,1,2,'Raha','learner','22b1df12f643f6b3b4d1c76455862fb2544e7eba6505a7ce1c545503a8d19a54','nova/audio/turns/de-fa/A1/m01/c02/l01/t02-raha-635e2dafc7e6.mp3',882),
('A1',1,2,1,3,'Jonas','character','3f22e95182a83d53e548ff495c5093369b0f69262a12e0f41469065b9a923e22','nova/audio/turns/de-fa/A1/m01/c02/l01/t03-jonas-2aa9a3ff677e.mp3',1254),
('A1',1,2,1,4,'Raha','learner','a111a6fca0234578fa1d188d569e83313be8fddc26008e7cf8c1750960dda3ec','nova/audio/turns/de-fa/A1/m01/c02/l01/t04-raha-95c6fce34bdd.mp3',1672),
('A1',1,2,1,5,'Jonas','character','ab865dc7a0414dd4e1fed8ce15effca5e3f211f03ba89a7d7864c7f2a7764a66','nova/audio/turns/de-fa/A1/m01/c02/l01/t05-jonas-acebbaa8367d.mp3',1486),
('A1',1,2,1,6,'Raha','learner','208880c8cb2f1bfdac901ecf185cdf47149be4ffe5729a87f01eee48df8206fa','nova/audio/turns/de-fa/A1/m01/c02/l01/t06-raha-413ace24a04a.mp3',1672),
('A1',1,2,1,7,'Jonas','character','b025d712d29eebcaf5b64cc6d71239084a7c58647a247d1bcfed4f90746e3c53','nova/audio/turns/de-fa/A1/m01/c02/l01/t07-jonas-38b552a6c140.mp3',1672),
('A1',1,2,1,8,'Raha','learner','098e5e67a0a82241e28338d60374c7ee9b690f33682ec63f47f1f41861180c41','nova/audio/turns/de-fa/A1/m01/c02/l01/t08-raha-3e3d7044d8c9.mp3',1393),
('A1',1,2,2,1,'Jonas','character','f0868f1cb8283ee321fbd327a2b558ef6bea544db4027667b3f8d7a4ca4d8696','nova/audio/turns/de-fa/A1/m01/c02/l02/t01-jonas-8cdfe717ad50.mp3',1765),
('A1',1,2,2,2,'Raha','learner','4ae1ce63e1bebe134a8a8f6a77f426d508b9043f7c335dc8390c789dd76c979d','nova/audio/turns/de-fa/A1/m01/c02/l02/t02-raha-03682febc43f.mp3',1672),
('A1',1,2,2,3,'Jonas','character','af726889ccb67e21d4be0b8d237fcef89655370914649cf3f0655a54b35445aa','nova/audio/turns/de-fa/A1/m01/c02/l02/t03-jonas-35655ff7220f.mp3',1486),
('A1',1,2,2,4,'Raha','learner','73d3d2e1582df14dfb90fd60a51018fb3e536485942afdad73d7540b9f738e81','nova/audio/turns/de-fa/A1/m01/c02/l02/t04-raha-634b5ac828fd.mp3',1997),
('A1',1,2,2,5,'Jonas','character','f08a938fd9b1b60c302da6165a26594ade7b30fd21a0120b9e2a08d7a7742ddf','nova/audio/turns/de-fa/A1/m01/c02/l02/t05-jonas-8a27e5a3509f.mp3',1950),
('A1',1,2,2,6,'Raha','learner','9baaf1b72e4ac189fba1c2b091eb89b24b294b0e09c899b74f097bc65662a6e9','nova/audio/turns/de-fa/A1/m01/c02/l02/t06-raha-a4c1452912d9.mp3',1765),
('A1',1,2,2,7,'Jonas','character','9f9fbb4fbfddab210111a2091a683c8872a1994fde905d61670c7a8f4c950c69','nova/audio/turns/de-fa/A1/m01/c02/l02/t07-jonas-8a9c4cad554e.mp3',1300),
('A1',1,2,2,8,'Raha','learner','11efe78ad09d0c98f2009d7ffb6d5920a4d6ec814e104063df2e6433c1a343b3','nova/audio/turns/de-fa/A1/m01/c02/l02/t08-raha-71f3057ff84e.mp3',882),
('A1',1,2,3,1,'Jonas','character','d078b01bfeaec67374457d917e1b4c0454400f0c48a1ccfb81cbd56c675693b7','nova/audio/turns/de-fa/A1/m01/c02/l03/t01-jonas-adcd73487013.mp3',2090),
('A1',1,2,3,2,'Raha','learner','2b3cb101af021b9b14b89315ed75d74dbb76767ff73c38faca5f7a5a36e48ba4','nova/audio/turns/de-fa/A1/m01/c02/l03/t02-raha-933f6659675e.mp3',1486),
('A1',1,2,3,3,'Jonas','character','2811514b8e9424e0f4581536a60f9da8f4c831deb7eae4fef658c3ffb79caaa0','nova/audio/turns/de-fa/A1/m01/c02/l03/t03-jonas-6b7c644a6c54.mp3',2415),
('A1',1,2,3,4,'Raha','learner','f21a2ac564bf74c98c705c6cd32c954594d98d618c2aad083106211dde05e4aa','nova/audio/turns/de-fa/A1/m01/c02/l03/t04-raha-885c15cdd7aa.mp3',2090),
('A1',1,2,3,5,'Jonas','character','76d3983ed29bc740321b01025c6e83e71fc7926eb55564e1cfab4e9d499e8f9a','nova/audio/turns/de-fa/A1/m01/c02/l03/t05-jonas-90c9c84258c2.mp3',1579),
('A1',1,2,3,6,'Raha','learner','45a64635b64c0d076f785b8bd41e6284e2c3b64f1daab662ef367e4ba0564450','nova/audio/turns/de-fa/A1/m01/c02/l03/t06-raha-80b203af0921.mp3',1765),
('A1',1,2,3,7,'Jonas','character','851b9875c6e8c226b73f25fe100b3da30d2ba90bc9c755ee55ee8d09243a4c2a','nova/audio/turns/de-fa/A1/m01/c02/l03/t07-jonas-15ec61d51048.mp3',1347),
('A1',1,2,3,8,'Raha','learner','fd2b614bee55adce18b2889ab20529de20f818fd41c0ffd286da3084ffeccffa','nova/audio/turns/de-fa/A1/m01/c02/l03/t08-raha-7ef628cdf8e2.mp3',1161),
('A1',1,2,4,1,'Jonas','character','98c99857209a77769d2be03cf3892dc83d19cf84f528d7c7169a556e17e67b4c','nova/audio/turns/de-fa/A1/m01/c02/l04/t01-jonas-b58a54d083cf.mp3',1579),
('A1',1,2,4,2,'Raha','learner','b7ca37d4e07adace23ba3b3ebc629351ffcb54bce7d787d7565d3d1982bf57aa','nova/audio/turns/de-fa/A1/m01/c02/l04/t02-raha-8d3df2a7b054.mp3',1625),
('A1',1,2,4,3,'Jonas','character','5db1343c728d7f853128baf7eea7d0b8bbddcf87b412500ae8ec4cd8234008de','nova/audio/turns/de-fa/A1/m01/c02/l04/t03-jonas-2817994c615e.mp3',1486),
('A1',1,2,4,4,'Raha','learner','7fa10cdd2d61e404dd2a61cf05ae363ab05b5deae141c2a2825de4fc695bf817','nova/audio/turns/de-fa/A1/m01/c02/l04/t04-raha-467cb37375bd.mp3',1347),
('A1',1,2,4,5,'Jonas','character','01fda9e5948293caadc0acb4ea94ea753ecd7409325b8329333b829f5c1cdcfc','nova/audio/turns/de-fa/A1/m01/c02/l04/t05-jonas-b041c374a824.mp3',1811),
('A1',1,2,4,6,'Raha','learner','886ebe93d7c914a721abdb454e10ef2ec85bbc0407f0bd88ec6a154687630632','nova/audio/turns/de-fa/A1/m01/c02/l04/t06-raha-96de2c5643df.mp3',1161),
('A1',1,2,4,7,'Jonas','character','7749b64a4997d2e48d333896b68766c874bc8c1bfc53383ed73a29cf4526b830','nova/audio/turns/de-fa/A1/m01/c02/l04/t07-jonas-f4e399e63e79.mp3',1625),
('A1',1,2,4,8,'Raha','learner','3839c32da5d43405eb0c4f80a2a092eada48d2031706eb07ef044305540f595d','nova/audio/turns/de-fa/A1/m01/c02/l04/t08-raha-827889a9336e.mp3',1579),
('A1',1,3,1,1,'Lena','character','882d1f3a991a14e61b6e6e1b12bef80c54a8355ca24eb149b94acac66f438e4b','nova/audio/turns/de-fa/A1/m01/c03/l01/t01-lena-040dc1e4adc5.mp3',1672),
('A1',1,3,1,2,'Raha','learner','0f0ba68dd7e11883ac49b82c05f6bbbd20ffbea057dcf7edeaf46db9394892e6','nova/audio/turns/de-fa/A1/m01/c03/l01/t02-raha-19b55136b7fa.mp3',2043),
('A1',1,3,1,3,'Lena','character','2c3c231533fd304b49e9a1b0ce0ee6c9f14e890705b885a139fd24471ac46d6c','nova/audio/turns/de-fa/A1/m01/c03/l01/t03-lena-4feb90089a47.mp3',1347),
('A1',1,3,1,4,'Raha','learner','a7d0befff6af3df8ac660bd42c6fa1bcb8fd9f96262fb21c0f0683ec5230724e','nova/audio/turns/de-fa/A1/m01/c03/l01/t04-raha-1cd959c4dea4.mp3',975),
('A1',1,3,1,5,'Lena','character','d8570818dc93450b842b374d9f6c8980829669b241387e560d03a1f55466d075','nova/audio/turns/de-fa/A1/m01/c03/l01/t05-lena-38728ad8d542.mp3',929),
('A1',1,3,1,6,'Raha','learner','8aea729d1d051a33ccdd81a8fff2c8eca3530541d9031bc2594219c022d0324c','nova/audio/turns/de-fa/A1/m01/c03/l01/t06-raha-95bbcee951cc.mp3',2043),
('A1',1,3,1,7,'Lena','character','c98365cea03604e14d7749ba90e2d8e8bbabf4eaa4409a0f71a828670f9cf112','nova/audio/turns/de-fa/A1/m01/c03/l01/t07-lena-5e0758e25982.mp3',1486),
('A1',1,3,1,8,'Raha','learner','de4c4fa81184c63b2619e598316af951a3e3fb2abe0eb71101b168c5eb758e16','nova/audio/turns/de-fa/A1/m01/c03/l01/t08-raha-d8908b0805a0.mp3',1393),
('A1',1,3,1,9,'Lena','character','a63879ca5f2f9cfaaa044cb4fb495566c66ae4aca7df1f28814e8f8852e352bd','nova/audio/turns/de-fa/A1/m01/c03/l01/t09-lena-4bdd1655ed88.mp3',1300),
('A1',1,3,1,10,'Raha','learner','dae124448d15e8fa171dea5f545cc6641a0ca14e268071083f931dc93816f551','nova/audio/turns/de-fa/A1/m01/c03/l01/t10-raha-10abbcbb2b31.mp3',882),
('A1',1,3,2,1,'Lena','character','a02f14135182b1f4b5e443aca9f6166f8d05f50ce43634d465abf4a3dccafdf3','nova/audio/turns/de-fa/A1/m01/c03/l02/t01-lena-36289b70a7ff.mp3',1533),
('A1',1,3,2,2,'Raha','learner','dbbd030f8c4ac8d936486fb66ee007c240b45e271082212b6eeba81aef8d7891','nova/audio/turns/de-fa/A1/m01/c03/l02/t02-raha-2a0b9ca1455c.mp3',1718),
('A1',1,3,2,3,'Lena','character','40f450ac25902a67d5465ee09cbb0c166b4a0040dec0b8f530ee1b4dd8353e7e','nova/audio/turns/de-fa/A1/m01/c03/l02/t03-lena-cf681131c868.mp3',1625),
('A1',1,3,2,4,'Raha','learner','6e1c3bf4aaf49cdd2550da4e7aa938d66f0618ec61b3e64a9685a2b41cd3e36e','nova/audio/turns/de-fa/A1/m01/c03/l02/t04-raha-b17a36e7aed3.mp3',1579),
('A1',1,3,2,5,'Lena','character','00b07bf96cde381c31b89af5c5ef9e71914b124ed5033022c478092bfd6f89aa','nova/audio/turns/de-fa/A1/m01/c03/l02/t05-lena-b97290e041ad.mp3',1997),
('A1',1,3,2,6,'Raha','learner','3896558e2abe463f3a114c140108220e2d64204b044f7e6d504216fda0f87dd3','nova/audio/turns/de-fa/A1/m01/c03/l02/t06-raha-632dabafbfe8.mp3',1393),
('A1',1,3,2,7,'Lena','character','42275ea881cab3b6093c1f45c7425082178a5d6657fd29814a672ca84db5960b','nova/audio/turns/de-fa/A1/m01/c03/l02/t07-lena-df2b38b60a3a.mp3',1579),
('A1',1,3,2,8,'Raha','learner','725c7954049b5dacc8995fcbdd534fa2aa891bb5b7e408a78bad571b990e3781','nova/audio/turns/de-fa/A1/m01/c03/l02/t08-raha-f1195ad83c2c.mp3',2415),
('A1',1,3,2,9,'Lena','character','a89a8e3655889cc0b5cfa5ccfd9674f43ac2e41a6c9624946333303c757c27e7','nova/audio/turns/de-fa/A1/m01/c03/l02/t09-lena-9081a100e669.mp3',1950),
('A1',1,3,2,10,'Raha','learner','66441522cf300696482156c327673ca50b2334b233206ca305d70ef03cf5d523','nova/audio/turns/de-fa/A1/m01/c03/l02/t10-raha-7bed7bcdd75d.mp3',1904),
('A1',1,3,2,11,'Lena','character','df074002dfe9f599efaf082f63d2fec3412f5533a58e402a193de3b04c2b2978','nova/audio/turns/de-fa/A1/m01/c03/l02/t11-lena-7b46f4eefd1f.mp3',2368),
('A1',1,3,2,12,'Raha','learner','8c3dcfe2aa7d1bcb671c308d440d7341268290ab37a923d59654a2cd9144eadd','nova/audio/turns/de-fa/A1/m01/c03/l02/t12-raha-59a4f9cade98.mp3',1161),
('A1',1,3,3,1,'Lena','character','28854acb7bbf92b459044c0bc4cb571e47918897823741eb1ae5636fe01c9e88','nova/audio/turns/de-fa/A1/m01/c03/l03/t01-lena-93f49f84f4f2.mp3',2136),
('A1',1,3,3,2,'Raha','learner','32b4628c48ab6de7ea7b4670a568e3b5e47110b3ce1c9c2ad7f5b085ef76b07f','nova/audio/turns/de-fa/A1/m01/c03/l03/t02-raha-dfbabe05af97.mp3',1811),
('A1',1,3,3,3,'Lena','character','3c2890b84358ba297c44da9e6ffb9adb91fb4e26e76b5d0904614c4b916c7da6','nova/audio/turns/de-fa/A1/m01/c03/l03/t03-lena-b4786fcf4d9c.mp3',1811),
('A1',1,3,3,4,'Raha','learner','91ba8f8f083e4bb9d9411eef3da1ced7fdef277789f723192a6987eca530a7f4','nova/audio/turns/de-fa/A1/m01/c03/l03/t04-raha-85b74d5bc895.mp3',1533),
('A1',1,3,3,5,'Lena','character','d57b98c4438e293f5c6dc994869e40fcc6d431a4451fd19f2dc4a5da0770221f','nova/audio/turns/de-fa/A1/m01/c03/l03/t05-lena-059008422894.mp3',1579),
('A1',1,3,3,6,'Raha','learner','9eac2bc5afbbeb66b9e30b119dc58dd684b2d0dd2820ca527f1717e60beffc27','nova/audio/turns/de-fa/A1/m01/c03/l03/t06-raha-3df7bc9a9d3c.mp3',1858),
('A1',1,3,3,7,'Lena','character','e259fc5d8f30d7a15722ec8d26ad6b53815a19edc14dcb8178ba152af143198b','nova/audio/turns/de-fa/A1/m01/c03/l03/t07-lena-eff053f7c9a4.mp3',2554),
('A1',1,3,3,8,'Raha','learner','9b57f9caf3da2e7293cce94ba220814e044f53000223903893aef0af9bf92e59','nova/audio/turns/de-fa/A1/m01/c03/l03/t08-raha-4eb1d73409c3.mp3',1022),
('A1',1,3,3,9,'Lena','character','59cf0060302a851fcc0cfc4a41e396aa46a0aaefbd7ff48fb3e13fe4bbbd4f9f','nova/audio/turns/de-fa/A1/m01/c03/l03/t09-lena-02d08ba1d9c7.mp3',1533),
('A1',1,3,3,10,'Raha','learner','bee61fdcf4028d28765f59bae491ac6829d72548626f13fe4753db9f3a9c884d','nova/audio/turns/de-fa/A1/m01/c03/l03/t10-raha-21c559b0e70b.mp3',1393),
('A1',1,3,4,1,'Lena','character','96b3269d84ce0716115144629955e32da51741c46b986f4c4f5837b7bb1a091a','nova/audio/turns/de-fa/A1/m01/c03/l04/t01-lena-6050398931a6.mp3',1625),
('A1',1,3,4,2,'Raha','learner','9653c8d050193c3ff6995cb1f0a082b8900e9895886c90bfb9c1f7b7a430abea','nova/audio/turns/de-fa/A1/m01/c03/l04/t02-raha-38a514ff86bd.mp3',1393),
('A1',1,3,4,3,'Lena','character','4854462c8afe2fa094b0caf55ec55b305c36deb71c0b833329eaed37cf969d6d','nova/audio/turns/de-fa/A1/m01/c03/l04/t03-lena-33451a5620ec.mp3',1161),
('A1',1,3,4,4,'Raha','learner','bcfea9e53bde3b88c5f94ff3af44ead8eaa0fd89b76fbb30c93533ab4b1756a1','nova/audio/turns/de-fa/A1/m01/c03/l04/t04-raha-c1e36ef34f58.mp3',1718),
('A1',1,3,4,5,'Lena','character','f08a938fd9b1b60c302da6165a26594ade7b30fd21a0120b9e2a08d7a7742ddf','nova/audio/turns/de-fa/A1/m01/c03/l04/t05-lena-a6490e091129.mp3',2415),
('A1',1,3,4,6,'Raha','learner','651e71a326347da8895825ac527279ee6330345dbb6dda3c733d250ed3b2b827','nova/audio/turns/de-fa/A1/m01/c03/l04/t06-raha-201dd9def85f.mp3',2229),
('A1',1,3,4,7,'Lena','character','2f63ec0652e53cd7e59a35df250134ce2391d3d397f9613a52c0b077aa037731','nova/audio/turns/de-fa/A1/m01/c03/l04/t07-lena-b94baa6f1d84.mp3',1533),
('A1',1,3,4,8,'Raha','learner','5b8886082f5274ef0018093078b72793aa39142080920ffb8f4a7ff345a7a53e','nova/audio/turns/de-fa/A1/m01/c03/l04/t08-raha-a31ef51716b1.mp3',1672),
('A1',1,3,4,9,'Lena','character','e4992a019949fe5e6a85039d30a13f07cb2da9ee266513013d851fe1681dea41','nova/audio/turns/de-fa/A1/m01/c03/l04/t09-lena-c821890b2e49.mp3',1858),
('A1',1,3,4,10,'Raha','learner','cb00c239d3049ca6f727bbf542a50ed4aa8ef2d9d61cbef9052ec82b4b046091','nova/audio/turns/de-fa/A1/m01/c03/l04/t10-raha-07587a4843e7.mp3',1625),
('A1',1,3,4,11,'Lena','character','a270d74f2174a8a059bbf000f0fd3b4377c847c0ba3aae600eee145d8905dbd0','nova/audio/turns/de-fa/A1/m01/c03/l04/t11-lena-814938c64003.mp3',1022),
('A1',1,3,4,12,'Raha','learner','179f63da20f699ec4a9e210c0a58abe9921c1454a624903dcfe5c8411e81b586','nova/audio/turns/de-fa/A1/m01/c03/l04/t12-raha-ef2f7d3906fe.mp3',2090),
('A1',1,3,4,13,'Lena','character','19aacff0af33cb3fe5633dfee74544d8e3380dcab232b2fae93fee9872e5e0b1','nova/audio/turns/de-fa/A1/m01/c03/l04/t13-lena-ab3e2d5f76bc.mp3',1068),
('A1',1,3,4,14,'Raha','learner','cdaf72d7606c114011b8d335d32be1470876394147987e1130758e4558077350','nova/audio/turns/de-fa/A1/m01/c03/l04/t14-raha-87645ace2493.mp3',1672),
('A1',1,4,1,1,'Lena','character','c622f747de63407eddd65e9a645e63dc5345c85a551a36e4a0094d4520504d2d','nova/audio/turns/de-fa/A1/m01/c04/l01/t01-lena-52067963ffe5.mp3',1161),
('A1',1,4,1,2,'Raha','learner','695f06911a274ab2bc85d35dc335b7f9f5aecb83beb3b0fcba2f11603812dfbe','nova/audio/turns/de-fa/A1/m01/c04/l01/t02-raha-b645cc11ceb0.mp3',1161),
('A1',1,4,1,3,'Lena','character','2cf3113c9a20f4e9a0fa764c1307eddceff63d7075ee06c2c004e715adbc82ff','nova/audio/turns/de-fa/A1/m01/c04/l01/t03-lena-e1513b2b0520.mp3',1811),
('A1',1,4,1,4,'Raha','learner','00d66236f29335b528a3fab3ea511f7f4bec14d306e4da34e2dce3a6047e372d','nova/audio/turns/de-fa/A1/m01/c04/l01/t04-raha-64e8af0e1640.mp3',1207),
('A1',1,4,1,5,'Lena','character','71eea649b3249b034472ada67adabf9747f4dd5eb9a4b29ee18b0f1b9d16bcf8','nova/audio/turns/de-fa/A1/m01/c04/l01/t05-lena-bf5252c5f7ff.mp3',1115),
('A1',1,4,1,6,'Raha','learner','e0c2556f7751a9d9ed20266d508375b0cc81bc1c79fe07e1ee9e3f25b1900637','nova/audio/turns/de-fa/A1/m01/c04/l01/t06-raha-df16bef37f3f.mp3',1161),
('A1',1,4,1,7,'Lena','character','899b37b0f23fd4229cafebd5e0684093a0a96928075dc58863f5db60442c7552','nova/audio/turns/de-fa/A1/m01/c04/l01/t07-lena-93566832ca54.mp3',1579),
('A1',1,4,1,8,'Raha','learner','490f4fdaf45519feafb49517d3fad327902491d9055c79a3dd797e3e94fc4e40','nova/audio/turns/de-fa/A1/m01/c04/l01/t08-raha-3807442f3dfe.mp3',1950),
('A1',1,4,1,9,'Lena','character','239f56ddf87f96bcdfd218ca4ef1b360d4f92a0877cf0cf350196bf950e8e0fb','nova/audio/turns/de-fa/A1/m01/c04/l01/t09-lena-12593295c8bd.mp3',1486),
('A1',1,4,1,10,'Raha','learner','0cb6f7a1f9fd65971ead68e576b83b64c7b519637668087f66701953f89a8481','nova/audio/turns/de-fa/A1/m01/c04/l01/t10-raha-aeccd19827e4.mp3',1486),
('A1',1,4,1,11,'Lena','character','b948f0df2f15c5848e4fa8ff46685a08b64b1ee329e80e5e340b390ecf3349a4','nova/audio/turns/de-fa/A1/m01/c04/l01/t11-lena-84de647ea9b2.mp3',1904),
('A1',1,4,2,1,'Lena','character','44a5e058a3e03490c5c5a786adc41e162a7e2f5a3e60abb361de23e6be5cb471','nova/audio/turns/de-fa/A1/m01/c04/l02/t01-lena-16fb031ccb31.mp3',1486),
('A1',1,4,2,2,'Raha','learner','616a00159aa4a46ab54e1d29dec9fdb718e6fc0c316f8aa598d6f885d9b67d33','nova/audio/turns/de-fa/A1/m01/c04/l02/t02-raha-a4f9b86d355a.mp3',1486),
('A1',1,4,2,3,'Lena','character','857e1907ebdd360fe1fdcf5aed60bf29236fdc1e7d90e53850ff1bd28e1f7e3b','nova/audio/turns/de-fa/A1/m01/c04/l02/t03-lena-5faa6cc81ffb.mp3',1393),
('A1',1,4,2,4,'Raha','learner','682d8086e2f621eff383191143ff9ec3eaa1ec14f461682d593e196fbcc40010','nova/audio/turns/de-fa/A1/m01/c04/l02/t04-raha-202820c8c9e7.mp3',1765),
('A1',1,4,2,5,'Lena','character','e4ce8c6fc5578e6b06a319427f3f77482356f7515cc377d587216f5a3db865ec','nova/audio/turns/de-fa/A1/m01/c04/l02/t05-lena-499bd1caf6be.mp3',1068),
('A1',1,4,2,6,'Raha','learner','b78b27fe18429bd987e5a13e60a0e75ab7bd891437962e5e534036f05d93b628','nova/audio/turns/de-fa/A1/m01/c04/l02/t06-raha-81b75c14b80f.mp3',1486),
('A1',1,4,2,7,'Lena','character','5e5570ca8213ef099610db79e52a903fd8fda7b0fa64892d457ed54920a1a760','nova/audio/turns/de-fa/A1/m01/c04/l02/t07-lena-b7ea0b27ea2b.mp3',1300),
('A1',1,4,2,8,'Raha','learner','bbff6379c508bfcab81c988c9f0f2618904be5ea5541cac5684306c99a73b872','nova/audio/turns/de-fa/A1/m01/c04/l02/t08-raha-e59d9add760c.mp3',1393),
('A1',1,4,2,9,'Lena','character','1bee76b27ca9eab7b16a87c7cec7e06d7c4d5e6de6bd819950f8de07166a6b81','nova/audio/turns/de-fa/A1/m01/c04/l02/t09-lena-7755f59d2fc9.mp3',1625),
('A1',1,4,2,10,'Raha','learner','341bea03a1684d997e238355f67f4b1ce2fdd0bea9cbffbfe6e4034b053d3161','nova/audio/turns/de-fa/A1/m01/c04/l02/t10-raha-ff04e2359dc7.mp3',1811),
('A1',1,4,2,11,'Lena','character','27e8bbedadbb907cd0816e7029a774e745e7417ad4fb692ed07612988fcbb16a','nova/audio/turns/de-fa/A1/m01/c04/l02/t11-lena-e5fe4a49d82e.mp3',1347),
('A1',1,4,2,12,'Raha','learner','14dfdf410f2efd5b8d956fb88ae8b19a0642e423401d4fd26624c4455edae28b','nova/audio/turns/de-fa/A1/m01/c04/l02/t12-raha-343ce4d90dd0.mp3',1207),
('A1',1,4,2,13,'Lena','character','308f0c04db013cbc8e0ecc9c13b53858ca184cfc5a8554dddefbc5f2570acaa5','nova/audio/turns/de-fa/A1/m01/c04/l02/t13-lena-6849390aec87.mp3',1068),
('A1',1,4,3,1,'Lena','character','91b3b84ee427473f2a9852da42c15e21e519fadd4115f2d6df87d88cc13f050a','nova/audio/turns/de-fa/A1/m01/c04/l03/t01-lena-157c0112bb7b.mp3',1347),
('A1',1,4,3,2,'Raha','learner','be38ce8075b051b35c78ae65fe0bbffa453639ae1fcce29497ef9f100c69c195','nova/audio/turns/de-fa/A1/m01/c04/l03/t02-raha-c408e7a3a068.mp3',1440),
('A1',1,4,3,3,'Lena','character','9d1818628c901692bcd20f1854967d8651ad4990b33d77ffa21fc369711d1cab','nova/audio/turns/de-fa/A1/m01/c04/l03/t03-lena-601f2a82620c.mp3',1207),
('A1',1,4,3,4,'Raha','learner','3d10720da0c7a2df07cd3c99c8ae5d9852fb2925ff10518a9e85468ce5e647a2','nova/audio/turns/de-fa/A1/m01/c04/l03/t04-raha-06b5abb65094.mp3',1858),
('A1',1,4,3,5,'Lena','character','d72b9c2495b0f5cb1eaaf2719c2c7a773266c193c72f2d7d2ce9a95b2883aa3a','nova/audio/turns/de-fa/A1/m01/c04/l03/t05-lena-cce401eed5f7.mp3',1950),
('A1',1,4,3,6,'Raha','learner','849ddf18558aeee7d170c27f0e2f5e7641c0bff3b90f108285a62dfed12e9461','nova/audio/turns/de-fa/A1/m01/c04/l03/t06-raha-43d8a49efe7d.mp3',1718),
('A1',1,4,3,7,'Lena','character','c6394e83e83eb971f6b9c87ce442c72b02216b6ac7c215bde8ecacea7cad8f92','nova/audio/turns/de-fa/A1/m01/c04/l03/t07-lena-cccea52cbe1c.mp3',1161),
('A1',1,4,3,8,'Raha','learner','aae396c5a47dfff783f6d396b7a1e49e77f8fe5cedd8a8e09cb85dadc8783eb9','nova/audio/turns/de-fa/A1/m01/c04/l03/t08-raha-b77f84dbde92.mp3',1022),
('A1',1,4,3,9,'Lena','character','e2c75e5327b18498fcfab7a99719c4a9e12b4ebbfbbcf1d34a8796294c80c8fd','nova/audio/turns/de-fa/A1/m01/c04/l03/t09-lena-ce851d98de71.mp3',1115),
('A1',1,4,3,10,'Raha','learner','706514aa6c7e8a20272691170abb68f42a8eef4008a6721781de0adaed15d256','nova/audio/turns/de-fa/A1/m01/c04/l03/t10-raha-c883ff7f4ee0.mp3',1347),
('A1',1,4,3,11,'Lena','character','b6f51e523868205118ebfba8e77ee7e9f153e34bb9b50503213eaf168e4853f7','nova/audio/turns/de-fa/A1/m01/c04/l03/t11-lena-2dbeea881e2b.mp3',1811),
('A1',1,4,3,12,'Raha','learner','33f1793fc2bbbb2d7832de2a4bf1a97994d39fc8ea4eff5af6d55037f8919519','nova/audio/turns/de-fa/A1/m01/c04/l03/t12-raha-11ddd07e1ad0.mp3',1115),
('A1',1,4,4,1,'Lena','character','7a410453e5a536a47f15ff4f3284937827321e80c0ca0ca04182a3cb8aeb8e11','nova/audio/turns/de-fa/A1/m01/c04/l04/t01-lena-26f2de814770.mp3',1579),
('A1',1,4,4,2,'Raha','learner','01faec3f065461d4997f730e966bd474725e66c58578b1d096b17f58a234b98b','nova/audio/turns/de-fa/A1/m01/c04/l04/t02-raha-5046b289a6f2.mp3',1765),
('A1',1,4,4,3,'Lena','character','ec38ccb69e7e672b18f49b6b29f7fe775d88d1e238171330c6ce7565ed5d353c','nova/audio/turns/de-fa/A1/m01/c04/l04/t03-lena-3195c262c507.mp3',2183),
('A1',1,4,4,4,'Raha','learner','64a893ef89a03532a96b376ec62706583e571d2b436e003c094e57c026f06c93','nova/audio/turns/de-fa/A1/m01/c04/l04/t04-raha-8370a89f3cf6.mp3',2786),
('A1',1,4,4,5,'Lena','character','882ee5e6314b692a857f4551308b4db59ce0ed3e944d9b013442bf8c0d4b28dc','nova/audio/turns/de-fa/A1/m01/c04/l04/t05-lena-013337a93c86.mp3',2043),
('A1',1,4,4,6,'Raha','learner','05bebe10fd7bfdcbf3c3e235e9108ad268ad8c50d9a247516a8ef08990af22f8','nova/audio/turns/de-fa/A1/m01/c04/l04/t06-raha-206858da7e65.mp3',1672),
('A1',1,4,4,7,'Lena','character','a949a35c64d7ab4f179d646dc5cc0a0caf7a964da624896742df6e9d4cc65135','nova/audio/turns/de-fa/A1/m01/c04/l04/t07-lena-a7ff66d7aeac.mp3',1486),
('A1',1,4,4,8,'Raha','learner','bf4a84f82c6a2c5ded56d82da6c67e9f68e7eab1e3e33378dab8ab405327dd1d','nova/audio/turns/de-fa/A1/m01/c04/l04/t08-raha-b29510680967.mp3',2554),
('A1',1,4,4,9,'Lena','character','e5b9aafcfa820de7d2919be00e7e9756392433afa61b9d83e2bc0b401cf6c4be','nova/audio/turns/de-fa/A1/m01/c04/l04/t09-lena-d7f6096fcb31.mp3',1625),
('A1',1,4,4,10,'Raha','learner','119bb2e7c5bbb43a88ebbace2da600eff0dd08399bec08f9c0ac89b9acf2bce9','nova/audio/turns/de-fa/A1/m01/c04/l04/t10-raha-4912899756e3.mp3',1533),
('A1',1,4,4,11,'Lena','character','2d4775c0714b15d49754692fa6def1edc3a34cce0d2055eec4daac33f6b9f271','nova/audio/turns/de-fa/A1/m01/c04/l04/t11-lena-2ee5c9b9f962.mp3',1997),
('A1',1,4,4,12,'Raha','learner','41ddce478cea79dd87edbf863d74504f04d26149ebae0a7e51b5c240cf01cc5f','nova/audio/turns/de-fa/A1/m01/c04/l04/t12-raha-be9763d34300.mp3',1811),
('A1',1,4,4,13,'Lena','character','75c94355d447ee78294447296c83527cd9fd6471d87bcce215cb1400794ea6a0','nova/audio/turns/de-fa/A1/m01/c04/l04/t13-lena-bf71a9947ca7.mp3',1440),
('A1',1,4,4,14,'Raha','learner','8a784395f2e4168aafc913994c25564cf059f217fd3313b4d2a26dc6e23799d7','nova/audio/turns/de-fa/A1/m01/c04/l04/t14-raha-50ae67bef422.mp3',1254),
('A1',1,5,1,1,'Lena','character','5c70fcf94953536b5fc7f61a051819a409645bfe187c56f50d050753250f11a6','nova/audio/turns/de-fa/A1/m01/c05/l01/t01-lena-e6953457bbfb.mp3',1254),
('A1',1,5,1,2,'Raha','learner','e954e26a2d0a517bd48ff05c1f456179088dc6c60005b66098cfc59657659bff','nova/audio/turns/de-fa/A1/m01/c05/l01/t02-raha-0674216fe21b.mp3',1486),
('A1',1,5,1,3,'Lena','character','d18a02eaafe8cbc2856bc81e554ec51027608104651b8b32b8460767df02f373','nova/audio/turns/de-fa/A1/m01/c05/l01/t03-lena-023237d736b5.mp3',2043),
('A1',1,5,1,4,'Raha','learner','c203a2d097d7f44c4337911d5b180220623fd4ddd66bea14114564e019138313','nova/audio/turns/de-fa/A1/m01/c05/l01/t04-raha-628a37f0bfbb.mp3',1486),
('A1',1,5,1,5,'Lena','character','91227c128b73aefa955bbed603e8040a736863d0ac3a1c14ecfbc26f28cc00df','nova/audio/turns/de-fa/A1/m01/c05/l01/t05-lena-96740257fa9f.mp3',1533),
('A1',1,5,1,6,'Raha','learner','78fabba0e2d8c675952175c1227399ad1559648ad7db911fa7c2f8eea76d2dee','nova/audio/turns/de-fa/A1/m01/c05/l01/t06-raha-96858ccbceda.mp3',1672),
('A1',1,5,1,7,'Lena','character','6ea2a4e80a66f7ba1020e4ee33c87978920bb433f599da9a945d95ad847151cf','nova/audio/turns/de-fa/A1/m01/c05/l01/t07-lena-abb4b91a06f0.mp3',1904),
('A1',1,5,1,8,'Raha','learner','d908c3d24f7a6ff1dae7c54f1c5199879d5b0a8aaa8012eb04dee4ce96c7023a','nova/audio/turns/de-fa/A1/m01/c05/l01/t08-raha-a449941c0b2f.mp3',1858),
('A1',1,5,1,9,'Lena','character','30bd68e27cb01efd2a06efcb20018806bafa961a2c20e3b4052e737ba6c10876','nova/audio/turns/de-fa/A1/m01/c05/l01/t09-lena-5d00f04cf20d.mp3',1718),
('A1',1,5,1,10,'Raha','learner','e257e628693df627bb62adeb4b439f351bbb5b1a990d346929be8864849ca0af','nova/audio/turns/de-fa/A1/m01/c05/l01/t10-raha-8bf306f85fb5.mp3',1579),
('A1',1,5,2,1,'Lena','character','fc549b2d950fa95d547ee467dd3c5313e15dfdebe7c62cfb99f90feaabe9e5ad','nova/audio/turns/de-fa/A1/m01/c05/l02/t01-lena-9e99c5374807.mp3',1904),
('A1',1,5,2,2,'Raha','learner','25f3962efbf89bf06df9eb3e922a186bc16377be0cd01e0f0ef343ef7d527c4d','nova/audio/turns/de-fa/A1/m01/c05/l02/t02-raha-e2d91ede1e93.mp3',1904),
('A1',1,5,2,3,'Lena','character','f36be2b8c54978627d55a8ce691a0d3637ebff7316021eb9eeaaa39e9a1b2031','nova/audio/turns/de-fa/A1/m01/c05/l02/t03-lena-a3b8d3c29a6e.mp3',1811),
('A1',1,5,2,4,'Raha','learner','ec1476cf49b29c352998a45517a92ee2801cc377ee4a965412b1e95fc24b8065','nova/audio/turns/de-fa/A1/m01/c05/l02/t04-raha-c426259911b8.mp3',1440),
('A1',1,5,2,5,'Lena','character','c9c95f0b7dafe309bfcfb212c3ec42c87578a978c88e9b61f93d98b77a5e4d12','nova/audio/turns/de-fa/A1/m01/c05/l02/t05-lena-089dc68ef53e.mp3',1858),
('A1',1,5,2,6,'Raha','learner','f64719e9d7a1eece800da3963aa3b87ef4b4bab3c626ae0d510b988ab7be91cc','nova/audio/turns/de-fa/A1/m01/c05/l02/t06-raha-e192841d8d6c.mp3',2368),
('A1',1,5,2,7,'Lena','character','1c8a63f2db77231518354003e54af9db191ee7cd6056f98ef0306d2466eae79f','nova/audio/turns/de-fa/A1/m01/c05/l02/t07-lena-f3bc3c4dea19.mp3',2183),
('A1',1,5,2,8,'Raha','learner','b4c1d7f2a3657ffa23059e951875e62953bceaffabefc53751ffb9de4b4b7d9b','nova/audio/turns/de-fa/A1/m01/c05/l02/t08-raha-2f8cd4998ce4.mp3',1858),
('A1',1,5,2,9,'Lena','character','22a96e5e1c733d4a4918a43df9d86e54e37b76605ad079bb59402916abe9c5ce','nova/audio/turns/de-fa/A1/m01/c05/l02/t09-lena-cdcc64210a05.mp3',2368),
('A1',1,5,2,10,'Raha','learner','17e11c885a801d1379479c5161718f386f0a5847a94ff3d512060a4a26f3ba8b','nova/audio/turns/de-fa/A1/m01/c05/l02/t10-raha-ef181ecce036.mp3',1811),
('A1',1,5,2,11,'Lena','character','df6392d9b71461f5748be2a3d84ce5d36befec762295a4316aff38693f015cdc','nova/audio/turns/de-fa/A1/m01/c05/l02/t11-lena-886568778711.mp3',1486),
('A1',1,5,2,12,'Raha','learner','4f10839aaf611bdcb1f31831ea6b04de7acf56e9aff6261c06d7fdf1e2efde65','nova/audio/turns/de-fa/A1/m01/c05/l02/t12-raha-4c5b2e8df5cd.mp3',1533),
('A1',1,5,3,1,'Lena','character','642503943f2f53e08f00ecd79e426e6814ff444afb5df4e3159fa55231e52367','nova/audio/turns/de-fa/A1/m01/c05/l03/t01-lena-fb36639bc8ac.mp3',929),
('A1',1,5,3,2,'Raha','learner','993a665464f810cd7cea97539e3cb5a0184dede1bf297540ea9d0c6a270e9f59','nova/audio/turns/de-fa/A1/m01/c05/l03/t02-raha-c7bd988f99ca.mp3',2461),
('A1',1,5,3,3,'Lena','character','69be4f99ba7da71f5cb3ee0cbc16f873799b82e4e8269eea0d72237945f9af02','nova/audio/turns/de-fa/A1/m01/c05/l03/t03-lena-44295d7c3547.mp3',1765),
('A1',1,5,3,4,'Raha','learner','9d765f68b346264986bf8a721ee88ccd48731c547c2d6bf747bc109c7fff8af2','nova/audio/turns/de-fa/A1/m01/c05/l03/t04-raha-e8d9455822fe.mp3',1625),
('A1',1,5,3,5,'Lena','character','3d7e6a3bbca2efd8ff03a3b3770c4933a6be8bfea3d5972ab5ee1f87a4dc3548','nova/audio/turns/de-fa/A1/m01/c05/l03/t05-lena-e7e7012047c0.mp3',2554),
('A1',1,5,3,6,'Raha','learner','8dfadd2930351f1b68c48c6e2530c31346de169039d5a26b19b8a3f8b50a9a53','nova/audio/turns/de-fa/A1/m01/c05/l03/t06-raha-003ee722bf16.mp3',1672),
('A1',1,5,3,7,'Lena','character','caca60011b659727c5c9649873381f1b079291ca89b4218825aa892870b6b80b','nova/audio/turns/de-fa/A1/m01/c05/l03/t07-lena-662995096039.mp3',1950),
('A1',1,5,3,8,'Raha','learner','fee3dc645634757b7d6be32d01dd90b123cf04b90ee38451011e10beafd7815a','nova/audio/turns/de-fa/A1/m01/c05/l03/t08-raha-d89c4f3447b3.mp3',1765),
('A1',1,5,3,9,'Lena','character','112b1c80d901f018e165ad3676f06605e3eec975c61ebba3b9ffae70c2bc9c52','nova/audio/turns/de-fa/A1/m01/c05/l03/t09-lena-b697723be2e7.mp3',2043),
('A1',1,5,3,10,'Raha','learner','4a00adf7317bdc46c19d11d843d565d8b45fd4ffb2cb5a552ef2c5b8e372f0ed','nova/audio/turns/de-fa/A1/m01/c05/l03/t10-raha-33c9660a6639.mp3',1533),
('A1',1,5,4,1,'Lena','character','5219ed3b26de47e8c6fcfb05e1dabcc290faad5848ac0266634d34ced027520e','nova/audio/turns/de-fa/A1/m01/c05/l04/t01-lena-eb5ecc88f065.mp3',1625),
('A1',1,5,4,2,'Raha','learner','f2118bb82ab3f0cc72544deb4037755047bc14b1113296daaff6a2046dd95333','nova/audio/turns/de-fa/A1/m01/c05/l04/t02-raha-f07429c26f84.mp3',1950),
('A1',1,5,4,3,'Lena','character','e768578d65ae55e01ba621d7dd288e7b4931cbb88977a0bad6c0de31b8271700','nova/audio/turns/de-fa/A1/m01/c05/l04/t03-lena-a9178cca0db5.mp3',1579),
('A1',1,5,4,4,'Raha','learner','7d21b96113cd4acc4115bf4cbf7aedf084cffc0432a931c9de3b404f419c637e','nova/audio/turns/de-fa/A1/m01/c05/l04/t04-raha-cded30bae12f.mp3',1533),
('A1',1,5,4,5,'Lena','character','103d0a7cb708ff8ebb8dff02bea3e1b450cd4770ee5abcce141087da3bc87fca','nova/audio/turns/de-fa/A1/m01/c05/l04/t05-lena-e60a718ad06b.mp3',1672),
('A1',1,5,4,6,'Raha','learner','005e01f85cd2360a5f888d7a1f6e875fc996aea52c1bb682ee20ffff037228f6','nova/audio/turns/de-fa/A1/m01/c05/l04/t06-raha-240ecc12b555.mp3',1440),
('A1',1,5,4,7,'Lena','character','a49d58a39aa3a50ca7743d62f3507ef99fa521671e11d54fae0722a8c67183de','nova/audio/turns/de-fa/A1/m01/c05/l04/t07-lena-be6209591f76.mp3',1533),
('A1',1,5,4,8,'Raha','learner','1ea26bb107d9eb8b242db617d02a9eab81faf87cab4bd5ce2d055ce84c675907','nova/audio/turns/de-fa/A1/m01/c05/l04/t08-raha-091e612a7933.mp3',1765),
('A1',1,5,4,9,'Lena','character','bd649fb103dc57007504bbcc81d8f6aedbcd9870531ac85aceeaae48cd6e0cfa','nova/audio/turns/de-fa/A1/m01/c05/l04/t09-lena-4d58a18af5e4.mp3',1811),
('A1',1,5,4,10,'Raha','learner','07851a540f42fdf4436593e7d8b3bc1c1ef2df0734af7ffcacbe908bbdc6528e','nova/audio/turns/de-fa/A1/m01/c05/l04/t10-raha-1ba7ff146757.mp3',2090),
('A1',1,5,4,11,'Lena','character','8f3c51672c79ee7be387e1ff13488b68b2a4c532b1af7b9f2772651b075d40c2','nova/audio/turns/de-fa/A1/m01/c05/l04/t11-lena-e96349aea2c0.mp3',1997),
('A1',1,5,4,12,'Raha','learner','40569d59239b2da782394323ce5514e9867ed025a08856ab718b77f1d4663eab','nova/audio/turns/de-fa/A1/m01/c05/l04/t12-raha-0a0b9123ae25.mp3',1625),
('A1',1,5,4,13,'Lena','character','19aacff0af33cb3fe5633dfee74544d8e3380dcab232b2fae93fee9872e5e0b1','nova/audio/turns/de-fa/A1/m01/c05/l04/t13-lena-1a42ffb3a9b9.mp3',1022),
('A1',1,5,4,14,'Raha','learner','45a64635b64c0d076f785b8bd41e6284e2c3b64f1daab662ef367e4ba0564450','nova/audio/turns/de-fa/A1/m01/c05/l04/t14-raha-469a18e222ca.mp3',1625),
('A1',1,6,1,1,'Lena','character','d9ebaa61dea1ebde95ec58c4e04a591c6e12727e10ee3d0543ca529a91a027fd','nova/audio/turns/de-fa/A1/m01/c06/l01/t01-lena-c4a7f3892d1a.mp3',1904),
('A1',1,6,1,2,'Raha','learner','ba706e04141cb1900896ae4545298ad400afb6ca1c177ca66164cb44a08f2a18','nova/audio/turns/de-fa/A1/m01/c06/l01/t02-raha-9cbdde466079.mp3',1950),
('A1',1,6,1,3,'Lena','character','4f69206d8868b546833e91d8794b76f2244379a42849ed3ada27d2fac7a456e8','nova/audio/turns/de-fa/A1/m01/c06/l01/t03-lena-2e83018dfc04.mp3',1300),
('A1',1,6,1,4,'Raha','learner','e32bdc7c4553f92940a4fcaf7d4422a35b08ca74f79906e0f5100f58b3ea175f','nova/audio/turns/de-fa/A1/m01/c06/l01/t04-raha-b811154eb54f.mp3',2043),
('A1',1,6,1,5,'Lena','character','dcd47cfb6569862dab9c2dc63d586bbafb74521a7c06e95d2669ae4699d64767','nova/audio/turns/de-fa/A1/m01/c06/l01/t05-lena-9d37ee59a8d1.mp3',1811),
('A1',1,6,1,6,'Raha','learner','586c676174668029ce5c47ab32226a323d3cd8385f8c4dea37f472833c07fa05','nova/audio/turns/de-fa/A1/m01/c06/l01/t06-raha-3880c56829e0.mp3',2136),
('A1',1,6,1,7,'Lena','character','17a4e91389cf7d0c18cf0ffb7c9379e3532bf8e1ab61d8d05085e1b456c0a4b8','nova/audio/turns/de-fa/A1/m01/c06/l01/t07-lena-9c15dd78afe6.mp3',2090),
('A1',1,6,1,8,'Raha','learner','cfc91e4397f1a0858599bc63ef680dffc2ed4fa71dd58ae50ad4acb9619ad978','nova/audio/turns/de-fa/A1/m01/c06/l01/t08-raha-d38f0aba81f6.mp3',1811),
('A1',1,6,1,9,'Lena','character','c639898cc5d37bd2a5818d98afb8f89f7c39bfff527fc4cbd59ef35874cec095','nova/audio/turns/de-fa/A1/m01/c06/l01/t09-lena-2b4abf1fdc40.mp3',1625),
('A1',1,6,1,10,'Raha','learner','757d96fd16c65f6bc815e7a9a1d9d3679a177e87da417b8b01a88a3b9ca9fb0a','nova/audio/turns/de-fa/A1/m01/c06/l01/t10-raha-30aab0bb9689.mp3',1440),
('A1',1,6,1,11,'Lena','character','803f39027615a1d472d61f4cc91409446ed3df80a428246bd09758469ec30e81','nova/audio/turns/de-fa/A1/m01/c06/l01/t11-lena-15a29986b58f.mp3',1533),
('A1',1,6,2,1,'Lena','character','ff8155115ec559ac7be36b78407cb1259515a2a96c7f7ca29b8a0cbeccecb736','nova/audio/turns/de-fa/A1/m01/c06/l02/t01-lena-5fcf8a82d890.mp3',1254),
('A1',1,6,2,2,'Raha','learner','a7b3eb34c465d1d887ff9ac1b7ce1b68293223a763f7b8ab0e8a930edfae8154','nova/audio/turns/de-fa/A1/m01/c06/l02/t02-raha-99fee3e62dfe.mp3',1625),
('A1',1,6,2,3,'Lena','character','feee9f904a995a9df36b2d683b29f57c6e3a331960d79b42c9c98ad771dca334','nova/audio/turns/de-fa/A1/m01/c06/l02/t03-lena-c0423d97609e.mp3',1533),
('A1',1,6,2,4,'Raha','learner','ddbe2cd6c8cf14b55ec7da874396f916265fb6e1f0af85da8daa177d311696ef','nova/audio/turns/de-fa/A1/m01/c06/l02/t04-raha-b4706e10b456.mp3',1858),
('A1',1,6,2,5,'Lena','character','29e2dcb9d988747e9918adf5ad059cc3dd1b1ed29e260197b722839b4df252a9','nova/audio/turns/de-fa/A1/m01/c06/l02/t05-lena-eb26475209a6.mp3',1904),
('A1',1,6,2,6,'Raha','learner','20af6f5671896e04b7b117b007ee2162b0092349430dbcf2e81543e4b4dbf61f','nova/audio/turns/de-fa/A1/m01/c06/l02/t06-raha-bc7d64f00f3c.mp3',2043),
('A1',1,6,2,7,'Lena','character','adf2427585dc14432d44c92090fa339d1043d4300f9b4422680f53d090cfee2a','nova/audio/turns/de-fa/A1/m01/c06/l02/t07-lena-19e062898972.mp3',1625),
('A1',1,6,2,8,'Raha','learner','b99ebd1c2d5ee5cc2e076654da1053b50115a321561a64a3d35c8e9580c15347','nova/audio/turns/de-fa/A1/m01/c06/l02/t08-raha-b50d725448ba.mp3',1718),
('A1',1,6,2,9,'Lena','character','a153c5660133e97d3ea283f26ce8e98729692ee69d4b1eda55f86d08e299d1ad','nova/audio/turns/de-fa/A1/m01/c06/l02/t09-lena-4102a8443148.mp3',1765),
('A1',1,6,2,10,'Raha','learner','1a1118dc2cbfd837e66714bbd28b03e873b5b047db81f7c3289c79cedcf13c5a','nova/audio/turns/de-fa/A1/m01/c06/l02/t10-raha-f4350973ecda.mp3',1393),
('A1',1,6,2,11,'Lena','character','5b5cbfc53fb3df6a4bff9f62600644c47efb69ee80532790a8a0f78106578170','nova/audio/turns/de-fa/A1/m01/c06/l02/t11-lena-ac046548397c.mp3',1115),
('A1',1,6,2,12,'Raha','learner','f259986b5162c578fe22c2eb53b68486e2ac01d6974a09b3b17f0eb5d8536c50','nova/audio/turns/de-fa/A1/m01/c06/l02/t12-raha-df5d4669d8e4.mp3',1533),
('A1',1,6,3,1,'Lena','character','7d0582d83af780fcc90c9512f8ee0773eaa830169826a0331bd22f4f9f3e7cc9','nova/audio/turns/de-fa/A1/m01/c06/l03/t01-lena-5257bc96c99b.mp3',1811),
('A1',1,6,3,2,'Raha','learner','d8bcf81d44f518afb7e55b809ec57f9dc271bc253a33abdbecf31ae2ecb41546','nova/audio/turns/de-fa/A1/m01/c06/l03/t02-raha-425374d2b44e.mp3',1765),
('A1',1,6,3,3,'Lena','character','2db3620f0fb2fe098d4fdf4aa8f045f96b78d297160e0867e1910c2c3e04d4a3','nova/audio/turns/de-fa/A1/m01/c06/l03/t03-lena-f02f0dc54442.mp3',1997),
('A1',1,6,3,4,'Raha','learner','d75d5851c669efac8a56649b9b8e658c85fd14bb3f059b0b6755242db8de94dd','nova/audio/turns/de-fa/A1/m01/c06/l03/t04-raha-0abb2864e1a0.mp3',1765),
('A1',1,6,3,5,'Lena','character','ab67c0b95844b53ec8ff0ba5f0c3db4f22abb2d2d824dacaeed9833c882e6780','nova/audio/turns/de-fa/A1/m01/c06/l03/t05-lena-b13ff68e144b.mp3',2043),
('A1',1,6,3,6,'Raha','learner','0cce18f53604dbfea859b945e535a822687ca97943a846cdb43b5416d9061a53','nova/audio/turns/de-fa/A1/m01/c06/l03/t06-raha-4b2591ea50ad.mp3',1904),
('A1',1,6,3,7,'Lena','character','892c317f390587d0158fe55ea21be90720a5404e1127e8dc7c7ea913748ac223','nova/audio/turns/de-fa/A1/m01/c06/l03/t07-lena-620fe01142f6.mp3',1254),
('A1',1,6,3,8,'Raha','learner','f0b890588949dd716921d76490d5eab68cd91ea19ea92d0ddb8d2fc3baa6ef78','nova/audio/turns/de-fa/A1/m01/c06/l03/t08-raha-c28b7c43779d.mp3',1161),
('A1',1,6,3,9,'Lena','character','1991e6d6c03f9f711d68c00a1c79ad40df08cb4ef612a28c8ddc1585c3a638e6','nova/audio/turns/de-fa/A1/m01/c06/l03/t09-lena-4fb935674afa.mp3',1347),
('A1',1,6,3,10,'Raha','learner','228f04ef00898745165d941cf2def81e736bdec82548f1c0753a527a8b2c04b0','nova/audio/turns/de-fa/A1/m01/c06/l03/t10-raha-7a705548db3e.mp3',1300),
('A1',1,6,4,1,'Lena','character','7980afba2efce470e34a58937e1147ec435b7ae0dc03d1475ddb754730590b6c','nova/audio/turns/de-fa/A1/m01/c06/l04/t01-lena-c71016aebdf2.mp3',1579),
('A1',1,6,4,2,'Raha','learner','c2a6f90b8c6ff7c8bf4dfb9153313af2b076eced4f5b16c1eed8c674093a8d75','nova/audio/turns/de-fa/A1/m01/c06/l04/t02-raha-cd6bc94a58ae.mp3',1486),
('A1',1,6,4,3,'Lena','character','5a4d7658b3f88371448def29d470ae93007e65eb204c0c7414a45cc9ed8be875','nova/audio/turns/de-fa/A1/m01/c06/l04/t03-lena-1f66b3a519f9.mp3',2183),
('A1',1,6,4,4,'Raha','learner','3986b45a56e0e743e262b95313c8e2821bc8a5da9eca0489140ce208a5117c06','nova/audio/turns/de-fa/A1/m01/c06/l04/t04-raha-963a455d4eb5.mp3',2554),
('A1',1,6,4,5,'Lena','character','2edfa95d67cd9c483cd3a916c45f8f8d879e50ce20e3fc8d738931120502b4e1','nova/audio/turns/de-fa/A1/m01/c06/l04/t05-lena-d179ccc3a8cd.mp3',1625),
('A1',1,6,4,6,'Raha','learner','f6559bbb6bd468b1422ea63dcbe3f861a0b205a6795f50d62398168b778e858e','nova/audio/turns/de-fa/A1/m01/c06/l04/t06-raha-bd48703f2dec.mp3',1625),
('A1',1,6,4,7,'Lena','character','c32db9e67dc90c03bc23249bb37a9e3b4a832d6fa5c9ad16e029ddb3b548da5c','nova/audio/turns/de-fa/A1/m01/c06/l04/t07-lena-cdd8731afc8d.mp3',1904),
('A1',1,6,4,8,'Raha','learner','f9474f6efffc79719133f250ead41e507b9dba9da1d2e61f7af2e1a7cdb1bbf6','nova/audio/turns/de-fa/A1/m01/c06/l04/t08-raha-819502c9d3f5.mp3',1997),
('A1',1,6,4,9,'Lena','character','7a410453e5a536a47f15ff4f3284937827321e80c0ca0ca04182a3cb8aeb8e11','nova/audio/turns/de-fa/A1/m01/c06/l04/t09-lena-e3b5bc2fdb5e.mp3',1718),
('A1',1,6,4,10,'Raha','learner','914117b36c8ec3e5bcae054936ebea70c01664c281a8322406a7ef969bba1a97','nova/audio/turns/de-fa/A1/m01/c06/l04/t10-raha-e976891fd253.mp3',1765),
('A1',1,6,4,11,'Lena','character','91f441537e5205ef55c978b03f41bf2d70be41df5b4d21709cdb7681a78293cf','nova/audio/turns/de-fa/A1/m01/c06/l04/t11-lena-8439dfc0a714.mp3',1161);

INSERT INTO nova_turn_audio_updates (cefr_level,module_order,chapter_order,lesson_order,turn_order,character_name,turn_role,text_sha256,audio_url,audio_duration_ms) VALUES
('A1',1,6,4,12,'Raha','learner','66cf62250dc1943f6e2800d4729a38bd1357c02ce74750569717948f465d358d','nova/audio/turns/de-fa/A1/m01/c06/l04/t12-raha-96ab101de74a.mp3',1533),
('A1',1,6,4,13,'Lena','character','e64f10c4b047c6de03bd205e97b09b1cb30465433d7e7cee75b9873ad934e890','nova/audio/turns/de-fa/A1/m01/c06/l04/t13-lena-577e97b51c84.mp3',2276),
('A1',1,6,4,14,'Raha','learner','0e026383672c86bcad29533177ec5d582630df23790bc4d1ef7e7c401811b32b','nova/audio/turns/de-fa/A1/m01/c06/l04/t14-raha-6d5e708693fa.mp3',1950);

DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_turn_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova de-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_turn_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order,
           COUNT(c.id) AS matched_rows
    FROM nova_turn_audio_updates AS u
    LEFT JOIN levels AS lv
      ON lv.course_id=v_course AND lv.cefr_level=u.cefr_level
    LEFT JOIN modules AS m
      ON m.level_id=lv.id AND m.sort_order=u.module_order
    LEFT JOIN chapters AS ch
      ON ch.module_id=m.id AND ch.sort_order=u.chapter_order
    LEFT JOIN lessons AS l
      ON l.chapter_id=ch.id AND l.sort_order=u.lesson_order
    LEFT JOIN turns AS t
      ON t.lesson_id=l.id AND t.sort_order=u.turn_order
     AND t.role=u.turn_role AND SHA2(t.text,256)=u.text_sha256
    LEFT JOIN characters AS c
      ON c.id=t.character_id AND c.course_id=v_course AND c.name=u.character_name
    GROUP BY u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order
    HAVING COUNT(c.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Turn locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE turns AS t
  JOIN lessons AS l ON l.id=t.lesson_id
  JOIN chapters AS ch ON ch.id=l.chapter_id
  JOIN modules AS m ON m.id=ch.module_id
  JOIN levels AS lv ON lv.id=m.level_id AND lv.course_id=v_course
  JOIN characters AS c ON c.id=t.character_id AND c.course_id=v_course
  JOIN nova_turn_audio_updates AS u
    ON u.cefr_level=lv.cefr_level
   AND u.module_order=m.sort_order
   AND u.chapter_order=ch.sort_order
   AND u.lesson_order=l.sort_order
   AND u.turn_order=t.sort_order
   AND u.character_name=c.name
   AND u.turn_role=t.role
   AND u.text_sha256=SHA2(t.text,256)
  SET t.audio_url=u.audio_url,
      t.audio_duration_ms=u.audio_duration_ms;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_turns, v_changed AS changed_turns;
END$$
DELIMITER ;
CALL apply_nova_turn_audio();
DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
