-- Generated by nova/tts/nova_word_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to words.audio_url and words.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
CREATE TEMPORARY TABLE nova_word_audio_updates (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
CREATE TEMPORARY TABLE nova_word_audio_exclusions (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_word_audio_updates (word_key,lemma,display_form,part_of_speech,translation,text_sha256,audio_url,audio_duration_ms) VALUES
('1a4c1aa7ddac391061245217596e8ce8a5cf6a25cada7965456921f4f1347346','aber','aber','conjunction','اما','64acc9f0681220916694d58fb4a5445b951408b8ef7774de9b9c19ca7c95f723','nova/audio/words/de-fa/1a/aber-98c907a572a5.mp3',975),
('b1398bd622f4a1688b7be11dbae642b2bef85c78b2e37866b4dabf87f479fe25','Adresse','Adresse','noun','نشانی','79e5cf20de0ba4547fa0d44be6753dbcf6b68f53d1ad2622e5a01cf77ae5905a','nova/audio/words/de-fa/b1/adresse-db0b21f107d6.mp3',1068),
('65558e6b0e89111ef3bc5abd7c26f14b5ce32e97ec5147af10e588a95c1dc5e1','alles','alles','pronoun','همه‌چیز','0ef6ec226337643d31f41812a186ba494b0fc2c9a2fcc45bb3c8cf9a8a0b56c4','nova/audio/words/de-fa/65/alles-753bc8890a84.mp3',836),
('ada27bf7b349e46acf4f2c246e4e29f51f32eea54fcdcc8d3ba6e42e41dde648','am','am','preposition','کنار','ab6db599234d2636659cba1aa191bd014c3867d5cfade98ff694785c20c28fc6','nova/audio/words/de-fa/ad/am-c1fdd9349dbd.mp3',743),
('7e02032bab0719d12d87e7cec7e6c7a69ed97974a65b799e76e2cf834a00acaf','Apfel','Apfel','noun','سیب','c55dcf4319da59a31ea115103f6fc8b17e86817cd27c652a87b0ec16ea9a443b','nova/audio/words/de-fa/7e/apfel-cb7f12158d93.mp3',975),
('c49f7267bfe2160a91d25e3117fb5f2e1e8fd7ae4d1a36e080cc4c252c5646a3','Appetit','Appetit','noun','اشتها','aff3071a5425a6370279d5ee4ccdf1323c7612a4d7eacae68ca0b934df3d5ad5','nova/audio/words/de-fa/c4/appetit-c8b9194a944c.mp3',1022),
('1ec48811c0c2d34cf8829a2d22ee0e8192c9623749474fee856669f3aa2d9993','auch','auch','adverb','هم','f1b7384743db3616cedb2810f40be29bbc3157001a2a7d77f58175bd9f9c02c6','nova/audio/words/de-fa/1e/auch-84d19246fdce.mp3',697),
('ba0f527bfeaa616272efecf64940577f0dcf8fab401eaa23cf404e4c3e048fff','auf','auf','preposition','برای','424c8eda8e3a16a7acb116eaf727794dae25ef5a16bf7dd483e929bd2534391a','nova/audio/words/de-fa/ba/auf-609f7b5de33c.mp3',697),
('df8ac9d42c67a676933052cccb20aaf60adc951c8e5a5a6699279cb1577160ff','aufstehen','aufstehen','verb','از خواب بلند شدن','3003bdc228aafc2cd4eea2c170b0a3162fa6a3fd25015ea9aaf3db888a0ddf1a','nova/audio/words/de-fa/df/aufstehen-b47374c078d1.mp3',1068),
('efbe26a97d9668fe8745319657c1bc7b7319b37975790ea419a950ba7e9dfac1','aus','aus','preposition','از','2337c37f0721980bcb9acc9fd678f19226f71959ea0f7fae447be7ada79a6a49','nova/audio/words/de-fa/ef/aus-00084d613f0a.mp3',743),
('4958ea238dc19787e8cfa4a0075b2ffb35cd826193a9d90187ed3cbaf03aaf00','Ausgang','Ausgang','noun','خروجی','8728cf4697c2072eb7812d533f662ebc1bf03fb157af0f5b5d9669c179016f90','nova/audio/words/de-fa/49/ausgang-5f7a9c79db38.mp3',975),
('23be96bb87f0544e6c6ae156f923d4c7c14a2018c0fa020b0695750f64f652df','Bad','Bad','noun','حمام','6fe7d7112caaba1b1bc7bfa656974ac4016cc525a7286117494f5b29dfec1f77','nova/audio/words/de-fa/23/bad-c6822e958a75.mp3',836),
('a9e4fbb2322510d96fbbee973c729485ac9173e2455f3b7aa02957df1aa5d97d','Balkon','Balkon','noun','بالکن','ff9f658402a62fc66b04b801da499a7fe6c0313f7b603891b6c497a653e8698f','nova/audio/words/de-fa/a9/balkon-fc3972496376.mp3',975),
('b65ec3ab778fc35818e1291beff1950b721d55ff7ef1d437a8918599e990e78b','bar','bar','adverb','نقدی','fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9','nova/audio/words/de-fa/b6/bar-a804bf27ffc3.mp3',1022),
('5867e77bb99b2bf67c2a9706afc1be3ce42f789b2b1d7139a9b1c5a56e5a8b6c','bereit','bereit','adjective','آماده','7f2ffe9a165a20a256f254772933deeb158a1e04a02320cc99b9847a2c9fc39f','nova/audio/words/de-fa/58/bereit-24982fca4f08.mp3',1068),
('b7343ecec962719b995acee1c4979cc336aa17dfb6ebd5d47e11fc6ffe96b452','Berlin','Berlin','proper_noun','برلین','dad114b6ed7342bac65c79575f6c7ff761ec26b52c1f5f7a9110532973d05df2','nova/audio/words/de-fa/b7/berlin-4606d60337b7.mp3',1115),
('2d7e0d697c48f713e8ec2d834b9e3b93e9010174c8d2c60a0752c647a618f2e8','Bestätigung','Bestätigung','noun','تایید','5f900688c9a1b3d7334f0054406caa8b368192f82ad261c8b3665b7df05d98d6','nova/audio/words/de-fa/2d/bestaetigung-05044a3c25e1.mp3',1207),
('141fd79bbfdaf080e142f3378441a422d74d9ec31ac61ee64ba52415c130e3da','bezahlen','bezahlen','verb','پرداخت کردن','aa92f8d706da53641e5e27ef4e4e5e8f95823be94b85a1bc43967d804fa24d44','nova/audio/words/de-fa/14/bezahlen-027aa298c6f0.mp3',1115),
('6034da2aaf53f026df986e29294fbb4225c5ab26219e11c0ae588c78a10023c4','bezahlt','bezahlt','adjective','پرداخت‌شده','52f27662aa1d7acc3e3da1954eee785ebb30395b6f492414defb87902099c67f','nova/audio/words/de-fa/60/bezahlt-40fb169e84ae.mp3',1022),
('b3978912cccebef3860f1cb73d766a425dfaf8e5469ae5e27ce3d3d953ff0fb8','bis','bis','preposition','تا','96147cdbfd6955d797f628fb510283afaecc1aa5a8735f3fe209ff22746b6258','nova/audio/words/de-fa/b3/bis-7b5fbd7e2f60.mp3',789),
('b8b183cd16c930bb353691ad05d3d8bd11cbb25b01ad6cf5792ce659c292e4f1','bisschen','bisschen','noun','کمی','4845e17a83e25b3088674f1b325120c4c888f40463d03d28b8eb28958b903050','nova/audio/words/de-fa/b8/bisschen-7ebc799be109.mp3',1115),
('1bcab91d670896148f3d3474807b291045542f24d93d3c30f003c46ad5ccfa0c','bitte','bitte','interjection','لطفاً','cca501495f4d40c2a3c570b1f6a372d1b4013c0ed01f6bead1eb64031692503c','nova/audio/words/de-fa/1b/bitte-70d6d2ab17bc.mp3',1068),
('0e145589411e8e8943bba22c61df5f6cda74cbfd9c6c50e430f1c066ebfe7ab7','Bon','Bon','noun','رسید','8c2bab1a74c91de1fb18837b21f89504fd9f7125b51a8c1f868a5a41e899782e','nova/audio/words/de-fa/0e/bon-242113f41a13.mp3',789),
('ce49e0940d12b7e847c023b35def812fb53beaf53161127eb4100d68d1359a5f','brauchen','brauchen','verb','لازم داشتن','16a104d33063b4f60d6dbe76337d334cc78414e32bcf792808c19f23abcbde31','nova/audio/words/de-fa/ce/brauchen-8cc7b320c50e.mp3',1068),
('2a8955cdde24ea6a7f34c59529dd6dfaa145e7a6f19c54e8be261cd3425e5278','Brot','Brot','noun','نان','ef53751671e5219919b139afb43865b325192727a2f1ca216b018d4509abb57f','nova/audio/words/de-fa/2a/brot-c83b2e31f1ab.mp3',1022),
('44bceb2cfbdbfe7f78a5b0c3eeebe38b57ceec4494c5d4407de28162ff573558','Code','Code','noun','کد','340f463033e0fd5ddeabb922df4d4f1b5747494d0f5ed9894f13b6e13ca831f5','nova/audio/words/de-fa/44/code-5df81808827d.mp3',882),
('34ab66eae301972626f6618728887fbaa16a6b2106b03e732edb469da46b0d69','da','da','adverb','آنجا','aa58b21b01d6b8a99c1a5856962dbac36c758a79dc0a77c2e013ce2c39ecdc8a','nova/audio/words/de-fa/34/da-1fe34ac66e8d.mp3',743),
('911cd1090980faaf9f481e38399a1311edb0f561b0c15282300821de10d4cfdc','danach','danach','adverb','پس از آن','e6cebfa7ea082d92918b624363148c3e64f3014619d4d19f4b3361340e3d57a8','nova/audio/words/de-fa/91/danach-055fdf6c6a78.mp3',975),
('a77be5f1e30586b401ba0c5ff909a74a703314c481f9a09f2b3dffe12e0802b3','Dank','Dank','noun','سپاس','40febf26099508c0d4725f0fdafdc6c810d3f88d6b40cbb91bbbaaf709c8c2e7','nova/audio/words/de-fa/a7/dank-b4851884cef7.mp3',836),
('1366bdf5283c221d21f5ae2f41afc34abf3f402e81db81a2bf3394260f2f7e5b','danke','danke','interjection','ممنون','ff1fd0804def10ad2c64ecd154df22c2d73326ed3e65989e9ce35c01200edd81','nova/audio/words/de-fa/13/danke-ccfeda3d847a.mp3',975),
('17178b308d2a11443b9208aa93380687abee24c351a344668dd02344cdb10407','dann','dann','adverb','پس','06cb6c291501e7d4dd2577fe8753defd6300fb30a11fe2e9f8c74b0a93863621','nova/audio/words/de-fa/17/dann-4088528dd2f3.mp3',1068),
('9208c64e73725b1d842c163419c6f4f93c65103078a7938990a8c9ae521f00fe','darauf','darauf','adverb','روی آن','561039868827469fafb05952b5bfea431cf2eb459febc7cb6775c0c0eab0f094','nova/audio/words/de-fa/92/darauf-e4174f63b3b9.mp3',882),
('448fdffa99a054f4ac9eaea89544750f853e825d3adeb1cba19e3a3b3a70f2fa','das','das','pronoun','این','0a7cb27e52927eacabbb7ecc738b0fea50b3967945257c43a67eb753cb465bd0','nova/audio/words/de-fa/44/das-694b91a22352.mp3',975),
('e0c8e2d0ce251d95a53e91888e6d44e057721ffc5a99271439301f3b08637642','dein','dein','determiner','مال تو','37464907b09fda64bf5d81e59e038716f41c458c48c696bb0a615a15f3e3caea','nova/audio/words/de-fa/e0/dein-808a5f68546c.mp3',836),
('768271256c11e641ba872bf441f773a97d530c29b0d2b8d89278cc2747148bcb','den','den','article','حرف تعریف مفعولی مذکر','8a8a1a9fe8565d64c5b8b27cb1f9c3dcb2ff7632bc715b805df124d668e3c9e3','nova/audio/words/de-fa/76/den-8bac66b5cc0e.mp3',929),
('f1db31875f020e2c11775e8ad825d74063628c76e8a1d38aee99c0c0886608f0','der','der','article','حرف تعریف مذکر','5050d80d22ecd471ea55df7034042c1e041341ff4066e7f6ff38e20b720df8ea','nova/audio/words/de-fa/f1/der-c16275113775.mp3',836),
('f90238c4a34c64ffa450979791ceb918a7847052103af3fea7aab2fa1c76538a','die','die','article','حرف تعریف مؤنث','a8d79f40ddb79de569d778f1c0b832f9cc266b32274b702cff4ba2b8a0dd1549','nova/audio/words/de-fa/f9/die-34f34726b556.mp3',882),
('04f15d8d89342a16aef80fd45e0eca9bef643da442dced267f20f180102aff8c','dies','dies','determiner','این','fff9f2190835c7e675fbf6dd6080dc11168b6858a4fc25c806ec498023b390fb','nova/audio/words/de-fa/04/dies-3d4d85a2899e.mp3',929),
('2d76f4bebfd2be7bd099ae219338fdec3ca7afd4cef80812af4170ca83b5e1a0','dort','dort','adverb','آنجا','39c21f5b3b359f1e66524755f6ffe25dd2d980176d0048191970365971ae5791','nova/audio/words/de-fa/2d/dort-0391b5151db4.mp3',836),
('5b75fa9139460c4887e6bf61fad80764b82c1434aa04c52cf4486a0a3412f2eb','draußen','draußen','adverb','بیرون','2bf128fb4ef828d38d75079e154396032bd4e122cafda29593141ff09d56a753','nova/audio/words/de-fa/5b/draussen-753dcaf473b0.mp3',1207),
('fef48ee63159a69eca9b82669afd2c931d7c39157906a4d3bd39601c7facb1fd','drei','drei','numeral','سه','6b70e2d592dd17196b7940574ee89f31c354435338179245457ad54064ba7f77','nova/audio/words/de-fa/fe/drei-e2b9fbeae1ad.mp3',929),
('bb6bd200ca400740a5bc3472453cb70d9fdb6768cd0944446b93b20f012627c5','du','du','pronoun','تو','601b2c2473811afea7864a21e4b965a970afa4ce9eaf85dbdf01414bca66c12c','nova/audio/words/de-fa/bb/du-7a9dcf25ace8.mp3',650),
('7876116fa5e0cf07d24cc70a10526ecc4e430e1fd59d72d748b837a1c96b830d','ein','ein','article','یک','4c3c3030130a4a1b174aa4b0eda1ab26f1ac0c3b88d8fb30e015e3172f356810','nova/audio/words/de-fa/78/ein-466870d04424.mp3',975),
('fa707dadc967909dba1ca1f9fef03cf724f8a152e327a5eb0b3c78a424a252c8','einfach','einfach','adjective','آسان','92b9907fe97032befd467899d5d75fe14ad36a663f6a8b22679e2f096accd18a','nova/audio/words/de-fa/fa/einfach-232ff5336200.mp3',975),
('60bf31402426d31d151ba7fcadb4ae82eee36438372d952cdf473b46c4e5b0dd','Eingang','Eingang','noun','ورودی','d8af5ec4b4ff618a742fa013f137fa37afdb82228968330b48d91d7435633244','nova/audio/words/de-fa/60/eingang-c8f785feb8f2.mp3',1068),
('d9aff8a0c059561c0ac00eb2874ace96a412db5da6ca885c9c5615ce839059ac','eingeben','eingeben','verb','وارد کردن','8c1f9a88213138b84dd73ff5c6b925fc5170d0b190b2dc195080dd27d3056c10','nova/audio/words/de-fa/d9/eingeben-039287cea0d8.mp3',1068),
('d86b24817d0ba5878f606faee552a186ad8da17d84eeb177af4821e388c511db','Einkauf','Einkauf','noun','خرید','c17ced86f696fd95422cdc7d60532e6d470e528e1204ce9e390fb25bc60c43e2','nova/audio/words/de-fa/d8/einkauf-c259818c1876.mp3',1115),
('cde8be9cd9149882dfa8671f26581af2a26caa9758067afbac214ca4286307f5','einstecken','einstecken','verb','وارد کردن','cfad17a7842abddd82908adc9ce77e86f0e71f620b87bdba1bbc410cb7da2fcf','nova/audio/words/de-fa/cd/einstecken-30fb13485403.mp3',1115),
('070e945fa9d5bfe32e27fdbd3d6d846c3b83c1be4387689eb592d5ff62a14a02','er','er','pronoun','او','cc7e4412564ba8a761bd32ab4cc6086bac3c2c9e580367e0b0eb32a4316f9154','nova/audio/words/de-fa/07/er-1c83ec8fa1a9.mp3',836),
('53998d4d8ad24d35a760adadb0a9d43198b7cc96ef54207c9dbd93873cee0492','erfassen','erfassen','verb','ثبت کردن','22ffcd2e74a3186188a968a9188002684b067d8e56bdbc2c9af9f7004797bcae','nova/audio/words/de-fa/53/erfassen-61be98957436.mp3',1161),
('26869ffef930627ac95bf8825373ea1d38bc65b3d57a74a7f7fae67498f0aff0','erledigt','erledigt','adjective','تمام‌شده','967f15af47f9e0873f2a2b9dec546773b0dc834b7049c33e6b8553cf66196253','nova/audio/words/de-fa/26/erledigt-6ea9cc15f1a0.mp3',1068),
('10fc85ba1250bd28cf9bc1773fb27d5fd3edd5ce93b5208ea78a0f4c5036b2b3','erst','erst','adjective','نخستین','b7b39ef221bc71da811aac8a34991cf6bab483a3a83b8fb6ccccd9f710f52623','nova/audio/words/de-fa/10/erst-3f3533773a38.mp3',882),
('8545dcd4d8f1890265cbc158fcb9911b73b3f13c37f6ddcdc2d4038b021bce4c','es','es','pronoun','آن','c0bc1e08f9743b2d50d5f1607503bf4e849af0e729fca896515bea955d70a33e','nova/audio/words/de-fa/85/es-e7be53e3b683.mp3',929),
('74d241c1f758d3776ef41c124663a3bd6dd196390faa5614124984af8d24e74e','essen','essen','verb','خوردن','119ee6901316eec1fa79564ff3048a9a41b02fab571eb02dccf0b77ddc508992','nova/audio/words/de-fa/74/essen-cba19cb0179e.mp3',975),
('bbf350ad809c11dbf2389cb5ccc9179b796f86eda1a9d2470c64d270a2f0067d','etwas','etwas','pronoun','مقداری','b9373420d1622cd300e9b724f131ad22a4398cef175e5e2505b7b31129293715','nova/audio/words/de-fa/bb/etwas-abe64fd0aaf7.mp3',1022),
('16d555f53e1ccdaa326402e2fa38a2f7cc11fd7bb6d15a77336b49de6363c3b3','Euro','Euro','noun','یورو','8bd0b436b489560e73e403e055dd0a15518a254cad0d9e2aa4771d1b561d78f6','nova/audio/words/de-fa/16/euro-339c3bc1b133.mp3',836),
('20c1c12af796d8d8e7c0aab3bfd19f0914582284677dc28ec9ca0f4cb17a2eb6','fahren','fahren','verb','رفتن با وسیله','2372b70bf01af83236aed0ed0d6fc921c655370fa36702a26655e792800a98d1','nova/audio/words/de-fa/20/fahren-d8bbf8206d04.mp3',1022),
('0cfbee83ed65837ef2b7d8c63b822dfa7a391d7800c1858ef399d9211c84ac2a','fast','fast','adverb','تقریباً','115dc3606fbf8691fb69f2aefec86f2ecd302362a0502b3a9648bf2c4dc8290f','nova/audio/words/de-fa/0c/fast-f8ebbbfae242.mp3',1022),
('8b686da6e14cf924414dacbb5867bf85a6585f733c51c5cacb7cb79c09bf1afa','fehlen','fehlen','verb','کم بودن','f03b26ab2899153eff38618cc04daac404fb49e9d1a241de5165bd969ff81473','nova/audio/words/de-fa/8b/fehlen-6cc56c783759.mp3',929),
('fa03ddb41cabdfb3ca2eace8027fa9c345bed89f430e3d6381fefb57d2d3f5eb','Fenster','Fenster','noun','پنجره','22c9783f5077bb8db7af2cb5f2a669cb2ae906d3160b30bed46f72479fa9f4be','nova/audio/words/de-fa/fa/fenster-b7b8f5a8b64d.mp3',1115),
('f684ae66b382e14130f6208209a2c48d91ecc62b395c768fdb20226869418ff6','fertig','fertig','adjective','آماده','fdc275ebe7bd74e14df77fa158e444fc94c69ce90c063959a1552c7f02fd07df','nova/audio/words/de-fa/f6/fertig-2d3fb00f94ba.mp3',929),
('c4ed541e6ae78ffe8bca1dfcd76dd7832f1ff056e9238f234fc9d7f092390e77','finden','finden','verb','پیدا کردن','7466392a9e2f01a723b9374f824585097b2e519624dd08ea6e51e0923eaac251','nova/audio/words/de-fa/c4/finden-a99d2dac49c1.mp3',1022),
('3d396997c6bd0372e5a11cf70a9d32c20aa5518f306748e80cdfcf8c26cc11f6','Frau','Frau','noun','خانم','a67c874c6211ae498fdaf7d4f55168c10e46bb54b4ec3a182eb8195e516bec6d','nova/audio/words/de-fa/3d/frau-7c9f385e7cf8.mp3',975),
('dbe7b0af0965c0146bc0477a002e54618b0f87dd3e35821905f14b8d50a722f2','frei','frei','adjective','خالی','a03d4e5546dea2b8a82c13e06542f6d454040c84a5d5caa5f106ebe1b00de1ac','nova/audio/words/de-fa/db/frei-6c5d18e7bc54.mp3',882),
('88f3987e139219c24c9f5e9439f629c228ba5cc995ce848d3d86069c4fd219d5','freuen','freuen','verb','خوشحال کردن','6a04bb01375a4d3367d42cb087185fd9c017dc2b18e7bc9e98b25e8e810a2ea8','nova/audio/words/de-fa/88/freuen-baddfa139a82.mp3',1115),
('8eda5819982e81921f325a3ff3891480fcbbb87bb26e79b71ae696b1f62af437','frisch','frisch','adjective','تازه','69e86cae43a127b0222e132dfbc678d7d7582934f2a2656596485dc8004cee15','nova/audio/words/de-fa/8e/frisch-2b39994dfdab.mp3',975),
('c10975d1f816083ce20d18a9f2cf4cb29dcc8ad5f42917eb23badee4afebd43e','Frühstück','Frühstück','noun','صبحانه','34f98c0f5c395e5eb579bf24b6e27ab4c751bc1806da3efd309f839fcdfe206f','nova/audio/words/de-fa/c1/fruehstueck-de5f560d6c54.mp3',1022),
('03b4982973aa90d0b7f13bd4333e934af69bfedf3ec19cdb3b2af7af003ddf67','funktionieren','funktionieren','verb','کار کردن','45ea71c91aaaa3aa19ac0e261c91ecf2cfde3cc7a43d0d8d1e21d453888b2b7f','nova/audio/words/de-fa/03/funktionieren-977737408fa2.mp3',1207),
('7dd1bc20b6226437e4dd65769f86cb8910501a830252a707c5364b3cb8870ec3','für','für','preposition','برای','cd23c4c603b344f63dd96d80bc9a0af209d7380ce4faa01bc350e742c364b490','nova/audio/words/de-fa/7d/fuer-7a3996ceb8f4.mp3',975),
('16b1e1e261d144709c022f1915febe2869357a5bda254aac78f21f1792239ec8','gefallen','gefallen','verb','خوش آمدن','5f26eebe6fc0b7ed5009c836a30aab80b6fede8ef5c8f3fc1b0af2c969b61fda','nova/audio/words/de-fa/16/gefallen-f3166c0e4d95.mp3',1068),
('4de6d840c69f59ccf8a0d94708365e65787329d8e64eaf289d2d8ceecf68a9cd','gehen','gehen','verb','رفتن','837ceb63da7920ad96d1be7382221cc7cea1e1d50afdbb4ef3ca2458ba4c8818','nova/audio/words/de-fa/4d/gehen-46443e8f1b10.mp3',1068),
('7d230584d41c3e19d8c24d99de0fac72af3f39e01f64366435d1387d46689413','Geld','Geld','noun','پول','d818da3685a11a51c585f4d2ec2e6ddd24cd09521cd61e1024cbfaaff90a3888','nova/audio/words/de-fa/7d/geld-5ec145a75766.mp3',929),
('7c4cf761617cb6e0a1bf36fc9422d3bb0e3411a330ac864947f01fd9ed3e4e19','genau','genau','adverb','دقیقاً','8e8bb937766852ce13443f8fc8b33703478b005b9de7ed16427b5125000cab54','nova/audio/words/de-fa/7c/genau-aa13846c08ab.mp3',882),
('72a39879d0ebd3e4ac8164710e5a5eb0048efc1dc54fdaa5d21e015e33fa1af7','genug','genug','adverb','کافی','4304d22f1116197b17b9cfc8ce097d5766af64699c4cde7f798b2caf96a923ca','nova/audio/words/de-fa/72/genug-8db8aa7b1c03.mp3',882),
('e804fda131ba85c10564d0dad00298807b8238a5a6ebe5f35be435d6fa683c43','gern','gern','adverb','با میل','bfa14a61e77ecedfe37f4361982d7de5b0c644b9872589044776d68bb2e1f0e9','nova/audio/words/de-fa/e8/gern-81a2f092d33e.mp3',1022),
('9ded7176becf4abe3eb05837b026ee128e164d3e3121a9d14ef6df1492474757','Gerät','Gerät','noun','دستگاه','b32db78620d9fa3b05211fb36ef8206082c2b62f81858073d8c552842fd4232e','nova/audio/words/de-fa/9d/geraet-2b7296b98fd1.mp3',975),
('975bcd04f415037a70a66f04495abdb4a0206210c903b32fc6022403a18a69bb','geschafft','geschafft','adjective','انجام‌شده','2a14f593645dda6b1bfbfc3bb5e1b4b08d01aa3ac8a130a71e77a8596498f351','nova/audio/words/de-fa/97/geschafft-c87093ef8bdd.mp3',1068),
('c4310c4ae8dae3015c36966a5cd7e1cf637685d84ed65c1fe2fdf85411c1ea9f','geschehen','geschehen','verb','رخ دادن','f12d0fd74696c60377468420eb3975774610f268d501af256d676edd6fd18b75','nova/audio/words/de-fa/c4/geschehen-65fc87b96da9.mp3',975),
('42c072a1f6af083b71a29e9656dcc9c16c1dc3cd884073a96b7030ce3a0db102','gleich','gleich','adverb','به‌زودی','95796228d26d94817ca0766c13ff3018ce6029b1d2be3d659aaa5fb6a5529309','nova/audio/words/de-fa/42/gleich-863dc7f02bae.mp3',929),
('e86bbf222d67ec7efc6a6a0a7ac3b75e47e86afa723edbd1c41390be4e26fea3','groß','groß','adjective','بزرگ','7b39b80f141a2adaed303b3f5cec8b6ad6bb47072627f805f869e8d2775467fd','nova/audio/words/de-fa/e8/gross-d8c58cb2de27.mp3',929),
('6ee226efb84ac1abc0f97eaacfbd70a51a1fc402d2db733eb89bc044035be4e2','gut','gut','adjective','خوب','77562953d4c8dc074e55e73375e64f65fef94dcddd39381abb5be1ee250e2b1f','nova/audio/words/de-fa/6e/gut-41d5da8b14be.mp3',743),
('ad58e2af2bb93430d545edf301b255f1966217c70c11805c19eb518e1bd48091','günstig','günstig','adjective','ارزان','3061a0b194d62c12a9fd4ec8a5b929bfb25c1c20af6820f2b54c54312e6edd78','nova/audio/words/de-fa/ad/guenstig-446ad0a847ee.mp3',1161),
('875c472faf74f24f66b451e8d4260e595ce1a082089b7ec7e814c066f3c139b6','haben','haben','verb','داشتن','ba9d261f6e9cec059a82b9aa869a70efdfed466cb8f35640bd28dc9c9e87d551','nova/audio/words/de-fa/87/haben-ce2e86a2a282.mp3',1115),
('f479a4e6ddac4ccd62acb7cea47d9a2a8e14b248ab0b658a0cbb9b16baa112b8','hallo','hallo','interjection','سلام','d3751d33f9cd5049c4af2b462735457e4d3baf130bcbb87f389e349fbaeb20b9','nova/audio/words/de-fa/f4/hallo-d335bccfb3fe.mp3',1022),
('5e9918ef342a85f701b982ac630aafb3cbf4f3362199a179634a77d5714b7be4','halten','halten','verb','نگه داشتن','764dc7965f79cf4b32dd77e2c3c4b8dd38ddab980512d1f3e41a9e8eb1665acf','nova/audio/words/de-fa/5e/halten-e0efcf1fdec1.mp3',1022),
('ac9e12545e748efce7e945c548f009e8528787d87f8ce41bae64733d754a4108','Haus','Haus','noun','خانه','50976ad58f5da02b7be89a224ef09b47ce3b5517623dd927576dc72ebca9214e','nova/audio/words/de-fa/ac/haus-9cf1d125fb0d.mp3',836),
('d31502e216c97154882b81820f939582e2cedf5d1dedd521e5c5a3fe0af8c55a','Hausnummer','Hausnummer','noun','شمارهٔ خانه','f5cff23f21bc897eb1336e7f180d48735c9f58158068b97d9fd59168069c1b5f','nova/audio/words/de-fa/d3/hausnummer-7fa0422cf11e.mp3',1068),
('858dc070585bdbdb93edc83bbf9fe5ecdbf509751321ed914690d5bce3370ac4','heiß','heiß','adjective','داغ','bef0d9f18b933e2bf5becf37bb9ff12c323d4c9e5fbf3709ac64d7fd240d61d2','nova/audio/words/de-fa/85/heiss-01862112ecaa.mp3',1022),
('c7de5aa68d6f2004350e5111a1891d8d3b0df291a2231263192835973a17c566','heißen','heißen','verb','نام داشتن','d291857f6b4bf46279355394bf9394ead82239e293ab38596bff32a0d7078792','nova/audio/words/de-fa/c7/heissen-c65c900e303b.mp3',1115),
('edf0c337fd885110d0460016001cef09a9f8a907ca33969f28749e21798ae1ac','Heizung','Heizung','noun','شوفاژ','744b4873e74c5cece2ccabba57a09fc8c23db13a805f0a05dbea388958b22b0b','nova/audio/words/de-fa/ed/heizung-888d8d31f289.mp3',1022),
('f8cb8bfdf87bf819046268145e5435ef104fcf5e7060e5e6f5635e5a4022474d','helfen','helfen','verb','کمک کردن','7d00e0f8e43792fdb209ef48c7f471fe204f7e1c3786264e0ebc657cf89cbc0d','nova/audio/words/de-fa/f8/helfen-306767eb5115.mp3',975),
('90d83afd75a9e7cbb877dd7afc8ed7f52ecb391c78215e91515058f9118eb319','hell','hell','adjective','روشن','0ebdc3317b75839f643387d783535adc360ca01f33c75f7c1e7373adcd675c0b','nova/audio/words/de-fa/90/hell-98b6ac2ea7d2.mp3',836),
('a775aa191253437f96aa7cb8c40a0263bf78ac73eaa4c52da09fb1b019c31006','herein','herein','adverb','به داخل','d2b5b25c597cff86f2d6617759fb1fe44ae939539e1fa75240f53b7e8fe77630','nova/audio/words/de-fa/a7/herein-f404a48db7bb.mp3',1207),
('b640ae5e20a362731e7eca39381d8613cb9dcd8d707949ed01814d3df05d26d4','heute','heute','adverb','امروز','b748a919ad3e0a2ce7499df93f42e4a9babab9c7f28fff798b66b53466b4bc7e','nova/audio/words/de-fa/b6/heute-053081aae235.mp3',1254),
('b3d9fa69277680884c2433cebc991eb80846d7261f38eafac44a20a53dddd290','hier','hier','adverb','اینجا','529cbc8f212773f23d5eceabfdd3e1736c7c063518b43711d03d229866b12d76','nova/audio/words/de-fa/b3/hier-87fade0d8c4c.mp3',1115),
('5456ae03bdf89b7bfe2faefc2e91df6eb953d10df5d77ff16b638706ce895dda','hierhin','hierhin','adverb','به اینجا','f2ff1bb4ed4395d44baa3e1129c94ac30d4b634794760ad21946ddc7db1d418b','nova/audio/words/de-fa/54/hierhin-a17fea740cbd.mp3',1022),
('e7f726c58523a25a8e582394fb120993f4995ee1b3bb83e0e14a82d4ee9a5a82','Hilfe','Hilfe','noun','کمک','95472f650a2b647ff8fa66450c77b281ac2846cbe9d8df6354cbcd8c5e589455','nova/audio/words/de-fa/e7/hilfe-f9fe7e67a073.mp3',1022),
('5d6bb4e513acc0a26c2e4e880b2057f39b9cd828520ad33d3ce707348126f082','hinlegen','hinlegen','verb','گذاشتن','1e7a4b710d39070287f0c07ef69f2570c5f9095cbc85fc50655df51ca1ac5175','nova/audio/words/de-fa/5d/hinlegen-3dc14352b6d1.mp3',1115),
('4c1b7f4846ac72164fac111933aa7ef4e3a7490feb921fe3f65a3ce56bbc5023','hinten','hinten','adverb','عقب','194e514bf21b52f99ca5a70e85eb2115a0f9679b3094f29bbe717ee7ba0b5e4c','nova/audio/words/de-fa/4c/hinten-072284a44c7f.mp3',1022),
('1102f93fb3d3efdd5ffce2e8bb46d70a9b006c65da9b89a5caf23046c594aecf','Hunger','Hunger','noun','گرسنگی','37cf5259e3c628bf13b7eac2088dc970be5991318fb63b5b4cdca6b3da9fd212','nova/audio/words/de-fa/11/hunger-595305a81731.mp3',975),
('40faac59c9d3427b33cc1d85ae7d3516b05fc7170aff960eb4ad10f63f40a1a1','hören','hören','verb','شنیدن','71f063f406bc357915ac0bc3c20463e035ae6363e08a4e1d799f73bd7fa682aa','nova/audio/words/de-fa/40/hoeren-a687c0689268.mp3',975),
('7338b1d9234e415bcce9d5ae2bb51be9e2998e04697356ed430c4c7767e7fd97','ich','ich','pronoun','من','84c92d8abf326bdb52f1fc6cd6856c41ae9bc1ef4f6056c2672e3d9d301782e1','nova/audio/words/de-fa/73/ich-4d924e30779b.mp3',882),
('de3eb61f18224dcad3d377f37969fc9fd750984a22a9ea00a975b31b557f6f72','ihr','ihr','determiner','مال او','f15e811721cd2c91e9696fd73b239b71b6cef3a91c8a81703348b70726393d8f','nova/audio/words/de-fa/de/ihr-a222124cbf9d.mp3',789),
('6f54ce42c52f4b73f96fe361777176bc1227461d8588c6c5725cc2d0a0e8c661','im','im','preposition','در','a898df22bfc74a1ae298c73211ab3b319e5b8da7543d6cd002a8dc4f8723be43','nova/audio/words/de-fa/6f/im-a44d4671a9fe.mp3',789),
('a9f802fbfa49207a513426bbe8a68d126c66d4bbd4b590e1829842bb86b039b8','immer','immer','adverb','همیشه','4bfacbaf9dbb4fc429e0474664a0ed7770e5a14b0739dc4866bd730ed6405aa9','nova/audio/words/de-fa/a9/immer-a0595e8e238d.mp3',836),
('7d611f75f38cd6412472fba80a84fafa76a0a07adf535f6f367f6bad180911e0','in','in','preposition','در','582967534d0f909d196b97f9e6921342777aea87b46fa52df165389db1fb8ccf','nova/audio/words/de-fa/7d/in-1027ff46c930.mp3',743),
('b6ad2923475b58b353af9efd64b49da07fda1f48d3d0aac870696cb39a891275','insgesamt','insgesamt','adverb','در مجموع','5799fca0937d3f61463430f19784f7970a32293452957313abdfc15dd31b0a9f','nova/audio/words/de-fa/b6/insgesamt-5a2ce25d2031.mp3',1254),
('a9a57703d51295ba9b3976d7440abbcabf2a6b8c9469f37995488c6a28328bde','Iran','Iran','proper_noun','ایران','18d4e170765cc48842d847de1d0545a2e379e9c87b2af2a6f761681309939ce5','nova/audio/words/de-fa/a9/iran-73a39a4005c1.mp3',836),
('24a103f9406dacdb7512fd4763aa131b0f74a9f1bfc9ce434d462d45558e89ac','ja','ja','interjection','بله','3702fc1866630796050c50e9c829bd32fde7cc4c883f28e3e4ca430307c485b0','nova/audio/words/de-fa/24/ja-c7f60a4f4cf0.mp3',836),
('550c9ef1db6acb48fc8b87e2c4caf85a047c03e4193513da337c8398b84de15e','jetzt','jetzt','adverb','اکنون','f1c98ccb91d3bc7f1aac306c67f866e31b2296e25f5f04a81bde924385e08b16','nova/audio/words/de-fa/55/jetzt-a37216670beb.mp3',789),
('e6a777662f080bc281d0a6015ac263eaedb363fe01061c9af55b46fe8c3e80bc','Jonas','Jonas','proper_noun','یوناس','9b67e15f271a91f875a2cad35cb8196b79e726f9c5b28e091037d739abc2d7fa','nova/audio/words/de-fa/e6/jonas-a8eeded5e4aa.mp3',975),
('1f8ed0d4010a5882fc4335ab7126d2b36e501ed8eb91e5eeee4e107d846702db','Kaffee','Kaffee','noun','قهوه','8eb3d40b2c2eab6d4ca9baf97ca7a45bc016861dd506a2f32a1e5b45ff6010f2','nova/audio/words/de-fa/1f/kaffee-3c8c8feb3ddb.mp3',1068),
('d7e098b0587bebb169ce6223ddb86032e1d3c4ba209f6ea17cf33e339fabc1bd','Karte','Karte','noun','کارت','36a8c4994c64ec8cdb71de238033affd088b0f0592e83f0744c3e42dde7d7354','nova/audio/words/de-fa/d7/karte-d4e8da16d9a3.mp3',975),
('239878fa03270d134f9e62102408e70dee29b9d02ea2ec40e3f56e69eaf4de79','Kasse','Kasse','noun','صندوق','fe919551e583e89703f146d9f11b08a99e0c789806c3fde4346a070c1f799bc6','nova/audio/words/de-fa/23/kasse-2f19a1c0a0de.mp3',1022),
('d576f36c5b0a9f6a48b48099c15e3d3836a0e7593eaa197dc0989d7353fd421a','kaufen','kaufen','verb','خریدن','168ec2b7d6cc9e85709b66655415aaa70cbb1743c4ebbea1b42dd1582d675bdc','nova/audio/words/de-fa/d5/kaufen-5f9e5a7277ee.mp3',1022),
('83627baf1585cb02adb70f3f90bf9a84a5ffefd3ae19749898ef00394ebd0999','Keller','Keller','proper_noun','کلر','32dfe2cbdfb72ce1fb1735acccc3c664bf4489b7f44dac87036e93c010d9f4ae','nova/audio/words/de-fa/83/keller-232a78636f8e.mp3',929),
('ef3c5c0133d13c200d945e7cd14cda63ff82b49da2dee33cc98d67cb4fe9d839','kennenlernen','kennenlernen','verb','آشنا شدن','4777a22201988c5b2673d0ccf5eb4e9ff8396011b58b8399e87b7722f598c4d3','nova/audio/words/de-fa/ef/kennenlernen-472ef9cd75de.mp3',1300),
('e9a6f5ec01c880dc22ae7f63c87e37436c72e967e7379baafed670c3850220e0','Kilo','Kilo','noun','کیلو','fb9cd3c57df9f5ed346d8ec28ce5b4958f1e65f553d7704bc09e7f92be795159','nova/audio/words/de-fa/e9/kilo-45c3abbd6c68.mp3',929),
('8e242d48d07da37be0c71909368fa88b1e500cd8064f7fedd840a82eb2e8fc2c','klar','klar','adjective','روشن','05045ef3745c9d71468da641ccf02aad1874585562b7cd606ddc06d43a596b01','nova/audio/words/de-fa/8e/klar-3a499db3846e.mp3',929),
('536dd3afa76dc99dc0dde3a28f9ee6027f35bda099752fca03d76dd17f0d6374','klein','klein','adjective','کوچک','e126893893b45d63758e0828940a2b48b1f9fb8012531ae7f27c7c6ec8dbbbe7','nova/audio/words/de-fa/53/klein-fa3f1fb3a5d7.mp3',1161),
('e4f2a8359283325db21ecc036e65b7af6b62ea3a1b45aef3eec8d0b57ff86965','klingen','klingen','verb','به نظر رسیدن','649fec1d87ae8c5c4d717b823f18d59dcb302037cdef85056e64529c0dd35502','nova/audio/words/de-fa/e4/klingen-3ac8e5b1e7b9.mp3',1022),
('0273a4f9912a918ef28fcd0c6d17f9bba7488058b58afb6e56b7cc1f81bb414d','Koffer','Koffer','noun','چمدان','c87ecc82c4d9bc7e4813b247f2703d2a51da3ffb4ddd00b270b9662df6a539cf','nova/audio/words/de-fa/02/koffer-56b021a2a958.mp3',1022),
('14617a7a4d5810513d2ef053d423c61a1937db372071c71fe538e14d4e5615a6','kommen','kommen','verb','آمدن','529f00bc62dff975aab2f1a4700be67e7c93fe78dca238b5347152391219afee','nova/audio/words/de-fa/14/kommen-18f0f6e138a5.mp3',975),
('a05ec58118d3437b6f41c164a8ecf924542f516f1453c03a620076b678cc053e','komplett','komplett','adjective','کامل','758d401897eef28778a27a31a084970b7837a7cebbad6bcfc006c37b2050dcaa','nova/audio/words/de-fa/a0/komplett-190132ef9a8b.mp3',975),
('1135ccfb78d08f6e0ad25a137948f9066f80bca031e44b4cf56a9fb7ba275a8d','Korb','Korb','noun','سبد','4625f2e59274222dccd2b5c8772fc1620d824702cb354f59fbc5ff2f3d338786','nova/audio/words/de-fa/11/korb-e762f0ca6b8f.mp3',882),
('b5fb3c7e4a7195502b0c61e0f5d2528c846d50a8eb9d9055b391b552ddb27412','kosten','kosten','verb','قیمت داشتن','b184048d4893820adbb965753c7d11e3724e2badc56e0a7fab6a383d5d1782df','nova/audio/words/de-fa/b5/kosten-95478b437147.mp3',1068),
('5603c4efc01cb5bea8ef92090b008513291adad02068c261ad3c9a123d780fba','kurz','kurz','adverb','کوتاه','2dfff992926eae305179c98db7de33e7bf2b9483e1529d17b398e7d9be338b7a','nova/audio/words/de-fa/56/kurz-97082e106e21.mp3',882),
('944372c43d086fec2d2e26de412266497a0621256f2648fbb25b726c4abea10a','Käse','Käse','noun','پنیر','f9eeb52c9bc41ee560ba93468b92317220be4939954e8b50591b8b71accc53ae','nova/audio/words/de-fa/94/kaese-2a24022e55e3.mp3',1022),
('3e3576489b7dde91e8d164ab2b14ff6ef12315cfbe5ba6765125a9b9324c84b8','können','können','verb','توانستن','9bbc28d7306fc59307a76aa67a9c3f8d976802ea16d0a18477f54811b1803900','nova/audio/words/de-fa/3e/koennen-109502d0fc14.mp3',975),
('b8c87db4dfe61c9ea04fff24b9ef442613fdfd382edbfde0b55e48203fbc1ad0','Küche','Küche','noun','آشپزخانه','a9ec872e661915b53a7b5e6e116d8d4095e0ab175c8ee1183b13840e9bde3cac','nova/audio/words/de-fa/b8/kueche-97a29be869f9.mp3',882),
('19c8a4c9cd0bdbcf4488dd76dff990f381ac61f56bed2be79bd41785d64fb98f','leicht','leicht','adjective','سبک','f0222e7b74e6e95677657538035041a8623330f93c3b05cc85ff1b3b12b3837c','nova/audio/words/de-fa/19/leicht-11dddccfb3e8.mp3',1068),
('f70ab4d6af607a9bf72c3b07be866480b732dca7cef71b10335ffd1b4e48a721','Lena','Lena','proper_noun','لنا','92c138b84412fa98ec92b3fdf75f22157d757c8a50de63de2c8ef333c433e085','nova/audio/words/de-fa/f7/lena-9d88086c7add.mp3',836),
('029a63315eadcc644e14872ab7ce00b77bc5a52538b5fd1bd773f48a43154925','lieber','lieber','adverb','ترجیحاً','6179d562d1bc6408db3cd5068af88969941cda54c85cf57202aa402fde70073a','nova/audio/words/de-fa/02/lieber-049a8159db31.mp3',929),
('a4963c18281ef1a8203df8b89f563334c1a7ab6dcfc70a38b5bdc46abfb02652','links','links','adverb','چپ','eef8b9fd5d437dd991ce2695fcce6c416ea3068e5b448963f0a7c3cbd9ad98eb','nova/audio/words/de-fa/a4/links-706ed7f0c7ff.mp3',929),
('c35766c49b04dbe6e8498837adc6ebd913b72cd460f6413df418b7257b664dcb','Liste','Liste','noun','فهرست','7343841e724e89445740d5ffded9127143fba53fc8a29bedb09d0e1f945d81b7','nova/audio/words/de-fa/c3/liste-d6008819e978.mp3',1115),
('96db001483be818f8a6f7beace851c576626d6d9d62035dc38f00b7a175ff006','los','los','adverb','راه بیفت','cb6e53541e37a1d6076e5b516510607a5f3af6c4c4d7f5ce7ac2ffbd18b340a2','nova/audio/words/de-fa/96/los-9e2aad3e838f.mp3',882),
('d5f1c19c9839abd8aa0bc42067249202b36032b4e4a73ae4b09a7ab686f03c3d','Luft','Luft','noun','هوا','34d875437d8f99d7eb035ec5ecbca0a4201e08769fc532711386f2ad89c51771','nova/audio/words/de-fa/d5/luft-b23acea5bf7f.mp3',882),
('bbbd9808e2174b376b93018e04fc0a31373de626d3269b9e6d7181fc4c2d6891','machen','machen','verb','انجام دادن','8740c3f7ac25c8871b88a592632a82dcb216959d06492efbd2b8f6f0d961de9d','nova/audio/words/de-fa/bb/machen-8853dc00445b.mp3',975),
('9bd807283efe7ce274f07b1ddf9e47e3f2d41d8ea990e7e3988bd2877e56d673','mein','mein','determiner','مال من','25352d33fff0003db2f3df1f4211b8d04eb3e63779d5af061943a0fe05d9f2ee','nova/audio/words/de-fa/9b/mein-cd7c8d38a5b8.mp3',1068),
('3baaefcd5844d4a98bea2f24693840cbfea085a6aa3e1542ced16d6395f20169','Menge','Menge','noun','مقدار','1bece813ec41fbf306131f6e68313486c7865c72f024fb56021a67953ebc98e4','nova/audio/words/de-fa/3b/menge-2886ba406f87.mp3',975),
('7d51db0eb55363929cefd2498a0bc65c5f6ab274910fadcdf4740f1e910f2f15','Milch','Milch','noun','شیر','80619cbf258ab6e679234b449434077f6bcd15995fa0aabf3a33fc1d3a0debac','nova/audio/words/de-fa/7d/milch-da3ecc1b424a.mp3',882),
('9b90d503025d3d8b66b27ae9aa69a12ef9cf373dfa3b2b73fca457826af75714','mit','mit','preposition','با','78198e7ab262449ad56e4ca48e10a36f98dda6fd5a377875dd7425afcca2312b','nova/audio/words/de-fa/9b/mit-b7ebba4488fd.mp3',882),
('18b00c33eb6a7a82c468a3d6cc7806053ee530b5c3a20a28bb5e029a6f7152a0','mitkommen','mitkommen','verb','همراه آمدن','467b23719c7014130a241bc3dfd2545da682d199c66ae8358f48ae33c96880b4','nova/audio/words/de-fa/18/mitkommen-89006ea97dae.mp3',1022),
('89b49d1aaa50f646b0aace5376446d90e6ad7af1137e6633cd5ba6833b140b99','morgen','morgen','adverb','فردا','eb26d4fa531af429ed3f011d6a57fa3379590a5c83adcb93839e36cbe1599531','nova/audio/words/de-fa/89/morgen-1c56d973e5c9.mp3',1115),
('d38c785e67f159edb7b5783a8ca8944e189201a8c0d2a9955e09f896bb0a5239','möchten','möchten','verb','خواستن','d1dcd50f900b4111b00fb2d2198ecd6b328217984ac787058c8ebab25268ca81','nova/audio/words/de-fa/d3/moechten-d1c61412fc66.mp3',1068),
('a1236e4f7edf20f3940201b88397486b0090591a67687cf47d11231ecc9e1647','nach','nach','preposition','به','d941a36dbe67051b56940bde18552222ec741260a9e71cb2a0cb8da396eb7045','nova/audio/words/de-fa/a1/nach-8b1b5f1467f0.mp3',975),
('49e17b4cc6a74d998ebb6870b75479a366d054a341b144b5f03bfbe4e0170074','neben','neben','preposition','کنار','8d31784680164d412e8c52dceb70562f85f76484e0fdae69e013d386c34fbf8e','nova/audio/words/de-fa/49/neben-5ef821ee6df3.mp3',882),
('11c5f33d12e27d22e1bbaed94acf907df5aeef4a8a128c579599010a6cc67f75','nehmen','nehmen','verb','برداشتن','4b7da3b65aec30ecd9bf4d16ada9744437830a2d6339c530f6036d75ef466d49','nova/audio/words/de-fa/11/nehmen-298d948cece8.mp3',789),
('653282e6e1f7cae58fb21c68550a7f2a20fb52eab2eed4bf1150d46fddc86081','nein','nein','interjection','نه','4d03db393cf10c84520510a9b957dbbe12150afbb9a9897ef2f6f042db590fe3','nova/audio/words/de-fa/65/nein-509c5e9b35e4.mp3',1068),
('e63143d951ae63f53fca6c8bc0a29bb1c953b076e695e6492561b5d1af58aa42','nett','nett','adjective','مهربان','d6250021d71ab3632c52093f9e5cdac28b0b1fb4f567f844003a021b38827709','nova/audio/words/de-fa/e6/nett-51a2bea52dae.mp3',836),
('37af0eb6135ee813e430126d977da594a76243455e941c6539c04ca6997c5223','neu','neu','adjective','جدید','b1688cbab7e2c8ad7cf619047e25eed6c9e344ed970badcdacd0e9ec73b08626','nova/audio/words/de-fa/37/neu-d60fc7563edd.mp3',882),
('c9bbd2f4ea13b6e79e1be07c90bfee1cb2bb8b2520f0b25d97be5283ede758f5','Neukölln','Neukölln','proper_noun','نوی‌کلن','98a26a7e0b34d6afa2bec149b1bb3af9e6364b625883c9b3590e9d4facb4bbfe','nova/audio/words/de-fa/c9/neukoelln-febda394a093.mp3',1068),
('9fcfe77a288a0660c3214ca4ca96c16a05d1723bc44296efc4389a4574293abc','neun','neun','numeral','نه','d5b7e81295ca0471ca6df83d9abe07bd624dc6fa0aa8a7eb0a0898908e003777','nova/audio/words/de-fa/9f/neun-39315d5fdfab.mp3',975),
('835c3e4c92dc1171f9aca2031ab5e3474d02aba2c0c74386b86ebf06f651c5dd','nicht','nicht','adverb','نه','6a8cd96a4b778934f9ef7673a09b59c0bb5475442ccbc491bb8e7862318f2302','nova/audio/words/de-fa/83/nicht-2a4aef3e5c2a.mp3',1068),
('3ce5ddf6d6f0dfac5df99773964dcf60bbffccebdfdcee131ad599557ce73848','nichts','nichts','pronoun','هیچ‌چیز','7f812985703138c507d17e83ffda68466ce2d67440095f87ea37356037e3b647','nova/audio/words/de-fa/3c/nichts-b166bf67360d.mp3',882),
('fc0bdc5ae6cfc1fee024693b4d3ff803f2d22ac137a16d0fb2e1874dcbfd2725','noch','noch','adverb','هنوز','a665c12561dff12c22b0beb42d1caed7f00db9f6486a8ec1ad9ff2f3642f7e52','nova/audio/words/de-fa/fc/noch-1527a3f23b03.mp3',1068),
('b6357fe7018233a8b615df743feed5b16274473999416c81df0f1794d9b37ec4','Nummer','Nummer','noun','شماره','9732e51294688edd0fe5d5ee09cb94532d02bf1c59bb71a54962a3a845d903d7','nova/audio/words/de-fa/b6/nummer-f274a714d0fc.mp3',1161),
('6e5cd0c3b9974475243aaf1162221008b486439cda687b33fdbec7f13a53e9d4','nur','nur','adverb','فقط','e9b5b78ab02082e001d4c29d0de8ee26e8b01cf7db33c792879714ff90413de9','nova/audio/words/de-fa/6e/nur-1c5569855910.mp3',882),
('4e51095ad60523c2cc55d1ba7e72172f1983556ca69fdb6a0de1ed228e0bb637','Obst','Obst','noun','میوه','017cb2ca51e27218c65abfbbc18eed9a52997fc26a4ebd0ee63178135ef14afb','nova/audio/words/de-fa/4e/obst-df9852dd01e7.mp3',789),
('dfdbde73556a2be9e6f0774ba55585dc1ba6bfa711b93ff8c1e18665d26f2abd','passen','passen','verb','مناسب بودن','3aff2d0b9afd3ad054d2d8d1f8f6b6ed3f5068539f571204ca4085d7e0de217e','nova/audio/words/de-fa/df/passen-3d222753c225.mp3',1022),
('245090546c371b2d4e615ff6f36ae6b3f71abe1fc1ceb1aa19f7dee828fbd6e5','perfekt','perfekt','adjective','عالی','be90a010f80db4c7953850a89d5aac8db5d441304b94222b4d3ad1da0c120dce','nova/audio/words/de-fa/24/perfekt-ad6b7e43eb48.mp3',1068),
('0edbc2ab0e8fcf857001b024d186c9123d747f14cdcc888d11a6ab449a777771','praktisch','praktisch','adjective','کاربردی','644039d078a71ca9ddb461e2702c09abb3d58e0f523bda85b23f842d8f3b5a1b','nova/audio/words/de-fa/0e/praktisch-6337bcef38e0.mp3',1068),
('7fce51c0172fe438b75a62d4ac19d80a82f08bd1bcb2d7b36f60b17e32232ca2','Preis','Preis','noun','قیمت','9883291e666c677170c9ec515026b80bd090db7dce30c8d52cde51ff01ddc79a','nova/audio/words/de-fa/7f/preis-6932d28bd729.mp3',1022),
('5bfd871f997bfe93d0369574194ad1274d94d686b0c367c1da3e609cc4209f12','Produkt','Produkt','noun','کالا','34b157607524c11c50670fe9194082bfed9e5fe45c0ecb7a435eab7d01856d0e','nova/audio/words/de-fa/5b/produkt-187acf32a5b5.mp3',975),
('a7579a7285cc2bb26a2413d30a430f8ae4c97513670dc978f0aed37816c4b448','Quittung','Quittung','noun','رسید رسمی','5e568c375be2edd62fa2218ed4d1a2f06fd579bc1ec1eaba145984e1cf41b7bd','nova/audio/words/de-fa/a7/quittung-506c0e73bb39.mp3',929),
('e5ec97802818469236c0fed58ceebf1defd87b8d8feb426a03db38dbbf55c91c','Raha','Raha','proper_noun','رها','bc1532ce0d50e8f914bb459f4afcb6431e4b1381969141bf19e218d57bc27ff4','nova/audio/words/de-fa/e5/raha-4a75ba29f9da.mp3',1068),
('fc7b7ac791d68f1dfedf11d62b7e6d3ed60ecf5b9b73d4b376a38ce58b9f741f','rechts','rechts','adverb','راست','dd3fbf0d05afcd41c283c0e758da94453b79fdaa39cfd846b211815224e6088b','nova/audio/words/de-fa/fc/rechts-248db654a31b.mp3',929),
('849cedcb64aed711126c902c2793f04d6b0287f36211be0d9bbe349f3f5c02dd','Regal','Regal','noun','قفسه','a0a5b7ba93a126a286ceed55d0618480132871567d1acdef90b53c9b3e8133b3','nova/audio/words/de-fa/84/regal-213970f89974.mp3',1022),
('61a8415bbd79cfef2f7893e9301e26b037f491c6f0900f6e5d6bfa6ace5b8683','reichen','reichen','verb','کافی بودن','5102cf442b097116fbde4667278c5d41397d8380212e8b07daa6ec0255929fbb','nova/audio/words/de-fa/61/reichen-48cf89ff1d55.mp3',1068),
('34e3a3d87ab4750fb0c639d0ccbf824f101b464b6f0103900e3809c26ff0746b','richtig','richtig','adjective','درست','953ae3742f333d144636d3a3cd3447453a645d2b76bb09b2200ce764fdc6c2e4','nova/audio/words/de-fa/34/richtig-1f798f354468.mp3',1022),
('c89248860c6d2249afcfaca26b5e8aa55574bb983935067129715140b2b3ec57','rot','rot','adjective','قرمز','7ec879c8c860699e23145733661074c562767d6f860ed0de439e5c2724bc4b18','nova/audio/words/de-fa/c8/rot-e041339920d4.mp3',1022),
('540783507f012e90b5e6fccb2f85742112aa169326433bad0401903991c19f68','ruhig','ruhig','adjective','آرام','d29898d82af929550aa0845211ca1b8853195395c7d9d820e3026fb1e6e53862','nova/audio/words/de-fa/54/ruhig-0fb3a2323350.mp3',975),
('d5f529e481a3b695e8304fdaee2f1118b2c53ac21025dcd06d804a5ddc95fd60','sagen','sagen','verb','گفتن','7c12f957e1f567602f343584d8abf06175d9a1bea479f27516b5d71fe5fcf4a6','nova/audio/words/de-fa/d5/sagen-84e78c289fa6.mp3',929),
('a7236b94546f17b3addfcf31baec480922ccfa39cb3f1880db454f8f5a180a3b','scannen','scannen','verb','اسکن کردن','c1cbc6f9abe60583e6f4bbdd6050f0c7844eb75006539b955b9edfaa2772f07e','nova/audio/words/de-fa/a7/scannen-d5a82267530c.mp3',1022),
('b57ff0519b12c9cb3e18f3d994aac5f1690d59a6988f1a956ed8da4c3f98bb66','Schlafzimmer','Schlafzimmer','noun','اتاق خواب','d169602d01f7a92da7a8bba4d3f2e6e5307b0ad314628090ebcdd7f926568e61','nova/audio/words/de-fa/b5/schlafzimmer-8b323affbae6.mp3',1161),
('9d52416ee5f3c114f875287cfdecab51c6ebb80a0754504ec74124de1092d9f7','Schlüssel','Schlüssel','noun','کلید','1fbd7a00cacba0b89a31bb00cd29e60d3f86c08dd7806bbe891642214672af0c','nova/audio/words/de-fa/9d/schluessel-34db9b7b29ba.mp3',882),
('43a5326b972ea6415f7dd6b3f059b0e584eebc7e2565d6b95c5af0cc9f0fc5ae','schon','schon','adverb','قبلاً','ed719858ee1b140e7f356c444eace6372fc92abe6512d3bf190e6e0644d88082','nova/audio/words/de-fa/43/schon-a6d721724ac3.mp3',975),
('a2f970ae7e7ea751df7c415c28ea97f304aa0ec72b2070a2bfc92ac34e3c3040','schwer','schwer','adjective','سنگین','c3c27bacd0e0b53f4e9bea3068736f4b8c08c8b7d35a479baef03e6b1a3c1d37','nova/audio/words/de-fa/a2/schwer-a83631f2a3e3.mp3',975),
('940e06b4fb936c67d093207c3e422aeef45714aea158e70a36c9f6e7b6ce3962','schön','schön','adjective','خوب','1a028e829b255703ecd9ade6ac712e048486eecfbf49d89994839481c772937d','nova/audio/words/de-fa/94/schoen-d394002ff78b.mp3',882),
('acde45b8e1c5796a2c5ddd1b9f0485a8dc02408d99177cd0bcd34cb03edda84b','sehen','sehen','verb','دیدن','b2e07b1cd677c28ecb97f8ff798e99b6f2fab8f578e46b95aac5a11bcddb017a','nova/audio/words/de-fa/ac/sehen-3f836f0c9bf6.mp3',836),
('416195e5c9069bf09d7559b8de64f83e859e99b1c61f8689f9fa8406c0978d17','sehr','sehr','adverb','خیلی','907114a73986290c82ce7e52f82008a500876df239fd85106f18f91c62b39b9d','nova/audio/words/de-fa/41/sehr-1140f6f40958.mp3',1022),
('54360aaea8c1c8bcf97af4891b0b3567a0f6de077c66d22e359ebaf46f8306e6','sein','sein','verb','بودن','f0abec8675ebc5503c13051760a3052b3f50baf79c5825b6767ec69e82ce501d','nova/audio/words/de-fa/54/sein-50b4d3102f4f.mp3',1022),
('4a365b064a5f244eaafd564880325579cd68e5e7555ead5cb247dbea76e4858f','sie','sie','pronoun','آن','70f0b8e6e13410a6852579add968e46ea8d34d48390f56e70629391bb3534f14','nova/audio/words/de-fa/4a/sie-c0378ea94733.mp3',975),
('9e28b3c249d5e453b5541e2671f2e6c35345e786b8454d54bf96d344ab4d887d','sieben','sieben','numeral','هفت','1e9d34deb9f9902732935c78800dd497a9b7cb60c142fde4e3c021fc7315cda1','nova/audio/words/de-fa/9e/sieben-122fb8ce4571.mp3',1022),
('aa0bf5821d132c08777ad07c13a7c8ba515b3afa777f9813cbf978680832b8d3','sollen','sollen','verb','باید','d1759198baa0eef62dd5ebaa880713dc5b35ccf1aac26e16abe73a2a5e23af1f','nova/audio/words/de-fa/aa/sollen-2a9d04de1f80.mp3',929),
('3ad86d8fb18c4340d300aced7d842fe3840b3d8a9436d21b68b4a7502504f7ff','speichern','speichern','verb','ذخیره کردن','899da8912848674e7cb9f6538046e92243d1cfb889e389cd21e551ebc1400b13','nova/audio/words/de-fa/3a/speichern-263c4151e6cc.mp3',1068),
('456acb1e90331986d15cd74e035f10bcfd0b12cd178eff55cadbe40c0d373831','spät','spät','adjective','دیر','386dbf01efbd156e98bdd3a8e08e8c287b9a9afb534071636b48791f3d822624','nova/audio/words/de-fa/45/spaet-1d949cb82052.mp3',882),
('63c3eaabebb06c191276d7e6fc5f7cae9f303663f11a436fc76fe4df6d44c273','stehen','stehen','verb','ایستادن','066399c5204672ada5ec0f06e3219c06a979f40f322a0b0018ba01b8dfaf0195','nova/audio/words/de-fa/63/stehen-973454bc2ac5.mp3',1022),
('0ec03dcf2ea539ac40a10f03683a3b302db2faa8cf67980487a9cb3b021039fe','stellen','stellen','verb','گذاشتن','eda5a835fd21f5147fbc3c5964cf0ac69cfa45d645e98c1fe426824ac0bda12c','nova/audio/words/de-fa/0e/stellen-fc1901270334.mp3',1161),
('7c7e202de633f6939825d018edf8d31b44f11a5349388474001a44c415b581d9','Stück','Stück','noun','تکه','95b17626803e50741dcf3ea0eb84e13f863f1a3e58900ca78f3cbb295a2ac86d','nova/audio/words/de-fa/7c/stueck-a23a80e8f07d.mp3',882),
('aff49feab1fd8fb8b4d286d8e5192467d551ad0d9cb75fc6ed27e3903937cf14','super','super','adjective','عالی','73d1b1b1bc1dabfb97f216d897b7968e44b06457920f00f2dc6c1ed3be25ad4c','nova/audio/words/de-fa/af/super-b542fbd03f76.mp3',789),
('68ff19457bb51feaa2af666fda3b03817d7bfe30e08555c8a32f9b2ef7701eb8','Supermarkt','Supermarkt','noun','فروشگاه','77b45b83d1a07fd84316c7972aa4427984bbd30401fc8e2d58fd4cc5d22c7beb','nova/audio/words/de-fa/68/supermarkt-a9bda5f690a1.mp3',1115),
('4f429f44ff11f78dd6be7a34ec54ff86e0f5d7ff45dfbba6fbc8da910f37ef5e','Tag','Tag','noun','روز','1503916a2ab2b0fd6768d3455fd8f2d9aa3b31333a8507dadcad983704a975d7','nova/audio/words/de-fa/4f/tag-5f0d8d620a14.mp3',836),
('8e2f9e7a4d8322bff56bd3bda070e591718ff62771b0bb9b28acbce59c0fdd74','Tasche','Tasche','noun','کیف','53f8e1a2ac391fb506c44df8e0083770a492307673a85b28b67df81d69cdc136','nova/audio/words/de-fa/8e/tasche-ca9f03418bcd.mp3',1022),
('95ef52f48632cf6aff3f4dcc662cf2c3606fc40d8abb48ad7e827c5ba3912cde','Taxi','Taxi','noun','تاکسی','7793c31446e339002451c04738d3480f636a4a3ecc1750c1e23d7907fce3e20f','nova/audio/words/de-fa/95/taxi-107c58ec0db8.mp3',975),
('71a5f18d727238e071cef3784582966118984ef569580c260f37fca817e73157','Tee','Tee','noun','چای','19c3fd6de646493a61a411846b1d649a75d7076784e0845fb30f32a2f8f27980','nova/audio/words/de-fa/71/tee-7baae8c998ea.mp3',882),
('8b431fc659072c1b8f8600e19efa426d0a337929ca6464b0eb7dba2b7709abc4','Teheran','Teheran','proper_noun','تهران','d4dddc09735e988a6faf0403a937d4953cbf0600fdbac36098611d089527a24f','nova/audio/words/de-fa/8b/teheran-2c7450b15983.mp3',1115),
('0fcc013f7e77709b53f8bb63edf7f4c9f4808d343cad1539feba6255024800c4','Telefon','Telefon','noun','تلفن','fa6906d76ee94d4e8d05a2424fb89005840522ab6dec0ee8055247424977169e','nova/audio/words/de-fa/0f/telefon-3b2578a90556.mp3',1207),
('aaad53d7376e55b67d54895976465ae61135b875f4304f29fbf213351b10c208','Termin','Termin','noun','قرار','83f07dc6e90d37666dddaa6f230ea94f45219631fc0bf1e99dbd517e35b5cae8','nova/audio/words/de-fa/aa/termin-7fd05aef1dc2.mp3',1068),
('1b59f1c5d087bb23f425b1f6f4fd8d2e573b66171ee235120a82bdfeb6df1982','teuer','teuer','adjective','گران','85955db377cec50af62a32c0151f5cecf9ac6e998e98f61af8eade221603ee34','nova/audio/words/de-fa/1b/teuer-a08a0a059d47.mp3',975),
('9edabdc6c050dae483e438c4443d9a254b92245018f140b140e3823e73f24ba2','Tomate','Tomate','noun','گوجه‌فرنگی','96eaefafc3db56ca49863a066b13a6a3c8139d28b49f083673c219bbd81f294e','nova/audio/words/de-fa/9e/tomate-754e784098c0.mp3',1068),
('29f148275ce9fdbddb9d99b9aaadbc80a30759e340a038325a0c32a6ce57c1d8','Ton','Ton','noun','صدا','d7bb53dca2ae574b558d274024a2093f7868bd29a7c2a02ea7c2748582aa5b22','nova/audio/words/de-fa/29/ton-8381257f1711.mp3',743),
('9e45fea00dd6582a7c26b65920a6f628a23915e49da5f955a3d72885d9682369','treffen','treffen','verb','ملاقات کردن','008679d18064e9c718029fafee6218d90135e2685d13b7b41799997b0926c679','nova/audio/words/de-fa/9e/treffen-1790a355a320.mp3',1115),
('4028b8522ccc22b384f208f2aa86e8841173228de145b97c5b49d21d91f489a2','trinken','trinken','verb','نوشیدن','7ab5d8bd3e5fc8eb3ca25215a684c777e47363a87bd27a5d9068306b351358a3','nova/audio/words/de-fa/40/trinken-6563dacda53b.mp3',1207),
('256e402bbe6c5589f4956c4e6a3249c4df6ee4f39c9f7ff9800e76ef89a609f9','Tür','Tür','noun','در','1cff8a95c840c89adb7b2cdbfc63d228355d76ec79cab441a86568ae4a0ef76d','nova/audio/words/de-fa/25/tuer-3427c30b3453.mp3',882),
('6fa2d96297a97a90bd45d3c1ac8247084611ddbccb3a73b664a65b7e83b27af2','Tüte','Tüte','noun','کیسه','af0a203da7ebd4c957f44030720e8914c8011d9def8df3548e419a1a45dacffe','nova/audio/words/de-fa/6f/tuete-32b4edd53f2a.mp3',975),
('2511335753b0bb68373fa03d92c0b081403fb0b16eeba30895f586c2264a3d82','Uhr','Uhr','noun','ساعت','4221b9b808159cb280f2c4564de85bc47b8bcd51d0e52748e2a1694eb8e76807','nova/audio/words/de-fa/25/uhr-110ace170955.mp3',789),
('9ae3f3e86d968d620078744df209af2d4f2b9c6eb38d50b6211397d2db789082','um','um','preposition','در ساعت','289c90decf40c8ec15f72f6080f2a4e7cd11d4128530dd5d290fc06ebadba620','nova/audio/words/de-fa/9a/um-ab7ec2942707.mp3',882),
('2c910542ccb5f4406dc1dc9aaa753b34b90906a6e3b6fd3b6efe268dc985556f','und','und','conjunction','و','856cc99d87343400dc05fe7d03fa666602a1d92c4fb0ee1f5ae2f0a5fb218eb8','nova/audio/words/de-fa/2c/und-fcdd4dcc9a41.mp3',743),
('5359dc277abb99d4cf12428b5393c17fa101aa780eb4d99a2992f45f4fabf0ab','unten','unten','adverb','پایین','bf65c1637f933b736080a53521bb980fb2942b53628fe6bdde9fc059e15238cf','nova/audio/words/de-fa/53/unten-54179efe592e.mp3',975),
('c69cae734639988647aa6014a68794a82660a3cc3a9ba44b3ccac8579761be5a','Vermieterin','Vermieterin','noun','صاحب‌خانهٔ زن','5563caf65c75215a81dc1150b17f954d5bad44b02078919174454181774b3b4f','nova/audio/words/de-fa/c6/vermieterin-b7e8a4f61d59.mp3',1254),
('d1fda5911f0c396c69772525867874604ccc385109c41bff41021367a9e4c39b','viel','viel','adverb','چقدر','8e695edf2a3232521df271fbb9d1e7500cb7008e1a5972b817543f9b4c1adcea','nova/audio/words/de-fa/d1/viel-5c5819078284.mp3',882),
('98e241a61d46ea678bd79d53925a29b964fed85492e0a3d52d6592b3e1e81a3f','viel','viel','determiner','بسیار','8e695edf2a3232521df271fbb9d1e7500cb7008e1a5972b817543f9b4c1adcea','nova/audio/words/de-fa/98/viel-5c5819078284.mp3',882),
('113e2457861e960dfb55a695a217c398cbaedb6eb141e909c662c787953295c6','Viertel','Viertel','noun','محله','ccc8d9c77e6ad775b51f8a071fd51b69d824458b55fc9f6ac5439ac52ff13029','nova/audio/words/de-fa/11/viertel-6ed222e81551.mp3',929),
('37d5bcf5f5e4e5f3334e4e2faeecc321b7a053a2d998f76c34dad92a72c03607','voll','voll','adjective','پر','907a3efd95c6f4d43126cf8ac87d752add59b5e95bedbc38b2845fcdfded606a','nova/audio/words/de-fa/37/voll-cd5ef3be280b.mp3',929),
('80a755d6d710e9a096aef994af8abc4416e8e783b765b83f4589caf8abae0bf8','vor','vor','preposition','جلوی','929f1ca4b2be58d78c26a4fc235d1eefe5e6545232f54fb3e916c564f5754c0e','nova/audio/words/de-fa/80/vor-54f2ec78dae5.mp3',882),
('647a96762aa534cf3231516fe79a36dbad456465f0df99ed1e472844f89ff890','vorne','vorne','adverb','جلو','907d3a75c94ce758ca651963fa523ce2109b4e9bd02bae757244552a0f1ed9e7','nova/audio/words/de-fa/64/vorne-65efbc608adb.mp3',929),
('bf080fc82753abac3c74af79f2a164ad7afde984e8e10a370d5a971ace30e80a','wach','wach','adjective','بیدار','e0f1d12bf33ad77a401ba3f6be0a4311ff05b38a1154a6593b6486d4c6430651','nova/audio/words/de-fa/bf/wach-38de9aa23cf9.mp3',1022),
('f1b82b6085af510a3419d80eb14d3b57f81dc90a20bfcc4aed16ca6e6f55d38a','wann','wann','adverb','چه زمانی','5d99599b60a043d425432e6b8e30c0970a73c4e8c2a57f2e2ace8947432c8baa','nova/audio/words/de-fa/f1/wann-b09f357e74c5.mp3',975),
('05c50ebc5340d9ff06df0298381abc7deed3530fb823a139be58f53748a783ac','warm','warm','adjective','گرم','0f0aa408c1832abefd06bced5378aa7945c11b3fe2f24f8a22cd6dbdbe4bccd8','nova/audio/words/de-fa/05/warm-44e750362bfb.mp3',882),
('c7f8ce0c6861e7fa33799f085d625d4e87553af8f368fefacb044a1ab7d88539','warten','warten','verb','منتظر ماندن','227835ebcc7b746ea42de04ec07fab5ccc09b6d6feb2f32543acb2f6231ca53c','nova/audio/words/de-fa/c7/warten-8938ff769374.mp3',1068),
('82e60abed62da2332f7f56b245582823596fd661f26b5f4be0f4e9ef75adf15d','was','was','pronoun','چه','b63b99f6383ba713b57ddfc77737c5f71639fa6f4663efe60a66a8c6d114b545','nova/audio/words/de-fa/82/was-c614b040b847.mp3',836),
('aa37e9679b5bb24792c1c7c7295fb6906390903ff28facd009810b56b9218ead','Wasser','Wasser','noun','آب','f942c0f4855b900888eb405e844e519e79c5309d4b204862e0ae535d14f4060c','nova/audio/words/de-fa/aa/wasser-da942e3f7bfa.mp3',975),
('e6cefe5f2c290d0fe66fa001ba4486eebdcfa3e3900f229c0f70773ca7e45f90','Wechselgeld','Wechselgeld','noun','پول خرد','30b49a2c74a19cf7e111f8de425d89dec55344cc9be08edcba677ac0164548a8','nova/audio/words/de-fa/e6/wechselgeld-ed91cc8920bb.mp3',1207),
('eb9186e769102c0a531e45f1a266762f3f93ed71efec5aa0264118cd3f2f3784','welche','welche','determiner','کدام','5e368aac938176f8e07881aac04cd81a4467dfcdae9b48eee7b528fa3fd1282d','nova/audio/words/de-fa/eb/welche-fb7f37c3b58a.mp3',929),
('9956891bcddac146fd37f894e0722d3821bacd3771012782b1e5844fe6ccb515','wie','wie','adverb','چطور','4a3f1139f614aab2af8d024c1c3a638ec4d3a00b99f9237ea02b6a69fd74b577','nova/audio/words/de-fa/99/wie-cefcd823d878.mp3',882),
('74bd55d261f442e7f157124d7a15ca0091438e2b73de09cc317f1206c5326d9a','willkommen','willkommen','adjective','خوش‌آمده','6cece6c1ea57f6ef2ca36fcf2cbba7f67cb7ff09f2699664c27294744d3e7a69','nova/audio/words/de-fa/74/willkommen-7c2c2b5e9368.mp3',1161),
('a16d275c3c9a45c5a54db2c537903030199453943af7e5bbfcc05dec06f12273','wir','wir','pronoun','ما','999da4de4d657b8e65d59368748cf17f16cf07f23ee9c164eb43de2c362f606b','nova/audio/words/de-fa/a1/wir-66b2985bf103.mp3',975),
('8166d2c558cbdee2e16cc34581abb75a6ef1f77be0ab8851e6dd4ab489b5b8c5','wo','wo','adverb','کجا','f8f26225fd1d7a1c68981c944df40164266c067a05e6c0cc0a90b8a6cef94b67','nova/audio/words/de-fa/81/wo-0760ea5ac9a8.mp3',789),
('2187ee5263e4c1653544011e7e8d4f9822c4ad46215aceb6a5fea7b80135049a','woher','woher','adverb','از کجا','c58061e325595c5714b8d7c3d89c299ee3d7ec975f6f9ed80632f7e83633fcfd','nova/audio/words/de-fa/21/woher-13730c45ca34.mp3',975),
('7193364b1884f8f9ae10486744af235a1056b3f327edc66615904a64339d9e3c','wohin','wohin','adverb','به کجا','5d0f856ff3a6f5417820c18e482c687f748bea61b20a5fcde30e51795f84c58c','nova/audio/words/de-fa/71/wohin-8a930a7ad356.mp3',975),
('6a9d135c165ec8f0b67625566135265670280dc8f527407a2656155d04d4b70c','wohnen','wohnen','verb','زندگی کردن','4944af70480b82a6c3002d53da795b40fcb6e33323b120a550ed034825360bae','nova/audio/words/de-fa/6a/wohnen-827d4c1da5c5.mp3',929),
('8c41991ad07d25033685add966a887dad5a6dc7425bde810121cafe8eb5fab28','Wohnung','Wohnung','noun','خانه','c91145d16d21c165362dbbdbe19e864d978f0030df1177b1689c231d27298191','nova/audio/words/de-fa/8c/wohnung-abbe9bdc8a9c.mp3',975),
('7c2032765e4b684930a529616150aa0ea720bff57f5085a1895a290ce303a431','Wohnzimmer','Wohnzimmer','noun','اتاق نشیمن','08f7b944a44e646d3dcdcc424155fbba8f412d561faceef61473fd29be3fdd62','nova/audio/words/de-fa/7c/wohnzimmer-bca3240bd04b.mp3',1115),
('01c85438e95c3a5802d972eb56010ac5db6ea1f343c5810ddd9f9f447ea2e8c9','wählen','wählen','verb','انتخاب کردن','e11cb91a6244b4cea3f9f9da0f89a3c2697a697993de59a0b59b07fe0dbdfc4d','nova/audio/words/de-fa/01/waehlen-aa6660d2d3ff.mp3',975),
('18ea4dc901013ae0d62da99b38abf9edd44fda111236a1d2421a5999a4a7f0f1','zahlen','zahlen','verb','پرداخت کردن','9a27f8494941d641e5386b06f7d41f04b94965c66d6710d0f0c3edd91cfd258a','nova/audio/words/de-fa/18/zahlen-0c69c0105abd.mp3',1161),
('ca1bd219a5303b2e230510e7434ed802ed8ea172be56a29e30df8a668b6245fc','zehn','zehn','numeral','ده','bedd6f98909f0da2622f39ce0312e19bf85886fef4fcbe81aee8a343fc0aa763','nova/audio/words/de-fa/ca/zehn-c8813d736b58.mp3',929),
('091e8df3cdc2f59ad0c6b1989d0c5b0f1ef964bf97076a35d6cc3faedfefc31f','zeigen','zeigen','verb','نشان دادن','46c96d17bab4baad86e1f19cd66156ce5d76919d43908c890cb7a0f14d23669d','nova/audio/words/de-fa/09/zeigen-6ef293454692.mp3',1022),
('236089cb9cbbdd43ae8bc83dee2e0237fa7ee546bcf03a8b1a15847ee0822bb1','zu','zu','preposition','به','82cefa8283d30fda9c86f8a976b95d79b395d4cff62a3c8242c7153039bfcde6','nova/audio/words/de-fa/23/zu-0d35cdce246a.mp3',836),
('ca085d5dd68d4dfc627d5879e579ccbfb913cc0270b58a9c70493fd5349c1104','zuerst','zuerst','adverb','اول','ccd1d16622a3d2a1160ebe7ccf9380757e240b42d4ef1751de19e83a0d4e9cfc','nova/audio/words/de-fa/ca/zuerst-0cbb55f18863.mp3',1022),
('4d508da4512668b1cc6f8478bd258af51982664d2e323f06747cc680ee0c7f69','zufrieden','zufrieden','adjective','راضی','da719fd7cd54ba65bf5be4d7bd4c19eabfa794ccb2a5693338ef76746127aafc','nova/audio/words/de-fa/4d/zufrieden-41c3895c7901.mp3',1161),
('f56d9be8582471aa6e111cdc9b2078edb52680cc17cc7aedc5cee9bf48116e22','Zuhause','Zuhause','noun','خانه','6f5c5f0e5a9f2cdeff0604bc74cd637f336ff8a3db81882715706cc3278c6383','nova/audio/words/de-fa/f5/zuhause-1a31d35a3a30.mp3',1161),
('a8de043797d96a5b6377602f3285161f6f13b35d97d83b565dbdf6946b61f28c','zum','zum','preposition','به سوی','eeccef1ac21b1189fd684c88f1c3eee5d62fd30639506d200a8dae4ddfb1d579','nova/audio/words/de-fa/a8/zum-9a595f0cc869.mp3',882),
('d25f00f0d2f4939680406f9e58964a24fcb9eaafd5ceb54b59e81067ae2c8c51','zur','zur','preposition','به سوی','09890dd421f069bdbb023b6a4aa1eb689b0d40c1c7bad5ec4f0bdf023ad83f11','nova/audio/words/de-fa/d2/zur-468f876a0f25.mp3',929),
('a59e986dc945e8e59233390f11cdba3bb65e55cb965f46130f46d634a3400cb1','zusammen','zusammen','adverb','با هم','b2253f5de165a720f991ff30ff0b61c3f54877e1ac1598eefe591aaa3c887cf7','nova/audio/words/de-fa/a5/zusammen-219204a344ef.mp3',1068),
('3e1c51752016c84e5bad2af464cb0787675e2952d7804b024312e52d1cb81f7d','zwei','zwei','numeral','دو','9dbe3cfc5af797f3516eb7c92f37fe507b83c13017aa9ddb57b9afe25a75a3a6','nova/audio/words/de-fa/3e/zwei-874bbba70daa.mp3',975),
('5dca2eae30c83521edadca9306f35b7f0eaddca49844892e20dbf05943bc431c','zwölf','zwölf','numeral','دوازده','70f5f8852578418e8af276a8806ffdb14df1de652506a73149f9dec5bd353b13','nova/audio/words/de-fa/5d/zwoelf-11060f2fcea6.mp3',1022),
('2f950f9361fafc6b5399ff39618967ad7ceeeee3a4ca9ea2cf530d5d021e56b9','öffnen','öffnen','verb','باز کردن','b804de742720522e4a9678188ae746f1591d191679a6aa1bdb9f21442ba41904','nova/audio/words/de-fa/2f/oeffnen-c60964124024.mp3',882);

DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_word_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_cleared INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova de-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_word_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_updates AS u
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY u.lemma
     AND BINARY w.display_form=BINARY u.display_form
     AND BINARY w.part_of_speech=BINARY u.part_of_speech
     AND BINARY w.translation=BINARY u.translation
     AND SHA2(w.display_form,256)=u.text_sha256
    GROUP BY u.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Word locators did not match exactly once.';
  END IF;

  SELECT COUNT(*) INTO v_excluded_expected FROM nova_word_audio_exclusions;
  SELECT COUNT(*) INTO v_excluded_invalid
  FROM (
    SELECT x.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_exclusions AS x
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY x.lemma
     AND BINARY w.display_form=BINARY x.display_form
     AND BINARY w.part_of_speech=BINARY x.part_of_speech
     AND BINARY w.translation=BINARY x.translation
     AND SHA2(w.display_form,256)=x.text_sha256
    GROUP BY x.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_exclusions;
  IF v_excluded_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio cleanup aborted: one or more excluded Word locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE words AS w
  JOIN nova_word_audio_exclusions AS x
    ON BINARY x.lemma=BINARY w.lemma
   AND BINARY x.display_form=BINARY w.display_form
   AND BINARY x.part_of_speech=BINARY w.part_of_speech
   AND BINARY x.translation=BINARY w.translation
   AND x.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=NULL,
      w.audio_duration_ms=NULL
  WHERE w.course_id=v_course
    AND (w.audio_url IS NOT NULL OR w.audio_duration_ms IS NOT NULL);
  SET v_cleared=ROW_COUNT();

  UPDATE words AS w
  JOIN nova_word_audio_updates AS u
    ON BINARY u.lemma=BINARY w.lemma
   AND BINARY u.display_form=BINARY w.display_form
   AND BINARY u.part_of_speech=BINARY w.part_of_speech
   AND BINARY u.translation=BINARY w.translation
   AND u.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=u.audio_url,
      w.audio_duration_ms=u.audio_duration_ms
  WHERE w.course_id=v_course;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_words, v_changed AS changed_words,
         v_excluded_expected AS excluded_words, v_cleared AS cleared_words;
END$$
DELIMITER ;
CALL apply_nova_word_audio();
DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
