-- Generated by nova/tts/nova_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to turns.audio_url and turns.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
CREATE TEMPORARY TABLE nova_turn_audio_updates (
  cefr_level VARCHAR(8) NOT NULL,
  module_order INT UNSIGNED NOT NULL,
  chapter_order INT UNSIGNED NOT NULL,
  lesson_order INT UNSIGNED NOT NULL,
  turn_order INT UNSIGNED NOT NULL,
  character_name VARCHAR(120) NOT NULL,
  turn_role VARCHAR(16) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL,
  PRIMARY KEY (cefr_level,module_order,chapter_order,lesson_order,turn_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_turn_audio_updates (cefr_level,module_order,chapter_order,lesson_order,turn_order,character_name,turn_role,text_sha256,audio_url,audio_duration_ms) VALUES
('A1',1,1,1,1,'Lena','character','357a57fe73d6c63bb1923e970f79a924db3a3609eb9797547784a94ee38fc3df','nova/audio/turns/de-fa/A1/m01/c01/l01/t01-lena-1493be49480b.mp3',511),
('A1',1,1,1,2,'Raha','learner','357a57fe73d6c63bb1923e970f79a924db3a3609eb9797547784a94ee38fc3df','nova/audio/turns/de-fa/A1/m01/c01/l01/t02-raha-1c635a71f1bd.mp3',557),
('A1',1,1,1,3,'Lena','character','9057691532bafd36496ef5f7710d8f8d39cfb8c4c5f024e847724979efe70350','nova/audio/turns/de-fa/A1/m01/c01/l01/t03-lena-d13c04bb88a9.mp3',1672),
('A1',1,1,1,4,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l01/t04-raha-b11f4b4048f0.mp3',1393),
('A1',1,1,1,5,'Lena','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c01/l01/t05-lena-58938944703a.mp3',1440),
('A1',1,1,1,6,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l01/t06-raha-1db58f156a7b.mp3',1022),
('A1',1,1,1,7,'Lena','character','a0e0b6ca00a4fc7504106fae267e4e9054861fae40b0a957ee04637923e74034','nova/audio/turns/de-fa/A1/m01/c01/l01/t07-lena-d954d217b938.mp3',1115),
('A1',1,1,1,8,'Raha','learner','dacc874c2bd53ebe5e4e58ff2d986849d5e178e70f823dc9efe9615301ea4b02','nova/audio/turns/de-fa/A1/m01/c01/l01/t08-raha-1862804389ae.mp3',882),
('A1',1,1,2,1,'Lena','character','c622f747de63407eddd65e9a645e63dc5345c85a551a36e4a0094d4520504d2d','nova/audio/turns/de-fa/A1/m01/c01/l02/t01-lena-52067963ffe5.mp3',1161),
('A1',1,1,2,2,'Raha','learner','695f06911a274ab2bc85d35dc335b7f9f5aecb83beb3b0fcba2f11603812dfbe','nova/audio/turns/de-fa/A1/m01/c01/l02/t02-raha-15b204a6702c.mp3',1207),
('A1',1,1,2,3,'Lena','character','1d9f9187df0286a7ac8874a8c503af18c5ec97a2a4311910e2dfdcd9ba2566a0','nova/audio/turns/de-fa/A1/m01/c01/l02/t03-lena-f21066006cc5.mp3',1579),
('A1',1,1,2,4,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l02/t04-raha-27514b1dbe44.mp3',1393),
('A1',1,1,2,5,'Lena','character','73194f62ef568168f74c3df6fef3ee0c665aadab0a74a9228b05198588b17b71','nova/audio/turns/de-fa/A1/m01/c01/l02/t05-lena-517352475f41.mp3',2601),
('A1',1,1,2,6,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l02/t06-raha-670ae945c484.mp3',1068),
('A1',1,1,2,7,'Lena','character','3c4ba2eaae0978b945fdadcf23d5948b020ad40d9d801dfe462c231425709368','nova/audio/turns/de-fa/A1/m01/c01/l02/t07-lena-d0b9810358ee.mp3',836),
('A1',1,1,2,8,'Raha','learner','3c4ba2eaae0978b945fdadcf23d5948b020ad40d9d801dfe462c231425709368','nova/audio/turns/de-fa/A1/m01/c01/l02/t08-raha-9fe47af971aa.mp3',1068),
('A1',1,1,3,1,'Lena','character','1ed0342abf9e85e4846458d134899e0bf3be2a3903cd486d6500b8616b512397','nova/audio/turns/de-fa/A1/m01/c01/l03/t01-lena-4453083d1b53.mp3',1115),
('A1',1,1,3,2,'Raha','learner','e48fca17da79cae4725cec4d22ae285686ac1b6663323474fd7654a9202f3be7','nova/audio/turns/de-fa/A1/m01/c01/l03/t02-raha-63bcfe807154.mp3',1533),
('A1',1,1,3,3,'Lena','character','2753e4860651be83bea82179f42ddb29947635c5ea61b047a06924f8c758f042','nova/audio/turns/de-fa/A1/m01/c01/l03/t03-lena-8ca82fdaacc8.mp3',1347),
('A1',1,1,3,4,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l03/t04-raha-90602ab12d6c.mp3',1254),
('A1',1,1,3,5,'Lena','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c01/l03/t05-lena-58938944703a.mp3',1440),
('A1',1,1,3,6,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l03/t06-raha-db9b0d14eaf9.mp3',1022),
('A1',1,1,3,7,'Lena','character','610e07d140ca4087f2b807158f7d54a625b2c7df39f5bb51b6256180f246e8da','nova/audio/turns/de-fa/A1/m01/c01/l03/t07-lena-f1cd23a77727.mp3',1207),
('A1',1,1,3,8,'Raha','learner','1d1b8d538b7137e4f766aecb6bb35e2a55aa803205c1c702ca3f158da94190a2','nova/audio/turns/de-fa/A1/m01/c01/l03/t08-raha-65bd2d1f18da.mp3',1161),
('A1',1,1,4,1,'Jonas','character','c6c50528f1eca43bb20a4c90a6de1096f86201eab22e80ba27f29d40e6ba0a3e','nova/audio/turns/de-fa/A1/m01/c01/l04/t01-jonas-5d4548fe65db.mp3',1811),
('A1',1,1,4,2,'Raha','learner','0030396148c5f239ce992c26822e583d1680b7f92de653449a1f777546c43f6f','nova/audio/turns/de-fa/A1/m01/c01/l04/t02-raha-7a62a740ddb3.mp3',1811),
('A1',1,1,4,3,'Jonas','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c01/l04/t03-jonas-33de76f1986c.mp3',1625),
('A1',1,1,4,4,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l04/t04-raha-8a77352986d1.mp3',975),
('A1',1,1,4,5,'Jonas','character','1d9f9187df0286a7ac8874a8c503af18c5ec97a2a4311910e2dfdcd9ba2566a0','nova/audio/turns/de-fa/A1/m01/c01/l04/t05-jonas-1e7b218e368f.mp3',1486),
('A1',1,1,4,6,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l04/t06-raha-494ff83bf0b2.mp3',1672),
('A1',1,1,4,7,'Jonas','character','3c4ba2eaae0978b945fdadcf23d5948b020ad40d9d801dfe462c231425709368','nova/audio/turns/de-fa/A1/m01/c01/l04/t07-jonas-bb49f20efd82.mp3',836),
('A1',1,1,4,8,'Raha','learner','43f692229732b4a5323689d6dc018a4acb578ca6d48152b78ceb88250d3323fa','nova/audio/turns/de-fa/A1/m01/c01/l04/t08-raha-26a8196c76c1.mp3',882),
('A1',1,2,1,1,'Lena','character','2ea47f9debedb493a62cbc1198bc1e100287e02f25feef5843e4cb578942889d','nova/audio/turns/de-fa/A1/m01/c02/l01/t01-lena-c2049f71c0b7.mp3',836),
('A1',1,2,1,2,'Raha','learner','2f7009179d76977cad4349a85a9fd53777678a0f331c7ba76f11b5982d92a2a1','nova/audio/turns/de-fa/A1/m01/c02/l01/t02-raha-a3f02f2ec366.mp3',975),
('A1',1,2,1,3,'Lena','character','3f22e95182a83d53e548ff495c5093369b0f69262a12e0f41469065b9a923e22','nova/audio/turns/de-fa/A1/m01/c02/l01/t03-lena-ee82ba6a2e93.mp3',1161),
('A1',1,2,1,4,'Raha','learner','a111a6fca0234578fa1d188d569e83313be8fddc26008e7cf8c1750960dda3ec','nova/audio/turns/de-fa/A1/m01/c02/l01/t04-raha-186cf6ac1f7c.mp3',1440),
('A1',1,2,1,5,'Lena','character','e80ea6f6e4c4983c8eed9f5488fa998c052be2d21ef8c39597fe476ecdc75aeb','nova/audio/turns/de-fa/A1/m01/c02/l01/t05-lena-886c0dc1b682.mp3',1997),
('A1',1,2,1,6,'Raha','learner','2ff759ad5e597c65b4dcfb83504d28e3284ac26bf053aa52c021106aa8943473','nova/audio/turns/de-fa/A1/m01/c02/l01/t06-raha-143bf1fde96e.mp3',1161),
('A1',1,2,1,7,'Lena','character','a0e0b6ca00a4fc7504106fae267e4e9054861fae40b0a957ee04637923e74034','nova/audio/turns/de-fa/A1/m01/c02/l01/t07-lena-dd99ca0241ea.mp3',1022),
('A1',1,2,1,8,'Raha','learner','dacc874c2bd53ebe5e4e58ff2d986849d5e178e70f823dc9efe9615301ea4b02','nova/audio/turns/de-fa/A1/m01/c02/l01/t08-raha-1862804389ae.mp3',882),
('A1',1,2,2,1,'Lena','character','7b86b3f857f9cb900ca8dc0df674c773ed51197366b0c80843f2439ab1a71f8a','nova/audio/turns/de-fa/A1/m01/c02/l02/t01-lena-784a077856a4.mp3',1115),
('A1',1,2,2,2,'Raha','learner','cbc22fb85adca904671d884da2f7622bef7b4b7438eed3f25ff7e904d883d598','nova/audio/turns/de-fa/A1/m01/c02/l02/t02-raha-1d098cde4dfe.mp3',1440),
('A1',1,2,2,3,'Lena','character','91b5826fa872f6eaad8c206c78b6db5ba4399d4eb9167b3365803f44f6b7aee2','nova/audio/turns/de-fa/A1/m01/c02/l02/t03-lena-91148acb82c4.mp3',1022),
('A1',1,2,2,4,'Raha','learner','114b55b9cbc871e7967002bb4e3c3bcaed74a1038a4342991fffc5bc45775bc6','nova/audio/turns/de-fa/A1/m01/c02/l02/t04-raha-34d9f46b20dd.mp3',1347),
('A1',1,2,2,5,'Lena','character','9ec41a99682e78511eac0d91fdfca47e0000984b1f3a4d5545ff1dcb748b9ff1','nova/audio/turns/de-fa/A1/m01/c02/l02/t05-lena-ebbfc28d8bf4.mp3',1115),
('A1',1,2,2,6,'Raha','learner','a111a6fca0234578fa1d188d569e83313be8fddc26008e7cf8c1750960dda3ec','nova/audio/turns/de-fa/A1/m01/c02/l02/t06-raha-eba8cd0715e0.mp3',1347),
('A1',1,2,2,7,'Lena','character','11efe78ad09d0c98f2009d7ffb6d5920a4d6ec814e104063df2e6433c1a343b3','nova/audio/turns/de-fa/A1/m01/c02/l02/t07-lena-93fdb836fce1.mp3',789),
('A1',1,2,2,8,'Raha','learner','f923f1001c61673323e2504d20c5eb042c74e96cea0f7e14c57a01a95058f633','nova/audio/turns/de-fa/A1/m01/c02/l02/t08-raha-2f99e2f837eb.mp3',697),
('A1',1,2,3,1,'Lena','character','c4524024558d0724f0930c3cab3c11233d443360b2bc33a991a96855b2aeac4f','nova/audio/turns/de-fa/A1/m01/c02/l03/t01-lena-facd2407076d.mp3',1347),
('A1',1,2,3,2,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c02/l03/t02-raha-e61894ab8755.mp3',1115),
('A1',1,2,3,3,'Lena','character','3f22e95182a83d53e548ff495c5093369b0f69262a12e0f41469065b9a923e22','nova/audio/turns/de-fa/A1/m01/c02/l03/t03-lena-f2f512f0087f.mp3',975),
('A1',1,2,3,4,'Raha','learner','a111a6fca0234578fa1d188d569e83313be8fddc26008e7cf8c1750960dda3ec','nova/audio/turns/de-fa/A1/m01/c02/l03/t04-raha-47177f393f82.mp3',1347),
('A1',1,2,3,5,'Lena','character','92b73862e35acbc79bf9fc5366409331e946f626c64586198cef75212650511b','nova/audio/turns/de-fa/A1/m01/c02/l03/t05-lena-e074ee8ab987.mp3',1161),
('A1',1,2,3,6,'Raha','learner','cbc22fb85adca904671d884da2f7622bef7b4b7438eed3f25ff7e904d883d598','nova/audio/turns/de-fa/A1/m01/c02/l03/t06-raha-082b4247cd14.mp3',1765),
('A1',1,2,3,7,'Lena','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c02/l03/t07-lena-af7ea0212cc4.mp3',1440),
('A1',1,2,3,8,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c02/l03/t08-raha-ffe39ae21f45.mp3',1347),
('A1',1,2,4,1,'Lena','character','c4524024558d0724f0930c3cab3c11233d443360b2bc33a991a96855b2aeac4f','nova/audio/turns/de-fa/A1/m01/c02/l04/t01-lena-07a2c3daacb9.mp3',1347),
('A1',1,2,4,2,'Raha','learner','0030396148c5f239ce992c26822e583d1680b7f92de653449a1f777546c43f6f','nova/audio/turns/de-fa/A1/m01/c02/l04/t02-raha-4c6c4a570fc1.mp3',1811),
('A1',1,2,4,3,'Lena','character','3f22e95182a83d53e548ff495c5093369b0f69262a12e0f41469065b9a923e22','nova/audio/turns/de-fa/A1/m01/c02/l04/t03-lena-4f49098dbbd1.mp3',1068),
('A1',1,2,4,4,'Raha','learner','a111a6fca0234578fa1d188d569e83313be8fddc26008e7cf8c1750960dda3ec','nova/audio/turns/de-fa/A1/m01/c02/l04/t04-raha-4de036145a5d.mp3',1161),
('A1',1,2,4,5,'Lena','character','7b86b3f857f9cb900ca8dc0df674c773ed51197366b0c80843f2439ab1a71f8a','nova/audio/turns/de-fa/A1/m01/c02/l04/t05-lena-66b2893b1490.mp3',1022),
('A1',1,2,4,6,'Raha','learner','cbc22fb85adca904671d884da2f7622bef7b4b7438eed3f25ff7e904d883d598','nova/audio/turns/de-fa/A1/m01/c02/l04/t06-raha-5b129bbd14c0.mp3',1486),
('A1',1,2,4,7,'Lena','character','c8a095b1359727af25ca13f29cb06e4b4b203fab58af9198c05c0b6fd9d4c070','nova/audio/turns/de-fa/A1/m01/c02/l04/t07-lena-84b475952c97.mp3',2183),
('A1',1,2,4,8,'Raha','learner','7e988fabc1490be9932ed1db7f235af6dd1026f97819ffbf98355b71b4d89474','nova/audio/turns/de-fa/A1/m01/c02/l04/t08-raha-435aed6e2fc9.mp3',1765),
('A1',1,3,1,1,'Jonas','character','6ff8829887ab779f4564db598d31dd05a42eda8b39e640fabfd91dd728738bbe','nova/audio/turns/de-fa/A1/m01/c03/l01/t01-jonas-1cddc3130003.mp3',3251),
('A1',1,3,1,2,'Raha','learner','13bed41f1b5a8959335d3ef7043b15a3de6b0d2be41fa3e0016a8bed0e9855f8','nova/audio/turns/de-fa/A1/m01/c03/l01/t02-raha-4c628877e1af.mp3',1950),
('A1',1,3,1,3,'Jonas','character','5409b946aae1ee8687af5a43917351d50850d3a25bf7b074994c5c2c5840f067','nova/audio/turns/de-fa/A1/m01/c03/l01/t03-jonas-c2e2426c30f2.mp3',1811),
('A1',1,3,1,4,'Raha','learner','2770e3d026ef5c0d0804312c22ac067ad3820a568f37c79f9d9361815647d0f5','nova/audio/turns/de-fa/A1/m01/c03/l01/t04-raha-c93c60460827.mp3',1486),
('A1',1,3,1,5,'Jonas','character','ad8bad8fb7cd22780933fedc35d1be1470919b2aa2a4797745925c07cf27ac2e','nova/audio/turns/de-fa/A1/m01/c03/l01/t05-jonas-e660c5c2e385.mp3',697),
('A1',1,3,1,6,'Raha','learner','f923f1001c61673323e2504d20c5eb042c74e96cea0f7e14c57a01a95058f633','nova/audio/turns/de-fa/A1/m01/c03/l01/t06-raha-de62d838ef87.mp3',1347),
('A1',1,3,1,7,'Jonas','character','b50460c24fc317ba6a04b27642d28777d9ea0d17732876951e0cd1b7fcf36000','nova/audio/turns/de-fa/A1/m01/c03/l01/t07-jonas-e290113fe624.mp3',1997),
('A1',1,3,1,8,'Raha','learner','00881c663b293b886d5eb1759c680a94217e284518cfe593373cc4008ea4f78f','nova/audio/turns/de-fa/A1/m01/c03/l01/t08-raha-c621cc502fa2.mp3',975),
('A1',1,3,2,1,'Jonas','character','5409b946aae1ee8687af5a43917351d50850d3a25bf7b074994c5c2c5840f067','nova/audio/turns/de-fa/A1/m01/c03/l02/t01-jonas-cd20f729aec0.mp3',1858),
('A1',1,3,2,2,'Raha','learner','616a00159aa4a46ab54e1d29dec9fdb718e6fc0c316f8aa598d6f885d9b67d33','nova/audio/turns/de-fa/A1/m01/c03/l02/t02-raha-31d3bca8f6c6.mp3',1579),
('A1',1,3,2,3,'Jonas','character','c60ee16dffffc3518ce07b15fade586f2a8ba7d72d5f561211ef6b8d23717697','nova/audio/turns/de-fa/A1/m01/c03/l02/t03-jonas-585a4aa774f3.mp3',1207),
('A1',1,3,2,4,'Raha','learner','ac856d2e633ab2026ac41a0b20873da0f7694b8b59743cb4ce622921b41ff77e','nova/audio/turns/de-fa/A1/m01/c03/l02/t04-raha-6b78f2e48ef9.mp3',1904),
('A1',1,3,2,5,'Jonas','character','11efe78ad09d0c98f2009d7ffb6d5920a4d6ec814e104063df2e6433c1a343b3','nova/audio/turns/de-fa/A1/m01/c03/l02/t05-jonas-7d10edff966b.mp3',604),
('A1',1,3,2,6,'Raha','learner','f923f1001c61673323e2504d20c5eb042c74e96cea0f7e14c57a01a95058f633','nova/audio/turns/de-fa/A1/m01/c03/l02/t06-raha-06fe9b4b8a49.mp3',557),
('A1',1,3,2,7,'Jonas','character','f13f25a375359b4c00b1dbfb60026f25be4000e9cec2e329fdb541aa6c36df0e','nova/audio/turns/de-fa/A1/m01/c03/l02/t07-jonas-9e4affa43df9.mp3',1161),
('A1',1,3,2,8,'Raha','learner','cbc22fb85adca904671d884da2f7622bef7b4b7438eed3f25ff7e904d883d598','nova/audio/turns/de-fa/A1/m01/c03/l02/t08-raha-ddeb8688990a.mp3',1533),
('A1',1,3,3,1,'Jonas','character','2753e4860651be83bea82179f42ddb29947635c5ea61b047a06924f8c758f042','nova/audio/turns/de-fa/A1/m01/c03/l03/t01-jonas-74c3484d7fdd.mp3',1254),
('A1',1,3,3,2,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c03/l03/t02-raha-926176020638.mp3',1254),
('A1',1,3,3,3,'Jonas','character','3f22e95182a83d53e548ff495c5093369b0f69262a12e0f41469065b9a923e22','nova/audio/turns/de-fa/A1/m01/c03/l03/t03-jonas-10b6b06d71d6.mp3',1207),
('A1',1,3,3,4,'Raha','learner','a111a6fca0234578fa1d188d569e83313be8fddc26008e7cf8c1750960dda3ec','nova/audio/turns/de-fa/A1/m01/c03/l03/t04-raha-7730f1cdedea.mp3',1347),
('A1',1,3,3,5,'Jonas','character','44a35d6cc0cc3a847ebbb3b6691fe48a847f3ebb4ec85dd752c39a576b01f4aa','nova/audio/turns/de-fa/A1/m01/c03/l03/t05-jonas-85a59edca252.mp3',2183),
('A1',1,3,3,6,'Raha','learner','6a5cd5198a6efe495f7d6c1de878df4068b2d9fcc95710ab107becba6957515a','nova/audio/turns/de-fa/A1/m01/c03/l03/t06-raha-d69d30d98ccb.mp3',2833),
('A1',1,3,3,7,'Jonas','character','e5931b846e6a58bca90a1f47bb05c48ec24c178423ed5aff3dd85bc118e0770b','nova/audio/turns/de-fa/A1/m01/c03/l03/t07-jonas-cf8d43bac9ba.mp3',743),
('A1',1,3,3,8,'Raha','learner','dacc874c2bd53ebe5e4e58ff2d986849d5e178e70f823dc9efe9615301ea4b02','nova/audio/turns/de-fa/A1/m01/c03/l03/t08-raha-524a14c26d03.mp3',836),
('A1',1,3,4,1,'Jonas','character','2526a66de14d71d004e0111457c0aa8e3c0cd369a0e844daf3a8326153a60f01','nova/audio/turns/de-fa/A1/m01/c03/l04/t01-jonas-12ba0b7f7eae.mp3',3111),
('A1',1,3,4,2,'Raha','learner','0030396148c5f239ce992c26822e583d1680b7f92de653449a1f777546c43f6f','nova/audio/turns/de-fa/A1/m01/c03/l04/t02-raha-f120747bcb71.mp3',1811),
('A1',1,3,4,3,'Jonas','character','44a35d6cc0cc3a847ebbb3b6691fe48a847f3ebb4ec85dd752c39a576b01f4aa','nova/audio/turns/de-fa/A1/m01/c03/l04/t03-jonas-465ac582be78.mp3',2043),
('A1',1,3,4,4,'Raha','learner','6a5cd5198a6efe495f7d6c1de878df4068b2d9fcc95710ab107becba6957515a','nova/audio/turns/de-fa/A1/m01/c03/l04/t04-raha-e3262d60987a.mp3',2740),
('A1',1,3,4,5,'Jonas','character','f13f25a375359b4c00b1dbfb60026f25be4000e9cec2e329fdb541aa6c36df0e','nova/audio/turns/de-fa/A1/m01/c03/l04/t05-jonas-b3187232e5d8.mp3',1440),
('A1',1,3,4,6,'Raha','learner','cbc22fb85adca904671d884da2f7622bef7b4b7438eed3f25ff7e904d883d598','nova/audio/turns/de-fa/A1/m01/c03/l04/t06-raha-eea89c4f9e03.mp3',1347),
('A1',1,3,4,7,'Jonas','character','c8a095b1359727af25ca13f29cb06e4b4b203fab58af9198c05c0b6fd9d4c070','nova/audio/turns/de-fa/A1/m01/c03/l04/t07-jonas-c60b40822155.mp3',1811),
('A1',1,3,4,8,'Raha','learner','7e988fabc1490be9932ed1db7f235af6dd1026f97819ffbf98355b71b4d89474','nova/audio/turns/de-fa/A1/m01/c03/l04/t08-raha-435aed6e2fc9.mp3',1765);

DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_turn_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova de-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_turn_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order,
           COUNT(c.id) AS matched_rows
    FROM nova_turn_audio_updates AS u
    LEFT JOIN levels AS lv
      ON lv.course_id=v_course AND lv.cefr_level=u.cefr_level
    LEFT JOIN modules AS m
      ON m.level_id=lv.id AND m.sort_order=u.module_order
    LEFT JOIN chapters AS ch
      ON ch.module_id=m.id AND ch.sort_order=u.chapter_order
    LEFT JOIN lessons AS l
      ON l.chapter_id=ch.id AND l.sort_order=u.lesson_order
    LEFT JOIN turns AS t
      ON t.lesson_id=l.id AND t.sort_order=u.turn_order
     AND t.role=u.turn_role AND SHA2(t.text,256)=u.text_sha256
    LEFT JOIN characters AS c
      ON c.id=t.character_id AND c.course_id=v_course AND c.name=u.character_name
    GROUP BY u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order
    HAVING COUNT(c.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Turn locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE turns AS t
  JOIN lessons AS l ON l.id=t.lesson_id
  JOIN chapters AS ch ON ch.id=l.chapter_id
  JOIN modules AS m ON m.id=ch.module_id
  JOIN levels AS lv ON lv.id=m.level_id AND lv.course_id=v_course
  JOIN characters AS c ON c.id=t.character_id AND c.course_id=v_course
  JOIN nova_turn_audio_updates AS u
    ON u.cefr_level=lv.cefr_level
   AND u.module_order=m.sort_order
   AND u.chapter_order=ch.sort_order
   AND u.lesson_order=l.sort_order
   AND u.turn_order=t.sort_order
   AND u.character_name=c.name
   AND u.turn_role=t.role
   AND u.text_sha256=SHA2(t.text,256)
  SET t.audio_url=u.audio_url,
      t.audio_duration_ms=u.audio_duration_ms;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_turns, v_changed AS changed_turns;
END$$
DELIMITER ;
CALL apply_nova_turn_audio();
DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
