-- Generated by nova/tts/nova_word_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to words.audio_url and words.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
CREATE TEMPORARY TABLE nova_word_audio_updates (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
CREATE TEMPORARY TABLE nova_word_audio_exclusions (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_word_audio_updates (word_key,lemma,display_form,part_of_speech,translation,text_sha256,audio_url,audio_duration_ms) VALUES
('a6c899261463d473e2f1541944e07d31b86883068f22ae614981b681f371e146','aus','aus','preposition','از / اهلِ','2337c37f0721980bcb9acc9fd678f19226f71959ea0f7fae447be7ada79a6a49','nova/audio/words/de-fa/a6/aus-00084d613f0a.mp3',743),
('b7343ecec962719b995acee1c4979cc336aa17dfb6ebd5d47e11fc6ffe96b452','Berlin','Berlin','proper_noun','برلین','dad114b6ed7342bac65c79575f6c7ff761ec26b52c1f5f7a9110532973d05df2','nova/audio/words/de-fa/b7/berlin-4606d60337b7.mp3',1115),
('d28bd69c59c8d3085ab744b1b60aefd7d6868570d80f53e6b77ad3d66d942c9a','bisschen','bisschen','noun','کمی؛ در «ein bisschen»','4845e17a83e25b3088674f1b325120c4c888f40463d03d28b8eb28958b903050','nova/audio/words/de-fa/d2/bisschen-7ebc799be109.mp3',1115),
('1366bdf5283c221d21f5ae2f41afc34abf3f402e81db81a2bf3394260f2f7e5b','danke','Danke','interjection','ممنون','dd5e148117aaa5f86dfb224b060fbaa2b71e8053f2f3321929b3d637ea340519','nova/audio/words/de-fa/13/danke-27a8c76a890a.mp3',975),
('53b4cad2af433dbd40b378ea0a7139a292c7db7dd9171094001a53570435694b','Deutsch','Deutsch','noun','آلمانی','801cfe0fa1182664d16f4aaf7856cc73412f79ef508a866eebc2e5ccf125ff0a','nova/audio/words/de-fa/53/deutsch-80e9759cd8d3.mp3',1161),
('bb6bd200ca400740a5bc3472453cb70d9fdb6768cd0944446b93b20f012627c5','du','du','pronoun','تو','601b2c2473811afea7864a21e4b965a970afa4ce9eaf85dbdf01414bca66c12c','nova/audio/words/de-fa/bb/du-7a9dcf25ace8.mp3',650),
('d19ac4069364a82345ca317b0faad6b15a338b6c3311da46e0e6b5ae1b626816','Freut mich','Freut mich','phrase','از آشنایی خوشحالم','e20e590f16aefd697adafff5f97304a2300ce5bc92d435620d6dd276dcdc4a5b','nova/audio/words/de-fa/d1/freut-mich-5be4dba41517.mp3',1022),
('4e904b55d131fe212ff497e3539ebe8cc2d88ee823cf6a9bdc0d1b8f9a428c45','Guten Morgen','Guten Morgen','phrase','صبح بخیر','c872cd6d08e13b1c0d98910bb0b732c34c57aa770221667099dc0076af79c388','nova/audio/words/de-fa/4e/guten-morgen-b54c771102f7.mp3',1161),
('410e266d81b856de41b18e869ebe34062d569cafaa1a73f061b5354743fef428','Hallo','Hallo','interjection','سلام','753692ec36adb4c794c973945eb2a99c1649703ea6f76bf259abb4fb838e013e','nova/audio/words/de-fa/41/hallo-fdccb32fe549.mp3',1068),
('5b509ac6d228137b14f0a9ab8a1f39e5b64eb22b4c98fd34ee5f428ceebe1dcf','heißen','heiße','verb','نام داشتن / نامیده شدن','fcc6a3fa3c70cf9fb7f939357c0a5917f96f86f3b87d4ad88119388da5f42f55','nova/audio/words/de-fa/5b/heisse-d7563b4671de.mp3',1161),
('7338b1d9234e415bcce9d5ae2bb51be9e2998e04697356ed430c4c7767e7fd97','ich','ich','pronoun','من','84c92d8abf326bdb52f1fc6cd6856c41ae9bc1ef4f6056c2672e3d9d301782e1','nova/audio/words/de-fa/73/ich-4d924e30779b.mp3',882),
('7d611f75f38cd6412472fba80a84fafa76a0a07adf535f6f367f6bad180911e0','in','in','preposition','در','582967534d0f909d196b97f9e6921342777aea87b46fa52df165389db1fb8ccf','nova/audio/words/de-fa/7d/in-1027ff46c930.mp3',743),
('a9a57703d51295ba9b3976d7440abbcabf2a6b8c9469f37995488c6a28328bde','Iran','Iran','proper_noun','ایران','18d4e170765cc48842d847de1d0545a2e379e9c87b2af2a6f761681309939ce5','nova/audio/words/de-fa/a9/iran-73a39a4005c1.mp3',836),
('28677af948a849b55cc75f28606bb56f51c2649e7f11d46805c1c8eb3e76b9f8','kommen','komme','verb','آمدن؛ در «aus ... kommen» اهل جایی بودن','ce42862c13e958d4ea10b49b355882a892642acc53ed6438a61d28a244b9afbf','nova/audio/words/de-fa/28/komme-70e75e16d979.mp3',975),
('9b8d8d4ae20c8ac49e6ac34950d42c2e8a9cac0234bc36f2057e151d1f5d83a4','Persisch','Persisch','noun','فارسی','9b30ef4784e43630171d905c4189d05a5fb8e281ea3b2e9bb01135ab905cd199','nova/audio/words/de-fa/9b/persisch-9b2e7574bb2c.mp3',1068),
('13e20d294c06b0249443b985d22aa4ee43a407d9e4b71c0c7d81c1e37e8da516','Sprache','Sprache','noun','زبان','f2a1cc71fa59a04b38c226ecc20d57747090ba3b6d6c11d349f5e052cd87aa5a','nova/audio/words/de-fa/13/sprache-d82341bb2d30.mp3',1115),
('952eefa76ca5a818570f0f8fc6fdc1ed2a76576911c3574c67fec0ece5420bfb','sprechen','spreche','verb','صحبت کردن','c425d35acf3cfcfdf3690469ad66be9f2e18f167794c50370ed465d608a90431','nova/audio/words/de-fa/95/spreche-e37765729ced.mp3',1068),
('5b5713fd3b98410616a88b071864b34a82777b9dcef92c1735569e06173ff19c','Tschüss','Tschüss','interjection','خداحافظ','ae04312b91230acc75758bd35f9494d969718c47d62d16993902e01a83abd6f8','nova/audio/words/de-fa/5b/tschuess-a5c2a2418a08.mp3',1022),
('e8f46a5314e141bcf465d7c742682ac354bb69b33ac535fa547cc6351c4a4a82','wie','Wie','adverb','چطور / چگونه','91fd41108f1fbf8ac2e5b7b2de9ec1e44bdd07af9892b8bf37ae3c4a8e64dd1d','nova/audio/words/de-fa/e8/wie-c232007982d9.mp3',929),
('4ac31a431bc70d6bf9a17aecce41178bb9a3c92dab604a882e5197084eed98ac','wohnen','wohne','verb','زندگی کردن / ساکن بودن','d91591fc9ae9e78bbcaec537e98a926604733e0402bfc8623dfd902bb4806eb4','nova/audio/words/de-fa/4a/wohne-6b01ab4eb735.mp3',1022);

DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_word_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_cleared INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova de-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_word_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_updates AS u
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY u.lemma
     AND BINARY w.display_form=BINARY u.display_form
     AND BINARY w.part_of_speech=BINARY u.part_of_speech
     AND BINARY w.translation=BINARY u.translation
     AND SHA2(w.display_form,256)=u.text_sha256
    GROUP BY u.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Word locators did not match exactly once.';
  END IF;

  SELECT COUNT(*) INTO v_excluded_expected FROM nova_word_audio_exclusions;
  SELECT COUNT(*) INTO v_excluded_invalid
  FROM (
    SELECT x.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_exclusions AS x
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY x.lemma
     AND BINARY w.display_form=BINARY x.display_form
     AND BINARY w.part_of_speech=BINARY x.part_of_speech
     AND BINARY w.translation=BINARY x.translation
     AND SHA2(w.display_form,256)=x.text_sha256
    GROUP BY x.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_exclusions;
  IF v_excluded_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio cleanup aborted: one or more excluded Word locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE words AS w
  JOIN nova_word_audio_exclusions AS x
    ON BINARY x.lemma=BINARY w.lemma
   AND BINARY x.display_form=BINARY w.display_form
   AND BINARY x.part_of_speech=BINARY w.part_of_speech
   AND BINARY x.translation=BINARY w.translation
   AND x.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=NULL,
      w.audio_duration_ms=NULL
  WHERE w.course_id=v_course
    AND (w.audio_url IS NOT NULL OR w.audio_duration_ms IS NOT NULL);
  SET v_cleared=ROW_COUNT();

  UPDATE words AS w
  JOIN nova_word_audio_updates AS u
    ON BINARY u.lemma=BINARY w.lemma
   AND BINARY u.display_form=BINARY w.display_form
   AND BINARY u.part_of_speech=BINARY w.part_of_speech
   AND BINARY u.translation=BINARY w.translation
   AND u.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=u.audio_url,
      w.audio_duration_ms=u.audio_duration_ms
  WHERE w.course_id=v_course;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_words, v_changed AS changed_words,
         v_excluded_expected AS excluded_words, v_cleared AS cleared_words;
END$$
DELIMITER ;
CALL apply_nova_word_audio();
DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
