-- Generated by nova/tts/nova_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to turns.audio_url and turns.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
CREATE TEMPORARY TABLE nova_turn_audio_updates (
  cefr_level VARCHAR(8) NOT NULL,
  module_order INT UNSIGNED NOT NULL,
  chapter_order INT UNSIGNED NOT NULL,
  lesson_order INT UNSIGNED NOT NULL,
  turn_order INT UNSIGNED NOT NULL,
  character_name VARCHAR(120) NOT NULL,
  turn_role VARCHAR(16) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL,
  PRIMARY KEY (cefr_level,module_order,chapter_order,lesson_order,turn_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_turn_audio_updates (cefr_level,module_order,chapter_order,lesson_order,turn_order,character_name,turn_role,text_sha256,audio_url,audio_duration_ms) VALUES
('A1',1,1,1,1,'Lena','character','357a57fe73d6c63bb1923e970f79a924db3a3609eb9797547784a94ee38fc3df','nova/audio/turns/de-fa/A1/m01/c01/l01/t01-lena-1493be49480b.mp3',511),
('A1',1,1,1,2,'Raha','learner','357a57fe73d6c63bb1923e970f79a924db3a3609eb9797547784a94ee38fc3df','nova/audio/turns/de-fa/A1/m01/c01/l01/t02-raha-1c635a71f1bd.mp3',557),
('A1',1,1,1,3,'Lena','character','9057691532bafd36496ef5f7710d8f8d39cfb8c4c5f024e847724979efe70350','nova/audio/turns/de-fa/A1/m01/c01/l01/t03-lena-d13c04bb88a9.mp3',1672),
('A1',1,1,1,4,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l01/t04-raha-b11f4b4048f0.mp3',1393),
('A1',1,1,1,5,'Lena','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c01/l01/t05-lena-58938944703a.mp3',1440),
('A1',1,1,1,6,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l01/t06-raha-1db58f156a7b.mp3',1022),
('A1',1,1,1,7,'Lena','character','a0e0b6ca00a4fc7504106fae267e4e9054861fae40b0a957ee04637923e74034','nova/audio/turns/de-fa/A1/m01/c01/l01/t07-lena-d954d217b938.mp3',1115),
('A1',1,1,1,8,'Raha','learner','dacc874c2bd53ebe5e4e58ff2d986849d5e178e70f823dc9efe9615301ea4b02','nova/audio/turns/de-fa/A1/m01/c01/l01/t08-raha-1862804389ae.mp3',882),
('A1',1,1,2,1,'Lena','character','c622f747de63407eddd65e9a645e63dc5345c85a551a36e4a0094d4520504d2d','nova/audio/turns/de-fa/A1/m01/c01/l02/t01-lena-52067963ffe5.mp3',1161),
('A1',1,1,2,2,'Raha','learner','695f06911a274ab2bc85d35dc335b7f9f5aecb83beb3b0fcba2f11603812dfbe','nova/audio/turns/de-fa/A1/m01/c01/l02/t02-raha-15b204a6702c.mp3',1207),
('A1',1,1,2,3,'Lena','character','1d9f9187df0286a7ac8874a8c503af18c5ec97a2a4311910e2dfdcd9ba2566a0','nova/audio/turns/de-fa/A1/m01/c01/l02/t03-lena-f21066006cc5.mp3',1579),
('A1',1,1,2,4,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l02/t04-raha-27514b1dbe44.mp3',1393),
('A1',1,1,2,5,'Lena','character','73194f62ef568168f74c3df6fef3ee0c665aadab0a74a9228b05198588b17b71','nova/audio/turns/de-fa/A1/m01/c01/l02/t05-lena-517352475f41.mp3',2601),
('A1',1,1,2,6,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l02/t06-raha-670ae945c484.mp3',1068),
('A1',1,1,2,7,'Lena','character','3c4ba2eaae0978b945fdadcf23d5948b020ad40d9d801dfe462c231425709368','nova/audio/turns/de-fa/A1/m01/c01/l02/t07-lena-d0b9810358ee.mp3',836),
('A1',1,1,2,8,'Raha','learner','3c4ba2eaae0978b945fdadcf23d5948b020ad40d9d801dfe462c231425709368','nova/audio/turns/de-fa/A1/m01/c01/l02/t08-raha-9fe47af971aa.mp3',1068),
('A1',1,1,3,1,'Lena','character','1ed0342abf9e85e4846458d134899e0bf3be2a3903cd486d6500b8616b512397','nova/audio/turns/de-fa/A1/m01/c01/l03/t01-lena-4453083d1b53.mp3',1115),
('A1',1,1,3,2,'Raha','learner','e48fca17da79cae4725cec4d22ae285686ac1b6663323474fd7654a9202f3be7','nova/audio/turns/de-fa/A1/m01/c01/l03/t02-raha-63bcfe807154.mp3',1533),
('A1',1,1,3,3,'Lena','character','2753e4860651be83bea82179f42ddb29947635c5ea61b047a06924f8c758f042','nova/audio/turns/de-fa/A1/m01/c01/l03/t03-lena-8ca82fdaacc8.mp3',1347),
('A1',1,1,3,4,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l03/t04-raha-90602ab12d6c.mp3',1254),
('A1',1,1,3,5,'Lena','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c01/l03/t05-lena-58938944703a.mp3',1440),
('A1',1,1,3,6,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l03/t06-raha-db9b0d14eaf9.mp3',1022),
('A1',1,1,3,7,'Lena','character','610e07d140ca4087f2b807158f7d54a625b2c7df39f5bb51b6256180f246e8da','nova/audio/turns/de-fa/A1/m01/c01/l03/t07-lena-f1cd23a77727.mp3',1207),
('A1',1,1,3,8,'Raha','learner','1d1b8d538b7137e4f766aecb6bb35e2a55aa803205c1c702ca3f158da94190a2','nova/audio/turns/de-fa/A1/m01/c01/l03/t08-raha-65bd2d1f18da.mp3',1161),
('A1',1,1,4,1,'Jonas','character','c6c50528f1eca43bb20a4c90a6de1096f86201eab22e80ba27f29d40e6ba0a3e','nova/audio/turns/de-fa/A1/m01/c01/l04/t01-jonas-5d4548fe65db.mp3',1811),
('A1',1,1,4,2,'Raha','learner','0030396148c5f239ce992c26822e583d1680b7f92de653449a1f777546c43f6f','nova/audio/turns/de-fa/A1/m01/c01/l04/t02-raha-7a62a740ddb3.mp3',1811),
('A1',1,1,4,3,'Jonas','character','145109961f9247d97a556351703b72151efc6bb0885b9c6d2e8775ff9761659a','nova/audio/turns/de-fa/A1/m01/c01/l04/t03-jonas-33de76f1986c.mp3',1625),
('A1',1,1,4,4,'Raha','learner','1d3be93f99031f2738e4ae043c9ba9a4593c9e945e05f24bfa9e3a26c3329169','nova/audio/turns/de-fa/A1/m01/c01/l04/t04-raha-8a77352986d1.mp3',975),
('A1',1,1,4,5,'Jonas','character','1d9f9187df0286a7ac8874a8c503af18c5ec97a2a4311910e2dfdcd9ba2566a0','nova/audio/turns/de-fa/A1/m01/c01/l04/t05-jonas-1e7b218e368f.mp3',1486),
('A1',1,1,4,6,'Raha','learner','cb7bbb5d984454b30ac079d95d5e8f671955ae28df411b03ee1563d371ee679d','nova/audio/turns/de-fa/A1/m01/c01/l04/t06-raha-494ff83bf0b2.mp3',1672),
('A1',1,1,4,7,'Jonas','character','3c4ba2eaae0978b945fdadcf23d5948b020ad40d9d801dfe462c231425709368','nova/audio/turns/de-fa/A1/m01/c01/l04/t07-jonas-bb49f20efd82.mp3',836),
('A1',1,1,4,8,'Raha','learner','43f692229732b4a5323689d6dc018a4acb578ca6d48152b78ceb88250d3323fa','nova/audio/turns/de-fa/A1/m01/c01/l04/t08-raha-26a8196c76c1.mp3',882);

DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_turn_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova de-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_turn_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order,
           COUNT(c.id) AS matched_rows
    FROM nova_turn_audio_updates AS u
    LEFT JOIN levels AS lv
      ON lv.course_id=v_course AND lv.cefr_level=u.cefr_level
    LEFT JOIN modules AS m
      ON m.level_id=lv.id AND m.sort_order=u.module_order
    LEFT JOIN chapters AS ch
      ON ch.module_id=m.id AND ch.sort_order=u.chapter_order
    LEFT JOIN lessons AS l
      ON l.chapter_id=ch.id AND l.sort_order=u.lesson_order
    LEFT JOIN turns AS t
      ON t.lesson_id=l.id AND t.sort_order=u.turn_order
     AND t.role=u.turn_role AND SHA2(t.text,256)=u.text_sha256
    LEFT JOIN characters AS c
      ON c.id=t.character_id AND c.course_id=v_course AND c.name=u.character_name
    GROUP BY u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order
    HAVING COUNT(c.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Turn locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE turns AS t
  JOIN lessons AS l ON l.id=t.lesson_id
  JOIN chapters AS ch ON ch.id=l.chapter_id
  JOIN modules AS m ON m.id=ch.module_id
  JOIN levels AS lv ON lv.id=m.level_id AND lv.course_id=v_course
  JOIN characters AS c ON c.id=t.character_id AND c.course_id=v_course
  JOIN nova_turn_audio_updates AS u
    ON u.cefr_level=lv.cefr_level
   AND u.module_order=m.sort_order
   AND u.chapter_order=ch.sort_order
   AND u.lesson_order=l.sort_order
   AND u.turn_order=t.sort_order
   AND u.character_name=c.name
   AND u.turn_role=t.role
   AND u.text_sha256=SHA2(t.text,256)
  SET t.audio_url=u.audio_url,
      t.audio_duration_ms=u.audio_duration_ms;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_turns, v_changed AS changed_turns;
END$$
DELIMITER ;
CALL apply_nova_turn_audio();
DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
