-- SERIES 2
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS nova_de_v3_s002;
DELIMITER $$
CREATE PROCEDURE nova_de_v3_s002()
BEGIN
  DECLARE v_count INT DEFAULT 0;
  DECLARE v_course BIGINT UNSIGNED; DECLARE v_level BIGINT UNSIGNED; DECLARE v_module BIGINT UNSIGNED; DECLARE v_chapter BIGINT UNSIGNED;
  DECLARE v_c_raha BIGINT UNSIGNED; DECLARE v_c_lena BIGINT UNSIGNED;
  DECLARE v_l_1 BIGINT UNSIGNED; DECLARE v_l_2 BIGINT UNSIGNED; DECLARE v_l_3 BIGINT UNSIGNED; DECLARE v_l_4 BIGINT UNSIGNED;
  DECLARE v_u_1 BIGINT UNSIGNED; DECLARE v_u_2 BIGINT UNSIGNED; DECLARE v_u_3 BIGINT UNSIGNED; DECLARE v_u_4 BIGINT UNSIGNED; DECLARE v_u_5 BIGINT UNSIGNED; DECLARE v_u_6 BIGINT UNSIGNED; DECLARE v_u_7 BIGINT UNSIGNED; DECLARE v_u_8 BIGINT UNSIGNED;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;
  SELECT COUNT(*),MIN(id) INTO v_count,v_course FROM courses WHERE learning_language='de' AND base_language='fa'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa course identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_level FROM levels WHERE course_id=v_course AND cefr_level='A1'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa A1 missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_module FROM modules WHERE level_id=v_level AND sort_order=1; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='de-fa module 1 missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_c_raha FROM characters WHERE course_id=v_course AND name='Raha' AND gender='female'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Raha identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_c_lena FROM characters WHERE course_id=v_course AND name='Lena' AND gender='female'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Lena identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_chapter FROM chapters WHERE module_id=v_module AND sort_order=2;
  IF v_count=0 THEN
    INSERT INTO chapters (module_id,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_module,'Woher kommst du?','اهل کجا هستی؟','Raha tells Lena where she is from and where she lives, then transfers the same information to a new interaction.','رها به لنا می‌گوید اهل کجاست و کجا زندگی می‌کند و بعد همین اطلاعات را در یک آشنایی تازه به کار می‌برد.',4,1,1,2,'validated',JSON_OBJECT('series',2,'contractVersion','3.0.0','level','A1','storyline','berlin_new_start','generatedStatus','locally_validated')); SET v_chapter=LAST_INSERT_ID();
    INSERT INTO learning_units (course_id,unit_type,unit_key,display_form,translation,description_fa,cefr_level,difficulty,data,metadata) VALUES
      (v_course,'chunk','de:a1:woher-kommst-du','Woher kommst du?','اهل کجا هستی؟','پرسش غیررسمی درباره مبدأ شخص','A1',1,JSON_OBJECT('function','ask_origin'),JSON_OBJECT('series',2)),
      (v_course,'chunk','de:a1:ich-komme-aus','Ich komme aus ...','من اهل ... هستم','الگوی طبیعی برای گفتن مبدأ','A1',1,JSON_OBJECT('function','state_origin'),JSON_OBJECT('series',2)),
      (v_course,'chunk','de:a1:wo-wohnst-du','Wo wohnst du?','کجا زندگی می‌کنی؟','پرسش غیررسمی درباره محل زندگی','A1',1,JSON_OBJECT('function','ask_residence'),JSON_OBJECT('series',2)),
      (v_course,'chunk','de:a1:ich-wohne-in','Ich wohne in ...','من در ... زندگی می‌کنم','الگوی پایه برای گفتن محل زندگی','A1',1,JSON_OBJECT('function','state_residence'),JSON_OBJECT('series',2)),
      (v_course,'word_sense','de:a1:aus:origin','aus','از / اهلِ','aus در ساخت بیان مبدأ','A1',1,JSON_OBJECT('pos','preposition','sense','origin'),JSON_OBJECT('series',2)),
      (v_course,'construction','de:a1:origin-vs-residence','aus + Herkunft / in + Wohnort','از برای مبدأ / در برای محل زندگی','تمایز کاربردی مبدأ و محل زندگی','A1',1,JSON_OBJECT('function','origin_residence_contrast'),JSON_OBJECT('series',2)),
      (v_course,'pronunciation','de:a1:pron:w-v','w in Wo / wohnen',NULL,'w آلمانی در Wo و wohnen مانند v شنیده می‌شود','A1',1,JSON_OBJECT('target','z_ts_and_w_v'),JSON_OBJECT('series',2)),
      (v_course,'can_do','de:a1:can-do:origin-residence','ask and state origin and residence',NULL,'مبدأ و محل زندگی را بپرسد و بگوید','A1',1,JSON_OBJECT('curriculum','identity_origin_residence'),JSON_OBJECT('series',2));
    SELECT id INTO v_u_1 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:woher-kommst-du'; SELECT id INTO v_u_2 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-komme-aus'; SELECT id INTO v_u_3 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:wo-wohnst-du'; SELECT id INTO v_u_4 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:ich-wohne-in'; SELECT id INTO v_u_5 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:aus:origin'; SELECT id INTO v_u_6 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:origin-vs-residence'; SELECT id INTO v_u_7 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:pron:w-v'; SELECT id INTO v_u_8 FROM learning_units WHERE course_id=v_course AND unit_key='de:a1:can-do:origin-residence';
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) VALUES
      (v_course,'kommen','komme','verb','آمدن؛ در «aus ... kommen» اهل جایی بودن',1,NULL,JSON_ARRAY('wohnen','heißen'),'Ich komme aus Iran.','من اهل ایران هستم.',JSON_OBJECT('series',2,'contractVersion','3.0.0')),
      (v_course,'aus','aus','preposition','از / اهلِ',1,NULL,JSON_ARRAY('in','wo'),'Ich komme aus Iran.','من اهل ایران هستم.',JSON_OBJECT('series',2,'contractVersion','3.0.0')),
      (v_course,'Iran','Iran','proper_noun','ایران',1,NULL,JSON_ARRAY('Berlin','Lena'),'Ich komme aus Iran.','من اهل ایران هستم.',JSON_OBJECT('series',2,'contractVersion','3.0.0')),
      (v_course,'wohnen','wohne','verb','زندگی کردن / ساکن بودن',1,NULL,JSON_ARRAY('kommen','heißen'),'Ich wohne in Berlin.','من در برلین زندگی می‌کنم.',JSON_OBJECT('series',2,'contractVersion','3.0.0')),
      (v_course,'in','in','preposition','در',1,NULL,JSON_ARRAY('aus','wie'),'Ich wohne in Berlin.','من در برلین زندگی می‌کنم.',JSON_OBJECT('series',2,'contractVersion','3.0.0')),
      (v_course,'Berlin','Berlin','proper_noun','برلین',1,NULL,JSON_ARRAY('Iran','Raha'),'Ich wohne in Berlin.','من در برلین زندگی می‌کنم.',JSON_OBJECT('series',2,'contractVersion','3.0.0'));
    INSERT INTO curriculum_outcomes (course_id,cefr_level,outcome_key,outcome_type,title,description_fa,required,status,evidence,metadata) VALUES
      (v_course,'A1','can_do:origin_residence','can_do','مبدأ و محل زندگی','مبدأ و محل زندگی را بپرسد و بگوید.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',2)),
      (v_course,'A1','grammar:origin_residence_chunks','grammar','aus و in در دو ساخت پایه','aus برای مبدأ و in برای محل زندگی را در این دو ساخت درست انتخاب کند.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',2)),
      (v_course,'A1','reading:identity_origin_residence','reading','خواندن معرفی با مبدأ و محل زندگی','نام، مبدأ و محل زندگی را از متن کوتاه پیدا کند.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',2)),
      (v_course,'A1','listening:origin_residence','listening','شنیدن مبدأ و محل زندگی','در دیالوگ آهسته مبدأ و محل زندگی را تشخیص دهد.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',2)),
      (v_course,'A1','pron:w_v','pronunciation','w آلمانی','w در Wo و wohnen را با صدای v تولید کند.',1,'in_progress',JSON_ARRAY(),JSON_OBJECT('seriesStarted',2))
      ON DUPLICATE KEY UPDATE status=status;

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_lena,v_c_raha,'Woher kommst du?','اهل کجا هستی؟','Lena asks Raha about her origin.','لنا از رها درباره مبدأش می‌پرسد.','story','berlin_new_start',5,1,480,1,'validated',JSON_OBJECT('pedagogicalRole','exposure')); SET v_l_1=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
      (v_l_1,v_c_lena,1,'character','Hallo, Raha!','سلام، رها!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_raha,2,'learner','Hallo, Lena!','سلام، لنا!',1,'Hallo, Lena!',JSON_ARRAY('Hallo, Lena!','Guten Morgen, Lena!'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_lena,3,'character','Woher kommst du?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_raha,4,'learner','Ich komme aus Iran.','من اهل ایران هستم.',1,'Ich komme aus Iran.',JSON_ARRAY('Ich komme aus Iran.','Aus Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_lena,5,'character','Ah, aus Iran. Schön!','آهان، از ایران. چه خوب!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_raha,6,'learner','Ja, aus Iran.','بله، از ایران.',1,'Ja, aus Iran.',JSON_ARRAY('Ja, aus Iran.','Genau, aus Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_lena,7,'character','Willkommen in Berlin!','به برلین خوش آمدی!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_raha,8,'learner','Danke!','ممنون!',1,'Danke!',JSON_ARRAY('Danke!','Danke schön!'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_1,'listen',1,'Woher kommst du?','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'chunk',2,'Woher kommst du?','پرسش مبدأ را یک تکه یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:woher-kommst-du","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'listen',3,'Ich komme aus Iran.','جواب را کامل گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'chunk',4,'Ich komme aus ...','الگوی گفتن مبدأ را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-komme-aus","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'reading_comprehension',5,'aus + Ort','نکته را بخوان.',1,CAST('{"mode":"micro_grammar","explanation_fa":"در این الگو aus مبدأ را نشان می‌دهد. فعلا Ich komme aus + مکان را یک ساخت آماده استفاده کن.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'meaning_choice',6,'Ich komme ___ Iran.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["aus","in","wie"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',7,'بگو اهل ایران هستی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اهل ایران هستی.","accepted":["Ich komme aus Iran.","Ich bin aus Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'reading',8,'Raha: Hallo! Ich heiße Raha. Ich komme aus Iran.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Raha: Hallo! Ich heiße Raha. Ich komme aus Iran.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'reading_comprehension',9,'Woher kommt Raha?','از متن جواب را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Aus Iran.","Aus Berlin.","Aus Lena."],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'pronunciation',10,'Woher','w ابتدای Woher را تقلید کن.',1,CAST('{"mode":"sound_notice","target":"z_ts_and_w_v","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',11,'نامت را بگو.','مرور Series 001.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"یک نفر تازه نامت را می‌پرسد. پاسخ بده.","accepted_intents":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',12,'مبدأت را بگو.','انتقال.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"یک نفر تازه می‌پرسد اهل کجایی.","accepted_intents":["Ich komme aus Iran.","Ich bin aus Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_lena,v_c_raha,'Wo wohnst du?','کجا زندگی می‌کنی؟','Lena asks about Raha’s current home.','لنا درباره محل زندگی فعلی رها می‌پرسد.','story','berlin_new_start',6,1,480,2,'validated',JSON_OBJECT('pedagogicalRole','explicit_form')); SET v_l_2=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
      (v_l_2,v_c_lena,1,'character','Wo wohnst du jetzt?','الان کجا زندگی می‌کنی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_raha,2,'learner','Ich wohne in Berlin.','من در برلین زندگی می‌کنم.',1,'Ich wohne in Berlin.',JSON_ARRAY('Ich wohne in Berlin.','In Berlin.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_lena,3,'character','In Berlin?','در برلین؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_raha,4,'learner','Ja, in Berlin.','بله، در برلین.',1,'Ja, in Berlin.',JSON_ARRAY('Ja, in Berlin.','Genau, in Berlin.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_lena,5,'character','Und woher kommst du?','و اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_raha,6,'learner','Ich komme aus Iran.','من اهل ایران هستم.',1,'Ich komme aus Iran.',JSON_ARRAY('Ich komme aus Iran.','Aus Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_lena,7,'character','Sehr gut.','خیلی خوب.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_raha,8,'learner','Danke.','ممنون.',1,'Danke.',JSON_ARRAY('Danke.','Danke schön.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_2,'listen',1,'Wo wohnst du jetzt?','فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'chunk',2,'Wo wohnst du?','پرسش محل زندگی را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:wo-wohnst-du","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'listen',3,'Ich wohne in Berlin.','جواب را گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'chunk',4,'Ich wohne in ...','الگوی محل زندگی را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-wohne-in","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'reading_comprehension',5,'aus / in','تفاوت را ببین.',1,CAST('{"mode":"micro_grammar","explanation_fa":"برای مبدأ در این درس aus می‌آید؛ برای محل زندگی in می‌آید.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'meaning_choice',6,'Ich wohne ___ Berlin.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["in","aus","du"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',7,'بگو در برلین زندگی می‌کنی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو در برلین زندگی می‌کنی.","accepted":["Ich wohne in Berlin.","Ich lebe in Berlin."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'reading',8,'Lena: Wo wohnst du? Raha: Ich wohne in Berlin.','گفت‌وگو را بخوان.',1,CAST('{"mode":"reading_input","text":"Lena: Wo wohnst du? Raha: Ich wohne in Berlin.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'reading_comprehension',9,'Wo wohnt Raha?','از متن جواب را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["In Berlin.","In Iran.","Aus Berlin."],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'pronunciation',10,'wohne','w ابتدای wohnen را تقلید کن.',1,CAST('{"mode":"sound_notice","target":"z_ts_and_w_v","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',11,'نام طرف مقابل را بپرس.','مرور Series 001.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"نام فرد تازه را بپرس.","accepted_intents":["Wie heißt du?","Und wie heißt du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',12,'مبدأ و محل زندگی را بگو.','انتقال.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بگو اهل کجایی و کجا زندگی می‌کنی.","accepted_intents":["Ich komme aus Iran. Ich wohne in Berlin.","Ich bin aus Iran und wohne in Berlin."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_lena,v_c_raha,'Aus Iran, in Berlin','اهل ایران، ساکن برلین','Raha retrieves origin and residence together.','رها مبدأ و محل زندگی را باهم بازیابی می‌کند.','story','berlin_new_start',7,1,500,3,'validated',JSON_OBJECT('pedagogicalRole','retrieval')); SET v_l_3=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
      (v_l_3,v_c_lena,1,'character','Hallo! Wie heißt du?','سلام! اسمت چیست؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_raha,2,'learner','Ich heiße Raha.','من رها هستم.',1,'Ich heiße Raha.',JSON_ARRAY('Ich heiße Raha.','Ich bin Raha.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_lena,3,'character','Woher kommst du?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_raha,4,'learner','Ich komme aus Iran.','من اهل ایران هستم.',1,'Ich komme aus Iran.',JSON_ARRAY('Ich komme aus Iran.','Ich bin aus Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_lena,5,'character','Und wo wohnst du?','و کجا زندگی می‌کنی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_raha,6,'learner','Ich wohne in Berlin.','من در برلین زندگی می‌کنم.',1,'Ich wohne in Berlin.',JSON_ARRAY('Ich wohne in Berlin.','In Berlin.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_lena,7,'character','Freut mich, Raha.','رها، از آشنایی خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_raha,8,'learner','Freut mich auch.','من هم از آشنایی خوشحالم.',1,'Freut mich auch.',JSON_ARRAY('Freut mich auch.','Mich auch.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_3,'listen',1,'Woher kommst du? Und wo wohnst du?','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'reading_comprehension',2,'Woher? / Wo?','تفاوت را ببین.',1,CAST('{"mode":"micro_grammar","explanation_fa":"Woher درباره مبدأ و Wo درباره مکان می‌پرسد.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'chunk',3,'Ich komme aus ...','الگوی مبدأ را مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-komme-aus","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'chunk',4,'Ich wohne in ...','الگوی محل زندگی را مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"de:a1:ich-wohne-in","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'meaning_choice',5,'Ich komme ___ Iran.','کامل کن.',1,CAST('{"mode":"sentence_blank","options":["aus","in","wo"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',6,'پرسش مبدأ را بگو.','از حافظه.',1,CAST('{"mode":"recall_hidden","cue_fa":"از طرف مقابل بپرس اهل کجاست.","accepted":["Woher kommst du?","Und woher kommst du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',7,'پرسش محل زندگی را بگو.','از حافظه.',1,CAST('{"mode":"recall_hidden","cue_fa":"بپرس کجا زندگی می‌کند.","accepted":["Wo wohnst du?","Und wo wohnst du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'reading',8,'Ich heiße Raha. Ich komme aus Iran. Ich wohne in Berlin.','معرفی را بخوان.',1,CAST('{"mode":"reading_input","text":"Ich heiße Raha. Ich komme aus Iran. Ich wohne in Berlin.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'reading_comprehension',9,'Welche Information stimmt?','انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["Raha wohnt in Berlin.","Raha kommt aus Berlin.","Raha heißt Lena."],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'pronunciation',10,'Woher? Wo?','w آلمانی را تقلید کن.',1,CAST('{"mode":"sound_notice","target":"z_ts_and_w_v","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',11,'بعد از معرفی پاسخ آشنایی بده.','مرور Series 001.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"طرف مقابل می‌گوید Freut mich. پاسخ بده.","accepted_intents":["Freut mich auch.","Mich auch."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',12,'خودت را کامل معرفی کن.','انتقال.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"نام، مبدأ و محل زندگی‌ات را بگو.","accepted_intents":["Ich heiße Raha. Ich komme aus Iran. Ich wohne in Berlin.","Ich bin Raha. Ich bin aus Iran und wohne in Berlin."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_lena,v_c_raha,'Neu im Haus','تازه در ساختمان','Raha uses the language independently in a new-neighbor scenario.','رها زبان را در موقعیت همسایه تازه مستقل به کار می‌برد.','story','berlin_new_start',8,1,520,4,'validated',JSON_OBJECT('pedagogicalRole','mastery','masteryCheck',TRUE)); SET v_l_4=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
      (v_l_4,v_c_lena,1,'character','Hallo! Wie heißt du?','سلام! اسمت چیست؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_raha,2,'learner','Hallo! Ich heiße Raha.','سلام! من رها هستم.',1,'Hallo! Ich heiße Raha.',JSON_ARRAY('Hallo! Ich heiße Raha.','Hallo! Ich bin Raha.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_lena,3,'character','Woher kommst du?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_raha,4,'learner','Ich komme aus Iran.','من اهل ایران هستم.',1,'Ich komme aus Iran.',JSON_ARRAY('Ich komme aus Iran.','Ich bin aus Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_lena,5,'character','Wo wohnst du jetzt?','الان کجا زندگی می‌کنی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_raha,6,'learner','Ich wohne in Berlin.','من در برلین زندگی می‌کنم.',1,'Ich wohne in Berlin.',JSON_ARRAY('Ich wohne in Berlin.','In Berlin.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_lena,7,'character','Freut mich. Bis später!','از آشنایی خوشحالم. بعدا می‌بینمت!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_raha,8,'learner','Freut mich auch. Tschüss!','من هم از آشنایی خوشحالم. خداحافظ!',1,'Freut mich auch. Tschüss!',JSON_ARRAY('Freut mich auch. Tschüss!','Mich auch. Bis später!'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_4,'listen',1,'Hallo! Wie heißt du?','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'reading_comprehension',2,'نام + مبدأ + محل زندگی','نقشه پاسخ را مرور کن.',1,CAST('{"mode":"micro_grammar","explanation_fa":"سه الگو را بازیابی کن: Ich heiße..., Ich komme aus..., Ich wohne in....","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',3,'نامت را بگو.','از حافظه.',1,CAST('{"mode":"recall_hidden","cue_fa":"نامت را بگو.","accepted":["Ich heiße Raha.","Ich bin Raha."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',4,'مبدأت را بگو.','از حافظه.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اهل ایران هستی.","accepted":["Ich komme aus Iran.","Ich bin aus Iran."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',5,'محل زندگی را بگو.','از حافظه.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو در برلین زندگی می‌کنی.","accepted":["Ich wohne in Berlin.","Ich lebe in Berlin."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'meaning_choice',6,'Ich wohne ___ Berlin.','کامل کن.',1,CAST('{"mode":"sentence_blank","options":["in","aus","woher"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'reading',7,'Woher kommst du? — Ich komme aus Iran. Wo wohnst du? — Ich wohne in Berlin.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Woher kommst du? — Ich komme aus Iran. Wo wohnst du? — Ich wohne in Berlin.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'reading_comprehension',8,'Wo wohnt Raha?','جواب را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["In Berlin.","Aus Iran.","In Jonas."],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'pronunciation',9,'Wo wohnst du?','w آلمانی را تقلید کن.',1,CAST('{"mode":"sound_notice","target":"z_ts_and_w_v","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',10,'گفت‌وگوی آشنایی را تمام کن.','مرور Series 001.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بعد از آشنایی پاسخ مناسب و خداحافظی بگو.","accepted_intents":["Freut mich auch. Tschüss!","Mich auch. Bis später!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',11,'خودت را مستقل معرفی کن.','mastery transfer.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"نام، مبدأ و محل زندگی را بدون راهنما بگو.","accepted_intents":["Hallo! Ich heiße Raha. Ich komme aus Iran. Ich wohne in Berlin.","Hallo! Ich bin Raha. Ich bin aus Iran und wohne in Berlin."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',12,'دو پرسش بپرس.','mastery transfer.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"از فرد تازه بپرس اهل کجاست و کجا زندگی می‌کند.","accepted_intents":["Woher kommst du? Wo wohnst du?","Und woher kommst du? Wo wohnst du?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,metadata) VALUES (v_l_1,v_u_1,'new',1,1,JSON_OBJECT()),(v_l_1,v_u_2,'new',1,1,JSON_OBJECT()),(v_l_1,v_u_5,'new',1,1,JSON_OBJECT()),(v_l_1,v_u_7,'new',1,1,JSON_OBJECT()),(v_l_2,v_u_3,'new',1,1,JSON_OBJECT()),(v_l_2,v_u_4,'new',1,1,JSON_OBJECT()),(v_l_2,v_u_6,'new',1,1,JSON_OBJECT()),(v_l_3,v_u_1,'review',1,1,JSON_OBJECT()),(v_l_3,v_u_2,'review',1,1,JSON_OBJECT()),(v_l_3,v_u_3,'review',1,1,JSON_OBJECT()),(v_l_3,v_u_4,'review',1,1,JSON_OBJECT()),(v_l_4,v_u_1,'mastery',1,1,JSON_OBJECT()),(v_l_4,v_u_2,'mastery',1,1,JSON_OBJECT()),(v_l_4,v_u_3,'mastery',1,1,JSON_OBJECT()),(v_l_4,v_u_4,'mastery',1,1,JSON_OBJECT()),(v_l_4,v_u_8,'mastery',1,1,JSON_OBJECT());
    UPDATE review_obligations SET status='fulfilled',fulfilled_chapter_id=v_chapter,metadata=JSON_SET(COALESCE(metadata,JSON_OBJECT()),'$.evidenceSeries',2,'$.evidenceType','retrieval_transfer','$.evidenceFile','review_evidence_v3.json') WHERE course_id=v_course AND due_series=2 AND status='due';
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,3,1,'due',JSON_OBJECT('originSeries',2) FROM learning_units WHERE course_id=v_course AND JSON_EXTRACT(metadata,'$.series')=2;
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,4,2,'due',JSON_OBJECT('originSeries',2) FROM learning_units WHERE course_id=v_course AND JSON_EXTRACT(metadata,'$.series')=2;
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,6,4,'due',JSON_OBJECT('originSeries',2) FROM learning_units WHERE course_id=v_course AND JSON_EXTRACT(metadata,'$.series')=2;
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,10,8,'due',JSON_OBJECT('originSeries',2) FROM learning_units WHERE course_id=v_course AND JSON_EXTRACT(metadata,'$.series')=2;
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,id,v_chapter,18,16,'due',JSON_OBJECT('originSeries',2) FROM learning_units WHERE course_id=v_course AND JSON_EXTRACT(metadata,'$.series')=2;
    UPDATE curriculum_outcomes SET status='covered',evidence=JSON_ARRAY(JSON_OBJECT('series',2,'lesson',4,'type','mastery_transfer')) WHERE course_id=v_course AND cefr_level='A1' AND outcome_key IN ('can_do:origin_residence','grammar:origin_residence_chunks','reading:identity_origin_residence','listening:origin_residence','pron:w_v');
  END IF;
  COMMIT;
END$$
DELIMITER ;
CALL nova_de_v3_s002();
DROP PROCEDURE nova_de_v3_s002;
