-- NOVA v9 RESET
SET FOREIGN_KEY_CHECKS=0;
DROP VIEW IF EXISTS v_lesson_story;
DROP TABLE IF EXISTS activities;
DROP TABLE IF EXISTS lesson_words;
DROP TABLE IF EXISTS turns;
DROP TABLE IF EXISTS words;
DROP TABLE IF EXISTS lessons;
DROP TABLE IF EXISTS characters;
DROP TABLE IF EXISTS chapters;
DROP TABLE IF EXISTS modules;
DROP TABLE IF EXISTS levels;
DROP TABLE IF EXISTS courses;
SET FOREIGN_KEY_CHECKS=1;
