-- SERIES 1
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS nova_en_v3_s001;
DELIMITER $$
CREATE PROCEDURE nova_en_v3_s001()
BEGIN
  DECLARE v_count INT DEFAULT 0;
  DECLARE v_course BIGINT UNSIGNED;
  DECLARE v_level BIGINT UNSIGNED;
  DECLARE v_module BIGINT UNSIGNED;
  DECLARE v_chapter BIGINT UNSIGNED;
  DECLARE v_c_arman BIGINT UNSIGNED;
  DECLARE v_c_maya BIGINT UNSIGNED;
  DECLARE v_l_1 BIGINT UNSIGNED; DECLARE v_l_2 BIGINT UNSIGNED; DECLARE v_l_3 BIGINT UNSIGNED; DECLARE v_l_4 BIGINT UNSIGNED;
  DECLARE v_u_hello BIGINT UNSIGNED; DECLARE v_u_goodbye BIGINT UNSIGNED; DECLARE v_u_name BIGINT UNSIGNED; DECLARE v_u_myname BIGINT UNSIGNED; DECLARE v_u_nicemeet BIGINT UNSIGNED; DECLARE v_u_howare BIGINT UNSIGNED; DECLARE v_u_pron BIGINT UNSIGNED;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;

  SELECT COUNT(*),MIN(id) INTO v_count,v_course FROM courses WHERE learning_language='en' AND base_language='fa';
  IF v_count=0 THEN INSERT INTO courses (learning_language,base_language,title,title_translation,status,metadata) VALUES ('en','fa','English for Persian Speakers','انگلیسی برای فارسی‌زبان‌ها','active',JSON_OBJECT('contractVersion','3.0.0')); SET v_course=LAST_INSERT_ID(); ELSEIF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='en-fa course identity not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_level FROM levels WHERE course_id=v_course AND cefr_level='A1';
  IF v_count=0 THEN INSERT INTO levels (course_id,cefr_level,title,title_translation,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_course,'A1','A1 Foundations','پایه A1',1,2,1,'active',JSON_OBJECT('completionMode','dynamic_outcome_mastery')); SET v_level=LAST_INSERT_ID(); END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_module FROM modules WHERE level_id=v_level AND sort_order=1;
  IF v_count=0 THEN INSERT INTO modules (level_id,title,title_translation,emoji,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_level,'First Connections','اولین ارتباط‌ها','👋',1,2,1,'active',JSON_OBJECT('dynamic',TRUE)); SET v_module=LAST_INSERT_ID(); END IF;

  SELECT COUNT(*),MIN(id) INTO v_count,v_c_arman FROM characters WHERE course_id=v_course AND name='Arman' AND gender='male';
  IF v_count=0 THEN INSERT INTO characters (course_id,name,gender,voice_key,profile,metadata) VALUES (v_course,'Arman','male','arman',JSON_OBJECT('role','زبان‌آموز و شخصیت اصلی'),JSON_OBJECT('context',NULL,'originCountry',NULL)); SET v_c_arman=LAST_INSERT_ID(); END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_c_maya FROM characters WHERE course_id=v_course AND name='Maya' AND gender='female';
  IF v_count=0 THEN INSERT INTO characters (course_id,name,gender,voice_key,profile,metadata) VALUES (v_course,'Maya','female','maya',JSON_OBJECT('role','دوست آرمان در لندن'),JSON_OBJECT('context',NULL,'originCountry',NULL)); SET v_c_maya=LAST_INSERT_ID(); END IF;

  SELECT COUNT(*),MIN(id) INTO v_count,v_chapter FROM chapters WHERE module_id=v_module AND sort_order=1;
  IF v_count=0 THEN
    INSERT INTO chapters (module_id,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_module,'Hello, I’m Arman','سلام، من آرمانم','Arman meets Maya and learns a first natural greeting and introduction.','آرمان با مایا آشنا می‌شود و اولین سلام و معرفی طبیعی را یاد می‌گیرد.',4,1,1,1,'validated',JSON_OBJECT('series',1,'contractVersion','3.0.0','level','A1')); SET v_chapter=LAST_INSERT_ID();

    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) VALUES (v_course,'hello','hello','interjection','سلام',1,JSON_OBJECT('cefr','A1','sense','greeting'),CAST('["خداحافظ","ممنون","بله"]' AS JSON),'Hello! I’m Maya.','سلام! من مایا هستم.',JSON_OBJECT('sourceSeries',1,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:hello:greeting'));
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) VALUES (v_course,'goodbye','goodbye','interjection','خداحافظ',1,JSON_OBJECT('cefr','A1','sense','parting'),CAST('["سلام","ممنون","بله"]' AS JSON),'Goodbye!','خداحافظ!',JSON_OBJECT('sourceSeries',1,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:goodbye:parting'));
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) VALUES (v_course,'name','name','noun','نام',1,JSON_OBJECT('cefr','A1','sense','personal_name'),CAST('["شهر","زمان","سلام"]' AS JSON),'My name is Arman.','اسم من آرمان است.',JSON_OBJECT('sourceSeries',1,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:name:person-name'));

    INSERT INTO learning_units (course_id,unit_type,unit_key,display_form,translation,description_fa,cefr_level,difficulty,data,metadata) VALUES
    (v_course,'word_sense','en:a1:hello:greeting','hello','سلام','سلام رایج برای شروع تعامل','A1',1,JSON_OBJECT('pos','interjection'),JSON_OBJECT('series',1)),
    (v_course,'word_sense','en:a1:goodbye:parting','goodbye','خداحافظ','پایان خنثی و مودبانه تعامل','A1',1,JSON_OBJECT('pos','interjection'),JSON_OBJECT('series',1)),
    (v_course,'word_sense','en:a1:name:person-name','name','نام','نام شخص در معرفی','A1',1,JSON_OBJECT('pos','noun'),JSON_OBJECT('series',1)),
    (v_course,'chunk','en:a1:my-name-is','My name is ...','اسم من ... است','الگوی معرفی نام','A1',1,JSON_OBJECT(),JSON_OBJECT('series',1)),
    (v_course,'chunk','en:a1:nice-to-meet-you','Nice to meet you.','از آشنایی با شما خوشحالم.','عبارت ثابت پس از معرفی','A1',1,JSON_OBJECT(),JSON_OBJECT('series',1)),
    (v_course,'chunk','en:a1:how-are-you','How are you?','حالت چطور است؟','پرسش رایج درباره حال','A1',1,JSON_OBJECT(),JSON_OBJECT('series',1)),
    (v_course,'pronunciation','en:a1:pron:hello-stress','hello — stress on second syllable',NULL,'تاکید hello روی هجای دوم است.','A1',1,JSON_OBJECT('target','basic_word_stress'),JSON_OBJECT('series',1));
    SELECT id INTO v_u_hello FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:hello:greeting'; SELECT id INTO v_u_goodbye FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:goodbye:parting'; SELECT id INTO v_u_name FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:name:person-name'; SELECT id INTO v_u_myname FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:my-name-is'; SELECT id INTO v_u_nicemeet FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:nice-to-meet-you'; SELECT id INTO v_u_howare FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:how-are-you'; SELECT id INTO v_u_pron FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:pron:hello-stress';
    INSERT INTO curriculum_outcomes (course_id,cefr_level,outcome_key,outcome_type,title,description_fa,required,status,evidence) VALUES (v_course,'A1','can_do:greet_part','can_do','Greet and part','سلام و خداحافظی پایه',1,'in_progress',JSON_ARRAY()),(v_course,'A1','can_do:introduce_name','can_do','Say your name','گفتن نام خود',1,'in_progress',JSON_ARRAY()),(v_course,'A1','reading:short_identity','reading','Read a short identity message','پیدا کردن نام از پیام کوتاه',1,'in_progress',JSON_ARRAY()),(v_course,'A1','pron:basic_word_stress','pronunciation','Notice word stress','تشخیص تاکید واژه پایه',1,'in_progress',JSON_ARRAY());

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_maya,v_c_arman,'A First Hello','اولین سلام','Maya greets Arman.','مایا به آرمان سلام می‌کند.','story','london_new_start',1,1,420,1,'validated',JSON_OBJECT('pedagogicalRole','exposure')); SET v_l_1=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_maya,1,'character','Hello!','سلام!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_arman,2,'learner','Hello!','سلام!',1,'Hello!',JSON_ARRAY('Hello!','Hi!'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_maya,3,'character','I’m Maya.','من مایا هستم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_arman,4,'learner','I’m Arman.','من آرمان هستم.',1,'I’m Arman.',JSON_ARRAY('I’m Arman.','My name is Arman.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_maya,5,'character','Nice to meet you.','از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_arman,6,'learner','Nice to meet you too.','من هم از آشنایی با تو خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_maya,7,'character','Welcome to London.','به لندن خوش آمدی.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_1,v_c_arman,8,'learner','Thank you.','ممنون.',1,'Thank you.',JSON_ARRAY('Thank you.','Thanks.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
    (v_l_1,'listen',1,'Hello!','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_1,'new_word',2,'Hello','معنی و کاربرد را ببین.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:hello:greeting","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_1,'speak',3,'hello','به تاکید هجای دوم دقت کن.',1,CAST('{"mode":"sound_notice","target":"basic_word_stress","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_1,'speak',4,'Hello!','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Hello!","Hi!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_1,'listen',5,'Nice to meet you.','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_1,'new_word',6,'Nice to meet you.','عبارت را یک تکه یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:nice-to-meet-you","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_1,'speak',7,'در اولین دیدار سلام کن.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"در اولین دیدار سلام کن.","accepted":["Hello!","Hi!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_1,'meaning_choice',8,'___!','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["Goodbye","Hello","Thanks"],"answer_index":1,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_1,'reading_comprehension',9,'Maya: Hello! I’m Maya.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Maya: Hello! I’m Maya.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_1,'reading_comprehension',10,'What is her name?','نام را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Maya","Arman","London"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_1,'speak',11,'یک نفر جدید به تو نزدیک می‌شود. سلام کن.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"یک نفر جدید به تو نزدیک می‌شود. سلام کن.","accepted_intents":["Hello!","Hi!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_1,'speak',12,'مایا می‌گوید Nice to meet you. پاسخ بده.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"مایا می‌گوید Nice to meet you. پاسخ بده.","accepted_intents":["Nice to meet you too.","Nice to meet you."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_maya,v_c_arman,'My Name Is Arman','اسم من آرمان است','Arman practices names.','آرمان معرفی نام را تمرین می‌کند.','story','london_new_start',2,1,430,2,'validated',JSON_OBJECT('pedagogicalRole','explicit_form')); SET v_l_2=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_maya,1,'character','What’s your name?','اسمت چیست؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_arman,2,'learner','My name is Arman.','اسم من آرمان است.',1,'My name is Arman.',JSON_ARRAY('My name is Arman.','I’m Arman.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_maya,3,'character','Arman. Nice to meet you.','آرمان. از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_arman,4,'learner','Nice to meet you too.','من هم از آشنایی با تو خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_maya,5,'character','Is your name Arman?','اسمت آرمان است؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_arman,6,'learner','Yes, I’m Arman.','بله، من آرمان هستم.',1,'Yes, I’m Arman.',JSON_ARRAY('Yes, I’m Arman.','Yes. My name is Arman.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_maya,7,'character','Great.','عالی.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_2,v_c_arman,8,'learner','Thank you.','ممنون.',1,'Thank you.',JSON_ARRAY('Thank you.','Thanks.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
    (v_l_2,'listen',1,'What’s your name?','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_2,'new_word',2,'My name is ...','الگو را یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:my-name-is","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_2,'reading_comprehension',3,'My name is Arman.','توضیح را بخوان.',1,CAST('{"mode":"micro_grammar","explanation_fa":"فعلا My name is ... را یک الگوی کامل برای معرفی نام در نظر بگیر.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_2,'speak',4,'My name is Arman.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["My name is Arman.","I’m Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_2,'meaning_choice',5,'My ___ is Arman.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["hello","name","goodbye"],"answer_index":1,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_2,'word_order',6,'My name is Arman','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["Arman","name","My","is"],"answer":["My","name","is","Arman"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_2,'speak',7,'بگو اسمت آرمان است.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو اسمت آرمان است.","accepted":["My name is Arman.","I’m Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_2,'reading_comprehension',8,'Hello. My name is Maya.','بخوان.',1,CAST('{"mode":"reading_input","text":"Hello. My name is Maya.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_2,'reading_comprehension',9,'Who is the message from?','نام را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["London","Maya","Arman"],"answer_index":1,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_2,'speak',10,'I’m Arman.','I’m را shadow کن.',1,CAST('{"mode":"shadowing","target":"common_contractions","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_2,'speak',11,'در پذیرش نامت را می‌پرسند. معرفی کن.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در پذیرش نامت را می‌پرسند. معرفی کن.","accepted_intents":["My name is Arman.","I’m Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_2,'speak',12,'می‌پرسند Is your name Arman? تایید کن.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"می‌پرسند Is your name Arman? تایید کن.","accepted_intents":["Yes, I’m Arman.","Yes. My name is Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_maya,v_c_arman,'How Are You?','حالت چطور است؟','A simple wellbeing exchange.','یک احوال‌پرسی ساده.','story','london_new_start',3,1,440,3,'validated',JSON_OBJECT('pedagogicalRole','retrieval')); SET v_l_3=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_maya,1,'character','How are you?','حالت چطور است؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_arman,2,'learner','I’m good, thanks.','خوبم، ممنون.',1,'I’m good, thanks.',JSON_ARRAY('I’m good, thanks.','I’m fine, thanks.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_maya,3,'character','Good.','خوبه.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_arman,4,'learner','And you?','تو چطور؟',1,'And you?',JSON_ARRAY('And you?','How about you?'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_maya,5,'character','I’m good, thank you.','خوبم، ممنون.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_arman,6,'learner','Great.','عالی.',1,'Great.',JSON_ARRAY('Great.','Good.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_maya,7,'character','Ready?','آماده‌ای؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_3,v_c_arman,8,'learner','Yes.','بله.',1,'Yes.',JSON_ARRAY('Yes.','Yes, I am.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
    (v_l_3,'listen',1,'How are you?','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_3,'new_word',2,'How are you?','یک تکه یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:how-are-you","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_3,'speak',3,'How are you?','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["How are you?","How’re you?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_3,'reading_comprehension',4,'How are you? → I’m good, thanks.','الگو را بخوان.',1,CAST('{"mode":"micro_grammar","explanation_fa":"How are you? پرسش رایج درباره حال است؛ پاسخ طبیعی کوتاه I’m good, thanks. است.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_3,'meaning_choice',5,'How ___ you?','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["is","are","name"],"answer_index":1,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_3,'speak',6,'بگو خوبی و تشکر کن.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو خوبی و تشکر کن.","accepted":["I’m good, thanks.","I’m fine, thanks."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_3,'reading_comprehension',7,'Maya: Hello, Arman. How are you?','بخوان.',1,CAST('{"mode":"reading_input","text":"Maya: Hello, Arman. How are you?","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_3,'reading_comprehension',8,'What does Maya ask about?','معنی کلی را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["حال آرمان","نام آرمان","خداحافظی"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_3,'speak',9,'How are you?','لحن پرسشی را shadow کن.',1,CAST('{"mode":"stress_rhythm","target":"question_vs_statement_intonation","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_3,'word_order',10,'How are you','مرتب کن.',1,CAST('{"mode":"tap_tokens","tokens":["you","How","are"],"answer":["How","are","you"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_3,'speak',11,'همکارت از حالت می‌پرسد. پاسخ بده.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"همکارت از حالت می‌پرسد. پاسخ بده.","accepted_intents":["I’m good, thanks.","I’m fine, thank you."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_3,'speak',12,'حال طرف مقابل را هم بپرس.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"حال طرف مقابل را هم بپرس.","accepted_intents":["And you?","How about you?"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (v_chapter,v_c_maya,v_c_arman,'See You Soon','به‌زودی می‌بینمت','First-interaction mastery.','جمع‌بندی اولین تعامل.','story','london_new_start',4,1,460,4,'validated',JSON_OBJECT('pedagogicalRole','mastery')); SET v_l_4=LAST_INSERT_ID();
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_maya,1,'character','Hello again!','دوباره سلام!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_arman,2,'learner','Hello!','سلام!',1,'Hello!',JSON_ARRAY('Hello!','Hi!'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_maya,3,'character','What’s your name?','اسمت چیست؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_arman,4,'learner','My name is Arman.','اسم من آرمان است.',1,'My name is Arman.',JSON_ARRAY('My name is Arman.','I’m Arman.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_maya,5,'character','Nice to meet you, Arman.','آرمان، از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_arman,6,'learner','Nice to meet you too.','من هم از آشنایی با تو خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_maya,7,'character','Goodbye for now.','فعلا خداحافظ.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES (v_l_4,v_c_arman,8,'learner','Goodbye!','خداحافظ!',1,'Goodbye!',JSON_ARRAY('Goodbye!','Bye!'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
    (v_l_4,'listen',1,'Hello again!','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_4,'new_word',2,'Goodbye','کاربرد را ببین.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:goodbye:parting","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_4,'speak',3,'Goodbye!','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Goodbye!","Bye!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_4,'speak',4,'بدون متن سلام کن.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بدون متن سلام کن.","accepted":["Hello!","Hi!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_4,'speak',5,'بدون متن نامت را بگو.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بدون متن نامت را بگو.","accepted":["My name is Arman.","I’m Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_4,'meaning_choice',6,'___! See you later.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["Hello","Name","Goodbye"],"answer_index":2,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_4,'reading_comprehension',7,'Hi! My name is Maya. Nice to meet you.','بخوان.',1,CAST('{"mode":"reading_input","text":"Hi! My name is Maya. Nice to meet you.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_4,'reading_comprehension',8,'Which sentence introduces the writer?','جمله معرفی را انتخاب کن.',1,CAST('{"mode":"reading_inference","options":["Nice to meet you.","My name is Maya.","Hi!"],"answer_index":1,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_4,'speak',9,'Hello. Goodbye.','تاکید را shadow کن.',1,CAST('{"mode":"shadowing","target":"basic_word_stress","input":"speech","scored":false}' AS JSON),JSON_OBJECT()),
    (v_l_4,'speak',10,'در کلاس جدید سلام کن و نامت را بگو.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در کلاس جدید سلام کن و نامت را بگو.","accepted_intents":["Hello! My name is Arman.","Hi! I’m Arman."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_4,'speak',11,'فرد تازه‌ای خودش را معرفی می‌کند. پاسخ مناسب بده.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"فرد تازه‌ای خودش را معرفی می‌کند. پاسخ مناسب بده.","accepted_intents":["Nice to meet you.","Nice to meet you too."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
    (v_l_4,'speak',12,'گفت‌وگو تمام شده. خداحافظی کن.','با صدا پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"گفت‌وگو تمام شده. خداحافظی کن.","accepted_intents":["Goodbye!","Bye!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());

    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count) VALUES (v_l_1,v_u_hello,'new',1,4),(v_l_1,v_u_nicemeet,'new',1,3),(v_l_1,v_u_pron,'new',1,2),(v_l_2,v_u_name,'new',1,3),(v_l_2,v_u_myname,'new',1,5),(v_l_2,v_u_nicemeet,'review',1,2),(v_l_3,v_u_howare,'new',1,5),(v_l_3,v_u_hello,'review',1,1),(v_l_4,v_u_goodbye,'new',1,4),(v_l_4,v_u_hello,'mastery',1,2),(v_l_4,v_u_myname,'mastery',1,3),(v_l_4,v_u_nicemeet,'mastery',1,2);
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata) SELECT v_course,u.id,v_chapter,1+x.off,x.off,'due',JSON_OBJECT('originSeries',1) FROM learning_units u CROSS JOIN (SELECT 1 off UNION ALL SELECT 2 UNION ALL SELECT 4 UNION ALL SELECT 8 UNION ALL SELECT 16) x WHERE u.course_id=v_course AND JSON_EXTRACT(u.metadata,'$.series')=1;
  END IF;
  COMMIT;
END$$
DELIMITER ;
CALL nova_en_v3_s001();
DROP PROCEDURE IF EXISTS nova_en_v3_s001;
