-- NOVA v9.1 staging / de-fa / B1 / Batch 01 / Chapter 01 / Series 081
-- Atomic staging unit. Do not publish or advance production_state from this file alone.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET time_zone = '+00:00';
START TRANSACTION;

SET @course_id = (SELECT id FROM courses WHERE course_key='de-fa' LIMIT 1);

INSERT INTO levels (course_id,level_key,cefr_level,title,title_translation,description,description_translation,difficulty_min,difficulty_max,sort_order,status)
VALUES (@course_id,'B1','B1','Gründe, Pläne und Erfahrungen','دلیل ها، برنامه ها و تجربه ها','Zusammenhängender über Gründe, Folgen, Pläne und Erfahrungen sprechen.','درباره دلیل ها، نتیجه ها، برنامه ها و تجربه ها پیوسته تر حرف بزن.',41,60,3,'active')
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),title=VALUES(title),title_translation=VALUES(title_translation),description=VALUES(description),description_translation=VALUES(description_translation),difficulty_min=VALUES(difficulty_min),difficulty_max=VALUES(difficulty_max),status='active';
SET @level_id=LAST_INSERT_ID();

INSERT INTO modules (level_id,module_key,title,title_translation,description,description_translation,planned_chapter_count,difficulty_min,difficulty_max,sort_order,status)
VALUES (@level_id,'B1-M01','Gründe und Folgen','دلیل و نتیجه','Einfache Gründe nennen und Folgen verständlich ausdrücken.','دلیل های ساده را بگو و نتیجه آنها را روشن بیان کن.',5,41,43,1,'active')
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),title=VALUES(title),title_translation=VALUES(title_translation),description=VALUES(description),description_translation=VALUES(description_translation),planned_chapter_count=5,difficulty_min=41,difficulty_max=43,status='active';
SET @module_id=LAST_INSERT_ID();

INSERT INTO content_batches (level_id,batch_number,chapter_order_from,chapter_order_to,series_from,series_to,artifact_name,status)
VALUES (@level_id,1,1,8,81,88,'batch_01_chapters_01_08.sql','generating')
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status=IF(status='published',status,'generating');
SET @batch_id=LAST_INSERT_ID();

INSERT INTO chapters (module_id,batch_id,chapter_key,series_number,global_sort_order,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata)
VALUES (@module_id,@batch_id,'B1-M01-C01',81,81,'Warum komme ich später?','چرا دیرتر می رسم؟','Lena und Ben sprechen über eine Zugverspätung. Ben erklärt einen Grund mit weil und eine Folge mit deshalb.','لنا و بن درباره تاخیر قطار حرف می زنند. بن با weil دلیل و با deshalb نتیجه را بیان می کند.',4,41,42,1,'draft',JSON_OBJECT('staging',true,'batch',1,'atomicChapter',1))
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),batch_id=VALUES(batch_id),title=VALUES(title),title_translation=VALUES(title_translation),description=VALUES(description),description_translation=VALUES(description_translation),planned_lesson_count=4,difficulty_min=41,difficulty_max=42,status='draft',metadata=VALUES(metadata);
SET @chapter_id=LAST_INSERT_ID();

SET @lena_id=(SELECT id FROM characters WHERE course_id=@course_id AND name='Lena' LIMIT 1);
SET @ben_id=(SELECT id FROM characters WHERE course_id=@course_id AND name='Ben' LIMIT 1);

-- New B1 lexical items and explicit phrase targets. Existing canonical words are reused by lemma below.
INSERT INTO words (course_id,word_key,sense_key,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,related_words,introduced_series,explicit_target_count,first_target_series,last_target_series,metadata)
VALUES
(@course_id,'de-fa-b1-081-weil','default','weil','weil','conjunction','چون / زیرا',41,JSON_OBJECT('syntax','subordinate_clause','verbPosition','final'),JSON_ARRAY('deshalb','dann','und'),JSON_ARRAY('deshalb','Grund'),81,1,81,81,JSON_OBJECT('cefr','B1')),
(@course_id,'de-fa-b1-081-puenktlich','default','pünktlich','pünktlich','adjective','سر وقت / به موقع',41,NULL,JSON_ARRAY('später','früh','lang'),JSON_ARRAY('Verspätung','später'),81,1,81,81,JSON_OBJECT('cefr','B1')),
(@course_id,'de-fa-b1-081-deshalb','default','deshalb','deshalb','adverb','برای همین / بنابراین',42,JSON_OBJECT('syntax','main_clause_connector','verbPosition',2),JSON_ARRAY('weil','aber','oder'),JSON_ARRAY('weil','Folge'),81,1,81,81,JSON_OBJECT('cefr','B1')),
(@course_id,'de-fa-b1-081-grund','default','Grund','Grund','noun','دلیل',42,JSON_OBJECT('gender','masculine','plural','Gründe'),JSON_ARRAY('Problem','Frage','Folge'),JSON_ARRAY('weil','Folge'),81,1,81,81,JSON_OBJECT('cefr','B1')),
(@course_id,'de-fa-b1-081-folge','default','Folge','Folge','noun','نتیجه / پیامد',42,JSON_OBJECT('gender','feminine','plural','Folgen'),JSON_ARRAY('Grund','Frage','Termin'),JSON_ARRAY('deshalb','Grund'),81,1,81,81,JSON_OBJECT('cefr','B1')),
(@course_id,'de-fa-b1-081-target-01','target','Ich komme später, weil der Zug Verspätung hat.','Ich komme später, weil der Zug Verspätung hat.','phrase','دیرتر می رسم، چون قطار تاخیر دارد.',41,NULL,JSON_ARRAY('Ich komme später, weil ich Kaffee mache.','Ich komme später, weil ich im Hotel bleibe.'),JSON_ARRAY('weil','Verspätung'),81,1,81,81,JSON_OBJECT('explicitTarget',true)),
(@course_id,'de-fa-b1-081-target-02','target','Ich kann nicht pünktlich sein, weil ich umsteigen muss.','Ich kann nicht pünktlich sein, weil ich umsteigen muss.','phrase','نمی توانم سر وقت برسم، چون باید خط عوض کنم.',41,NULL,JSON_ARRAY('Ich kann pünktlich sein, weil ich arbeite.','Ich muss pünktlich sein, weil ich Kaffee mache.'),JSON_ARRAY('weil','pünktlich','umsteigen'),81,1,81,81,JSON_OBJECT('explicitTarget',true)),
(@course_id,'de-fa-b1-081-target-03','target','Der Zug hat Verspätung. Deshalb komme ich später.','Der Zug hat Verspätung. Deshalb komme ich später.','phrase','قطار تاخیر دارد. برای همین دیرتر می رسم.',42,NULL,JSON_ARRAY('Der Zug hat Verspätung. Deshalb komme ich früher.','Der Zug hat Verspätung. Deshalb bleibe ich im Hotel.'),JSON_ARRAY('deshalb','Verspätung'),81,1,81,81,JSON_OBJECT('explicitTarget',true)),
(@course_id,'de-fa-b1-081-target-04','target','Der Grund ist die Verspätung.','Der Grund ist die Verspätung.','phrase','دلیل، تاخیر قطار است.',42,NULL,JSON_ARRAY('Der Grund ist die Reservierung.','Der Grund ist die Tablette.'),JSON_ARRAY('Grund','Verspätung'),81,1,81,81,JSON_OBJECT('explicitTarget',true)),
(@course_id,'de-fa-b1-081-target-05','target','Die Folge ist: Ich komme später.','Die Folge ist: Ich komme später.','phrase','نتیجه این است: دیرتر می رسم.',42,NULL,JSON_ARRAY('Die Folge ist: Ich komme früher.','Die Folge ist: Ich bleibe im Hotel.'),JSON_ARRAY('Folge','deshalb'),81,1,81,81,JSON_OBJECT('explicitTarget',true))
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),display_form=VALUES(display_form),translation=VALUES(translation),difficulty=VALUES(difficulty),grammar=VALUES(grammar),distractors=VALUES(distractors),related_words=VALUES(related_words),metadata=VALUES(metadata);

-- LESSON 1
INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata)
VALUES (@chapter_id,@lena_id,@ben_id,'B1-M01-C01-L01','Eine Verspätung erklären','توضیح دادن یک تاخیر','Einen einfachen Grund mit weil nennen.','با weil یک دلیل ساده بیان کن.','lena-ben-b1-delay-reasons',1,41,240,1,'validated',JSON_OBJECT('staging',true))
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='validated',content_version=content_version+1;
SET @l1=LAST_INSERT_ID();
INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens,grammar_title,grammar_note,grammar_data) VALUES
(@l1,@lena_id,'B1-081-L01-T01',1,'character','Hallo Ben. Wo bist du?','سلام بن. کجایی؟',41,NULL,JSON_ARRAY(JSON_OBJECT('s','Hallo','l','Hallo'),JSON_OBJECT('s','Ben','l','Ben'),JSON_OBJECT('s','Wo','l','wo'),JSON_OBJECT('s','bist','l','sein'),JSON_OBJECT('s','du','l','du')),NULL,NULL,NULL),
(@l1,@ben_id,'B1-081-L01-T02',2,'learner','Ich bin noch im Zug.','هنوز داخل قطارم.',41,'Ich bin noch im Zug.',JSON_ARRAY(JSON_OBJECT('s','Ich','l','ich'),JSON_OBJECT('s','bin','l','sein'),JSON_OBJECT('s','noch','l','noch'),JSON_OBJECT('s','im','l','in'),JSON_OBJECT('s','Zug','l','Zug')),NULL,NULL,NULL),
(@l1,@lena_id,'B1-081-L01-T03',3,'character','Hat der Zug Verspätung?','قطار تاخیر دارد؟',41,NULL,JSON_ARRAY(JSON_OBJECT('s','Hat','l','haben'),JSON_OBJECT('s','der','l','der'),JSON_OBJECT('s','Zug','l','Zug'),JSON_OBJECT('s','Verspätung','l','Verspätung')),NULL,NULL,NULL),
(@l1,@ben_id,'B1-081-L01-T04',4,'learner','Ja. Ich komme später, weil der Zug Verspätung hat.','بله. دیرتر می رسم، چون قطار تاخیر دارد.',41,'Ich komme später, weil der Zug Verspätung hat.',JSON_ARRAY(JSON_OBJECT('s','Ja','l','ja'),JSON_OBJECT('s','Ich','l','ich'),JSON_OBJECT('s','komme','l','kommen'),JSON_OBJECT('s','später','l','später'),JSON_OBJECT('s','weil','l','weil'),JSON_OBJECT('s','der','l','der'),JSON_OBJECT('s','Zug','l','Zug'),JSON_OBJECT('s','Verspätung','l','Verspätung'),JSON_OBJECT('s','hat','l','haben')),'weil + Nebensatz','Nach weil steht das konjugierte Verb am Ende.','{"connector":"weil","verbPosition":"final"}'),
(@l1,@lena_id,'B1-081-L01-T05',5,'character','Kein Problem. Sag mir bitte Bescheid.','مشکلی نیست. لطفا بهم خبر بده.',41,NULL,JSON_ARRAY(JSON_OBJECT('s','Kein','l','kein'),JSON_OBJECT('s','Problem','l','Problem'),JSON_OBJECT('s','Sag','l','sagen'),JSON_OBJECT('s','mir','l','ich'),JSON_OBJECT('s','bitte','l','bitte'),JSON_OBJECT('s','Bescheid','l','Bescheid')),NULL,NULL,NULL),
(@l1,@ben_id,'B1-081-L01-T06',6,'learner','Ja, ich sage dir Bescheid.','بله، بهت خبر می دهم.',41,'Ja, ich sage dir Bescheid.',JSON_ARRAY(JSON_OBJECT('s','Ja','l','ja'),JSON_OBJECT('s','ich','l','ich'),JSON_OBJECT('s','sage','l','sagen'),JSON_OBJECT('s','dir','l','du'),JSON_OBJECT('s','Bescheid','l','Bescheid')),NULL,NULL,NULL);

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count)
SELECT @l1,id,ROW_NUMBER() OVER (ORDER BY id),'review',0,1 FROM words WHERE course_id=@course_id AND lemma IN ('Hallo','Ben','wo','sein','du','ich','noch','in','Zug','haben','der','Verspätung','ja','kommen','später','kein','Problem','sagen','bitte','Bescheid')
ON DUPLICATE KEY UPDATE exposure_count=VALUES(exposure_count);
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l1,id,100,'new',1,3 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-weil' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=3;
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l1,id,101,'new',1,2 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-01' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=2;
SET @l1t1=(SELECT id FROM turns WHERE lesson_id=@l1 AND sort_order=1); SET @l1t4=(SELECT id FROM turns WHERE lesson_id=@l1 AND sort_order=4); SET @weil=(SELECT id FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-weil');
INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l1,'B1-081-L01-A01','listen',1,@l1t1,NULL,NULL,NULL,'Hör zu.','گوش کن.',41,NULL),
(@l1,'B1-081-L01-A02','new_word',2,NULL,@weil,'weil','چون / زیرا','Lerne das neue Verbindungswort.','کلمه ربط جدید را یاد بگیر.',41,JSON_OBJECT('example','Ich komme später, weil der Zug Verspätung hat.')),
(@l1,'B1-081-L01-A03','speak',3,@l1t4,NULL,NULL,NULL,'Sprich den Satz.','جمله را با صدای بلند بگو.',41,NULL),
(@l1,'B1-081-L01-A04','word_order',4,@l1t4,NULL,'Ich komme später, weil der Zug Verspätung hat.','دیرتر می رسم، چون قطار تاخیر دارد.','Ordne die Wörter.','کلمه ها را مرتب کن.',41,JSON_OBJECT('tokens',JSON_ARRAY('Ich','komme','später','weil','der','Zug','Verspätung','hat'))),
(@l1,'B1-081-L01-A05','reading_comprehension',5,NULL,NULL,'Warum kommt Ben später?','چرا بن دیرتر می رسد؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',41,JSON_OBJECT('answer','Weil der Zug Verspätung hat.','distractors',JSON_ARRAY('Weil er im Büro arbeitet.','Weil er Kaffee macht.')));

-- LESSON 2
INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata)
VALUES (@chapter_id,@lena_id,@ben_id,'B1-M01-C01-L02','Nicht pünktlich','سر وقت نمی رسم','Mit weil einen zweiten Grund erklären und pünktlich verwenden.','یک دلیل دیگر را با weil توضیح بده و pünktlich را استفاده کن.','lena-ben-b1-delay-reasons',2,41,240,2,'validated',JSON_OBJECT('staging',true))
ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='validated',content_version=content_version+1;
SET @l2=LAST_INSERT_ID();
INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens) VALUES
(@l2,@lena_id,'B1-081-L02-T01',1,'character','Kommst du pünktlich an?','سر وقت می رسی؟',41,NULL,JSON_ARRAY(JSON_OBJECT('s','Kommst','l','ankommen'),JSON_OBJECT('s','du','l','du'),JSON_OBJECT('s','pünktlich','l','pünktlich'),JSON_OBJECT('s','an','l','ankommen'))),
(@l2,@ben_id,'B1-081-L02-T02',2,'learner','Nein, nicht pünktlich.','نه، سر وقت نمی رسم.',41,'Nein, nicht pünktlich.',JSON_ARRAY(JSON_OBJECT('s','Nein','l','nein'),JSON_OBJECT('s','nicht','l','nicht'),JSON_OBJECT('s','pünktlich','l','pünktlich'))),
(@l2,@lena_id,'B1-081-L02-T03',3,'character','Warum nicht?','چرا نه؟',41,NULL,JSON_ARRAY(JSON_OBJECT('s','Warum','l','warum'),JSON_OBJECT('s','nicht','l','nicht'))),
(@l2,@ben_id,'B1-081-L02-T04',4,'learner','Ich kann nicht pünktlich sein, weil ich umsteigen muss.','نمی توانم سر وقت برسم، چون باید خط عوض کنم.',41,'Ich kann nicht pünktlich sein, weil ich umsteigen muss.',JSON_ARRAY(JSON_OBJECT('s','Ich','l','ich'),JSON_OBJECT('s','kann','l','können'),JSON_OBJECT('s','nicht','l','nicht'),JSON_OBJECT('s','pünktlich','l','pünktlich'),JSON_OBJECT('s','sein','l','sein'),JSON_OBJECT('s','weil','l','weil'),JSON_OBJECT('s','ich','l','ich'),JSON_OBJECT('s','umsteigen','l','umsteigen'),JSON_OBJECT('s','muss','l','müssen'))),
(@l2,@lena_id,'B1-081-L02-T05',5,'character','Dann warte ich.','پس منتظر می مانم.',41,NULL,JSON_ARRAY(JSON_OBJECT('s','Dann','l','dann'),JSON_OBJECT('s','warte','l','warten'),JSON_OBJECT('s','ich','l','ich'))),
(@l2,@ben_id,'B1-081-L02-T06',6,'learner','Danke. Ich rufe dich später an.','ممنون. بعدا بهت زنگ می زنم.',41,'Danke. Ich rufe dich später an.',JSON_ARRAY(JSON_OBJECT('s','Danke','l','danke'),JSON_OBJECT('s','Ich','l','ich'),JSON_OBJECT('s','rufe','l','anrufen'),JSON_OBJECT('s','dich','l','du'),JSON_OBJECT('s','später','l','später'),JSON_OBJECT('s','an','l','anrufen')));
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l2,id,ROW_NUMBER() OVER (ORDER BY id),'review',0,1 FROM words WHERE course_id=@course_id AND lemma IN ('ankommen','du','nein','nicht','warum','ich','können','sein','umsteigen','müssen','dann','warten','danke','anrufen','später','weil') ON DUPLICATE KEY UPDATE exposure_count=VALUES(exposure_count);
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l2,id,100,'new',1,4 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-puenktlich' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=4;
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l2,id,101,'new',1,2 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-02' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=2;
SET @l2t1=(SELECT id FROM turns WHERE lesson_id=@l2 AND sort_order=1); SET @l2t4=(SELECT id FROM turns WHERE lesson_id=@l2 AND sort_order=4); SET @puenktlich=(SELECT id FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-puenktlich');
INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l2,'B1-081-L02-A01','listen',1,@l2t1,NULL,NULL,NULL,'Hör zu.','گوش کن.',41,NULL),(@l2,'B1-081-L02-A02','new_word',2,NULL,@puenktlich,'pünktlich','سر وقت / به موقع','Lerne das neue Wort.','کلمه جدید را یاد بگیر.',41,NULL),(@l2,'B1-081-L02-A03','speak',3,@l2t4,NULL,NULL,NULL,'Sprich den Satz.','جمله را با صدای بلند بگو.',41,NULL),(@l2,'B1-081-L02-A04','word_order',4,@l2t4,NULL,'Ich kann nicht pünktlich sein, weil ich umsteigen muss.','نمی توانم سر وقت برسم، چون باید خط عوض کنم.','Ordne die Wörter.','کلمه ها را مرتب کن.',41,JSON_OBJECT('tokens',JSON_ARRAY('Ich','kann','nicht','pünktlich','sein','weil','ich','umsteigen','muss'))),(@l2,'B1-081-L02-A05','reading_comprehension',5,NULL,NULL,'Warum ist Ben nicht pünktlich?','چرا بن سر وقت نمی رسد؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',41,JSON_OBJECT('answer','Weil er umsteigen muss.','distractors',JSON_ARRAY('Weil er auschecken möchte.','Weil er krank ist.')));

-- LESSON 3
INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata)
VALUES (@chapter_id,@lena_id,@ben_id,'B1-M01-C01-L03','Deshalb komme ich später','برای همین دیرتر می رسم','Eine Folge mit deshalb ausdrücken.','با deshalb نتیجه یک اتفاق را بیان کن.','lena-ben-b1-delay-reasons',3,42,240,3,'validated',JSON_OBJECT('staging',true)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='validated',content_version=content_version+1;
SET @l3=LAST_INSERT_ID();
INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens,grammar_title,grammar_note,grammar_data) VALUES
(@l3,@lena_id,'B1-081-L03-T01',1,'character','Hat der Zug noch Verspätung?','قطار هنوز تاخیر دارد؟',42,NULL,JSON_ARRAY(JSON_OBJECT('s','Hat','l','haben'),JSON_OBJECT('s','der','l','der'),JSON_OBJECT('s','Zug','l','Zug'),JSON_OBJECT('s','noch','l','noch'),JSON_OBJECT('s','Verspätung','l','Verspätung')),NULL,NULL,NULL),
(@l3,@ben_id,'B1-081-L03-T02',2,'learner','Ja, der Zug hat Verspätung.','بله، قطار تاخیر دارد.',42,'Ja, der Zug hat Verspätung.',JSON_ARRAY(JSON_OBJECT('s','Ja','l','ja'),JSON_OBJECT('s','der','l','der'),JSON_OBJECT('s','Zug','l','Zug'),JSON_OBJECT('s','hat','l','haben'),JSON_OBJECT('s','Verspätung','l','Verspätung')),NULL,NULL,NULL),
(@l3,@lena_id,'B1-081-L03-T03',3,'character','Dann kommst du später.','پس دیرتر می رسی.',42,NULL,JSON_ARRAY(JSON_OBJECT('s','Dann','l','dann'),JSON_OBJECT('s','kommst','l','kommen'),JSON_OBJECT('s','du','l','du'),JSON_OBJECT('s','später','l','später')),NULL,NULL,NULL),
(@l3,@ben_id,'B1-081-L03-T04',4,'learner','Der Zug hat Verspätung. Deshalb komme ich später.','قطار تاخیر دارد. برای همین دیرتر می رسم.',42,'Der Zug hat Verspätung. Deshalb komme ich später.',JSON_ARRAY(JSON_OBJECT('s','Der','l','der'),JSON_OBJECT('s','Zug','l','Zug'),JSON_OBJECT('s','hat','l','haben'),JSON_OBJECT('s','Verspätung','l','Verspätung'),JSON_OBJECT('s','Deshalb','l','deshalb'),JSON_OBJECT('s','komme','l','kommen'),JSON_OBJECT('s','ich','l','ich'),JSON_OBJECT('s','später','l','später')),'deshalb + Hauptsatz','Nach deshalb steht das konjugierte Verb an Position 2.','{"connector":"deshalb","verbPosition":2}'),
(@l3,@lena_id,'B1-081-L03-T05',5,'character','Wir sprechen später.','بعدا صحبت می کنیم.',42,NULL,JSON_ARRAY(JSON_OBJECT('s','Wir','l','wir'),JSON_OBJECT('s','sprechen','l','sprechen'),JSON_OBJECT('s','später','l','später')),NULL,NULL,NULL),
(@l3,@ben_id,'B1-081-L03-T06',6,'learner','Ja. Dann sprechen wir später.','بله. پس بعدا صحبت می کنیم.',42,'Ja. Dann sprechen wir später.',JSON_ARRAY(JSON_OBJECT('s','Ja','l','ja'),JSON_OBJECT('s','Dann','l','dann'),JSON_OBJECT('s','sprechen','l','sprechen'),JSON_OBJECT('s','wir','l','wir'),JSON_OBJECT('s','später','l','später')),NULL,NULL,NULL);
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l3,id,ROW_NUMBER() OVER (ORDER BY id),'review',0,1 FROM words WHERE course_id=@course_id AND lemma IN ('haben','der','Zug','noch','Verspätung','ja','dann','kommen','du','später','ich','wir','sprechen') ON DUPLICATE KEY UPDATE exposure_count=VALUES(exposure_count);
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l3,id,100,'new',1,3 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-deshalb' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=3;
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l3,id,101,'new',1,2 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-03' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=2;
SET @l3t1=(SELECT id FROM turns WHERE lesson_id=@l3 AND sort_order=1); SET @l3t4=(SELECT id FROM turns WHERE lesson_id=@l3 AND sort_order=4); SET @deshalb=(SELECT id FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-deshalb');
INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l3,'B1-081-L03-A01','listen',1,@l3t1,NULL,NULL,NULL,'Hör zu.','گوش کن.',42,NULL),(@l3,'B1-081-L03-A02','new_word',2,NULL,@deshalb,'deshalb','برای همین / بنابراین','Lerne das neue Verbindungswort.','کلمه ربط جدید را یاد بگیر.',42,NULL),(@l3,'B1-081-L03-A03','speak',3,@l3t4,NULL,NULL,NULL,'Sprich den Satz.','جمله را با صدای بلند بگو.',42,NULL),(@l3,'B1-081-L03-A04','meaning_choice',4,NULL,@deshalb,'Was bedeutet deshalb hier?','deshalb اینجا چه معنی می دهد؟','Wähle die passende Bedeutung.','معنی مناسب را انتخاب کن.',42,JSON_OBJECT('answer','برای همین','distractors',JSON_ARRAY('چون','بعدا'))),(@l3,'B1-081-L03-A05','reading_comprehension',5,NULL,NULL,'Was ist die Folge der Verspätung?','نتیجه تاخیر چیست؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',42,JSON_OBJECT('answer','Ben kommt später.','distractors',JSON_ARRAY('Ben bleibt im Hotel.','Ben kauft eine Fahrkarte.')));

-- LESSON 4
INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata)
VALUES (@chapter_id,@lena_id,@ben_id,'B1-M01-C01-L04','Grund und Folge','دلیل و نتیجه','Grund und Folge unterscheiden und kurz ausdrücken.','دلیل و نتیجه را از هم تشخیص بده و کوتاه بیان کن.','lena-ben-b1-delay-reasons',4,42,240,4,'validated',JSON_OBJECT('staging',true)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='validated',content_version=content_version+1;
SET @l4=LAST_INSERT_ID();
INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens) VALUES
(@l4,@lena_id,'B1-081-L04-T01',1,'character','Was ist der Grund?','دلیل چیست؟',42,NULL,JSON_ARRAY(JSON_OBJECT('s','Was','l','was'),JSON_OBJECT('s','ist','l','sein'),JSON_OBJECT('s','der','l','der'),JSON_OBJECT('s','Grund','l','Grund'))),
(@l4,@ben_id,'B1-081-L04-T02',2,'learner','Der Grund ist die Verspätung.','دلیل، تاخیر قطار است.',42,'Der Grund ist die Verspätung.',JSON_ARRAY(JSON_OBJECT('s','Der','l','der'),JSON_OBJECT('s','Grund','l','Grund'),JSON_OBJECT('s','ist','l','sein'),JSON_OBJECT('s','die','l','der'),JSON_OBJECT('s','Verspätung','l','Verspätung'))),
(@l4,@lena_id,'B1-081-L04-T03',3,'character','Und was ist die Folge?','و نتیجه چیست؟',42,NULL,JSON_ARRAY(JSON_OBJECT('s','Und','l','und'),JSON_OBJECT('s','was','l','was'),JSON_OBJECT('s','ist','l','sein'),JSON_OBJECT('s','die','l','der'),JSON_OBJECT('s','Folge','l','Folge'))),
(@l4,@ben_id,'B1-081-L04-T04',4,'learner','Die Folge ist: Ich komme später.','نتیجه این است: دیرتر می رسم.',42,'Die Folge ist: Ich komme später.',JSON_ARRAY(JSON_OBJECT('s','Die','l','der'),JSON_OBJECT('s','Folge','l','Folge'),JSON_OBJECT('s','ist','l','sein'),JSON_OBJECT('s','Ich','l','ich'),JSON_OBJECT('s','komme','l','kommen'),JSON_OBJECT('s','später','l','später'))),
(@l4,@lena_id,'B1-081-L04-T05',5,'character','Verstehst du das?','متوجه می شوی؟',42,NULL,JSON_ARRAY(JSON_OBJECT('s','Verstehst','l','verstehen'),JSON_OBJECT('s','du','l','du'),JSON_OBJECT('s','das','l','das'))),
(@l4,@ben_id,'B1-081-L04-T06',6,'learner','Ja, ich verstehe das.','بله، متوجه می شوم.',42,'Ja, ich verstehe das.',JSON_ARRAY(JSON_OBJECT('s','Ja','l','ja'),JSON_OBJECT('s','ich','l','ich'),JSON_OBJECT('s','verstehe','l','verstehen'),JSON_OBJECT('s','das','l','das')));
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l4,id,ROW_NUMBER() OVER (ORDER BY id),'review',0,1 FROM words WHERE course_id=@course_id AND lemma IN ('was','sein','der','Verspätung','und','ich','kommen','später','verstehen','du','das','ja') ON DUPLICATE KEY UPDATE exposure_count=VALUES(exposure_count);
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l4,id,100,'new',1,3 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-grund' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=3;
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l4,id,101,'new',1,3 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-folge' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=3;
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l4,id,102,'new',1,2 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-04' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=2;
INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l4,id,103,'new',1,2 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-05' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=2;
SET @l4t1=(SELECT id FROM turns WHERE lesson_id=@l4 AND sort_order=1); SET @l4t2=(SELECT id FROM turns WHERE lesson_id=@l4 AND sort_order=2); SET @l4t4=(SELECT id FROM turns WHERE lesson_id=@l4 AND sort_order=4); SET @grund=(SELECT id FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-grund'); SET @folge=(SELECT id FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-folge');
INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l4,'B1-081-L04-A01','listen',1,@l4t1,NULL,NULL,NULL,'Hör zu.','گوش کن.',42,NULL),(@l4,'B1-081-L04-A02','new_word',2,NULL,@grund,'Grund','دلیل','Lerne das neue Wort.','کلمه جدید را یاد بگیر.',42,NULL),(@l4,'B1-081-L04-A03','new_word',3,NULL,@folge,'Folge','نتیجه / پیامد','Lerne das neue Wort.','کلمه جدید را یاد بگیر.',42,NULL),(@l4,'B1-081-L04-A04','speak',4,@l4t2,NULL,NULL,NULL,'Sprich den Grund.','دلیل را با صدای بلند بگو.',42,NULL),(@l4,'B1-081-L04-A05','speak',5,@l4t4,NULL,NULL,NULL,'Sprich die Folge.','نتیجه را با صدای بلند بگو.',42,NULL),(@l4,'B1-081-L04-A06','reading_comprehension',6,NULL,NULL,'Was ist der Grund?','دلیل چیست؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',42,JSON_OBJECT('answer','Die Verspätung.','distractors',JSON_ARRAY('Die Reservierung.','Die Tabletten.')));

-- Atomic chapter guardrails. Any failed assertion aborts the transaction by division by zero.
SET @lesson_count=(SELECT COUNT(*) FROM lessons WHERE chapter_id=@chapter_id);
SET @turn_count=(SELECT COUNT(*) FROM turns WHERE lesson_id IN (@l1,@l2,@l3,@l4));
SET @learner_turns=(SELECT COUNT(*) FROM turns WHERE lesson_id IN (@l1,@l2,@l3,@l4) AND role='learner');
SET @learner_targets=(SELECT COUNT(*) FROM turns WHERE lesson_id IN (@l1,@l2,@l3,@l4) AND role='learner' AND speech_target IS NOT NULL AND CHAR_LENGTH(TRIM(speech_target))>0);
SET @reading_count=(SELECT COUNT(*) FROM activities WHERE lesson_id IN (@l1,@l2,@l3,@l4) AND activity_type='reading_comprehension');
SET @character_pair_count=(SELECT COUNT(*) FROM lessons WHERE chapter_id=@chapter_id AND prompt_character_id=@lena_id AND learner_character_id=@ben_id AND prompt_character_id<>learner_character_id);
SELECT IF(@course_id IS NULL OR @lena_id IS NULL OR @ben_id IS NULL,1/0,1) AS dependency_guard;
SELECT IF(@lesson_count<>4 OR @turn_count<>24 OR @learner_turns<>12 OR @learner_targets<>12 OR @reading_count<>4 OR @character_pair_count<>4,1/0,1) AS chapter_guard;

COMMIT;
