-- NOVA v9.1.1 / de-fa / B1 / Batch 01 / Chapter 01 / Series 081

-- Regenerated from scratch. The quarantined v9.1.0 staging content is deleted and not reused.

-- Atomic staging unit. Do not publish or advance production_state from this file alone.

SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

SET time_zone = '+00:00';

START TRANSACTION;

SET @course_id=(SELECT id FROM courses WHERE course_key='de-fa' LIMIT 1);

INSERT INTO levels (course_id,level_key,cefr_level,title,title_translation,description,description_translation,difficulty_min,difficulty_max,sort_order,status) VALUES (@course_id,'de-fa-b1','B1','Selbstständiger im Alltag','مستقل تر در زندگی روزمره','Selbstständig entscheiden, begründen und handeln.','تصمیم گرفتن، دلیل آوردن و عمل کردن به شکل مستقل.',41,60,3,'active') ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),title=VALUES(title),title_translation=VALUES(title_translation),difficulty_min=VALUES(difficulty_min),difficulty_max=VALUES(difficulty_max),status='active';

SET @level_id=LAST_INSERT_ID();

INSERT INTO modules (level_id,module_key,title,title_translation,description,description_translation,planned_chapter_count,difficulty_min,difficulty_max,sort_order,status) VALUES (@level_id,'de-fa-b1-m01','Entscheidungen & Gründe','تصمیم ها و دلیل ها','Mia wägt eine wichtige Entscheidung ab.','میا یک تصمیم مهم را سبک سنگین می کند.',5,41,43,1,'active') ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),title=VALUES(title),title_translation=VALUES(title_translation),status='active';

SET @module_id=LAST_INSERT_ID();

INSERT INTO content_batches (level_id,batch_number,chapter_order_from,chapter_order_to,series_from,series_to,artifact_name,status) VALUES (@level_id,1,1,8,81,88,'batch_01_chapters_01_08.sql','generating') ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),status='generating';

SET @batch_id=LAST_INSERT_ID();

INSERT INTO chapters (module_id,batch_id,chapter_key,series_number,global_sort_order,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (@module_id,@batch_id,'de-fa-b1-c01',81,1,'Ich muss mich entscheiden','باید تصمیم بگیرم','Mia erzählt Sara von einem Jobangebot und plant, ihre Gründe geordnet abzuwägen.','میا درباره یک پیشنهاد شغلی با سارا حرف می زند و تصمیم می گیرد دلیل هایش را منظم بررسی کند.',4,41,42,1,'validated',JSON_OBJECT('databaseRevision','v9.1.1','staging',TRUE,'regeneratedFromScratch',TRUE)) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id),title=VALUES(title),title_translation=VALUES(title_translation),description=VALUES(description),description_translation=VALUES(description_translation),status='validated',metadata=VALUES(metadata);

SET @chapter_id=LAST_INSERT_ID();

SET @mia_id=(SELECT id FROM characters WHERE course_id=@course_id AND name='Mia' LIMIT 1);

SET @sara_id=(SELECT id FROM characters WHERE course_id=@course_id AND name='Sara' LIMIT 1);

-- Remove any prior Series 081 staging rows before the v9.1.1 regeneration.

DELETE FROM lessons WHERE chapter_id=@chapter_id;

DELETE FROM words WHERE course_id=@course_id AND word_key LIKE 'de-fa-b1-081-%';

-- New lexical tuples and four unique explicit targets.

INSERT INTO words (course_id,word_key,sense_key,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,related_words,introduced_series,explicit_target_count,first_target_series,last_target_series,metadata) VALUES

(@course_id,'de-fa-b1-081-word-01','default','still','still','adjective','ساکت',41,NULL,JSON_ARRAY('پرسروصدا','بی قرار'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-02','default','los','los','adjective','پیش آمده / در جریان',42,NULL,JSON_ARRAY('تمام شده','آماده'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-03','default','sich entscheiden','sich entscheiden','verb','تصمیم گرفتن',41,NULL,JSON_ARRAY('منصرف شدن','صبر کردن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-04','default','worum','worum','pronoun','درباره چه چیزی',42,NULL,JSON_ARRAY('کجا','چه وقت'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-05','default','Jobangebot','Jobangebot','noun','پیشنهاد شغلی',41,NULL,JSON_ARRAY('پیشنهاد سفر','قرار پزشک'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-06','default','Leipzig','Leipzig','proper_noun','لایپزیگ',42,NULL,JSON_ARRAY('برلین','هامبورگ'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-07','default','bekommen','bekommen','verb','گرفتن / دریافت کردن',41,NULL,JSON_ARRAY('فرستادن','پس دادن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-08','default','klingen','klingen','verb','به نظر رسیدن',42,NULL,JSON_ARRAY('نوشتن','خریدن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-09','default','interessant','interessant','adjective','جالب',41,NULL,JSON_ARRAY('خسته کننده','بی اهمیت'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-10','default','sich freuen','sich freuen','verb','خوشحال بودن',42,NULL,JSON_ARRAY('نگران بودن','عصبانی بودن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-11','default','aber','aber','conjunction','اما / ولی',41,NULL,JSON_ARRAY('و','چون'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-12','default','auch','auch','adverb','هم / همچنین',42,NULL,JSON_ARRAY('فقط','هرگز'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-13','default','unsicher','unsicher','adjective','مردد / بدون اطمینان',41,NULL,JSON_ARRAY('با اطمینان','آماده'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-14','default','weil','weil','conjunction','چون / زیرا',42,NULL,JSON_ARRAY('بنابراین','اما'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-15','default','Stelle','Stelle','noun','موقعیت شغلی',41,NULL,JSON_ARRAY('تعطیلات','بلیت'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-16','default','weit','weit','adjective','دور',42,NULL,JSON_ARRAY('نزدیک','کوتاه'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-17','default','weg','weg','adverb','دور / آن طرف',41,NULL,JSON_ARRAY('اینجا','نزدیک'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-18','default','denn','denn','particle','پس / آخر',42,NULL,JSON_ARRAY('یا','با این حال'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-19','default','umziehen','umziehen','verb','اسباب کشی کردن',41,NULL,JSON_ARRAY('ماندن','برگشتن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-20','default','wissen','wissen','verb','دانستن',42,NULL,JSON_ARRAY('حدس زدن','فراموش کردن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-21','default','für','für','preposition','برای / به نفع',41,NULL,JSON_ARRAY('بدون','علیه'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-22','default','lernen','lernen','verb','یاد گرفتن',42,NULL,JSON_ARRAY('فراموش کردن','استراحت کردن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-23','default','verdienen','verdienen','verb','درآمد داشتن',41,NULL,JSON_ARRAY('خرج کردن','قرض گرفتن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-24','default','bei','bei','preposition','در / هنگام',42,NULL,JSON_ARRAY('بدون','دور از'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-25','default','Entscheidung','Entscheidung','noun','تصمیم',41,NULL,JSON_ARRAY('پرسش','پاسخ'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-26','default','wichtig','wichtig','adjective','مهم',42,NULL,JSON_ARRAY('بی اهمیت','ساده'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-27','default','Nähe','Nähe','noun','نزدیکی',41,NULL,JSON_ARRAY('دوری','بیرون'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-28','default','Freund','Freund','noun','دوست',42,NULL,JSON_ARRAY('غریبه','مدیر'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-29','default','neu','neu','adjective','جدید / تازه',41,NULL,JSON_ARRAY('قدیمی','قبلی'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-30','default','Arbeit','Arbeit','noun','کار',42,NULL,JSON_ARRAY('تعطیلات','استراحت'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-31','default','gefallen','gefallen','verb','خوش آمدن',41,NULL,JSON_ARRAY('ناراحت کردن','فراموش کردن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-32','default','Verantwortung','Verantwortung','noun','مسوولیت',42,NULL,JSON_ARRAY('تفریح','تصادف'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-33','default','beide','beide','pronoun','هر دو',41,NULL,JSON_ARRAY('هیچ کدام','فقط یکی'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-34','default','genau','genau','adverb','دقیقا',42,NULL,JSON_ARRAY('تقریبا','اشتباه'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-35','default','deshalb','deshalb','adverb','برای همین / بنابراین',41,NULL,JSON_ARRAY('با این حال','چون'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-36','default','wollen','wollen','verb','خواستن',42,NULL,JSON_ARRAY('توانستن','مجبور بودن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-37','default','aufschreiben','aufschreiben','verb','یادداشت کردن',41,NULL,JSON_ARRAY('پاک کردن','خواندن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-38','default','alle','alle','determiner','همه',42,NULL,JSON_ARRAY('بعضی','هیچ'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-39','default','Vorteil','Vorteil','noun','مزیت',41,NULL,JSON_ARRAY('عیب','مشکل'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-40','default','Nachteil','Nachteil','noun','عیب / نکته منفی',42,NULL,JSON_ARRAY('مزیت','فرصت'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-41','default','Idee','Idee','noun','ایده',41,NULL,JSON_ARRAY('مشکل','زمان'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-42','default','Ruhe','Ruhe','noun','آرامش',42,NULL,JSON_ARRAY('سروصدا','عجله'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-43','default','darüber','darüber','adverb','درباره آن',41,NULL,JSON_ARRAY('زیر آن','از آنجا'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-44','default','nachdenken','nachdenken','verb','فکر کردن',42,NULL,JSON_ARRAY('فراموش کردن','بی توجه بودن'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-word-45','default','dass','dass','conjunction','که',41,NULL,JSON_ARRAY('اگر','چون'),NULL,81,0,NULL,NULL,JSON_OBJECT('explicitTarget',FALSE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-target-01','default','Ich muss mich entscheiden.','Ich muss mich entscheiden.','phrase','باید تصمیم بگیرم.',41,NULL,JSON_ARRAY('Ich muss heute arbeiten.','Ich habe mich schon entschieden.'),NULL,81,1,81,81,JSON_OBJECT('explicitTarget',TRUE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-target-02','default','Ich könnte dort mehr lernen und mehr verdienen.','Ich könnte dort mehr lernen und mehr verdienen.','phrase','می توانم آنجا بیشتر یاد بگیرم و درآمد بیشتری داشته باشم.',41,NULL,JSON_ARRAY('Ich könnte dort weniger lernen.','Ich möchte dort nur Urlaub machen.'),NULL,81,1,81,81,JSON_OBJECT('explicitTarget',TRUE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-target-03','default','Ich möchte in der Nähe meiner Freunde bleiben.','Ich möchte in der Nähe meiner Freunde bleiben.','phrase','می خواهم نزدیک دوستانم بمانم.',42,NULL,JSON_ARRAY('Ich möchte weit von meinen Freunden wohnen.','Ich möchte die Stelle sofort ablehnen.'),NULL,81,1,81,81,JSON_OBJECT('explicitTarget',TRUE,'databaseRevision','v9.1.1')),
(@course_id,'de-fa-b1-081-target-04','default','Ich schreibe zuerst alle Vorteile und Nachteile auf.','Ich schreibe zuerst alle Vorteile und Nachteile auf.','phrase','اول همه مزایا و معایب را یادداشت می کنم.',42,NULL,JSON_ARRAY('Ich schreibe nur die Vorteile auf.','Ich entscheide mich ohne eine Liste.'),NULL,81,1,81,81,JSON_OBJECT('explicitTarget',TRUE,'databaseRevision','v9.1.1'));

-- LESSON 1

INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (@chapter_id,@sara_id,@mia_id,'B1-M01-C01-L01','Eine wichtige Entscheidung','یک تصمیم مهم','Über eine anstehende Entscheidung sprechen und sich entscheiden verwenden.','درباره یک تصمیم پیش رو حرف بزن و از sich entscheiden استفاده کن.','mia-sara-b1-decisions',1,41,300,1,'validated',JSON_OBJECT('staging',TRUE,'databaseRevision','v9.1.1'));

SET @l1=LAST_INSERT_ID();

INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens,grammar_title,grammar_note,grammar_data) VALUES
(@l1,@sara_id,'B1-081-L01-T01',1,'character','Du bist heute so still. Was ist los?','امروز خیلی ساکتی. چی شده؟',41,NULL,JSON_ARRAY(JSON_OBJECT('surface','Du','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','bist','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','heute','lemma','heute','translation','امروز','partOfSpeech','adverb'),JSON_OBJECT('surface','so','lemma','so','translation','این طور / آن طور','partOfSpeech','adverb'),JSON_OBJECT('surface','still','lemma','still','translation','ساکت','partOfSpeech','adjective','suffix','.'),JSON_OBJECT('surface','Was','lemma','was','translation','چی / چه','partOfSpeech','pronoun'),JSON_OBJECT('surface','ist','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','los','lemma','los','translation','پیش آمده / در جریان','partOfSpeech','adjective','suffix','?')),NULL,NULL,NULL),
(@l1,@mia_id,'B1-081-L01-T02',2,'learner','Ich muss mich entscheiden.','باید تصمیم بگیرم.',41,'Ich muss mich entscheiden.',JSON_ARRAY(JSON_OBJECT('surface','Ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','muss','lemma','müssen','translation','مجبور بودن / باید','partOfSpeech','verb'),JSON_OBJECT('surface','mich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','entscheiden','lemma','sich entscheiden','translation','تصمیم گرفتن','partOfSpeech','verb','suffix','.')),'sich entscheiden','Das reflexive Verb steht hier mit einem Reflexivpronomen.',JSON_OBJECT('focus','reflexive_verb')),
(@l1,@sara_id,'B1-081-L01-T03',3,'character','Worum geht es?','موضوع چیه؟',41,NULL,JSON_ARRAY(JSON_OBJECT('surface','Worum','lemma','worum','translation','درباره چه چیزی','partOfSpeech','pronoun'),JSON_OBJECT('surface','geht','lemma','gehen','translation','رفتن','partOfSpeech','verb'),JSON_OBJECT('surface','es','lemma','es','translation','آن / این / ضمیر خنثی','partOfSpeech','pronoun','suffix','?')),NULL,NULL,NULL),
(@l1,@mia_id,'B1-081-L01-T04',4,'learner','Ich habe ein Jobangebot in Leipzig bekommen.','یک پیشنهاد شغلی در لایپزیگ گرفته ام.',41,'Ich habe ein Jobangebot in Leipzig bekommen.',JSON_ARRAY(JSON_OBJECT('surface','Ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','habe','lemma','haben','translation','داشتن','partOfSpeech','verb'),JSON_OBJECT('surface','ein','lemma','ein','translation','یک / حرف تعریف نامعین','partOfSpeech','article'),JSON_OBJECT('surface','Jobangebot','lemma','Jobangebot','translation','پیشنهاد شغلی','partOfSpeech','noun'),JSON_OBJECT('surface','in','lemma','in','translation','در / داخل','partOfSpeech','preposition'),JSON_OBJECT('surface','Leipzig','lemma','Leipzig','translation','لایپزیگ','partOfSpeech','proper_noun'),JSON_OBJECT('surface','bekommen','lemma','bekommen','translation','گرفتن / دریافت کردن','partOfSpeech','verb','suffix','.')),NULL,NULL,NULL),
(@l1,@sara_id,'B1-081-L01-T05',5,'character','Das klingt interessant. Freust du dich?','جالب به نظر می رسد. خوشحالی؟',41,NULL,JSON_ARRAY(JSON_OBJECT('surface','Das','lemma','das','translation','این / آن','partOfSpeech','pronoun'),JSON_OBJECT('surface','klingt','lemma','klingen','translation','به نظر رسیدن','partOfSpeech','verb'),JSON_OBJECT('surface','interessant','lemma','interessant','translation','جالب','partOfSpeech','adjective','suffix','.'),JSON_OBJECT('surface','Freust','lemma','sich freuen','translation','خوشحال بودن','partOfSpeech','verb'),JSON_OBJECT('surface','du','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','dich','lemma','du','translation','تو','partOfSpeech','pronoun','suffix','?')),NULL,NULL,NULL),
(@l1,@mia_id,'B1-081-L01-T06',6,'learner','Ja, aber ich bin auch unsicher.','آره، ولی کمی هم مرددم.',41,'Ja, aber ich bin auch unsicher.',JSON_ARRAY(JSON_OBJECT('surface','Ja','lemma','ja','translation','بله / آره','partOfSpeech','interjection','suffix',','),JSON_OBJECT('surface','aber','lemma','aber','translation','اما / ولی','partOfSpeech','conjunction'),JSON_OBJECT('surface','ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','bin','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','auch','lemma','auch','translation','هم / همچنین','partOfSpeech','adverb'),JSON_OBJECT('surface','unsicher','lemma','unsicher','translation','مردد / بدون اطمینان','partOfSpeech','adjective','suffix','.')),NULL,NULL,NULL);

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l1,id,ROW_NUMBER() OVER (ORDER BY id),IF(introduced_series=81,'new','review'),0,1 FROM words WHERE course_id=@course_id AND ((lemma='du' AND part_of_speech='pronoun' AND translation='تو') OR (lemma='sein' AND part_of_speech='verb' AND translation='بودن') OR (lemma='heute' AND part_of_speech='adverb' AND translation='امروز') OR (lemma='so' AND part_of_speech='adverb' AND translation='این طور / آن طور') OR (lemma='still' AND part_of_speech='adjective' AND translation='ساکت') OR (lemma='was' AND part_of_speech='pronoun' AND translation='چی / چه') OR (lemma='los' AND part_of_speech='adjective' AND translation='پیش آمده / در جریان') OR (lemma='ich' AND part_of_speech='pronoun' AND translation='من') OR (lemma='müssen' AND part_of_speech='verb' AND translation='مجبور بودن / باید') OR (lemma='sich entscheiden' AND part_of_speech='verb' AND translation='تصمیم گرفتن') OR (lemma='worum' AND part_of_speech='pronoun' AND translation='درباره چه چیزی') OR (lemma='gehen' AND part_of_speech='verb' AND translation='رفتن') OR (lemma='es' AND part_of_speech='pronoun' AND translation='آن / این / ضمیر خنثی') OR (lemma='haben' AND part_of_speech='verb' AND translation='داشتن') OR (lemma='ein' AND part_of_speech='article' AND translation='یک / حرف تعریف نامعین') OR (lemma='Jobangebot' AND part_of_speech='noun' AND translation='پیشنهاد شغلی') OR (lemma='in' AND part_of_speech='preposition' AND translation='در / داخل') OR (lemma='Leipzig' AND part_of_speech='proper_noun' AND translation='لایپزیگ') OR (lemma='bekommen' AND part_of_speech='verb' AND translation='گرفتن / دریافت کردن') OR (lemma='das' AND part_of_speech='pronoun' AND translation='این / آن') OR (lemma='klingen' AND part_of_speech='verb' AND translation='به نظر رسیدن') OR (lemma='interessant' AND part_of_speech='adjective' AND translation='جالب') OR (lemma='sich freuen' AND part_of_speech='verb' AND translation='خوشحال بودن') OR (lemma='ja' AND part_of_speech='interjection' AND translation='بله / آره') OR (lemma='aber' AND part_of_speech='conjunction' AND translation='اما / ولی') OR (lemma='auch' AND part_of_speech='adverb' AND translation='هم / همچنین') OR (lemma='unsicher' AND part_of_speech='adjective' AND translation='مردد / بدون اطمینان')) ON DUPLICATE KEY UPDATE learning_role=VALUES(learning_role),is_target=0,exposure_count=VALUES(exposure_count);

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l1,id,999,'new',1,1 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-01' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=1;

SET @l1t1=(SELECT id FROM turns WHERE lesson_id=@l1 AND sort_order=1);

SET @l1t2=(SELECT id FROM turns WHERE lesson_id=@l1 AND sort_order=2);

SET @l1new=(SELECT id FROM words WHERE course_id=@course_id AND lemma='sich entscheiden' AND part_of_speech='verb' AND translation='تصمیم گرفتن' LIMIT 1);

INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l1,'B1-081-L01-A01','listen',1,@l1t1,NULL,NULL,NULL,'Hör genau zu.','با دقت گوش کن.',41,NULL),
(@l1,'B1-081-L01-A02','new_word',2,NULL,@l1new,'sich entscheiden','تصمیم گرفتن','Lerne den Ausdruck im Kontext.','این عبارت را در جمله یاد بگیر.',41,JSON_OBJECT('example','Ich muss mich entscheiden.')),
(@l1,'B1-081-L01-A03','speak',3,@l1t2,NULL,NULL,NULL,'Sprich Mias Antwort.','پاسخ میا را با صدای بلند بگو.',41,NULL),
(@l1,'B1-081-L01-A04','word_order',4,@l1t2,NULL,'Ich muss mich entscheiden.','باید تصمیم بگیرم.','Ordne die Wörter.','کلمه ها را مرتب کن.',41,JSON_OBJECT('tokens',JSON_ARRAY('Ich','muss','mich','entscheiden'))),
(@l1,'B1-081-L01-A05','reading_comprehension',5,NULL,NULL,'Warum muss Mia sich entscheiden?','چرا میا باید تصمیم بگیرد؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',41,JSON_OBJECT('question','Warum muss Mia sich entscheiden?','choices',JSON_ARRAY('Sie hat ein Jobangebot bekommen.','Sie möchte Kaffee bestellen.','Sie sucht ein Hotel.'),'correctIndex',0));

-- LESSON 2

INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (@chapter_id,@sara_id,@mia_id,'B1-M01-C01-L02','Gründe abwägen','سبک سنگین کردن دلیل ها','Gründe mit weil erklären und Vor- und Nachteile einer Stelle nennen.','با weil دلیل بیاور و نکات مثبت و منفی یک موقعیت شغلی را بگو.','mia-sara-b1-decisions',2,41,300,2,'validated',JSON_OBJECT('staging',TRUE,'databaseRevision','v9.1.1'));

SET @l2=LAST_INSERT_ID();

INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens,grammar_title,grammar_note,grammar_data) VALUES
(@l2,@sara_id,'B1-081-L02-T01',1,'character','Warum bist du unsicher?','چرا مرددی؟',41,NULL,JSON_ARRAY(JSON_OBJECT('surface','Warum','lemma','warum','translation','چرا','partOfSpeech','adverb'),JSON_OBJECT('surface','bist','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','du','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','unsicher','lemma','unsicher','translation','مردد / بدون اطمینان','partOfSpeech','adjective','suffix','?')),NULL,NULL,NULL),
(@l2,@mia_id,'B1-081-L02-T02',2,'learner','Weil die Stelle interessant ist, aber Leipzig weit weg ist.','چون موقعیت شغلی جالب است، ولی لایپزیگ خیلی دور است.',41,'Weil die Stelle interessant ist, aber Leipzig weit weg ist.',JSON_ARRAY(JSON_OBJECT('surface','Weil','lemma','weil','translation','چون / زیرا','partOfSpeech','conjunction'),JSON_OBJECT('surface','die','lemma','der','translation','حرف تعریف','partOfSpeech','article'),JSON_OBJECT('surface','Stelle','lemma','Stelle','translation','موقعیت شغلی','partOfSpeech','noun'),JSON_OBJECT('surface','interessant','lemma','interessant','translation','جالب','partOfSpeech','adjective'),JSON_OBJECT('surface','ist','lemma','sein','translation','بودن','partOfSpeech','verb','suffix',','),JSON_OBJECT('surface','aber','lemma','aber','translation','اما / ولی','partOfSpeech','conjunction'),JSON_OBJECT('surface','Leipzig','lemma','Leipzig','translation','لایپزیگ','partOfSpeech','proper_noun'),JSON_OBJECT('surface','weit','lemma','weit','translation','دور','partOfSpeech','adjective'),JSON_OBJECT('surface','weg','lemma','weg','translation','دور / آن طرف','partOfSpeech','adverb'),JSON_OBJECT('surface','ist','lemma','sein','translation','بودن','partOfSpeech','verb','suffix','.')),'weil + Nebensatz','Nach weil steht das konjugierte Verb am Ende.',JSON_OBJECT('focus','verb_final')),
(@l2,@sara_id,'B1-081-L02-T03',3,'character','Möchtest du denn umziehen?','پس می خواهی اسباب کشی کنی؟',41,NULL,JSON_ARRAY(JSON_OBJECT('surface','Möchtest','lemma','möchten','translation','خواستن / مایل بودن','partOfSpeech','verb'),JSON_OBJECT('surface','du','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','denn','lemma','denn','translation','پس / آخر','partOfSpeech','particle'),JSON_OBJECT('surface','umziehen','lemma','umziehen','translation','اسباب کشی کردن','partOfSpeech','verb','suffix','?')),NULL,NULL,NULL),
(@l2,@mia_id,'B1-081-L02-T04',4,'learner','Das weiß ich noch nicht.','هنوز نمی دانم.',41,'Das weiß ich noch nicht.',JSON_ARRAY(JSON_OBJECT('surface','Das','lemma','das','translation','این / آن','partOfSpeech','pronoun'),JSON_OBJECT('surface','weiß','lemma','wissen','translation','دانستن','partOfSpeech','verb'),JSON_OBJECT('surface','ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','noch','lemma','noch','translation','هنوز','partOfSpeech','adverb'),JSON_OBJECT('surface','nicht','lemma','nicht','translation','نه / نیست','partOfSpeech','particle','suffix','.')),NULL,NULL,NULL),
(@l2,@sara_id,'B1-081-L02-T05',5,'character','Was spricht für die Stelle?','چه چیزی به نفع این موقعیت شغلی است؟',41,NULL,JSON_ARRAY(JSON_OBJECT('surface','Was','lemma','was','translation','چی / چه','partOfSpeech','pronoun'),JSON_OBJECT('surface','spricht','lemma','sprechen','translation','صحبت کردن / حرف زدن','partOfSpeech','verb'),JSON_OBJECT('surface','für','lemma','für','translation','برای / به نفع','partOfSpeech','preposition'),JSON_OBJECT('surface','die','lemma','der','translation','حرف تعریف','partOfSpeech','article'),JSON_OBJECT('surface','Stelle','lemma','Stelle','translation','موقعیت شغلی','partOfSpeech','noun','suffix','?')),NULL,NULL,NULL),
(@l2,@mia_id,'B1-081-L02-T06',6,'learner','Ich könnte dort mehr lernen und mehr verdienen.','می توانم آنجا بیشتر یاد بگیرم و درآمد بیشتری داشته باشم.',41,'Ich könnte dort mehr lernen und mehr verdienen.',JSON_ARRAY(JSON_OBJECT('surface','Ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','könnte','lemma','können','translation','توانستن / بتوان','partOfSpeech','verb'),JSON_OBJECT('surface','dort','lemma','dort','translation','آنجا','partOfSpeech','adverb'),JSON_OBJECT('surface','mehr','lemma','mehr','translation','دیگه / بیشتر','partOfSpeech','adverb'),JSON_OBJECT('surface','lernen','lemma','lernen','translation','یاد گرفتن','partOfSpeech','verb'),JSON_OBJECT('surface','und','lemma','und','translation','و','partOfSpeech','conjunction'),JSON_OBJECT('surface','mehr','lemma','mehr','translation','دیگه / بیشتر','partOfSpeech','adverb'),JSON_OBJECT('surface','verdienen','lemma','verdienen','translation','درآمد داشتن','partOfSpeech','verb','suffix','.')),'könnte','Mit könnte klingt eine Möglichkeit vorsichtiger.',JSON_OBJECT('focus','konjunktiv_ii'));

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l2,id,ROW_NUMBER() OVER (ORDER BY id),IF(introduced_series=81,'new','review'),0,1 FROM words WHERE course_id=@course_id AND ((lemma='warum' AND part_of_speech='adverb' AND translation='چرا') OR (lemma='sein' AND part_of_speech='verb' AND translation='بودن') OR (lemma='du' AND part_of_speech='pronoun' AND translation='تو') OR (lemma='unsicher' AND part_of_speech='adjective' AND translation='مردد / بدون اطمینان') OR (lemma='weil' AND part_of_speech='conjunction' AND translation='چون / زیرا') OR (lemma='der' AND part_of_speech='article' AND translation='حرف تعریف') OR (lemma='Stelle' AND part_of_speech='noun' AND translation='موقعیت شغلی') OR (lemma='interessant' AND part_of_speech='adjective' AND translation='جالب') OR (lemma='aber' AND part_of_speech='conjunction' AND translation='اما / ولی') OR (lemma='Leipzig' AND part_of_speech='proper_noun' AND translation='لایپزیگ') OR (lemma='weit' AND part_of_speech='adjective' AND translation='دور') OR (lemma='weg' AND part_of_speech='adverb' AND translation='دور / آن طرف') OR (lemma='möchten' AND part_of_speech='verb' AND translation='خواستن / مایل بودن') OR (lemma='denn' AND part_of_speech='particle' AND translation='پس / آخر') OR (lemma='umziehen' AND part_of_speech='verb' AND translation='اسباب کشی کردن') OR (lemma='das' AND part_of_speech='pronoun' AND translation='این / آن') OR (lemma='wissen' AND part_of_speech='verb' AND translation='دانستن') OR (lemma='ich' AND part_of_speech='pronoun' AND translation='من') OR (lemma='noch' AND part_of_speech='adverb' AND translation='هنوز') OR (lemma='nicht' AND part_of_speech='particle' AND translation='نه / نیست') OR (lemma='was' AND part_of_speech='pronoun' AND translation='چی / چه') OR (lemma='sprechen' AND part_of_speech='verb' AND translation='صحبت کردن / حرف زدن') OR (lemma='für' AND part_of_speech='preposition' AND translation='برای / به نفع') OR (lemma='können' AND part_of_speech='verb' AND translation='توانستن / بتوان') OR (lemma='dort' AND part_of_speech='adverb' AND translation='آنجا') OR (lemma='mehr' AND part_of_speech='adverb' AND translation='دیگه / بیشتر') OR (lemma='lernen' AND part_of_speech='verb' AND translation='یاد گرفتن') OR (lemma='und' AND part_of_speech='conjunction' AND translation='و') OR (lemma='verdienen' AND part_of_speech='verb' AND translation='درآمد داشتن')) ON DUPLICATE KEY UPDATE learning_role=VALUES(learning_role),is_target=0,exposure_count=VALUES(exposure_count);

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l2,id,999,'new',1,1 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-02' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=1;

SET @l2t1=(SELECT id FROM turns WHERE lesson_id=@l2 AND sort_order=1);

SET @l2t2=(SELECT id FROM turns WHERE lesson_id=@l2 AND sort_order=2);

SET @l2new=(SELECT id FROM words WHERE course_id=@course_id AND lemma='weil' AND part_of_speech='conjunction' AND translation='چون / زیرا' LIMIT 1);

INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l2,'B1-081-L02-A01','listen',1,@l2t1,NULL,NULL,NULL,'Hör genau zu.','با دقت گوش کن.',41,NULL),
(@l2,'B1-081-L02-A02','new_word',2,NULL,@l2new,'weil','چون / زیرا','Lerne den Ausdruck im Kontext.','این عبارت را در جمله یاد بگیر.',41,JSON_OBJECT('example','Weil die Stelle interessant ist, aber Leipzig weit weg ist.')),
(@l2,'B1-081-L02-A03','speak',3,@l2t2,NULL,NULL,NULL,'Sprich Mias Antwort.','پاسخ میا را با صدای بلند بگو.',41,NULL),
(@l2,'B1-081-L02-A04','word_order',4,@l2t2,NULL,'Weil die Stelle interessant ist, aber Leipzig weit weg ist.','چون موقعیت شغلی جالب است، ولی لایپزیگ خیلی دور است.','Ordne die Wörter.','کلمه ها را مرتب کن.',41,JSON_OBJECT('tokens',JSON_ARRAY('Weil','die','Stelle','interessant','ist','aber','Leipzig','weit','weg','ist'))),
(@l2,'B1-081-L02-A05','reading_comprehension',5,NULL,NULL,'Warum ist Mia unsicher?','چرا میا مردد است؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',41,JSON_OBJECT('question','Warum ist Mia unsicher?','choices',JSON_ARRAY('Die Stelle ist langweilig.','Leipzig ist weit weg.','Sara zieht heute um.'),'correctIndex',1));

-- LESSON 3

INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (@chapter_id,@sara_id,@mia_id,'B1-M01-C01-L03','Was ist mir wichtig?','چه چیزی برایم مهم است؟','Persönliche Prioritäten ausdrücken und eine Unsicherheit begründen.','اولویت های شخصی را بیان کن و برای تردیدت دلیل بیاور.','mia-sara-b1-decisions',3,42,300,3,'validated',JSON_OBJECT('staging',TRUE,'databaseRevision','v9.1.1'));

SET @l3=LAST_INSERT_ID();

INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens,grammar_title,grammar_note,grammar_data) VALUES
(@l3,@sara_id,'B1-081-L03-T01',1,'character','Was ist dir bei der Entscheidung wichtig?','در این تصمیم چه چیزی برایت مهم است؟',42,NULL,JSON_ARRAY(JSON_OBJECT('surface','Was','lemma','was','translation','چی / چه','partOfSpeech','pronoun'),JSON_OBJECT('surface','ist','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','dir','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','bei','lemma','bei','translation','در / هنگام','partOfSpeech','preposition'),JSON_OBJECT('surface','der','lemma','der','translation','حرف تعریف','partOfSpeech','article'),JSON_OBJECT('surface','Entscheidung','lemma','Entscheidung','translation','تصمیم','partOfSpeech','noun'),JSON_OBJECT('surface','wichtig','lemma','wichtig','translation','مهم','partOfSpeech','adjective','suffix','?')),NULL,NULL,NULL),
(@l3,@mia_id,'B1-081-L03-T02',2,'learner','Ich möchte in der Nähe meiner Freunde bleiben.','می خواهم نزدیک دوستانم بمانم.',42,'Ich möchte in der Nähe meiner Freunde bleiben.',JSON_ARRAY(JSON_OBJECT('surface','Ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','möchte','lemma','möchten','translation','خواستن / مایل بودن','partOfSpeech','verb'),JSON_OBJECT('surface','in','lemma','in','translation','در / داخل','partOfSpeech','preposition'),JSON_OBJECT('surface','der','lemma','der','translation','حرف تعریف','partOfSpeech','article'),JSON_OBJECT('surface','Nähe','lemma','Nähe','translation','نزدیکی','partOfSpeech','noun'),JSON_OBJECT('surface','meiner','lemma','mein','translation','مال من / من','partOfSpeech','determiner'),JSON_OBJECT('surface','Freunde','lemma','Freund','translation','دوست','partOfSpeech','noun'),JSON_OBJECT('surface','bleiben','lemma','bleiben','translation','ماندن','partOfSpeech','verb','suffix','.')),NULL,NULL,NULL),
(@l3,@sara_id,'B1-081-L03-T03',3,'character','Und was ist mit der neuen Arbeit?','پس کار جدید چی؟',42,NULL,JSON_ARRAY(JSON_OBJECT('surface','Und','lemma','und','translation','و','partOfSpeech','conjunction'),JSON_OBJECT('surface','was','lemma','was','translation','چی / چه','partOfSpeech','pronoun'),JSON_OBJECT('surface','ist','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','mit','lemma','mit','translation','با','partOfSpeech','preposition'),JSON_OBJECT('surface','der','lemma','der','translation','حرف تعریف','partOfSpeech','article'),JSON_OBJECT('surface','neuen','lemma','neu','translation','جدید / تازه','partOfSpeech','adjective'),JSON_OBJECT('surface','Arbeit','lemma','Arbeit','translation','کار','partOfSpeech','noun','suffix','?')),NULL,NULL,NULL),
(@l3,@mia_id,'B1-081-L03-T04',4,'learner','Die Arbeit gefällt mir, weil ich dort mehr Verantwortung hätte.','از کار خوشم می آید، چون آنجا مسوولیت بیشتری خواهم داشت.',42,'Die Arbeit gefällt mir, weil ich dort mehr Verantwortung hätte.',JSON_ARRAY(JSON_OBJECT('surface','Die','lemma','der','translation','حرف تعریف','partOfSpeech','article'),JSON_OBJECT('surface','Arbeit','lemma','Arbeit','translation','کار','partOfSpeech','noun'),JSON_OBJECT('surface','gefällt','lemma','gefallen','translation','خوش آمدن','partOfSpeech','verb'),JSON_OBJECT('surface','mir','lemma','ich','translation','من','partOfSpeech','pronoun','suffix',','),JSON_OBJECT('surface','weil','lemma','weil','translation','چون / زیرا','partOfSpeech','conjunction'),JSON_OBJECT('surface','ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','dort','lemma','dort','translation','آنجا','partOfSpeech','adverb'),JSON_OBJECT('surface','mehr','lemma','mehr','translation','دیگه / بیشتر','partOfSpeech','adverb'),JSON_OBJECT('surface','Verantwortung','lemma','Verantwortung','translation','مسوولیت','partOfSpeech','noun'),JSON_OBJECT('surface','hätte','lemma','haben','translation','داشتن','partOfSpeech','verb','suffix','.')),'hätte','Mit hätte beschreibt Mia eine vorgestellte Möglichkeit.',JSON_OBJECT('focus','konjunktiv_ii')),
(@l3,@sara_id,'B1-081-L03-T05',5,'character','Beides ist wichtig.','هر دو مهم اند.',42,NULL,JSON_ARRAY(JSON_OBJECT('surface','Beides','lemma','beide','translation','هر دو','partOfSpeech','pronoun'),JSON_OBJECT('surface','ist','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','wichtig','lemma','wichtig','translation','مهم','partOfSpeech','adjective','suffix','.')),NULL,NULL,NULL),
(@l3,@mia_id,'B1-081-L03-T06',6,'learner','Genau. Deshalb brauche ich noch Zeit.','دقیقا. برای همین هنوز به زمان نیاز دارم.',42,'Genau. Deshalb brauche ich noch Zeit.',JSON_ARRAY(JSON_OBJECT('surface','Genau','lemma','genau','translation','دقیقا','partOfSpeech','adverb','suffix','.'),JSON_OBJECT('surface','Deshalb','lemma','deshalb','translation','برای همین / بنابراین','partOfSpeech','adverb'),JSON_OBJECT('surface','brauche','lemma','brauchen','translation','نیاز داشتن / لازم داشتن','partOfSpeech','verb'),JSON_OBJECT('surface','ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','noch','lemma','noch','translation','هنوز','partOfSpeech','adverb'),JSON_OBJECT('surface','Zeit','lemma','Zeit','translation','وقت / زمان','partOfSpeech','noun','suffix','.')),NULL,NULL,NULL);

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l3,id,ROW_NUMBER() OVER (ORDER BY id),IF(introduced_series=81,'new','review'),0,1 FROM words WHERE course_id=@course_id AND ((lemma='was' AND part_of_speech='pronoun' AND translation='چی / چه') OR (lemma='sein' AND part_of_speech='verb' AND translation='بودن') OR (lemma='du' AND part_of_speech='pronoun' AND translation='تو') OR (lemma='bei' AND part_of_speech='preposition' AND translation='در / هنگام') OR (lemma='der' AND part_of_speech='article' AND translation='حرف تعریف') OR (lemma='Entscheidung' AND part_of_speech='noun' AND translation='تصمیم') OR (lemma='wichtig' AND part_of_speech='adjective' AND translation='مهم') OR (lemma='ich' AND part_of_speech='pronoun' AND translation='من') OR (lemma='möchten' AND part_of_speech='verb' AND translation='خواستن / مایل بودن') OR (lemma='in' AND part_of_speech='preposition' AND translation='در / داخل') OR (lemma='Nähe' AND part_of_speech='noun' AND translation='نزدیکی') OR (lemma='mein' AND part_of_speech='determiner' AND translation='مال من / من') OR (lemma='Freund' AND part_of_speech='noun' AND translation='دوست') OR (lemma='bleiben' AND part_of_speech='verb' AND translation='ماندن') OR (lemma='und' AND part_of_speech='conjunction' AND translation='و') OR (lemma='mit' AND part_of_speech='preposition' AND translation='با') OR (lemma='neu' AND part_of_speech='adjective' AND translation='جدید / تازه') OR (lemma='Arbeit' AND part_of_speech='noun' AND translation='کار') OR (lemma='gefallen' AND part_of_speech='verb' AND translation='خوش آمدن') OR (lemma='weil' AND part_of_speech='conjunction' AND translation='چون / زیرا') OR (lemma='dort' AND part_of_speech='adverb' AND translation='آنجا') OR (lemma='mehr' AND part_of_speech='adverb' AND translation='دیگه / بیشتر') OR (lemma='Verantwortung' AND part_of_speech='noun' AND translation='مسوولیت') OR (lemma='haben' AND part_of_speech='verb' AND translation='داشتن') OR (lemma='beide' AND part_of_speech='pronoun' AND translation='هر دو') OR (lemma='genau' AND part_of_speech='adverb' AND translation='دقیقا') OR (lemma='deshalb' AND part_of_speech='adverb' AND translation='برای همین / بنابراین') OR (lemma='brauchen' AND part_of_speech='verb' AND translation='نیاز داشتن / لازم داشتن') OR (lemma='noch' AND part_of_speech='adverb' AND translation='هنوز') OR (lemma='Zeit' AND part_of_speech='noun' AND translation='وقت / زمان')) ON DUPLICATE KEY UPDATE learning_role=VALUES(learning_role),is_target=0,exposure_count=VALUES(exposure_count);

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l3,id,999,'new',1,1 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-03' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=1;

SET @l3t1=(SELECT id FROM turns WHERE lesson_id=@l3 AND sort_order=1);

SET @l3t2=(SELECT id FROM turns WHERE lesson_id=@l3 AND sort_order=2);

SET @l3new=(SELECT id FROM words WHERE course_id=@course_id AND lemma='Verantwortung' AND part_of_speech='noun' AND translation='مسوولیت' LIMIT 1);

INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l3,'B1-081-L03-A01','listen',1,@l3t1,NULL,NULL,NULL,'Hör genau zu.','با دقت گوش کن.',42,NULL),
(@l3,'B1-081-L03-A02','new_word',2,NULL,@l3new,'Verantwortung','مسوولیت','Lerne den Ausdruck im Kontext.','این عبارت را در جمله یاد بگیر.',42,JSON_OBJECT('example','Die Arbeit gefällt mir, weil ich dort mehr Verantwortung hätte.')),
(@l3,'B1-081-L03-A03','speak',3,@l3t2,NULL,NULL,NULL,'Sprich Mias Antwort.','پاسخ میا را با صدای بلند بگو.',42,NULL),
(@l3,'B1-081-L03-A04','word_order',4,@l3t2,NULL,'Ich möchte in der Nähe meiner Freunde bleiben.','می خواهم نزدیک دوستانم بمانم.','Ordne die Wörter.','کلمه ها را مرتب کن.',42,JSON_OBJECT('tokens',JSON_ARRAY('Ich','möchte','in','der','Nähe','meiner','Freunde','bleiben'))),
(@l3,'B1-081-L03-A05','reading_comprehension',5,NULL,NULL,'Was ist Mia besonders wichtig?','چه چیزی برای میا اهمیت ویژه دارد؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',42,JSON_OBJECT('question','Was ist Mia besonders wichtig?','choices',JSON_ARRAY('In der Nähe ihrer Freunde zu bleiben.','Sofort ein Ticket zu kaufen.','Nur mehr Geld zu verdienen.'),'correctIndex',0));

-- LESSON 4

INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,lesson_key,title,title_translation,learning_objective,learning_objective_translation,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES (@chapter_id,@sara_id,@mia_id,'B1-M01-C01-L04','Eine Liste machen','درست کردن یک فهرست','Einen konkreten nächsten Schritt planen und Hilfe wertschätzen.','یک قدم بعدی مشخص برنامه ریزی کن و از کمک طرف مقابل تشکر کن.','mia-sara-b1-decisions',4,42,300,4,'validated',JSON_OBJECT('staging',TRUE,'databaseRevision','v9.1.1'));

SET @l4=LAST_INSERT_ID();

INSERT INTO turns (lesson_id,character_id,turn_key,sort_order,role,text,translation,difficulty,speech_target,tokens,grammar_title,grammar_note,grammar_data) VALUES
(@l4,@sara_id,'B1-081-L04-T01',1,'character','Wie willst du dich entscheiden?','می خواهی چطور تصمیم بگیری؟',42,NULL,JSON_ARRAY(JSON_OBJECT('surface','Wie','lemma','wie','translation','چطور / چگونه','partOfSpeech','adverb'),JSON_OBJECT('surface','willst','lemma','wollen','translation','خواستن','partOfSpeech','verb'),JSON_OBJECT('surface','du','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','dich','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','entscheiden','lemma','sich entscheiden','translation','تصمیم گرفتن','partOfSpeech','verb','suffix','?')),NULL,NULL,NULL),
(@l4,@mia_id,'B1-081-L04-T02',2,'learner','Ich schreibe zuerst alle Vorteile und Nachteile auf.','اول همه مزایا و معایب را یادداشت می کنم.',42,'Ich schreibe zuerst alle Vorteile und Nachteile auf.',JSON_ARRAY(JSON_OBJECT('surface','Ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','schreibe','lemma','aufschreiben','translation','یادداشت کردن','partOfSpeech','verb'),JSON_OBJECT('surface','zuerst','lemma','zuerst','translation','اول / ابتدا','partOfSpeech','adverb'),JSON_OBJECT('surface','alle','lemma','alle','translation','همه','partOfSpeech','determiner'),JSON_OBJECT('surface','Vorteile','lemma','Vorteil','translation','مزیت','partOfSpeech','noun'),JSON_OBJECT('surface','und','lemma','und','translation','و','partOfSpeech','conjunction'),JSON_OBJECT('surface','Nachteile','lemma','Nachteil','translation','عیب / نکته منفی','partOfSpeech','noun'),JSON_OBJECT('surface','auf','lemma','aufschreiben','translation','یادداشت کردن','partOfSpeech','verb','suffix','.')),NULL,NULL,NULL),
(@l4,@sara_id,'B1-081-L04-T03',3,'character','Das ist eine gute Idee.','ایده خوبی است.',42,NULL,JSON_ARRAY(JSON_OBJECT('surface','Das','lemma','das','translation','این / آن','partOfSpeech','pronoun'),JSON_OBJECT('surface','ist','lemma','sein','translation','بودن','partOfSpeech','verb'),JSON_OBJECT('surface','eine','lemma','ein','translation','یک / حرف تعریف نامعین','partOfSpeech','article'),JSON_OBJECT('surface','gute','lemma','gut','translation','خوب','partOfSpeech','adjective'),JSON_OBJECT('surface','Idee','lemma','Idee','translation','ایده','partOfSpeech','noun','suffix','.')),NULL,NULL,NULL),
(@l4,@mia_id,'B1-081-L04-T04',4,'learner','Danach kann ich in Ruhe darüber nachdenken.','بعد از آن می توانم با آرامش درباره اش فکر کنم.',42,'Danach kann ich in Ruhe darüber nachdenken.',JSON_ARRAY(JSON_OBJECT('surface','Danach','lemma','danach','translation','بعد از آن / بعدش','partOfSpeech','adverb'),JSON_OBJECT('surface','kann','lemma','können','translation','توانستن / بتوان','partOfSpeech','verb'),JSON_OBJECT('surface','ich','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','in','lemma','in','translation','در / داخل','partOfSpeech','preposition'),JSON_OBJECT('surface','Ruhe','lemma','Ruhe','translation','آرامش','partOfSpeech','noun'),JSON_OBJECT('surface','darüber','lemma','darüber','translation','درباره آن','partOfSpeech','adverb'),JSON_OBJECT('surface','nachdenken','lemma','nachdenken','translation','فکر کردن','partOfSpeech','verb','suffix','.')),NULL,NULL,NULL),
(@l4,@sara_id,'B1-081-L04-T05',5,'character','Und wann sprechen wir wieder?','و کی دوباره حرف می زنیم؟',42,NULL,JSON_ARRAY(JSON_OBJECT('surface','Und','lemma','und','translation','و','partOfSpeech','conjunction'),JSON_OBJECT('surface','wann','lemma','wann','translation','کی / چه زمانی','partOfSpeech','adverb'),JSON_OBJECT('surface','sprechen','lemma','sprechen','translation','صحبت کردن / حرف زدن','partOfSpeech','verb'),JSON_OBJECT('surface','wir','lemma','wir','translation','ما','partOfSpeech','pronoun'),JSON_OBJECT('surface','wieder','lemma','wieder','translation','دوباره','partOfSpeech','adverb','suffix','?')),NULL,NULL,NULL),
(@l4,@mia_id,'B1-081-L04-T06',6,'learner','Morgen. Danke, dass du mir hilfst.','فردا. ممنون که کمکم می کنی.',42,'Morgen. Danke, dass du mir hilfst.',JSON_ARRAY(JSON_OBJECT('surface','Morgen','lemma','morgen','translation','فردا','partOfSpeech','adverb','suffix','.'),JSON_OBJECT('surface','Danke','lemma','danke','translation','ممنون','partOfSpeech','interjection','suffix',','),JSON_OBJECT('surface','dass','lemma','dass','translation','که','partOfSpeech','conjunction'),JSON_OBJECT('surface','du','lemma','du','translation','تو','partOfSpeech','pronoun'),JSON_OBJECT('surface','mir','lemma','ich','translation','من','partOfSpeech','pronoun'),JSON_OBJECT('surface','hilfst','lemma','helfen','translation','کمک کردن','partOfSpeech','verb','suffix','.')),'dass + Nebensatz','Nach dass steht das konjugierte Verb am Ende.',JSON_OBJECT('focus','verb_final'));

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l4,id,ROW_NUMBER() OVER (ORDER BY id),IF(introduced_series=81,'new','review'),0,1 FROM words WHERE course_id=@course_id AND ((lemma='wie' AND part_of_speech='adverb' AND translation='چطور / چگونه') OR (lemma='wollen' AND part_of_speech='verb' AND translation='خواستن') OR (lemma='du' AND part_of_speech='pronoun' AND translation='تو') OR (lemma='sich entscheiden' AND part_of_speech='verb' AND translation='تصمیم گرفتن') OR (lemma='ich' AND part_of_speech='pronoun' AND translation='من') OR (lemma='aufschreiben' AND part_of_speech='verb' AND translation='یادداشت کردن') OR (lemma='zuerst' AND part_of_speech='adverb' AND translation='اول / ابتدا') OR (lemma='alle' AND part_of_speech='determiner' AND translation='همه') OR (lemma='Vorteil' AND part_of_speech='noun' AND translation='مزیت') OR (lemma='und' AND part_of_speech='conjunction' AND translation='و') OR (lemma='Nachteil' AND part_of_speech='noun' AND translation='عیب / نکته منفی') OR (lemma='das' AND part_of_speech='pronoun' AND translation='این / آن') OR (lemma='sein' AND part_of_speech='verb' AND translation='بودن') OR (lemma='ein' AND part_of_speech='article' AND translation='یک / حرف تعریف نامعین') OR (lemma='gut' AND part_of_speech='adjective' AND translation='خوب') OR (lemma='Idee' AND part_of_speech='noun' AND translation='ایده') OR (lemma='danach' AND part_of_speech='adverb' AND translation='بعد از آن / بعدش') OR (lemma='können' AND part_of_speech='verb' AND translation='توانستن / بتوان') OR (lemma='in' AND part_of_speech='preposition' AND translation='در / داخل') OR (lemma='Ruhe' AND part_of_speech='noun' AND translation='آرامش') OR (lemma='darüber' AND part_of_speech='adverb' AND translation='درباره آن') OR (lemma='nachdenken' AND part_of_speech='verb' AND translation='فکر کردن') OR (lemma='wann' AND part_of_speech='adverb' AND translation='کی / چه زمانی') OR (lemma='sprechen' AND part_of_speech='verb' AND translation='صحبت کردن / حرف زدن') OR (lemma='wir' AND part_of_speech='pronoun' AND translation='ما') OR (lemma='wieder' AND part_of_speech='adverb' AND translation='دوباره') OR (lemma='morgen' AND part_of_speech='adverb' AND translation='فردا') OR (lemma='danke' AND part_of_speech='interjection' AND translation='ممنون') OR (lemma='dass' AND part_of_speech='conjunction' AND translation='که') OR (lemma='helfen' AND part_of_speech='verb' AND translation='کمک کردن')) ON DUPLICATE KEY UPDATE learning_role=VALUES(learning_role),is_target=0,exposure_count=VALUES(exposure_count);

INSERT INTO lesson_words (lesson_id,word_id,sort_order,learning_role,is_target,exposure_count) SELECT @l4,id,999,'new',1,1 FROM words WHERE course_id=@course_id AND word_key='de-fa-b1-081-target-04' ON DUPLICATE KEY UPDATE learning_role='new',is_target=1,exposure_count=1;

SET @l4t1=(SELECT id FROM turns WHERE lesson_id=@l4 AND sort_order=1);

SET @l4t2=(SELECT id FROM turns WHERE lesson_id=@l4 AND sort_order=2);

SET @l4new=(SELECT id FROM words WHERE course_id=@course_id AND lemma='Vorteil' AND part_of_speech='noun' AND translation='مزیت' LIMIT 1);

INSERT INTO activities (lesson_id,activity_key,activity_type,sort_order,turn_id,word_id,prompt,prompt_translation,instruction,instruction_translation,difficulty,config) VALUES
(@l4,'B1-081-L04-A01','listen',1,@l4t1,NULL,NULL,NULL,'Hör genau zu.','با دقت گوش کن.',42,NULL),
(@l4,'B1-081-L04-A02','new_word',2,NULL,@l4new,'Vorteil','مزیت','Lerne den Ausdruck im Kontext.','این عبارت را در جمله یاد بگیر.',42,JSON_OBJECT('example','Ich schreibe zuerst alle Vorteile und Nachteile auf.')),
(@l4,'B1-081-L04-A03','speak',3,@l4t2,NULL,NULL,NULL,'Sprich Mias Antwort.','پاسخ میا را با صدای بلند بگو.',42,NULL),
(@l4,'B1-081-L04-A04','word_order',4,@l4t2,NULL,'Ich schreibe zuerst alle Vorteile und Nachteile auf.','اول همه مزایا و معایب را یادداشت می کنم.','Ordne die Wörter.','کلمه ها را مرتب کن.',42,JSON_OBJECT('tokens',JSON_ARRAY('Ich','schreibe','zuerst','alle','Vorteile','und','Nachteile','auf'))),
(@l4,'B1-081-L04-A05','reading_comprehension',5,NULL,NULL,'Was macht Mia als Nächstes?','میا در قدم بعدی چه کار می کند؟','Wähle die richtige Antwort.','جواب درست را انتخاب کن.',42,JSON_OBJECT('question','Was macht Mia als Nächstes?','choices',JSON_ARRAY('Sie sagt sofort ab.','Sie schreibt Vorteile und Nachteile auf.','Sie zieht noch heute um.'),'correctIndex',1));

-- Atomic v9.1.1 chapter guardrails.

SET @lesson_count=(SELECT COUNT(*) FROM lessons WHERE chapter_id=@chapter_id);

SET @turn_count=(SELECT COUNT(*) FROM turns WHERE lesson_id IN (@l1,@l2,@l3,@l4));

SET @learner_turns=(SELECT COUNT(*) FROM turns WHERE lesson_id IN (@l1,@l2,@l3,@l4) AND role='learner');

SET @learner_targets=(SELECT COUNT(*) FROM turns WHERE lesson_id IN (@l1,@l2,@l3,@l4) AND role='learner' AND speech_target IS NOT NULL AND CHAR_LENGTH(TRIM(speech_target))>0);

SET @reading_count=(SELECT COUNT(*) FROM activities WHERE lesson_id IN (@l1,@l2,@l3,@l4) AND activity_type='reading_comprehension');

SET @character_pair_count=(SELECT COUNT(*) FROM lessons WHERE chapter_id=@chapter_id AND prompt_character_id=@sara_id AND learner_character_id=@mia_id AND prompt_character_id<>learner_character_id);

SET @bad_token_tuples=(SELECT COUNT(*) FROM turns t JOIN JSON_TABLE(t.tokens,'$[*]' COLUMNS (surface VARCHAR(255) PATH '$.surface',lemma VARCHAR(255) PATH '$.lemma',translation VARCHAR(512) PATH '$.translation',part_of_speech VARCHAR(48) PATH '$.partOfSpeech')) jt LEFT JOIN words w ON w.course_id=@course_id AND w.lemma=jt.lemma AND w.part_of_speech=jt.part_of_speech AND w.translation=jt.translation WHERE t.lesson_id IN (@l1,@l2,@l3,@l4) AND (jt.surface IS NULL OR w.id IS NULL));

SELECT IF(@course_id IS NULL OR @mia_id IS NULL OR @sara_id IS NULL,1/0,1) AS dependency_guard;

SELECT IF(@lesson_count<>4 OR @turn_count<>24 OR @learner_turns<>12 OR @learner_targets<>12 OR @reading_count<>4 OR @character_pair_count<>4 OR @bad_token_tuples<>0,1/0,1) AS chapter_guard;

COMMIT;
