-- NOVA v9.0 / B1 SERIES 104 / Ich sollte mehr schlafen
-- Requires canonical v9.0 and validated Series 103. No schema DDL.
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS import_nova_series_104_v9;
DELIMITER $$
CREATE PROCEDURE import_nova_series_104_v9()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL; DECLARE v_level BIGINT UNSIGNED DEFAULT NULL; DECLARE v_module BIGINT UNSIGNED DEFAULT NULL; DECLARE v_chapter BIGINT UNSIGNED DEFAULT NULL; DECLARE v_count INT DEFAULT 0;
  DECLARE v_c_mia BIGINT UNSIGNED DEFAULT NULL; DECLARE v_c_sara BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_001 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_002 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_003 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_004 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_005 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_006 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_007 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_008 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_009 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_010 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_011 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_012 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_013 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_014 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_015 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_016 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_017 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_018 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_019 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_020 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_021 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_022 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_023 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_024 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_025 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_026 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_027 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_028 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_029 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_030 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_031 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_032 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_033 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_034 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_035 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_036 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_037 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_038 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_039 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_040 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_041 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_042 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_043 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_044 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_045 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_046 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_047 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_048 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_049 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_050 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_051 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_052 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_053 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_054 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_055 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_056 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_057 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_058 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_059 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_060 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_061 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_062 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_063 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_064 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_065 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_066 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_067 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_068 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_069 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_070 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_071 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_1 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_2 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_3 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_4 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_1 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_2 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_3 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_4 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_5 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_6 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_7 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_8 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_9 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_10 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_11 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_12 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_13 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_14 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_15 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_16 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_17 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_18 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_19 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_20 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_21 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_22 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_23 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_24 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;
  SELECT id INTO v_course FROM courses WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1; IF v_course IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Canonical de-fa Course missing.'; END IF;
  SELECT id INTO v_level FROM levels WHERE course_id=v_course AND cefr_level='B1' AND sort_order=3 ORDER BY id LIMIT 1;
  SELECT id INTO v_module FROM modules WHERE level_id=v_level AND sort_order=5 ORDER BY id LIMIT 1; IF v_level IS NULL OR v_module IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='B1 dependency missing.'; END IF;
  SELECT COUNT(*) INTO v_count FROM chapters c JOIN modules m ON m.id=c.module_id WHERE m.level_id=v_level AND c.title='Wenn es nicht besser wird, komme ich wieder' AND c.status IN ('validated','complete'); IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 103 must be validated.'; END IF;
  SELECT COUNT(*) INTO v_count FROM lessons WHERE storyline_key='mia-sara-b1-health-routine'; IF v_count<>12 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Health storyline must contain exactly twelve prior lessons.'; END IF;
  SELECT id INTO v_chapter FROM chapters WHERE module_id=v_module AND sort_order=4 ORDER BY id LIMIT 1; IF v_chapter IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 104 chapter missing.'; END IF;
  SELECT COUNT(*) INTO v_count FROM chapters WHERE id=v_chapter AND title='Ich sollte mehr schlafen' AND title_translation='باید بیشتر بخوابم'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 104 canonical title mismatch.'; END IF;
  SELECT COUNT(*) INTO v_count FROM lessons WHERE chapter_id=v_chapter; IF v_count<>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 104 chapter must be empty.'; END IF;
  SELECT id INTO v_c_mia FROM characters WHERE course_id=v_course AND name='Mia' AND gender='female' LIMIT 1; SELECT id INTO v_c_sara FROM characters WHERE course_id=v_course AND name='Sara' AND gender='female' LIMIT 1;
  IF v_c_mia IS NULL OR v_c_sara IS NULL OR v_c_mia=v_c_sara THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Distinct Characters missing.'; END IF;
  SELECT id INTO v_w_001 FROM words WHERE course_id=v_course AND lemma='Abend' AND part_of_speech='noun' AND translation='عصر / شب' ORDER BY id LIMIT 1;
  IF v_w_001 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Abend | noun'; END IF;
  SELECT id INTO v_w_002 FROM words WHERE course_id=v_course AND lemma='acht' AND part_of_speech='number' AND translation='هشت' ORDER BY id LIMIT 1;
  IF v_w_002 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: acht | number'; END IF;
  SELECT id INTO v_w_003 FROM words WHERE course_id=v_course AND lemma='an' AND part_of_speech='preposition' AND translation='در / در روز' ORDER BY id LIMIT 1;
  IF v_w_003 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: an | preposition'; END IF;
  SELECT id INTO v_w_004 FROM words WHERE course_id=v_course AND lemma='auf' AND part_of_speech='preposition' AND translation='روی / برای' ORDER BY id LIMIT 1;
  IF v_w_004 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: auf | preposition'; END IF;
  SELECT id INTO v_w_005 FROM words WHERE course_id=v_course AND lemma='aufstehen' AND part_of_speech='verb' AND translation='از خواب بلند شدن' ORDER BY id LIMIT 1;
  IF v_w_005 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: aufstehen | verb'; END IF;
  SELECT id INTO v_w_006 FROM words WHERE course_id=v_course AND lemma='ausschalten' AND part_of_speech='verb' AND translation='خاموش کردن' ORDER BY id LIMIT 1;
  IF v_w_006 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: ausschalten | verb'; END IF;
  SELECT id INTO v_w_007 FROM words WHERE course_id=v_course AND lemma='besser' AND part_of_speech='adverb' AND translation='بهتر' ORDER BY id LIMIT 1;
  IF v_w_007 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: besser | adverb'; END IF;
  SELECT id INTO v_w_008 FROM words WHERE course_id=v_course AND lemma='Bett' AND part_of_speech='noun' AND translation='تخت' ORDER BY id LIMIT 1;
  IF v_w_008 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Bett | noun'; END IF;
  SELECT id INTO v_w_009 FROM words WHERE course_id=v_course AND lemma='Bildschirm' AND part_of_speech='noun' AND translation='صفحه نمایش' ORDER BY id LIMIT 1;
  IF v_w_009 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Bildschirm','Bildschirm','noun','صفحه نمایش',55,'{"type":"noun","gender":"der","plural":"Bildschirme"}','[{"text":"Handy","translation":"گوشی"},{"text":"Telefon","translation":"تلفن"},{"text":"Licht","translation":"نور"}]','Der Bildschirm stört deinen Schlaf.','صفحه نمایش خواب تو را مختل می کند.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":true}'); SET v_w_009=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_010 FROM words WHERE course_id=v_course AND lemma='bisschen' AND part_of_speech='noun' AND translation='کمی' ORDER BY id LIMIT 1;
  IF v_w_010 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: bisschen | noun'; END IF;
  SELECT id INTO v_w_011 FROM words WHERE course_id=v_course AND lemma='brauchen' AND part_of_speech='verb' AND translation='نیاز داشتن / لازم داشتن' ORDER BY id LIMIT 1;
  IF v_w_011 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: brauchen | verb'; END IF;
  SELECT id INTO v_w_012 FROM words WHERE course_id=v_course AND lemma='damit' AND part_of_speech='conjunction' AND translation='تا / برای اینکه' ORDER BY id LIMIT 1;
  IF v_w_012 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: damit | conjunction'; END IF;
  SELECT id INTO v_w_013 FROM words WHERE course_id=v_course AND lemma='Dann sollte ich das Handy früher ausschalten.' AND part_of_speech='phrase' AND translation='پس باید گوشی را زودتر خاموش کنم.' ORDER BY id LIMIT 1;
  IF v_w_013 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Dann sollte ich das Handy früher ausschalten.','Dann sollte ich das Handy früher ausschalten.','phrase','پس باید گوشی را زودتر خاموش کنم.',55,'{"type":"phrase","focus":"sollte_and_sleep_routine"}','[{"text":"Ich muss heute arbeiten.","translation":"امروز باید کار کنم."},{"text":"Der Zug kommt später.","translation":"قطار دیرتر می آید."},{"text":"Das Fenster ist offen.","translation":"پنجره باز است."}]','Dann sollte ich das Handy früher ausschalten.','پس باید گوشی را زودتر خاموش کنم.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":false}'); SET v_w_013=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_014 FROM words WHERE course_id=v_course AND lemma='dann' AND part_of_speech='adverb' AND translation='بعد / سپس' ORDER BY id LIMIT 1;
  IF v_w_014 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: dann | adverb'; END IF;
  SELECT id INTO v_w_015 FROM words WHERE course_id=v_course AND lemma='das' AND part_of_speech='pronoun' AND translation='این / آن' ORDER BY id LIMIT 1;
  IF v_w_015 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: das | pronoun'; END IF;
  SELECT id INTO v_w_016 FROM words WHERE course_id=v_course AND lemma='dein' AND part_of_speech='determiner' AND translation='مال تو / تو' ORDER BY id LIMIT 1;
  IF v_w_016 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: dein | determiner'; END IF;
  SELECT id INTO v_w_017 FROM words WHERE course_id=v_course AND lemma='der' AND part_of_speech='article' AND translation='حرف تعریف' ORDER BY id LIMIT 1;
  IF v_w_017 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: der | article'; END IF;
  SELECT id INTO v_w_018 FROM words WHERE course_id=v_course AND lemma='du' AND part_of_speech='pronoun' AND translation='تو' ORDER BY id LIMIT 1;
  IF v_w_018 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: du | pronoun'; END IF;
  SELECT id INTO v_w_019 FROM words WHERE course_id=v_course AND lemma='ein' AND part_of_speech='article' AND translation='یک / حرف تعریف نامعین' ORDER BY id LIMIT 1;
  IF v_w_019 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: ein | article'; END IF;
  SELECT id INTO v_w_020 FROM words WHERE course_id=v_course AND lemma='einfach' AND part_of_speech='adjective' AND translation='آسان / ساده' ORDER BY id LIMIT 1;
  IF v_w_020 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: einfach | adjective'; END IF;
  SELECT id INTO v_w_021 FROM words WHERE course_id=v_course AND lemma='etwas' AND part_of_speech='pronoun' AND translation='چیزی / یک چیزی' ORDER BY id LIMIT 1;
  IF v_w_021 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: etwas | pronoun'; END IF;
  SELECT id INTO v_w_022 FROM words WHERE course_id=v_course AND lemma='früh' AND part_of_speech='adverb' AND translation='زودتر' ORDER BY id LIMIT 1;
  IF v_w_022 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: früh | adverb'; END IF;
  SELECT id INTO v_w_023 FROM words WHERE course_id=v_course AND lemma='gehen' AND part_of_speech='verb' AND translation='رفتن' ORDER BY id LIMIT 1;
  IF v_w_023 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: gehen | verb'; END IF;
  SELECT id INTO v_w_024 FROM words WHERE course_id=v_course AND lemma='genug' AND part_of_speech='adverb' AND translation='کافی' ORDER BY id LIMIT 1;
  IF v_w_024 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: genug | adverb'; END IF;
  SELECT id INTO v_w_025 FROM words WHERE course_id=v_course AND lemma='Gewohnheit' AND part_of_speech='noun' AND translation='عادت' ORDER BY id LIMIT 1;
  IF v_w_025 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Gewohnheit','Gewohnheit','noun','عادت',55,'{"type":"noun","gender":"die","plural":"Gewohnheiten"}','[{"text":"Plan","translation":"برنامه"},{"text":"Pause","translation":"استراحت"},{"text":"Rat","translation":"توصیه"}]','Das ist eine gute Gewohnheit.','این یک عادت خوب است.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":true}'); SET v_w_025=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_026 FROM words WHERE course_id=v_course AND lemma='gut' AND part_of_speech='adjective' AND translation='خوب' ORDER BY id LIMIT 1;
  IF v_w_026 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: gut | adjective'; END IF;
  SELECT id INTO v_w_027 FROM words WHERE course_id=v_course AND lemma='haben' AND part_of_speech='verb' AND translation='داشتن' ORDER BY id LIMIT 1;
  IF v_w_027 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: haben | verb'; END IF;
  SELECT id INTO v_w_028 FROM words WHERE course_id=v_course AND lemma='Handy' AND part_of_speech='noun' AND translation='گوشی' ORDER BY id LIMIT 1;
  IF v_w_028 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Handy | noun'; END IF;
  SELECT id INTO v_w_029 FROM words WHERE course_id=v_course AND lemma='helfen' AND part_of_speech='verb' AND translation='کمک کردن' ORDER BY id LIMIT 1;
  IF v_w_029 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: helfen | verb'; END IF;
  SELECT id INTO v_w_030 FROM words WHERE course_id=v_course AND lemma='heute' AND part_of_speech='adverb' AND translation='امروز' ORDER BY id LIMIT 1;
  IF v_w_030 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: heute | adverb'; END IF;
  SELECT id INTO v_w_031 FROM words WHERE course_id=v_course AND lemma='Ich stehe morgen um acht Uhr auf.' AND part_of_speech='phrase' AND translation='فردا ساعت هشت بیدار می شوم.' ORDER BY id LIMIT 1;
  IF v_w_031 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Ich stehe morgen um acht Uhr auf.','Ich stehe morgen um acht Uhr auf.','phrase','فردا ساعت هشت بیدار می شوم.',55,'{"type":"phrase","focus":"sollte_and_sleep_routine"}','[{"text":"Ich muss heute arbeiten.","translation":"امروز باید کار کنم."},{"text":"Der Zug kommt später.","translation":"قطار دیرتر می آید."},{"text":"Das Fenster ist offen.","translation":"پنجره باز است."}]','Ich stehe morgen um acht Uhr auf.','فردا ساعت هشت بیدار می شوم.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":false}'); SET v_w_031=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_032 FROM words WHERE course_id=v_course AND lemma='ich' AND part_of_speech='pronoun' AND translation='من' ORDER BY id LIMIT 1;
  IF v_w_032 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: ich | pronoun'; END IF;
  SELECT id INTO v_w_033 FROM words WHERE course_id=v_course AND lemma='in' AND part_of_speech='preposition' AND translation='در / داخل' ORDER BY id LIMIT 1;
  IF v_w_033 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: in | preposition'; END IF;
  SELECT id INTO v_w_034 FROM words WHERE course_id=v_course AND lemma='Ja, damit ich besser schlafen kann.' AND part_of_speech='phrase' AND translation='بله، تا بتوانم بهتر بخوابم.' ORDER BY id LIMIT 1;
  IF v_w_034 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Ja, damit ich besser schlafen kann.','Ja, damit ich besser schlafen kann.','phrase','بله، تا بتوانم بهتر بخوابم.',55,'{"type":"phrase","focus":"sollte_and_sleep_routine"}','[{"text":"Ich muss heute arbeiten.","translation":"امروز باید کار کنم."},{"text":"Der Zug kommt später.","translation":"قطار دیرتر می آید."},{"text":"Das Fenster ist offen.","translation":"پنجره باز است."}]','Ja, damit ich besser schlafen kann.','بله، تا بتوانم بهتر بخوابم.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":false}'); SET v_w_034=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_035 FROM words WHERE course_id=v_course AND lemma='Ja, ich sollte mehr schlafen.' AND part_of_speech='phrase' AND translation='بله، باید بیشتر بخوابم.' ORDER BY id LIMIT 1;
  IF v_w_035 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Ja, ich sollte mehr schlafen.','Ja, ich sollte mehr schlafen.','phrase','بله، باید بیشتر بخوابم.',55,'{"type":"phrase","focus":"sollte_and_sleep_routine"}','[{"text":"Ich muss heute arbeiten.","translation":"امروز باید کار کنم."},{"text":"Der Zug kommt später.","translation":"قطار دیرتر می آید."},{"text":"Das Fenster ist offen.","translation":"پنجره باز است."}]','Ja, ich sollte mehr schlafen.','بله، باید بیشتر بخوابم.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":false}'); SET v_w_035=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_036 FROM words WHERE course_id=v_course AND lemma='ja' AND part_of_speech='interjection' AND translation='بله / آره' ORDER BY id LIMIT 1;
  IF v_w_036 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: ja | interjection'; END IF;
  SELECT id INTO v_w_037 FROM words WHERE course_id=v_course AND lemma='können' AND part_of_speech='verb' AND translation='توانستن / بتوان' ORDER BY id LIMIT 1;
  IF v_w_037 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: können | verb'; END IF;
  SELECT id INTO v_w_038 FROM words WHERE course_id=v_course AND lemma='machen' AND part_of_speech='verb' AND translation='انجام دادن' ORDER BY id LIMIT 1;
  IF v_w_038 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: machen | verb'; END IF;
  SELECT id INTO v_w_039 FROM words WHERE course_id=v_course AND lemma='mehr' AND part_of_speech='adverb' AND translation='دیگه / بیشتر' ORDER BY id LIMIT 1;
  IF v_w_039 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: mehr | adverb'; END IF;
  SELECT id INTO v_w_040 FROM words WHERE course_id=v_course AND lemma='mein' AND part_of_speech='determiner' AND translation='مال من / من' ORDER BY id LIMIT 1;
  IF v_w_040 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: mein | determiner'; END IF;
  SELECT id INTO v_w_041 FROM words WHERE course_id=v_course AND lemma='morgen' AND part_of_speech='adverb' AND translation='فردا' ORDER BY id LIMIT 1;
  IF v_w_041 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: morgen | adverb'; END IF;
  SELECT id INTO v_w_042 FROM words WHERE course_id=v_course AND lemma='müde' AND part_of_speech='adjective' AND translation='خسته' ORDER BY id LIMIT 1;
  IF v_w_042 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: müde | adjective'; END IF;
  SELECT id INTO v_w_043 FROM words WHERE course_id=v_course AND lemma='nein' AND part_of_speech='interjection' AND translation='نه' ORDER BY id LIMIT 1;
  IF v_w_043 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: nein | interjection'; END IF;
  SELECT id INTO v_w_044 FROM words WHERE course_id=v_course AND lemma='neu' AND part_of_speech='adjective' AND translation='جدید / تازه' ORDER BY id LIMIT 1;
  IF v_w_044 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: neu | adjective'; END IF;
  SELECT id INTO v_w_045 FROM words WHERE course_id=v_course AND lemma='nicht' AND part_of_speech='adverb' AND translation='نه / نیست' ORDER BY id LIMIT 1;
  IF v_w_045 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: nicht | adverb'; END IF;
  SELECT id INTO v_w_046 FROM words WHERE course_id=v_course AND lemma='oft' AND part_of_speech='adverb' AND translation='اغلب' ORDER BY id LIMIT 1;
  IF v_w_046 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: oft | adverb'; END IF;
  SELECT id INTO v_w_047 FROM words WHERE course_id=v_course AND lemma='Plan' AND part_of_speech='noun' AND translation='برنامه' ORDER BY id LIMIT 1;
  IF v_w_047 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Plan | noun'; END IF;
  SELECT id INTO v_w_048 FROM words WHERE course_id=v_course AND lemma='regelmäßig' AND part_of_speech='adverb' AND translation='به طور منظم' ORDER BY id LIMIT 1;
  IF v_w_048 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'regelmäßig','regelmäßig','adverb','به طور منظم',55,'{"type":"adverb"}','[{"text":"plötzlich","translation":"ناگهان"},{"text":"vielleicht","translation":"شاید"},{"text":"besonders","translation":"مخصوصا"}]','Ich will das regelmäßig machen.','می خواهم این کار را به طور منظم انجام بدهم.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":true}'); SET v_w_048=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_049 FROM words WHERE course_id=v_course AND lemma='Ruhe' AND part_of_speech='noun' AND translation='آرامش / سکوت' ORDER BY id LIMIT 1;
  IF v_w_049 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Ruhe | noun'; END IF;
  SELECT id INTO v_w_050 FROM words WHERE course_id=v_course AND lemma='Schlaf' AND part_of_speech='noun' AND translation='خواب' ORDER BY id LIMIT 1;
  IF v_w_050 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Schlaf | noun'; END IF;
  SELECT id INTO v_w_051 FROM words WHERE course_id=v_course AND lemma='schlafen' AND part_of_speech='verb' AND translation='خوابیدن' ORDER BY id LIMIT 1;
  IF v_w_051 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: schlafen | verb'; END IF;
  SELECT id INTO v_w_052 FROM words WHERE course_id=v_course AND lemma='sehen' AND part_of_speech='verb' AND translation='دیدن' ORDER BY id LIMIT 1;
  IF v_w_052 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sehen | verb'; END IF;
  SELECT id INTO v_w_053 FROM words WHERE course_id=v_course AND lemma='sein' AND part_of_speech='verb' AND translation='بودن' ORDER BY id LIMIT 1;
  IF v_w_053 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sein | verb'; END IF;
  SELECT id INTO v_w_054 FROM words WHERE course_id=v_course AND lemma='sollen' AND part_of_speech='verb' AND translation='باید / قرار است' ORDER BY id LIMIT 1;
  IF v_w_054 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sollen | verb'; END IF;
  SELECT id INTO v_w_055 FROM words WHERE course_id=v_course AND lemma='stören' AND part_of_speech='verb' AND translation='مزاحم بودن / اذیت کردن' ORDER BY id LIMIT 1;
  IF v_w_055 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: stören | verb'; END IF;
  SELECT id INTO v_w_056 FROM words WHERE course_id=v_course AND lemma='Stunde' AND part_of_speech='noun' AND translation='ساعت / یک ساعت' ORDER BY id LIMIT 1;
  IF v_w_056 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Stunde | noun'; END IF;
  SELECT id INTO v_w_057 FROM words WHERE course_id=v_course AND lemma='Uhr' AND part_of_speech='noun' AND translation='ساعت' ORDER BY id LIMIT 1;
  IF v_w_057 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Uhr | noun'; END IF;
  SELECT id INTO v_w_058 FROM words WHERE course_id=v_course AND lemma='um' AND part_of_speech='preposition' AND translation='در ساعت / حوالی' ORDER BY id LIMIT 1;
  IF v_w_058 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: um | preposition'; END IF;
  SELECT id INTO v_w_059 FROM words WHERE course_id=v_course AND lemma='und' AND part_of_speech='conjunction' AND translation='و' ORDER BY id LIMIT 1;
  IF v_w_059 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: und | conjunction'; END IF;
  SELECT id INTO v_w_060 FROM words WHERE course_id=v_course AND lemma='versuchen' AND part_of_speech='verb' AND translation='تلاش کردن / امتحان کردن' ORDER BY id LIMIT 1;
  IF v_w_060 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: versuchen | verb'; END IF;
  SELECT id INTO v_w_061 FROM words WHERE course_id=v_course AND lemma='viel' AND part_of_speech='determiner' AND translation='زیاد / مقدار زیاد' ORDER BY id LIMIT 1;
  IF v_w_061 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: viel | determiner'; END IF;
  SELECT id INTO v_w_062 FROM words WHERE course_id=v_course AND lemma='vielleicht' AND part_of_speech='adverb' AND translation='شاید' ORDER BY id LIMIT 1;
  IF v_w_062 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: vielleicht | adverb'; END IF;
  SELECT id INTO v_w_063 FROM words WHERE course_id=v_course AND lemma='vor' AND part_of_speech='preposition' AND translation='از / جلوی' ORDER BY id LIMIT 1;
  IF v_w_063 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: vor | preposition'; END IF;
  SELECT id INTO v_w_064 FROM words WHERE course_id=v_course AND lemma='wann' AND part_of_speech='adverb' AND translation='کی / چه زمانی' ORDER BY id LIMIT 1;
  IF v_w_064 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wann | adverb'; END IF;
  SELECT id INTO v_w_065 FROM words WHERE course_id=v_course AND lemma='was' AND part_of_speech='pronoun' AND translation='چی / چه' ORDER BY id LIMIT 1;
  IF v_w_065 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: was | pronoun'; END IF;
  SELECT id INTO v_w_066 FROM words WHERE course_id=v_course AND lemma='Wasser' AND part_of_speech='noun' AND translation='آب' ORDER BY id LIMIT 1;
  IF v_w_066 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Wasser | noun'; END IF;
  SELECT id INTO v_w_067 FROM words WHERE course_id=v_course AND lemma='weniger' AND part_of_speech='adverb' AND translation='کمتر' ORDER BY id LIMIT 1;
  IF v_w_067 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: weniger | adverb'; END IF;
  SELECT id INTO v_w_071 FROM words WHERE course_id=v_course AND lemma='Rhythmus' AND part_of_speech='noun' AND translation='ریتم / برنامه منظم' ORDER BY id LIMIT 1;
  IF v_w_071 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Rhythmus','Rhythmus','noun','ریتم / برنامه منظم',55,'{"type":"noun","gender":"der","plural":"Rhythmen"}','[{"text":"Plan","translation":"برنامه"},{"text":"Gewohnheit","translation":"عادت"},{"text":"Pause","translation":"استراحت"}]','Das ist mein neuer Rhythmus.','این برنامه منظم تازه من است.',NULL,NULL,'{"cefr":"B1","introducedInSeries":104,"wordAudioEligible":true}'); SET v_w_071=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_068 FROM words WHERE course_id=v_course AND lemma='wie' AND part_of_speech='adverb' AND translation='چطور / چگونه' ORDER BY id LIMIT 1;
  IF v_w_068 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wie | adverb'; END IF;
  SELECT id INTO v_w_069 FROM words WHERE course_id=v_course AND lemma='wollen' AND part_of_speech='verb' AND translation='خواستن' ORDER BY id LIMIT 1;
  IF v_w_069 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wollen | verb'; END IF;
  SELECT id INTO v_w_070 FROM words WHERE course_id=v_course AND lemma='zehn' AND part_of_speech='number' AND translation='ده' ORDER BY id LIMIT 1;
  IF v_w_070 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: zehn | number'; END IF;
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'Mehr Schlaf planen','برای خواب بیشتر برنامه ریختن','Sara und Mia planen eine längere Nacht und vergleichen Schlafdauer und Tagesrhythmus.','سارا و میا برای خواب طولانی تر برنامه می ریزند و مدت خواب و برنامه روزانه را مقایسه می کنند.','story','mia-sara-b1-health-routine',13,55,180,1,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"plan-more-sleep"}'); SET v_l_1=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_sara,1,'character','Hast du heute genug geschlafen?','امروز به اندازه کافی خوابیدی؟',55,NULL,NULL,NULL,NULL,'[{"surface":"Hast","lemma":"haben","translation":"داشتن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"heute","lemma":"heute","translation":"امروز","partOfSpeech":"adverb"},{"surface":"genug","lemma":"genug","translation":"کافی","partOfSpeech":"adverb"},{"surface":"geschlafen","lemma":"schlafen","translation":"خوابیدن","partOfSpeech":"verb","suffix":"?"}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_1=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_mia,2,'learner','Nein, ich habe nicht genug geschlafen.','نه، به اندازه کافی نخوابیدم.',55,NULL,NULL,'nein ich habe nicht genug geschlafen',NULL,'[{"surface":"Nein","lemma":"nein","translation":"نه","partOfSpeech":"interjection","suffix":","},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"habe","lemma":"haben","translation":"داشتن","partOfSpeech":"verb"},{"surface":"nicht","lemma":"nicht","translation":"نه / نیست","partOfSpeech":"adverb"},{"surface":"genug","lemma":"genug","translation":"کافی","partOfSpeech":"adverb"},{"surface":"geschlafen","lemma":"schlafen","translation":"خوابیدن","partOfSpeech":"verb","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_2=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_sara,3,'character','Dann solltest du heute früh ins Bett gehen.','پس بهتر است امروز زود به تخت بروی.',55,NULL,NULL,NULL,NULL,'[{"surface":"Dann","lemma":"dann","translation":"بعد / سپس","partOfSpeech":"adverb"},{"surface":"solltest","lemma":"sollen","translation":"باید / قرار است","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"heute","lemma":"heute","translation":"امروز","partOfSpeech":"adverb"},{"surface":"früh","lemma":"früh","translation":"زودتر","partOfSpeech":"adverb"},{"surface":"ins","lemma":"in","translation":"در / داخل","partOfSpeech":"preposition"},{"surface":"Bett","lemma":"Bett","translation":"تخت","partOfSpeech":"noun"},{"surface":"gehen","lemma":"gehen","translation":"رفتن","partOfSpeech":"verb","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_3=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_mia,4,'learner','Ja, ich sollte mehr schlafen.','بله، باید بیشتر بخوابم.',55,NULL,NULL,'ja ich sollte mehr schlafen',NULL,'[{"surface":"Ja","lemma":"ja","translation":"بله / آره","partOfSpeech":"interjection","suffix":","},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"sollte","lemma":"sollen","translation":"باید / قرار است","partOfSpeech":"verb"},{"surface":"mehr","lemma":"mehr","translation":"دیگه / بیشتر","partOfSpeech":"adverb"},{"surface":"schlafen","lemma":"schlafen","translation":"خوابیدن","partOfSpeech":"verb","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_4=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_sara,5,'character','Wie viel Schlaf brauchst du?','چقدر خواب لازم داری؟',55,NULL,NULL,NULL,NULL,'[{"surface":"Wie","lemma":"wie","translation":"چطور / چگونه","partOfSpeech":"adverb"},{"surface":"viel","lemma":"viel","translation":"زیاد / مقدار زیاد","partOfSpeech":"determiner"},{"surface":"Schlaf","lemma":"Schlaf","translation":"خواب","partOfSpeech":"noun"},{"surface":"brauchst","lemma":"brauchen","translation":"نیاز داشتن / لازم داشتن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun","suffix":"?"}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_5=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_mia,6,'learner','Ich brauche acht Stunden Schlaf.','من به هشت ساعت خواب نیاز دارم.',55,NULL,NULL,'ich brauche acht stunden schlaf',NULL,'[{"surface":"Ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"brauche","lemma":"brauchen","translation":"نیاز داشتن / لازم داشتن","partOfSpeech":"verb"},{"surface":"acht","lemma":"acht","translation":"هشت","partOfSpeech":"number"},{"surface":"Stunden","lemma":"Stunde","translation":"ساعت / یک ساعت","partOfSpeech":"noun"},{"surface":"Schlaf","lemma":"Schlaf","translation":"خواب","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_6=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_027,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_018,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_030,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_024,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_051,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_043,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_032,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_045,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_014,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_054,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_022,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_033,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_008,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_023,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_036,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_039,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_068,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_061,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_050,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_011,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_002,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_056,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_035,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'new_word',1,NULL,v_w_035,'عبارت کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'new_word',2,NULL,v_w_025,'واژهٔ کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'listen',3,v_t_1,NULL,'به جملهٔ سارا گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'speak',4,v_t_2,NULL,'پاسخ میا را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'listen',5,v_t_5,NULL,'به جملهٔ بعدی گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'speak',6,v_t_6,NULL,'پاسخ را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'meaning_choice',7,NULL,v_w_025,'معنی واژهٔ کلیدی را انتخاب کن',NULL,55,'{"mode":"word_translation","question":"Gewohnheit در این درس چه معنی دارد؟","choices":["عادت","سفر مستقیم","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,55,'{"source":"lesson_story","question":"میا امشب چه تصمیمی می گیرد؟","choices":["بیشتر بخوابد","بیشتر کار کند","به سفر برود"],"correctIndex":0}','{"cefr":"B1","series":104}');
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'Das Handy am Abend','گوشی در شب','Mia erkennt, wie der Bildschirm ihren Schlaf stört, und entscheidet sich für eine frühere Handy-Pause.','میا متوجه می شود صفحه نمایش چطور خوابش را مختل می کند و تصمیم می گیرد گوشی را زودتر کنار بگذارد.','story','mia-sara-b1-health-routine',14,55,180,2,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"reduce-evening-screen"}'); SET v_l_2=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_sara,1,'character','Was machst du am Abend?','شب ها چه کار می کنی؟',55,NULL,NULL,NULL,NULL,'[{"surface":"Was","lemma":"was","translation":"چی / چه","partOfSpeech":"pronoun"},{"surface":"machst","lemma":"machen","translation":"انجام دادن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"am","lemma":"an","translation":"در / در روز","partOfSpeech":"preposition"},{"surface":"Abend","lemma":"Abend","translation":"عصر / شب","partOfSpeech":"noun","suffix":"?"}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_7=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_mia,2,'learner','Ich sehe oft auf mein Handy.','اغلب به گوشی ام نگاه می کنم.',55,NULL,NULL,'ich sehe oft auf mein handy',NULL,'[{"surface":"Ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"sehe","lemma":"sehen","translation":"دیدن","partOfSpeech":"verb"},{"surface":"oft","lemma":"oft","translation":"اغلب","partOfSpeech":"adverb"},{"surface":"auf","lemma":"auf","translation":"روی / برای","partOfSpeech":"preposition"},{"surface":"mein","lemma":"mein","translation":"مال من / من","partOfSpeech":"determiner"},{"surface":"Handy","lemma":"Handy","translation":"گوشی","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_8=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_sara,3,'character','Der Bildschirm stört deinen Schlaf.','صفحه نمایش خواب تو را مختل می کند.',55,NULL,NULL,NULL,NULL,'[{"surface":"Der","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Bildschirm","lemma":"Bildschirm","translation":"صفحه نمایش","partOfSpeech":"noun"},{"surface":"stört","lemma":"stören","translation":"مزاحم بودن / اذیت کردن","partOfSpeech":"verb"},{"surface":"deinen","lemma":"dein","translation":"مال تو / تو","partOfSpeech":"determiner"},{"surface":"Schlaf","lemma":"Schlaf","translation":"خواب","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_9=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_mia,4,'learner','Dann sollte ich das Handy früher ausschalten.','پس باید گوشی را زودتر خاموش کنم.',55,NULL,NULL,'dann sollte ich das handy früher ausschalten',NULL,'[{"surface":"Dann","lemma":"dann","translation":"بعد / سپس","partOfSpeech":"adverb"},{"surface":"sollte","lemma":"sollen","translation":"باید / قرار است","partOfSpeech":"verb"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"das","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Handy","lemma":"Handy","translation":"گوشی","partOfSpeech":"noun"},{"surface":"früher","lemma":"früh","translation":"زودتر","partOfSpeech":"adverb"},{"surface":"ausschalten","lemma":"ausschalten","translation":"خاموش کردن","partOfSpeech":"verb","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_10=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_sara,5,'character','Das ist ein einfacher Plan.','این یک برنامه ساده است.',55,NULL,NULL,NULL,NULL,'[{"surface":"Das","lemma":"das","translation":"این / آن","partOfSpeech":"pronoun"},{"surface":"ist","lemma":"sein","translation":"بودن","partOfSpeech":"verb"},{"surface":"ein","lemma":"ein","translation":"یک / حرف تعریف نامعین","partOfSpeech":"article"},{"surface":"einfacher","lemma":"einfach","translation":"آسان / ساده","partOfSpeech":"adjective"},{"surface":"Plan","lemma":"Plan","translation":"برنامه","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_11=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_mia,6,'learner','Ich versuche das heute Abend.','امشب این کار را امتحان می کنم.',55,NULL,NULL,'ich versuche das heute abend',NULL,'[{"surface":"Ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"versuche","lemma":"versuchen","translation":"تلاش کردن / امتحان کردن","partOfSpeech":"verb"},{"surface":"das","lemma":"das","translation":"این / آن","partOfSpeech":"pronoun"},{"surface":"heute","lemma":"heute","translation":"امروز","partOfSpeech":"adverb"},{"surface":"Abend","lemma":"Abend","translation":"عصر / شب","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_12=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_065,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_038,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_018,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_003,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_001,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_032,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_052,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_046,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_004,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_040,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_028,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_017,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_009,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_055,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_016,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_050,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_014,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_054,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_022,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_006,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_015,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_053,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_019,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_020,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_047,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_060,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_030,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_013,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'new_word',1,NULL,v_w_013,'عبارت کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'new_word',2,NULL,v_w_009,'واژهٔ کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'listen',3,v_t_7,NULL,'به جملهٔ سارا گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'speak',4,v_t_8,NULL,'پاسخ میا را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'listen',5,v_t_11,NULL,'به جملهٔ بعدی گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'speak',6,v_t_12,NULL,'پاسخ را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'meaning_choice',7,NULL,v_w_009,'معنی واژهٔ کلیدی را انتخاب کن',NULL,55,'{"mode":"word_translation","question":"Bildschirm در این درس چه معنی دارد؟","choices":["صفحه نمایش","سفر مستقیم","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,55,'{"source":"lesson_story","question":"میا درباره گوشی چه تصمیمی می گیرد؟","choices":["زودتر خاموشش کند","گوشی تازه بخرد","با آن تماس بگیرد"],"correctIndex":0}','{"cefr":"B1","series":104}');
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'Ein fester Rhythmus','یک برنامه ثابت','Mia legt feste Schlaf- und Aufstehzeiten fest und macht daraus eine regelmäßige Gewohnheit.','میا زمان مشخصی برای خواب و بیدار شدن تعیین می کند و آن را به یک عادت منظم تبدیل می کند.','story','mia-sara-b1-health-routine',15,55,180,3,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"set-sleep-rhythm"}'); SET v_l_3=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_sara,1,'character','Wann willst du ins Bett gehen?','کی می خواهی به تخت بروی؟',55,NULL,NULL,NULL,NULL,'[{"surface":"Wann","lemma":"wann","translation":"کی / چه زمانی","partOfSpeech":"adverb"},{"surface":"willst","lemma":"wollen","translation":"خواستن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"ins","lemma":"in","translation":"در / داخل","partOfSpeech":"preposition"},{"surface":"Bett","lemma":"Bett","translation":"تخت","partOfSpeech":"noun"},{"surface":"gehen","lemma":"gehen","translation":"رفتن","partOfSpeech":"verb","suffix":"?"}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_13=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_mia,2,'learner','Heute gehe ich um zehn Uhr ins Bett.','امشب ساعت ده به تخت می روم.',55,NULL,NULL,'heute gehe ich um zehn uhr ins bett',NULL,'[{"surface":"Heute","lemma":"heute","translation":"امروز","partOfSpeech":"adverb"},{"surface":"gehe","lemma":"gehen","translation":"رفتن","partOfSpeech":"verb"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"um","lemma":"um","translation":"در ساعت / حوالی","partOfSpeech":"preposition"},{"surface":"zehn","lemma":"zehn","translation":"ده","partOfSpeech":"number"},{"surface":"Uhr","lemma":"Uhr","translation":"ساعت","partOfSpeech":"noun"},{"surface":"ins","lemma":"in","translation":"در / داخل","partOfSpeech":"preposition"},{"surface":"Bett","lemma":"Bett","translation":"تخت","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_14=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_sara,3,'character','Und wann stehst du morgen auf?','و فردا کی از خواب بلند می شوی؟',55,NULL,NULL,NULL,NULL,'[{"surface":"Und","lemma":"und","translation":"و","partOfSpeech":"conjunction"},{"surface":"wann","lemma":"wann","translation":"کی / چه زمانی","partOfSpeech":"adverb"},{"surface":"stehst","lemma":"aufstehen","translation":"از خواب بلند شدن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"morgen","lemma":"morgen","translation":"فردا","partOfSpeech":"adverb"},{"surface":"auf","lemma":"aufstehen","translation":"از خواب بلند شدن","partOfSpeech":"verb","suffix":"?"}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_15=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_mia,4,'learner','Ich stehe morgen um acht Uhr auf.','فردا ساعت هشت بیدار می شوم.',55,NULL,NULL,'ich stehe morgen um acht uhr auf',NULL,'[{"surface":"Ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"stehe","lemma":"aufstehen","translation":"از خواب بلند شدن","partOfSpeech":"verb"},{"surface":"morgen","lemma":"morgen","translation":"فردا","partOfSpeech":"adverb"},{"surface":"um","lemma":"um","translation":"در ساعت / حوالی","partOfSpeech":"preposition"},{"surface":"acht","lemma":"acht","translation":"هشت","partOfSpeech":"number"},{"surface":"Uhr","lemma":"Uhr","translation":"ساعت","partOfSpeech":"noun"},{"surface":"auf","lemma":"aufstehen","translation":"از خواب بلند شدن","partOfSpeech":"verb","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_16=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_sara,5,'character','Das ist eine gute Gewohnheit.','این یک عادت خوب است.',55,NULL,NULL,NULL,NULL,'[{"surface":"Das","lemma":"das","translation":"این / آن","partOfSpeech":"pronoun"},{"surface":"ist","lemma":"sein","translation":"بودن","partOfSpeech":"verb"},{"surface":"eine","lemma":"ein","translation":"یک / حرف تعریف نامعین","partOfSpeech":"article"},{"surface":"gute","lemma":"gut","translation":"خوب","partOfSpeech":"adjective"},{"surface":"Gewohnheit","lemma":"Gewohnheit","translation":"عادت","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_17=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_mia,6,'learner','Ich will das regelmäßig machen.','می خواهم این کار را به طور منظم انجام بدهم.',55,NULL,NULL,'ich will das regelmäßig machen',NULL,'[{"surface":"Ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"will","lemma":"wollen","translation":"خواستن","partOfSpeech":"verb"},{"surface":"das","lemma":"das","translation":"این / آن","partOfSpeech":"pronoun"},{"surface":"regelmäßig","lemma":"regelmäßig","translation":"به طور منظم","partOfSpeech":"adverb"},{"surface":"machen","lemma":"machen","translation":"انجام دادن","partOfSpeech":"verb","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_18=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_064,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_069,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_018,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_033,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_008,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_023,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_030,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_032,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_058,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_070,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_057,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_059,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_005,'review',0,4);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_041,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_002,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_015,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_053,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_019,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_026,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_025,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_048,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_038,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_031,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'new_word',1,NULL,v_w_031,'عبارت کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'new_word',2,NULL,v_w_048,'واژهٔ کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'listen',3,v_t_13,NULL,'به جملهٔ سارا گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'speak',4,v_t_14,NULL,'پاسخ میا را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'listen',5,v_t_17,NULL,'به جملهٔ بعدی گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'speak',6,v_t_18,NULL,'پاسخ را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'meaning_choice',7,NULL,v_w_048,'معنی واژهٔ کلیدی را انتخاب کن',NULL,55,'{"mode":"word_translation","question":"regelmäßig در این درس چه معنی دارد؟","choices":["به طور منظم","سفر مستقیم","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,55,'{"source":"lesson_story","question":"میا فردا چه ساعتی بیدار می شود؟","choices":["ساعت هشت","ساعت ده","بعدازظهر"],"correctIndex":0}','{"cefr":"B1","series":104}');
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'Der neue Abendplan','برنامه تازه شب','Sara und Mia schließen den Gesundheitsbogen mit einer ruhigen Abendroutine und einem klaren persönlichen Plan ab.','سارا و میا مسیر سلامتی را با یک برنامه آرام شبانه و یک تصمیم شخصی روشن به پایان می رسانند.','story','mia-sara-b1-health-routine',16,55,180,4,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"commit-evening-plan"}'); SET v_l_4=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_sara,1,'character','Was hilft dir vor dem Schlafen?','پیش از خواب چه چیزی به تو کمک می کند؟',55,NULL,NULL,NULL,NULL,'[{"surface":"Was","lemma":"was","translation":"چی / چه","partOfSpeech":"pronoun"},{"surface":"hilft","lemma":"helfen","translation":"کمک کردن","partOfSpeech":"verb"},{"surface":"dir","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"vor","lemma":"vor","translation":"از / جلوی","partOfSpeech":"preposition"},{"surface":"dem","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Schlafen","lemma":"schlafen","translation":"خوابیدن","partOfSpeech":"verb","suffix":"?"}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_19=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_mia,2,'learner','Etwas Ruhe und ein bisschen Wasser.','کمی آرامش و کمی آب.',55,NULL,NULL,'etwas ruhe und ein bisschen wasser',NULL,'[{"surface":"Etwas","lemma":"etwas","translation":"چیزی / یک چیزی","partOfSpeech":"pronoun"},{"surface":"Ruhe","lemma":"Ruhe","translation":"آرامش / سکوت","partOfSpeech":"noun"},{"surface":"und","lemma":"und","translation":"و","partOfSpeech":"conjunction"},{"surface":"ein","lemma":"ein","translation":"یک / حرف تعریف نامعین","partOfSpeech":"article"},{"surface":"bisschen","lemma":"bisschen","translation":"کمی","partOfSpeech":"noun"},{"surface":"Wasser","lemma":"Wasser","translation":"آب","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_20=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_sara,3,'character','Willst du weniger auf dein Handy sehen?','می خواهی کمتر به گوشی ات نگاه کنی؟',55,NULL,NULL,NULL,NULL,'[{"surface":"Willst","lemma":"wollen","translation":"خواستن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"weniger","lemma":"weniger","translation":"کمتر","partOfSpeech":"adverb"},{"surface":"auf","lemma":"auf","translation":"روی / برای","partOfSpeech":"preposition"},{"surface":"dein","lemma":"dein","translation":"مال تو / تو","partOfSpeech":"determiner"},{"surface":"Handy","lemma":"Handy","translation":"گوشی","partOfSpeech":"noun"},{"surface":"sehen","lemma":"sehen","translation":"دیدن","partOfSpeech":"verb","suffix":"?"}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_21=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_mia,4,'learner','Ja, damit ich besser schlafen kann.','بله، تا بتوانم بهتر بخوابم.',55,NULL,NULL,'ja damit ich besser schlafen kann',NULL,'[{"surface":"Ja","lemma":"ja","translation":"بله / آره","partOfSpeech":"interjection","suffix":","},{"surface":"damit","lemma":"damit","translation":"تا / برای اینکه","partOfSpeech":"conjunction"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"besser","lemma":"besser","translation":"بهتر","partOfSpeech":"adverb"},{"surface":"schlafen","lemma":"schlafen","translation":"خوابیدن","partOfSpeech":"verb"},{"surface":"kann","lemma":"können","translation":"توانستن / بتوان","partOfSpeech":"verb","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_22=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_sara,5,'character','Dann bist du morgen vielleicht weniger müde.','پس شاید فردا کمتر خسته باشی.',55,NULL,NULL,NULL,NULL,'[{"surface":"Dann","lemma":"dann","translation":"بعد / سپس","partOfSpeech":"adverb"},{"surface":"bist","lemma":"sein","translation":"بودن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"morgen","lemma":"morgen","translation":"فردا","partOfSpeech":"adverb"},{"surface":"vielleicht","lemma":"vielleicht","translation":"شاید","partOfSpeech":"adverb"},{"surface":"weniger","lemma":"weniger","translation":"کمتر","partOfSpeech":"adverb"},{"surface":"müde","lemma":"müde","translation":"خسته","partOfSpeech":"adjective","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_23=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_mia,6,'learner','Das ist mein neuer Rhythmus.','این برنامه منظم تازه من است.',55,NULL,NULL,'das ist mein neuer rhythmus',NULL,'[{"surface":"Das","lemma":"das","translation":"این / آن","partOfSpeech":"pronoun"},{"surface":"ist","lemma":"sein","translation":"بودن","partOfSpeech":"verb"},{"surface":"mein","lemma":"mein","translation":"مال من / من","partOfSpeech":"determiner"},{"surface":"neuer","lemma":"neu","translation":"جدید / تازه","partOfSpeech":"adjective"},{"surface":"Rhythmus","lemma":"Rhythmus","translation":"ریتم / برنامه منظم","partOfSpeech":"noun","suffix":"."}]','Mit sollte über gesunde Gewohnheiten sprechen','با sollte توصیه یا تصمیم ملایم بیان می‌شود. قیدهای زمان و مقدار برنامهٔ خواب را دقیق‌تر می‌کنند.','{"focus":"sollte_sleep_routine","structures":["sollte recommendation","time expressions","separable aufstehen","damit purpose clause"]}','{"cefr":"B1","course":"de-fa","series":104}'); SET v_t_24=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_065,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_029,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_018,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_063,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_017,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_051,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_021,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_049,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_059,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_019,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_010,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_066,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_069,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_067,'new',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_004,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_016,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_028,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_052,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_036,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_012,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_032,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_007,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_037,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_014,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_053,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_041,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_062,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_042,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_015,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_040,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_044,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_071,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_034,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'new_word',1,NULL,v_w_034,'عبارت کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'new_word',2,NULL,v_w_071,'واژهٔ کلیدی درس',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'listen',3,v_t_19,NULL,'به جملهٔ سارا گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'speak',4,v_t_20,NULL,'پاسخ میا را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'listen',5,v_t_23,NULL,'به جملهٔ بعدی گوش کن',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'speak',6,v_t_24,NULL,'پاسخ را با صدای بلند بگو',NULL,55,NULL,'{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'meaning_choice',7,NULL,v_w_067,'معنی واژهٔ کلیدی را انتخاب کن',NULL,55,'{"mode":"word_translation","question":"Rhythmus در این درس چه معنی دارد؟","choices":["ریتم / برنامه منظم","سفر مستقیم","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":104}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,55,'{"source":"lesson_story","question":"هدف برنامه تازه میا چیست؟","choices":["بهتر خوابیدن","دیرتر بیدار شدن","کمتر آب خوردن"],"correctIndex":0}','{"cefr":"B1","series":104}');
  SELECT COUNT(*) INTO v_count FROM lessons WHERE chapter_id=v_chapter; IF v_count<>4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 104 requires four lessons.'; END IF;
  SELECT COUNT(*) INTO v_count FROM turns t JOIN lessons l ON l.id=t.lesson_id WHERE l.chapter_id=v_chapter; IF v_count<>24 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 104 requires 24 turns.'; END IF;
  SELECT COUNT(*) INTO v_count FROM turns t JOIN lessons l ON l.id=t.lesson_id WHERE l.chapter_id=v_chapter AND t.role='learner' AND (t.speech_target IS NULL OR CHAR_LENGTH(TRIM(t.speech_target))=0); IF v_count<>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Every learner Turn needs speech_target.'; END IF;
  SELECT COUNT(*) INTO v_count FROM activities a JOIN lessons l ON l.id=a.lesson_id WHERE l.chapter_id=v_chapter; IF v_count<>32 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 104 requires 32 activities.'; END IF;
  SELECT COUNT(*) INTO v_count FROM lessons WHERE chapter_id=v_chapter AND prompt_character_id<>learner_character_id AND storyline_key='mia-sara-b1-health-routine' AND storyline_order BETWEEN 13 AND 16 AND status='validated'; IF v_count<>4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Continuity failure.'; END IF;
  SELECT COUNT(*) INTO v_count FROM (SELECT lw.lesson_id,lw.word_id,COUNT(*) n FROM lesson_words lw JOIN lessons l ON l.id=lw.lesson_id WHERE l.chapter_id=v_chapter GROUP BY lw.lesson_id,lw.word_id HAVING COUNT(*)>1)d; IF v_count<>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Duplicate lesson_words tuple.'; END IF;
  UPDATE chapters SET planned_lesson_count=4,status='validated' WHERE id=v_chapter; COMMIT;
END$$
DELIMITER ;
CALL import_nova_series_104_v9();
DROP PROCEDURE IF EXISTS import_nova_series_104_v9;
