#!/usr/bin/env python3
from scripts.generate_c1_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=41, slug="c1-metaphor-idiom", topic="simple-messages", title="Metaphor & Idiom",
    vocab=[V("metaphor","metaphor","استعاره"),V("idiom","idiom","اصطلاح"),V("figurative","figurative","مجازی","adjective"),V("literal","literal","تحت‌اللفظی","adjective"),V("connotation","connotation","بار معنایی"),V("image","image","تصویر ذهنی"),V("convey","convey","منتقل کردن","verb"),V("conventional","conventional","رایج / تثبیت‌شده","adjective")],
    utterances=[
        U("metaphor","Calling the proposal a 'bridge' frames it as a temporary connection between positions rather than a final destination.","وقتی پیشنهاد رو «پل» می‌نامیم، به‌عنوان اتصال موقت بین دو موضع قاب‌بندی می‌شه نه مقصد نهایی.","interpret_metaphor",["metaphor","image","convey"],1),
        U("idiom","The idiom makes sense only if you recognize the conventional meaning rather than translating each word literally.","اصطلاح فقط وقتی معنا می‌ده که معنی رایجش رو بشناسی، نه اینکه هر کلمه رو تحت‌اللفظی ترجمه کنی.","interpret_idiom",["idiom","conventional","literal"],1),
        U("connotation","The two expressions refer to the same basic action, but one carries a much more negative connotation.","دو عبارت به یک کار پایه اشاره می‌کنن، ولی یکی بار معنایی خیلی منفی‌تری داره.","compare_connotation",["connotation","figurative"],2),
        U("figurative","The sentence is figurative: nobody is literally 'holding the door open'; the speaker means preserving an option.","جمله مجازیه؛ کسی واقعاً «در رو باز نگه نداشته»، منظور حفظ یک گزینه‌ست.","distinguish_literal_figurative",["figurative","literal"],2),
        U("image","A fresh metaphor can make an abstract idea memorable, but too many competing images can make an explanation harder to follow.","استعاره تازه می‌تونه ایده انتزاعی رو ماندگار کنه، ولی تصویرهای رقیب زیاد توضیح رو سخت‌تر می‌کنن.","evaluate_metaphor_use",["metaphor","image"],3),
        U("culture","Some idioms travel easily across cultures because the underlying image is familiar; others lose the point entirely.","بعضی اصطلاح‌ها بین فرهنگ‌ها راحت منتقل می‌شن چون تصویر پایه آشناست؛ بعضی‌ها کل معنی رو از دست می‌دن.","discuss_idiom_transfer",["idiom","image"],3),
        U("convey","In this context, 'walking a tightrope' conveys the difficulty of balancing two risks at the same time.","در این زمینه «راه رفتن روی طناب» سختی متعادل کردن هم‌زمان دو ریسک رو منتقل می‌کنه.","explain_conveyed_meaning",["convey","metaphor"],3),
        U("close","Understanding figurative language at C1 means noticing the stance and connotations it adds, not merely decoding the basic meaning.","فهم زبان مجازی در C1 یعنی موضع و بار معنایی اضافه‌شده رو هم ببینی، نه اینکه فقط معنی پایه رو رمزگشایی کنی.","summarize_figurative_language",["figurative","connotation"],3),
    ], grammar=["reformulation","register_shift","cohesion_reference"], fill=["The phrase is ___ rather than literal; it describes keeping an option available.",["figurative","conventional","connotation","idiom"],"figurative"]),

make_spec(index=42, slug="c1-register-shifting", topic="polite-language", title="Register Shifting",
    vocab=[V("register","register","سطح رسمیت زبان"),V("formal","formal","رسمی","adjective"),V("informal","informal","خودمانی","adjective"),V("concise","concise","مختصر","adjective"),V("direct","direct","مستقیم","adjective"),V("deferential","deferential","احترام‌آمیز و ملاحظه‌کار","adjective"),V("adapt","adapt","سازگار کردن","verb"),V("audience","audience","مخاطب")],
    utterances=[
        U("register","The content can remain the same while the register changes substantially depending on the relationship and purpose.","محتوا می‌تونه همون بمونه ولی سطح رسمیت بسته به رابطه و هدف خیلی تغییر کنه.","explain_register",["register","audience"],1),
        U("direct","With a close colleague, 'Can you fix this today?' may be appropriately direct; with a new client, it may sound abrupt.","با همکار نزدیک «می‌تونی امروز درستش کنی؟» می‌تونه مستقیم و مناسب باشه؛ با مشتری جدید شاید تند به نظر بیاد.","compare_directness",["direct","audience"],1),
        U("formal","In a formal complaint, I would make the requested action explicit while avoiding emotional language that weakens the case.","در شکایت رسمی، اقدام درخواستی رو صریح می‌کنم و از زبان احساسی که پرونده رو ضعیف می‌کنه دوری می‌کنم.","use_formal_register",["formal","concise"],2),
        U("informal","An informal message can be concise and warm without becoming vague about what is actually needed.","پیام خودمانی می‌تونه کوتاه و گرم باشه بدون اینکه درباره نیاز واقعی مبهم بشه.","use_informal_register",["informal","concise"],2),
        U("deferential","A more deferential style may be appropriate when challenging someone with greater institutional authority, but it should not obscure the point.","وقتی فردی با قدرت سازمانی بیشتر رو به چالش می‌کشیم لحن ملاحظه‌کارتر مناسبه، ولی نباید اصل حرف رو مبهم کنه.","use_deference",["deferential","direct"],3),
        U("adapt","Strong communicators adapt register without sounding like a different person in every context.","ارتباط‌گرهای قوی سطح رسمیت رو سازگار می‌کنن بدون اینکه در هر زمینه مثل یک آدم کاملاً متفاوت به نظر بیان.","adapt_register",["adapt","register"],3),
        U("rewrite","I would rewrite the sentence for the audience, not merely replace casual words with longer formal ones.","جمله رو برای مخاطب بازنویسی می‌کنم، نه اینکه فقط کلمه‌های خودمانی رو با واژه‌های رسمی طولانی عوض کنم.","adapt_to_audience",["audience","formal"],3),
        U("close","Register is ultimately a strategic choice about distance, clarity, respect, and shared expectations.","سطح رسمیت در نهایت یک انتخاب راهبردی درباره فاصله، شفافیت، احترام و انتظارهای مشترکه.","summarize_register",["register","audience"],3),
    ], grammar=["register_shift","diplomatic_language","ellipsis_substitution"], fill=["Good communicators ___ their register to the audience and purpose.",["adapt","defer","convey","corroborate"],"adapt"]),

make_spec(index=43, slug="c1-mediating-perspectives", topic="requests", title="Mediating Perspectives",
    vocab=[V("mediate","mediate","میانجی‌گری کردن","verb"),V("perspective","perspective","دیدگاه"),V("common_ground","common ground","زمینه مشترک","noun_phrase"),V("reframe","reframe","بازقاب‌بندی کردن","verb"),V("misrepresent","misrepresent","تحریف کردن","verb"),V("interest","interest","منفعت / دغدغه"),V("position","position","موضع"),V("bridge","bridge","پل زدن / نزدیک کردن","verb")],
    utterances=[
        U("position","The two positions sound incompatible because each side is arguing from its preferred solution rather than its underlying interest.","دو موضع ناسازگار به نظر می‌رسن چون هر طرف از راه‌حل ترجیحی خودش حرف می‌زنه نه دغدغه زیرینش.","separate_position_interest",["position","interest","perspective"],1),
        U("mediate","To mediate fairly, I need to restate each perspective in terms the other side would recognize as accurate.","برای میانجی‌گری منصفانه باید هر دیدگاه رو طوری بازگو کنم که طرف مقابل هم اون رو توصیف دقیقی بدونه.","mediate_fairly",["mediate","perspective","misrepresent"],1),
        U("common","There is common ground on reliability and cost; the disagreement is mainly about which risk deserves priority.","روی قابلیت اتکا و هزینه زمینه مشترک هست؛ اختلاف اصلی درباره اینه که کدوم ریسک اولویت داره.","identify_common_ground",["common_ground","interest"],2),
        U("reframe","I would reframe the conflict from 'central control versus local freedom' to 'where consistency matters and where flexibility adds value.'", "اختلاف رو از «کنترل مرکزی در برابر آزادی محلی» به «کجا یکدستی مهمه و کجا انعطاف ارزش اضافه می‌کنه» بازقاب‌بندی می‌کنم.","reframe_disagreement",["reframe","position"],2),
        U("misrep","A mediator loses trust quickly by simplifying one side's argument until it becomes easier to dismiss.","میانجی وقتی استدلال یک طرف رو اون‌قدر ساده کنه که رد کردنش راحت بشه خیلی سریع اعتماد رو از دست می‌ده.","avoid_misrepresentation",["mediate","misrepresent"],3),
        U("bridge","A temporary pilot may bridge the perspectives because it gives one side evidence and the other side a limit on commitment.","اجرای آزمایشی موقت شاید بین دیدگاه‌ها پل بزنه چون به یک طرف شواهد می‌ده و برای طرف دیگه تعهد رو محدود می‌کنه.","bridge_perspectives",["bridge","perspective"],3),
        U("interest2","Once the underlying interests are visible, the negotiation has more options than the original yes-or-no positions suggested.","وقتی دغدغه‌های زیرین روشن می‌شن، مذاکره گزینه‌های بیشتری از موضع‌های اولیه بله یا نه پیدا می‌کنه.","expand_options",["interest","position"],3),
        U("close","Successful mediation does not require identical views; it requires enough shared understanding to make a workable decision.","میانجی‌گری موفق نیاز به دیدگاه یکسان نداره؛ نیاز به درک مشترک کافی برای تصمیم عملی داره.","summarize_mediation",["mediate","common_ground"],3),
    ], grammar=["reformulation","diplomatic_language","concession_rebuttal"], fill=["A mediator should identify underlying interests rather than repeat fixed ___.",["positions","perspectives","bridges","grounds"],"positions"]),

make_spec(index=44, slug="c1-multisource-problem-solving", topic="questions", title="Multi-source Problem Solving",
    vocab=[V("constraint","constraint","محدودیت"),V("source","source","منبع"),V("synthesize","synthesize","ترکیب تحلیلی کردن","verb"),V("conflict","conflict","تعارض"),V("priority","priority","اولویت"),V("scenario","scenario","سناریو"),V("assumption","assumption","فرض"),V("recommendation","recommendation","توصیه")],
    utterances=[
        U("sources","No single source contains the full problem: the customer data show impact, the technical report shows cause, and the budget sets the constraint.","هیچ منبعی کل مسئله رو نداره: داده مشتری اثر رو نشون می‌ده، گزارش فنی علت رو و بودجه محدودیت رو.","map_sources",["source","constraint"],1),
        U("conflict","The sources conflict on timing, so I would not build the recommendation around a deadline that only one source supports.","منابع درباره زمان‌بندی تعارض دارن، پس توصیه رو حول موعدی که فقط یک منبع تأیید می‌کنه نمی‌سازم.","handle_source_conflict",["conflict","source","recommendation"],1),
        U("synth","Synthesizing the evidence reveals that the cheapest option solves the technical fault but leaves the highest-impact customer problem unresolved.","ترکیب شواهد نشون می‌ده ارزان‌ترین گزینه مشکل فنی رو حل می‌کنه ولی مهم‌ترین مشکل مشتری رو باز می‌ذاره.","synthesize_problem",["synthesize","priority"],2),
        U("assumption","The proposed plan assumes demand will remain stable; if that assumption fails, the capacity calculation changes completely.","برنامه پیشنهادی فرض می‌کنه تقاضا ثابت می‌مونه؛ اگر این فرض غلط باشه محاسبه ظرفیت کامل عوض می‌شه.","test_assumption",["assumption","scenario"],2),
        U("scenario","I would compare a base scenario with one credible downside scenario rather than model every imaginable outcome.","یک سناریوی پایه رو با یک سناریوی منفی معتبر مقایسه می‌کنم، نه اینکه هر نتیجه قابل تصور رو مدل کنم.","compare_scenarios",["scenario","constraint"],3),
        U("priority","The priority should be the failure mode with the greatest combined impact and likelihood, not the most visible complaint.","اولویت باید حالتی باشه که ترکیب اثر و احتمال بالاتری داره، نه پرصداترین شکایت.","set_problem_priority",["priority","recommendation"],3),
        U("recommend","My recommendation is conditional: proceed with the faster option only if the supplier confirms the fallback capacity in writing.","توصیه من مشروطه: فقط وقتی با گزینه سریع‌تر جلو بریم که تأمین‌کننده ظرفیت پشتیبان رو کتبی تأیید کنه.","make_conditional_recommendation",["recommendation","constraint"],3),
        U("close","The solution is credible because each major decision can be traced back to evidence, a stated assumption, or an explicit constraint.","راه‌حل معتبره چون هر تصمیم اصلی رو می‌شه به شواهد، فرض بیان‌شده یا محدودیت صریح برگردوند.","justify_solution",["source","assumption","constraint"],3),
    ], grammar=["discourse_management","mixed_conditionals","advanced_reporting"], fill=["The plan depends on an ___ about future demand that should be tested.",["assumption","source","priority","conflict"],"assumption"]),

make_spec(index=45, slug="c1-integrated-capstone", topic="simple-messages", title="Integrated C1 Capstone",
    vocab=[V("synthesize","synthesize","ترکیب و جمع‌بندی تحلیلی کردن","verb"),V("mediate","mediate","میانجی‌گری کردن","verb"),V("qualify","qualify","دقیق و مشروط کردن","verb"),V("infer","infer","استنباط کردن","verb"),V("substantiate","substantiate","با شواهد پشتیبانی کردن","verb"),V("reframe","reframe","بازقاب‌بندی کردن","verb"),V("register","register","سطح رسمیت"),V("implication","implication","پیامد ضمنی / منطقی")],
    utterances=[
        U("receive","The briefing contains one confirmed finding, two plausible interpretations, and a recommendation that goes further than the evidence clearly supports.","گزارش یک یافته تأییدشده، دو تفسیر محتمل و یک توصیه داره که از چیزی که شواهد روشن پشتیبانی می‌کنن جلوتر می‌ره.","analyze_complex_input",["infer","substantiate"],1),
        U("synth","I would synthesize the sources around the decision we need to make rather than reproduce every detail they contain.","منابع رو حول تصمیمی که باید بگیریم ترکیب می‌کنم، نه اینکه همه جزئیاتشون رو بازتولید کنم.","synthesize_for_decision",["synthesize"],1),
        U("infer","The safest inference is that the problem is real but unevenly distributed; the data do not yet establish why.","امن‌ترین استنباط اینه که مشکل واقعی ولی نابرابر توزیع شده؛ داده هنوز دلیلش رو ثابت نمی‌کنه.","make_calibrated_inference",["infer","qualify"],2),
        U("qualify","I would qualify the recommendation by making implementation conditional on an independent review after the first phase.","توصیه رو با این شرط دقیق‌تر می‌کنم که اجرا بعد از مرحله اول به بازبینی مستقل وابسته باشه.","qualify_recommendation",["qualify","substantiate"],2),
        U("mediate","To mediate the disagreement, I would separate the shared objective from the competing assumptions about how to achieve it.","برای میانجی‌گری اختلاف، هدف مشترک رو از فرض‌های رقیب درباره نحوه رسیدن بهش جدا می‌کنم.","mediate_disagreement",["mediate","reframe"],3),
        U("reframe","Reframing the issue around acceptable risk gives both sides more room than the original all-or-nothing choice.","بازقاب‌بندی مسئله حول ریسک قابل قبول به هر دو طرف فضای بیشتری از انتخاب صفر و یکی اولیه می‌ده.","reframe_problem",["reframe","implication"],3),
        U("register","The final message should shift register by audience: concise and direct for the project team, more explicit and formal for external stakeholders.","پیام نهایی باید با مخاطب سطح رسمیتش عوض بشه: برای تیم پروژه کوتاه و مستقیم، برای ذی‌نفع بیرونی صریح‌تر و رسمی‌تر.","adapt_register",["register"],3),
        U("close","The C1 skill is not sounding complicated; it is controlling complexity well enough to be precise, flexible, persuasive, and fair.","مهارت C1 پیچیده حرف زدن نیست؛ اینه که پیچیدگی رو اون‌قدر خوب کنترل کنی که دقیق، منعطف، قانع‌کننده و منصف باشی.","integrate_c1_control",["synthesize","mediate","qualify","register"],3),
    ], grammar=["discourse_management","advanced_hedging","register_shift"], fill=["A strong C1 response should ___ multiple sources rather than list them separately.",["synthesize","infer","register","qualify"],"synthesize"]),
]

if __name__ == "__main__":
    write_units(UNITS)
