#!/usr/bin/env python3
from scripts.generate_c2_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=1, slug="c2-implicit-stance", topic="simple-messages", title="Implicit Stance & Fine-Grained Inference",
    vocab=[V("equivocal","equivocal","دوپهلو / نامطمئن","adjective"),V("tacit","tacit","ضمنی و ناگفته","adjective"),V("stance","stance","موضع"),V("hedge","hedge","با احتیاط محدود کردن ادعا","verb"),V("undertone","undertone","لحن پنهان"),V("infer","infer","استنباط کردن","verb"),V("disavow","disavow","صریحاً فاصله گرفتن از یک دیدگاه","verb"),V("alignment","alignment","هم‌راستایی")],
    utterances=[
        U("equivocal","Her answer is deliberately equivocal: it leaves room for cooperation without committing her to the proposal itself.","جوابش عمداً دوپهلوئه: راه همکاری رو باز می‌ذاره بدون اینکه خودش رو به خود پیشنهاد متعهد کنه.","interpret_equivocation",["equivocal","stance"],1),
        U("tacit","There is a tacit assumption that speed matters more than consultation, and that assumption is doing a lot of work in the argument.","یک فرض ناگفته وجود داره که سرعت از مشورت مهم‌تره و همین فرض بخش بزرگی از استدلال رو جلو می‌بره.","surface_tacit_assumption",["tacit","stance"],1),
        U("undertone","The wording is courteous, but the undertone suggests she sees the decision as effectively settled already.","واژه‌ها مؤدبانه‌ان، ولی لحن پنهان نشون می‌ده از نظر اون تصمیم عملاً از قبل گرفته شده.","read_undertone",["undertone","infer"],2),
        U("hedge","He hedges the criticism so carefully that the disagreement could be missed by anyone listening only for explicit objections.","انتقاد رو اون‌قدر با احتیاط بیان می‌کنه که کسی که فقط دنبال مخالفت صریح باشه ممکنه اصلاً متوجه اختلاف نشه.","detect_hedged_disagreement",["hedge","stance"],2),
        U("disavow","Notice that she does not disavow the principle; she distances herself only from the way it has been applied here.","دقت کن که از اصل موضوع فاصله نمی‌گیره؛ فقط از نحوه اجرای اون در این مورد مشخص فاصله می‌گیره.","distinguish_position",["disavow","alignment"],3),
        U("alignment","His lexical choices signal broad alignment with the goal while preserving room to challenge the means.","انتخاب واژه‌هاش هم‌راستایی کلی با هدف رو نشون می‌ده، در حالی که جا برای نقد روش باقی می‌ذاره.","infer_alignment",["alignment","stance"],3),
        U("caution","I would infer reluctance rather than opposition; the distinction matters because the appropriate response is different.","من بیشتر بی‌میلی استنباط می‌کنم تا مخالفت؛ این تفاوت مهمه چون نوع پاسخ مناسب رو عوض می‌کنه.","calibrate_inference",["infer","equivocal"],3),
        U("summary","So the safest reading is that the surface agreement masks a narrower, more conditional stance underneath.","پس امن‌ترین برداشت اینه که موافقت ظاهری یک موضع محدودتر و مشروط‌تر رو زیر خودش پنهان کرده.","summarize_stance",["undertone","stance"],3),
    ], grammar=["advanced_hedging","distancing","cohesion_reference"], fill=["The reply is deliberately ___, allowing several interpretations.",["equivocal","tacit","literal","conclusive"],"equivocal"]),

make_spec(index=2, slug="c2-layered-narrative", topic="simple-messages", title="Layered Narrative & Reflective Control",
    vocab=[V("retrospective","retrospective","بازنگرانه","adjective"),V("foreshadow","foreshadow","از قبل نشانه دادن","verb"),V("digression","digression","حاشیه‌روی"),V("reframe","reframe","از زاویه تازه بازتعریف کردن","verb"),V("culminate","culminate","در نهایت به نقطه‌ای رسیدن","verb"),V("vantage_point","vantage point","زاویه دید"),V("recollection","recollection","خاطره / یادآوری"),V("resonance","resonance","اثر و معنای ماندگار")],
    utterances=[
        U("opening","From my current vantage point, what looked like a routine decision then now feels like the first sign of a much larger shift.","از زاویه دید امروزم، چیزی که آن موقع یک تصمیم عادی به نظر می‌رسید حالا اولین نشانه یک تغییر خیلی بزرگ‌تره.","frame_retrospective",["vantage_point","retrospective"],1),
        U("foreshadow","A minor disagreement in the first meeting foreshadowed the conflict that would eventually reshape the whole project.","یک اختلاف کوچک در جلسه اول، در واقع پیش‌درآمد درگیری‌ای بود که بعداً کل پروژه رو تغییر داد.","foreshadow_outcome",["foreshadow","culminate"],1),
        U("digression","That apparent digression matters because it explains why I interpreted the later warning so differently from everyone else.","اون حاشیه‌روی ظاهری مهمه چون توضیح می‌ده چرا هشدار بعدی رو کاملاً متفاوت از بقیه برداشت کردم.","justify_digression",["digression","recollection"],2),
        U("reframe","For years I told the story as a failure; with distance, I have come to reframe it as a badly timed but useful correction.","سال‌ها داستان رو به شکل شکست تعریف می‌کردم؛ با فاصله زمانی، حالا بیشتر بهش به چشم یک اصلاح مفید ولی بدزمان‌بندی‌شده نگاه می‌کنم.","reframe_experience",["reframe","retrospective"],2),
        U("culminate","Several small compromises culminated in a decision none of us would have endorsed if it had been presented all at once.","چند سازش کوچک در نهایت به تصمیمی رسید که اگر یک‌جا جلوی ما گذاشته می‌شد هیچ‌کدوم تأییدش نمی‌کردیم.","show_cumulative_change",["culminate","reframe"],3),
        U("memory","My recollection is vivid but not necessarily reliable, so I try to distinguish what I remember from what the records later confirmed.","خاطره‌م واضحه ولی لزوماً قابل اتکا نیست، برای همین سعی می‌کنم چیزی که یادمه رو از چیزی که اسناد بعداً تأیید کردن جدا کنم.","qualify_memory",["recollection","retrospective"],3),
        U("counterfactual","Had I understood the wider context then, I might have read the same event less personally and responded more constructively.","اگر اون موقع زمینه گسترده‌تر رو می‌فهمیدم، شاید همون اتفاق رو کمتر شخصی برداشت می‌کردم و سازنده‌تر واکنش نشون می‌دادم.","reflect_counterfactually",["vantage_point","reframe"],3),
        U("close","What gives the episode lasting resonance is not the mistake itself, but how differently each person understood the same sequence of events.","چیزی که به این اتفاق معنای ماندگار می‌ده خود اشتباه نیست، بلکه تفاوت برداشت آدم‌ها از یک زنجیره اتفاق یکسانه.","close_with_resonance",["resonance","vantage_point"],3),
    ], grammar=["counterfactual_past","participle_clauses","inversion_emphasis"], fill=["With distance, she chose to ___ the setback as a useful correction.",["reframe","foreshadow","culminate","disavow"],"reframe"]),

make_spec(index=3, slug="c2-lexical-precision", topic="questions", title="Lexical Precision & Semantic Boundaries",
    vocab=[V("connotation","connotation","بار معنایی"),V("denotation","denotation","معنای مستقیم"),V("granular","granular","ریز و دقیق","adjective"),V("collocation","collocation","هم‌آیی واژگانی"),V("semantic","semantic","معنایی","adjective"),V("approximate","approximate","تقریبی","adjective"),V("distinction","distinction","تمایز"),V("idiomatic","idiomatic","طبیعی و جاافتاده در زبان","adjective")],
    utterances=[
        U("connotation","The denotation is similar, but the connotation is not: 'persistent' can sound admirable where 'stubborn' sounds critical.","معنای مستقیم شبیهه، ولی بار معنایی نه: persistent می‌تونه مثبت باشه، در حالی که stubborn معمولاً انتقادیه.","compare_connotation",["denotation","connotation"],1),
        U("granular","At this level, accuracy means being granular enough to distinguish a temporary constraint from a structural limitation.","در این سطح، دقت یعنی اون‌قدر جزئی و دقیق حرف بزنی که محدودیت موقت رو از محدودیت ساختاری جدا کنی.","make_granular_distinction",["granular","distinction"],1),
        U("collocation","The sentence is grammatically possible, but the collocation is unusual enough to make it sound translated rather than idiomatic.","جمله از نظر دستور ممکنه، ولی هم‌آیی واژه‌ها اون‌قدر غیرعادیه که ترجمه‌ای به نظر می‌رسه نه طبیعی.","judge_collocation",["collocation","idiomatic"],2),
        U("semantic","The semantic difference is small on paper but significant in negotiation because one term implies obligation and the other merely preference.","تفاوت معنایی روی کاغذ کمه، ولی در مذاکره مهمه چون یکی تعهد رو می‌رسونه و اون یکی فقط ترجیح رو.","explain_semantic_difference",["semantic","distinction"],2),
        U("approximate","'Misgiving' conveys doubt or unease; whether the speaker supports the proposal must be established from the wider context.","misgiving تردید یا نگرانی را می‌رساند؛ اینکه گوینده از پیشنهاد حمایت می‌کند یا نه باید از بافت گسترده‌تر مشخص شود.","refine_word_choice",["approximate","connotation"],3),
        U("idiomatic","An idiomatic choice is not always the most formal one; it is the one a proficient speaker would naturally select in that context.","انتخاب طبیعی همیشه رسمی‌ترین انتخاب نیست؛ انتخابیه که یک گوینده مسلط در اون موقعیت به شکل طبیعی استفاده می‌کنه.","define_idiomaticity",["idiomatic","collocation"],3),
        U("repair","Let me replace 'big' with 'far-reaching'; the first word understates both the scale and the consequences.","بذار big رو با far-reaching عوض کنم؛ واژه اول هم اندازه و هم پیامدها رو کمتر از واقع نشون می‌ده.","repair_lexical_choice",["granular","semantic"],3),
        U("summary","The aim is not ornamental vocabulary; it is choosing the narrowest expression that preserves the intended nuance.","هدف استفاده تزئینی از واژه‌های سخت نیست؛ هدف انتخاب دقیق‌ترین عبارتیه که ظرافت معنای موردنظر رو حفظ کنه.","state_precision_goal",["distinction","connotation"],3),
    ], grammar=["reformulation","cleft_sentences","emphasis_adverbs"], fill=["The two words share a denotation but differ sharply in ___.",["connotation","collocation","granularity","syntax"],"connotation"]),

make_spec(index=4, slug="c2-strategic-ambiguity", topic="questions", title="Strategic Ambiguity & Interpretive Control",
    vocab=[V("ambiguity","ambiguity","ابهام"),V("plausible_deniability","plausible deniability","امکان انکار قابل‌باور","noun_phrase"),V("underspecified","underspecified","کم‌جزئیات و عمداً نامشخص","adjective"),V("interpretive","interpretive","تفسیری","adjective"),V("loophole","loophole","راه فرار در متن / قانون"),V("wording","wording","نحوه عبارت‌بندی"),V("deliberate","deliberate","عمدی","adjective"),V("constraint","constraint","محدودیت")],
    utterances=[
        U("ambiguity","The ambiguity may be deliberate: the wording lets different audiences hear what they want without forcing a single interpretation.","ممکنه ابهام عمدی باشه: عبارت‌بندی اجازه می‌ده مخاطب‌های مختلف برداشت دلخواه خودشون رو داشته باشن بدون اینکه یک تفسیر قطعی تحمیل بشه.","identify_strategic_ambiguity",["ambiguity","deliberate","wording"],1),
        U("underspecified","The commitment is underspecified on timing, which preserves flexibility but also makes accountability harder.","تعهد از نظر زمان‌بندی عمداً کم‌جزئیاته؛ این انعطاف می‌ده ولی پاسخ‌گویی رو سخت‌تر می‌کنه.","evaluate_underspecification",["underspecified","constraint"],1),
        U("deniability","That phrase creates plausible deniability because the speaker can later claim a narrower meaning than listeners reasonably inferred.","اون عبارت امکان انکار قابل‌باور می‌سازه چون گوینده بعداً می‌تونه ادعا کنه منظور محدودتری از برداشت منطقی شنونده‌ها داشته.","explain_deniability",["plausible_deniability","interpretive"],2),
        U("loophole","The apparent loophole comes from a mismatch between the policy's stated intention and the exact wording used to define compliance.","راه فرار ظاهری از فاصله بین نیت اعلام‌شده سیاست و عبارت دقیق تعریف‌کننده رعایت قانون میاد.","locate_loophole",["loophole","wording"],2),
        U("interpretive","We need to separate legitimate interpretive flexibility from wording so vague that it prevents consistent enforcement.","باید انعطاف تفسیری قابل‌قبول رو از عبارتی که اون‌قدر مبهمه که اجرای یکدست رو ناممکن می‌کنه جدا کنیم.","draw_boundary",["interpretive","ambiguity"],3),
        U("constraint","If the document needs flexibility, the constraint should be explicit about which parts are negotiable and which are not.","اگر سند به انعطاف نیاز داره، باید صریح مشخص کنه کدوم بخش‌ها قابل مذاکره‌ان و کدوم نیستن.","clarify_constraints",["constraint","underspecified"],3),
        U("intent","I would not assume bad faith from ambiguity alone; sometimes several stakeholders can agree only because the wording remains open.","فقط از روی ابهام بدخواهی فرض نمی‌کنم؛ گاهی چند ذی‌نفع فقط وقتی می‌تونن توافق کنن که عبارت عمداً باز بمونه.","avoid_overinference",["ambiguity","deliberate"],3),
        U("summary","The key question is whether the ambiguity supports legitimate flexibility or merely postpones a conflict that the text should resolve now.","سؤال اصلی اینه که ابهام واقعاً انعطاف مفید ایجاد می‌کنه یا فقط اختلافی رو عقب می‌ندازه که متن باید همین حالا حلش کنه.","evaluate_ambiguity",["ambiguity","constraint"],3),
    ], grammar=["advanced_hedging","distancing","reformulation"], fill=["The clause is deliberately ___ on timing, leaving several possibilities open.",["underspecified","idiomatic","conclusive","literal"],"underspecified"]),

make_spec(index=5, slug="c2-pragmatic-meaning", topic="polite-language", title="Pragmatic Meaning, Face & Intent",
    vocab=[V("pragmatic","pragmatic","کاربردشناختی / وابسته به موقعیت","adjective"),V("face_saving","face-saving","حفظ آبرو و جایگاه اجتماعی","adjective"),V("imposition","imposition","تحمیل / زحمت"),V("rapport","rapport","رابطه و صمیمیت"),V("mitigate","mitigate","ملایم کردن","verb"),V("blunt","blunt","بیش از حد صریح","adjective"),V("deference","deference","احترام همراه با ملاحظه"),V("intent","intent","قصد")],
    utterances=[
        U("pragmatic","Pragmatically, 'You might want to check that again' can function as a strong warning even though its grammar looks tentative.","از نظر کاربرد در موقعیت، You might want to check that again می‌تونه هشدار خیلی جدی باشه با اینکه از نظر دستوری ملایم به نظر میاد.","interpret_pragmatic_force",["pragmatic","intent"],1),
        U("face","Her response is face-saving: it corrects the mistake without publicly forcing the other person to admit incompetence.","پاسخش طوریه که آبروی طرف حفظ می‌شه: اشتباه رو اصلاح می‌کنه بدون اینکه جلوی جمع مجبورش کنه ناتوانی خودش رو بپذیره.","identify_face_saving",["face_saving","rapport"],1),
        U("imposition","The request is small, but the imposition feels larger because it arrives after several previous favors.","درخواست کوچیکه، ولی چون بعد از چند لطف قبلی مطرح شده حس تحمیلش بیشتره.","assess_imposition",["imposition","rapport"],2),
        U("mitigate","He mitigates the refusal by giving a brief reason and offering a realistic alternative rather than over-apologizing.","رد کردن رو با یک دلیل کوتاه و یک جایگزین واقعی ملایم می‌کنه، نه با عذرخواهی افراطی.","mitigate_refusal",["mitigate","face_saving"],2),
        U("blunt","The sentence is not rude in isolation, but in this relationship it is blunt enough to sound impatient.","جمله به‌تنهایی بی‌ادبانه نیست، ولی در این رابطه اون‌قدر مستقیمه که بی‌حوصلگی می‌رسونه.","judge_contextual_directness",["blunt","rapport"],3),
        U("deference","Too much deference can sound distant or ironic when people normally speak to each other informally.","احترام بیش از حد وقتی آدم‌ها معمولاً خودمونی حرف می‌زنن می‌تونه سرد یا حتی طعنه‌آمیز به نظر برسه.","calibrate_deference",["deference","pragmatic"],3),
        U("intent","We should distinguish communicative intent from impact: a well-meant joke can still land badly.","باید قصد ارتباطی رو از اثر واقعی جدا کنیم: یک شوخی با نیت خوب هم می‌تونه بد برداشت بشه.","separate_intent_impact",["intent","rapport"],3),
        U("summary","Effective politeness is less about fixed formulas than about matching directness, distance and rapport to the actual relationship.","ادب مؤثر کمتر به فرمول‌های ثابت وابسته‌ست و بیشتر به هماهنگ کردن میزان صراحت، فاصله و صمیمیت با رابطه واقعی.","summarize_pragmatics",["rapport","deference"],3),
    ], grammar=["diplomatic_language","stance_markers","register_shift"], fill=["The speaker tries to ___ the refusal by offering a realistic alternative.",["mitigate","impose","disavow","foreshadow"],"mitigate"]),

make_spec(index=6, slug="c2-evidential-reasoning", topic="simple-messages", title="Evidential Reasoning & Degrees of Commitment",
    vocab=[V("evidential","evidential","مربوط به نوع و منبع شواهد","adjective"),V("corroboration","corroboration","تأیید مستقل"),V("provisional","provisional","موقت و قابل بازنگری","adjective"),V("indeterminate","indeterminate","نامشخص","adjective"),V("attribution","attribution","نسبت دادن ادعا به منبع"),V("warrant","warrant","پشتوانه منطقی برای ادعا"),V("triangulate","triangulate","از چند منبع مستقل بررسی کردن","verb"),V("certainty","certainty","قطعیت")],
    utterances=[
        U("evidential","The evidential basis differs across the claims: one rests on direct records, another on recollection, and a third on inference.","پایه شواهد برای ادعاها یکسان نیست: یکی روی اسناد مستقیمه، یکی روی خاطره و سومی روی استنباط.","classify_evidence_basis",["evidential","attribution"],1),
        U("warrant","The data warrant saying demand increased; they do not warrant saying the campaign caused the increase.","داده‌ها اجازه می‌دن بگیم تقاضا بالا رفته، ولی اجازه نمی‌دن بگیم کمپین باعث اون افزایش شده.","match_claim_to_warrant",["warrant","certainty"],1),
        U("corroboration","The anonymous account gains credibility because several details receive independent corroboration from records created at the time.","روایت ناشناس معتبرتر می‌شه چون چند جزئیش با اسناد مستقلی که همون زمان ساخته شدن تأیید می‌شن.","use_corroboration",["corroboration","triangulate"],2),
        U("provisional","My conclusion is provisional: it is the best fit for the current evidence, not a claim that alternatives have been eliminated.","نتیجه‌م موقته: بهترین توضیح برای شواهد فعلیه، نه ادعای اینکه همه گزینه‌های دیگه حذف شدن.","state_provisional_judgment",["provisional","certainty"],2),
        U("triangulate","Before treating the pattern as established, I would triangulate the survey with behavioral data and a source that does not share the same incentives.","قبل از اینکه الگو رو قطعی بدونم، نظرسنجی رو با داده رفتاری و منبعی که منافع مشابهی نداره تطبیق می‌دم.","triangulate_sources",["triangulate","evidential"],3),
        U("indeterminate","On motive, the evidence remains indeterminate; several explanations fit equally well.","درباره انگیزه، شواهد هنوز نامشخصن؛ چند توضیح به یک اندازه با داده‌ها جور درمیاد.","mark_indeterminacy",["indeterminate","certainty"],3),
        U("attribution","Careful attribution lets us report a serious claim without silently adopting the source's level of certainty as our own.","نسبت دادن دقیق به منبع اجازه می‌ده یک ادعای جدی رو گزارش کنیم بدون اینکه میزان قطعیت منبع رو بی‌صدا مال خودمون کنیم.","attribute_claim",["attribution","provisional"],3),
        U("summary","The disciplined position is neither skepticism about everything nor confidence by default; commitment should rise with the quality of the warrant.","موضع دقیق نه شک به همه‌چیزه و نه اعتماد پیش‌فرض؛ میزان تعهد به ادعا باید با کیفیت پشتوانه‌اش بالا بره.","calibrate_commitment",["warrant","certainty"],3),
    ], grammar=["advanced_reporting","advanced_hedging","reporting_passive"], fill=["The conclusion is ___ and should be revised if stronger evidence appears.",["provisional","conclusive","literal","blunt"],"provisional"]),

make_spec(index=7, slug="c2-causal-complexity", topic="requests", title="Causal Complexity & Counterfactual Explanation",
    vocab=[V("causal","causal","علّی","adjective"),V("confounder","confounder","عامل مداخله‌گر"),V("mechanism","mechanism","سازوکار"),V("multifactorial","multifactorial","چندعاملی","adjective"),V("counterfactual","counterfactual","خلاف واقع"),V("pathway","pathway","مسیر اثرگذاری"),V("mediate","mediate","واسطه اثر شدن","verb"),V("contingent","contingent","وابسته به شرایط","adjective")],
    utterances=[
        U("multi","The outcome is clearly multifactorial, so searching for a single decisive cause is likely to distort the explanation.","نتیجه کاملاً چندعاملیه، پس دنبال یک علت واحد و تعیین‌کننده گشتن احتمالاً توضیح رو تحریف می‌کنه.","reject_single_cause",["multifactorial","causal"],1),
        U("mechanism","A correlation becomes more persuasive when we can identify a plausible mechanism connecting the change to the outcome.","همبستگی وقتی قانع‌کننده‌تر می‌شه که بتونیم یک سازوکار منطقی بین تغییر و نتیجه پیدا کنیم.","identify_mechanism",["mechanism","causal"],1),
        U("confounder","Seasonality is a possible confounder because it affects both usage and purchasing behavior during the same period.","فصلی بودن می‌تونه عامل مداخله‌گر باشه چون هم استفاده و هم رفتار خرید رو در همون بازه تغییر می‌ده.","identify_confounder",["confounder","pathway"],2),
        U("pathway","The policy may influence retention indirectly, through a pathway mediated by trust rather than price itself.","سیاست شاید غیرمستقیم روی ماندگاری اثر بذاره، از مسیری که اعتماد واسطه‌شه نه خود قیمت.","trace_pathway",["pathway","mediate"],2),
        U("counterfactual","The relevant counterfactual is what would probably have happened without the intervention, not what happened before it.","خلاف‌واقع مرتبط اینه که بدون مداخله احتمالاً چه اتفاقی می‌افتاد، نه صرفاً قبل از مداخله چه اتفاقی افتاده بود.","frame_counterfactual",["counterfactual","causal"],3),
        U("contingent","The effect appears contingent on local capacity, which explains why the same intervention produced different outcomes across sites.","به نظر می‌رسه اثر به ظرفیت محلی وابسته‌ست و همین توضیح می‌ده چرا یک مداخله در جاهای مختلف نتایج متفاوت داده.","explain_contingency",["contingent","mechanism"],3),
        U("limits","Even a convincing mechanism does not eliminate alternative causes; it simply makes one explanation more coherent with the evidence.","حتی یک سازوکار قانع‌کننده هم علت‌های جایگزین رو حذف نمی‌کنه؛ فقط یک توضیح رو با شواهد سازگارتر می‌کنه.","limit_causal_claim",["mechanism","confounder"],3),
        U("summary","A strong causal account combines timing, mechanism, counterfactual reasoning and explicit treatment of plausible confounders.","یک توضیح علّی قوی زمان‌بندی، سازوکار، استدلال خلاف‌واقع و بررسی صریح عوامل مداخله‌گر منطقی رو کنار هم می‌ذاره.","synthesize_causal_case",["causal","counterfactual","confounder"],3),
    ], grammar=["mixed_conditionals","counterfactual_past","advanced_hedging"], fill=["Seasonality may be a ___ affecting both variables.",["confounder","mechanism","pathway","warrant"],"confounder"]),

make_spec(index=8, slug="c2-argument-diagnostics", topic="simple-messages", title="Argument Diagnostics & Hidden Premises",
    vocab=[V("premise","premise","پیش‌فرض"),V("validity","validity","اعتبار منطقی"),V("soundness","soundness","درستی منطقی همراه با مقدمات معتبر"),V("fallacy","fallacy","مغالطه"),V("circular","circular","دور باطل / چرخشی","adjective"),V("burden_of_proof","burden of proof","بار اثبات","noun_phrase"),V("rebuttal","rebuttal","پاسخ استدلالی"),V("inference","inference","استنتاج")],
    utterances=[
        U("premise","The conclusion sounds reasonable only because an unstated premise treats efficiency as more important than equity.","نتیجه فقط به این دلیل منطقی به نظر میاد که یک پیش‌فرض ناگفته کارایی رو مهم‌تر از عدالت فرض کرده.","surface_hidden_premise",["premise","inference"],1),
        U("validity","The argument may be logically valid while still being unpersuasive if one of its central premises is poorly supported.","استدلال ممکنه از نظر منطقی معتبر باشه ولی اگر یکی از مقدمات اصلیش پشتوانه ضعیفی داشته باشه همچنان قانع‌کننده نباشه.","separate_validity_support",["validity","premise"],1),
        U("soundness","For a deductive argument to be sound, its reasoning must be valid and all of its premises must be true.","برای sound بودن یک استدلال قیاسی، صورت استدلال باید معتبر و همهٔ مقدمات آن صادق باشند.","define_soundness",["soundness","validity"],2),
        U("fallacy","Calling the disagreement a false choice is useful only if we can show a realistic third option rather than merely naming a fallacy.","گفتن اینکه بحث دوگانه‌سازی کاذبه فقط وقتی مفیده که واقعاً گزینه سوم عملی نشون بدیم، نه اینکه فقط اسم مغالطه رو بگیم.","diagnose_fallacy",["fallacy","rebuttal"],2),
        U("circular","The justification is circular: the policy is described as necessary because it is said to be unavoidable, and unavoidable because it is necessary.","توجیه دوریه: سیاست ضروریه چون اجتناب‌ناپذیره و اجتناب‌ناپذیره چون ضروریه.","identify_circularity",["circular","premise"],3),
        U("burden","The burden of proof lies with the stronger claim, especially when it asks us to overturn a well-supported default assumption.","بار اثبات با ادعای قوی‌تره، مخصوصاً وقتی می‌خواد یک فرض پیش‌فرض با پشتوانه خوب رو کنار بزنه.","assign_burden_of_proof",["burden_of_proof","inference"],3),
        U("rebuttal","A strong rebuttal addresses the best version of the opposing argument rather than the easiest version to attack.","یک پاسخ استدلالی قوی به بهترین نسخه حرف طرف مقابل جواب می‌ده، نه ساده‌ترین نسخه‌ای که می‌شه بهش حمله کرد.","construct_rebuttal",["rebuttal","soundness"],3),
        U("summary","Before accepting the conclusion, trace the inference, expose the premises and ask which step carries the greatest evidential burden.","قبل از قبول نتیجه، مسیر استنتاج رو دنبال کن، پیش‌فرض‌ها رو آشکار کن و ببین کدوم مرحله بیشترین بار شواهدی رو داره.","diagnose_argument",["inference","premise","burden_of_proof"],3),
    ], grammar=["concession_rebuttal","cleft_sentences","discourse_management"], fill=["The argument depends on an unstated ___.",["premise","rebuttal","fallacy","collocation"],"premise"]),

make_spec(index=9, slug="c2-qualification-scope", topic="simple-messages", title="Qualification, Scope & Exception Handling",
    vocab=[V("scope","scope","دامنه"),V("qualifier","qualifier","قید محدودکننده"),V("exception","exception","استثنا"),V("boundary_case","boundary case","مورد مرزی","noun_phrase"),V("contingency","contingency","وابستگی به شرایط"),V("categorical","categorical","قطعی و بدون استثنا","adjective"),V("generalization","generalization","تعمیم"),V("nuance","nuance","ظرافت معنایی")],
    utterances=[
        U("scope","The statement becomes defensible once its scope is limited to first-time users in high-demand periods.","ادعا وقتی قابل دفاع می‌شه که دامنه‌اش به کاربران باراول در دوره‌های پرترافیک محدود بشه.","narrow_scope",["scope","qualifier"],1),
        U("categorical","The evidence does not justify a categorical claim; it supports a strong tendency with identifiable exceptions.","شواهد ادعای قطعی و بدون استثنا رو توجیه نمی‌کنن؛ یک روند قوی با استثناهای مشخص رو پشتیبانی می‌کنن.","avoid_categorical_claim",["categorical","exception"],1),
        U("boundary","Boundary cases are useful because they show exactly where the rule starts to break down.","موارد مرزی مفیدن چون دقیقاً نشون می‌دن قانون از کجا شروع به از کار افتادن می‌کنه.","use_boundary_cases",["boundary_case","scope"],2),
        U("contingency","The relationship is real, but its strength depends on a contingency the original summary leaves out: prior experience.","رابطه واقعیه، ولی شدت اون به یک شرط بستگی داره که خلاصه اولیه حذفش کرده: تجربه قبلی.","surface_contingency",["contingency","qualifier"],2),
        U("generalization","A useful generalization survives ordinary exceptions; a careless one treats every exception as noise.","تعمیم مفید استثناهای عادی رو تحمل می‌کنه؛ تعمیم بی‌دقت هر استثنایی رو نویز حساب می‌کنه.","evaluate_generalization",["generalization","exception"],3),
        U("qualifier","Adding 'in most observed settings' is not evasive; it is the qualifier needed to match the claim to the evidence.","اضافه کردن in most observed settings طفره رفتن نیست؛ همون قیدی‌ه که ادعا رو با شواهد هم‌اندازه می‌کنه.","add_qualifier",["qualifier","scope"],3),
        U("nuance","The nuance matters because a policy that is usually effective may still be inappropriate for a predictable minority of cases.","این ظرافت مهمه چون سیاستی که معمولاً مؤثره ممکنه برای یک اقلیت قابل‌پیش‌بینی از موارد همچنان نامناسب باشه.","explain_nuance",["nuance","exception"],3),
        U("summary","Precision comes from saying not only what is true, but for whom, under which conditions, and with what exceptions.","دقت فقط گفتن این نیست که چی درسته؛ باید بگی برای چه کسی، تحت چه شرایطی و با چه استثناهایی درسته.","summarize_scope_control",["scope","contingency","exception"],3),
    ], grammar=["advanced_hedging","complex_prepositions","emphasis_adverbs"], fill=["The claim needs a narrower ___ before it becomes defensible.",["scope","fallacy","rapport","mechanism"],"scope"]),

make_spec(index=10, slug="c2-rhetorical-concession", topic="polite-language", title="Rhetorical Concession & Sophisticated Rebuttal",
    vocab=[V("concession","concession","پذیرش بخشی از حرف مقابل"),V("rebuttal","rebuttal","پاسخ استدلالی"),V("counterargument","counterargument","استدلال مخالف"),V("steelman","steelman","قوی‌ترین نسخه حرف مقابل را ساختن","verb"),V("reservation","reservation","ملاحظه / تردید"),V("undercut","undercut","تضعیف کردن","verb"),V("compelling","compelling","بسیار قانع‌کننده","adjective"),V("common_ground","common ground","زمینه مشترک","noun_phrase")],
    utterances=[
        U("concession","I accept the central concession that the current system is faster; the question is whether speed compensates for the loss of review.","می‌پذیرم که سیستم فعلی سریع‌تره؛ سؤال اینه که آیا سرعت واقعاً کاهش بازبینی رو جبران می‌کنه یا نه.","concede_then_reframe",["concession","reservation"],1),
        U("steelman","Let me steelman the opposing case before I answer it: their concern is not cost alone, but predictability for smaller organizations.","قبل از جواب، قوی‌ترین نسخه استدلال طرف مقابل رو می‌گم: نگرانی‌شون فقط هزینه نیست، بلکه قابل‌پیش‌بینی بودن شرایط برای سازمان‌های کوچیکه.","steelman_opponent",["steelman","counterargument"],1),
        U("rebuttal","My rebuttal is narrower than a rejection: that concern is valid, but the proposed remedy creates a different risk of equal importance.","پاسخ من رد کامل نیست: اون نگرانی معتبره، ولی راه‌حل پیشنهادی یک ریسک متفاوت و هم‌اندازه می‌سازه.","deliver_rebuttal",["rebuttal","reservation"],2),
        U("undercut","The new evidence does not destroy the argument, but it does undercut the assumption that the benefits are evenly distributed.","شواهد جدید استدلال رو نابود نمی‌کنه، ولی فرض توزیع برابر مزایا رو تضعیف می‌کنه.","undercut_assumption",["undercut","counterargument"],2),
        U("compelling","The strongest part of their case is compelling precisely because it addresses a failure our proposal has not yet solved.","قوی‌ترین بخش حرفشون دقیقاً به این دلیل قانع‌کننده‌ست که مشکلی رو مطرح می‌کنه که پیشنهاد ما هنوز حلش نکرده.","acknowledge_strength",["compelling","concession"],3),
        U("ground","There is enough common ground to narrow the disagreement: we share the objective but weight the risks differently.","زمینه مشترک به اندازه کافی هست که اختلاف رو محدود کنیم: هدف مشترکه، ولی وزن ریسک‌ها رو متفاوت می‌بینیم.","locate_common_ground",["common_ground","reservation"],3),
        U("balance","A sophisticated rebuttal should leave intact whatever the opposing argument genuinely establishes.","پاسخ استدلالی پخته باید هر بخشی از حرف طرف مقابل رو که واقعاً ثابت شده دست‌نخورده نگه داره.","preserve_valid_points",["rebuttal","steelman"],3),
        U("close","So I would revise the proposal in response to the objection rather than defend the original wording unchanged.","پس در پاسخ به ایراد، پیشنهاد رو اصلاح می‌کنم نه اینکه از نسخه اولیه بدون تغییر دفاع کنم.","respond_constructively",["counterargument","common_ground"],3),
    ], grammar=["concession_rebuttal","diplomatic_language","stance_markers"], fill=["Before responding, she chose to ___ the opposing argument.",["steelman","undercut","mitigate","infer"],"steelman"]),
]

if __name__ == "__main__":
    write_units(UNITS)
