#!/usr/bin/env python3
from scripts.generate_c2_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=21, slug="c2-seminar-discourse", topic="school-study", title="Seminar Discourse & Intellectual Positioning",
    vocab=[V("intervention","intervention","ورود هدفمند به بحث"),V("thesis","thesis","تز / ادعای اصلی"),V("premise","premise","پیش‌فرض"),V("qualify","qualify","محدود و دقیق کردن","verb"),V("interrogate","interrogate","موشکافانه بررسی کردن","verb"),V("framework","framework","چارچوب"),V("situate","situate","در زمینه قرار دادن","verb"),V("implication","implication","پیامد ضمنی")],
    utterances=[
        U("entry","I want to make a narrow intervention here rather than challenge the entire thesis.","می‌خوام اینجا یک ورود محدود به بحث داشته باشم، نه اینکه کل تز رو زیر سؤال ببرم.","enter_seminar_discussion",["intervention","thesis"],1),
        U("premise","The premise I would interrogate is that institutional stability necessarily implies social legitimacy.","پیش‌فرضی که می‌خوام موشکافانه بررسی کنم اینه که ثبات نهادی لزوماً به معنای مشروعیت اجتماعی باشه.","interrogate_premise",["premise","interrogate"],1),
        U("framework","Within that framework, the conclusion follows; outside it, some of the categories stop being analytically useful.","داخل اون چارچوب، نتیجه منطقیه؛ بیرونش بعضی دسته‌بندی‌ها دیگه از نظر تحلیلی مفید نیستن.","evaluate_framework",["framework","thesis"],2),
        U("situate","I would situate the argument historically before treating the author's categories as universally applicable.","قبل از اینکه دسته‌بندی‌های نویسنده رو جهان‌شمول بدونم، استدلال رو در زمینه تاریخی خودش قرار می‌دم.","situate_argument",["situate","framework"],2),
        U("qualify","I agree with the direction of the claim, but I would qualify the mechanism more carefully.","با جهت ادعا موافقم، ولی سازوکارش رو دقیق‌تر و محدودتر بیان می‌کنم.","qualify_academic_claim",["qualify","premise"],3),
        U("implication","One implication of that reading is that the apparent contradiction may reflect competing definitions rather than incompatible evidence.","یکی از پیامدهای اون برداشت اینه که تناقض ظاهری شاید از تعریف‌های متفاوت بیاد نه از شواهد ناسازگار.","draw_implication",["implication","framework"],3),
        U("build","To build on that point, the exception may actually reveal a boundary condition the theory needs to explain.","برای ادامه اون نکته، استثنا شاید در واقع یک شرط مرزی رو نشون بده که نظریه باید توضیحش بده.","build_on_peer_point",["intervention","qualify"],3),
        U("summary","Advanced seminar participation means locating exactly where you agree, where you intervene and what follows if your intervention is right.","مشارکت پیشرفته در سمینار یعنی دقیق مشخص کنی کجا موافقی، کجا وارد بحث می‌شی و اگر نکته‌ت درست باشه چه پیامدی داره.","summarize_seminar_control",["intervention","implication","thesis"],3),
    ], grammar=["discourse_management","advanced_hedging","stance_markers"], fill=["She chose to ___ one premise rather than reject the entire thesis.",["interrogate","delegate","mitigate","recast"],"interrogate"]),

make_spec(index=22, slug="c2-synthesizing-complex-sources", topic="school-study", title="Synthesizing Dense & Conflicting Sources",
    vocab=[V("synthesis","synthesis","ترکیب تحلیلی"),V("convergence","convergence","همگرایی"),V("divergence","divergence","واگرایی"),V("reconcile","reconcile","سازگار کردن","verb"),V("tension","tension","تنش"),V("strand","strand","خط / رشته استدلال"),V("corroborate","corroborate","تأیید مستقل کردن","verb"),V("discrepancy","discrepancy","ناهمخوانی")],
    utterances=[
        U("synthesis","A synthesis should organize sources around the question, not march through them one author at a time.","ترکیب تحلیلی باید منابع رو حول سؤال سازمان بده، نه اینکه نویسنده‌ها رو یکی‌یکی خلاصه کنه.","define_synthesis",["synthesis","strand"],1),
        U("converge","The sources converge on the direction of change but diverge sharply on what caused it.","منابع درباره جهت تغییر همگرا هستن ولی درباره علتش به‌شدت واگرا.","identify_convergence_divergence",["convergence","divergence"],1),
        U("tension","That tension is analytically useful because each source explains evidence the other leaves unresolved.","اون تنش از نظر تحلیلی مفیده چون هر منبع بخشی از شواهد حل‌نشده منبع دیگه رو توضیح می‌ده.","use_source_tension",["tension","reconcile"],2),
        U("discrepancy","The discrepancy may come from different sampling windows rather than a genuine contradiction in findings.","ناهمخوانی شاید از بازه‌های نمونه‌گیری متفاوت بیاد نه از تناقض واقعی در یافته‌ها.","explain_discrepancy",["discrepancy","reconcile"],2),
        U("strand","One strand of the literature focuses on incentives, while another treats institutional trust as the mediating factor.","یک خط از ادبیات روی مشوق‌ها تمرکز داره و خط دیگه اعتماد نهادی رو عامل واسطه می‌دونه.","map_source_strands",["strand","synthesis"],3),
        U("corroborate","The archival evidence corroborates the timeline without supporting the interpretation attached to it by the interview source.","شواهد آرشیوی زمان‌بندی رو مستقل تأیید می‌کنه بدون اینکه تفسیر منبع مصاحبه رو هم تأیید کنه.","separate_fact_interpretation",["corroborate","discrepancy"],3),
        U("reconcile","We can reconcile the findings if we treat them as answers to different levels of the same question.","می‌تونیم یافته‌ها رو سازگار کنیم اگر اون‌ها رو پاسخ به سطوح متفاوت یک سؤال بدونیم.","reconcile_sources",["reconcile","synthesis"],3),
        U("summary","A strong synthesis preserves meaningful disagreement instead of smoothing every source into artificial consensus.","ترکیب قوی اختلاف معنادار رو حفظ می‌کنه به‌جای اینکه همه منابع رو به یک اجماع مصنوعی تبدیل کنه.","summarize_synthesis",["divergence","tension","synthesis"],3),
    ], grammar=["advanced_reporting","cohesion_reference","nominalisation"], fill=["The two studies ___ on the trend but diverge on its cause.",["converge","reconcile","undercut","mitigate"],"converge"]),

make_spec(index=23, slug="c2-comparative-theory", topic="school-study", title="Comparative Theory & Conceptual Lenses",
    vocab=[V("lens","lens","لنز / زاویه نظری"),V("construct","construct","سازه مفهومی"),V("explanatory","explanatory","توضیح‌دهنده","adjective"),V("paradigm","paradigm","پارادایم"),V("commensurable","commensurable","قابل مقایسه روی یک معیار","adjective"),V("assumption","assumption","فرض"),V("scope","scope","دامنه"),V("predictive","predictive","پیش‌بینی‌کننده","adjective")],
    utterances=[
        U("lens","Each theory makes different features salient because each uses a different analytical lens.","هر نظریه ویژگی‌های متفاوتی رو برجسته می‌کنه چون از لنز تحلیلی متفاوتی استفاده می‌کنه.","compare_theoretical_lenses",["lens","paradigm"],1),
        U("construct","The disagreement partly concerns the construct itself: the two authors operationalize 'trust' in incompatible ways.","بخشی از اختلاف درباره خود سازه‌ست: دو نویسنده trust رو به شکل‌های ناسازگار عملیاتی می‌کنن.","compare_constructs",["construct","commensurable"],1),
        U("explanatory","This framework has stronger explanatory depth, but the simpler model has better predictive performance in this dataset.","این چارچوب عمق توضیحی بیشتری داره، ولی مدل ساده‌تر در این داده قدرت پیش‌بینی بهتری داره.","contrast_explanation_prediction",["explanatory","predictive"],2),
        U("assumption","Their conclusions differ less than their assumptions about what counts as a relevant cause.","نتیجه‌ها کمتر از فرض‌هاشون درباره اینکه چه چیزی علت مرتبط حساب می‌شه با هم فرق دارن.","compare_assumptions",["assumption","lens"],2),
        U("scope","The theory is powerful within its scope, but it becomes strained when applied to settings it was not designed to explain.","نظریه داخل دامنه خودش قویه، ولی وقتی به موقعیت‌هایی که برای توضیحشون طراحی نشده تعمیم داده می‌شه کش پیدا می‌کنه.","evaluate_theory_scope",["scope","explanatory"],3),
        U("commensurable","The models are not fully commensurable because one predicts individual behavior and the other explains institutional change.","مدل‌ها کاملاً روی یک معیار قابل مقایسه نیستن چون یکی رفتار فردی رو پیش‌بینی می‌کنه و دیگری تغییر نهادی رو توضیح می‌ده.","limit_comparison",["commensurable","paradigm"],3),
        U("paradigm","A paradigm shift is not simply a new answer; it can change which questions are considered meaningful in the first place.","تغییر پارادایم فقط جواب جدید نیست؛ می‌تونه اصلاً تعیین کنه چه سؤال‌هایی از ابتدا معنادار حساب می‌شن.","explain_paradigm_shift",["paradigm","construct"],3),
        U("summary","Comparative theory works best when we compare assumptions, scope and explanatory purpose before ranking conclusions.","مقایسه نظریه وقتی بهتره که قبل از رتبه دادن به نتیجه‌ها، فرض‌ها، دامنه و هدف توضیحی رو مقایسه کنیم.","summarize_theory_comparison",["assumption","scope","explanatory"],3),
    ], grammar=["concession_rebuttal","advanced_hedging","complex_prepositions"], fill=["The two models are not fully ___ because they explain different levels of analysis.",["commensurable","categorical","transactional","irreversible"],"commensurable"]),

make_spec(index=24, slug="c2-methodological-critique", topic="school-study", title="Methodological Critique & Epistemic Limits",
    vocab=[V("validity","validity","اعتبار"),V("reliability","reliability","پایایی"),V("replication","replication","تکرارپذیری"),V("selection_bias","selection bias","سوگیری انتخاب","noun_phrase"),V("confounder","confounder","عامل مداخله‌گر"),V("measurement","measurement","سنجش"),V("causal","causal","علّی","adjective"),V("generalizability","generalizability","قابلیت تعمیم")],
    utterances=[
        U("validity","The measure is reliable in the sense that it is consistent, but its validity is questionable because it may not capture the construct we care about.","سنجش از نظر ثبات پایاست، ولی اعتبارش محل سؤاله چون شاید اصلاً سازه‌ای رو که برامون مهمه اندازه نگیره.","separate_validity_reliability",["validity","reliability"],1),
        U("selection","Selection bias is a serious concern because participation was voluntary and the most dissatisfied users were more likely to respond.","سوگیری انتخاب نگرانی جدیه چون شرکت داوطلبانه بوده و ناراضی‌ترین کاربران احتمال بیشتری برای پاسخ دادن داشتن.","identify_selection_bias",["selection_bias","generalizability"],1),
        U("measurement","The apparent improvement could partly reflect a change in measurement rather than a change in the underlying behavior.","بهبود ظاهری ممکنه بخشی از تغییر در روش سنجش باشه نه تغییر در رفتار واقعی.","question_measurement",["measurement","validity"],2),
        U("confounder","Without a strategy for the obvious confounders, the causal interpretation remains substantially weaker than the descriptive finding.","بدون راهی برای کنترل عوامل مداخله‌گر واضح، تفسیر علّی خیلی ضعیف‌تر از یافته توصیفی باقی می‌مونه.","limit_causal_inference",["confounder","causal"],2),
        U("replication","A failed replication does not automatically invalidate the original study; it may reveal a boundary condition or hidden dependency.","تکرار ناموفق لزوماً مطالعه اصلی رو باطل نمی‌کنه؛ ممکنه یک شرط مرزی یا وابستگی پنهان رو آشکار کنه.","interpret_replication",["replication","validity"],3),
        U("general","The sample supports inference about this population reasonably well, but generalizability beyond it is speculative.","نمونه برای استنتاج درباره همین جمعیت نسبتاً خوبه، ولی تعمیم فراتر از اون حدسیه.","scope_generalizability",["generalizability","selection_bias"],3),
        U("causal","The design establishes temporal order, which is necessary for a causal claim but nowhere near sufficient on its own.","طراحی ترتیب زمانی رو مشخص می‌کنه که برای ادعای علّی لازمه، ولی به‌تنهایی اصلاً کافی نیست.","calibrate_causal_claim",["causal","confounder"],3),
        U("summary","Methodological critique should identify what the design supports, what it cannot establish and which limitation matters most for the conclusion.","نقد روش‌شناسی باید مشخص کنه طراحی چی رو پشتیبانی می‌کنه، چی رو نمی‌تونه ثابت کنه و کدوم محدودیت برای نتیجه مهم‌تره.","summarize_method_critique",["validity","generalizability","measurement"],3),
    ], grammar=["advanced_hedging","nominalisation","reporting_passive"], fill=["A consistent measure can still lack ___.",["validity","reliability","replication","salience"],"validity"]),

make_spec(index=25, slug="c2-sustained-argument", topic="questions", title="Sustained Argument, Signposting & Rebuttal",
    vocab=[V("proposition","proposition","گزاره"),V("line_of_reasoning","line of reasoning","خط استدلال","noun_phrase"),V("rebuttal","rebuttal","پاسخ استدلالی"),V("counterexample","counterexample","مثال نقض"),V("signpost","signpost","نشانه‌گذاری مسیر بحث","verb"),V("cumulative","cumulative","تجمعی","adjective"),V("coherence","coherence","انسجام"),V("implication","implication","پیامد")],
    utterances=[
        U("proposition","My central proposition is narrow: the policy is defensible only if the review mechanism remains independent.","گزاره مرکزی من محدوده: سیاست فقط وقتی قابل دفاعه که سازوکار بازبینی مستقل بمونه.","state_core_proposition",["proposition","coherence"],1),
        U("signpost","Before turning to the counterargument, let me signpost the two steps that connect the evidence to the recommendation.","قبل از رفتن سراغ استدلال مخالف، دو مرحله‌ای که شواهد رو به توصیه وصل می‌کنن روشن می‌کنم.","signpost_argument",["signpost","line_of_reasoning"],1),
        U("cumulative","No single item is decisive; the case is cumulative, with several moderate reasons pointing in the same direction.","هیچ موردی به‌تنهایی تعیین‌کننده نیست؛ استدلال تجمعیه و چند دلیل متوسط همگی به یک جهت اشاره می‌کنن.","build_cumulative_case",["cumulative","line_of_reasoning"],2),
        U("counterexample","The counterexample does not destroy the proposition, but it forces us to define its scope more carefully.","مثال نقض گزاره رو نابود نمی‌کنه، ولی مجبورمون می‌کنه دامنه‌اش رو دقیق‌تر تعریف کنیم.","handle_counterexample",["counterexample","proposition"],2),
        U("rebuttal","The rebuttal succeeds only if it answers the objection's strongest form rather than changing the subject.","پاسخ استدلالی فقط وقتی موفقه که قوی‌ترین نسخه ایراد رو جواب بده نه اینکه موضوع رو عوض کنه.","deliver_rebuttal",["rebuttal","coherence"],3),
        U("implication","If that premise is accepted, the implication is broader than the author acknowledges because it affects the funding model as well.","اگر اون پیش‌فرض پذیرفته بشه، پیامدش از چیزی که نویسنده قبول داره گسترده‌تره چون مدل تأمین مالی رو هم تحت‌تأثیر قرار می‌ده.","extend_implication",["implication","proposition"],3),
        U("coherence","The argument is coherent because each section advances the same line of reasoning rather than adding unrelated good points.","استدلال منسجمه چون هر بخش همون خط استدلال رو جلو می‌بره نه اینکه نکته‌های خوب ولی نامرتبط اضافه کنه.","maintain_coherence",["coherence","line_of_reasoning"],3),
        U("summary","A sustained argument controls scope, sequence and rebuttal so the listener always knows what has been established and what remains contested.","استدلال پیوسته دامنه، توالی و پاسخ به اعتراض رو کنترل می‌کنه تا شنونده همیشه بدونه چی ثابت شده و چی هنوز محل اختلافه.","summarize_sustained_argument",["rebuttal","signpost","coherence"],3),
    ], grammar=["discourse_management","cleft_sentences","concession_rebuttal"], fill=["The argument is ___: no single piece of evidence is decisive.",["cumulative","categorical","transactional","equivocal"],"cumulative"]),

make_spec(index=26, slug="c2-policy-briefing", topic="jobs", title="Policy Briefing & Decision-Grade Communication",
    vocab=[V("briefing","briefing","گزارش تصمیم‌محور"),V("recommendation","recommendation","توصیه"),V("criterion","criterion","معیار"),V("implementation","implementation","اجرا"),V("feasibility","feasibility","امکان‌پذیری"),V("stakeholder","stakeholder","ذی‌نفع"),V("mitigation","mitigation","کاهش ریسک"),V("decision_grade","decision-grade","مناسب برای تصمیم واقعی","adjective")],
    utterances=[
        U("opening","The briefing should begin with the decision required, not with the history of how we reached the meeting.","گزارش باید با تصمیم موردنیاز شروع بشه نه تاریخچه اینکه چطور به جلسه رسیدیم.","open_decision_briefing",["briefing","recommendation"],1),
        U("criterion","The recommendation depends on three criteria: effectiveness, feasibility and distribution of risk.","توصیه به سه معیار بستگی داره: اثربخشی، امکان‌پذیری و توزیع ریسک.","state_decision_criteria",["criterion","feasibility"],1),
        U("stakeholder","The stakeholder analysis matters because the same policy imposes cost on one group while delivering benefit to another.","تحلیل ذی‌نفع مهمه چون یک سیاست برای یک گروه هزینه می‌سازه و برای گروه دیگه منفعت.","map_stakeholders",["stakeholder","implementation"],2),
        U("implementation","A theoretically attractive option may still be weak if implementation depends on capacity that does not currently exist.","گزینه‌ای که روی کاغذ جذابه ممکنه ضعیف باشه اگر اجرای اون به ظرفیتی وابسته باشه که الان وجود نداره.","test_implementation",["implementation","feasibility"],2),
        U("mitigation","I would recommend option B with one mitigation: an automatic review if the access gap widens beyond the agreed threshold.","گزینه B رو با یک اقدام کاهش ریسک توصیه می‌کنم: اگر شکاف دسترسی از آستانه تعیین‌شده بیشتر شد، بازبینی خودکار انجام بشه.","recommend_with_mitigation",["recommendation","mitigation"],3),
        U("decision","Decision-grade communication makes uncertainty visible without making the decision-maker reconstruct the analysis from raw detail.","ارتباط مناسب تصمیم، عدم قطعیت رو روشن می‌کنه بدون اینکه تصمیم‌گیر مجبور بشه تحلیل رو از جزئیات خام دوباره بسازه.","define_decision_grade",["decision_grade","briefing"],3),
        U("tradeoff","The briefing should state which downside we are deliberately accepting, not hide it in an appendix.","گزارش باید صریح بگه کدوم نقطه‌ضعف رو آگاهانه می‌پذیریم، نه اینکه توی ضمیمه قایمش کنه.","surface_accepted_downside",["recommendation","criterion"],3),
        U("summary","A good policy brief compresses complexity into a recommendation, criteria, trade-offs, implementation risks and clear triggers for review.","گزارش سیاست خوب پیچیدگی رو به توصیه، معیارها، مصالحه‌ها، ریسک‌های اجرا و محرک‌های روشن بازبینی فشرده می‌کنه.","summarize_policy_brief",["briefing","implementation","mitigation"],3),
    ], grammar=["nominalisation","discourse_management","advanced_hedging"], fill=["A recommendation can be attractive in theory but weak in practical ___.",["feasibility","connotation","rapport","denotation"],"feasibility"]),

make_spec(index=27, slug="c2-framing-propaganda", topic="simple-messages", title="Framing, Persuasion & Propaganda Techniques",
    vocab=[V("propaganda","propaganda","تبلیغات جهت‌دار"),V("framing","framing","قاب‌بندی"),V("loaded_language","loaded language","زبان بارگذاری‌شده","noun_phrase"),V("omission","omission","حذف"),V("false_balance","false balance","توازن کاذب","noun_phrase"),V("source_interest","source interest","منافع منبع","noun_phrase"),V("narrative","narrative","روایت"),V("manipulative","manipulative","دستکاری‌کننده","adjective")],
    utterances=[
        U("frame","Two reports can use the same facts yet create different impressions through framing, sequence and what they omit.","دو گزارش می‌تونن از واقعیت‌های یکسان استفاده کنن ولی با قاب‌بندی، ترتیب و چیزهایی که حذف می‌کنن برداشت‌های متفاوت بسازن.","compare_media_frames",["framing","omission"],1),
        U("loaded","Loaded language matters because it quietly tells the audience how to evaluate an event before the evidence is examined.","زبان بارگذاری‌شده مهمه چون قبل از بررسی شواهد، بی‌صدا به مخاطب می‌گه اتفاق رو چطور ارزیابی کنه.","identify_loaded_language",["loaded_language","narrative"],1),
        U("interest","Source interest does not automatically make a claim false, but it changes what independent verification we should seek.","منافع منبع لزوماً ادعا رو غلط نمی‌کنه، ولی تعیین می‌کنه دنبال چه تأیید مستقلی باید بگردیم.","evaluate_source_interest",["source_interest","propaganda"],2),
        U("balance","False balance occurs when unequal bodies of evidence are presented as if they had equal support simply to appear neutral.","توازن کاذب وقتی اتفاق می‌افته که دو طرف با پشتوانه شواهدی نابرابر فقط برای ظاهر بی‌طرفانه برابر نشان داده بشن.","identify_false_balance",["false_balance","framing"],2),
        U("propaganda","Propaganda is not defined merely by strong persuasion; systematic manipulation of information, identity and emotional cues matters too.","تبلیغات جهت‌دار فقط با اقناع قوی تعریف نمی‌شه؛ دستکاری نظام‌مند اطلاعات، هویت و محرک‌های احساسی هم مهمه.","define_propaganda",["propaganda","manipulative"],3),
        U("omission","An omission is most significant when the missing context would materially change how a reasonable audience interprets the claim.","حذف وقتی مهم‌تره که زمینه حذف‌شده برداشت یک مخاطب منطقی از ادعا رو به شکل جدی عوض کنه.","evaluate_omission",["omission","narrative"],3),
        U("narrative","The narrative selects heroes, causes and turning points; that structure can shape memory even when individual facts are accurate.","روایت قهرمان‌ها، علت‌ها و نقاط عطف رو انتخاب می‌کنه؛ همین ساختار می‌تونه حافظه رو شکل بده حتی اگر تک‌واقعیت‌ها درست باشن.","analyze_narrative_structure",["narrative","framing"],3),
        U("summary","Critical reading asks not only whether a statement is true, but why this fact, this label and this sequence were chosen for this audience.","خواندن انتقادی فقط نمی‌پرسه جمله درسته یا نه؛ می‌پرسه چرا همین واقعیت، همین برچسب و همین ترتیب برای این مخاطب انتخاب شده.","summarize_framing_analysis",["framing","source_interest","loaded_language"],3),
    ], grammar=["distancing","advanced_reporting","stance_markers"], fill=["Presenting unequal evidence as equally supported can create ___.",["false balance","common ground","plausible deniability","path dependency"],"false balance"]),

make_spec(index=28, slug="c2-breaking-news-uncertainty", topic="simple-messages", title="Breaking News, Verification & Rapidly Changing Claims",
    vocab=[V("verification","verification","راستی‌آزمایی"),V("unconfirmed","unconfirmed","تأییدنشده","adjective"),V("developing","developing","در حال تغییر","adjective"),V("corroborate","corroborate","تأیید مستقل کردن","verb"),V("provisional","provisional","موقت","adjective"),V("retract","retract","پس گرفتن ادعا","verb"),V("eyewitness","eyewitness","شاهد عینی"),V("timeline","timeline","خط زمانی")],
    utterances=[
        U("develop","This is a developing story, so the responsible summary should distinguish confirmed facts from claims that remain provisional.","این خبر در حال تغییره، پس خلاصه مسئولانه باید واقعیت‌های تأییدشده رو از ادعاهای موقت جدا کنه.","frame_developing_story",["developing","provisional"],1),
        U("unconfirmed","Several accounts repeat the number, but repetition is not verification; the figure remains unconfirmed.","چند روایت عدد رو تکرار می‌کنن، ولی تکرار راستی‌آزمایی نیست؛ عدد هنوز تأییدنشده‌ست.","mark_unconfirmed_claim",["unconfirmed","verification"],1),
        U("eyewitness","Eyewitness evidence can be valuable for immediate detail while remaining unreliable on scale, sequence or motive.","شهادت عینی برای جزئیات فوری می‌تونه ارزشمند باشه ولی درباره اندازه، توالی یا انگیزه همچنان ممکنه قابل اتکا نباشه.","qualify_eyewitness",["eyewitness","timeline"],2),
        U("corroborate","We should wait for an independent source to corroborate the location before building further conclusions on it.","قبل از اینکه نتیجه‌های بیشتری روی مکان بنا کنیم باید صبر کنیم یک منبع مستقل اون رو تأیید کنه.","seek_corroboration",["corroborate","verification"],2),
        U("timeline","The timeline has changed twice, which means earlier causal interpretations should be revisited rather than quietly retained.","خط زمانی دوبار عوض شده، یعنی تفسیرهای علّی قبلی باید دوباره بررسی بشن نه اینکه بی‌صدا حفظ بشن.","revise_with_timeline",["timeline","developing"],3),
        U("retract","A correction updates a detail; a retraction withdraws the claim itself. We should be precise about which has happened.","اصلاح یک جزئیات رو تغییر می‌ده؛ پس‌گرفتن ادعا خود ادعا رو کنار می‌ذاره. باید دقیق بگیم کدوم اتفاق افتاده.","distinguish_retraction",["retract","verification"],3),
        U("provisional","My current interpretation is provisional because the strongest evidence concerns what happened, not yet why it happened.","برداشت فعلیم موقته چون قوی‌ترین شواهد درباره اینه که چه اتفاقی افتاده، نه هنوز چرا اتفاق افتاده.","calibrate_news_inference",["provisional","unconfirmed"],3),
        U("summary","In fast-moving news, accuracy includes the discipline to update, retract and leave uncertainty visible as evidence changes.","در خبر سریع، دقت یعنی انضباط برای به‌روزرسانی، پس گرفتن ادعا و آشکار نگه داشتن عدم قطعیت وقتی شواهد عوض می‌شن.","summarize_news_verification",["verification","retract","developing"],3),
    ], grammar=["reporting_passive","distancing","advanced_hedging"], fill=["The figure remains ___ until an independent source verifies it.",["unconfirmed","categorical","idiomatic","transactional"],"unconfirmed"]),

make_spec(index=29, slug="c2-ai-governance", topic="common-actions", title="AI Governance, Accountability & Socio-Technical Risk",
    vocab=[V("governance","governance","حاکمیت و چارچوب نظارت"),V("accountability","accountability","پاسخ‌گویی"),V("oversight","oversight","نظارت"),V("automation_bias","automation bias","سوگیری اعتماد به خودکارسازی","noun_phrase"),V("auditability","auditability","قابلیت ممیزی"),V("deployment","deployment","استقرار"),V("safeguard","safeguard","اقدام حفاظتی"),V("externality","externality","پیامد تحمیل‌شده به دیگران")],
    utterances=[
        U("governance","AI governance is not just model quality; it includes who may deploy a system, under which conditions and with what accountability.","حاکمیت هوش مصنوعی فقط کیفیت مدل نیست؛ شامل اینه چه کسی، تحت چه شرایطی و با چه پاسخ‌گویی‌ای می‌تونه سیستم رو مستقر کنه.","define_ai_governance",["governance","deployment","accountability"],1),
        U("oversight","Human oversight is meaningful only if the reviewer has enough information, authority and time to challenge the system's output.","نظارت انسانی فقط وقتی معنی داره که بازبین اطلاعات، اختیار و زمان کافی برای به چالش کشیدن خروجی سیستم داشته باشه.","evaluate_oversight",["oversight","accountability"],1),
        U("bias","Automation bias can turn a nominally human decision into de facto machine approval if disagreement is costly or unusual.","سوگیری اعتماد به خودکارسازی می‌تونه تصمیم ظاهراً انسانی رو عملاً به تأیید ماشینی تبدیل کنه اگر مخالفت پرهزینه یا غیرعادی باشه.","explain_automation_bias",["automation_bias","oversight"],2),
        U("audit","Auditability matters because post-hoc accountability is weak when we cannot reconstruct what information influenced the decision.","قابلیت ممیزی مهمه چون پاسخ‌گویی بعد از اتفاق وقتی نتونیم بفهمیم چه اطلاعاتی روی تصمیم اثر گذاشته ضعیفه.","explain_auditability",["auditability","accountability"],2),
        U("safeguard","A safeguard should target a plausible failure mode rather than exist merely to make the deployment appear cautious.","اقدام حفاظتی باید یک حالت شکست واقعی رو هدف بگیره نه اینکه فقط استقرار رو محتاطانه به نظر برسونه.","design_safeguard",["safeguard","deployment"],3),
        U("externality","The operator may receive the benefit while the externality falls on people who cannot opt out or appeal.","ممکنه بهره اصلی به اپراتور برسه ولی پیامد منفی روی آدم‌هایی بیفته که نه می‌تونن خارج بشن نه اعتراض کنن.","identify_externality",["externality","governance"],3),
        U("threshold","The acceptable threshold for error should depend partly on reversibility, stakes and whether affected people have meaningful recourse.","آستانه قابل‌قبول خطا باید تا حدی به برگشت‌پذیری، شدت پیامد و دسترسی افراد آسیب‌دیده به راه اعتراض واقعی بستگی داشته باشه.","calibrate_risk_threshold",["safeguard","accountability"],3),
        U("summary","Responsible deployment combines technical performance with governance, auditability, human authority and remedies when things go wrong.","استقرار مسئولانه عملکرد فنی رو با حاکمیت، ممیزی‌پذیری، اختیار انسانی و راه جبران وقتی مشکل پیش میاد ترکیب می‌کنه.","summarize_ai_governance",["governance","auditability","oversight"],3),
    ], grammar=["nominalisation","concession_rebuttal","advanced_hedging"], fill=["A system may have human ___ in name but not in practice.",["oversight","denotation","collocation","restitution"],"oversight"]),

make_spec(index=30, slug="c2-climate-systems", topic="common-actions", title="Climate Systems, Policy Trade-offs & Long Horizons",
    vocab=[V("mitigation","mitigation","کاهش علت‌های تغییر اقلیم"),V("adaptation","adaptation","سازگاری"),V("resilience","resilience","تاب‌آوری"),V("externality","externality","پیامد بیرونی"),V("lock_in","lock-in","قفل شدن در مسیر","noun_phrase"),V("transition","transition","گذار"),V("distributional","distributional","مربوط به توزیع هزینه و منفعت","adjective"),V("trajectory","trajectory","مسیر بلندمدت")],
    utterances=[
        U("mitigation","Mitigation reduces future climate pressure; adaptation addresses harms that can no longer be fully avoided.","کاهش انتشار فشار اقلیمی آینده رو کم می‌کنه؛ سازگاری با آسیب‌هایی سروکار داره که دیگه کامل قابل اجتناب نیستن.","distinguish_mitigation_adaptation",["mitigation","adaptation"],1),
        U("resilience","Resilience is not simply returning to the old state if that old state was already vulnerable.","تاب‌آوری فقط برگشتن به وضعیت قبلی نیست، مخصوصاً اگر همون وضعیت از قبل آسیب‌پذیر بوده.","define_resilience",["resilience","adaptation"],1),
        U("externality","Carbon pricing addresses an externality by making at least part of the social cost visible in private decisions.","قیمت‌گذاری کربن بخشی از پیامد بیرونی رو با وارد کردن هزینه اجتماعی به تصمیم خصوصی قابل مشاهده می‌کنه.","explain_externality_policy",["externality","mitigation"],2),
        U("distribution","A policy can be environmentally effective and still politically fragile if its distributional effects are perceived as unfair.","یک سیاست می‌تونه از نظر محیط‌زیستی مؤثر باشه ولی اگر توزیع هزینه‌ها ناعادلانه دیده بشه از نظر سیاسی شکننده بمونه.","analyze_distributional_effect",["distributional","transition"],2),
        U("lock","Infrastructure choices create lock-in: a cheap short-term option can narrow the feasible transition path for decades.","انتخاب‌های زیرساختی قفل‌شدگی می‌سازن: گزینه ارزان کوتاه‌مدت می‌تونه مسیر گذار ممکن رو برای دهه‌ها محدود کنه.","explain_lock_in",["lock_in","trajectory"],3),
        U("trajectory","The relevant question is not whether one year improved, but whether the long-term emissions trajectory has shifted enough.","سؤال مهم این نیست که یک سال بهتر شده یا نه؛ اینه که آیا مسیر بلندمدت انتشار به اندازه کافی عوض شده.","focus_long_horizon",["trajectory","mitigation"],3),
        U("transition","A just transition makes the distribution of costs explicit and supports groups whose livelihoods are directly disrupted.","گذار عادلانه توزیع هزینه‌ها رو آشکار می‌کنه و از گروه‌هایی که معیشتشون مستقیم مختل می‌شه حمایت می‌کنه.","explain_just_transition",["transition","distributional"],3),
        U("summary","Climate policy requires long-horizon reasoning because present incentives, infrastructure and distributional choices shape future options.","سیاست اقلیمی به استدلال بلندمدت نیاز داره چون مشوق‌ها، زیرساخت و انتخاب‌های توزیعی امروز گزینه‌های آینده رو شکل می‌دن.","summarize_climate_systems",["trajectory","lock_in","transition"],3),
    ], grammar=["complex_prepositions","nominalisation","advanced_hedging"], fill=["Infrastructure can create long-term ___ that narrows future options.",["lock-in","rapport","rebuttal","denotation"],"lock-in"]),
]

if __name__ == "__main__":
    write_units(UNITS)
