#!/usr/bin/env python3
from scripts.generate_c1_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=1, slug="c1-reading-between-lines", topic="simple-messages", title="Reading Between the Lines",
    vocab=[V("implication","implication","پیام ضمنی"),V("subtle","subtle","ظریف / غیرمستقیم","adjective"),V("hint","hint","اشاره ضمنی"),V("infer","infer","استنباط کردن","verb"),V("underlying","underlying","زیربنایی / پنهان","adjective"),V("reservation","reservation","تردید / ملاحظه"),V("signal","signal","نشانه دادن","verb"),V("literal","literal","تحت‌اللفظی","adjective")],
    utterances=[
        U("surface","Taken literally, her reply sounds positive, but the hesitation signals a fairly clear reservation.","اگر جوابش رو تحت‌اللفظی بگیریم مثبت به نظر میاد، ولی مکثش یک تردید نسبتاً روشن رو نشون می‌ده.","identify_subtext",["literal","signal","reservation"],1),
        U("implication","The implication seems to be that she supports the goal but not the way we're proposing to reach it.","پیام ضمنی اینه که با هدف موافقه، ولی نه با روشی که برای رسیدن بهش پیشنهاد می‌دیم.","infer_implication",["implication","infer"],1),
        U("hint","He never rejected the idea directly; he kept hinting that the timing was wrong.","هیچ‌وقت مستقیم ایده رو رد نکرد؛ مدام غیرمستقیم اشاره می‌کرد که زمان‌بندیش اشتباهه.","interpret_hint",["hint","subtle"],2),
        U("underlying","The underlying concern may be about trust rather than cost, which changes how we should respond.","نگرانی پنهان شاید بیشتر اعتماد باشه تا هزینه، و این نحوه پاسخ ما رو عوض می‌کنه.","identify_underlying_concern",["underlying","infer"],2),
        U("tone","What matters here is not just what was said, but what the choice of words quietly signals about priorities.","اینجا فقط چیزی که گفته شده مهم نیست؛ انتخاب واژه‌ها هم خیلی ظریف درباره اولویت‌ها پیام می‌ده.","interpret_language_choice",["signal","subtle"],3),
        U("caution","I'd be cautious about inferring too much from one phrase when the rest of the message is ambiguous.","من درباره استنباط زیاد از یک عبارت احتیاط می‌کنم وقتی بقیه پیام مبهمه.","limit_inference",["infer","implication"],3),
        U("contrast","There is a subtle difference between reluctance and refusal, and the response sounds closer to the former.","بین بی‌میلی و رد کردن تفاوت ظریفی هست و این پاسخ بیشتر شبیه اولی به نظر می‌رسه.","distinguish_meaning",["subtle","reservation"],3),
        U("summary","So the safest reading is that there is interest, but also an unspoken reservation we should clarify.","پس امن‌ترین برداشت اینه که علاقه وجود داره، ولی یک تردید ناگفته هم هست که باید روشنش کنیم.","summarize_subtext",["reservation","implication"],3),
    ], grammar=["advanced_hedging","distancing","cohesion_reference"], fill=["The pause seemed to ___ a reservation rather than a refusal.",["signal","literal","infer","underlying"],"signal"]),

make_spec(index=2, slug="c1-complex-anecdotes", topic="simple-messages", title="Complex Anecdotes & Reflection",
    vocab=[V("turning_point","turning point","نقطه عطف"),V("in_hindsight","in hindsight","حالا که به گذشته نگاه می‌کنم","phrase"),V("unfold","unfold","پیش رفتن / آشکار شدن","verb"),V("misjudge","misjudge","بد قضاوت کردن","verb"),V("coincidence","coincidence","تصادف"),V("setback","setback","عقب‌گرد / مانع"),V("perspective","perspective","دیدگاه"),V("eventually","eventually","در نهایت","adverb")],
    utterances=[
        U("setup","At the time, it felt like a minor setback; in hindsight, it was the turning point of the whole project.","اون موقع یک مانع کوچک به نظر می‌رسید؛ حالا که نگاه می‌کنم، نقطه عطف کل پروژه بود.","frame_anecdote",["setback","in_hindsight","turning_point"],1),
        U("unfold","What happened next unfolded so gradually that none of us noticed the pattern until much later.","چیزی که بعدش اتفاق افتاد اون‌قدر تدریجی پیش رفت که هیچ‌کدوم تا خیلی بعد متوجه الگو نشدیم.","develop_story",["unfold","eventually"],1),
        U("misjudge","I'd misjudged the situation because I was focusing on the immediate problem rather than the broader context.","موقعیت رو بد قضاوت کرده بودم چون به‌جای زمینه کلی، روی مشکل فوری تمرکز داشتم.","reflect_on_mistake",["misjudge","perspective"],2),
        U("coincidence","A coincidence brought the right people into the same room, but what followed was anything but accidental.","یک تصادف آدم‌های درست رو توی یک اتاق جمع کرد، ولی چیزی که بعدش شد اصلاً تصادفی نبود.","mark_coincidence",["coincidence","unfold"],2),
        U("shift","The experience changed my perspective on failure: a setback can expose a weakness before it becomes expensive.","اون تجربه دیدگاهم به شکست رو عوض کرد: یک مانع می‌تونه قبل از پرهزینه شدن، یک ضعف رو آشکار کنه.","reflect_on_meaning",["perspective","setback"],3),
        U("counterfactual","Had everything gone according to plan, we might never have questioned the assumption that caused the later problem.","اگر همه‌چیز طبق برنامه پیش رفته بود، شاید هیچ‌وقت فرضی رو که بعداً مشکل ساخت زیر سؤال نمی‌بردیم.","consider_counterfactual",["turning_point"],3),
        U("eventually","Eventually, the story became less about what went wrong and more about what we learned from responding to it.","در نهایت داستان کمتر درباره چیزی بود که خراب شد و بیشتر درباره چیزی که از واکنش بهش یاد گرفتیم.","close_reflectively",["eventually","perspective"],3),
        U("lesson","If there is one lesson I would take from it, it is that early certainty can be more dangerous than early doubt.","اگر بخوام یک درس ازش بگیرم، اینه که اطمینان زودهنگام می‌تونه از تردید زودهنگام خطرناک‌تر باشه.","derive_lesson",["in_hindsight"],3),
    ], grammar=["participle_clauses","counterfactual_past","inversion_emphasis"], fill=["In ___, the delay was actually a useful turning point.",["hindsight","perspective","coincidence","setback"],"hindsight"]),

make_spec(index=3, slug="c1-precision-reformulation", topic="questions", title="Precision & Reformulation",
    vocab=[V("precise","precise","دقیق","adjective"),V("distinction","distinction","تمایز"),V("rephrase","rephrase","بازگویی کردن","verb"),V("qualify","qualify","با قید و شرط دقیق‌تر کردن","verb"),V("scope","scope","دامنه"),V("misleading","misleading","گمراه‌کننده","adjective"),V("nuance","nuance","ظرافت معنایی"),V("clarify","clarify","روشن کردن","verb")],
    utterances=[
        U("correct","Saying the policy failed is too broad; more precisely, it failed to reach the groups most in need.","گفتن اینکه سیاست شکست خورد خیلی کلیه؛ دقیق‌ترش اینه که نتونست به گروه‌هایی که بیشتر نیاز داشتن برسه.","reformulate_claim",["precise","scope"],1),
        U("distinction","The distinction I want to make is between low participation and low interest; they are not the same thing.","تمایزی که می‌خوام بگم بین مشارکت کم و علاقه کمه؛ این دو یکی نیستن.","make_distinction",["distinction","nuance"],1),
        U("rephrase","Let me rephrase that, because the first version makes the situation sound more certain than it is.","بذار دوباره بیانش کنم، چون نسخه اول موقعیت رو قطعی‌تر از چیزی که هست نشون می‌ده.","self_repair",["rephrase","misleading"],2),
        U("qualify","I would qualify the claim by saying the effect was significant in some settings, but not consistently across all of them.","من ادعا رو این‌طور دقیق‌تر می‌کنم که اثر در بعضی محیط‌ها مهم بود، ولی در همه‌شون به‌طور ثابت نه.","qualify_claim",["qualify","scope"],2),
        U("scope","When we narrow the scope to first-time users, the pattern becomes much easier to explain.","وقتی دامنه رو به کاربران باراول محدود می‌کنیم، توضیح الگو خیلی راحت‌تر می‌شه.","narrow_scope",["scope","clarify"],3),
        U("misleading","The average is technically correct, but it is misleading because it hides how uneven the outcomes were.","میانگین از نظر فنی درسته، ولی گمراه‌کننده‌ست چون نابرابری نتیجه‌ها رو پنهان می‌کنه.","challenge_wording",["misleading","nuance"],3),
        U("nuance","That extra nuance matters because it changes whether the issue looks temporary or structural.","اون ظرافت اضافه مهمه چون تعیین می‌کنه مشکل موقتی به نظر بیاد یا ساختاری.","explain_nuance",["nuance","distinction"],3),
        U("clarify","So, to clarify, we are questioning the interpretation of the data, not the accuracy of the data itself.","پس برای روشن شدن: ما تفسیر داده‌ها رو زیر سؤال می‌بریم، نه دقت خود داده‌ها رو.","clarify_position",["clarify","distinction"],3),
    ], grammar=["reformulation","cleft_sentences","emphasis_adverbs"], fill=["Let me ___ that: the result was uneven, not universally negative.",["rephrase","qualify","scope","nuance"],"rephrase"]),

make_spec(index=4, slug="c1-ambiguity-clarification", topic="questions", title="Ambiguity & Clarification",
    vocab=[V("ambiguous","ambiguous","مبهم","adjective"),V("interpretation","interpretation","تفسیر"),V("assumption","assumption","فرض"),V("explicit","explicit","صریح","adjective"),V("tentative","tentative","موقت / با احتیاط","adjective"),V("resolve","resolve","برطرف کردن","verb"),V("premise","premise","مبنای استدلال"),V("consistent","consistent","سازگار / یکدست","adjective")],
    utterances=[
        U("ambiguous","The wording is ambiguous enough that two reasonable people could walk away with different interpretations.","عبارت اون‌قدر مبهمه که دو آدم منطقی می‌تونن دو برداشت متفاوت ازش داشته باشن.","identify_ambiguity",["ambiguous","interpretation"],1),
        U("assumption","Before we resolve the disagreement, we should make the underlying assumption explicit.","قبل از حل اختلاف باید فرض پنهان رو صریح کنیم.","surface_assumption",["assumption","explicit","resolve"],1),
        U("tentative","My reading is tentative because the document never actually defines what it means by 'reasonable access.'", "برداشت من موقته چون سند اصلاً مشخص نمی‌کنه منظورش از «دسترسی معقول» چیه.","mark_tentative_reading",["tentative","interpretation"],2),
        U("premise","If we do not share the same premise, clarifying individual words will not solve the larger disagreement.","اگر مبنای مشترکی نداشته باشیم، روشن کردن واژه‌های جداگانه اختلاف بزرگ‌تر رو حل نمی‌کنه.","identify_premise",["premise","resolve"],2),
        U("explicit","Could we make the criterion explicit rather than relying on everyone to interpret 'high quality' in the same way?", "می‌شه معیار رو صریح کنیم به‌جای اینکه فرض کنیم همه «کیفیت بالا» رو یک‌جور تفسیر می‌کنن؟","request_explicitness",["explicit","interpretation"],3),
        U("consistent","The two sections are individually clear, but they are not fully consistent with each other.","هر دو بخش جداگانه روشنن، ولی کاملاً با هم سازگار نیستن.","identify_inconsistency",["consistent"],3),
        U("resolve","We can probably resolve most of this by agreeing on the definition before debating the conclusion.","احتمالاً می‌تونیم بیشتر این اختلاف رو با توافق روی تعریف، قبل از بحث روی نتیجه، حل کنیم.","propose_resolution",["resolve","premise"],3),
        U("limit","Even after clarification, there may still be legitimate room for more than one interpretation.","حتی بعد از روشن‌سازی، ممکنه همچنان بیش از یک تفسیر معتبر وجود داشته باشه.","acknowledge_remaining_ambiguity",["interpretation","ambiguous"],3),
    ], grammar=["advanced_hedging","reformulation","complex_prepositions"], fill=["The wording is too ___ to support only one interpretation.",["ambiguous","explicit","consistent","tentative"],"ambiguous"]),

make_spec(index=5, slug="c1-tone-subtext", topic="polite-language", title="Tone, Subtext & Intent",
    vocab=[V("dismissive","dismissive","تحقیرآمیز / بی‌اعتنا","adjective"),V("defensive","defensive","دفاعی","adjective"),V("patronizing","patronizing","از بالا به پایین","adjective"),V("sincere","sincere","صادقانه","adjective"),V("undertone","undertone","لحن پنهان"),V("intent","intent","نیت"),V("wording","wording","نحوه بیان"),V("come_across","come across","به نظر رسیدن","phrasal_verb")],
    utterances=[
        U("intent","I doubt the intent was dismissive, but the wording can easily come across that way.","فکر نمی‌کنم نیت بی‌اعتنایی بوده، ولی نحوه بیان خیلی راحت می‌تونه این‌طور برداشت بشه.","separate_intent_effect",["intent","dismissive","wording","come_across"],1),
        U("undertone","There is a defensive undertone in the reply, especially where it shifts responsibility back to the customer.","در جواب یک لحن دفاعی پنهان هست، مخصوصاً جایی که مسئولیت رو برمی‌گردونه سمت مشتری.","identify_tone",["defensive","undertone"],1),
        U("patronizing","The phrase is meant to reassure, but in this context it risks sounding patronizing rather than supportive.","عبارت قرار بوده اطمینان‌بخش باشه، ولی توی این زمینه ممکنه به‌جای حمایت، از بالا به پایین به نظر بیاد.","evaluate_tone_risk",["patronizing","come_across"],2),
        U("sincere","The apology sounds sincere because it names the specific harm instead of using a vague formula.","عذرخواهی صادقانه به نظر میاد چون آسیب مشخص رو نام می‌بره و فقط یک جمله کلیشه‌ای نمی‌گه.","evaluate_sincerity",["sincere","wording"],2),
        U("rewrite","I'd keep the same message but remove the phrase that makes the response sound unnecessarily defensive.","همون پیام رو نگه می‌دارم ولی عبارتی رو که جواب رو بی‌دلیل دفاعی می‌کنه حذف می‌کنم.","adjust_tone",["defensive","wording"],3),
        U("effect","Whatever the original intent, we need to respond to how the message is likely to be received.","هر نیتی که پشت پیام بوده، باید به اثری که احتمالاً روی مخاطب می‌ذاره پاسخ بدیم.","prioritize_reception",["intent","come_across"],3),
        U("context","A sentence that sounds neutral among close colleagues may come across as abrupt in a formal exchange.","جمله‌ای که بین همکارهای نزدیک خنثی به نظر میاد ممکنه در یک مکاتبه رسمی تند برداشت بشه.","compare_contexts",["come_across","wording"],3),
        U("summary","The problem is less the content than the undertone created by the sequence and wording.","مشکل کمتر خود محتواست و بیشتر لحن پنهانیه که ترتیب و نحوه بیان ایجاد کرده.","summarize_tone_issue",["undertone","wording"],3),
    ], grammar=["register_shift","diplomatic_language","cleft_sentences"], fill=["The message may ___ as more defensive than the writer intended.",["come across","resolve","qualify","infer"],"come across"]),

make_spec(index=6, slug="c1-speculation-inference", topic="simple-messages", title="Speculation & Inference",
    vocab=[V("plausible","plausible","قابل‌قبول / محتمل","adjective"),V("account_for","account for","توضیح دادن / عامل بودن","phrasal_verb"),V("indicate","indicate","نشان دادن","verb"),V("likelihood","likelihood","احتمال"),V("alternative","alternative","توضیح جایگزین"),V("evidence","evidence","شواهد"),V("deduce","deduce","نتیجه‌گیری کردن","verb"),V("tentatively","tentatively","با احتیاط","adverb")],
    utterances=[
        U("plausible","A staffing shortage is a plausible explanation, but it does not account for why the delays began so suddenly.","کمبود نیرو توضیح محتملیه، ولی توضیح نمی‌ده چرا تأخیرها این‌قدر ناگهانی شروع شدن.","evaluate_explanation",["plausible","account_for"],1),
        U("indicate","The pattern indicates that the problem is concentrated in one region rather than spread across the system.","الگو نشون می‌ده مشکل در یک منطقه متمرکزه، نه اینکه در کل سیستم پخش شده باشه.","infer_from_pattern",["indicate","deduce"],1),
        U("likelihood","Given the timing, the likelihood of a purely seasonal explanation seems relatively low.","با توجه به زمان‌بندی، احتمال اینکه توضیح فقط فصلی باشه نسبتاً کمه.","assess_likelihood",["likelihood","alternative"],2),
        U("alternative","We should keep an alternative explanation in view until we know whether the data collection method changed.","تا وقتی ندونیم روش جمع‌آوری داده تغییر کرده یا نه، باید یک توضیح جایگزین رو هم در نظر نگه داریم.","preserve_alternative",["alternative","evidence"],2),
        U("past","They may have underestimated demand, although the available evidence cannot establish that with confidence.","ممکنه تقاضا رو کمتر از واقع برآورد کرده باشن، هرچند شواهد موجود نمی‌تونه با اطمینان ثابتش کنه.","speculate_about_past",["evidence","plausible"],3),
        U("deduce","From the public figures alone, we can deduce that something changed; we cannot yet say what caused it.","فقط از ارقام عمومی می‌تونیم نتیجه بگیریم چیزی تغییر کرده؛ هنوز نمی‌تونیم بگیم علتش چی بوده.","limit_deduction",["deduce","evidence"],3),
        U("tentative","Tentatively, I'd rank the operational explanation above the behavioral one, but only slightly.","با احتیاط، توضیح عملیاتی رو کمی محتمل‌تر از توضیح رفتاری می‌دونم، ولی اختلاف زیادی نیست.","rank_hypotheses",["tentatively","likelihood"],3),
        U("update","If new evidence contradicts that reading, we should revise the inference rather than defend it.","اگر شواهد جدید با این برداشت تناقض داشت، باید استنباط رو اصلاح کنیم نه اینکه ازش دفاع کنیم.","revise_inference",["evidence","deduce"],3),
    ], grammar=["modal_deduction_past","advanced_hedging","distancing"], fill=["That is a ___ explanation, but it does not account for every detail.",["plausible","literal","explicit","dismissive"],"plausible"]),

make_spec(index=7, slug="c1-counterfactual-reasoning", topic="requests", title="Counterfactual Reasoning",
    vocab=[V("counterfactual","counterfactual","خلاف واقع"),V("outcome","outcome","نتیجه"),V("intervention","intervention","مداخله"),V("preventable","preventable","قابل پیشگیری","adjective"),V("contingent","contingent","وابسته به شرایط","adjective"),V("retrospect","retrospect","بازنگری به گذشته"),V("trigger","trigger","عامل آغازگر"),V("trajectory","trajectory","مسیر تحول")],
    utterances=[
        U("counterfactual","The useful counterfactual is not 'what if nothing had gone wrong?' but 'which earlier intervention could realistically have changed the outcome?'", "خلاف‌واقع مفید این نیست که «اگر هیچ‌چیز خراب نمی‌شد چی؟»؛ اینه که «کدوم مداخله زودتر واقعاً می‌تونست نتیجه رو عوض کنه؟»","frame_counterfactual",["counterfactual","intervention","outcome"],1),
        U("preventable","Some of the damage was probably preventable, but not all of it was within the team's control.","احتمالاً بخشی از آسیب قابل پیشگیری بود، ولی همه‌ش تحت کنترل تیم نبود.","assess_preventability",["preventable","outcome"],1),
        U("trigger","Had the warning triggered a review in March, the later failure might have been contained.","اگر هشدار در مارس باعث بازبینی شده بود، شاید شکست بعدی محدود می‌شد.","evaluate_alternative_past",["trigger","intervention"],2),
        U("trajectory","A small decision early on altered the trajectory, even though its importance was not obvious at the time.","یک تصمیم کوچک در اوایل مسیر رو عوض کرد، با اینکه اهمیتش اون موقع واضح نبود.","identify_turning_point",["trajectory","outcome"],2),
        U("contingent","The result was contingent on several choices, so it is misleading to attribute everything to one mistake.","نتیجه به چند انتخاب وابسته بود، پس نسبت دادن همه‌چیز به یک اشتباه گمراه‌کننده‌ست.","reject_single_cause",["contingent","outcome"],3),
        U("retrospect","In retrospect, we can see the missed signals, but that does not mean they were equally visible at the time.","در بازنگری به گذشته نشونه‌های از دست‌رفته رو می‌بینیم، ولی این معنی رو نمی‌ده که اون موقع هم به همون اندازه واضح بودن.","avoid_hindsight_bias",["retrospect"],3),
        U("present","If the earlier controls had been stronger, we would be dealing with a much smaller problem now.","اگر کنترل‌های قبلی قوی‌تر بودن، الان با مشکل خیلی کوچک‌تری روبه‌رو بودیم.","link_past_to_present",["intervention","outcome"],3),
        U("lesson","The point of counterfactual reasoning is to improve future decisions, not to invent certainty about the past.","هدف از استدلال خلاف‌واقع بهتر کردن تصمیم‌های آینده‌ست، نه ساختن اطمینان مصنوعی درباره گذشته.","state_purpose",["counterfactual","retrospect"],3),
    ], grammar=["counterfactual_past","mixed_conditionals","cleft_sentences"], fill=["The outcome was ___ on several decisions, not one single mistake.",["contingent","preventable","literal","explicit"],"contingent"]),

make_spec(index=8, slug="c1-weighing-evidence", topic="simple-messages", title="Weighing Evidence",
    vocab=[V("robust","robust","قوی و قابل اتکا","adjective"),V("anecdotal","anecdotal","مبتنی بر تجربه فردی","adjective"),V("corroborate","corroborate","تأیید مستقل کردن","verb"),V("contradict","contradict","تناقض داشتن","verb"),V("representative","representative","نماینده کل / قابل تعمیم","adjective"),V("methodology","methodology","روش‌شناسی"),V("bias","bias","سوگیری"),V("conclusive","conclusive","قطعی","adjective")],
    utterances=[
        U("robust","The evidence is reasonably robust on the overall trend, but much weaker on the explanation for it.","شواهد درباره روند کلی نسبتاً قویه، ولی درباره دلیلش خیلی ضعیف‌تره.","weigh_strength",["robust","evidence"],1),
        U("anecdotal","The personal accounts are useful for context, although they remain anecdotal and may not be representative.","روایت‌های شخصی برای زمینه مفیدن، هرچند تجربی و فردی هستن و شاید نماینده کل نباشن.","limit_anecdote",["anecdotal","representative"],1),
        U("corroborate","Two independent sources corroborate the timeline, which makes that part of the account more credible.","دو منبع مستقل زمان‌بندی رو تأیید می‌کنن و همین اون بخش روایت رو معتبرتر می‌کنه.","corroborate_claim",["corroborate","robust"],2),
        U("contradict","The survey does not directly contradict the interviews; it measures a different question using a different sample.","نظرسنجی مستقیم با مصاحبه‌ها تناقض نداره؛ سؤال متفاوتی رو با نمونه متفاوت اندازه می‌گیره.","reconcile_evidence",["contradict","methodology"],2),
        U("bias","The methodology reduces one kind of bias while introducing another, so the result needs careful interpretation.","روش‌شناسی یک نوع سوگیری رو کم می‌کنه ولی نوع دیگه‌ای وارد می‌کنه، پس نتیجه نیاز به تفسیر دقیق داره.","evaluate_method",["methodology","bias"],3),
        U("conclusive","None of this is conclusive on its own, but the sources point in broadly the same direction.","هیچ‌کدوم به‌تنهایی قطعی نیست، ولی منابع در کلیت به یک جهت اشاره می‌کنن.","synthesize_evidence",["conclusive","corroborate"],3),
        U("representative","Before generalizing, I'd want to know whether the sample is representative of the population being discussed.","قبل از تعمیم دادن، می‌خوام بدونم نمونه واقعاً نماینده جمعیتی هست که درباره‌ش حرف می‌زنیم یا نه.","question_generalization",["representative","methodology"],3),
        U("judgment","On balance, the evidence supports a cautious conclusion rather than a definitive one.","در مجموع، شواهد از یک نتیجه‌گیری محتاطانه حمایت می‌کنن نه یک نتیجه قطعی.","reach_evidence_judgment",["robust","conclusive"],3),
    ], grammar=["advanced_reporting","advanced_hedging","concession_rebuttal"], fill=["The interviews are informative, but they are still largely ___ evidence.",["anecdotal","conclusive","robust","representative"],"anecdotal"]),

make_spec(index=9, slug="c1-qualifying-claims", topic="simple-messages", title="Qualifying Claims",
    vocab=[V("caveat","caveat","قید / هشدار محدودکننده"),V("generalize","generalize","تعمیم دادن","verb"),V("extent","extent","میزان"),V("conditional","conditional","مشروط","adjective"),V("exception","exception","استثنا"),V("tentative","tentative","با احتیاط / موقتی","adjective"),V("overstate","overstate","بیش از حد بزرگ جلوه دادن","verb"),V("valid","valid","معتبر","adjective")],
    utterances=[
        U("caveat","The claim is broadly valid, with the important caveat that it applies mainly to larger organizations.","ادعا در کلیت معتبره، با این قید مهم که بیشتر درباره سازمان‌های بزرگ صدق می‌کنه.","add_caveat",["valid","caveat"],1),
        U("extent","The effect exists, but the extent of it varies considerably by age, location, and income.","اثر وجود داره، ولی میزانش با سن، محل و درآمد خیلی فرق می‌کنه.","qualify_extent",["extent","exception"],1),
        U("generalize","I would not generalize from this result until we have comparable data from at least two other settings.","تا وقتی داده قابل مقایسه از حداقل دو محیط دیگه نداشته باشیم، این نتیجه رو تعمیم نمی‌دم.","limit_generalization",["generalize","tentative"],2),
        U("conditional","My support is conditional on there being a clear review process if the policy produces unintended effects.","حمایت من مشروط به اینه که اگر سیاست اثر ناخواسته داشت، روند بازبینی روشنی وجود داشته باشه.","state_condition",["conditional","caveat"],2),
        U("exception","The exception matters because it challenges the idea that one mechanism explains every case.","استثنا مهمه چون این ایده رو به چالش می‌کشه که یک سازوکار همه موارد رو توضیح می‌ده.","use_exception",["exception","generalize"],3),
        U("overstate","Calling the program a complete success would overstate what the current evidence can support.","موفقیت کامل نامیدن برنامه بیشتر از چیزیه که شواهد فعلی پشتیبانی می‌کنن.","avoid_overstatement",["overstate","valid"],3),
        U("tentative","A more tentative conclusion would be that the approach is promising under certain conditions.","نتیجه محتاطانه‌تر اینه که رویکرد در بعضی شرایط امیدوارکننده‌ست.","offer_tentative_claim",["tentative","conditional"],3),
        U("summary","So I accept the direction of the argument, but I would qualify both its scope and its certainty.","پس جهت استدلال رو می‌پذیرم، ولی هم دامنه و هم میزان قطعیتش رو محدودتر بیان می‌کنم.","summarize_qualification",["extent","caveat"],3),
    ], grammar=["advanced_hedging","complex_prepositions","emphasis_adverbs"], fill=["The conclusion is broadly valid, with one important ___.",["caveat","extent","exceptional","conditional"],"caveat"]),

make_spec(index=10, slug="c1-diplomatic-disagreement", topic="polite-language", title="Diplomatic Disagreement",
    vocab=[V("challenge","challenge","به چالش کشیدن","verb"),V("concede","concede","پذیرفتن بخشی از استدلال","verb"),V("objection","objection","اعتراض / ایراد"),V("premise","premise","پیش‌فرض / مبنا"),V("constructive","constructive","سازنده","adjective"),V("dismiss","dismiss","رد کردن بدون بررسی","verb"),V("misgiving","misgiving","تردید / نگرانی"),V("common_ground","common ground","زمینه مشترک","noun_phrase")],
    utterances=[
        U("concede","I can concede that the proposal is simpler to implement; my objection is that simplicity is being treated as the main criterion.","می‌تونم بپذیرم که اجرای پیشنهاد ساده‌تره؛ ایراد من اینه که سادگی داره معیار اصلی فرض می‌شه.","concede_then_object",["concede","objection"],1),
        U("premise","I would challenge the premise rather than the conclusion, because the conclusion follows if that premise is accepted.","من بیشتر پیش‌فرض رو به چالش می‌کشم تا نتیجه رو، چون اگر اون پیش‌فرض پذیرفته بشه نتیجه منطقیه.","challenge_premise",["challenge","premise"],1),
        U("constructive","A constructive disagreement should make the alternative reasoning visible instead of simply saying the other view is wrong.","مخالفت سازنده باید منطق جایگزین رو روشن کنه، نه اینکه فقط بگه دیدگاه طرف مقابل غلطه.","define_constructive_disagreement",["constructive","dismiss"],2),
        U("misgiving","My main misgiving is not the objective itself but the assumption that the same approach will work in every context.","نگرانی اصلی من خود هدف نیست، بلکه فرض اینه که یک رویکرد در همه زمینه‌ها جواب می‌ده.","state_misgiving",["misgiving","premise"],2),
        U("common","There is more common ground here than it first appears: we agree on the problem, but not on the mechanism.","اینجا زمینه مشترک بیشتر از چیزیه که اول به نظر میاد: روی مشکل توافق داریم، ولی روی سازوکار نه.","identify_common_ground",["common_ground","objection"],3),
        U("dismiss","I would not dismiss that concern; I just think it should be weighed against the cost of delaying the decision.","اون نگرانی رو رد نمی‌کنم؛ فقط فکر می‌کنم باید در برابر هزینه به تعویق انداختن تصمیم سنجیده بشه.","acknowledge_concern",["dismiss","constructive"],3),
        U("soft","I see why that argument is attractive, though I'm not convinced it holds once we include the implementation costs.","می‌فهمم چرا اون استدلال جذابه، ولی وقتی هزینه اجرا رو وارد کنیم قانع نیستم همچنان برقرار بمونه.","disagree_diplomatically",["challenge","objection"],3),
        U("close","If we separate the points we agree on from the points still disputed, we may be able to move the discussion forward.","اگر بخش‌های مورد توافق رو از بخش‌های مورد اختلاف جدا کنیم، شاید بتونیم بحث رو جلو ببریم.","move_discussion_forward",["common_ground","constructive"],3),
    ], grammar=["diplomatic_language","concession_rebuttal","stance_markers"], fill=["I can ___ that the proposal is simpler, while still questioning its fairness.",["concede","dismiss","challenge","overstate"],"concede"]),
]

if __name__ == "__main__":
    write_units(UNITS)
