#!/usr/bin/env python3
from scripts.generate_c2_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=31, slug="c2-social-institutions", topic="simple-messages", title="Social Institutions, Norms & Structural Change",
    vocab=[V("institution","institution","نهاد"),V("norm","norm","هنجار"),V("legitimacy","legitimacy","مشروعیت"),V("structural","structural","ساختاری","adjective"),V("path_dependency","path dependency","وابستگی به مسیر","noun_phrase"),V("incentive","incentive","مشوق"),V("informal","informal","غیررسمی","adjective"),V("compliance","compliance","پیروی / رعایت")],
    utterances=[
        U("institution","An institution is not only a formal organization; it can also be a durable set of rules and expectations shaping behavior.","نهاد فقط یک سازمان رسمی نیست؛ می‌تونه مجموعه پایداری از قواعد و انتظارها باشه که رفتار رو شکل می‌ده.","define_institution",["institution","norm"],1),
        U("norm","A norm can remain powerful without legal enforcement if violating it carries social or reputational cost.","یک هنجار حتی بدون اجرای قانونی هم می‌تونه قوی بمونه اگر نقضش هزینه اجتماعی یا اعتباری داشته باشه.","explain_norm_power",["norm","informal"],1),
        U("legitimacy","Compliance based on legitimacy is different from compliance produced mainly by fear of sanction.","رعایت مبتنی بر مشروعیت با رعایتی که بیشتر از ترس مجازات میاد فرق داره.","distinguish_compliance_sources",["legitimacy","compliance"],2),
        U("structural","A structural explanation asks what recurring arrangement produces the pattern, not which individual made the last visible decision.","توضیح ساختاری می‌پرسه چه آرایش تکرارشونده‌ای این الگو رو می‌سازه، نه اینکه آخرین تصمیم قابل مشاهده رو کدوم فرد گرفته.","give_structural_explanation",["structural","institution"],2),
        U("path","Path dependency helps explain why an inefficient arrangement can persist long after better alternatives become available.","وابستگی به مسیر توضیح می‌ده چرا یک ساختار ناکارآمد می‌تونه مدت‌ها بعد از در دسترس شدن گزینه‌های بهتر باقی بمونه.","explain_path_dependency",["path_dependency","institution"],3),
        U("incentive","Changing the rule without changing the incentive may produce formal compliance and unchanged behavior.","عوض کردن قانون بدون عوض کردن مشوق ممکنه رعایت ظاهری بسازه ولی رفتار رو دست‌نخورده نگه داره.","analyze_rule_incentive_gap",["incentive","compliance"],3),
        U("informal","Informal practices often determine how a formal policy operates in reality, especially where discretion is high.","رویه‌های غیررسمی اغلب تعیین می‌کنن سیاست رسمی در عمل چطور کار کنه، مخصوصاً جایی که اختیار زیاد باشه.","connect_formal_informal",["informal","institution"],3),
        U("summary","Social change becomes easier to explain when we separate rules, norms, incentives, legitimacy and historical path rather than treating society as one actor.","تغییر اجتماعی وقتی بهتر توضیح داده می‌شه که قواعد، هنجارها، مشوق‌ها، مشروعیت و مسیر تاریخی رو جدا کنیم نه اینکه جامعه رو یک بازیگر واحد فرض کنیم.","summarize_institutions",["norm","incentive","legitimacy"],3),
    ], grammar=["nominalisation","advanced_hedging","cohesion_reference"], fill=["People may comply because they see an institution as ___.",["legitimate","transactional","equivocal","literal"],"legitimate"]),

make_spec(index=32, slug="c2-identity-discourse", topic="likes-dislikes", title="Identity, Belonging & Discursive Positioning",
    vocab=[V("belonging","belonging","حس تعلق"),V("identity","identity","هویت"),V("stereotype","stereotype","کلیشه"),V("hybridity","hybridity","هویت ترکیبی"),V("positioning","positioning","جایگاه‌سازی در گفتگو"),V("essentialize","essentialize","ذات‌انگارانه ساده‌سازی کردن","verb"),V("affiliation","affiliation","وابستگی / پیوند"),V("contextual","contextual","وابسته به زمینه","adjective")],
    utterances=[
        U("identity","Identity is not always a stable label; different aspects become salient in different relationships and settings.","هویت همیشه یک برچسب ثابت نیست؛ جنبه‌های مختلفش در رابطه‌ها و موقعیت‌های مختلف برجسته می‌شن.","frame_contextual_identity",["identity","contextual"],1),
        U("belonging","A person can feel strong belonging to several communities without experiencing those affiliations as contradictory.","یک نفر می‌تونه به چند جامعه حس تعلق قوی داشته باشه بدون اینکه این وابستگی‌ها رو متناقض بدونه.","discuss_multiple_belonging",["belonging","affiliation"],1),
        U("essentialize","We essentialize a group when we treat internal diversity as noise and present one trait as if it defined everyone.","وقتی تنوع داخل یک گروه رو نادیده می‌گیریم و یک ویژگی رو طوری می‌گیم که انگار همه رو تعریف می‌کنه، داریم ذات‌انگارانه ساده‌سازی می‌کنیم.","identify_essentializing",["essentialize","stereotype"],2),
        U("stereotype","A positive stereotype can still be restrictive if it pressures individuals to perform an expected identity.","یک کلیشه مثبت هم می‌تونه محدودکننده باشه اگر آدم‌ها رو مجبور کنه هویت موردانتظار رو اجرا کنن.","analyze_positive_stereotype",["stereotype","identity"],2),
        U("hybridity","Hybridity is useful when it describes lived mixture, but less useful if it implies that supposedly pure identities existed beforehand.","هویت ترکیبی وقتی تجربه واقعی آمیختگی رو توصیف می‌کنه مفیده، ولی اگر فرض کنه قبلش هویت‌های خالصی وجود داشتن کمتر مفیده.","qualify_hybridity",["hybridity","identity"],3),
        U("positioning","In conversation, people position themselves and others through labels, pronouns, jokes and assumptions about shared experience.","آدم‌ها در گفتگو با برچسب‌ها، ضمیرها، شوخی‌ها و فرض درباره تجربه مشترک، خودشون و دیگران رو جایگاه‌گذاری می‌کنن.","analyze_discursive_positioning",["positioning","affiliation"],3),
        U("context","The same remark may feel inclusive in one context and excluding in another because the history of the relationship changes its meaning.","همون جمله ممکنه در یک زمینه صمیمی و در زمینه دیگه طردکننده باشه چون تاریخ رابطه معنیش رو عوض می‌کنه.","interpret_contextual_identity_language",["contextual","belonging"],3),
        U("summary","Nuanced identity discourse avoids reducing people to categories while still recognizing that categories can shape real opportunities and experiences.","گفتگوی ظریف درباره هویت آدم‌ها رو به دسته‌ها تقلیل نمی‌ده، ولی در عین حال می‌پذیره دسته‌بندی‌ها می‌تونن فرصت‌ها و تجربه‌های واقعی رو شکل بدن.","summarize_identity_discourse",["identity","stereotype","contextual"],3),
    ], grammar=["advanced_hedging","concession_rebuttal","stance_markers"], fill=["Treating one trait as defining an entire group can ___ its members.",["essentialize","corroborate","mitigate","triangulate"],"essentialize"]),

make_spec(index=33, slug="c2-relationship-nuance", topic="polite-language", title="Relationship Nuance, Intimacy & Difficult Conversations",
    vocab=[V("intimacy","intimacy","صمیمیت"),V("resentment","resentment","دلخوری انباشته"),V("reciprocity","reciprocity","دوطرفه بودن"),V("vulnerability","vulnerability","آسیب‌پذیری عاطفی"),V("misattunement","misattunement","ناهماهنگی عاطفی"),V("repair","repair","ترمیم"),V("boundary","boundary","مرز"),V("subtext","subtext","معنای پنهان")],
    utterances=[
        U("subtext","The literal disagreement is about plans, but the subtext is whether each person feels considered in the relationship.","اختلاف ظاهری درباره برنامه‌هاست، ولی معنای پنهانش اینه که آیا هر نفر در رابطه احساس می‌کنه دیده شده یا نه.","identify_relationship_subtext",["subtext","intimacy"],1),
        U("resentment","Resentment often grows from repeated small asymmetries rather than one dramatic breach.","دلخوری انباشته اغلب از نابرابری‌های کوچک ولی تکراری میاد نه یک شکستن بزرگ اعتماد.","explain_resentment",["resentment","reciprocity"],1),
        U("vulnerability","Saying 'I felt excluded' is more vulnerable than saying 'you never care,' but it also gives the other person something specific to respond to.","گفتن «احساس کردم کنار گذاشته شدم» آسیب‌پذیرتر از «تو هیچ‌وقت اهمیت نمی‌دی»ـه، ولی به طرف مقابل چیز مشخص‌تری برای پاسخ می‌ده.","use_vulnerable_language",["vulnerability","repair"],2),
        U("misattune","The conflict may be less about intent than misattunement: one person needed reassurance while the other offered solutions.","اختلاف شاید کمتر درباره نیت باشه و بیشتر درباره ناهماهنگی عاطفی: یکی نیاز به اطمینان داشت و اون یکی راه‌حل می‌داد.","identify_misattunement",["misattunement","subtext"],2),
        U("boundary","A healthy boundary describes what I will do to protect a need; it is not a threat designed to control your choices.","مرز سالم می‌گه من برای محافظت از یک نیاز چه کاری می‌کنم؛ تهدیدی برای کنترل انتخاب‌های تو نیست.","distinguish_boundary_control",["boundary","intimacy"],3),
        U("reciprocity","Reciprocity does not mean identical effort every day; it means the relationship is not persistently sustained by one person alone.","دوطرفه بودن یعنی هر روز تلاش کاملاً برابر نه؛ یعنی رابطه به شکل دائمی فقط توسط یک نفر حمل نشه.","define_relationship_reciprocity",["reciprocity","resentment"],3),
        U("repair","Repair is credible when behavior changes in the situation that originally caused the hurt, not only in the apology conversation.","ترمیم وقتی واقعی می‌شه که رفتار در همون موقعیتی که ناراحتی رو ساخته تغییر کنه، نه فقط در گفتگوی عذرخواهی.","test_relationship_repair",["repair","vulnerability"],3),
        U("summary","Mature relationship language keeps intent, impact, need, boundary and repair separate enough to discuss each without collapsing everything into blame.","زبان پخته در رابطه نیت، اثر، نیاز، مرز و ترمیم رو اون‌قدر جدا نگه می‌داره که بشه درباره هر کدوم حرف زد بدون اینکه همه‌چیز تبدیل به سرزنش بشه.","summarize_relationship_nuance",["boundary","repair","subtext"],3),
    ], grammar=["diplomatic_language","reformulation","stance_markers"], fill=["Repeated small imbalances can gradually create ___.",["resentment","salience","validity","lock-in"],"resentment"]),

make_spec(index=34, slug="c2-medical-communication", topic="basic-health", title="Medical Communication, Risk & Shared Decisions",
    vocab=[V("prognosis","prognosis","پیش‌آگهی"),V("contraindication","contraindication","منع مصرف / منع انجام"),V("tradeoff","trade-off","مصالحه"),V("uncertainty","uncertainty","عدم قطعیت"),V("informed_consent","informed consent","رضایت آگاهانه","noun_phrase"),V("baseline","baseline","وضعیت پایه"),V("relative_risk","relative risk","ریسک نسبی","noun_phrase"),V("absolute_risk","absolute risk","ریسک مطلق","noun_phrase")],
    utterances=[
        U("risk","A large relative risk can still correspond to a small absolute change, so both figures matter when discussing benefit.","ریسک نسبی بزرگ می‌تونه هنوز به تغییر مطلق کوچیکی مربوط باشه، پس برای حرف زدن درباره منفعت هر دو عدد مهمن.","distinguish_risk_formats",["relative_risk","absolute_risk"],1),
        U("baseline","The meaning of the result depends partly on baseline risk; the same intervention does not offer equal benefit to everyone.","معنای نتیجه تا حدی به ریسک پایه بستگی داره؛ یک مداخله برای همه منفعت یکسانی نداره.","use_baseline_risk",["baseline","absolute_risk"],1),
        U("prognosis","A prognosis is an estimate based on groups and current information, not a precise prediction of one person's future.","پیش‌آگهی یک برآورد مبتنی بر گروه‌ها و اطلاعات فعلیه، نه پیش‌بینی دقیق آینده یک فرد.","explain_prognosis",["prognosis","uncertainty"],2),
        U("contra","The contraindication changes the decision because a treatment that is usually reasonable carries a specific additional risk here.","منع مصرف تصمیم رو عوض می‌کنه چون درمانی که معمولاً منطقیه اینجا یک ریسک اضافه مشخص داره.","explain_contraindication",["contraindication","tradeoff"],2),
        U("consent","Informed consent requires understanding meaningful alternatives and material risks, not simply signing a form.","رضایت آگاهانه یعنی فهم گزینه‌های مهم و ریسک‌های اثرگذار، نه فقط امضای یک فرم.","define_informed_consent",["informed_consent","tradeoff"],3),
        U("tradeoff","Two patients can make different reasonable choices because they weigh the same benefits, burdens and uncertainty differently.","دو بیمار می‌تونن با اطلاعات یکسان تصمیم‌های منطقی متفاوتی بگیرن چون منفعت، سختی و عدم قطعیت رو متفاوت وزن می‌کنن.","respect_preference_sensitive_decision",["tradeoff","uncertainty"],3),
        U("uncertain","The evidence is reassuring on common side effects but still uncertain on a rare long-term outcome.","شواهد درباره عوارض شایع اطمینان‌بخشن، ولی درباره یک پیامد نادر بلندمدت هنوز نامطمئنن.","communicate_medical_uncertainty",["uncertainty","prognosis"],3),
        U("summary","High-quality medical communication separates evidence, uncertainty and patient preference so that the decision is genuinely shared.","ارتباط پزشکی باکیفیت شواهد، عدم قطعیت و ترجیح بیمار رو جدا می‌کنه تا تصمیم واقعاً مشترک باشه.","summarize_shared_decision",["informed_consent","uncertainty","tradeoff"],3),
    ], grammar=["advanced_hedging","reporting_passive","concession_rebuttal"], fill=["A prognosis is an estimate, not a precise ___.",["prediction","collocation","restitution","affiliation"],"prediction"]),

make_spec(index=35, slug="c2-economic-policy", topic="prices", title="Economic Policy, Distribution & Incentive Effects",
    vocab=[V("incidence","incidence","محل واقعی تحمیل هزینه"),V("elasticity","elasticity","کشش"),V("subsidy","subsidy","یارانه"),V("distortion","distortion","اختلال انگیزشی"),V("distributional","distributional","توزیعی","adjective"),V("productivity","productivity","بهره‌وری"),V("externality","externality","پیامد بیرونی"),V("tradeoff","trade-off","مصالحه")],
    utterances=[
        U("incidence","The legal payer of a tax is not necessarily the group that bears its economic incidence after prices and wages adjust.","کسی که قانوناً مالیات رو می‌پردازه لزوماً همون گروهی نیست که بعد از تغییر قیمت و دستمزد بار اقتصادی واقعی رو تحمل می‌کنه.","explain_tax_incidence",["incidence","distributional"],1),
        U("elasticity","Elasticity matters because the less responsive side of a market may bear more of the burden.","کشش مهمه چون طرفی از بازار که کمتر می‌تونه واکنش نشون بده ممکنه بار بیشتری تحمل کنه.","use_elasticity",["elasticity","incidence"],1),
        U("subsidy","A subsidy can improve access while also increasing demand, so its effect on final prices is not automatic.","یارانه می‌تونه دسترسی رو بهتر کنه ولی هم‌زمان تقاضا رو بالا ببره، پس اثرش روی قیمت نهایی خودکار نیست.","analyze_subsidy",["subsidy","tradeoff"],2),
        U("distortion","Calling every behavioral response a distortion is misleading; sometimes the policy is deliberately trying to change incentives.","اینکه هر واکنش رفتاری رو اختلال بنامیم گمراه‌کننده‌ست؛ گاهی خود سیاست عمداً می‌خواد مشوق‌ها رو تغییر بده.","qualify_distortion",["distortion","externality"],2),
        U("distribution","Average gains can coexist with serious distributional losses if the benefits and costs fall on different groups.","میانگین سود مثبت می‌تونه هم‌زمان با زیان توزیعی جدی وجود داشته باشه اگر منفعت و هزینه روی گروه‌های متفاوت بیفته.","analyze_distributional_effects",["distributional","tradeoff"],3),
        U("productivity","A productivity gain matters for long-run capacity, but it does not tell us how the resulting income will be distributed.","افزایش بهره‌وری برای ظرفیت بلندمدت مهمه، ولی نمی‌گه درآمد حاصل چطور توزیع می‌شه.","separate_productivity_distribution",["productivity","distributional"],3),
        U("externality","A corrective policy is strongest when the externality is measurable enough that the incentive can be linked to the harm.","سیاست اصلاحی وقتی قوی‌تره که پیامد بیرونی اون‌قدر قابل اندازه‌گیری باشه که مشوق رو بشه به آسیب وصل کرد.","design_externality_policy",["externality","distortion"],3),
        U("summary","Economic policy analysis should track incentives, incidence, productivity and distribution instead of treating one headline indicator as the whole outcome.","تحلیل سیاست اقتصادی باید مشوق‌ها، محل واقعی هزینه، بهره‌وری و توزیع رو دنبال کنه نه اینکه یک شاخص اصلی رو کل نتیجه بدونه.","summarize_economic_policy",["incidence","productivity","distributional"],3),
    ], grammar=["nominalisation","complex_prepositions","advanced_hedging"], fill=["The group legally paying a tax may not bear its final economic ___.",["incidence","validity","rapport","subtext"],"incidence"]),

make_spec(index=36, slug="c2-cross-border-travel-resolution", topic="transport", title="Cross-Border Travel Disruption & Multi-Party Resolution",
    vocab=[V("rerouting","rerouting","مسیر جایگزین"),V("liability","liability","مسئولیت حقوقی / مالی"),V("interline","interline","همکاری بین شرکت‌های حمل‌ونقل","adjective"),V("documentation","documentation","مدارک"),V("reimbursement","reimbursement","بازپرداخت"),V("jurisdiction","jurisdiction","حوزه قضایی"),V("disruption","disruption","اختلال"),V("entitlement","entitlement","حق قانونی / قراردادی")],
    utterances=[
        U("route","The fastest rerouting is not useful if the operating carrier cannot honor the ticket under the current agreement.","سریع‌ترین مسیر جایگزین وقتی فایده نداره که شرکت اجراکننده طبق توافق فعلی نتونه بلیت رو قبول کنه.","evaluate_rerouting",["rerouting","interline"],1),
        U("liability","I need to separate operational help from liability; the desk assisting me may not be the party responsible for reimbursement.","باید کمک عملیاتی رو از مسئولیت مالی جدا کنم؛ میزی که کمکم می‌کنه شاید مسئول بازپرداخت نباشه.","separate_help_liability",["liability","reimbursement"],1),
        U("docs","I am keeping every receipt and written refusal because documentation matters if the claim later moves to formal review.","همه رسیدها و ردهای کتبی رو نگه می‌دارم چون اگر پرونده به بازبینی رسمی برسه مدارک مهم می‌شن.","preserve_documentation",["documentation","reimbursement"],2),
        U("entitlement","My entitlement may depend on the cause of the disruption, the route and which carrier actually operated the affected segment.","حق من ممکنه به علت اختلال، مسیر و اینکه کدوم شرکت واقعاً بخش آسیب‌دیده رو اجرا کرده بستگی داشته باشه.","scope_entitlement",["entitlement","disruption"],2),
        U("jurisdiction","Because the itinerary crosses jurisdictions, the applicable passenger rights may not be determined by the departure country alone.","چون مسیر از چند حوزه قضایی رد می‌شه، حقوق مسافر لزوماً فقط با کشور مبدأ تعیین نمی‌شه.","consider_jurisdiction",["jurisdiction","entitlement"],3),
        U("interline","An interline agreement can solve ticketing logistics without making the second carrier responsible for the original delay.","توافق بین شرکت‌ها می‌تونه مشکل بلیت رو حل کنه بدون اینکه شرکت دوم مسئول تأخیر اولیه بشه.","distinguish_interline_responsibility",["interline","liability"],3),
        U("escalate","I would ask for the decision and policy basis in writing before escalating; that makes the next review much more efficient.","قبل از ارجاع بالاتر، تصمیم و مبنای سیاست رو کتبی می‌خوام؛ این بازبینی بعدی رو خیلی مؤثرتر می‌کنه.","prepare_travel_escalation",["documentation","entitlement"],3),
        U("summary","Complex travel resolution depends on mapping the disruption, carrier roles, contractual rights, jurisdiction and evidence before choosing the escalation route.","حل اختلال پیچیده سفر به این بستگی داره که اختلال، نقش شرکت‌ها، حقوق قراردادی، حوزه قضایی و مدارک رو قبل از انتخاب مسیر اعتراض مشخص کنیم.","summarize_travel_resolution",["disruption","liability","jurisdiction"],3),
    ], grammar=["diplomatic_language","complex_prepositions","reporting_passive"], fill=["Receipts and written decisions provide essential ___ for a later claim.",["documentation","denotation","dominance","hybridity"],"documentation"]),

make_spec(index=37, slug="c2-legal-administrative-language", topic="requests", title="Legal-Administrative Language, Procedure & Appeal",
    vocab=[V("eligibility","eligibility","شرایط واجد بودن"),V("procedural","procedural","رویه‌ای","adjective"),V("substantive","substantive","ماهوی","adjective"),V("appeal","appeal","اعتراض رسمی"),V("discretion","discretion","اختیار تصمیم‌گیر"),V("precedent","precedent","سابقه"),V("burden","burden","بار اثبات / تکلیف"),V("remedy","remedy","راه جبران")],
    utterances=[
        U("eligibility","The first question is eligibility: if the threshold condition is not met, the merits may never be considered.","سؤال اول شرایط واجد بودنه: اگر شرط اولیه برقرار نباشه ممکنه اصلاً به ماهیت پرونده رسیدگی نشه.","check_eligibility",["eligibility","substantive"],1),
        U("procedure","A procedurally flawed decision can sometimes be challenged even when the substantive outcome might ultimately remain the same.","تصمیمی که از نظر روال ایراد داره گاهی قابل اعتراضه حتی اگر نتیجه ماهوی در نهایت همون بمونه.","separate_procedure_substance",["procedural","substantive"],1),
        U("discretion","The rule gives the decision-maker discretion, but discretion is not the same as unlimited freedom from reasons or consistency.","قانون به تصمیم‌گیر اختیار می‌ده، ولی اختیار به معنی آزادی نامحدود از ارائه دلیل یا یکدستی نیست.","interpret_discretion",["discretion","procedural"],2),
        U("burden","The burden is on the applicant to provide evidence of residence, while the authority must explain any adverse finding based on conflicting records.","بار ارائه مدرک اقامت با متقاضیه، در حالی که مرجع باید هر نتیجه منفی مبتنی بر اسناد متعارض رو توضیح بده.","allocate_evidential_burden",["burden","eligibility"],2),
        U("precedent","A precedent may guide interpretation without mechanically deciding a case with materially different facts.","سابقه می‌تونه تفسیر رو هدایت کنه بدون اینکه پرونده‌ای با واقعیت‌های مهم متفاوت رو مکانیکی تعیین کنه.","use_precedent_cautiously",["precedent","substantive"],3),
        U("appeal","A good appeal identifies the reviewable error, links it to evidence and asks for a remedy the reviewing body can actually grant.","اعتراض خوب خطای قابل بازبینی رو مشخص می‌کنه، به مدرک وصلش می‌کنه و جبرانی می‌خواد که مرجع واقعاً اختیار اعطاش رو داشته باشه.","structure_appeal",["appeal","remedy"],3),
        U("remedy","Winning on procedure may lead to a fresh decision rather than the final benefit the applicant originally sought.","برنده شدن روی ایراد روال ممکنه فقط به تصمیم‌گیری دوباره منجر بشه نه مستقیماً به مزیتی که متقاضی از اول می‌خواست.","understand_remedy",["procedural","remedy"],3),
        U("summary","Administrative language becomes manageable when we separate eligibility, procedure, merits, discretion, burden and available remedy.","زبان اداری وقتی قابل مدیریت می‌شه که شرایط، روال، ماهیت، اختیار، بار اثبات و جبران موجود رو جدا کنیم.","summarize_admin_language",["eligibility","discretion","remedy"],3),
    ], grammar=["nominalisation","reporting_passive","complex_prepositions"], fill=["An appeal should identify both the error and the available ___.",["remedy","collocation","rapport","trajectory"],"remedy"]),

make_spec(index=38, slug="c2-public-consultation", topic="simple-messages", title="Public Consultation, Stakeholders & Deliberative Trade-offs",
    vocab=[V("consultation","consultation","مشورت عمومی"),V("stakeholder","stakeholder","ذی‌نفع"),V("deliberation","deliberation","بحث سنجیده"),V("representation","representation","نمایندگی"),V("mandate","mandate","اختیار / مأموریت"),V("participation","participation","مشارکت"),V("tradeoff","trade-off","مصالحه"),V("legitimacy","legitimacy","مشروعیت")],
    utterances=[
        U("consult","A consultation is weak if it asks for views after the central decision is already irreversible.","مشورت عمومی وقتی ضعیفه که بعد از برگشت‌ناپذیر شدن تصمیم اصلی نظر بخواد.","evaluate_consultation",["consultation","legitimacy"],1),
        U("stake","Stakeholder mapping should include people who bear costs without having organized representation.","نقشه ذی‌نفع‌ها باید آدم‌هایی رو هم شامل بشه که هزینه می‌دن ولی نمایندگی سازمان‌یافته ندارن.","map_hidden_stakeholders",["stakeholder","representation"],1),
        U("participation","High participation does not guarantee representative participation if the process systematically favors people with more time or resources.","مشارکت زیاد لزوماً نماینده بودن رو تضمین نمی‌کنه اگر فرایند به شکل نظام‌مند به نفع افراد با زمان یا منابع بیشتر باشه.","question_participation_bias",["participation","representation"],2),
        U("deliberation","Deliberation is more than collecting preferences; participants need enough shared information to respond to each other's reasons.","بحث سنجیده بیشتر از جمع کردن ترجیحه؛ شرکت‌کننده‌ها باید اطلاعات مشترک کافی داشته باشن تا به دلایل همدیگه پاسخ بدن.","define_deliberation",["deliberation","consultation"],2),
        U("mandate","The committee's mandate is advisory, so it can strengthen legitimacy without pretending to replace the elected decision-maker.","مأموریت کمیته مشورتیه، پس می‌تونه مشروعیت رو تقویت کنه بدون اینکه وانمود کنه جای تصمیم‌گیر منتخب رو می‌گیره.","clarify_mandate",["mandate","legitimacy"],3),
        U("tradeoff","A fair process should make the trade-off explicit when improving access for one group reduces convenience for another.","فرایند عادلانه باید مصالحه رو صریح کنه وقتی بهتر کردن دسترسی یک گروه راحتی گروه دیگه رو کم می‌کنه.","surface_public_tradeoff",["tradeoff","stakeholder"],3),
        U("legitimacy","Procedural legitimacy cannot rescue every bad outcome, but opaque procedure can undermine even a reasonable decision.","مشروعیت رویه‌ای هر نتیجه بدی رو نجات نمی‌ده، ولی روال مبهم می‌تونه حتی تصمیم منطقی رو هم تضعیف کنه.","discuss_procedural_legitimacy",["legitimacy","consultation"],3),
        U("summary","Credible consultation makes participation limits, stakeholder effects, trade-offs and the actual decision mandate visible from the start.","مشورت معتبر از ابتدا محدودیت‌های مشارکت، اثر بر ذی‌نفع‌ها، مصالحه‌ها و اختیار واقعی تصمیم رو روشن می‌کنه.","summarize_public_consultation",["participation","stakeholder","mandate"],3),
    ], grammar=["concession_rebuttal","advanced_hedging","discourse_management"], fill=["A consultation should clarify whether its ___ is advisory or binding.",["mandate","denotation","restitution","collocation"],"mandate"]),

make_spec(index=39, slug="c2-literary-interpretation", topic="hobbies", title="Literary Interpretation, Voice & Ambiguity",
    vocab=[V("narrator","narrator","راوی"),V("unreliable","unreliable","غیرقابل اعتماد","adjective"),V("motif","motif","درون‌مایه تکرارشونده"),V("symbolism","symbolism","نمادپردازی"),V("ambiguity","ambiguity","ابهام"),V("voice","voice","صدای روایی"),V("intertextual","intertextual","بینامتنی","adjective"),V("reading","reading","تفسیر")],
    utterances=[
        U("narrator","The narrator is not simply dishonest; the gaps between what she notices and what the reader can infer make her reliability unstable.","راوی صرفاً دروغگو نیست؛ فاصله بین چیزهایی که خودش می‌بینه و چیزی که خواننده می‌تونه بفهمه، قابل‌اعتماد بودنش رو ناپایدار می‌کنه.","analyze_unreliable_narrator",["narrator","unreliable"],1),
        U("motif","The repeated image of locked doors functions as a motif linking privacy, exclusion and self-protection.","تصویر تکرارشونده درهای قفل‌شده به‌عنوان یک درون‌مایه، حریم خصوصی، طرد شدن و محافظت از خود رو به هم وصل می‌کنه.","interpret_motif",["motif","symbolism"],1),
        U("ambiguity","The ending's ambiguity is productive because neither interpretation cancels the emotional logic of the other.","ابهام پایان مفیده چون هیچ‌کدوم از دو تفسیر منطق احساسی اون یکی رو از بین نمی‌بره.","value_literary_ambiguity",["ambiguity","reading"],2),
        U("voice","The voice shifts from detached observation to intimate confession, and that change alters how earlier scenes are retrospectively read.","صدای روایت از مشاهده سرد به اعتراف صمیمی تغییر می‌کنه و همین باعث می‌شه صحنه‌های قبلی رو بعداً متفاوت بخونیم.","analyze_voice_shift",["voice","reading"],2),
        U("symbol","I would avoid fixing the river to one symbolic meaning; its function changes across the novel.","رودخانه رو به یک معنای نمادین ثابت محدود نمی‌کنم؛ کارکردش در طول رمان تغییر می‌کنه.","avoid_single_symbol_reading",["symbolism","motif"],3),
        U("intertext","The intertextual reference matters even if a reader misses the source, but recognizing it adds an extra layer of irony.","ارجاع بینامتنی حتی اگر خواننده منبع رو نشناسه هم کار می‌کنه، ولی شناختنش یک لایه طعنه اضافه می‌کنه.","analyze_intertextuality",["intertextual","reading"],3),
        U("evidence","A persuasive reading needs textual evidence, but evidence in literature supports interpretation rather than proving it uniquely.","تفسیر قانع‌کننده به شاهد متنی نیاز داره، ولی شاهد ادبی یک برداشت رو پشتیبانی می‌کنه نه اینکه به‌طور یکتا ثابتش کنه.","calibrate_literary_claim",["reading","ambiguity"],3),
        U("summary","Sophisticated literary analysis holds form, voice, pattern, context and ambiguity together without reducing the text to a hidden message to decode.","تحلیل ادبی پخته فرم، صدا، الگو، زمینه و ابهام رو کنار هم نگه می‌داره بدون اینکه متن رو به یک پیام مخفی برای رمزگشایی تقلیل بده.","summarize_literary_analysis",["voice","motif","ambiguity"],3),
    ], grammar=["advanced_hedging","cleft_sentences","cohesion_reference"], fill=["A recurring image or pattern in a literary work can function as a ___.",["motif","remedy","criterion","fallback"],"motif"]),

make_spec(index=40, slug="c2-comedy-wordplay", topic="polite-language", title="Comedy, Wordplay, Irony & Layered Humor",
    vocab=[V("wordplay","wordplay","بازی با کلمات"),V("deadpan","deadpan","طنز با لحن کاملاً جدی","adjective"),V("understatement","understatement","کم‌گویی طنزآمیز"),V("callback","callback","ارجاع دوباره به شوخی قبلی"),V("double_meaning","double meaning","معنای دوگانه","noun_phrase"),V("irony","irony","طعنه / تضاد معنایی"),V("timing","timing","زمان‌بندی"),V("punchline","punchline","نقطه ضربه شوخی")],
    utterances=[
        U("deadpan","The line is funny because it is delivered deadpan even though the situation is obviously absurd.","جمله به این دلیل خنده‌داره که با لحن کاملاً جدی گفته می‌شه در حالی که موقعیت واضحاً مسخره‌ست.","interpret_deadpan",["deadpan","irony"],1),
        U("under","Calling a complete system failure 'a slight inconvenience' is understatement, and the mismatch creates the humor.","اینکه خرابی کامل سیستم رو «یک دردسر کوچیک» بنامیم کم‌گویی طنزآمیزه و همین ناهماهنگی شوخی رو می‌سازه.","interpret_understatement",["understatement","irony"],1),
        U("wordplay","The wordplay works because the same phrase can be parsed as both a technical instruction and a social comment.","بازی کلامی چون کار می‌کنه که همون عبارت هم می‌تونه دستور فنی باشه هم نظر اجتماعی.","analyze_wordplay",["wordplay","double_meaning"],2),
        U("callback","The callback is stronger than a new joke because it rewards the audience for remembering an earlier detail.","ارجاع دوباره از یک شوخی جدید قوی‌تره چون مخاطب رو بابت به خاطر داشتن جزئیات قبلی پاداش می‌ده.","explain_callback",["callback","timing"],2),
        U("timing","The wording is ordinary; the humor depends almost entirely on timing and the pause before the final clause.","عبارت عادیه؛ طنز تقریباً کامل به زمان‌بندی و مکث قبل از بخش آخر بستگی داره.","analyze_comic_timing",["timing","punchline"],3),
        U("double","The double meaning is playful here, but in a different relationship the same line could sound suggestive or insulting.","معنای دوگانه اینجا بازیگوشانه‌ست، ولی در رابطه‌ای دیگه همون جمله می‌تونه کنایه‌دار یا توهین‌آمیز به نظر برسه.","judge_contextual_humor",["double_meaning","wordplay"],3),
        U("irony","Irony requires a gap between surface wording and intended stance; without enough shared context, that gap can simply look like sincerity.","طعنه به فاصله بین عبارت ظاهری و موضع واقعی نیاز داره؛ بدون زمینه مشترک کافی، اون فاصله ممکنه اصلاً به شکل حرف جدی دیده بشه.","explain_irony",["irony","deadpan"],3),
        U("summary","Advanced humor comprehension depends on lexical ambiguity, shared knowledge, relationship, timing and the listener's ability to recover nonliteral intent.","فهم طنز پیشرفته به ابهام واژگانی، دانش مشترک، رابطه، زمان‌بندی و توان شنونده برای بازیابی قصد غیرلفظی وابسته‌ست.","summarize_humor",["wordplay","timing","irony"],3),
    ], grammar=["ellipsis_substitution","register_shift","distancing"], fill=["A joke that refers back to an earlier joke is a ___.",["callback","rebuttal","criterion","fallback"],"callback"]),
]

if __name__ == "__main__":
    write_units(UNITS)
