#!/usr/bin/env python3
from scripts.generate_c1_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=21, slug="c1-academic-discussion", topic="school-study", title="Academic Discussion",
    vocab=[V("thesis","thesis","تز / ادعای اصلی"),V("premise","premise","مبنای استدلال"),V("criterion","criterion","معیار"),V("relevance","relevance","ارتباط"),V("substantiate","substantiate","با شواهد پشتیبانی کردن","verb"),V("challenge","challenge","به چالش کشیدن","verb"),V("interpretation","interpretation","تفسیر"),V("framework","framework","چارچوب")],
    utterances=[
        U("thesis","The thesis is clear, but the argument needs a stronger explanation of why this evidence is relevant to the central claim.","تز روشنه، ولی استدلال باید بهتر توضیح بده چرا این شواهد به ادعای اصلی مربوطه.","evaluate_thesis",["thesis","relevance"],1),
        U("premise","I would challenge the premise that efficiency and fairness necessarily move in opposite directions.","پیش‌فرض اینکه کارایی و عدالت لزوماً در جهت مخالف حرکت می‌کنن رو به چالش می‌کشم.","challenge_premise",["premise","challenge"],1),
        U("criterion","We appear to be evaluating the studies by different criteria, which may explain why we reach different judgments.","به نظر میاد مطالعات رو با معیارهای متفاوت ارزیابی می‌کنیم و شاید دلیل قضاوت متفاوت همین باشه.","surface_criterion",["criterion","interpretation"],2),
        U("subst","That interpretation is plausible, but I do not think the current data substantiate it strongly enough.","اون تفسیر قابل‌قبوله، ولی فکر نمی‌کنم داده فعلی به اندازه کافی قوی پشتیبانیش کنه.","request_support",["interpretation","substantiate"],2),
        U("framework","Within that framework, the result looks contradictory; under a different framework, the two findings can coexist.","داخل اون چارچوب نتیجه متناقض به نظر میاد؛ در چارچوب دیگه، دو یافته می‌تونن کنار هم وجود داشته باشن.","compare_frameworks",["framework","interpretation"],3),
        U("relevance","A detail can be accurate without being relevant to the question the discussion is trying to answer.","یک جزئیات می‌تونه دقیق باشه بدون اینکه به سؤالی که بحث می‌خواد جواب بده مرتبط باشه.","distinguish_relevance",["relevance","criterion"],3),
        U("challenge2","I am challenging the inference, not the quality of the research itself.","من استنباط رو به چالش می‌کشم، نه کیفیت خود تحقیق رو.","clarify_challenge",["challenge","interpretation"],3),
        U("close","The discussion becomes more productive once we make the thesis, evidence, and evaluation criteria explicit.","بحث وقتی سازنده‌تر می‌شه که تز، شواهد و معیارهای ارزیابی رو صریح کنیم.","summarize_academic_discussion",["thesis","criterion"],3),
    ], grammar=["advanced_reporting","discourse_management","nominalisation"], fill=["The data do not fully ___ the interpretation yet.",["substantiate","challenge","framework","relevance"],"substantiate"]),

make_spec(index=22, slug="c1-synthesizing-sources", topic="school-study", title="Synthesizing Sources",
    vocab=[V("synthesize","synthesize","ترکیب تحلیلی کردن","verb"),V("converge","converge","همگرا شدن","verb"),V("diverge","diverge","واگرا شدن","verb"),V("corroborate","corroborate","تأیید مستقل کردن","verb"),V("source","source","منبع"),V("theme","theme","درون‌مایه"),V("contradiction","contradiction","تناقض"),V("integrate","integrate","یکپارچه کردن","verb")],
    utterances=[
        U("synth","A synthesis should organize sources around ideas, not simply summarize one source and then the next.","سنتز باید منابع رو حول ایده‌ها سازمان بده، نه اینکه فقط یکی‌یکی خلاصه‌شون کنه.","define_synthesis",["synthesize","source","theme"],1),
        U("converge","Three sources converge on the importance of access, even though they explain the access problem differently.","سه منبع روی اهمیت دسترسی همگرا هستن، با اینکه مشکل دسترسی رو متفاوت توضیح می‌دن.","identify_convergence",["converge","source"],1),
        U("diverge","The studies diverge most clearly on whether the observed change is temporary or structural.","مطالعات بیشتر از همه سر این اختلاف دارن که تغییر مشاهده‌شده موقته یا ساختاری.","identify_divergence",["diverge","contradiction"],2),
        U("corroborate","The interview data corroborate the timing described in the report, but not its explanation of the cause.","داده مصاحبه زمان‌بندی گزارش رو تأیید می‌کنه، ولی توضیحش درباره علت رو نه.","corroborate_selectively",["corroborate","source"],2),
        U("theme","A recurring theme across the literature is that implementation quality matters as much as policy design.","درون‌مایه تکراری در منابع اینه که کیفیت اجرا به اندازه طراحی سیاست مهمه.","identify_theme",["theme","synthesize"],3),
        U("contradict","What looks like a contradiction disappears once we notice that the sources are studying different populations.","چیزی که تناقض به نظر میاد وقتی می‌بینیم منابع جمعیت‌های متفاوتی رو بررسی می‌کنن از بین می‌ره.","resolve_contradiction",["contradiction","source"],3),
        U("integrate","I would integrate the quantitative trend with the qualitative explanation rather than treating either as complete on its own.","روند کمی رو با توضیح کیفی یکپارچه می‌کنم، به‌جای اینکه هرکدوم رو به‌تنهایی کامل بدونم.","integrate_evidence",["integrate","synthesize"],3),
        U("close","Taken together, the sources support a cautious explanation while leaving one important mechanism unresolved.","در کنار هم، منابع از یک توضیح محتاطانه حمایت می‌کنن و در عین حال یک سازوکار مهم رو حل‌نشده می‌ذارن.","synthesize_conclusion",["source","converge"],3),
    ], grammar=["advanced_reporting","cohesion_reference","participle_clauses"], fill=["The sources ___ on the overall trend but differ on its cause.",["converge","diverge","integrate","contradiction"],"converge"]),

make_spec(index=23, slug="c1-comparing-viewpoints", topic="simple-messages", title="Comparing Viewpoints",
    vocab=[V("viewpoint","viewpoint","دیدگاه"),V("overlap","overlap","هم‌پوشانی"),V("divergence","divergence","اختلاف"),V("assumption","assumption","فرض"),V("emphasis","emphasis","تأکید"),V("lens","lens","زاویه نگاه"),V("reconcile","reconcile","آشتی دادن / سازگار کردن","verb"),V("incompatible","incompatible","ناسازگار","adjective")],
    utterances=[
        U("overlap","The two viewpoints overlap on the diagnosis but diverge sharply on what should be done next.","دو دیدگاه روی تشخیص مشکل هم‌پوشانی دارن ولی درباره قدم بعدی شدیداً متفاوتن.","compare_overlap",["viewpoint","overlap","divergence"],1),
        U("assumption","Their disagreement partly reflects different assumptions about how much responsibility individuals can realistically carry.","بخشی از اختلافشون از فرض‌های متفاوت درباره میزان مسئولیتی میاد که واقعاً می‌شه روی دوش فرد گذاشت.","compare_assumptions",["assumption","viewpoint"],1),
        U("emphasis","One author places the emphasis on freedom of choice; the other emphasizes unequal starting conditions.","یک نویسنده روی آزادی انتخاب تأکید می‌کنه؛ اون یکی روی نابرابری شرایط شروع.","compare_emphasis",["emphasis","lens"],2),
        U("lens","Seen through an economic lens, the policy looks efficient; through a social lens, the distributional effects become more visible.","از زاویه اقتصادی سیاست کارا به نظر میاد؛ از زاویه اجتماعی، اثرات توزیعی بیشتر دیده می‌شن.","compare_lenses",["lens","viewpoint"],2),
        U("reconcile","The positions are not fully incompatible; they can be reconciled if we separate the short-term and long-term objectives.","موضع‌ها کاملاً ناسازگار نیستن؛ اگر اهداف کوتاه‌مدت و بلندمدت رو جدا کنیم می‌شه بینشون سازگاری ساخت.","reconcile_views",["reconcile","incompatible"],3),
        U("limit","I would avoid flattening the disagreement into 'optimistic versus pessimistic' because both positions are more specific than that.","اختلاف رو به «خوش‌بین در برابر بدبین» تقلیل نمی‌دم چون هر دو موضع دقیق‌تر از اینن.","avoid_false_binary",["viewpoint","divergence"],3),
        U("common","A fair comparison should identify common ground before focusing on the point of maximum divergence.","مقایسه منصفانه باید قبل از تمرکز روی شدیدترین اختلاف، زمینه مشترک رو مشخص کنه.","structure_comparison",["overlap","divergence"],3),
        U("close","The most useful distinction is not which viewpoint is right in general, but which assumptions hold in this context.","مفیدترین تمایز این نیست که کدوم دیدگاه کلاً درسته؛ اینه که کدوم فرض‌ها در این زمینه برقرارن.","evaluate_viewpoints",["viewpoint","assumption"],3),
    ], grammar=["cleft_sentences","concession_rebuttal","cohesion_reference"], fill=["The two perspectives are not necessarily ___; they share some common ground.",["incompatible","reconciled","overlap","emphasis"],"incompatible"]),

make_spec(index=24, slug="c1-evaluating-methods", topic="school-study", title="Evaluating Methods",
    vocab=[V("methodology","methodology","روش‌شناسی"),V("sample","sample","نمونه"),V("variable","variable","متغیر"),V("reliability","reliability","پایایی"),V("validity","validity","اعتبار سنجش"),V("limitation","limitation","محدودیت"),V("replicate","replicate","تکرارپذیر کردن / بازتولید کردن","verb"),V("control","control","کنترل پژوهشی")],
    utterances=[
        U("method","The methodology is appropriate for exploring experience, but less suited to estimating how common that experience is.","روش‌شناسی برای بررسی تجربه مناسبه، ولی برای برآورد اینکه اون تجربه چقدر رایجه کمتر مناسبه.","evaluate_method_fit",["methodology","validity"],1),
        U("sample","The sample is large, although size alone does not make it representative of the wider population.","نمونه بزرگه، ولی بزرگی به‌تنهایی باعث نمی‌شه نماینده جمعیت گسترده‌تر باشه.","evaluate_sample",["sample","limitation"],1),
        U("variable","One variable changed at the same time as the intervention, which makes the causal interpretation less secure.","یک متغیر هم‌زمان با مداخله تغییر کرده و همین تفسیر علّی رو کمتر مطمئن می‌کنه.","identify_confound",["variable","control"],2),
        U("reliability","The measure appears reliable across repeated tests, but its validity for this particular construct is less obvious.","سنجش در آزمون‌های تکراری پایا به نظر میاد، ولی اعتبارش برای این مفهوم خاص کمتر روشنه.","distinguish_reliability_validity",["reliability","validity"],2),
        U("limitation","A limitation is not automatically a fatal flaw; the question is whether it changes the conclusion we are entitled to draw.","محدودیت لزوماً نقص کشنده نیست؛ سؤال اینه که آیا نتیجه‌ای رو که حق داریم بگیریم عوض می‌کنه یا نه.","interpret_limitation",["limitation","validity"],3),
        U("replicate","I would be more confident if the result were replicated with a different sample and a slightly different design.","اگر نتیجه با نمونه متفاوت و طراحی کمی متفاوت تکرار می‌شد اعتماد بیشتری می‌کردم.","request_replication",["replicate","sample"],3),
        U("control","The control condition helps, but it does not eliminate every plausible alternative explanation.","شرایط کنترل کمک می‌کنه، ولی همه توضیح‌های جایگزین محتمل رو حذف نمی‌کنه.","evaluate_control",["control","methodology"],3),
        U("close","Overall, the method supports a useful finding, but not the strongest version of the claim being made.","در مجموع روش از یک یافته مفید حمایت می‌کنه، ولی نه از قوی‌ترین نسخه ادعایی که مطرح شده.","reach_method_judgment",["methodology","limitation"],3),
    ], grammar=["advanced_hedging","nominalisation","advanced_passive"], fill=["The result would be stronger if another team could ___ it.",["replicate","control","sample","variable"],"replicate"]),

make_spec(index=25, slug="c1-presenting-arguments", topic="questions", title="Presenting Arguments",
    vocab=[V("argument","argument","استدلال"),V("claim","claim","ادعا"),V("premise","premise","مقدمه / پیش‌فرض"),V("evidence","evidence","شواهد"),V("implication","implication","پیامد منطقی"),V("rebuttal","rebuttal","پاسخ به استدلال مخالف"),V("sequence","sequence","توالی"),V("signpost","signpost","مسیر بحث را علامت‌گذاری کردن","verb")],
    utterances=[
        U("claim","I would state the claim early, then make clear which evidence supports it and which evidence merely provides context.","ادعا رو زود مطرح می‌کنم و بعد روشن می‌کنم کدوم شواهد حمایتش می‌کنن و کدوم فقط زمینه می‌دن.","structure_claim",["claim","evidence"],1),
        U("premise","The argument depends on a premise the audience may not share, so I would surface it before moving to the conclusion.","استدلال به پیش‌فرضی وابسته‌ست که شاید مخاطب قبولش نداشته باشه، پس قبل از نتیجه صریحش می‌کنم.","surface_premise",["argument","premise"],1),
        U("sequence","The sequence matters: if the audience hears the recommendation before the problem is established, the proposal can feel predetermined.","توالی مهمه؛ اگر مخاطب قبل از روشن شدن مشکل توصیه رو بشنوه، پیشنهاد ممکنه از قبل تصمیم‌گرفته‌شده به نظر بیاد.","sequence_argument",["sequence","claim"],2),
        U("signpost","I would signpost the shift from evidence to interpretation so the audience can see where judgment enters the argument.","تغییر از شواهد به تفسیر رو علامت‌گذاری می‌کنم تا مخاطب ببینه قضاوت کجا وارد استدلال می‌شه.","signpost_reasoning",["signpost","evidence"],2),
        U("rebuttal","A rebuttal is strongest when it addresses the best version of the opposing argument rather than an easy caricature.","پاسخ مخالف وقتی قوی‌تره که به بهترین نسخه استدلال طرف مقابل جواب بده، نه یک کاریکاتور ساده‌شده.","build_rebuttal",["rebuttal","argument"],3),
        U("implication","After each major point, I would make the practical implication explicit instead of assuming the audience will infer it.","بعد از هر نکته اصلی پیامد عملی رو صریح می‌کنم، به‌جای اینکه فرض کنم مخاطب خودش استنباطش می‌کنه.","state_implication",["implication","signpost"],3),
        U("limit","The conclusion should be no broader than the evidence allows; otherwise a strong argument can be weakened by an overstated ending.","نتیجه نباید از چیزی که شواهد اجازه می‌دن گسترده‌تر باشه؛ وگرنه پایان اغراق‌آمیز یک استدلال قوی رو ضعیف می‌کنه.","calibrate_conclusion",["evidence","claim"],3),
        U("close","To close, I would restate the claim in light of the evidence rather than simply repeating the opening sentence.","در پایان ادعا رو با توجه به شواهد دوباره بیان می‌کنم، نه اینکه فقط جمله اول رو تکرار کنم.","close_argument",["claim","evidence"],3),
    ], grammar=["discourse_management","rhetorical_questions","cleft_sentences"], fill=["A clear presentation should ___ the shift from evidence to interpretation.",["signpost","rebuttal","premise","sequence"],"signpost"]),

make_spec(index=26, slug="c1-formal-proposals", topic="jobs", title="Formal Proposals",
    vocab=[V("proposal","proposal","پیشنهاد رسمی"),V("rationale","rationale","منطق / توجیه"),V("feasible","feasible","شدنی","adjective"),V("implementation","implementation","اجرا"),V("resource","resource","منبع"),V("recommendation","recommendation","توصیه"),V("contingency","contingency","برنامه جایگزین"),V("criterion","criterion","معیار")],
    utterances=[
        U("rationale","The proposal should begin with the rationale for change, not with the details of the preferred solution.","پیشنهاد باید با منطق نیاز به تغییر شروع بشه، نه جزئیات راه‌حل ترجیحی.","state_rationale",["proposal","rationale"],1),
        U("feasible","The recommendation is desirable in principle, but we need to show that it is feasible within the current staffing and budget constraints.","توصیه در اصل مطلوبه، ولی باید نشون بدیم با محدودیت نیروی فعلی و بودجه شدنیه.","demonstrate_feasibility",["recommendation","feasible","resource"],1),
        U("criterion","I would make the evaluation criteria explicit so alternatives can be compared against the same standard.","معیارهای ارزیابی رو صریح می‌کنم تا گزینه‌ها با استاندارد یکسان مقایسه بشن.","set_criteria",["criterion","proposal"],2),
        U("implementation","A credible proposal needs an implementation path, including who owns each stage and what happens if a dependency slips.","پیشنهاد معتبر مسیر اجرا لازم داره، از جمله مسئول هر مرحله و اینکه اگر وابستگی عقب افتاد چه می‌شه.","outline_implementation",["implementation","contingency"],2),
        U("resource","The resource request should distinguish essential capacity from capacity that would merely make delivery more comfortable.","درخواست منابع باید ظرفیت ضروری رو از ظرفیتی که فقط اجرا رو راحت‌تر می‌کنه جدا کنه.","justify_resources",["resource","feasible"],3),
        U("contingency","I would include a contingency for the highest-impact risk rather than listing every imaginable problem.","برای ریسک با بیشترین اثر یک برنامه جایگزین می‌ذارم، نه اینکه هر مشکل قابل تصور رو فهرست کنم.","include_contingency",["contingency","implementation"],3),
        U("formal","It is essential that the proposal be reviewed against the agreed criteria before funding is approved.","ضروریه پیشنهاد قبل از تأیید بودجه بر اساس معیارهای توافق‌شده بررسی بشه.","state_formal_requirement",["proposal","criterion"],3),
        U("close","The final recommendation should make the decision easy to evaluate even for someone who has not followed the project closely.","توصیه نهایی باید تصمیم رو حتی برای کسی که پروژه رو نزدیک دنبال نکرده قابل ارزیابی کنه.","close_proposal",["recommendation","rationale"],3),
    ], grammar=["formal_subjunctive","nominalisation","advanced_passive"], fill=["A credible proposal must show that the plan is financially and operationally ___.",["feasible","contingency","criterion","rationale"],"feasible"]),

make_spec(index=27, slug="c1-media-framing-bias", topic="simple-messages", title="Media Framing & Bias",
    vocab=[V("framing","framing","قاب‌بندی رسانه‌ای"),V("bias","bias","سوگیری"),V("headline","headline","تیتر"),V("omit","omit","حذف کردن","verb"),V("portray","portray","به تصویر کشیدن","verb"),V("source","source","منبع"),V("loaded","loaded","باردار / جهت‌دار","adjective"),V("context","context","زمینه")],
    utterances=[
        U("framing","Two reports can contain the same facts while framing the story around entirely different questions.","دو گزارش می‌تونن همون واقعیت‌ها رو داشته باشن ولی داستان رو حول سؤال‌های کاملاً متفاوت قاب‌بندی کنن.","compare_framing",["framing","context"],1),
        U("headline","The headline is technically defensible, but it foregrounds the most dramatic interpretation of an uncertain result.","تیتر از نظر فنی قابل دفاعه، ولی نمایشی‌ترین تفسیر یک نتیجه نامطمئن رو برجسته می‌کنه.","evaluate_headline",["headline","framing"],1),
        U("omit","What a report omits can shape the reader's interpretation as strongly as the information it includes.","چیزی که گزارش حذف می‌کنه می‌تونه به اندازه اطلاعاتی که میاره برداشت خواننده رو شکل بده.","analyze_omission",["omit","context"],2),
        U("portray","Notice how the two outlets portray the same protest either as disruption or as civic participation.","ببین دو رسانه همون اعتراض رو یکی اخلال و یکی مشارکت مدنی به تصویر می‌کشن.","compare_portrayal",["portray","framing"],2),
        U("loaded","The word 'admit' is more loaded than 'say' because it implies the speaker was previously hiding or resisting something.","واژه admit از say جهت‌دارتره چون القا می‌کنه گوینده قبلاً چیزی رو پنهان می‌کرده یا مقاومت داشته.","identify_loaded_language",["loaded","bias"],3),
        U("source","A source can be credible and still have an interest that affects which facts it emphasizes.","یک منبع می‌تونه معتبر باشه و در عین حال منفعتی داشته باشه که روی چیزهایی که برجسته می‌کنه اثر بذاره.","evaluate_source_interest",["source","bias"],3),
        U("bias2","Bias does not always mean false information; it can appear in selection, emphasis, sequence, or context.","سوگیری همیشه یعنی اطلاعات غلط نیست؛ می‌تونه در انتخاب، تأکید، ترتیب یا زمینه ظاهر بشه.","define_bias",["bias","context"],3),
        U("close","I would compare the framing across sources before deciding which interpretation the evidence itself best supports.","قبل از تصمیم درباره اینکه خود شواهد از کدوم تفسیر بیشتر حمایت می‌کنن قاب‌بندی منابع مختلف رو مقایسه می‌کنم.","compare_sources",["framing","source"],3),
    ], grammar=["distancing","advanced_reporting","cleft_sentences"], fill=["The article uses somewhat ___ language to describe one side of the dispute.",["loaded","feasible","reciprocal","robust"],"loaded"]),

make_spec(index=28, slug="c1-news-analysis", topic="simple-messages", title="News Analysis",
    vocab=[V("development","development","تحول"),V("implication","implication","پیامد"),V("verify","verify","راستی‌آزمایی کردن","verb"),V("confirmed","confirmed","تأییدشده","adjective"),V("preliminary","preliminary","اولیه","adjective"),V("context","context","زمینه"),V("stake","stake","منفعت / موضوع در خطر"),V("unfold","unfold","در حال شکل‌گیری بودن","verb")],
    utterances=[
        U("development","The most important development is not the announcement itself but the fact that implementation has been brought forward by six months.","مهم‌ترین تحول خود اعلام خبر نیست؛ اینه که اجرا شش ماه جلو افتاده.","identify_key_development",["development","implication"],1),
        U("prelim","The figures are preliminary, so I would report the direction of change without treating the exact percentage as settled.","اعداد اولیه‌ان، پس جهت تغییر رو گزارش می‌کنم بدون اینکه درصد دقیق رو قطعی بدونم.","handle_preliminary_data",["preliminary","confirmed"],1),
        U("verify","Before repeating the claim, I would verify whether it comes from an independent source or from one party to the dispute.","قبل از تکرار ادعا بررسی می‌کنم از منبع مستقل اومده یا یکی از طرف‌های اختلاف.","verify_claim",["verify","context"],2),
        U("context","Without the previous three policy changes as context, today's announcement looks much more sudden than it actually is.","بدون سه تغییر سیاست قبلی به‌عنوان زمینه، اعلام امروز خیلی ناگهانی‌تر از واقعیت به نظر میاد.","add_context",["context","development"],2),
        U("stake","Different actors have different stakes in how the story is interpreted, which matters when evaluating their comments.","بازیگران مختلف منفعت‌های متفاوتی در نحوه تفسیر خبر دارن و این در ارزیابی حرف‌هاشون مهمه.","identify_stakes",["stake","verify"],3),
        U("unfold","Because the situation is still unfolding, a useful analysis should distinguish confirmed facts from plausible scenarios.","چون وضعیت هنوز در حال شکل‌گیریه، تحلیل خوب باید واقعیت‌های تأییدشده رو از سناریوهای محتمل جدا کنه.","analyze_live_story",["unfold","confirmed"],3),
        U("implication","One likely implication is increased short-term uncertainty, although the longer-term effect depends on the final rules.","یک پیامد محتمل افزایش عدم قطعیت کوتاه‌مدته، هرچند اثر بلندمدت به قوانین نهایی بستگی داره.","infer_implication",["implication","preliminary"],3),
        U("close","At this stage, the strongest conclusion is about what changed, not about who will ultimately benefit.","در این مرحله قوی‌ترین نتیجه درباره چیزیه که تغییر کرده، نه اینکه در نهایت چه کسی سود می‌بره.","calibrate_news_conclusion",["development","confirmed"],3),
    ], grammar=["distancing","reporting_passive","advanced_hedging"], fill=["Because the story is still ___, some conclusions remain provisional.",["unfolding","verified","confirmed","stake"],"unfolding"]),

make_spec(index=29, slug="c1-tech-ethics", topic="common-actions", title="Technology & Ethics",
    vocab=[V("ethical","ethical","اخلاقی","adjective"),V("consent","consent","رضایت آگاهانه"),V("accountability","accountability","پاسخ‌گویی"),V("transparency","transparency","شفافیت"),V("automate","automate","خودکار کردن","verb"),V("bias","bias","سوگیری"),V("tradeoff","trade-off","بده‌بستان"),V("oversight","oversight","نظارت")],
    utterances=[
        U("ethical","The ethical question is not simply whether the system works, but who carries the risk when it fails.","سؤال اخلاقی فقط این نیست که سیستم کار می‌کنه یا نه؛ اینه که وقتی خراب می‌شه چه کسی ریسک رو تحمل می‌کنه.","frame_ethics_question",["ethical","accountability"],1),
        U("consent","Consent is weak if people technically agree without understanding what data will be collected or how it may be used.","رضایت وقتی ضعیفه که افراد فنی موافقت کنن ولی نفهمن چه داده‌ای جمع می‌شه یا چطور استفاده می‌شه.","evaluate_consent",["consent","transparency"],1),
        U("automate","Automating a decision can improve consistency while making individual exceptions harder to notice.","خودکار کردن تصمیم می‌تونه یکدستی رو بهتر کنه ولی دیدن استثناهای فردی رو سخت‌تر کنه.","evaluate_automation",["automate","tradeoff"],2),
        U("bias","A system can reproduce bias even when no individual developer intends to discriminate.","سیستم می‌تونه سوگیری رو بازتولید کنه حتی وقتی هیچ توسعه‌دهنده‌ای قصد تبعیض نداره.","explain_systemic_bias",["bias","ethical"],2),
        U("oversight","Independent oversight matters most where the affected person cannot easily understand or challenge the decision.","نظارت مستقل جایی مهم‌تره که فرد تحت‌تأثیر نتونه راحت تصمیم رو بفهمه یا بهش اعتراض کنه.","justify_oversight",["oversight","accountability"],3),
        U("transparency","Transparency should make meaningful scrutiny possible; publishing a thousand pages nobody can interpret is not enough.","شفافیت باید بررسی معنادار رو ممکن کنه؛ انتشار هزار صفحه‌ای که کسی نمی‌فهمه کافی نیست.","define_transparency",["transparency","oversight"],3),
        U("tradeoff","The trade-off is not privacy versus innovation in the abstract; it depends on which data are necessary for which benefit.","بده‌بستان به‌صورت کلی حریم خصوصی در برابر نوآوری نیست؛ بستگی داره کدوم داده برای کدوم فایده واقعاً لازمه.","specify_tradeoff",["tradeoff","consent"],3),
        U("close","Accountability requires a route for correcting harmful decisions, not merely an explanation of how they were produced.","پاسخ‌گویی مسیر اصلاح تصمیم آسیب‌زا می‌خواد، نه فقط توضیح اینکه چطور تولید شده.","define_accountability",["accountability","oversight"],3),
    ], grammar=["cleft_sentences","nominalisation","formal_subjunctive"], fill=["Independent ___ can help challenge decisions that are difficult to inspect internally.",["oversight","consent","bias","trade-off"],"oversight"]),

make_spec(index=30, slug="c1-environment-policy", topic="common-actions", title="Environment & Policy",
    vocab=[V("emission","emission","انتشار آلاینده"),V("incentive","incentive","مشوق"),V("regulation","regulation","مقررات"),V("transition","transition","گذار"),V("burden","burden","بار / هزینه تحمیلی"),V("effective","effective","مؤثر","adjective"),V("equitable","equitable","منصفانه","adjective"),V("implementation","implementation","اجرا")],
    utterances=[
        U("effect","A policy can reduce emissions overall while distributing the financial burden very unevenly.","یک سیاست می‌تونه در مجموع انتشار رو کم کنه ولی بار مالی رو خیلی نابرابر توزیع کنه.","identify_distributional_effect",["emission","burden"],1),
        U("incentive","The incentive changes behavior only if the alternative is affordable and realistically available.","مشوق فقط وقتی رفتار رو عوض می‌کنه که گزینه جایگزین مقرون‌به‌صرفه و واقعاً در دسترس باشه.","evaluate_incentive",["incentive","effective"],1),
        U("regulation","Regulation may be necessary where individual choices cannot address a problem created by shared infrastructure.","جایی که انتخاب فردی نمی‌تونه مشکلی رو که زیرساخت مشترک ساخته حل کنه، مقررات ممکنه لازم باشه.","justify_regulation",["regulation","implementation"],2),
        U("transition","A credible transition plan needs to explain not only the destination but how affected workers and communities get there.","برنامه گذار معتبر باید فقط مقصد رو نگه؛ باید توضیح بده کارگرها و جوامع تحت‌تأثیر چطور به اونجا می‌رسن.","evaluate_transition",["transition","equitable"],2),
        U("equitable","An effective policy is not automatically equitable, and an equitable policy may require additional implementation cost.","سیاست مؤثر لزوماً منصفانه نیست و سیاست منصفانه ممکنه هزینه اجرای بیشتری بخواد.","distinguish_effectiveness_equity",["effective","equitable"],3),
        U("burden","If the burden falls mainly on people with the fewest alternatives, public resistance is hardly surprising.","اگر بار اصلی روی افرادی بیفته که کمترین گزینه جایگزین رو دارن، مقاومت عمومی اصلاً عجیب نیست.","explain_resistance",["burden","transition"],3),
        U("implementation","The implementation details determine whether the regulation changes behavior or simply creates paperwork.","جزئیات اجرا تعیین می‌کنه مقررات رفتار رو عوض کنه یا فقط کاغذبازی بسازه.","evaluate_implementation",["implementation","regulation"],3),
        U("close","The strongest policy package may combine regulation, incentives, and targeted support rather than relying on one instrument alone.","قوی‌ترین بسته سیاستی شاید مقررات، مشوق و حمایت هدفمند رو ترکیب کنه، نه اینکه فقط به یک ابزار تکیه کنه.","synthesize_policy",["regulation","incentive","effective"],3),
    ], grammar=["concession_rebuttal","complex_prepositions","nominalisation"], fill=["A policy may be effective without being equally ___.",["equitable","emission","transition","burden"],"equitable"]),
]

if __name__ == "__main__":
    write_units(UNITS)
