#!/usr/bin/env python3
from scripts.generate_c2_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=41, slug="c2-figurative-language", topic="simple-messages", title="Figurative Language, Connotation & Conceptual Metaphor",
    vocab=[V("metaphor","metaphor","استعاره"),V("connotation","connotation","بار معنایی"),V("figurative","figurative","مجازي / غیرلفظی","adjective"),V("image_schema","image schema","الگوی تصویری ذهنی","noun_phrase"),V("idiom","idiom","اصطلاح"),V("evoke","evoke","تداعی کردن","verb"),V("literal","literal","لفظی","adjective"),V("resonance","resonance","طنین معنایی")],
    utterances=[
        U("metaphor","Calling the reform a 'bridge' frames it as a temporary connection between two states rather than a destination in itself.","اینکه اصلاحات رو bridge بنامیم اون رو به‌عنوان اتصال موقت بین دو وضعیت قاب‌بندی می‌کنه نه مقصد نهایی.","analyze_conceptual_metaphor",["metaphor","figurative"],1),
        U("literal","A literal paraphrase preserves the basic information but often loses the emotional and evaluative work done by the original image.","بازگویی لفظی اطلاعات اصلی رو نگه می‌داره ولی اغلب کار احساسی و ارزشی تصویر اصلی رو از دست می‌ده.","compare_literal_figurative",["literal","resonance"],1),
        U("connotation","The phrase 'tighten the net' carries a connotation of pursuit and restriction that 'improve enforcement' does not.","عبارت tighten the net بار معنایی تعقیب و محدودیت داره که improve enforcement نداره.","analyze_connotation",["connotation","evoke"],2),
        U("schema","The argument repeatedly uses an image schema of upward movement, which subtly associates progress with height and decline with descent.","استدلال بارها از الگوی تصویری حرکت رو به بالا استفاده می‌کنه و ظریفاً پیشرفت رو با ارتفاع و پسرفت رو با پایین رفتن پیوند می‌ده.","analyze_image_schema",["image_schema","metaphor"],2),
        U("idiom","An idiom may be fully conventional for native speakers while remaining opaque to a learner who knows every individual word.","یک اصطلاح ممکنه برای گوینده بومی کاملاً عادی باشه ولی برای زبان‌آموزی که تک‌تک واژه‌ها رو می‌دونه همچنان نامفهوم بمونه.","explain_idiom_opacity",["idiom","literal"],3),
        U("evoke","The writer chooses 'drift' rather than 'change' because it evokes movement without deliberate control.","نویسنده drift رو به‌جای change انتخاب می‌کنه چون حرکت بدون کنترل آگاهانه رو تداعی می‌کنه.","interpret_word_image",["evoke","connotation"],3),
        U("resonance","The metaphor gains resonance later when the same image returns in a different emotional context.","استعاره بعداً وقتی همون تصویر در زمینه احساسی متفاوت برمی‌گرده طنین بیشتری پیدا می‌کنه.","track_metaphor_resonance",["resonance","metaphor"],3),
        U("summary","Advanced figurative comprehension asks what an image selects, what it hides, what it evokes and why that framing matters in context.","فهم پیشرفته زبان تصویری می‌پرسه یک تصویر چی رو انتخاب می‌کنه، چی رو پنهان می‌کنه، چی رو تداعی می‌کنه و چرا این قاب‌بندی در اون زمینه مهمه.","summarize_figurative_analysis",["figurative","connotation","metaphor"],3),
    ], grammar=["cleft_sentences","cohesion_reference","advanced_hedging"], fill=["The word 'drift' can ___ a sense of movement without deliberate control.",["evoke","delegate","triangulate","mitigate"],"evoke"]),

make_spec(index=42, slug="c2-register-voice", topic="polite-language", title="Register, Voice & Stylistic Identity",
    vocab=[V("register","register","سطح و سبک زبانی"),V("voice","voice","صدای نویسنده / گوینده"),V("formality","formality","رسمیت"),V("stance","stance","موضع"),V("cadence","cadence","ریتم جمله"),V("compression","compression","فشرده‌سازی"),V("deference","deference","ملاحظه و احترام"),V("persona","persona","شخصیت زبانی")],
    utterances=[
        U("register","Register is not a ladder from bad to good; it is a set of choices that fit different audiences, purposes and relationships.","رجیستر نردبان بد تا خوب نیست؛ مجموعه انتخاب‌هاییه که با مخاطب، هدف و رابطه‌های متفاوت جور می‌شن.","define_register",["register","formality"],1),
        U("voice","A strong professional voice can remain concise and personal without becoming casual or vague.","صدای حرفه‌ای قوی می‌تونه کوتاه و شخصی بمونه بدون اینکه بیش از حد خودمونی یا مبهم بشه.","shape_professional_voice",["voice","persona"],1),
        U("formality","Increasing formality by replacing every short word with a longer one often makes prose less natural rather than more professional.","رسمی‌تر کردن متن با عوض کردن هر واژه کوتاه با واژه بلند معمولاً متن رو غیرطبیعی‌تر می‌کنه نه حرفه‌ای‌تر.","avoid_fake_formality",["formality","register"],2),
        U("stance","Small choices such as 'I would suggest' versus 'we recommend' change both stance and institutional authority.","انتخاب‌های کوچیکی مثل I would suggest در برابر we recommend هم موضع و هم قدرت سازمانی رو عوض می‌کنن.","analyze_stance_register",["stance","voice"],2),
        U("cadence","Cadence matters in speeches because sentence length and pause structure affect authority, warmth and emphasis.","ریتم در سخنرانی مهمه چون طول جمله و ساختار مکث روی اقتدار، صمیمیت و تأکید اثر می‌ذاره.","control_cadence",["cadence","voice"],3),
        U("compression","Executive writing often needs compression, but excessive compression can hide assumptions the reader needs to evaluate.","نوشتار مدیریتی معمولاً فشردگی می‌خواد، ولی فشردگی زیاد می‌تونه فرض‌هایی رو که خواننده باید ارزیابی کنه پنهان کنه.","balance_compression",["compression","register"],3),
        U("deference","Deference should be calibrated to power and relationship; too much can sound evasive, too little can sound presumptuous.","ملاحظه باید با قدرت و رابطه تنظیم بشه؛ زیادی اون می‌تونه طفره‌رو و کمی اون می‌تونه پررو به نظر برسه.","calibrate_deference",["deference","formality"],3),
        U("summary","Stylistic mastery means being able to change register deliberately while keeping a recognizable voice and precise meaning.","تسلط سبکی یعنی بتونی آگاهانه رجیستر رو عوض کنی و در عین حال صدای قابل‌شناسایی و معنای دقیق رو حفظ کنی.","summarize_register_voice",["register","voice","persona"],3),
    ], grammar=["register_shift","ellipsis_substitution","reformulation"], fill=["A writer can shift ___ while preserving the same core meaning.",["register","trajectory","remedy","validity"],"register"]),

make_spec(index=43, slug="c2-mediation-reframing", topic="requests", title="Mediation, Reframing & Interest-Based Resolution",
    vocab=[V("mediate","mediate","میانجی‌گری کردن","verb"),V("reframe","reframe","بازقاب‌بندی کردن","verb"),V("interest","interest","منفعت / نیاز زیرین"),V("position","position","موضع اعلام‌شده"),V("neutral","neutral","بی‌طرف","adjective"),V("acknowledge","acknowledge","به رسمیت شناختن","verb"),V("overlap","overlap","هم‌پوشانی"),V("proposal","proposal","پیشنهاد")],
    utterances=[
        U("position","Their positions conflict—one wants immediate closure and the other wants delay—but their underlying interests overlap more than the positions suggest.","مواضعشون متضاده؛ یکی بستن فوری رو می‌خواد و یکی تأخیر رو، ولی نیازهای زیرینشون بیشتر از چیزی که مواضع نشون می‌ده هم‌پوشانی داره.","separate_positions_interests",["position","interest","overlap"],1),
        U("reframe","I would reframe 'you keep blocking us' as 'you need stronger evidence before accepting irreversible changes.'", "عبارت «تو همیشه جلوی ما رو می‌گیری» رو این‌طور بازقاب‌بندی می‌کنم: «قبل از پذیرفتن تغییر برگشت‌ناپذیر به شواهد قوی‌تری نیاز داری.»","reframe_blame",["reframe","neutral"],1),
        U("ack","Mediation works better when each side hears its concern accurately acknowledged before being asked to consider compromise.","میانجی‌گری وقتی بهتر کار می‌کنه که هر طرف قبل از درخواست سازش، بشنوه نگرانی‌ش دقیق فهمیده و به رسمیت شناخته شده.","acknowledge_both_sides",["mediate","acknowledge"],2),
        U("neutral","Neutral language should reduce unnecessary blame without flattening real differences in responsibility or impact.","زبان بی‌طرف باید سرزنش اضافه رو کم کنه بدون اینکه تفاوت واقعی در مسئولیت یا اثر رو صاف و بی‌معنا کنه.","use_neutral_language",["neutral","reframe"],2),
        U("overlap","The practical overlap is narrow but sufficient: both sides want a review before the next irreversible step.","هم‌پوشانی عملی محدوده ولی کافیه: هر دو طرف قبل از مرحله برگشت‌ناپذیر بعدی بازبینی می‌خوان.","identify_overlap",["overlap","interest"],3),
        U("proposal","A useful proposal should answer the interests we surfaced, not merely split the difference between the opening positions.","پیشنهاد مفید باید به نیازهای زیرینی که پیدا کردیم جواب بده، نه اینکه فقط وسط دو موضع اولیه رو بگیره.","build_interest_based_proposal",["proposal","interest"],3),
        U("fair","I would test the wording with both sides to make sure the reframing feels accurate rather than strategically convenient to the mediator.","عبارت رو با هر دو طرف چک می‌کنم تا مطمئن شم بازقاب‌بندی واقعاً دقیق حس می‌شه نه فقط برای میانجی راحت و مفیده.","test_reframing_fairness",["reframe","mediate"],3),
        U("summary","Advanced mediation preserves substantive disagreement while translating accusations into needs, constraints and proposals that can actually be negotiated.","میانجی‌گری پیشرفته اختلاف واقعی رو حفظ می‌کنه ولی اتهام‌ها رو به نیازها، محدودیت‌ها و پیشنهادهایی ترجمه می‌کنه که واقعاً قابل مذاکره‌ان.","summarize_mediation",["mediate","interest","proposal"],3),
    ], grammar=["diplomatic_language","reformulation","concession_rebuttal"], fill=["The mediator tried to ___ the accusation as an underlying need.",["reframe","corroborate","foreshadow","retract"],"reframe"]),

make_spec(index=44, slug="c2-complex-decision-matrix", topic="questions", title="Complex Decisions, Competing Criteria & Robust Choice",
    vocab=[V("criterion","criterion","معیار"),V("weighting","weighting","وزن‌دهی"),V("sensitivity","sensitivity","حساسیت نتیجه"),V("scenario","scenario","سناریو"),V("robust","robust","مقاوم","adjective"),V("dominate","dominate","غالب شدن","verb"),V("threshold","threshold","آستانه"),V("reversibility","reversibility","برگشت‌پذیری")],
    utterances=[
        U("criterion","We should agree on the criteria before scoring options; otherwise the preferred option can quietly determine the criteria afterward.","قبل از امتیاز دادن به گزینه‌ها باید روی معیارها توافق کنیم؛ وگرنه گزینه موردعلاقه می‌تونه بعداً بی‌صدا معیارها رو تعیین کنه.","set_decision_criteria",["criterion","weighting"],1),
        U("weight","The disagreement is not about the scores but the weighting: one team prioritizes speed while another prioritizes reversibility.","اختلاف درباره امتیازها نیست، درباره وزن‌دهیه: یک تیم سرعت رو مهم‌تر می‌دونه و تیم دیگه برگشت‌پذیری رو.","surface_weighting_disagreement",["weighting","reversibility"],1),
        U("sensitivity","A sensitivity check shows the recommendation changes only if cost is weighted almost twice as heavily as reliability.","بررسی حساسیت نشون می‌ده توصیه فقط وقتی عوض می‌شه که هزینه تقریباً دو برابر قابلیت اعتماد وزن بگیره.","run_sensitivity_reasoning",["sensitivity","weighting"],2),
        U("scenario","Option A dominates in the base case, but option B is more robust across the two adverse scenarios.","گزینه A در سناریوی پایه برتره، ولی گزینه B در دو سناریوی نامطلوب مقاوم‌تره.","compare_scenarios",["scenario","robust","dominate"],2),
        U("threshold","I would set a threshold: if implementation time exceeds six months, the value of option C falls sharply.","یک آستانه می‌ذارم: اگر زمان اجرا از شش ماه بیشتر بشه ارزش گزینه C شدیداً افت می‌کنه.","define_decision_threshold",["threshold","criterion"],3),
        U("reverse","Reversibility deserves extra weight under uncertainty because a correctable mistake is not equivalent to an irreversible one.","در عدم قطعیت، برگشت‌پذیری باید وزن بیشتری بگیره چون اشتباه قابل اصلاح با اشتباه برگشت‌ناپذیر یکی نیست.","value_reversibility",["reversibility","robust"],3),
        U("dominance","No option dominates on every criterion, so the final choice necessarily reflects a judgment about trade-offs rather than pure calculation.","هیچ گزینه‌ای روی همه معیارها برتر نیست، پس انتخاب نهایی ناچار شامل قضاوت درباره مصالحه‌هاست نه فقط محاسبه.","recognize_non_dominance",["dominate","criterion"],3),
        U("summary","A robust decision process makes criteria, weighting, thresholds, scenarios and reversibility explicit enough that reasonable disagreement can be located precisely.","فرایند تصمیم مقاوم معیارها، وزن‌دهی، آستانه‌ها، سناریوها و برگشت‌پذیری رو اون‌قدر روشن می‌کنه که محل دقیق اختلاف منطقی مشخص بشه.","summarize_complex_decision",["criterion","sensitivity","scenario"],3),
    ], grammar=["mixed_conditionals","nominalisation","discourse_management"], fill=["A ___ analysis checks whether small changes in assumptions alter the recommendation.",["sensitivity","validity","rapport","ambiguity"],"sensitivity"]),

make_spec(index=45, slug="c2-integrated-mastery", topic="simple-messages", title="Integrated C2 Mastery Capstone",
    vocab=[V("synthesize","synthesize","ترکیب تحلیلی کردن","verb"),V("mediate","mediate","میانجی‌گری کردن","verb"),V("infer","infer","استنباط کردن","verb"),V("reformulate","reformulate","بازفرمول‌بندی کردن","verb"),V("register","register","رجیستر"),V("qualify","qualify","دقیق و محدود کردن","verb"),V("evaluate","evaluate","ارزیابی کردن","verb"),V("adapt","adapt","سازگار کردن","verb")],
    utterances=[
        U("infer","First, infer the unstated concern without presenting your interpretation as certain fact.","اول نگرانی ناگفته رو استنباط کن بدون اینکه برداشتت رو واقعیت قطعی نشون بدی.","integrate_inference",["infer","qualify"],1),
        U("synth","Then synthesize the conflicting sources around the decision rather than summarizing them separately.","بعد منابع متعارض رو حول تصمیم ترکیب کن نه اینکه جداگانه خلاصه‌شون کنی.","integrate_synthesis",["synthesize","evaluate"],1),
        U("evaluate","Evaluate which evidence changes the recommendation and which evidence merely adds context.","ارزیابی کن کدوم شواهد توصیه رو عوض می‌کنن و کدوم فقط زمینه اضافه می‌کنن.","integrate_evaluation",["evaluate","synthesize"],2),
        U("mediate","When the stakeholders clash, mediate interests without pretending the underlying values are identical.","وقتی ذی‌نفع‌ها درگیرن، بین منافع میانجی‌گری کن بدون اینکه وانمود کنی ارزش‌های زیربنایی یکسانن.","integrate_mediation",["mediate","reformulate"],2),
        U("reform","If your first wording overstates the case, reformulate it immediately and preserve the distinction that matters.","اگر عبارت اولت ادعا رو بیش از حد قوی می‌کنه، همون لحظه بازفرمول‌بندی کن و تمایز مهم رو نگه دار.","integrate_reformulation",["reformulate","qualify"],3),
        U("register","Adapt register, directness and compression to the audience without changing the evidential strength of the message.","رجیستر، صراحت و فشردگی رو با مخاطب سازگار کن بدون اینکه قدرت شواهدی پیام رو تغییر بدی.","integrate_register",["register","adapt"],3),
        U("qualify","Qualify uncertainty precisely enough that caution does not become vagueness and confidence does not become overclaiming.","عدم قطعیت رو اون‌قدر دقیق محدود کن که احتیاط تبدیل به ابهام و اعتماد تبدیل به ادعای بیش از حد نشه.","integrate_qualification",["qualify","infer"],3),
        U("capstone","C2 mastery is flexible control: understanding layered meaning, choosing precise language, adapting in real time and preserving nuance under pressure.","تسلط C2 یعنی کنترل انعطاف‌پذیر: فهم معنای چندلایه، انتخاب زبان دقیق، سازگاری در لحظه و حفظ ظرافت زیر فشار.","state_c2_mastery",["adapt","register","evaluate"],3),
    ], grammar=["discourse_management","register_shift","advanced_hedging"], fill=["At C2, a speaker should be able to ___ register without losing precision.",["adapt","retract","corroborate","foreshadow"],"adapt"]),
]

if __name__ == "__main__":
    write_units(UNITS)
