#!/usr/bin/env python3
from scripts.generate_c1_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=31, slug="c1-social-change", topic="simple-messages", title="Social Change",
    vocab=[V("shift","shift","تغییر / جابه‌جایی"),V("norm","norm","هنجار"),V("attitude","attitude","نگرش"),V("generational","generational","نسلی","adjective"),V("accelerate","accelerate","شتاب دادن","verb"),V("resistance","resistance","مقاومت"),V("gradual","gradual","تدریجی","adjective"),V("institution","institution","نهاد")],
    utterances=[
        U("shift","The shift in attitudes looks sudden only if we ignore the gradual changes that had been accumulating for years.","تغییر نگرش فقط وقتی ناگهانی به نظر میاد که تغییرات تدریجی چند سال قبل رو نادیده بگیریم.","analyze_social_shift",["shift","attitude","gradual"],1),
        U("norm","A social norm can weaken before people feel comfortable saying openly that they no longer support it.","یک هنجار اجتماعی می‌تونه قبل از اینکه مردم راحت بگن دیگه حمایتش نمی‌کنن ضعیف بشه.","explain_norm_change",["norm","attitude"],1),
        U("generational","The difference is partly generational, but age alone does not explain the pattern across regions.","تفاوت تا حدی نسلیه، ولی سن به‌تنهایی الگو بین مناطق رو توضیح نمی‌ده.","qualify_generation_effect",["generational","shift"],2),
        U("accelerate","Technology may have accelerated the change by making previously isolated views more visible to one another.","فناوری شاید تغییر رو سریع‌تر کرده چون دیدگاه‌هایی که قبلاً جدا بودن رو برای هم قابل مشاهده کرده.","explain_acceleration",["accelerate","attitude"],2),
        U("resistance","Resistance is not always evidence that change will fail; it may reflect the speed or distribution of its costs.","مقاومت همیشه نشونه شکست تغییر نیست؛ شاید سرعت تغییر یا نحوه توزیع هزینه‌ها رو بازتاب بده.","interpret_resistance",["resistance","shift"],3),
        U("institution","Institutions often adapt more slowly than informal attitudes, which creates a period of visible tension between rules and practice.","نهادها معمولاً کندتر از نگرش‌های غیررسمی سازگار می‌شن و یک دوره تنش آشکار بین قانون و عمل ایجاد می‌کنن.","compare_institutional_change",["institution","attitude"],3),
        U("cause","I would be cautious about naming one cause when demographic, economic, and cultural changes are occurring at the same time.","وقتی تغییرات جمعیتی، اقتصادی و فرهنگی هم‌زمان رخ می‌دن، درباره معرفی یک علت واحد محتاطم.","avoid_single_cause",["shift","gradual"],3),
        U("close","The more useful question may be not whether society changed, but which changes became visible, legitimate, and institutionalized.","شاید سؤال مفیدتر این نباشه که جامعه تغییر کرد یا نه؛ این باشه که کدوم تغییرها قابل مشاهده، مشروع و نهادی شدن.","synthesize_social_change",["institution","norm"],3),
    ], grammar=["advanced_hedging","cleft_sentences","nominalisation"], fill=["Institutional change is often more ___ than shifts in informal attitudes.",["gradual","generational","resistant","accelerate"],"gradual"]),

make_spec(index=32, slug="c1-culture-identity", topic="likes-dislikes", title="Culture & Identity",
    vocab=[V("identity","identity","هویت"),V("belonging","belonging","احساس تعلق"),V("heritage","heritage","میراث فرهنگی"),V("adapt","adapt","سازگار شدن","verb"),V("stereotype","stereotype","کلیشه"),V("hybrid","hybrid","ترکیبی","adjective"),V("community","community","جامعه / اجتماع"),V("authentic","authentic","اصیل / واقعی","adjective")],
    utterances=[
        U("identity","Identity is rarely a single category; people may emphasize different parts of it in different contexts without being inconsistent.","هویت به‌ندرت فقط یک دسته‌ست؛ آدم‌ها ممکنه در زمینه‌های مختلف بخش‌های متفاوتش رو برجسته کنن بدون اینکه متناقض باشن.","describe_identity_complexity",["identity","community"],1),
        U("belonging","A sense of belonging can come from language, place, relationships, shared experience, or several of these at once.","احساس تعلق می‌تونه از زبان، مکان، رابطه، تجربه مشترک یا چندتاشون با هم بیاد.","explain_belonging",["belonging","identity"],1),
        U("heritage","Maintaining a connection to heritage does not necessarily mean preserving every custom unchanged.","حفظ ارتباط با میراث فرهنگی لزوماً یعنی نگه داشتن همه رسم‌ها بدون تغییر نیست.","qualify_heritage",["heritage","adapt"],2),
        U("stereotype","A stereotype becomes particularly limiting when it is treated as a script individuals are expected to perform.","کلیشه وقتی خیلی محدودکننده می‌شه که به‌عنوان نقشی در نظر گرفته بشه که انتظار دارن فرد اجراش کنه.","analyze_stereotype",["stereotype","identity"],2),
        U("hybrid","Hybrid identities are not incomplete versions of two cultures; they can be coherent identities in their own right.","هویت‌های ترکیبی نسخه ناقص دو فرهنگ نیستن؛ خودشون می‌تونن هویت‌های منسجم باشن.","challenge_binary_identity",["hybrid","identity"],3),
        U("authentic","The idea of being 'authentic' becomes complicated when other people define authenticity more narrowly than the person does.","ایده «اصیل بودن» وقتی پیچیده می‌شه که بقیه اصالت رو محدودتر از خود فرد تعریف کنن.","question_authenticity",["authentic","identity"],3),
        U("adapt2","Adapting to a new community can involve learning new conventions without abandoning previous forms of belonging.","سازگار شدن با جامعه جدید می‌تونه شامل یاد گرفتن قراردادهای جدید باشه بدون اینکه تعلق‌های قبلی کنار گذاشته بشن.","describe_adaptation",["adapt","community","belonging"],3),
        U("close","I would avoid talking about culture as if every member experiences it in the same way.","درباره فرهنگ طوری حرف نمی‌زنم که انگار همه اعضاش دقیقاً یک تجربه دارن.","avoid_cultural_generalization",["community","stereotype"],3),
    ], grammar=["concession_rebuttal","advanced_hedging","reduced_relatives"], fill=["A ___ identity can draw meaningfully on more than one cultural tradition.",["hybrid","authentic","stereotype","heritage"],"hybrid"]),

make_spec(index=33, slug="c1-boundaries-repair", topic="polite-language", title="Boundaries & Relationship Repair",
    vocab=[V("boundary","boundary","مرز رابطه"),V("breach","breach","نقض"),V("repair","repair","ترمیم کردن","verb"),V("accountability","accountability","پاسخ‌گویی"),V("trust","trust","اعتماد"),V("resentment","resentment","دلخوری عمیق"),V("reassure","reassure","اطمینان دادن","verb"),V("reciprocal","reciprocal","دوطرفه","adjective")],
    utterances=[
        U("boundary","A boundary is clearer when it describes what you will do, not only what you want the other person to stop doing.","مرز وقتی روشن‌تره که بگه خودت چه کاری می‌کنی، نه فقط اینکه طرف مقابل چه کاری رو متوقف کنه.","state_boundary",["boundary"],1),
        U("breach","The breach of trust was not just the mistake itself; it was the decision to hide it after being asked directly.","نقض اعتماد فقط خود اشتباه نبود؛ تصمیم به پنهان کردنش بعد از سؤال مستقیم بود.","identify_trust_breach",["breach","trust"],1),
        U("repair","Repair requires more than an apology if the behavior that caused the problem is likely to recur.","اگر رفتاری که مشکل ساخته احتمالاً تکرار می‌شه، ترمیم بیشتر از یک عذرخواهی می‌خواد.","define_repair",["repair","accountability"],2),
        U("account","Taking accountability means naming your part accurately without turning the conversation into self-punishment.","پاسخ‌گویی یعنی سهم خودت رو دقیق نام ببری بدون اینکه گفتگو رو تبدیل به خودسرزنشی کنی.","take_accountability",["accountability","repair"],2),
        U("resent","Unspoken resentment can make a minor disagreement carry the weight of several older ones.","دلخوری ناگفته می‌تونه باعث بشه یک اختلاف کوچک وزن چند اختلاف قدیمی رو هم حمل کنه.","identify_accumulated_resentment",["resentment","trust"],3),
        U("reassure","Reassurance is credible when it is tied to a concrete change rather than a promise that the problem will never happen again.","اطمینان دادن وقتی معتبره که به تغییر مشخص وصل باشه، نه قول اینکه مشکل هیچ‌وقت تکرار نمی‌شه.","reassure_credibly",["reassure","repair"],3),
        U("reciprocal","Healthy repair is reciprocal in the sense that both people can state needs, even if responsibility for the original harm is unequal.","ترمیم سالم از این نظر دوطرفه‌ست که هر دو نفر می‌تونن نیازهاشون رو بگن، حتی اگر مسئولیت آسیب اولیه برابر نباشه.","describe_reciprocal_repair",["reciprocal","accountability"],3),
        U("close","Restoring trust is usually a pattern of reliable behavior over time, not one perfect conversation.","برگردوندن اعتماد معمولاً الگویی از رفتار قابل اتکا در طول زمانه، نه یک گفتگوی بی‌نقص.","summarize_trust_repair",["trust","repair"],3),
    ], grammar=["diplomatic_language","cleft_sentences","concession_rebuttal"], fill=["Restoring ___ usually requires consistent behavior over time.",["trust","boundary","resentment","breach"],"trust"]),

make_spec(index=34, slug="c1-health-decisions", topic="basic-health", title="Health Decisions",
    vocab=[V("benefit","benefit","فایده"),V("risk","risk","ریسک"),V("evidence","evidence","شواهد"),V("uncertainty","uncertainty","عدم قطعیت"),V("preference","preference","ترجیح"),V("screening","screening","غربالگری"),V("intervention","intervention","مداخله"),V("informed","informed","آگاهانه","adjective")],
    utterances=[
        U("balance","A health decision may involve balancing a modest likely benefit against a small but serious risk.","تصمیم مربوط به سلامتی ممکنه شامل سنجیدن یک فایده کوچک اما محتمل در برابر ریسکی کم‌احتمال ولی جدی باشه.","weigh_health_tradeoff",["benefit","risk"],1),
        U("evidence","The evidence can tell us average outcomes, but it cannot decide how an individual should value each outcome.","شواهد می‌تونن نتیجه‌های متوسط رو بگن، ولی نمی‌تونن تصمیم بگیرن هر فرد باید چقدر برای هر نتیجه ارزش قائل بشه.","separate_evidence_values",["evidence","preference"],1),
        U("uncertainty","Uncertainty should be explained clearly rather than hidden behind a single precise-looking number.","عدم قطعیت باید روشن توضیح داده بشه، نه اینکه پشت یک عدد ظاهراً دقیق پنهان بشه.","communicate_uncertainty",["uncertainty","evidence"],2),
        U("screening","Screening can identify problems earlier, but it can also detect findings that would never have caused harm.","غربالگری می‌تونه مشکل رو زودتر پیدا کنه، ولی ممکنه چیزهایی رو هم پیدا کنه که هیچ‌وقت آسیب ایجاد نمی‌کردن.","evaluate_screening",["screening","benefit","risk"],2),
        U("informed","An informed choice requires understanding the realistic options, including the option of waiting or doing nothing for now.","انتخاب آگاهانه نیاز داره گزینه‌های واقعی رو بفهمیم، از جمله صبر کردن یا فعلاً کاری نکردن.","define_informed_choice",["informed","preference"],3),
        U("intervention","A more intensive intervention is not automatically better if the additional benefit is small and the burden is substantial.","مداخله شدیدتر لزوماً بهتر نیست اگر فایده اضافه کم و بارش زیاد باشه.","compare_interventions",["intervention","benefit","risk"],3),
        U("preference","Two well-informed people can reasonably make different choices because their preferences and tolerance for risk differ.","دو آدم کاملاً آگاه می‌تونن منطقی تصمیم‌های متفاوت بگیرن چون ترجیح‌ها و تحمل ریسک‌شون فرق داره.","normalize_preference_sensitive_choice",["informed","preference","risk"],3),
        U("close","The aim is not false certainty but a decision that remains reasonable given the evidence, uncertainty, and person's priorities.","هدف اطمینان مصنوعی نیست؛ تصمیمیه که با توجه به شواهد، عدم قطعیت و اولویت‌های فرد منطقی بمونه.","summarize_health_decision",["evidence","uncertainty","preference"],3),
    ], grammar=["advanced_hedging","concession_rebuttal","nominalisation"], fill=["An ___ choice depends on understanding benefits, risks, and alternatives.",["informed","screening","intervention","uncertainty"],"informed"]),

make_spec(index=35, slug="c1-economic-tradeoffs", topic="prices", title="Economic Trade-offs",
    vocab=[V("inflation","inflation","تورم"),V("incentive","incentive","مشوق"),V("subsidy","subsidy","یارانه"),V("distribution","distribution","توزیع"),V("productivity","productivity","بهره‌وری"),V("affordability","affordability","قابل‌پرداخت بودن"),V("tradeoff","trade-off","بده‌بستان"),V("unintended","unintended","ناخواسته","adjective")],
    utterances=[
        U("inflation","A rise in wages can improve affordability for some households while also adding pressure to costs in certain sectors.","افزایش دستمزد می‌تونه توان پرداخت بعضی خانوارها رو بهتر کنه و هم‌زمان در بعضی بخش‌ها فشار هزینه ایجاد کنه.","analyze_wage_effect",["affordability","inflation"],1),
        U("subsidy","A subsidy may lower the visible price without addressing the underlying reason the service is expensive.","یارانه می‌تونه قیمت قابل مشاهده رو پایین بیاره بدون اینکه علت اصلی گرونی سرویس رو حل کنه.","evaluate_subsidy",["subsidy","affordability"],1),
        U("distribution","The average benefit is positive, but the distribution matters because lower-income groups experience the policy differently.","فایده متوسط مثبته، ولی توزیع مهمه چون گروه‌های کم‌درآمد سیاست رو متفاوت تجربه می‌کنن.","analyze_distribution",["distribution","affordability"],2),
        U("incentive","Every tax or subsidy changes incentives to some extent, although the size of the behavioral response is often uncertain.","هر مالیات یا یارانه‌ای تا حدی مشوق‌ها رو عوض می‌کنه، هرچند اندازه واکنش رفتاری اغلب نامطمئنه.","analyze_incentive",["incentive","subsidy"],2),
        U("productivity","Higher productivity can support rising incomes over time, but it does not determine how those gains are distributed.","بهره‌وری بالاتر می‌تونه در طول زمان درآمد رو بالا ببره، ولی تعیین نمی‌کنه این منفعت چطور توزیع بشه.","link_productivity_distribution",["productivity","distribution"],3),
        U("tradeoff","The trade-off is not simply growth versus fairness; some policies can improve both, while others force a harder choice.","بده‌بستان فقط رشد در برابر عدالت نیست؛ بعضی سیاست‌ها هر دو رو بهتر می‌کنن و بعضی واقعاً انتخاب سخت می‌سازن.","qualify_tradeoff",["tradeoff","distribution"],3),
        U("unintended","An unintended effect can become large enough to outweigh the original benefit if the policy changes behavior in an unexpected way.","اثر ناخواسته اگر سیاست رفتار رو غیرمنتظره تغییر بده می‌تونه اون‌قدر بزرگ بشه که فایده اولیه رو خنثی کنه.","analyze_unintended_effect",["unintended","incentive"],3),
        U("close","I would compare not only total cost and benefit, but who bears each cost, when it occurs, and whether alternatives exist.","فقط هزینه و فایده کل رو مقایسه نمی‌کنم؛ می‌بینم هر هزینه روی دوش کیه، کی اتفاق می‌افته و آیا جایگزین هست یا نه.","summarize_economic_tradeoff",["tradeoff","distribution"],3),
    ], grammar=["concession_rebuttal","complex_prepositions","advanced_hedging"], fill=["The policy had an ___ effect on prices in a neighboring market.",["unintended","affordability","productivity","distribution"],"unintended"]),

make_spec(index=36, slug="c1-complex-travel-resolution", topic="transport", title="Complex Travel Resolution",
    vocab=[V("reroute","reroute","تغییر مسیر دادن","verb"),V("liability","liability","مسئولیت حقوقی / مالی"),V("entitlement","entitlement","حق دریافت"),V("disruption","disruption","اختلال"),V("reimbursement","reimbursement","بازپرداخت هزینه"),V("alternative","alternative","گزینه جایگزین"),V("escalate","escalate","ارجاع به سطح بالاتر","verb"),V("document","document","مستند کردن","verb")],
    utterances=[
        U("disruption","The initial delay became a complex disruption because the replacement route caused us to miss the final connection.","تأخیر اولیه تبدیل به اختلال پیچیده شد چون مسیر جایگزین باعث شد اتصال آخر رو از دست بدیم.","explain_disruption_chain",["disruption","reroute"],1),
        U("reroute","I am happy to be rerouted, provided the new itinerary gets me to the destination today rather than tomorrow morning.","با تغییر مسیر مشکلی ندارم، به شرطی که برنامه جدید امروز منو برسونه نه فردا صبح.","negotiate_reroute",["reroute","alternative"],1),
        U("entitlement","Before accepting the voucher, I would like to clarify whether doing so affects my entitlement to reimbursement.","قبل از قبول ووچر می‌خوام روشن کنم آیا این کار روی حق بازپرداختم اثر می‌ذاره یا نه.","clarify_entitlement",["entitlement","reimbursement"],2),
        U("liability","I understand the weather was outside the airline's control, but I am asking about its liability for the accommodation arranged afterward.","می‌فهمم هوا خارج از کنترل شرکت بوده، ولی سؤالم درباره مسئولیت هزینه اقامتیه که بعدش ترتیب داده شد.","separate_liability",["liability","disruption"],2),
        U("document","I have documented the original booking, the cancellation notice, the replacement route, and the additional expenses.","رزرو اصلی، اطلاع لغو، مسیر جایگزین و هزینه‌های اضافه رو مستند کردم.","document_case",["document","reimbursement"],3),
        U("escalate","If the desk cannot resolve the reimbursement question, could you escalate it to someone who can confirm the policy in writing?", "اگر این میز نمی‌تونه موضوع بازپرداخت رو حل کنه، می‌شه به کسی ارجاعش بدید که سیاست رو کتبی تأیید کنه؟","escalate_case",["escalate","reimbursement"],3),
        U("alternative","A workable alternative would be a later direct flight plus tonight's accommodation rather than three uncertain connections.","گزینه عملی می‌تونه پرواز مستقیم دیرتر به‌علاوه اقامت امشب باشه، نه سه اتصال نامطمئن.","propose_alternative",["alternative","reroute"],3),
        U("close","I am trying to resolve the journey first and preserve the documentation needed for any reimbursement claim afterward.","اول می‌خوام سفر حل بشه و بعد مدارک لازم برای درخواست بازپرداخت رو حفظ کنم.","prioritize_resolution",["document","reimbursement"],3),
    ], grammar=["diplomatic_language","advanced_passive","complex_prepositions"], fill=["I need to clarify my ___ to reimbursement before accepting the voucher.",["entitlement","liability","disruption","alternative"],"entitlement"]),

make_spec(index=37, slug="c1-bureaucracy-rights", topic="requests", title="Bureaucracy & Rights",
    vocab=[V("eligibility","eligibility","شرایط احراز"),V("appeal","appeal","اعتراض رسمی"),V("procedure","procedure","رویه"),V("requirement","requirement","الزام"),V("deadline","deadline","مهلت"),V("evidence","evidence","مدرک / شواهد"),V("decision","decision","تصمیم"),V("review","review","بازبینی")],
    utterances=[
        U("eligibility","The rejection notice states the outcome but does not explain which eligibility requirement the application failed to meet.","نامه رد نتیجه رو می‌گه ولی توضیح نمی‌ده درخواست کدوم شرط احراز رو نداشته.","identify_missing_reason",["eligibility","requirement","decision"],1),
        U("procedure","I would first confirm the formal procedure, because an informal complaint may not pause the appeal deadline.","اول رویه رسمی رو تأیید می‌کنم چون شکایت غیررسمی ممکنه مهلت اعتراض رو متوقف نکنه.","clarify_procedure",["procedure","appeal","deadline"],1),
        U("evidence","The new evidence is relevant because it addresses the specific reason given for the decision, not merely the overall situation.","مدرک جدید مرتبطه چون دقیقاً دلیل تصمیم رو هدف می‌گیره، نه فقط وضعیت کلی رو.","link_evidence_to_decision",["evidence","decision"],2),
        U("review","I am requesting a review of the decision on the basis that the submitted document appears not to have been considered.","درخواست بازبینی تصمیم رو دارم چون به نظر میاد مدرک ارسال‌شده بررسی نشده.","request_review",["review","decision","evidence"],2),
        U("deadline","If the deadline cannot be extended, I would like written confirmation of the date and the acceptable submission methods.","اگر مهلت قابل تمدید نیست، تأیید کتبی تاریخ و روش‌های قابل قبول ارسال رو می‌خوام.","protect_deadline",["deadline","procedure"],3),
        U("requirement","A requirement should be applied consistently; if an exception exists, the basis for that exception should also be clear.","یک الزام باید یکدست اعمال بشه؛ اگر استثنا وجود داره مبناش هم باید روشن باشه.","question_consistency",["requirement","eligibility"],3),
        U("appeal","An appeal is more effective when it identifies the alleged error precisely rather than simply restating dissatisfaction with the outcome.","اعتراض وقتی مؤثرتره که خطای ادعایی رو دقیق مشخص کنه، نه اینکه فقط نارضایتی از نتیجه رو تکرار کنه.","structure_appeal",["appeal","decision"],3),
        U("close","My immediate goal is to preserve the right to review while gathering the strongest evidence for the substantive case.","هدف فوری من حفظ حق بازبینیه، در حالی که قوی‌ترین مدارک برای اصل پرونده رو جمع می‌کنم.","preserve_rights",["review","evidence"],3),
    ], grammar=["formal_subjunctive","advanced_passive","nominalisation"], fill=["The letter does not explain which eligibility ___ was not met.",["requirement","appeal","procedure","review"],"requirement"]),

make_spec(index=38, slug="c1-community-policy", topic="simple-messages", title="Community Policy",
    vocab=[V("stakeholder","stakeholder","ذی‌نفع"),V("consultation","consultation","مشورت عمومی"),V("access","access","دسترسی"),V("allocation","allocation","تخصیص"),V("equity","equity","عدالت در توزیع"),V("capacity","capacity","ظرفیت"),V("proposal","proposal","پیشنهاد"),V("impact","impact","اثر")],
    utterances=[
        U("stake","A community policy can look efficient on paper while overlooking stakeholders who have less capacity to participate in consultation.","سیاست محلی می‌تونه روی کاغذ کارا باشه ولی ذی‌نفع‌هایی رو نادیده بگیره که ظرفیت کمتری برای شرکت در مشورت دارن.","identify_participation_gap",["stakeholder","consultation","capacity"],1),
        U("access","The issue is not only whether the service exists, but whether people can access it at the times and locations they actually need.","مسئله فقط وجود سرویس نیست؛ اینه که مردم در زمان و مکان موردنیاز واقعاً بهش دسترسی دارن یا نه.","define_access",["access","impact"],1),
        U("allocation","Resource allocation inevitably reflects priorities, so the criteria should be visible and open to challenge.","تخصیص منابع ناگزیر اولویت‌ها رو بازتاب می‌ده، پس معیارها باید قابل مشاهده و قابل اعتراض باشن.","question_allocation",["allocation","proposal"],2),
        U("equity","Equal provision is not always equitable if some neighborhoods face substantially greater barriers.","ارائه برابر همیشه عادلانه نیست اگر بعضی محله‌ها موانع خیلی بیشتری داشته باشن.","distinguish_equality_equity",["equity","access"],2),
        U("consult","A consultation process should explain how public input affected the final proposal, not merely record that comments were collected.","روند مشورت باید بگه نظر مردم چطور روی پیشنهاد نهایی اثر گذاشت، نه اینکه فقط ثبت کنه نظرها جمع شدن.","evaluate_consultation",["consultation","proposal"],3),
        U("capacity","The council may lack capacity to implement every request, but that constraint should be stated before priorities are ranked.","شورا شاید ظرفیت اجرای همه درخواست‌ها رو نداشته باشه، ولی این محدودیت باید قبل از رتبه‌بندی اولویت‌ها صریح بشه.","surface_capacity",["capacity","allocation"],3),
        U("impact","I would assess impact by who gains access, who loses convenience, and whether any group carries a disproportionate burden.","اثر رو بر اساس اینکه چه کسی دسترسی می‌گیره، چه کسی راحتی از دست می‌ده و آیا گروهی بار نامتناسب تحمل می‌کنه می‌سنجم.","assess_policy_impact",["impact","equity"],3),
        U("close","A legitimate local decision does not require unanimous agreement, but it should make the trade-offs and reasoning understandable.","تصمیم محلی معتبر نیاز به توافق همه نداره، ولی باید بده‌بستان‌ها و منطقش قابل فهم باشه.","summarize_legitimacy",["proposal","stakeholder"],3),
    ], grammar=["nominalisation","concession_rebuttal","formal_subjunctive"], fill=["Equal provision is not always the same as ___.",["equity","allocation","capacity","consultation"],"equity"]),

make_spec(index=39, slug="c1-art-interpretation", topic="hobbies", title="Art & Interpretation",
    vocab=[V("interpretation","interpretation","تفسیر"),V("symbolism","symbolism","نمادپردازی"),V("ambiguous","ambiguous","چندپهلو / مبهم","adjective"),V("composition","composition","ترکیب‌بندی"),V("evoke","evoke","برانگیختن","verb"),V("context","context","زمینه"),V("intent","intent","نیت خالق"),V("reading","reading","برداشت / خوانش")],
    utterances=[
        U("reading","My reading of the film is shaped less by the plot than by the repeated images of doors, borders, and interrupted journeys.","برداشت من از فیلم کمتر از داستان و بیشتر از تصویرهای تکراری در، مرز و سفرهای قطع‌شده میاد.","offer_interpretation",["reading","symbolism"],1),
        U("ambiguous","The ending is deliberately ambiguous enough to support several interpretations without making every interpretation equally convincing.","پایان عمداً اون‌قدر چندپهلوئه که چند تفسیر رو ممکن می‌کنه، بدون اینکه همه تفسیرها به یک اندازه قانع‌کننده باشن.","analyze_ambiguity",["ambiguous","interpretation"],1),
        U("composition","The composition draws attention away from the central figure, which makes the empty space feel unusually important.","ترکیب‌بندی توجه رو از شخصیت مرکزی دور می‌کنه و باعث می‌شه فضای خالی به شکل غیرعادی مهم بشه.","analyze_composition",["composition","evoke"],2),
        U("context","Knowing the historical context changes the significance of the image, but the work still communicates something without that knowledge.","دانستن زمینه تاریخی اهمیت تصویر رو عوض می‌کنه، ولی اثر بدون اون دانش هم چیزی منتقل می‌کنه.","use_context",["context","interpretation"],2),
        U("intent","The artist's stated intent is relevant, but I would not treat it as the only legitimate guide to meaning.","نیت اعلام‌شده هنرمند مهمه، ولی اون رو تنها راهنمای معتبر معنا نمی‌دونم.","weigh_artist_intent",["intent","reading"],3),
        U("symbol","The symbolism works partly because the object is ordinary enough to carry several associations at once.","نمادپردازی تا حدی جواب می‌ده چون شیء اون‌قدر عادیه که چند تداعی رو هم‌زمان حمل کنه.","analyze_symbolism",["symbolism","ambiguous"],3),
        U("evoke","For me, the final scene evokes unease rather than sadness, although I can see why another viewer might read it differently.","برای من صحنه آخر بیشتر اضطراب ایجاد می‌کنه تا غم، هرچند می‌فهمم چرا بیننده دیگه می‌تونه متفاوت برداشت کنه.","describe_response",["evoke","reading"],3),
        U("close","A strong interpretation should remain accountable to details in the work even when meaning is not fixed.","تفسیر قوی حتی وقتی معنا ثابت نیست باید همچنان به جزئیات خود اثر پاسخ‌گو بمونه.","justify_interpretation",["interpretation","context"],3),
    ], grammar=["advanced_hedging","cleft_sentences","concession_rebuttal"], fill=["The deliberately ___ ending supports more than one plausible reading.",["ambiguous","composition","intent","evoke"],"ambiguous"]),

make_spec(index=40, slug="c1-humor-irony", topic="polite-language", title="Humor, Irony & Sarcasm",
    vocab=[V("irony","irony","طعنه / آیرونی"),V("sarcasm","sarcasm","کنایه تند"),V("deadpan","deadpan","خشک و بی‌حالت","adjective"),V("tease","tease","شوخی کردن با کسی","verb"),V("understatement","understatement","کم‌گویی عمدی"),V("punchline","punchline","ضربه پایانی شوخی"),V("misfire","misfire","بد از آب درآمدن","verb"),V("context","context","زمینه")],
    utterances=[
        U("irony","The irony depends on the gap between what the speaker says and what everyone in the room knows to be true.","آیرونی به فاصله بین چیزی که گوینده می‌گه و چیزی که همه اتاق می‌دونن واقعیه وابسته‌ست.","explain_irony",["irony","context"],1),
        U("deadpan","The line works because it is delivered completely deadpan, as if the absurd situation were perfectly normal.","جمله چون کاملاً خشک و جدی گفته می‌شه جواب می‌ده، انگار موقعیت عجیب کاملاً عادیه.","explain_deadpan",["deadpan","irony"],1),
        U("sarcasm","Sarcasm can create solidarity among close friends, but the same wording may sound hostile when trust is weak.","کنایه تند بین دوست‌های نزدیک می‌تونه حس همراهی بسازه، ولی همون جمله وقتی اعتماد کمه خصمانه به نظر میاد.","evaluate_sarcasm",["sarcasm","context"],2),
        U("tease","Good teasing usually signals affection and leaves the other person room to respond rather than trapping them in embarrassment.","شوخی خوب معمولاً محبت رو نشون می‌ده و به طرف فضا برای جواب می‌ده، نه اینکه توی خجالت گیرش بندازه.","describe_teasing",["tease","context"],2),
        U("under","Calling a complete disaster 'not our smoothest launch' is an understatement used for comic effect.","گفتن «روان‌ترین عرضه‌مون نبود» برای یک فاجعه کامل، کم‌گویی عمدیه برای اثر طنز.","identify_understatement",["understatement","irony"],3),
        U("punch","Explaining the punchline usually destroys the timing, which is why humor can be difficult to translate directly.","توضیح ضربه آخر معمولاً زمان‌بندی رو خراب می‌کنه و برای همینه ترجمه مستقیم طنز سخته.","analyze_punchline",["punchline","context"],3),
        U("misfire","The joke misfired because the speaker assumed shared context that half the audience did not have.","شوخی بد از آب دراومد چون گوینده فرض کرد زمینه مشترکی هست که نصف مخاطب نداشت.","explain_failed_humor",["misfire","context"],3),
        U("close","At C1, understanding humor often means recognizing not only the words but the relationship, timing, and implied stance behind them.","در C1 فهم طنز اغلب یعنی فقط واژه‌ها رو نفهمیم؛ رابطه، زمان‌بندی و موضع ضمنی پشتشون رو هم تشخیص بدیم.","summarize_humor_comprehension",["irony","sarcasm","context"],3),
    ], grammar=["distancing","register_shift","reformulation"], fill=["The joke ___ because the audience did not share the assumed context.",["misfired","teased","deadpan","punchline"],"misfired"]),
]

if __name__ == "__main__":
    write_units(UNITS)
