#!/usr/bin/env python3
from __future__ import annotations
import json
from scripts.generate_b1_batch import V,U,G,D,T,build,OUT

UNITS=[
{
"slug":"b1-places-culture","file":"b1-places-culture-v1.json","topic":"places-town","lessons":3,
"vocab":[V("tradition","tradition","سنت"),V("festival","festival","جشنواره"),V("heritage","heritage","میراث"),V("custom","custom","رسم"),V("local","local","محلی","adjective"),V("historic","historic","تاریخی","adjective"),V("celebrate","celebrate","جشن گرفتن","verb"),V("similar","similar","مشابه","adjective"),V("difference","difference","تفاوت"),V("atmosphere","atmosphere","حال‌وهوا")],
"utterances":[U("place","It's a historic neighborhood that has kept many of its original buildings.","محله‌ای تاریخیه که خیلی از ساختمان‌های اصلیش رو حفظ کرده.","describe_place",["historic","heritage"],1),U("festival","The festival is held every spring and attracts visitors from across the region.","جشنواره هر بهار برگزار می‌شه و از سراسر منطقه بازدیدکننده جذب می‌کنه.","describe_cultural_event",["festival","celebrate"],1),U("custom","One local custom is to bring a small gift when you're invited to someone's home.","یکی از رسم‌های محلی اینه که وقتی به خونه کسی دعوت می‌شی یک هدیه کوچک ببری.","explain_custom",["custom","local"],1),U("heritage","The old market has been protected because it's an important part of the city's heritage.","بازار قدیمی محافظت شده چون بخش مهمی از میراث شهره.","explain_cultural_value",["heritage"],2),U("compare","The celebration is similar to New Year in some ways, but the food and traditions are different.","این جشن از بعضی جهت‌ها شبیه سال نوئه، ولی غذا و سنت‌ها متفاوتن.","compare_cultures",["similar","difference","tradition"],2),U("atmosphere","What I liked most was the atmosphere: the streets were full of music and families.","چیزی که بیشتر دوست داشتم حال‌وهوا بود: خیابون‌ها پر از موسیقی و خانواده بود.","describe_cultural_impression",["atmosphere"],2),U("passive","Traditional dishes are prepared in large outdoor kitchens during the event.","غذاهای سنتی در طول رویداد در آشپزخانه‌های بزرگ بیرونی آماده می‌شن.","describe_tradition_process",["tradition"],3),U("reflection","Experiencing the festival helped me understand why the tradition matters to local people.","تجربه جشنواره کمک کرد بفهمم چرا این سنت برای مردم محلی مهمه.","reflect_cultural_experience",["festival","local"],3)],
"grammar":[G("relative_places","Relative clauses for culture and places","Use who/that/which/where to connect descriptive information about people, events, and places.","برای وصل کردن اطلاعات توصیفی درباره آدم‌ها، رویدادها و مکان‌ها از who/that/which/where استفاده می‌کنیم.",[("It's a town where artists have lived for generations.","شهریه که نسل‌ها هنرمندها در اون زندگی کردند."),("The festival that takes place in June is free.","جشنواره‌ای که ژوئن برگزار می‌شه رایگانه.")],1),G("passive_culture","Passive voice for traditions","Use passive forms to describe how things are made, celebrated, or organized when the process matters most.","برای توضیح نحوه ساخته شدن، جشن گرفتن یا برگزاری وقتی فرایند مهم‌تر است از passive استفاده می‌کنیم.",[("The event is held every spring.","رویداد هر بهار برگزار می‌شه."),("Traditional food is prepared outdoors.","غذای سنتی بیرون آماده می‌شه.")],2),G("comparison_culture","Comparative structures for cultures","Use similar to, different from, whereas, and compared with to make respectful comparisons.","برای مقایسه محترمانه فرهنگ‌ها از similar to، different from، whereas و compared with استفاده می‌کنیم.",[("The custom is similar to one in my country.","این رسم شبیه یکی از رسم‌های کشور منه."),("Compared with my hometown, the festival is much larger.","در مقایسه با شهر من، جشنواره خیلی بزرگ‌تره.")],3)],
"dialogues":[D("oldtown","Exploring an old town","walking tour",["Maya","Leo"],[T("Maya","These buildings look much older than the rest of the city.","این ساختمان‌ها خیلی قدیمی‌تر از بقیه شهر به نظر میان."),T("Leo","They are. This area has been protected as a historic district.","همین‌طوره. این منطقه به‌عنوان بافت تاریخی محافظت شده."),T("Maya","Are people still allowed to live here?","هنوز مردم اجازه دارند اینجا زندگی کنند؟"),T("Leo","Yes, but major changes to the buildings are restricted.","آره، ولی تغییرات بزرگ در ساختمان‌ها محدود شده.")],1),D("festival","Talking about a festival","cafe",["Hana","Noah"],[T("Hana","What was the spring festival like?","جشنواره بهاری چطور بود؟"),T("Noah","Really lively. There was music in almost every street.","خیلی زنده. تقریباً توی هر خیابون موسیقی بود."),T("Hana","Was it mostly for tourists?","بیشتر برای توریست‌ها بود؟"),T("Noah","Not at all. Most people there were local families.","اصلاً. بیشتر آدم‌ها خانواده‌های محلی بودند.")],2),D("compare","Comparing traditions","dinner",["Sofia","Omar"],[T("Sofia","That custom sounds similar to something we do at New Year.","اون رسم شبیه کاریه که ما در سال نو می‌کنیم."),T("Omar","Yes, although the meaning is a little different.","آره، با اینکه معنیش کمی فرق داره."),T("Sofia","I like learning the reason behind a tradition, not just seeing it.","دوست دارم دلیل پشت یک سنت رو یاد بگیرم، نه فقط ببینمش."),T("Omar","Same. Context makes the experience much more interesting.","منم. زمینه باعث می‌شه تجربه خیلی جالب‌تر باشه.")],3)],
"fill":["The festival is ___ every spring.",["held","hold","holding","holds"],"held"]
},
{
"slug":"b1-everyday-environment","file":"b1-everyday-environment-v1.json","topic":"common-actions","lessons":3,
"vocab":[V("waste","waste","زباله / هدررفت"),V("recycle","recycle","بازیافت کردن","verb"),V("reusable","reusable","قابل‌استفاده مجدد","adjective"),V("energy","energy","انرژی"),V("transport","transport","حمل‌ونقل"),V("reduce","reduce","کاهش دادن","verb"),V("efficient","efficient","کارآمد / کم‌مصرف","adjective"),V("impact","impact","اثر"),V("packaging","packaging","بسته‌بندی"),V("practical","practical","عملی","adjective")],
"utterances":[U("waste","We throw away less food now because we plan meals before shopping.","الان غذای کمتری دور می‌ریزیم چون قبل خرید برنامه غذایی می‌چینیم.","describe_waste_reduction",["waste","reduce"],1),U("reusable","I keep a reusable bottle at work so I don't buy plastic bottles every day.","سر کار بطری قابل‌استفاده مجدد دارم تا هر روز بطری پلاستیکی نخرم.","describe_environmental_habit",["reusable"],1),U("transport","If public transport were more frequent in my area, I'd use the car less.","اگر حمل‌ونقل عمومی منطقه‌م پرتعدادتر بود، کمتر ماشین استفاده می‌کردم.","discuss_transport_choice",["transport","impact"],1),U("packaging","A lot of unnecessary packaging is used for products that don't need it.","برای محصولاتی که نیاز ندارند بسته‌بندی اضافی زیادی استفاده می‌شه.","identify_problem",["packaging","waste"],2),U("efficient","We replaced the old lights with more energy-efficient ones, which reduced our electricity use.","چراغ‌های قدیمی رو با مدل‌های کم‌مصرف‌تر عوض کردیم که مصرف برق رو کم کرد.","describe_efficiency_change",["efficient","energy","reduce"],2),U("practical","The solution has to be practical enough that people will actually keep doing it.","راه‌حل باید آن‌قدر عملی باشه که مردم واقعاً ادامه‌اش بدن.","evaluate_solution",["practical"],2),U("conditional","If everyone in the office printed less, we'd cut paper use significantly.","اگر همه در دفتر کمتر چاپ می‌کردند، مصرف کاغذ خیلی کم می‌شد.","suggest_collective_action",["reduce"],3),U("balanced","Small individual choices matter, but larger systems also have a major impact.","انتخاب‌های کوچک فردی مهمن، ولی سیستم‌های بزرگ‌تر هم اثر زیادی دارند.","give_balanced_environment_view",["impact"],3)],
"grammar":[G("conditionals_env","Conditionals for environmental choices","Use first conditional for likely results and second conditional for hypothetical changes.","برای نتیجه‌های محتمل از شرط نوع اول و برای تغییر فرضی از شرط نوع دوم استفاده می‌کنیم.",[("If we recycle more, we'll reduce waste.","اگر بیشتر بازیافت کنیم زباله کمتر می‌شه."),("If buses were more frequent, I'd drive less.","اگر اتوبوس بیشتر بود کمتر رانندگی می‌کردم.")],1),G("passive_env","Passive voice for systems","Use passive forms to describe waste, energy, and production systems when the process is central.","برای توضیح سیستم‌های زباله، انرژی و تولید وقتی فرایند محور اصلی است از passive استفاده می‌کنیم.",[("Plastic is collected separately.","پلاستیک جدا جمع می‌شه."),("Too much packaging is used.","بسته‌بندی زیادی استفاده می‌شه.")],2),G("cause_effect_env","Cause and effect links","Use because, so, therefore, which, and as a result to explain environmental impact clearly.","برای توضیح اثر محیط‌زیستی از because، so، therefore، which و as a result استفاده می‌کنیم.",[("We planned meals, so we wasted less food.","برنامه غذایی چیدیم، پس غذای کمتری هدر دادیم."),("The lights use less energy; as a result, bills are lower.","چراغ‌ها انرژی کمتری مصرف می‌کنند؛ در نتیجه قبض‌ها کمتره.")],3)],
"dialogues":[D("office","Reducing office waste","team meeting",["Lina","Ben"],[T("Lina","We still use a lot of disposable cups in the office.","هنوز توی دفتر لیوان یک‌بارمصرف زیادی استفاده می‌کنیم."),T("Ben","What if we gave everyone a reusable mug?","چی می‌شه اگر به همه لیوان قابل‌استفاده مجدد بدیم؟"),T("Lina","That could help, but we also need somewhere easy to wash them.","می‌تونه کمک کنه، ولی جایی راحت برای شستن هم لازم داریم."),T("Ben","Good point. Let's include that in the plan.","نکته خوبیه. توی برنامه بذاریمش.")],1),D("commute","Talking about commuting","bus stop",["Amir","Ella"],[T("Amir","I'd use the bus more if it came every fifteen minutes.","اگر اتوبوس هر پانزده دقیقه می‌اومد بیشتر استفاده می‌کردم."),T("Ella","Same. Right now driving is just much more practical.","منم. الان رانندگی خیلی عملی‌تره."),T("Amir","That's the problem. People need a realistic alternative.","مشکل همینه. مردم به جایگزین واقعی نیاز دارند."),T("Ella","Exactly. Telling people to drive less isn't enough by itself.","دقیقاً. فقط گفتن کمتر رانندگی کنید کافی نیست.")],2),D("shopping","Reducing packaging","grocery store",["Ravi","Mina"],[T("Ravi","I've started buying these refill packs instead of new bottles.","شروع کردم به خرید بسته‌های شارژ به‌جای بطری جدید."),T("Mina","Do they actually use much less packaging?","واقعاً بسته‌بندی خیلی کمتری استفاده می‌کنند؟"),T("Ravi","About seventy percent less, according to the label.","طبق برچسب حدود هفتاد درصد کمتر."),T("Mina","That's a practical change if the price is similar.","اگر قیمت مشابه باشه تغییر عملیه.")],3)],
"fill":["If public transport were better, I ___ drive less.",["would","will","did","have"],"would"]
},
{
"slug":"b1-explaining-presenting","file":"b1-explaining-presenting-v1.json","topic":"questions","lessons":3,
"vocab":[V("outline","outline","طرح کلی"),V("purpose","purpose","هدف"),V("point","point","نکته"),V("example","example","مثال"),V("conclusion","conclusion","جمع‌بندی"),V("audience","audience","مخاطب"),V("clarify","clarify","شفاف کردن","verb"),V("signpost","signpost","علامت‌دهی ساختار","verb"),V("question","question","سؤال"),V("summarize","summarize","خلاصه کردن","verb")],
"utterances":[U("opening","Today I'd like to explain three simple ways to make meetings more efficient.","امروز می‌خوام سه راه ساده برای کارآمدتر کردن جلسه‌ها توضیح بدم.","open_presentation",["purpose","outline"],1),U("outline","First, I'll look at preparation, then meeting structure, and finally follow-up.","اول آمادگی، بعد ساختار جلسه و در آخر پیگیری رو بررسی می‌کنم.","signpost_outline",["outline","signpost"],1),U("point","The first point is that every meeting should have a clear purpose.","نکته اول اینه که هر جلسه باید هدف واضحی داشته باشه.","introduce_main_point",["point","purpose"],1),U("example","For example, a fifteen-minute update meeting doesn't need a one-hour agenda.","مثلاً جلسه گزارش پانزده‌دقیقه‌ای به دستور جلسه یک‌ساعته نیاز نداره.","give_presentation_example",["example"],2),U("transition","Now that we've looked at preparation, let's move on to what happens during the meeting.","حالا که آمادگی رو دیدیم، بریم سراغ چیزی که داخل جلسه اتفاق می‌افته.","transition_section",["signpost"],2),U("clarify","Just to clarify, I'm not suggesting that every meeting should be short.","فقط برای شفاف شدن، نمی‌گم همه جلسه‌ها باید کوتاه باشند.","clarify_point",["clarify"],2),U("question","That's a good question. The answer depends on the size of the team.","سؤال خوبیه. جواب به اندازه تیم بستگی داره.","handle_question",["question","audience"],3),U("conclusion","To summarize, clear goals, focused discussion, and written next steps make meetings more useful.","در جمع‌بندی، هدف روشن، بحث متمرکز و قدم‌های بعدی مکتوب جلسه رو مفیدتر می‌کنه.","close_presentation",["summarize","conclusion"],3)],
"grammar":[G("signposting","Presentation signposting","Use first, next, moving on to, and to summarize to make structure explicit for listeners.","برای روشن کردن ساختار ارائه از first، next، moving on to و to summarize استفاده می‌کنیم.",[("First, let's look at the problem.","اول مشکل رو بررسی کنیم."),("To summarize, there are three main benefits.","در جمع‌بندی سه مزیت اصلی هست.")],1),G("relative_present","Relative clauses in explanations","Use relative clauses to define examples, people, or processes without starting a new sentence.","برای تعریف مثال، شخص یا فرایند بدون شروع جمله جدید از relative clause استفاده می‌کنیم.",[("A meeting that has no agenda often runs long.","جلسه‌ای که دستور ندارد اغلب طولانی می‌شه."),("The person who leads the meeting should keep time.","کسی که جلسه رو اداره می‌کنه باید زمان رو کنترل کنه.")],2),G("question_handling","Handling follow-up questions","Use That's a good question, If I understand correctly…, and What I mean is… to buy thinking time and clarify.","برای پاسخ به سؤال پیگیری از That's a good question، If I understand correctly و What I mean is استفاده می‌کنیم.",[("If I understand correctly, you're asking about cost.","اگر درست فهمیده باشم، درباره هزینه می‌پرسید."),("What I mean is that the process should be simpler.","منظورم اینه که فرایند باید ساده‌تر باشه.")],3)],
"dialogues":[D("opening","Practicing an opening","classroom",["Maya","Claire"],[T("Maya","Today I'd like to explain how I organize my weekly tasks.","امروز می‌خوام توضیح بدم کارهای هفتگی‌م رو چطور سازمان می‌دم."),T("Claire","Good. Can you tell the audience what the three sections are?","خوبه. می‌تونی به مخاطب بگی سه بخش چیه؟"),T("Maya","Yes. First priorities, then scheduling, and finally review.","آره. اول اولویت‌ها، بعد زمان‌بندی و در آخر مرور."),T("Claire","Much clearer.","خیلی واضح‌تره.")],1),D("transition","Improving presentation flow","practice room",["Hana","Noah"],[T("Hana","I keep jumping from one point to another.","مدام از یک نکته به نکته دیگه می‌پرم."),T("Noah","Use a transition sentence before each new section.","قبل هر بخش جدید یک جمله انتقالی استفاده کن."),T("Hana","Like 'Now let's move on to the results'?","مثل Now let's move on to the results؟"),T("Noah","Exactly. It tells the audience where you are.","دقیقاً. به مخاطب می‌گه کجای ارائه‌ای.")],2),D("qa","Handling a question","presentation",["Sofia","Omar"],[T("Omar","What happens if a team has several urgent priorities at once?","اگر تیم هم‌زمان چند اولویت فوری داشته باشه چی؟"),T("Sofia","That's a good question. In that case, someone needs to rank them explicitly.","سؤال خوبیه. در اون حالت یک نفر باید صریح اولویت‌بندیشون کنه."),T("Omar","Who should make that decision?","کی باید اون تصمیم رو بگیره؟"),T("Sofia","Usually the team lead, but it depends on the organization.","معمولاً رهبر تیم، ولی به سازمان بستگی داره.")],3)],
"fill":["To ___, there are three main points.",["summarize","summary","summarizing","summarized"],"summarize"]
},
{
"slug":"b1-summarizing-relaying","file":"b1-summarizing-relaying-v1.json","topic":"simple-messages","lessons":3,
"vocab":[V("relay","relay","منتقل کردن","verb"),V("summary","summary","خلاصه"),V("main_point","main point","نکته اصلی"),V("detail","detail","جزئیات"),V("message","message","پیام"),V("notice","notice","اطلاعیه"),V("mention","mention","اشاره کردن","verb"),V("confirm","confirm","تأیید کردن","verb"),V("deadline","deadline","مهلت"),V("instruction","instruction","دستورالعمل")],
"utterances":[U("main","The main point is that tomorrow's workshop has moved online.","نکته اصلی اینه که کارگاه فردا آنلاین شده.","relay_main_point",["main_point","message"],1),U("details","They said the start time is the same, but we'll receive a new link this afternoon.","گفتند ساعت شروع همونه، ولی بعدازظهر لینک جدید می‌گیریم.","relay_key_details",["detail","message"],1),U("notice","The notice says the building will be closed from six p.m. Friday until Monday morning.","اطلاعیه می‌گه ساختمان از جمعه شش عصر تا دوشنبه صبح بسته است.","relay_notice",["notice"],1),U("tell","Could you tell Maya that the client moved the deadline to Wednesday?","می‌شه به مایا بگی مشتری مهلت رو به چهارشنبه منتقل کرده؟","ask_to_relay",["relay","deadline"],2),U("mention","Please mention that they still want the draft by Monday for an early review.","لطفاً اشاره کن که هنوز پیش‌نویس رو برای بررسی زودهنگام تا دوشنبه می‌خوان.","add_relay_detail",["mention","deadline"],2),U("confirm","He asked me to confirm whether everyone had received the updated instructions.","ازم خواست تأیید کنم همه دستورالعمل جدید رو گرفتند یا نه.","relay_request",["confirm","instruction"],2),U("shift","She said she couldn't attend today and asked if we could send her the notes afterward.","گفت امروز نمی‌تونه شرکت کنه و پرسید می‌تونیم بعداً یادداشت‌ها رو براش بفرستیم یا نه.","report_message",["message"],3),U("summary","So, in short: same time, new link, and no need to come to the office.","پس خلاصه: همون ساعت، لینک جدید و نیازی نیست بیای دفتر.","summarize_practical_info",["summary","main_point"],3)],
"grammar":[G("reported_speech","Reported speech","Use said/told/asked to relay the main meaning of someone's message; pronouns and time references may shift.","برای انتقال معنی اصلی پیام از said/told/asked استفاده می‌کنیم؛ ضمیر و زمان ممکنه تغییر کنه.",[("She said she was running late.","گفت دیر می‌رسه."),("He asked me to call him.","ازم خواست بهش زنگ بزنم.")],1),G("say_tell","say vs tell","Use say without a person object or with to; use tell + person.","say معمولاً بدون مفعول شخص میاد یا با to؛ tell مستقیم با شخص میاد.",[("She said that the time had changed.","گفت زمان عوض شده."),("She told me that the time had changed.","به من گفت زمان عوض شده.")],2),G("relay_shifts","Basic time and pronoun shifts","When reporting later, words such as today/tomorrow and I/we may need to change to keep meaning clear.","وقتی بعداً حرف کسی رو منتقل می‌کنیم، کلماتی مثل today/tomorrow و ضمیرها ممکنه برای حفظ معنی تغییر کنند.",[("'I'll call tomorrow.' → She said she'd call the next day.","گفت روز بعد تماس می‌گیره."),("'We need this today.' → They said they needed it that day.","گفتند همان روز لازم دارند.")],3)],
"dialogues":[D("workshop","Relaying a workshop change","office",["Lina","Ben"],[T("Lina","I missed the announcement. What's happening with tomorrow's workshop?","اعلان رو ندیدم. کارگاه فردا چی شد؟"),T("Ben","It's moved online. The start time hasn't changed.","آنلاین شده. ساعت شروع عوض نشده."),T("Lina","Do we already have the new link?","لینک جدید رو داریم؟"),T("Ben","Not yet. They said they'd send it this afternoon.","هنوز نه. گفتند بعدازظهر می‌فرستن.")],1),D("deadline","Passing on a deadline change","phone call",["Amir","Ella"],[T("Amir","Could you tell Maya the client changed the deadline to Wednesday?","می‌شه به مایا بگی مشتری مهلت رو به چهارشنبه عوض کرد؟"),T("Ella","Sure. Anything else?","حتماً. چیز دیگه‌ای؟"),T("Amir","Yes. They still want the draft by Monday for an early review.","آره. هنوز پیش‌نویس رو برای بررسی اولیه تا دوشنبه می‌خوان."),T("Ella","Got it. I'll make sure she knows both dates.","فهمیدم. مطمئن می‌شم هر دو تاریخ رو می‌دونه.")],2),D("absence","Relaying an absence message","team chat",["Ravi","Mina"],[T("Ravi","Did Priya say why she isn't joining today?","پریا گفت چرا امروز نمیاد؟"),T("Mina","She said she had a medical appointment.","گفت وقت پزشکی داره."),T("Ravi","Does she need anything from us?","چیزی از ما لازم داره؟"),T("Mina","She asked us to send the meeting notes afterward.","خواست بعد جلسه یادداشت‌ها رو براش بفرستیم.")],3)],
"fill":["She ___ me that the deadline had changed.",["told","said","spoke","asked to"],"told"]
},
{
"slug":"b1-integrated-capstone","file":"b1-integrated-capstone-v1.json","topic":"simple-messages","lessons":4,
"vocab":[V("schedule","schedule","برنامه زمانی"),V("disruption","disruption","اختلال"),V("alternative","alternative","جایگزین"),V("recommendation","recommendation","پیشنهاد"),V("update","update","به‌روزرسانی"),V("priority","priority","اولویت"),V("summary","summary","خلاصه"),V("arrangement","arrangement","قرار"),V("decision","decision","تصمیم"),V("solution","solution","راه‌حل")],
"utterances":[U("arrival","Our train has been cancelled, so we need an alternative way to reach the city before tonight.","قطارمون لغو شده، پس باید قبل از امشب یک راه جایگزین برای رسیدن به شهر پیدا کنیم.","handle_travel_disruption",["disruption","alternative"],1),U("compare","The bus is cheaper, but it takes almost two hours longer than the replacement train.","اتوبوس ارزون‌تره، ولی تقریباً دو ساعت بیشتر از قطار جایگزین طول می‌کشه.","compare_alternatives",["alternative","decision"],1),U("hotel","I'll call the hotel and tell them we're going to arrive later than planned.","به هتل زنگ می‌زنم و می‌گم دیرتر از برنامه می‌رسیم.","relay_arrival_change",["schedule","update"],2),U("recommend","The receptionist recommended a restaurant that serves local food and stays open late.","پذیرش یک رستوران پیشنهاد داد که غذای محلی داره و تا دیر وقت بازه.","relay_recommendation",["recommendation"],2),U("problem","Tomorrow's museum tour is fully booked, but we could visit the market in the morning instead.","تور موزه فردا کاملاً پره، ولی می‌تونیم صبح به جاش بازار رو ببینیم.","solve_plan_problem",["solution","alternative"],3),U("meeting","We're meeting Priya at four, so whatever we choose needs to finish before then.","ساعت چهار با پریا قرار داریم، پس هرچی انتخاب می‌کنیم باید قبلش تموم بشه.","manage_arrangement",["arrangement","priority"],3),U("summary","So the updated plan is: replacement train, late hotel check-in, market in the morning, and Priya at four.","پس برنامه جدید اینه: قطار جایگزین، تحویل دیرتر هتل، بازار صبح و پریا ساعت چهار.","summarize_plan",["summary","update"],4),U("reflection","The day didn't go as planned, but we managed each problem without losing the whole trip.","روز طبق برنامه پیش نرفت، ولی هر مشکل رو مدیریت کردیم بدون اینکه کل سفر خراب بشه.","reflect_capstone",["solution","decision"],4)],
"grammar":[G("integrated_tenses","Integrated tense control","Choose past forms for what happened, present forms for current needs, and future forms for arrangements and decisions.","برای اتفاق افتاده از گذشته، برای نیاز فعلی از حال و برای قرار و تصمیم از آینده مناسب استفاده می‌کنیم.",[("The train was cancelled, so we need another route.","قطار لغو شد، پس مسیر دیگه‌ای لازم داریم."),("We're meeting Priya at four.","ساعت چهار با پریا قرار داریم.")],1),G("integrated_conditionals","Conditionals for backup plans","Use if/unless with can/could/will/might to adapt a plan when conditions change.","برای تطبیق برنامه با تغییر شرایط از if/unless همراه can/could/will/might استفاده می‌کنیم.",[("If the museum is full, we can visit the market.","اگر موزه پر باشه، می‌تونیم بازار بریم."),("We'll walk unless it starts raining.","مگر اینکه بارون شروع بشه، پیاده می‌ریم.")],2),G("integrated_relay","Relaying information and recommendations","Use told us, said that, asked us to, and recommended to mediate practical information.","برای انتقال اطلاعات عملی از told us، said that، asked us to و recommended استفاده می‌کنیم.",[("The hotel told us the desk stayed open late.","هتل گفت پذیرش تا دیر وقت بازه."),("She recommended taking the subway.","پیشنهاد داد مترو بگیریم.")],3)],
"dialogues":[D("station","Handling a cancelled train","station desk",["Maya","Daniel"],[T("Maya","Our train has been cancelled. We need to be in the city tonight.","قطارمون لغو شده. باید امشب توی شهر باشیم."),T("Daniel","There's a replacement train in ninety minutes, or a bus leaving in twenty.","نود دقیقه دیگه قطار جایگزین هست یا بیست دقیقه دیگه اتوبوس."),T("Maya","How much longer does the bus take?","اتوبوس چقدر بیشتر طول می‌کشه؟"),T("Daniel","About two hours longer, but it's cheaper.","حدود دو ساعت بیشتر، ولی ارزون‌تره.")],1),D("hotel","Updating the hotel and getting advice","hotel call",["Leo","Claire"],[T("Leo","Our train was cancelled, so we'll arrive around ten instead of seven.","قطارمون لغو شده، پس به‌جای هفت حدود ده می‌رسیم."),T("Claire","That's fine. Reception is open all night.","مشکلی نیست. پذیرش تمام شب بازه."),T("Leo","Could you recommend somewhere nearby for a late dinner?","می‌شه برای شام دیرهنگام جایی نزدیک پیشنهاد بدید؟"),T("Claire","There's a local restaurant two blocks away that serves until eleven.","دو بلوک اون‌طرف‌تر رستوران محلی هست که تا یازده سرو می‌کنه.")],2),D("replan","Replanning the next day","hotel breakfast",["Maya","Leo"],[T("Maya","The museum tour is fully booked tomorrow.","تور موزه فردا کاملاً پره."),T("Leo","Then we could visit the market in the morning and try the museum in the afternoon.","پس می‌تونیم صبح بازار بریم و بعدازظهر موزه رو امتحان کنیم."),T("Maya","We need to meet Priya at four, remember.","یادت باشه ساعت چهار با پریا قرار داریم."),T("Leo","Right. Let's do the market, have lunch nearby, and keep the afternoon simple.","درسته. بازار بریم، نزدیکش ناهار بخوریم و بعدازظهر رو ساده نگه داریم.")],4)],
"fill":["If the museum is full, we ___ visit the market instead.",["could","did","have","were"],"could"]
}
]

def main():
    OUT.mkdir(parents=True,exist_ok=True); w=[]
    for s in UNITS:
        p=OUT/s["file"]; p.write_text(json.dumps(build(s),ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); w.append(p.name)
    print(json.dumps({"written":len(w),"files":w},ensure_ascii=False,indent=2))
if __name__=="__main__": main()
