#!/usr/bin/env python3
from __future__ import annotations
import json
from scripts.generate_b1_batch import V,U,G,D,T,build,OUT

UNITS=[
{
"slug":"b1-food-preferences","file":"b1-food-preferences-v1.json","topic":"restaurants","lessons":3,
"vocab":[V("allergy","allergy","حساسیت غذایی"),V("ingredient","ingredient","مواد تشکیل‌دهنده"),V("vegetarian","vegetarian","گیاه‌خوار","adjective"),V("dairy","dairy","لبنیات"),V("gluten","gluten","گلوتن"),V("substitute","substitute","جایگزین کردن","verb"),V("spicy","spicy","تند","adjective"),V("preference","preference","ترجیح"),V("portion","portion","پرس / مقدار غذا"),V("suitable","suitable","مناسب","adjective")],
"utterances":[U("allergy","I have a serious nut allergy, so I need to know exactly what's in the sauce.","من حساسیت شدید به مغزها دارم، پس باید دقیق بدونم داخل سس چیه.","explain_allergy",["allergy","ingredient"],1),U("vegetarian","Do you have a vegetarian option that doesn't contain dairy?","گزینه گیاه‌خواری دارید که لبنیات نداشته باشه؟","ask_dietary_option",["vegetarian","dairy"],1),U("gluten","The soup is gluten-free, but the bread that comes with it isn't.","سوپ بدون گلوتنه، ولی نونی که همراهش میاد نیست.","clarify_ingredient",["gluten","ingredient"],1),U("substitute","Could you substitute roasted vegetables for the fries?","می‌شه به‌جای سیب‌زمینی سرخ‌کرده سبزیجات کبابی بذارید؟","request_substitution",["substitute"],2,"polite"),U("spice","I enjoy spicy food, but I'd prefer something milder tonight.","غذای تند دوست دارم، ولی امشب ترجیح می‌دم ملایم‌تر باشه.","state_preference",["spicy","preference"],2),U("portion","Is the main-course portion large enough to share?","پرس غذای اصلی آن‌قدر بزرگ هست که دو نفر بخورن؟","ask_portion",["portion"],2),U("relative","I'm looking for a dish that is filling but not too heavy.","دنبال غذایی هستم که سیرکننده باشه ولی خیلی سنگین نباشه.","describe_suitable_food",["suitable"],3),U("choice","I'd rather choose the grilled fish because it fits my diet better.","ترجیح می‌دم ماهی گریل‌شده رو بگیرم چون با رژیمم بهتر جور درمیاد.","make_food_choice",["preference"],3)],
"grammar":[G("relative_food","Relative clauses for food","Use that/which to add essential information about a dish or ingredient.","برای اضافه کردن اطلاعات ضروری درباره غذا یا ماده غذایی از that/which استفاده می‌کنیم.",[("I need a dish that doesn't contain dairy.","غذایی می‌خوام که لبنیات نداشته باشه."),("The sauce which comes with it is spicy.","سس همراهش تنده.")],1),G("quantifiers","Quantifiers review","Use much/many, a little/a few, enough, and too much/many to talk precisely about amounts.","برای مقدار دقیق‌تر از much/many، a little/a few، enough و too much/many استفاده می‌کنیم.",[("There's too much salt in this.","این زیادی نمک داره."),("There are a few vegetarian choices.","چند گزینه گیاه‌خواری هست.")],2),G("preference","would rather / prefer","Use would rather + base verb and prefer + noun/-ing to express food preferences.","برای ترجیح غذایی از would rather + فعل پایه و prefer + اسم/ing استفاده می‌کنیم.",[("I'd rather have soup.","ترجیح می‌دم سوپ بخورم."),("I prefer eating lighter meals at night.","شب‌ها غذای سبک‌تر رو ترجیح می‌دم.")],3)],
"dialogues":[D("allergy","Checking ingredients","restaurant",["Maya","Daniel"],[T("Maya","I have a nut allergy. Does this sauce contain any nuts?","به مغزها حساسیت دارم. این سس مغز داره؟"),T("Daniel","The sauce itself doesn't, but it's prepared in a kitchen that uses nuts.","خود سس نداره، ولی در آشپزخانه‌ای آماده می‌شه که مغز استفاده می‌کنه."),T("Maya","Thanks for telling me. What's the safest option?","ممنون که گفتید. امن‌ترین گزینه چیه؟"),T("Daniel","The grilled chicken can be prepared separately.","مرغ گریل‌شده رو می‌تونیم جدا آماده کنیم.")],1),D("substitute","Changing a side dish","cafe",["Hana","Noah"],[T("Hana","Could I have the burger without cheese?","می‌شه برگر رو بدون پنیر بگیرم؟"),T("Noah","Of course. Would you like fries with it?","حتماً. سیب‌زمینی هم می‌خواید؟"),T("Hana","Could I substitute a salad instead?","می‌شه به جاش سالاد بگیرم؟"),T("Noah","Yes, that's no problem.","بله، مشکلی نیست.")],2),D("choice","Choosing dinner","restaurant",["Sofia","Omar"],[T("Sofia","The curry sounds good, but I don't want anything too spicy tonight.","کاری خوب به نظر میاد، ولی امشب غذای خیلی تند نمی‌خوام."),T("Omar","The grilled fish is milder and comes with vegetables.","ماهی گریل‌شده ملایم‌تره و با سبزیجات میاد."),T("Sofia","That sounds better for me.","اون برای من بهتره."),T("Omar","Good choice. The portion is generous too.","انتخاب خوبیه. پرسش هم خوبه.")],3)],
"fill":["I'd rather ___ something lighter tonight.",["have","having","to have","had"],"have"]
},
{
"slug":"b1-health-wellbeing","file":"b1-health-wellbeing-v1.json","topic":"basic-health","lessons":3,
"vocab":[V("wellbeing","wellbeing","سلامت و حال خوب"),V("stress","stress","استرس"),V("sleep_quality","sleep quality","کیفیت خواب"),V("balanced","balanced","متعادل","adjective"),V("routine","routine","روال"),V("recover","recover","ریکاوری کردن / بهبود یافتن","verb"),V("energy","energy","انرژی"),V("overwhelmed","overwhelmed","تحت فشار زیاد","adjective"),V("break","break","استراحت کوتاه"),V("habit","habit","عادت")],
"utterances":[U("stress","I've been feeling more stressed since my workload increased.","از وقتی حجم کارم بیشتر شده استرس بیشتری دارم.","describe_wellbeing_change",["stress"],1),U("sleep","My sleep quality improves when I stop using my phone before bed.","وقتی قبل خواب گوشی استفاده نمی‌کنم کیفیت خوابم بهتر می‌شه.","describe_habit_effect",["sleep_quality","habit"],1),U("balanced","A balanced routine is easier to maintain than an extreme one.","روال متعادل رو راحت‌تر از برنامه افراطی می‌شه ادامه داد.","evaluate_routine",["balanced","routine"],1),U("break","Taking short breaks helps me stay focused during long work sessions.","استراحت‌های کوتاه کمک می‌کنه در زمان کار طولانی متمرکز بمونم.","explain_benefit",["break"],2),U("overwhelmed","If you feel overwhelmed, it may help to reduce the number of tasks you're trying to do at once.","اگر خیلی تحت فشار حس می‌کنی، شاید کمک کنه تعداد کارهایی که هم‌زمان انجام می‌دی کمتر کنی.","give_wellbeing_advice",["overwhelmed"],2),U("recover","You need to give your body enough time to recover after intense exercise.","بعد از ورزش سنگین باید به بدنت زمان کافی برای ریکاوری بدی.","give_recovery_advice",["recover"],2),U("energy","I've had more energy since I started walking during my lunch break.","از وقتی وقت ناهار پیاده‌روی می‌کنم انرژی بیشتری دارم.","report_positive_change",["energy"],3),U("sustainable","The best health plan is one you can realistically continue for months, not days.","بهترین برنامه سلامتی اونیه که واقعاً بتونی ماه‌ها ادامه بدی، نه چند روز.","summarize_wellbeing_view",["routine","habit"],3)],
"grammar":[G("advice","should / ought to for wellbeing","Use should and ought to for practical recommendations rather than medical certainty.","برای توصیه عملی در زمینه سلامت از should و ought to استفاده می‌کنیم، نه برای تشخیص قطعی.",[("You should take regular breaks.","بهتره منظم استراحت کنی."),("You ought to get more sleep.","بهتره بیشتر بخوابی.")],1),G("gerund_inf","Gerunds and infinitives","Some verbs are followed by -ing and others by to + infinitive; common chunks should be learned as patterns.","بعضی فعل‌ها با ing و بعضی با to + مصدر می‌آیند؛ بهتر است به شکل الگو یاد گرفته شوند.",[("I enjoy walking after work.","بعد کار پیاده‌روی دوست دارم."),("I try to sleep eight hours.","سعی می‌کنم هشت ساعت بخوابم.")],2),G("cause_effect","Cause and effect links","Use because, so, which means, and as a result to connect lifestyle choices and effects.","برای وصل کردن انتخاب سبک زندگی و نتیجه از because، so، which means و as a result استفاده می‌کنیم.",[("I sleep badly, so I'm tired.","بد می‌خوابم، پس خسته‌ام."),("I changed my routine. As a result, I have more energy.","روالم رو عوض کردم. در نتیجه انرژی بیشتری دارم.")],3)],
"dialogues":[D("workload","Talking about stress","park",["Lina","Ben"],[T("Lina","I've been feeling overwhelmed at work lately.","این اواخر سر کار خیلی تحت فشارم."),T("Ben","Have you been taking any real breaks during the day?","در طول روز واقعاً استراحت می‌کنی؟"),T("Lina","Not really. I usually eat at my desk.","نه زیاد. معمولاً پشت میز غذا می‌خورم."),T("Ben","You should try stepping away for at least twenty minutes.","بهتره حداقل بیست دقیقه از میز فاصله بگیری.")],1),D("sleep","Improving sleep","cafe",["Amir","Ella"],[T("Amir","I've been sleeping badly for weeks.","چند هفته‌ست بد می‌خوابم."),T("Ella","Do you use your phone in bed?","توی تخت گوشی استفاده می‌کنی؟"),T("Amir","Usually, yes.","معمولاً آره."),T("Ella","Try leaving it outside the bedroom for a week and see if it helps.","یک هفته بیرون اتاق بذارش و ببین کمک می‌کنه یا نه.")],2),D("routine","Finding a sustainable routine","gym lobby",["Ravi","Mina"],[T("Ravi","I keep starting intense workout plans and quitting after two weeks.","مدام برنامه ورزش سنگین شروع می‌کنم و دو هفته بعد ول می‌کنم."),T("Mina","Maybe the plans are too extreme.","شاید برنامه‌ها زیادی سنگینن."),T("Ravi","So I should start smaller?","پس باید سبک‌تر شروع کنم؟"),T("Mina","Exactly. A routine you can maintain is more useful than a perfect one you quit.","دقیقاً. روالی که بتونی ادامه بدی از برنامه بی‌نقصی که رهاش کنی مفیدتره.")],3)],
"fill":["Taking short breaks helps me ___ focused.",["stay","staying","to staying","stayed"],"stay"]
},
{
"slug":"b1-medical-appointments","file":"b1-medical-appointments-v1.json","topic":"basic-health","lessons":3,
"vocab":[V("symptom","symptom","علامت"),V("persistent","persistent","مداوم","adjective"),V("appointment","appointment","وقت پزشکی"),V("prescription","prescription","نسخه"),V("dose","dose","دوز"),V("swelling","swelling","ورم"),V("improve","improve","بهبود پیدا کردن","verb"),V("worsen","worsen","بدتر شدن","verb"),V("onset","onset","شروع علائم"),V("follow_up","follow-up","پیگیری")],
"utterances":[U("duration","I've had this cough for about three weeks, and it hasn't improved.","حدود سه هفته‌ست این سرفه رو دارم و بهتر نشده.","describe_duration",["symptom","persistent","improve"],1),U("onset","The pain started suddenly on Tuesday evening after dinner.","درد سه‌شنبه شب بعد شام ناگهانی شروع شد.","describe_onset",["onset"],1),U("change","It was mild at first, but it has gradually become worse.","اول خفیف بود، ولی کم‌کم بدتر شده.","describe_symptom_change",["worsen"],1),U("swelling","There's some swelling around my ankle, especially by the end of the day.","اطراف مچ پام کمی ورم هست، مخصوصاً آخر روز.","describe_symptom",["swelling"],2),U("questions","Have you taken any medication for it yet?","تا حالا برایش دارویی مصرف کردی؟","answer_medical_question",["prescription"],2),U("dose","The doctor told me to take one dose with food twice a day.","دکتر گفت روزی دو بار یک دوز همراه غذا بخورم.","relay_medical_advice",["dose"],2),U("follow","She asked me to book a follow-up appointment if the symptoms didn't improve.","گفت اگر علائم بهتر نشد برای پیگیری وقت بگیرم.","relay_followup_advice",["follow_up","appointment"],3),U("clarify","Could you explain what side effects I should watch for?","می‌شه توضیح بدید باید مراقب چه عوارضی باشم؟","ask_for_clarification",["prescription"],3,"polite")],
"grammar":[G("for_since","Present perfect with for / since","Use present perfect with for for duration and since for the starting point of a situation continuing now.","برای مدت از for و برای نقطه شروع از since همراه present perfect استفاده می‌کنیم.",[("I've had it for three weeks.","سه هفته‌ست دارمش."),("I've felt tired since Monday.","از دوشنبه خسته‌ام.")],1),G("past_onset","Past simple for symptom onset","Use past simple for the specific time a symptom began or a finished event connected to it.","برای زمان مشخص شروع علامت یا اتفاق تمام‌شده مرتبط از past simple استفاده می‌کنیم.",[("The pain started Tuesday night.","درد سه‌شنبه شب شروع شد."),("I fell during a run yesterday.","دیروز هنگام دویدن افتادم.")],2),G("reported_advice","Reported medical advice","Use told me to / asked me to / said I should to report straightforward advice.","برای انتقال توصیه پزشکی از told me to، asked me to یا said I should استفاده می‌کنیم.",[("She told me to rest.","گفت استراحت کنم."),("He said I should drink more water.","گفت بهتره آب بیشتری بخورم.")],3)],
"dialogues":[D("doctor","Explaining symptoms","clinic",["Maya","Drake"],[T("Drake","What brings you in today?","امروز برای چی اومدید؟"),T("Maya","I've had a cough for about three weeks, and it hasn't improved.","حدود سه هفته‌ست سرفه دارم و بهتر نشده."),T("Drake","Did it start with a cold?","با سرماخوردگی شروع شد؟"),T("Maya","Yes, but the cold went away after a few days.","آره، ولی سرماخوردگی بعد چند روز خوب شد.")],1),D("ankle","An ankle problem","clinic",["Hana","Claire"],[T("Claire","When did the ankle pain start?","درد مچ پا کی شروع شد؟"),T("Hana","Tuesday evening, after I went running.","سه‌شنبه عصر، بعد از دویدن."),T("Claire","Has the swelling gotten worse since then?","از اون موقع ورم بدتر شده؟"),T("Hana","A little, especially in the evenings.","کمی، مخصوصاً عصرها.")],2),D("follow","Understanding instructions","pharmacy",["Sofia","Daniel"],[T("Sofia","The doctor told me to take this twice a day.","دکتر گفت روزی دو بار این رو بخورم."),T("Daniel","Yes, one tablet with food in the morning and evening.","بله، یک قرص همراه غذا صبح و عصر."),T("Sofia","Are there any side effects I should watch for?","عوارضی هست که باید مراقبش باشم؟"),T("Daniel","If you feel very dizzy, stop taking it and contact your doctor.","اگر خیلی سرگیجه گرفتی، مصرف رو قطع کن و با پزشکت تماس بگیر.")],3)],
"fill":["I've had this cough ___ three weeks.",["for","since","ago","during"],"for"]
},
{
"slug":"b1-travel-planning","file":"b1-travel-planning-v1.json","topic":"transport","lessons":3,
"vocab":[V("itinerary","itinerary","برنامه سفر"),V("connection","connection","پرواز/قطار اتصال"),V("flexible","flexible","منعطف","adjective"),V("accommodation","accommodation","اقامتگاه"),V("direct","direct","مستقیم","adjective"),V("layover","layover","توقف بین راه"),V("refundable","refundable","قابل استرداد","adjective"),V("availability","availability","موجودی"),V("route","route","مسیر"),V("reservation","reservation","رزرو")],
"utterances":[U("route","The direct flight is faster, but the route with one connection is much cheaper.","پرواز مستقیم سریع‌تره، ولی مسیر با یک توقف خیلی ارزون‌تره.","compare_routes",["direct","connection","route"],1),U("flexible","I'd rather book a flexible ticket in case our plans change.","ترجیح می‌دم بلیت منعطف بگیریم اگر برنامه عوض شد.","choose_flexible_ticket",["flexible"],1),U("layover","A two-hour layover should be enough unless the first flight is delayed.","توقف دو ساعته باید کافی باشه مگر اینکه پرواز اول تأخیر داشته باشه.","evaluate_connection",["layover","connection"],1),U("stay","The apartment is farther from the center, but it includes a kitchen and free parking.","آپارتمان از مرکز دورتره، ولی آشپزخانه و پارکینگ رایگان داره.","compare_accommodation",["accommodation"],2),U("availability","There's limited availability that weekend, so we should book soon.","اون آخرهفته ظرفیت محدوده، پس بهتره زود رزرو کنیم.","discuss_availability",["availability","reservation"],2),U("refund","If we pay a little more, the reservation will be fully refundable.","اگر کمی بیشتر بدیم، رزرو کاملاً قابل استرداد می‌شه.","weigh_booking_condition",["refundable","reservation"],2),U("itinerary","I've put the museum on Saturday morning because it's close to our hotel.","موزه رو شنبه صبح گذاشتم چون نزدیک هتلمونه.","explain_itinerary",["itinerary"],3),U("plan","If the weather is good, we can keep Sunday flexible and decide then.","اگر هوا خوب بود، یکشنبه رو منعطف نگه می‌داریم و همون موقع تصمیم می‌گیریم.","keep_plan_open",["flexible"],3)],
"grammar":[G("future_review","Future forms for travel plans","Use present continuous for fixed bookings, going to for intentions, and will/might for predictions or flexible decisions.","برای رزرو قطعی از present continuous، برای قصد از going to و برای پیش‌بینی یا تصمیم منعطف از will/might استفاده می‌کنیم.",[("We're flying Friday night.","جمعه شب پرواز داریم."),("We might stay an extra day.","شاید یک روز بیشتر بمونیم.")],1),G("travel_conditionals","Conditionals for travel planning","Use if/unless to compare practical travel outcomes and backup plans.","برای بررسی نتیجه‌ها و برنامه پشتیبان سفر از if/unless استفاده می‌کنیم.",[("If the train is cheaper, we'll take it.","اگر قطار ارزون‌تر باشه، قطار می‌گیریم."),("We'll go hiking unless it rains.","مگر اینکه بارون بیاد، کوه‌پیمایی می‌ریم.")],2),G("relative_travel","Relative clauses for travel choices","Use that/which to identify routes, hotels, or tickets by their features.","برای مشخص کردن مسیر، هتل یا بلیت با ویژگی‌ها از that/which استفاده می‌کنیم.",[("I want a ticket that can be changed.","بلیتی می‌خوام که بشه تغییرش داد."),("The hotel which includes breakfast is farther away.","هتلی که صبحانه داره دورتره.")],3)],
"dialogues":[D("flight","Choosing flights","living room",["Lina","Ben"],[T("Lina","The direct flight is convenient, but it's almost twice the price.","پرواز مستقیم راحته، ولی تقریباً دو برابر قیمته."),T("Ben","How long is the layover on the cheaper route?","توقف مسیر ارزون‌تر چقدره؟"),T("Lina","About two hours.","حدود دو ساعت."),T("Ben","I'd take the cheaper one if the connection isn't too risky.","اگر اتصال خیلی ریسکی نباشه، من ارزون‌تره رو می‌گیرم.")],1),D("hotel","Choosing accommodation","video call",["Amir","Ella"],[T("Amir","This apartment is farther out, but it has a kitchen.","این آپارتمان دورتره، ولی آشپزخانه داره."),T("Ella","That could save us money on meals.","می‌تونه هزینه غذا رو کم کنه."),T("Amir","The cancellation policy is also more flexible.","قانون لغوش هم منعطف‌تره."),T("Ella","Then I think it's worth the extra travel time.","پس فکر می‌کنم ارزش زمان رفت‌وآمد اضافه رو داره.")],2),D("itinerary","Planning the weekend","cafe",["Ravi","Mina"],[T("Ravi","I've booked the museum for Saturday morning.","موزه رو برای شنبه صبح رزرو کردم."),T("Mina","What about Sunday?","یکشنبه چی؟"),T("Ravi","I'd like to keep it flexible in case the weather changes.","دوست دارم منعطف نگهش دارم اگر هوا عوض شد."),T("Mina","Good idea. We can decide after breakfast.","ایده خوبیه. بعد صبحانه تصمیم می‌گیریم.")],3)],
"fill":["I'd rather book a ticket that is fully ___.",["refundable","refund","refunding","refunded"],"refundable"]
},
{
"slug":"b1-travel-disruptions","file":"b1-travel-disruptions-v1.json","topic":"transport","lessons":3,
"vocab":[V("cancelled","cancelled","لغوشده","adjective"),V("delay","delay","تأخیر"),V("connection","connection","اتصال"),V("rebook","rebook","رزرو مجدد کردن","verb"),V("baggage","baggage","بار"),V("claim","claim","درخواست خسارت"),V("alternative","alternative","جایگزین"),V("voucher","voucher","کوپن / اعتبار"),V("compensation","compensation","غرامت"),V("stranded","stranded","گیر افتاده","adjective")],
"utterances":[U("cancelled","My flight has been cancelled, and the next direct flight isn't until tomorrow.","پروازم لغو شده و پرواز مستقیم بعدی تا فردا نیست.","report_cancellation",["cancelled"],1),U("missed","Because of the delay, I've missed my connection to Denver.","به‌خاطر تأخیر، پرواز اتصال به دنور رو از دست دادم.","report_missed_connection",["delay","connection"],1),U("rebook","Could you rebook me on the earliest available flight, even if it has a connection?","می‌شه من رو روی اولین پرواز موجود دوباره رزرو کنید، حتی اگر توقف داشته باشه؟","request_rebooking",["rebook","connection"],1,"polite"),U("passive","Passengers are being moved to a different gate while the aircraft is inspected.","مسافرها دارن به گیت دیگه منتقل می‌شن تا هواپیما بررسی بشه.","understand_disruption_update",["delay"],2),U("baggage","My bag hasn't arrived, although it was checked through to my final destination.","چمدونم نرسیده، با اینکه تا مقصد نهایی تحویل داده شده بود.","report_baggage_problem",["baggage"],2),U("claim","Where do I need to go to file a baggage claim?","برای ثبت درخواست چمدان باید کجا برم؟","ask_claim_process",["claim","baggage"],2),U("voucher","The airline offered a hotel voucher because we were stranded overnight.","شرکت هواپیمایی چون شب گیر افتادیم اعتبار هتل داد.","report_compensation",["voucher","stranded"],3),U("alternative","If there's no flight tonight, is there an alternative route by train?","اگر امشب پرواز نیست، مسیر جایگزین با قطار وجود داره؟","seek_alternative",["alternative"],3)],
"grammar":[G("passive_travel","Passive voice in travel updates","Travel announcements often use the passive because the event matters more than the actor.","اعلان‌های سفر اغلب passive هستند چون اتفاق مهم‌تر از انجام‌دهنده است.",[("The flight has been cancelled.","پرواز لغو شده."),("Passengers are being rebooked.","مسافرها دارن دوباره رزرو می‌شن.")],1),G("present_perfect_problem","Present perfect for ongoing disruption","Use present perfect when a travel problem has happened and still affects the current situation.","برای مشکل سفر که اتفاق افتاده و هنوز اثرش ادامه دارد از present perfect استفاده می‌کنیم.",[("I've missed my connection.","پرواز اتصال رو از دست داده‌ام."),("My bag hasn't arrived.","چمدونم نرسیده.")],2),G("conditionals_options","Conditionals for next steps","Use if + present with can/could/will to discuss practical alternatives.","برای گزینه‌های عملی بعدی از if + present همراه can/could/will استفاده می‌کنیم.",[("If there's no flight, could I take the train?","اگر پرواز نیست، می‌تونم قطار بگیرم؟"),("If you wait here, we'll call your name.","اگر اینجا صبر کنید، اسمتون رو صدا می‌کنیم.")],3)],
"dialogues":[D("cancel","Cancelled flight","airport desk",["Maya","Daniel"],[T("Maya","My flight to Denver has been cancelled. What are my options?","پروازم به دنور لغو شده. چه گزینه‌هایی دارم؟"),T("Daniel","We can rebook you tonight with one connection, or tomorrow on a direct flight.","می‌تونیم امشب با یک توقف رزرو کنیم یا فردا مستقیم."),T("Maya","I'd prefer tonight if the connection is reasonable.","امشب رو ترجیح می‌دم اگر توقف منطقی باشه."),T("Daniel","There's a ninety-minute connection in Chicago.","در شیکاگو توقف نود دقیقه‌ای هست.")],1),D("bag","Missing baggage","baggage desk",["Hana","Noah"],[T("Hana","My suitcase hasn't arrived on the carousel.","چمدونم روی نوار نیومده."),T("Noah","Do you have the baggage tag?","برچسب بار رو دارید؟"),T("Hana","Yes. It was checked through from Boston.","آره. از بوستون تا مقصد نهایی تحویل داده شده بود."),T("Noah","We'll trace it and create a claim for you.","ردیابیش می‌کنیم و درخواست براتون ثبت می‌کنیم.")],2),D("overnight","Stranded overnight","airport lounge",["Sofia","Omar"],[T("Sofia","They've rebooked us for tomorrow morning.","ما رو برای فردا صبح دوباره رزرو کردند."),T("Omar","Did they offer a hotel?","هتل پیشنهاد دادند؟"),T("Sofia","Yes, we got a voucher for a hotel near the airport.","آره، اعتبار هتل نزدیک فرودگاه دادند."),T("Omar","At least we won't have to sleep here.","حداقل لازم نیست اینجا بخوابیم.")],3)],
"fill":["My flight has been ___, so I need another route.",["cancelled","cancel","cancelling","cancellation"],"cancelled"]
}
]

def main():
    OUT.mkdir(parents=True,exist_ok=True); w=[]
    for s in UNITS:
        p=OUT/s["file"]; p.write_text(json.dumps(build(s),ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); w.append(p.name)
    print(json.dumps({"written":len(w),"files":w},ensure_ascii=False,indent=2))
if __name__=="__main__": main()
