#!/usr/bin/env python3
from __future__ import annotations
import json
from scripts.generate_b1_batch import V,U,G,D,T,build,OUT

UNITS = [
{
"slug":"b1-storytelling","file":"b1-storytelling-v1.json","topic":"simple-messages","lessons":3,
"vocab":[V("turn_out","turn out","از آب درآمدن","phrasal_verb"),V("unexpected","unexpected","غیرمنتظره","adjective"),V("meanwhile","meanwhile","در همین حین","adverb"),V("in_the_end","in the end","در نهایت","adverb"),V("soaked","soaked","خیسِ خیس","adjective"),V("notice","notice","متوجه شدن","verb"),V("manage","manage","موفق شدن","verb"),V("fortunately","fortunately","خوشبختانه","adverb"),V("such","such","چنین / این‌قدر","determiner"),V("relieved","relieved","خیالش راحت شده","adjective")],
"utterances":[U("opening","It started as a normal Saturday, but it turned out to be anything but normal.","مثل یک شنبه معمولی شروع شد، ولی آخرش اصلاً معمولی از آب درنیومد.","open_story",["turn_out"],1),U("storm","We were hiking when an unexpected storm moved in.","داشتیم کوه‌پیمایی می‌کردیم که یک طوفان غیرمنتظره رسید.","introduce_complication",["unexpected"],1),U("meanwhile","Meanwhile, our friends were waiting for us at the cabin.","در همین حین، دوستانمون در کلبه منتظر ما بودند.","add_parallel_event",["meanwhile"],1),U("notice","I didn't notice that my phone battery was almost dead until we got lost.","تا وقتی گم شدیم متوجه نشدم باتری گوشیم تقریباً تموم شده.","add_detail",["notice"],2),U("soaked","By the time we found the trail again, we were completely soaked.","تا وقتی دوباره مسیر رو پیدا کردیم، خیسِ خیس شده بودیم.","describe_result",["soaked"],2),U("managed","Fortunately, we managed to reach the cabin before dark.","خوشبختانه موفق شدیم قبل از تاریکی به کلبه برسیم.","resolve_problem",["fortunately","manage"],2),U("emphasis","It was such a stressful afternoon that nobody spoke for the first ten minutes.","بعدازظهر آن‌قدر پراسترسی بود که ده دقیقه اول هیچ‌کس حرف نزد.","emphasize_result",["such"],3),U("ending","In the end, we were just relieved to be safe and warm.","در نهایت فقط خوشحال بودیم که سالم و در جای گرم هستیم.","close_story",["in_the_end","relieved"],3)],
"grammar":[G("narrative_review","Narrative tenses review","Combine past simple for main events, past continuous for background, and past perfect when an earlier past event matters.","برای روایت منسجم، از past simple برای اتفاق اصلی، past continuous برای پس‌زمینه و past perfect برای اتفاقی که قبل‌تر رخ داده استفاده می‌کنیم.",[("We were driving when the engine stopped.","داشتیم رانندگی می‌کردیم که موتور خاموش شد."),("I realized I had left the map at home.","فهمیدم نقشه را خانه جا گذاشته بودم.")],1),G("linkers","Story linkers","Use meanwhile, by the time, eventually, and in the end to guide the listener through a story.","برای هدایت شنونده در داستان از meanwhile، by the time، eventually و in the end استفاده می‌کنیم.",[("Meanwhile, the rain got heavier.","در همین حین باران شدیدتر شد."),("In the end, everyone laughed about it.","در نهایت همه بهش خندیدند.")],2),G("so_such","so / such for emphasis","Use so + adjective/adverb and such + noun phrase to emphasize a strong result.","برای تأکید از so + صفت/قید و such + گروه اسمی استفاده می‌کنیم.",[("It was so cold that we went back.","آن‌قدر سرد بود که برگشتیم."),("It was such a long day that I fell asleep immediately.","آن‌قدر روز طولانی‌ای بود که فوراً خوابم برد.")],3)],
"dialogues":[D("camping","A camping story","kitchen",["Maya","Leo"],[T("Maya","You look exhausted. What happened?","خیلی خسته به نظر میای. چی شد؟"),T("Leo","We were camping when a huge storm started.","داشتیم کمپ می‌کردیم که یک طوفان شدید شروع شد."),T("Maya","Were you able to get back safely?","تونستید سالم برگردید؟"),T("Leo","Fortunately, yes. We reached the car just before dark.","خوشبختانه آره. درست قبل از تاریکی به ماشین رسیدیم.")],1),D("train","The wrong train","office break room",["Hana","Noah"],[T("Hana","How was your trip yesterday?","سفرت دیروز چطور بود؟"),T("Noah","Embarrassing. I got on the wrong train without noticing.","خجالت‌آور. بدون اینکه بفهمم سوار قطار اشتباهی شدم."),T("Hana","When did you realize?","کی فهمیدی؟"),T("Noah","By the time I noticed, we had already passed my stop.","وقتی فهمیدم، از ایستگاهم رد شده بودیم.")],2),D("ending","A happy ending","cafe",["Sofia","Omar"],[T("Sofia","That sounds like such a stressful day.","به نظر روز خیلی پراسترسی میاد."),T("Omar","It was, but in the end everything worked out.","بود، ولی در نهایت همه‌چی درست شد."),T("Sofia","So would you do the trip again?","پس دوباره این سفر رو می‌ری؟"),T("Omar","Definitely, but next time I'm checking the weather first.","حتماً، ولی دفعه بعد اول هوا رو چک می‌کنم.")],3)],
"fill":["It was ___ a stressful day that I went straight to bed.",["such","so","very","too"],"such"]
},
{
"slug":"b1-memorable-experiences","file":"b1-memorable-experiences-v1.json","topic":"hobbies","lessons":3,
"vocab":[V("memorable","memorable","به‌یادماندنی","adjective"),V("once_in_a_lifetime","once-in-a-lifetime","یک‌بار در عمر","adjective"),V("impressed","impressed","تحت‌تأثیر","adjective"),V("perform","perform","اجرا کردن","verb"),V("audience","audience","تماشاگران"),V("achievement","achievement","دستاورد"),V("ever","ever","تا به حال","adverb"),V("yet","yet","هنوز / تا الان","adverb"),V("already","already","قبلاً / همین حالا","adverb"),V("worth","worth","ارزش داشتن","adjective")],
"utterances":[U("best","What's the most memorable concert you've ever been to?","به‌یادماندنی‌ترین کنسرتی که تا حالا رفتی کدوم بوده؟","ask_experience",["memorable","ever"],1),U("first_time","I've never performed in front of such a large audience before.","قبلاً هیچ‌وقت جلوی چنین جمعیت بزرگی اجرا نکرده بودم.","describe_first_experience",["perform","audience"],1),U("detail","I saw them live in Seattle two years ago, and they were amazing.","دو سال پیش در سیاتل زنده دیدمشون و فوق‌العاده بودند.","add_past_detail",["impressed"],1),U("already","I've already visited the museum twice, but I'd happily go again.","تا حالا دو بار موزه رو دیدم، ولی بازم با خوشحالی می‌رم.","state_repeated_experience",["already"],2),U("yet","I haven't tried scuba diving yet, although I'd really like to.","هنوز غواصی با کپسول رو امتحان نکردم، با اینکه خیلی دوست دارم.","state_untried_experience",["yet"],2),U("achievement","Finishing my first half-marathon is an achievement I'm still proud of.","تمام کردن اولین نیمه‌ماراتنم دستاوردیه که هنوز بهش افتخار می‌کنم.","describe_achievement",["achievement"],2),U("worth","The trip was expensive, but the experience was absolutely worth it.","سفر گرون بود، ولی تجربه‌اش کاملاً ارزش داشت.","evaluate_experience",["worth"],3),U("lifetime","Seeing the northern lights felt like a once-in-a-lifetime experience.","دیدن شفق قطبی حس یک تجربه یک‌بار در عمر رو داشت.","reflect_experience",["once_in_a_lifetime"],3)],
"grammar":[G("perfect_past","Present perfect vs past simple for experiences","Use present perfect to ask or talk about experience without a finished time; switch to past simple for specific details.","برای تجربه بدون زمان تمام‌شده از present perfect استفاده می‌کنیم و برای جزئیات مشخص گذشته به past simple می‌رویم.",[("Have you ever seen a whale?","تا حالا نهنگ دیدی؟"),("Yes, I saw one in Canada last year.","آره، پارسال در کانادا یکی دیدم.")],1),G("experience_adverbs","ever, never, already, yet","Use ever/never for life experience, already for something completed sooner than expected, and yet in negatives/questions about unfinished experience.","ever و never برای تجربه زندگی، already برای چیزی که انجام شده و yet برای سؤال یا منفیِ چیزی که هنوز انجام نشده استفاده می‌شود.",[("I've already read it.","قبلاً خوندمش."),("Have you tried it yet?","تا حالا امتحانش کردی؟")],2),G("relative_intro","Defining relative clauses","Use who, that, or which to add essential information about a person or thing.","با who، that یا which اطلاعات ضروری درباره شخص یا چیز اضافه می‌کنیم.",[("She's the coach who encouraged me.","او مربی‌ایه که تشویقم کرد."),("It was a trip that changed my perspective.","سفری بود که دیدگاهم رو عوض کرد.")],3)],
"dialogues":[D("concert","A memorable concert","restaurant",["Lina","Ben"],[T("Lina","Have you ever seen your favorite band live?","تا حالا گروه موردعلاقه‌ات رو زنده دیدی؟"),T("Ben","Yes, I saw them in Austin three years ago.","آره، سه سال پیش در آستین دیدمشون."),T("Lina","What made it so memorable?","چی باعث شد این‌قدر به‌یادماندنی باشه؟"),T("Ben","The audience knew every song. The energy was incredible.","تماشاگرها همه آهنگ‌ها رو بلد بودند. انرژی فوق‌العاده بود.")],1),D("challenge","A personal achievement","park",["Amir","Ella"],[T("Amir","What's an achievement you're really proud of?","به کدوم دستاوردت واقعاً افتخار می‌کنی؟"),T("Ella","I finished my first long-distance bike ride last summer.","تابستون گذشته اولین دوچرخه‌سواری طولانی‌م رو تموم کردم."),T("Amir","Had you trained for it long?","مدت زیادی براش تمرین کرده بودی؟"),T("Ella","About four months. It was difficult, but completely worth it.","حدود چهار ماه. سخت بود، ولی کاملاً ارزش داشت.")],2),D("bucket","Things still to try","video call",["Ravi","Mina"],[T("Ravi","Have you tried surfing yet?","تا حالا موج‌سواری رو امتحان کردی؟"),T("Mina","Not yet, but it's high on my list.","هنوز نه، ولی خیلی دوست دارم امتحانش کنم."),T("Ravi","I've done it once. The first hour was mostly falling.","من یک بار انجامش دادم. ساعت اول بیشتر افتادن بود."),T("Mina","That still sounds fun.","بازم باحال به نظر میاد.")],3)],
"fill":["Have you ___ tried scuba diving?",["ever","ago","last","since"],"ever"]
},
{
"slug":"b1-plans-predictions","file":"b1-plans-predictions-v1.json","topic":"future-plans","lessons":3,
"vocab":[V("arrangement","arrangement","قرار قطعی"),V("intention","intention","قصد"),V("predict","predict","پیش‌بینی کردن","verb"),V("probably","probably","احتمالاً","adverb"),V("definitely","definitely","قطعاً","adverb"),V("decision","decision","تصمیم"),V("schedule","schedule","برنامه زمانی"),V("forecast","forecast","پیش‌بینی"),V("expect","expect","انتظار داشتن","verb"),V("spontaneous","spontaneous","بداهه / ناگهانی","adjective")],
"utterances":[U("meeting","I'm meeting the designer at ten tomorrow morning.","فردا ساعت ده با طراح جلسه دارم.","state_arrangement",["arrangement","schedule"],1),U("intention","I'm going to update my portfolio before I apply.","قبل از درخواست دادن قصد دارم پورتفولیومم رو به‌روز کنم.","state_intention",["intention"],1),U("offer","I'll carry that box for you.","من اون جعبه رو برات می‌برم.","make_spontaneous_offer",["spontaneous"],1),U("prediction","I think remote work will remain common, but offices won't disappear.","فکر می‌کنم دورکاری رایج می‌مونه، ولی دفترها از بین نمی‌رن.","make_prediction",["predict"],2),U("evidence","Look at those clouds. It's going to rain soon.","اون ابرها رو ببین. به‌زودی بارون میاد.","predict_from_evidence",["forecast"],2),U("probably","We'll probably finish by Friday if nothing unexpected comes up.","اگر اتفاق غیرمنتظره‌ای نیفته احتمالاً تا جمعه تمام می‌کنیم.","qualified_prediction",["probably"],2),U("expect","I expect the event to be busier than last year.","انتظار دارم رویداد از پارسال شلوغ‌تر باشه.","state_expectation",["expect"],3),U("definite","We're definitely not driving; we've already booked train tickets.","قطعاً با ماشین نمی‌ریم؛ بلیت قطار رو رزرو کردیم.","confirm_plan",["definitely","arrangement"],3)],
"grammar":[G("future_forms","Choosing future forms","Use present continuous for fixed arrangements, going to for intentions/evidence, and will for spontaneous decisions or neutral predictions.","برای قرار قطعی از present continuous، برای قصد یا شواهد از going to و برای تصمیم لحظه‌ای یا پیش‌بینی خنثی از will استفاده می‌کنیم.",[("I'm seeing Sam tonight.","امشب سام رو می‌بینم."),("I'll answer the phone.","من تلفن رو جواب می‌دم.")],1),G("prediction_strength","Prediction adverbs","Use probably, definitely, perhaps, and likely to show how certain a prediction is.","با probably، definitely، perhaps و likely میزان اطمینان پیش‌بینی را نشان می‌دهیم.",[("It'll probably take an hour.","احتمالاً یک ساعت طول می‌کشه."),("She's definitely going to notice.","قطعاً متوجه می‌شه.")],2),G("if_future","Future with first conditional","Use if + present simple for a possible condition and will/might/can for the result.","برای شرط ممکن از if + present simple و برای نتیجه از will/might/can استفاده می‌کنیم.",[("If traffic is bad, we'll take the train.","اگر ترافیک بد باشه، قطار می‌گیریم."),("If we finish early, we might go out.","اگر زود تموم کنیم، شاید بریم بیرون.")],3)],
"dialogues":[D("week","Planning a busy week","office",["Chloe","Adam"],[T("Chloe","Are you free tomorrow afternoon?","فردا بعدازظهر آزادی؟"),T("Adam","I'm meeting a client at two, but I'm free after four.","ساعت دو با مشتری جلسه دارم، ولی بعد از چهار آزادم."),T("Chloe","Great. I'm going to review the proposal before then.","عالیه. قبلش قصد دارم پیشنهاد رو مرور کنم."),T("Adam","I'll send you my notes this evening.","امشب یادداشت‌هام رو برات می‌فرستم.")],1),D("weather","A weekend prediction","living room",["Priya","Daniel"],[T("Priya","Do you think the hike will happen on Sunday?","فکر می‌کنی یکشنبه برنامه کوه‌پیمایی انجام می‌شه؟"),T("Daniel","Probably not. Look at the forecast.","احتمالاً نه. پیش‌بینی هوا رو ببین."),T("Priya","You're right. It's going to rain all morning.","درسته. کل صبح بارون میاد."),T("Daniel","If it clears up later, we could still go for a short walk.","اگر بعداً هوا باز شد، هنوز می‌تونیم یک پیاده‌روی کوتاه بریم.")],2),D("event","Predicting an event","cafe",["Maya","Leo"],[T("Maya","How many people do you expect at the launch?","برای افتتاحیه چند نفر انتظار داری؟"),T("Leo","Probably around two hundred.","احتمالاً حدود دویست نفر."),T("Maya","That's more than last year.","از پارسال بیشتره."),T("Leo","Yes, and I think it'll be even busier online.","آره، و فکر می‌کنم آنلاین حتی شلوغ‌تر هم باشه.")],3)],
"fill":["I'm ___ the designer at ten tomorrow.",["meeting","meet","will meet","met"],"meeting"]
},
{
"slug":"b1-goals-ambitions","file":"b1-goals-ambitions-v1.json","topic":"future-plans","lessons":3,
"vocab":[V("ambition","ambition","هدف بلندپروازانه"),V("goal","goal","هدف"),V("motivation","motivation","انگیزه"),V("obstacle","obstacle","مانع"),V("achieve","achieve","به‌دست آوردن","verb"),V("realistic","realistic","واقع‌بینانه","adjective"),V("step","step","گام"),V("commit","commit","متعهد شدن","verb"),V("progress","progress","پیشرفت"),V("deadline","deadline","مهلت")],
"utterances":[U("goal","My main goal this year is to become confident enough to lead meetings in English.","هدف اصلی‌م امسال اینه که آن‌قدر اعتمادبه‌نفس پیدا کنم که جلسه‌ها رو به انگلیسی اداره کنم.","state_goal",["goal"],1),U("reason","I'm learning data analysis in order to qualify for more technical roles.","دارم تحلیل داده یاد می‌گیرم تا برای نقش‌های فنی‌تر واجد شرایط بشم.","explain_purpose",["ambition"],1),U("step","The first step is to study for thirty minutes every weekday.","گام اول اینه که هر روز کاری سی دقیقه مطالعه کنم.","describe_step",["step"],1),U("obstacle","My biggest obstacle is finding time when work gets busy.","بزرگ‌ترین مانعم پیدا کردن وقت وقتی کار شلوغ می‌شه است.","identify_obstacle",["obstacle"],2),U("conditional","If I keep this routine for six months, I'll make real progress.","اگر شش ماه این روال رو ادامه بدم، پیشرفت واقعی می‌کنم.","predict_goal_result",["progress"],2),U("realistic","I want the plan to be challenging but realistic.","می‌خوام برنامه چالش‌برانگیز ولی واقع‌بینانه باشه.","evaluate_plan",["realistic"],2),U("deadline","I've given myself a deadline of the end of March.","برای خودم تا آخر مارس مهلت گذاشتم.","set_deadline",["deadline"],3),U("commit","I'm committed to practicing even when I don't feel motivated.","متعهد شدم حتی وقتی انگیزه ندارم تمرین کنم.","express_commitment",["commit","motivation"],3)],
"grammar":[G("verb_patterns","hope / plan / expect + to","Use common planning verbs followed by to + infinitive to describe goals and expectations.","برای بیان هدف و انتظار، بسیاری از فعل‌ها مثل hope، plan و expect با to + مصدر می‌آیند.",[("I hope to finish by June.","امیدوارم تا ژوئن تمام کنم."),("We plan to expand next year.","قصد داریم سال بعد توسعه بدیم.")],1),G("purpose","Purpose with to / in order to","Use to or in order to to explain the purpose of an action.","برای توضیح هدف یک کار از to یا in order to استفاده می‌کنیم.",[("I'm saving to buy a car.","دارم پس‌انداز می‌کنم تا ماشین بخرم."),("She moved closer in order to reduce her commute.","نزدیک‌تر نقل مکان کرد تا رفت‌وآمدش کمتر بشه.")],1),G("first_conditional","First conditional for goal outcomes","Use if + present simple and will/can/might to discuss realistic future results.","برای نتیجه‌های واقع‌بینانه آینده از if + present simple و will/can/might استفاده می‌کنیم.",[("If I practice regularly, I'll improve.","اگر منظم تمرین کنم بهتر می‌شم."),("If you break the goal into steps, it may feel easier.","اگر هدف رو به گام‌ها تقسیم کنی، شاید راحت‌تر بشه.")],2)],
"dialogues":[D("career","A career goal","walk",["Hana","Noah"],[T("Hana","What's your biggest goal for this year?","بزرگ‌ترین هدفت برای امسال چیه؟"),T("Noah","I want to move into a team-lead role.","می‌خوام وارد نقش سرپرست تیم بشم."),T("Hana","What are you doing to prepare for it?","برای آماده شدن چه کار می‌کنی؟"),T("Noah","I'm taking a management course and asking for more responsibility at work.","یک دوره مدیریت می‌گذرونم و در کار مسئولیت بیشتری می‌گیرم.")],1),D("fitness","Making a realistic plan","gym lobby",["Sofia","Omar"],[T("Sofia","I want to run a half-marathon, but I keep missing workouts.","می‌خوام نیمه‌ماراتن بدوم، ولی مدام تمرین‌ها رو از دست می‌دم."),T("Omar","Maybe your plan is too demanding.","شاید برنامه‌ات زیادی سنگینه."),T("Sofia","You're probably right. I need something more realistic.","احتمالاً درست می‌گی. یک برنامه واقع‌بینانه‌تر لازم دارم."),T("Omar","If you start with three days a week, it'll be easier to stay consistent.","اگر با سه روز در هفته شروع کنی، ثابت موندن راحت‌تره.")],2),D("deadline","Checking progress","video call",["Lina","Ben"],[T("Lina","How's your course going?","دوره‌ات چطور پیش می‌ره؟"),T("Ben","Pretty well. I'm about halfway through.","خوب. تقریباً نصفش رو رفتم."),T("Lina","Do you still expect to finish by March?","هنوز انتظار داری تا مارس تمومش کنی؟"),T("Ben","Yes. I've set aside extra time on Sundays.","آره. یکشنبه‌ها وقت اضافه براش کنار گذاشتم.")],3)],
"fill":["I'm studying every day in order ___ improve faster.",["to","for","that","of"],"to"]
},
{
"slug":"b1-arrangements-changes","file":"b1-arrangements-changes-v1.json","topic":"future-plans","lessons":3,
"vocab":[V("reschedule","reschedule","زمان را عوض کردن","verb"),V("confirm","confirm","تأیید کردن","verb"),V("available","available","در دسترس","adjective"),V("alternative","alternative","گزینه جایگزین"),V("tentative","tentative","موقت / قطعی‌نشده","adjective"),V("postpone","postpone","به تعویق انداختن","verb"),V("slot","slot","بازه زمانی"),V("venue","venue","محل برگزاری"),V("might","might","شاید","modal"),V("update","update","به‌روزرسانی")],
"utterances":[U("change","Could we reschedule Thursday's meeting for Friday morning?","می‌شه جلسه پنجشنبه رو به جمعه صبح منتقل کنیم؟","request_schedule_change",["reschedule"],1,"polite"),U("availability","I'm available after ten, but I have another call at noon.","بعد از ده آزادم، ولی ظهر یک تماس دیگه دارم.","state_availability",["available","slot"],1),U("confirm","Let's confirm the time once Maya checks her schedule.","وقتی مایا برنامه‌اش رو چک کرد زمان رو قطعی کنیم.","delay_confirmation",["confirm"],1),U("postpone","We may have to postpone the outdoor event if the weather gets worse.","اگر هوا بدتر بشه شاید مجبور بشیم رویداد بیرونی رو عقب بندازیم.","discuss_possible_change",["postpone","might"],2),U("alternative","If Friday doesn't work, Monday afternoon is another option.","اگر جمعه نشد، دوشنبه بعدازظهر یک گزینه دیگه است.","offer_alternative",["alternative"],2),U("venue","The venue might change, so check the update before you leave.","ممکنه محل برگزاری عوض بشه، پس قبل از حرکت به‌روزرسانی رو چک کن.","warn_tentative_detail",["venue","might","update"],2),U("tentative","For now, let's keep the dinner plan tentative.","فعلاً برنامه شام رو قطعی نکنیم.","keep_plan_tentative",["tentative"],3),U("summary","So we're meeting at eleven on Friday unless anything changes.","پس اگر چیزی عوض نشه جمعه ساعت یازده همدیگه رو می‌بینیم.","confirm_updated_plan",["confirm"],3)],
"grammar":[G("future_arrangements","Future arrangements review","Use present continuous for arrangements that have been agreed and scheduled.","برای قرارهایی که توافق و زمان‌بندی شده‌اند از present continuous استفاده می‌کنیم.",[("We're meeting at eleven.","ساعت یازده همدیگه رو می‌بینیم."),("She's flying in on Friday.","جمعه با پرواز میاد.")],1),G("may_might","may / might for uncertain plans","Use may or might when a future plan or detail is possible but not certain.","وقتی یک برنامه یا جزئیات آینده قطعی نیست از may یا might استفاده می‌کنیم.",[("The venue might change.","ممکنه محل عوض بشه."),("We may finish earlier than expected.","شاید زودتر از انتظار تموم کنیم.")],2),G("alternatives","Conditionals for alternatives","Use if + present to discuss a possible scheduling problem and an alternative result.","برای مشکل احتمالی در برنامه و گزینه جایگزین از if + present استفاده می‌کنیم.",[("If Tuesday doesn't work, we can meet Wednesday.","اگر سه‌شنبه نشد، چهارشنبه می‌تونیم ببینیم هم."),("If it rains, we'll move the event inside.","اگر بارون بیاد، رویداد رو داخل برگزار می‌کنیم.")],2)],
"dialogues":[D("meeting","Moving a meeting","office call",["Amir","Ella"],[T("Amir","Could we move tomorrow's meeting to Friday?","می‌شه جلسه فردا رو ببریم جمعه؟"),T("Ella","Friday works for me after ten.","جمعه بعد از ده برای من خوبه."),T("Amir","How about eleven?","یازده چطوره؟"),T("Ella","Perfect. I'll update the calendar invite.","عالیه. دعوت تقویم رو به‌روز می‌کنم.")],1),D("weather","Changing an outdoor plan","group call",["Ravi","Mina"],[T("Ravi","The forecast looks worse for Saturday.","پیش‌بینی هوا برای شنبه بدتر شده."),T("Mina","Do you think we should postpone the picnic?","فکر می‌کنی پیک‌نیک رو عقب بندازیم؟"),T("Ravi","Maybe. If it rains, we could meet at my place instead.","شاید. اگر بارون بیاد می‌تونیم به جاش خونه من جمع بشیم."),T("Mina","Let's decide tomorrow when the forecast is clearer.","فردا وقتی پیش‌بینی دقیق‌تر شد تصمیم بگیریم.")],2),D("confirm","Confirming details","text messages",["Chloe","Adam"],[T("Chloe","Are we still on for Friday at eleven?","هنوز جمعه ساعت یازده قراره؟"),T("Adam","Yes, unless the client changes the time again.","آره، مگر اینکه مشتری دوباره زمان رو عوض کنه."),T("Chloe","And is the meeting room confirmed?","اتاق جلسه هم قطعی شده؟"),T("Adam","Not yet. I'll send you an update this afternoon.","هنوز نه. بعدازظهر بهت خبر می‌دم.")],3)],
"fill":["The venue ___ change, so check the update.",["might","must","did","has"],"might"]
}
]

def main():
    OUT.mkdir(parents=True, exist_ok=True)
    written=[]
    for spec in UNITS:
        p=OUT/spec["file"]
        p.write_text(json.dumps(build(spec),ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
        written.append(p.name)
    print(json.dumps({"written":len(written),"files":written},ensure_ascii=False,indent=2))

if __name__=="__main__": main()
