#!/usr/bin/env python3
from __future__ import annotations
import json
from scripts.generate_b1_batch import V,U,G,D,T,build,OUT

UNITS=[
{
"slug":"b1-learning-progress","file":"b1-learning-progress-v1.json","topic":"school-study","lessons":3,
"vocab":[V("progress","progress","پیشرفت"),V("strength","strength","نقطه قوت"),V("challenge","challenge","چالش"),V("feedback","feedback","بازخورد"),V("confidence","confidence","اعتمادبه‌نفس"),V("fluency","fluency","روانی"),V("accurate","accurate","دقیق","adjective"),V("priority","priority","اولویت"),V("improve","improve","بهبود دادن","verb"),V("consistent","consistent","مداوم","adjective")],
"utterances":[U("progress","I've made the most progress in listening because I practice with short podcasts every day.","بیشترین پیشرفتم در شنیدنه چون هر روز با پادکست‌های کوتاه تمرین می‌کنم.","describe_progress",["progress"],1),U("since","My speaking confidence has improved a lot since I started practicing with a partner.","از وقتی با یک پارتنر تمرین می‌کنم اعتمادبه‌نفسم در صحبت خیلی بهتر شده.","describe_change_over_time",["confidence","improve"],1),U("strength","Understanding the main idea is one of my strengths, but details are still difficult.","فهمیدن ایده اصلی یکی از نقطه‌قوت‌هامه، ولی جزئیات هنوز سخته.","identify_strength",["strength","challenge"],1),U("yet","I haven't become as fluent as I want yet, but I hesitate much less than before.","هنوز به روانی‌ای که می‌خوام نرسیدم، ولی خیلی کمتر از قبل مکث می‌کنم.","qualify_progress",["fluency"],2),U("accuracy","My grammar is more accurate now, especially when I have time to prepare.","گرامرم الان دقیق‌تره، مخصوصاً وقتی وقت آماده شدن دارم.","compare_accuracy",["accurate"],2),U("feedback","The feedback I keep getting is that I should organize my answers more clearly.","بازخوردی که مدام می‌گیرم اینه که باید جواب‌هام رو واضح‌تر ساختاربندی کنم.","report_feedback",["feedback"],2),U("priority","My next priority is improving how quickly I respond in conversation.","اولویت بعدی‌م بهتر کردن سرعت پاسخ دادن در مکالمه است.","set_learning_priority",["priority"],3),U("consistent","If I stay consistent for another three months, I think I'll notice a big difference.","اگر سه ماه دیگه مداوم بمونم، فکر می‌کنم تفاوت بزرگی می‌بینم.","predict_future_progress",["consistent","progress"],3)],
"grammar":[G("perfect_progress","Present perfect for learning progress","Use present perfect to describe changes and achievements from the past up to now.","برای تغییر و دستاورد از گذشته تا الان از present perfect استفاده می‌کنیم.",[("I've improved a lot this year.","امسال خیلی بهتر شده‌ام."),("My vocabulary has grown since January.","دایره واژگانم از ژانویه بیشتر شده.")],1),G("comparisons_time","Comparing ability over time","Use comparative forms with now, before, than I used to, and much/a little to describe development.","برای مقایسه توانایی در طول زمان از now، before، than I used to و much/a little استفاده می‌کنیم.",[("I speak more confidently now.","الان با اعتمادبه‌نفس بیشتری صحبت می‌کنم."),("I make fewer mistakes than I used to.","کمتر از قبل اشتباه می‌کنم.")],2),G("yet_already_still","yet / already / still","Use yet, already, and still to show whether expected progress has happened or continues.","برای نشان دادن اتفاق افتادن یا ادامه داشتن پیشرفت مورد انتظار از yet، already و still استفاده می‌کنیم.",[("I haven't finished yet.","هنوز تموم نکردم."),("I can already understand most of it.","الان دیگه بیشترش رو می‌فهمم.")],3)],
"dialogues":[D("review","Reviewing progress","classroom",["Maya","Claire"],[T("Claire","Where do you feel you've made the most progress?","فکر می‌کنی کجا بیشترین پیشرفت رو داشتی؟"),T("Maya","Listening. I can follow normal-speed conversations much better now.","شنیدن. الان مکالمه‌های با سرعت طبیعی رو خیلی بهتر دنبال می‌کنم."),T("Claire","What still feels difficult?","چی هنوز سخت به نظر میاد؟"),T("Maya","Responding quickly without translating in my head.","سریع جواب دادن بدون ترجمه توی ذهنم.")],1),D("feedback","Talking about feedback","study room",["Hana","Noah"],[T("Hana","My teacher says my ideas are clear, but my answers need better structure.","معلمم می‌گه ایده‌هام واضحه، ولی جواب‌هام ساختار بهتر می‌خواد."),T("Noah","Have you tried using a simple beginning-middle-end plan?","سعی کردی از طرح ساده شروع-میانه-پایان استفاده کنی؟"),T("Hana","Not consistently.","نه به‌طور مداوم."),T("Noah","That could be a good next priority.","می‌تونه اولویت بعدی خوبی باشه.")],2),D("goal","Setting a next goal","cafe",["Sofia","Omar"],[T("Sofia","What's your next language goal?","هدف بعدی زبانت چیه؟"),T("Omar","I want to sound more natural in meetings.","می‌خوام در جلسه‌ها طبیعی‌تر حرف بزنم."),T("Sofia","How are you going to work on that?","چطور روش کار می‌کنی؟"),T("Omar","I'm going to record short practice answers and compare them over time.","جواب‌های تمرینی کوتاه ضبط می‌کنم و در طول زمان مقایسه‌شون می‌کنم.")],3)],
"fill":["My confidence has improved a lot ___ I started practicing.",["since","for","ago","during"],"since"]
},
{
"slug":"b1-media-entertainment","file":"b1-media-entertainment-v1.json","topic":"hobbies","lessons":3,
"vocab":[V("plot","plot","داستان / پیرنگ"),V("character","character","شخصیت"),V("performance","performance","اجرا"),V("episode","episode","قسمت"),V("recommend","recommend","پیشنهاد کردن","verb"),V("spoiler","spoiler","لو دادن داستان"),V("gripping","gripping","گیرا","adjective"),V("disappointing","disappointing","ناامیدکننده","adjective"),V("moving","moving","تأثیرگذار","adjective"),V("review","review","نقد")],
"utterances":[U("recommend","I'd recommend the series because the characters feel believable and the story develops slowly.","سریال رو پیشنهاد می‌کنم چون شخصیت‌ها باورپذیرن و داستان آرام پیش می‌ره.","recommend_media",["recommend","character","plot"],1),U("spoiler","I won't give you any spoilers, but the ending changes how you understand the first episode.","اسپویل نمی‌کنم، ولی پایانش برداشتت از قسمت اول رو عوض می‌کنه.","avoid_spoiler",["spoiler","episode"],1),U("performance","The lead actor gives a really convincing performance.","بازیگر اصلی اجرای خیلی قانع‌کننده‌ای داره.","evaluate_performance",["performance"],1),U("gripping","The first chapter is slow, but after that the book becomes really gripping.","فصل اول کند پیش می‌ره، ولی بعدش کتاب واقعاً گیرا می‌شه.","describe_media_pacing",["gripping"],2),U("moving","I found the documentary moving because it focuses on ordinary people's experiences.","مستند رو تأثیرگذار دیدم چون روی تجربه آدم‌های معمولی تمرکز می‌کنه.","explain_reaction",["moving"],2),U("disappointing","The visuals were impressive, but the story was surprisingly disappointing.","تصاویر چشمگیر بود، ولی داستان به‌شکل عجیبی ناامیدکننده بود.","give_mixed_review",["disappointing","plot"],2),U("relative","It's the kind of film that stays with you after it ends.","از اون فیلم‌هاست که بعد از تموم شدن هم توی ذهنت می‌مونه.","describe_media_impact",["character"],3),U("reported","A friend told me the second season was better, so I'm going to keep watching.","یکی از دوستام گفت فصل دوم بهتره، پس ادامه می‌دم.","report_recommendation",["review"],3)],
"grammar":[G("relative_media","Relative clauses for media","Use who/that/which to describe characters, stories, and works without repeating nouns.","برای توصیف شخصیت، داستان و اثر بدون تکرار اسم از who/that/which استفاده می‌کنیم.",[("It's a film that makes you think.","فیلمیه که وادارت می‌کنه فکر کنی."),("She's the actor who plays the detective.","اون بازیگریه که نقش کارآگاه رو بازی می‌کنه.")],1),G("ed_ing","-ed / -ing adjectives","Use -ing adjectives for what causes a feeling and -ed adjectives for how someone feels.","صفت -ing علت احساس و صفت -ed احساس شخص را بیان می‌کند.",[("The film was moving; I was moved.","فیلم تأثیرگذار بود؛ من تحت‌تأثیر قرار گرفتم."),("The ending was surprising; I was surprised.","پایان غافلگیرکننده بود؛ غافلگیر شدم.")],2),G("reported_opinion","Reported opinions","Use said/told me/thought that to relay someone else's reaction or recommendation.","برای انتقال نظر یا پیشنهاد دیگری از said، told me یا thought that استفاده می‌کنیم.",[("She said the book was excellent.","گفت کتاب عالی بود."),("He told me the ending was weak.","گفت پایان ضعیف بود.")],3)],
"dialogues":[D("series","Recommending a series","lunch",["Lina","Ben"],[T("Lina","Have you watched Harbor Street yet?","Harbor Street رو دیدی؟"),T("Ben","No. Is it worth starting?","نه. ارزش شروع داره؟"),T("Lina","Definitely. The first episode is slow, but the characters become really interesting.","حتماً. قسمت اول کنده، ولی شخصیت‌ها خیلی جالب می‌شن."),T("Ben","Okay, but no spoilers.","باشه، ولی اسپویل نکن.")],1),D("film","A mixed film review","cafe",["Amir","Ella"],[T("Amir","What did you think of the movie?","نظرت درباره فیلم چی بود؟"),T("Ella","The acting was excellent, but I found the plot disappointing.","بازی عالی بود، ولی داستان رو ناامیدکننده دیدم."),T("Amir","Same. The ending felt rushed.","منم همین‌طور. پایان عجولانه بود."),T("Ella","Exactly. It needed another twenty minutes.","دقیقاً. بیست دقیقه بیشتر لازم داشت.")],2),D("book","Recommending a book","bookstore",["Ravi","Mina"],[T("Ravi","I'm looking for something engaging but not too heavy.","دنبال چیزی گیرا ولی نه خیلی سنگینم."),T("Mina","Try this one. It's a mystery that takes place in a small coastal town.","این رو امتحان کن. یک معماست که در شهر ساحلی کوچیکی اتفاق می‌افته."),T("Ravi","Is it scary?","ترسناکه؟"),T("Mina","Not really. It's more atmospheric than frightening.","نه زیاد. بیشتر فضای خاص داره تا ترسناک باشه.")],3)],
"fill":["The documentary was very ___, and I felt emotional afterward.",["moving","moved","move","movement"],"moving"]
},
{
"slug":"b1-news-stories","file":"b1-news-stories-v1.json","topic":"simple-messages","lessons":3,
"vocab":[V("headline","headline","تیتر"),V("report","report","گزارش"),V("source","source","منبع"),V("according_to","according to","طبق","phrase"),V("announce","announce","اعلام کردن","verb"),V("incident","incident","حادثه"),V("official","official","رسمی","adjective"),V("detail","detail","جزئیات"),V("confirm","confirm","تأیید کردن","verb"),V("summary","summary","خلاصه")],
"utterances":[U("headline","The headline makes the story sound dramatic, but the actual report is more balanced.","تیتر داستان رو خیلی دراماتیک نشون می‌ده، ولی گزارش واقعی متعادل‌تره.","compare_headline_report",["headline","report"],1),U("main","The main point is that the city has announced a new bus route starting next month.","نکته اصلی اینه که شهر یک مسیر اتوبوس جدید از ماه بعد اعلام کرده.","summarize_main_point",["announce","summary"],1),U("source","According to the transport department, the route will serve three new neighborhoods.","طبق اداره حمل‌ونقل، مسیر سه محله جدید رو پوشش می‌ده.","cite_source",["according_to","source"],1),U("passive","Two roads were closed after the incident, but they reopened later that evening.","دو خیابون بعد حادثه بسته شدند، ولی همون شب دوباره باز شدند.","report_event",["incident"],2),U("confirm","Officials haven't confirmed the cause yet.","مقام‌ها هنوز علت رو تأیید نکردند.","state_unconfirmed_detail",["official","confirm"],2),U("detail","The report gives several details, but only one of them affects commuters directly.","گزارش چند جزئیات می‌ده، ولی فقط یکی مستقیماً روی رفت‌وآمدکننده‌ها اثر داره.","distinguish_detail",["detail","report"],2),U("reported","The mayor said the project would reduce travel time in the area.","شهردار گفت پروژه زمان سفر در منطقه رو کم می‌کنه.","report_statement",["announce"],3),U("relay","In short, the service is expanding, but the exact schedule hasn't been published yet.","خلاصه اینکه سرویس داره گسترش پیدا می‌کنه، ولی برنامه دقیق هنوز منتشر نشده.","relay_summary",["summary"],3)],
"grammar":[G("passive_news","Passive voice in news","Use passive forms when the event or result is more important than the actor.","در خبر وقتی رویداد یا نتیجه مهم‌تر از انجام‌دهنده است از passive استفاده می‌کنیم.",[("Two roads were closed.","دو خیابون بسته شدند."),("A new service has been announced.","سرویس جدیدی اعلام شده.")],1),G("reported_news","Reported speech introduction","Use said that / announced that / reported that to relay statements without quoting exactly.","برای انتقال گفته‌ها بدون نقل قول مستقیم از said that، announced that و reported that استفاده می‌کنیم.",[("The mayor said the project would help.","شهردار گفت پروژه کمک می‌کنه."),("The company announced that prices would rise.","شرکت اعلام کرد قیمت‌ها بالا می‌ره.")],2),G("cause_time","Time and cause links","Use after, before, while, because, and as a result to connect events in a news summary.","برای وصل کردن رویدادهای خبری از after، before، while، because و as a result استفاده می‌کنیم.",[("The road closed after a crash.","خیابون بعد تصادف بسته شد."),("Demand increased, so more trains were added.","تقاضا بالا رفت، پس قطار بیشتری اضافه شد.")],3)],
"dialogues":[D("transit","Discussing a local news story","office",["Maya","Leo"],[T("Maya","Did you see the story about the new bus route?","خبر مسیر اتوبوس جدید رو دیدی؟"),T("Leo","Only the headline. What's changing?","فقط تیتر رو. چی عوض می‌شه؟"),T("Maya","The city is adding a route through three neighborhoods that don't have direct service now.","شهر مسیری اضافه می‌کنه که از سه محله بدون سرویس مستقیم رد می‌شه."),T("Leo","That could make a big difference for commuters there.","برای رفت‌وآمدکننده‌های اونجا می‌تونه تفاوت بزرگی ایجاد کنه.")],1),D("incident","Separating facts from unknowns","cafe",["Hana","Noah"],[T("Hana","The article says two roads were closed after an incident downtown.","مقاله می‌گه دو خیابون بعد حادثه مرکز شهر بسته شدند."),T("Noah","Do they know what caused it?","می‌دونن علت چی بوده؟"),T("Hana","Not yet. Officials haven't confirmed the cause.","هنوز نه. مقام‌ها علت رو تأیید نکردند."),T("Noah","Then the comments online are probably mostly guesses.","پس کامنت‌های آنلاین احتمالاً بیشتر حدسه.")],2),D("summary","Relaying the main point","phone call",["Sofia","Omar"],[T("Omar","I missed the news. Anything important about the train line?","خبر رو ندیدم. درباره خط قطار چیز مهمی بود؟"),T("Sofia","Basically, weekend service is increasing next month.","خلاصه اینکه سرویس آخرهفته ماه بعد بیشتر می‌شه."),T("Omar","Do they have the new schedule yet?","برنامه جدید رو دارند؟"),T("Sofia","Not yet. They said it'll be published next week.","هنوز نه. گفتند هفته بعد منتشر می‌شه.")],3)],
"fill":["According ___ the report, the road will reopen tonight.",["to","with","for","from"],"to"]
},
{
"slug":"b1-digital-life","file":"b1-digital-life-v1.json","topic":"simple-messages","lessons":3,
"vocab":[V("privacy","privacy","حریم خصوصی"),V("permission","permission","مجوز"),V("backup","backup","نسخه پشتیبان"),V("sync","sync","همگام‌سازی کردن","verb"),V("update","update","به‌روزرسانی"),V("account","account","حساب"),V("notification","notification","اعلان"),V("secure","secure","امن","adjective"),V("troubleshoot","troubleshoot","عیب‌یابی کردن","verb"),V("storage","storage","فضای ذخیره‌سازی")],
"utterances":[U("permissions","I check app permissions because some apps ask for access they don't really need.","مجوزهای اپ رو چک می‌کنم چون بعضی اپ‌ها دسترسی‌هایی می‌خوان که واقعاً لازم ندارند.","discuss_privacy",["privacy","permission"],1),U("secure","Using a password manager is more secure than reusing the same password everywhere.","استفاده از مدیر رمز امن‌تر از استفاده از یک رمز در همه‌جاست.","discuss_security",["secure","account"],1),U("notifications","I turned off most notifications because they were constantly interrupting me.","بیشتر اعلان‌ها رو خاموش کردم چون مدام حواسم رو پرت می‌کردند.","describe_digital_habit",["notification"],1),U("sync","My photos aren't syncing between my phone and laptop.","عکس‌هام بین گوشی و لپ‌تاپ همگام نمی‌شن.","report_technical_issue",["sync"],2),U("backup","Before you reset the device, make sure everything important has been backed up.","قبل از ریست دستگاه مطمئن شو همه چیز مهم پشتیبان‌گیری شده.","give_technical_advice",["backup"],2),U("storage","If your storage is almost full, deleting old downloads may solve the problem.","اگر فضای ذخیره‌سازی تقریباً پره، حذف دانلودهای قدیمی شاید مشکل رو حل کنه.","troubleshoot_storage",["storage","troubleshoot"],2),U("update","The app was updated yesterday, and that's when the problem started.","اپ دیروز به‌روزرسانی شد و مشکل از همون موقع شروع شد.","link_update_problem",["update"],3),U("account","If I can't recover the account, I'll contact support and verify my identity.","اگر نتونم حساب رو برگردونم، با پشتیبانی تماس می‌گیرم و هویتم رو تأیید می‌کنم.","plan_account_recovery",["account","secure"],3)],
"grammar":[G("relative_digital","Relative clauses for digital tools","Use that/which to define apps, settings, or devices by what they do.","برای مشخص کردن اپ، تنظیم یا دستگاه با کارکردش از that/which استفاده می‌کنیم.",[("I use an app that blocks distractions.","از اپی استفاده می‌کنم که حواس‌پرتی رو می‌بنده."),("The setting which controls notifications is here.","تنظیمی که اعلان‌ها رو کنترل می‌کنه اینجاست.")],1),G("passive_digital","Passive for technical processes","Use passive forms when describing updates, backups, or automated processes.","برای توضیح آپدیت، پشتیبان‌گیری و فرایندهای خودکار از passive استفاده می‌کنیم.",[("The app was updated yesterday.","اپ دیروز به‌روزرسانی شد."),("Your data is backed up automatically.","داده‌هات خودکار پشتیبان‌گیری می‌شن.")],2),G("troubleshooting_if","Conditionals for troubleshooting","Use if + present with try/can/may/will to test possible causes and fixes.","برای تست علت و راه‌حل از if + present همراه try/can/may/will استفاده می‌کنیم.",[("If it still doesn't sync, restart the app.","اگر هنوز همگام نشد، اپ رو ری‌استارت کن."),("If storage is full, the update may fail.","اگر حافظه پر باشه، ممکنه آپدیت شکست بخوره.")],3)],
"dialogues":[D("privacy","Reviewing app permissions","home",["Lina","Ben"],[T("Lina","Why does this flashlight app want access to my contacts?","چرا این اپ چراغ‌قوه دسترسی به مخاطب‌هام می‌خواد؟"),T("Ben","It probably doesn't need that permission.","احتمالاً اون مجوز رو لازم نداره."),T("Lina","I'll turn it off and check the other permissions too.","خاموشش می‌کنم و بقیه مجوزها رو هم چک می‌کنم."),T("Ben","Good idea. I review mine every few months.","ایده خوبیه. من هر چند ماه بررسی می‌کنم.")],1),D("sync","Fixing a sync problem","office",["Amir","Ella"],[T("Amir","My notes stopped syncing after yesterday's update.","یادداشت‌هام بعد آپدیت دیروز همگام نمی‌شن."),T("Ella","Are you still signed into the same account on both devices?","روی هر دو دستگاه با یک حساب واردی؟"),T("Amir","Yes.","آره."),T("Ella","Then try turning sync off and back on before you reinstall anything.","پس قبل از نصب مجدد، همگام‌سازی رو خاموش و روشن کن.")],2),D("backup","Preparing to reset a phone","support chat",["Ravi","Mina"],[T("Ravi","Support says I may need to reset my phone.","پشتیبانی می‌گه شاید لازم باشه گوشیم رو ریست کنم."),T("Mina","Have you backed everything up?","از همه‌چی پشتیبان گرفتی؟"),T("Ravi","Photos are backed up, but I'm not sure about messages.","عکس‌ها پشتیبان دارند، ولی درباره پیام‌ها مطمئن نیستم."),T("Mina","Check that first. You don't want to lose them.","اول اون رو چک کن. نمی‌خوای از دستشون بدی.")],3)],
"fill":["Make sure your files have been ___ before you reset the device.",["backed up","back up","backing up","backup"],"backed up"]
},
{
"slug":"b1-relationships-social","file":"b1-relationships-social-v1.json","topic":"polite-language","lessons":3,
"vocab":[V("misunderstanding","misunderstanding","سوءتفاهم"),V("assume","assume","فرض کردن","verb"),V("apologize","apologize","عذرخواهی کردن","verb"),V("boundary","boundary","مرز شخصی"),V("supportive","supportive","حمایتگر","adjective"),V("reliable","reliable","قابل‌اعتماد","adjective"),V("upset","upset","ناراحت","adjective"),V("explain","explain","توضیح دادن","verb"),V("perspective","perspective","دیدگاه"),V("resolve","resolve","حل کردن","verb")],
"utterances":[U("misunderstanding","I think there was a misunderstanding about what time we were supposed to meet.","فکر می‌کنم درباره ساعتی که قرار بود همدیگه رو ببینیم سوءتفاهم شد.","identify_misunderstanding",["misunderstanding"],1),U("assume","I assumed you were busy because you didn't reply, but I should have asked.","فرض کردم سرت شلوغه چون جواب ندادی، ولی باید می‌پرسیدم.","acknowledge_assumption",["assume"],1),U("apology","I'm sorry I sounded annoyed. I was stressed about something else.","ببخشید عصبانی به نظر رسیدم. درباره چیز دیگه‌ای استرس داشتم.","apologize_explain",["apologize","upset"],1),U("reported","Maya said she felt left out because nobody told her the plan had changed.","مایا گفت حس کرده کنار گذاشته شده چون کسی نگفته بود برنامه عوض شده.","report_social_issue",["perspective"],2),U("boundary","It's okay to set a boundary without being rude or unfriendly.","می‌شه بدون بی‌ادبی یا سرد بودن مرز شخصی تعیین کرد.","discuss_boundary",["boundary"],2),U("supportive","A supportive friend listens before immediately giving advice.","دوست حمایتگر قبل از اینکه فوری توصیه کنه گوش می‌ده.","describe_supportive_behavior",["supportive"],2),U("suggest","If I were you, I'd explain how you felt instead of guessing what they meant.","اگر جای تو بودم توضیح می‌دادم چه حسی داشتی به‌جای اینکه حدس بزنی منظورشون چی بوده.","give_relationship_advice",["explain","perspective"],3),U("resolve","Once we talked about it directly, the misunderstanding was easy to resolve.","وقتی مستقیم درباره‌اش حرف زدیم، حل سوءتفاهم راحت بود.","describe_resolution",["resolve","misunderstanding"],3)],
"grammar":[G("reported_social","Reported speech for social situations","Use said/told me/explained that to report what someone communicated without repeating exact words.","برای انتقال حرف دیگران بدون نقل قول مستقیم از said، told me و explained that استفاده می‌کنیم.",[("She said she was upset.","گفت ناراحت بوده."),("He told me he needed more time.","گفت زمان بیشتری لازم داره.")],1),G("advice_social","should / could / if I were you","Use these forms to give tactful suggestions; could is often softer than should.","برای پیشنهاد مؤدبانه از should، could و if I were you استفاده می‌کنیم؛ could معمولاً نرم‌تره.",[("You could ask what happened.","می‌تونی بپرسی چی شده."),("If I were you, I'd talk to her directly.","اگر جای تو بودم مستقیم باهاش حرف می‌زدم.")],2),G("conditionals_social","Conditionals for social outcomes","Use first conditional to discuss likely results of possible social actions.","برای نتیجه محتمل رفتار اجتماعی از شرط نوع اول استفاده می‌کنیم.",[("If you explain calmly, they'll probably understand.","اگر آروم توضیح بدی، احتمالاً می‌فهمند."),("If we don't talk about it, the problem may continue.","اگر درباره‌اش حرف نزنیم، ممکنه مشکل ادامه پیدا کنه.")],3)],
"dialogues":[D("late","A misunderstanding about plans","cafe",["Maya","Leo"],[T("Maya","I thought we were meeting at seven, not six-thirty.","فکر می‌کردم قرارمون هفت بود نه شش‌ونیم."),T("Leo","I sent an update yesterday, but maybe you didn't see it.","دیروز آپدیت فرستادم، ولی شاید ندیدیش."),T("Maya","I didn't. Sorry—I thought you were annoyed with me.","ندیدم. ببخشید—فکر کردم ازم ناراحتی."),T("Leo","No, not at all. It was just a misunderstanding.","نه اصلاً. فقط سوءتفاهم بود.")],1),D("friend","Giving social advice","walk",["Hana","Noah"],[T("Hana","My friend has been distant, and I don't know why.","دوستم این اواخر فاصله گرفته و نمی‌دونم چرا."),T("Noah","Have you asked if something's wrong?","پرسیدی مشکلی هست؟"),T("Hana","No. I assumed she wanted space.","نه. فرض کردم فضا می‌خواد."),T("Noah","You could check in without pressuring her.","می‌تونی بدون فشار آوردن حالش رو بپرسی.")],2),D("boundary","Setting a boundary","phone call",["Sofia","Omar"],[T("Sofia","I need to stop answering work messages late at night.","باید جواب دادن به پیام کاری آخر شب رو متوقف کنم."),T("Omar","Then set a clear boundary with your team.","پس با تیمت مرز واضح بذار."),T("Sofia","I'm worried they'll think I'm unhelpful.","نگرانم فکر کنند همکاری نمی‌کنم."),T("Omar","You can be supportive without being available twenty-four hours a day.","می‌تونی حمایتگر باشی بدون اینکه بیست‌وچهارساعته در دسترس باشی.")],3)],
"fill":["I assumed you were busy, but I should have ___.",["asked","ask","asking","to asking"],"asked"]
}
]

def main():
    OUT.mkdir(parents=True,exist_ok=True); w=[]
    for s in UNITS:
        p=OUT/s["file"]; p.write_text(json.dumps(build(s),ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); w.append(p.name)
    print(json.dumps({"written":len(w),"files":w},ensure_ascii=False,indent=2))
if __name__=="__main__": main()
