#!/usr/bin/env python3
from scripts.generate_c2_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=11, slug="c2-persuasive-framing", topic="requests", title="Persuasive Framing & Audience Design",
    vocab=[V("framing","framing","قاب‌بندی"),V("salience","salience","برجستگی"),V("audience","audience","مخاطب"),V("appeal","appeal","جذابیت استدلالی / توسل"),V("credibility","credibility","اعتبار"),V("relevance","relevance","ارتباط"),V("emphasis","emphasis","تأکید"),V("recast","recast","بازقالب‌بندی کردن","verb")],
    utterances=[
        U("frame","The facts have not changed; what changes is the framing, which determines which costs and benefits become most salient.","واقعیت‌ها عوض نشدن؛ چیزی که عوض می‌شه قاب‌بندیه و همون تعیین می‌کنه کدوم هزینه‌ها و مزایا برجسته‌تر دیده بشن.","analyze_framing",["framing","salience"],1),
        U("audience","For this audience, an appeal to operational reliability will carry more weight than a purely abstract argument about efficiency.","برای این مخاطب، تکیه روی قابل‌اعتماد بودن اجرا وزن بیشتری از یک استدلال کاملاً انتزاعی درباره کارایی داره.","adapt_to_audience",["audience","appeal"],1),
        U("credibility","If we acknowledge the main drawback ourselves, we gain credibility and make the recommendation harder to dismiss as advocacy.","اگر خودمون ایراد اصلی رو بپذیریم، اعتبار بیشتری می‌گیریم و توصیه سخت‌تر به‌عنوان جانبداری کنار گذاشته می‌شه.","build_credibility",["credibility","relevance"],2),
        U("recast","I would recast the proposal as a risk-management measure rather than a modernization project, because that better matches their priorities.","پیشنهاد رو بیشتر به‌عنوان اقدام مدیریت ریسک بازتعریف می‌کنم تا پروژه نوسازی، چون با اولویت‌های اون‌ها بهتر جور درمیاد.","recast_message",["recast","framing"],2),
        U("emphasis","Emphasis should follow audience need, not speaker preference; otherwise a technically strong case may still miss the decision criterion.","تأکید باید از نیاز مخاطب بیاد نه سلیقه گوینده؛ وگرنه یک استدلال فنی قوی هم ممکنه معیار اصلی تصمیم رو از دست بده.","align_emphasis",["emphasis","audience"],3),
        U("relevance","The statistic is impressive but not especially relevant to the decision, so I would move it out of the opening.","عدد چشمگیره ولی برای تصمیم خیلی مرتبط نیست، پس از شروع ارائه حذفش می‌کنم.","prioritize_relevance",["relevance","salience"],3),
        U("appeal","An emotional appeal can support a case, but it should not be used to obscure uncertainty in the evidence.","توسل احساسی می‌تونه استدلال رو پشتیبانی کنه، ولی نباید برای پنهان کردن عدم قطعیت شواهد استفاده بشه.","limit_appeal",["appeal","credibility"],3),
        U("summary","Persuasion at this level means preserving factual integrity while designing emphasis, sequence and framing for a specific listener.","اقناع در این سطح یعنی صداقت factual رو حفظ کنی و در عین حال تأکید، ترتیب و قاب‌بندی رو برای مخاطب مشخص طراحی کنی.","summarize_persuasion",["framing","emphasis","audience"],3),
    ], grammar=["discourse_management","stance_markers","cleft_sentences"], fill=["The proposal was ___ as a risk-management measure.",["recast","inferred","mitigated","foreshadowed"],"recast"]),

make_spec(index=12, slug="c2-high-stakes-negotiation", topic="requests", title="High-Stakes Negotiation & Package Building",
    vocab=[V("leverage","leverage","اهرم مذاکره"),V("concession","concession","امتیاز"),V("tradeoff","trade-off","مصالحه بین دو مزیت"),V("nonnegotiable","non-negotiable","غیرقابل مذاکره","adjective"),V("package","package","بسته پیشنهادی"),V("contingent","contingent","مشروط","adjective"),V("fallback","fallback","گزینه پشتیبان"),V("reciprocity","reciprocity","عمل متقابل")],
    utterances=[
        U("interests","Before discussing numbers, I want to separate genuine non-negotiables from positions we are using mainly for leverage.","قبل از عددها می‌خوام چیزهای واقعاً غیرقابل مذاکره رو از مواضعی که بیشتر برای اهرم استفاده می‌کنیم جدا کنم.","surface_interests",["nonnegotiable","leverage"],1),
        U("package","A package works better than item-by-item bargaining because each side can trade across priorities with different values.","بسته پیشنهادی بهتر از چانه‌زنی موردبه‌مورد جواب می‌ده چون هر طرف می‌تونه بین اولویت‌هایی با ارزش متفاوت معامله کنه.","build_package",["package","tradeoff"],1),
        U("concession","I can make that concession if it is paired with a longer notice period; on its own, it shifts too much risk to us.","اون امتیاز رو می‌دم اگر با مهلت اطلاع‌رسانی طولانی‌تر همراه باشه؛ به‌تنهایی ریسک زیادی رو به ما منتقل می‌کنه.","make_conditional_concession",["concession","contingent"],2),
        U("reciprocity","Reciprocity does not require identical concessions; it requires both sides to perceive meaningful movement.","عمل متقابل به معنی امتیازهای یکسان نیست؛ یعنی هر دو طرف حرکت واقعی از سمت مقابل ببینن.","explain_reciprocity",["reciprocity","concession"],2),
        U("fallback","Our fallback is acceptable but expensive, which means we have room to negotiate without pretending we have no alternative.","گزینه پشتیبان قابل قبوله ولی گرونه، پس جا برای مذاکره داریم بدون اینکه وانمود کنیم هیچ جایگزینی نداریم.","assess_fallback",["fallback","leverage"],3),
        U("tradeoff","The core trade-off is not price versus quality; it is certainty now versus flexibility later.","مصالحه اصلی قیمت در برابر کیفیت نیست؛ قطعیت الان در برابر انعطاف بعدیه.","reframe_tradeoff",["tradeoff","package"],3),
        U("pause","I would pause rather than fill the silence; the other side may clarify which term actually matters most to them.","به‌جای پر کردن سکوت مکث می‌کنم؛ شاید طرف مقابل خودش روشن کنه کدوم شرط واقعاً براش مهم‌تره.","use_negotiation_silence",["leverage","nonnegotiable"],3),
        U("close","A durable agreement should make the exchange explicit enough that neither side later remembers the concessions differently.","توافق پایدار باید مبادله امتیازها رو اون‌قدر روشن ثبت کنه که بعداً دو طرف روایت متفاوتی ازش نداشته باشن.","close_agreement",["reciprocity","package"],3),
    ], grammar=["diplomatic_language","mixed_conditionals","concession_rebuttal"], fill=["The concession is ___ on receiving a longer notice period.",["contingent","categorical","equivocal","literal"],"contingent"]),

make_spec(index=13, slug="c2-facilitating-complex-discussion", topic="jobs", title="Facilitating Complex Discussion & Consensus Testing",
    vocab=[V("facilitate","facilitate","تسهیل کردن","verb"),V("consensus","consensus","اجماع"),V("synthesize","synthesize","جمع‌بندی ترکیبی کردن","verb"),V("intervention","intervention","دخالت هدفمند"),V("dominance","dominance","غلبه در گفتگو"),V("agenda","agenda","دستور جلسه"),V("convergence","convergence","نزدیک شدن دیدگاه‌ها"),V("dissent","dissent","مخالفت")],
    utterances=[
        U("agenda","We are drifting beyond the agenda, so I want to capture that issue separately and bring us back to the decision we need today.","داریم از دستور جلسه دور می‌شیم؛ اون موضوع رو جدا ثبت می‌کنم و برمی‌گردیم به تصمیمی که امروز لازم داریم.","manage_agenda",["agenda","facilitate"],1),
        U("voices","Before we test consensus, I want to hear from people who have not spoken yet; otherwise silence may be mistaken for agreement.","قبل از سنجش اجماع می‌خوام از کسانی که هنوز حرف نزدن بشنویم؛ وگرنه سکوت ممکنه اشتباهی به‌عنوان موافقت برداشت بشه.","balance_participation",["consensus","dominance"],1),
        U("synthesize","Let me synthesize the discussion: we have convergence on the objective, but two unresolved disagreements about timing and ownership.","بذار بحث رو ترکیبی جمع‌بندی کنم: روی هدف نزدیک شدیم، ولی دو اختلاف حل‌نشده درباره زمان‌بندی و مسئولیت داریم.","synthesize_discussion",["synthesize","convergence"],2),
        U("intervention","I am going to intervene here because the same two positions are repeating without answering each other's central concern.","اینجا دخالت می‌کنم چون دو موضع دارن تکرار می‌شن بدون اینکه به نگرانی اصلی همدیگه جواب بدن.","intervene_productively",["intervention","dissent"],2),
        U("dissent","I want the dissent recorded clearly; consensus does not require us to erase a material objection.","می‌خوام مخالفت واضح ثبت بشه؛ اجماع لازم نیست یک ایراد مهم رو پاک کنه.","preserve_dissent",["dissent","consensus"],3),
        U("dominance","The problem is not that one person speaks often; it is that conversational dominance is narrowing which options receive serious examination.","مشکل فقط زیاد حرف زدن یک نفر نیست؛ غلبه در گفتگو داره گزینه‌هایی رو که جدی بررسی می‌شن محدود می‌کنه.","address_dominance",["dominance","facilitate"],3),
        U("test","Can everyone live with this version, including those who would not choose it as their first option?", "همه می‌تونن با این نسخه کنار بیان، حتی کسانی که انتخاب اولشون نیست؟","test_working_consensus",["consensus","convergence"],3),
        U("close","We have a decision, one explicit reservation and two owners; I will close by restating all three so nothing gets lost.","یک تصمیم داریم، یک ملاحظه صریح و دو مسئول؛ در پایان هر سه رو دوباره می‌گم که چیزی گم نشه.","close_facilitated_discussion",["dissent","agenda"],3),
    ], grammar=["discourse_management","reformulation","diplomatic_language"], fill=["The facilitator paused to test whether the group had reached ___.",["consensus","dominance","digression","ambiguity"],"consensus"]),

make_spec(index=14, slug="c2-spontaneous-interaction", topic="jobs", title="Spontaneous Interaction & Real-Time Repair",
    vocab=[V("spontaneous","spontaneous","بداهه و بدون آماده‌سازی","adjective"),V("repair","repair","اصلاح در لحظه"),V("overlap","overlap","هم‌زمانی صحبت"),V("floor","floor","نوبت صحبت"),V("self_correct","self-correct","خوداصلاحی کردن","verb"),V("retrieve","retrieve","به یاد آوردن واژه","verb"),V("paraphrase","paraphrase","با عبارت دیگر گفتن","verb"),V("fluency","fluency","روانی")],
    utterances=[
        U("repair","I said 'inevitable'—that's too strong. Let me repair that: difficult to avoid under the current constraints.","گفتم inevitable؛ زیادی قویه. اصلاحش می‌کنم: با محدودیت‌های فعلی سخت می‌شه ازش اجتناب کرد.","repair_claim_live",["repair","self_correct"],1),
        U("overlap","Sorry, we overlapped. Finish your point and I will come back to the distinction I was trying to make.","ببخشید هم‌زمان شدیم. تو نکته‌ت رو کامل کن، بعد برمی‌گردم به تمایزی که می‌خواستم بگم.","manage_overlap",["overlap","floor"],1),
        U("retrieve","I cannot retrieve the exact term, but I mean a system where responsibility is distributed rather than centralized.","اصطلاح دقیق یادم نمیاد، ولی منظورم سیستمیه که مسئولیت در اون توزیع شده نه متمرکز.","circumlocute_word_gap",["retrieve","paraphrase"],2),
        U("paraphrase","Let me paraphrase your point to check I have understood it before I answer.","بذار حرفت رو با عبارت دیگه بگم تا قبل از جواب مطمئن شم درست فهمیدم.","check_understanding_live",["paraphrase","repair"],2),
        U("floor","I will give the floor back in a second; I just want to clarify one premise that affects the rest of the argument.","یک لحظه دیگه نوبت رو برمی‌گردونم؛ فقط می‌خوام یک پیش‌فرض رو روشن کنم که روی بقیه استدلال اثر داره.","hold_floor_briefly",["floor","fluency"],3),
        U("fluency","Fluency here is not speed; it is the ability to keep meaning moving even when wording needs to be repaired.","روانی اینجا سرعت نیست؛ توانایی ادامه دادن معناست حتی وقتی عبارت نیاز به اصلاح داره.","define_advanced_fluency",["fluency","repair"],3),
        U("self","Actually, I will self-correct that example because it implies the opposite of what I intended.","در واقع اون مثال رو خودم اصلاح می‌کنم چون خلاف چیزی که منظورم بود رو القا می‌کنه.","self_correct_example",["self_correct","repair"],3),
        U("summary","Advanced spontaneous interaction depends on recovery: entering, yielding, repairing and paraphrasing without losing the relationship or the argument.","تعامل بداهه پیشرفته به توان بازیابی وابسته‌ست: وارد شدن، نوبت دادن، اصلاح کردن و بازگویی بدون اینکه رابطه یا استدلال از دست بره.","summarize_spontaneous_control",["spontaneous","paraphrase","floor"],3),
    ], grammar=["ellipsis_substitution","reformulation","discourse_management"], fill=["When the exact word did not come, she chose to ___.",["paraphrase","disavow","undercut","triangulate"],"paraphrase"]),

make_spec(index=15, slug="c2-conflict-repair", topic="polite-language", title="Conflict Repair, Accountability & Boundary Work",
    vocab=[V("accountability","accountability","پاسخ‌گویی"),V("rupture","rupture","گسست در رابطه"),V("repair","repair","ترمیم"),V("boundary","boundary","مرز"),V("acknowledge","acknowledge","پذیرفتن و به رسمیت شناختن","verb"),V("defensive","defensive","دفاعی","adjective"),V("impact","impact","اثر"),V("restitution","restitution","جبران")],
    utterances=[
        U("impact","I believe the comment was meant lightly, but the impact was different, and that is the part we need to address.","فکر می‌کنم حرف با نیت سبک گفته شد، ولی اثرش متفاوت بود و همون بخشی‌ه که باید بهش رسیدگی کنیم.","separate_intent_impact",["impact","repair"],1),
        U("ack","I can acknowledge that my wording put you in a difficult position without pretending I intended the outcome.","می‌تونم بپذیرم که عبارت‌بندیم تو رو در موقعیت سختی گذاشت، بدون اینکه وانمود کنم قصد اون نتیجه رو داشتم.","acknowledge_harm",["acknowledge","accountability"],1),
        U("boundary","The boundary is not 'never disagree with me'; it is 'do not raise personal criticism in front of the wider team.'", "مرز این نیست که «هیچ‌وقت با من مخالفت نکن»؛ اینه که «انتقاد شخصی رو جلوی کل تیم مطرح نکن».","state_boundary_precisely",["boundary","impact"],2),
        U("defensive","If I become defensive, the conversation shifts from what happened to protecting my self-image, which makes repair harder.","اگر دفاعی بشم، گفتگو از اتفاقی که افتاده می‌ره سمت دفاع از تصویر خودم و ترمیم سخت‌تر می‌شه.","avoid_defensiveness",["defensive","repair"],2),
        U("rupture","The rupture is small enough to repair, but only if we treat the loss of trust as real rather than trivial.","گسست اون‌قدر کوچیکه که بشه ترمیمش کرد، ولی فقط اگر کاهش اعتماد رو واقعی بدونیم نه بی‌اهمیت.","assess_rupture",["rupture","repair"],3),
        U("restitution","An apology helps, but restitution may require changing the process that allowed the same problem to happen twice.","عذرخواهی کمک می‌کنه، ولی جبران ممکنه نیاز داشته باشه روندی که دوبار اجازه تکرار مشکل داده عوض بشه.","design_restitution",["restitution","accountability"],3),
        U("future","I am willing to continue, provided the boundary is explicit and we both know what happens if it is crossed again.","حاضرم ادامه بدیم به شرطی که مرز روشن باشه و هر دو بدونیم اگر دوباره رد شد چه اتفاقی می‌افته.","negotiate_future_boundary",["boundary","accountability"],3),
        U("summary","Repair becomes credible when acknowledgment, impact, responsibility and a concrete change all line up.","ترمیم وقتی قابل‌باور می‌شه که پذیرش، اثر، مسئولیت و تغییر عملی با هم جور باشن.","summarize_repair",["repair","acknowledge","restitution"],3),
    ], grammar=["diplomatic_language","concession_rebuttal","stance_markers"], fill=["A credible apology requires more than words; it may also require ___.",["restitution","dominance","ambiguity","salience"],"restitution"]),

make_spec(index=16, slug="c2-expert-feedback", topic="jobs", title="Expert Feedback, Calibration & Coaching",
    vocab=[V("calibrate","calibrate","دقیق تنظیم کردن","verb"),V("actionable","actionable","قابل اقدام","adjective"),V("diagnostic","diagnostic","تشخیصی","adjective"),V("criterion","criterion","معیار"),V("iterate","iterate","چندبار اصلاح و تکرار کردن","verb"),V("specificity","specificity","مشخص بودن"),V("tradeoff","trade-off","مصالحه"),V("ownership","ownership","مسئولیت‌پذیری")],
    utterances=[
        U("criterion","My feedback is tied to one criterion: can a reader identify the recommendation before reaching the second paragraph?", "بازخورد من به یک معیار مشخص وصله: آیا خواننده قبل از رسیدن به پاراگراف دوم توصیه اصلی رو پیدا می‌کنه؟","anchor_feedback",["criterion","diagnostic"],1),
        U("diagnostic","The problem is diagnostic rather than cosmetic: the structure reflects uncertainty about the argument, not merely weak wording.","مشکل تشخیصیه نه ظاهری: ساختار نشون می‌ده خود استدلال هنوز روشن نیست، نه اینکه فقط عبارت‌بندی ضعیفه.","diagnose_root_problem",["diagnostic","specificity"],1),
        U("actionable","Instead of saying 'make it clearer,' I would make the feedback actionable: state the decision, then give two reasons in descending importance.","به‌جای اینکه بگم «واضح‌ترش کن»، بازخورد رو عملی می‌کنم: اول تصمیم رو بگو، بعد دو دلیل رو به ترتیب اهمیت بیار.","make_feedback_actionable",["actionable","specificity"],2),
        U("calibrate","I would calibrate the tone differently for a first draft and a final submission; the same flaw warrants different levels of urgency.","برای پیش‌نویس اول و نسخه نهایی لحن بازخورد رو متفاوت تنظیم می‌کنم؛ یک ایراد مشابه در این دو مرحله فوریت یکسانی نداره.","calibrate_feedback",["calibrate","criterion"],2),
        U("tradeoff","There is a trade-off between completeness and readability here, so I would cut one example rather than add another explanation.","اینجا بین کامل بودن و خوانایی مصالحه وجود داره، پس یک مثال رو حذف می‌کنم به‌جای اینکه توضیح دیگه اضافه کنم.","coach_tradeoff",["tradeoff","actionable"],3),
        U("iterate","Let us iterate once on the opening only; if the structure works there, you can apply the pattern to the rest yourself.","فقط یک بار روی شروع متن تکرار و اصلاح کنیم؛ اگر ساختار اونجا جواب بده خودت می‌تونی الگو رو به بقیه تعمیم بدی.","coach_iteration",["iterate","ownership"],3),
        U("ownership","I do not want to rewrite it for you, because preserving your ownership matters more than making this one version perfect.","نمی‌خوام خودم برات بازنویسی کنم چون حفظ مسئولیت و صدای خودت مهم‌تر از بی‌نقص شدن همین یک نسخه‌ست.","preserve_ownership",["ownership","iterate"],3),
        U("summary","Expert feedback identifies the underlying issue, anchors it to a criterion and leaves the receiver with a concrete next move.","بازخورد حرفه‌ای مشکل زیرساختی رو پیدا می‌کنه، به یک معیار وصلش می‌کنه و یک حرکت بعدی مشخص به مخاطب می‌ده.","summarize_expert_feedback",["diagnostic","criterion","actionable"],3),
    ], grammar=["cleft_sentences","reformulation","discourse_management"], fill=["Good feedback should be specific and ___.",["actionable","equivocal","circular","indeterminate"],"actionable"]),

make_spec(index=17, slug="c2-strategy-scenarios", topic="jobs", title="Strategy, Scenarios & Second-Order Effects",
    vocab=[V("scenario","scenario","سناریو"),V("second_order","second-order","مرتبه دوم / غیرمستقیم","adjective"),V("incentive","incentive","مشوق"),V("constraint","constraint","محدودیت"),V("optionality","optionality","حفظ گزینه‌های آینده"),V("path_dependency","path dependency","وابستگی به مسیر","noun_phrase"),V("assumption","assumption","فرض"),V("robust","robust","مقاوم و قابل اتکا","adjective")],
    utterances=[
        U("scenario","We do not need a single forecast; we need three plausible scenarios that stress different assumptions.","به یک پیش‌بینی واحد نیاز نداریم؛ سه سناریوی منطقی می‌خوایم که فرض‌های متفاوت رو تحت فشار بذارن.","build_scenarios",["scenario","assumption"],1),
        U("second","The first-order effect is lower cost; the second-order effect may be weaker service because the incentive to invest changes.","اثر مستقیم هزینه کمتره؛ اثر مرتبه دوم ممکنه خدمات ضعیف‌تر باشه چون مشوق سرمایه‌گذاری عوض می‌شه.","identify_second_order_effect",["second_order","incentive"],1),
        U("optionality","This option is slightly less efficient now but preserves optionality if demand moves in either direction.","این گزینه الان کمی کم‌کاراتره، ولی اگر تقاضا به هر سمتی حرکت کنه گزینه‌های آینده رو حفظ می‌کنه.","value_optionality",["optionality","scenario"],2),
        U("path","Once we reorganize around this platform, path dependency makes reversing the choice progressively more expensive.","وقتی ساختار رو حول این پلتفرم بچینیم، وابستگی به مسیر باعث می‌شه برگشتن از تصمیم به‌مرور گرون‌تر بشه.","explain_path_dependency",["path_dependency","constraint"],2),
        U("constraint","The strategy should be designed around the binding constraint, not the most visible inconvenience.","استراتژی باید حول محدودیتی طراحی بشه که واقعاً گلوگاهه، نه مشکلی که فقط بیشتر به چشم میاد.","identify_binding_constraint",["constraint","robust"],3),
        U("robust","A robust choice is not the one that wins in the optimistic scenario; it performs acceptably across several credible futures.","گزینه مقاوم اون نیست که فقط در سناریوی خوش‌بینانه بهترین باشه؛ در چند آینده قابل‌باور عملکرد قابل‌قبولی داره.","define_robust_strategy",["robust","scenario"],3),
        U("assumption","I would make that assumption explicit because the recommendation changes completely if it fails.","اون فرض رو صریح می‌کنم چون اگر درست از آب درنیاد، توصیه کاملاً عوض می‌شه.","surface_critical_assumption",["assumption","scenario"],3),
        U("summary","Strategic judgment means choosing with uncertainty while preserving room to adapt when the world does not follow the base case.","قضاوت استراتژیک یعنی در عدم قطعیت انتخاب کنی و وقتی دنیا طبق سناریوی پایه جلو نرفت، فضای سازگار شدن رو حفظ کنی.","summarize_strategy",["optionality","robust","scenario"],3),
    ], grammar=["mixed_conditionals","advanced_hedging","nominalisation"], fill=["The less efficient option preserves valuable ___ for the future.",["optionality","dominance","denotation","restitution"],"optionality"]),

make_spec(index=18, slug="c2-crisis-response", topic="jobs", title="Crisis Response, Uncertainty & Decision Thresholds",
    vocab=[V("threshold","threshold","آستانه تصمیم"),V("containment","containment","مهار"),V("escalate","escalate","تشدید / ارجاع بالاتر دادن","verb"),V("triage","triage","اولویت‌بندی فوری"),V("uncertainty","uncertainty","عدم قطعیت"),V("irreversible","irreversible","برگشت‌ناپذیر","adjective"),V("contingency","contingency","برنامه احتمالی"),V("signal","signal","نشانه")],
    utterances=[
        U("triage","The first task is triage: separate what is dangerous now from what is merely incomplete or inconvenient.","کار اول اولویت‌بندی فوریه: چیزی که الان خطرناکه رو از چیزی که فقط ناقص یا دردسرسازه جدا کنیم.","triage_crisis",["triage","containment"],1),
        U("threshold","We need a decision threshold in advance; otherwise every new signal will restart the debate from zero.","از قبل آستانه تصمیم می‌خوایم؛ وگرنه هر نشانه جدید بحث رو از صفر شروع می‌کنه.","set_decision_threshold",["threshold","signal"],1),
        U("contain","Containment comes before diagnosis when delay itself could make the harm materially worse.","وقتی تأخیر خودش می‌تونه آسیب رو جدی‌تر کنه، مهار قبل از تشخیص کامل میاد.","prioritize_containment",["containment","uncertainty"],2),
        U("escalate","I would escalate now, not because failure is certain, but because the downside of waiting crosses our agreed threshold.","الان ارجاع بالاتر می‌دم، نه چون شکست قطعیه، بلکه چون هزینه صبر کردن از آستانه توافق‌شده رد شده.","escalate_under_uncertainty",["escalate","threshold"],2),
        U("irreversible","When an action is hard to reverse, the evidential threshold should usually be higher than for a temporary precaution.","وقتی اقدام سخت برگشت‌پذیره، معمولاً آستانه شواهد باید بالاتر از یک احتیاط موقت باشه.","calibrate_irreversibility",["irreversible","threshold"],3),
        U("contingency","Our contingency plan assumes the primary channel is unavailable for forty-eight hours, not indefinitely.","برنامه احتمالی ما فرض می‌کنه کانال اصلی چهل‌وهشت ساعت در دسترس نیست، نه برای همیشه.","scope_contingency",["contingency","uncertainty"],3),
        U("signal","One weak signal should not trigger panic, but several independent weak signals can collectively justify action.","یک نشانه ضعیف نباید وحشت ایجاد کنه، ولی چند نشانه ضعیف مستقل کنار هم می‌تونن اقدام رو توجیه کنن.","aggregate_signals",["signal","uncertainty"],3),
        U("summary","Good crisis language distinguishes what is known, what is suspected, what triggers action and what remains reversible.","زبان خوب در بحران مشخص می‌کنه چی معلومه، چی مشکوکه، چه چیزی اقدام رو فعال می‌کنه و چه چیزهایی هنوز برگشت‌پذیرن.","summarize_crisis_control",["threshold","uncertainty","irreversible"],3),
    ], grammar=["advanced_hedging","reporting_passive","discourse_management"], fill=["The team agreed on a clear decision ___ before the crisis intensified.",["threshold","collocation","rapport","denotation"],"threshold"]),

make_spec(index=19, slug="c2-executive-networking", topic="jobs", title="Executive Networking, Positioning & Reciprocity",
    vocab=[V("positioning","positioning","جایگاه‌سازی حرفه‌ای"),V("reciprocity","reciprocity","تعامل دوطرفه"),V("rapport","rapport","رابطه"),V("credibility","credibility","اعتبار"),V("referral","referral","معرفی"),V("mutual","mutual","دوطرفه","adjective"),V("contextualize","contextualize","در زمینه قرار دادن","verb"),V("transactional","transactional","صرفاً معامله‌ای","adjective")],
    utterances=[
        U("rapport","I would start with genuine rapport rather than the request; otherwise the interaction becomes transactional immediately.","با ارتباط واقعی شروع می‌کنم نه با درخواست؛ وگرنه تعامل از همون اول کاملاً معامله‌ای می‌شه.","build_network_rapport",["rapport","transactional"],1),
        U("position","Effective positioning is not self-promotion alone; it is making your relevance legible without overstating it.","جایگاه‌سازی مؤثر فقط خودتبلیغی نیست؛ یعنی ارتباط و ارزش خودت رو روشن کنی بدون اغراق.","position_professionally",["positioning","credibility"],1),
        U("context","Let me contextualize the introduction: you are both working on the same problem from different sides, so the connection may be useful to each of you.","بذار معرفی رو زمینه‌دار کنم: هر دوتون روی یک مسئله از دو سمت مختلف کار می‌کنید، پس این ارتباط ممکنه برای هر دو مفید باشه.","make_relevant_introduction",["contextualize","mutual"],2),
        U("reciprocity","Reciprocity accumulates over time; one useful introduction can matter more than repeatedly asking for small favors.","تعامل دوطرفه در طول زمان ساخته می‌شه؛ یک معرفی مفید می‌تونه از چندین درخواست کوچک ارزشمندتر باشه.","build_reciprocity",["reciprocity","referral"],2),
        U("referral","A referral carries borrowed credibility, so I would never ask someone to make one before they understand the fit.","معرفی بخشی از اعتبار معرف رو منتقل می‌کنه، پس قبل از اینکه طرف تناسب رو بفهمه ازش چنین درخواستی نمی‌کنم.","handle_referral_ethically",["referral","credibility"],3),
        U("mutual","The strongest relationships are mutual without being mechanically balanced; value can move in different forms at different times.","قوی‌ترین رابطه‌ها دوطرفه‌ان بدون اینکه مکانیکی و حسابداری‌شده باشن؛ ارزش می‌تونه در زمان‌های مختلف شکل‌های متفاوتی داشته باشه.","explain_mutuality",["mutual","reciprocity"],3),
        U("follow","I would follow up with one specific reference to the conversation rather than a generic 'great to connect' message.","برای پیگیری به یک نکته مشخص از گفتگو اشاره می‌کنم نه یک پیام کلی مثل great to connect.","follow_up_meaningfully",["rapport","contextualize"],3),
        U("summary","Sophisticated networking makes relevance, reciprocity and boundaries visible while keeping the relationship human rather than purely instrumental.","شبکه‌سازی پخته ارتباط، تعامل دوطرفه و مرزها رو روشن می‌کنه و رابطه رو انسانی نگه می‌داره نه صرفاً ابزاری.","summarize_networking",["reciprocity","transactional","positioning"],3),
    ], grammar=["register_shift","diplomatic_language","stance_markers"], fill=["The introduction should feel mutually useful rather than purely ___.",["transactional","provisional","equivocal","circular"],"transactional"]),

make_spec(index=20, slug="c2-leadership-judgment", topic="jobs", title="Leadership Judgment, Ownership & Ambiguous Outcomes",
    vocab=[V("judgment","judgment","قضاوت"),V("ownership","ownership","مسئولیت‌پذیری"),V("delegate","delegate","تفویض کردن","verb"),V("accountability","accountability","پاسخ‌گویی"),V("ambiguity","ambiguity","ابهام"),V("constraint","constraint","محدودیت"),V("tradeoff","trade-off","مصالحه"),V("retrospective","retrospective","بازنگرانه","adjective")],
    utterances=[
        U("judgment","The decision was not obviously right; good judgment meant choosing under ambiguity and being explicit about what could change the choice.","تصمیم به‌وضوح درست نبود؛ قضاوت خوب یعنی وسط ابهام انتخاب کنی و روشن بگی چه چیزی می‌تونه انتخاب رو عوض کنه.","explain_leadership_judgment",["judgment","ambiguity"],1),
        U("ownership","I take ownership of the decision, but that does not mean pretending the constraints or advice from others were irrelevant.","مسئولیت تصمیم رو می‌پذیرم، ولی این یعنی محدودیت‌ها یا نظر دیگران رو بی‌اهمیت جلوه بدم نیست.","take_ownership",["ownership","constraint"],1),
        U("delegate","I delegated the analysis, not the accountability; the final call was still mine to make.","تحلیل رو تفویض کردم، نه پاسخ‌گویی رو؛ تصمیم نهایی هنوز مسئولیت من بود.","distinguish_delegation_accountability",["delegate","accountability"],2),
        U("tradeoff","The trade-off was between short-term certainty and long-term capability, and either choice carried a real cost.","مصالحه بین قطعیت کوتاه‌مدت و توانمندی بلندمدت بود و هر انتخاب هزینه واقعی داشت.","explain_tradeoff",["tradeoff","judgment"],2),
        U("retrospective","Retrospective clarity can be misleading; information that looks obvious now was not equally available at the time.","وضوحی که بعداً پیدا می‌کنیم می‌تونه گمراه‌کننده باشه؛ اطلاعاتی که الان واضح به نظر میاد اون موقع به همون اندازه در دسترس نبود.","avoid_hindsight_bias",["retrospective","ambiguity"],3),
        U("failure","If I faced the same evidence again, I would change the communication, not necessarily the decision itself.","اگر دوباره با همون شواهد روبه‌رو می‌شدم، ارتباط رو عوض می‌کردم نه لزوماً خود تصمیم رو.","reflect_with_precision",["judgment","ownership"],3),
        U("account","Accountability is stronger when a leader can explain both the reasoning and the limits of that reasoning without becoming defensive.","پاسخ‌گویی وقتی قوی‌تره که رهبر هم منطق تصمیم و هم محدودیت‌های اون منطق رو بدون حالت دفاعی توضیح بده.","demonstrate_accountability",["accountability","judgment"],3),
        U("summary","Leadership judgment is visible in how decisions are framed, delegated, revised and owned when outcomes remain partly uncertain.","قضاوت رهبری در نحوه قاب‌بندی، تفویض، بازنگری و پذیرفتن مسئولیت تصمیم‌ها دیده می‌شه وقتی نتیجه‌ها هنوز تا حدی نامطمئنن.","summarize_leadership",["delegate","ownership","ambiguity"],3),
    ], grammar=["counterfactual_past","advanced_hedging","nominalisation"], fill=["A leader may delegate analysis without delegating ___.",["accountability","ambiguity","salience","collocation"],"accountability"]),
]

if __name__ == "__main__":
    write_units(UNITS)
