#!/usr/bin/env python3
from __future__ import annotations
import json
from scripts.generate_b1_batch import V,U,G,D,T,build,OUT

UNITS=[
{
"slug":"b1-rules-obligations","file":"b1-rules-obligations-v1.json","topic":"jobs","lessons":3,
"vocab":[V("required","required","الزامی","adjective"),V("optional","optional","اختیاری","adjective"),V("permission","permission","اجازه"),V("prohibited","prohibited","ممنوع","adjective"),V("policy","policy","سیاست / آیین‌نامه"),V("exception","exception","استثنا"),V("badge","badge","کارت شناسایی"),V("protective","protective","محافظتی","adjective"),V("allowed","allowed","مجاز","adjective"),V("obligation","obligation","الزام")],
"utterances":[U("badge","All visitors are required to wear a badge while they're in the building.","همه بازدیدکننده‌ها باید وقتی داخل ساختمان هستند کارت شناسایی داشته باشند.","explain_requirement",["required","badge"],1),U("must","Employees must report safety problems immediately.","کارمندها باید مشکلات ایمنی رو فوراً گزارش کنند.","state_rule",["obligation"],1),U("dont_have","You don't have to wear formal clothes on Fridays.","جمعه‌ها لازم نیست لباس رسمی بپوشی.","state_no_obligation",["optional"],1),U("mustnt","You mustn't share your access code with anyone.","نباید کد دسترسی‌ت رو با کسی به اشتراک بذاری.","state_prohibition",["prohibited"],2),U("allowed","Staff are allowed to work from home two days a week.","کارمندها اجازه دارند دو روز در هفته از خانه کار کنند.","state_permission",["allowed","permission"],2),U("exception","There is an exception for people who work night shifts.","برای کسانی که شیفت شب دارند یک استثنا وجود داره.","explain_exception",["exception"],2),U("policy","According to the policy, expenses over fifty dollars need manager approval.","طبق آیین‌نامه، هزینه‌های بالای پنجاه دلار به تأیید مدیر نیاز دارند.","cite_policy",["policy"],3),U("protective","You have to wear protective equipment in the workshop, even for a short visit.","حتی برای بازدید کوتاه هم باید در کارگاه تجهیزات محافظتی بپوشی.","emphasize_rule",["protective"],3)],
"grammar":[G("must_have_to","must vs have to","Use must for strong rules or speaker authority; have to is common for external rules and obligations.","برای الزام قوی یا قانون مستقیم از must و برای الزام بیرونی و رایج از have to استفاده می‌کنیم.",[("You must sign in.","باید ورودت رو ثبت کنی."),("We have to wear badges.","باید کارت شناسایی داشته باشیم.")],1),G("prohibition","mustn't vs don't have to","Mustn't means something is prohibited; don't have to means it is not necessary.","mustn't یعنی ممنوع است؛ don't have to یعنی لازم نیست.",[("You mustn't smoke here.","اینجا نباید سیگار بکشی."),("You don't have to stay late.","لازم نیست دیر بمونی.")],2),G("allowed","be allowed to","Use be allowed to for permission in rules and policies.","برای بیان اجازه طبق قانون یا آیین‌نامه از be allowed to استفاده می‌کنیم.",[("We're allowed to leave early on Friday.","جمعه اجازه داریم زودتر بریم."),("Visitors aren't allowed to enter this area.","بازدیدکننده‌ها اجازه ورود به این قسمت رو ندارند.")],3)],
"dialogues":[D("orientation","Workplace orientation","office",["Maya","Daniel"],[T("Daniel","You have to wear your badge at all times.","همیشه باید کارت شناسایی‌ت رو داشته باشی."),T("Maya","Do I have to wear formal clothes every day?","هر روز باید لباس رسمی بپوشم؟"),T("Daniel","No, you don't have to on Fridays.","نه، جمعه‌ها لازم نیست."),T("Maya","Good to know.","خوبه بدونم.")],1),D("workshop","Workshop rules","workshop",["Leo","Adam"],[T("Adam","Before we go in, you need safety glasses.","قبل از ورود به عینک ایمنی نیاز داری."),T("Leo","Even if I'm only staying for ten minutes?","حتی اگر فقط ده دقیقه بمونم؟"),T("Adam","Yes. Everyone has to wear them.","آره. همه باید استفاده کنند."),T("Leo","Got it.","فهمیدم.")],2),D("exception","Asking about an exception","HR desk",["Hana","Claire"],[T("Hana","The policy says we can work from home twice a week. Does that apply to my team?","آیین‌نامه می‌گه دو روز در هفته می‌تونیم دورکاری کنیم. برای تیم من هم هست؟"),T("Claire","Usually, yes, but there are some exceptions.","معمولاً آره، ولی چند استثنا هست."),T("Hana","Who should I ask about my schedule?","درباره برنامه‌م از کی بپرسم؟"),T("Claire","Your team manager can confirm it.","مدیر تیمت می‌تونه تأیید کنه.")],3)],
"fill":["You ___ share your access code with anyone.",["mustn't","don't have to","can","should"],"mustn't"]
},
{
"slug":"b1-solving-problems","file":"b1-solving-problems-v1.json","topic":"requests","lessons":3,
"vocab":[V("solution","solution","راه‌حل"),V("alternative","alternative","گزینه جایگزین"),V("practical","practical","عملی","adjective"),V("issue","issue","مشکل"),V("suggest","suggest","پیشنهاد دادن","verb"),V("workaround","workaround","راه‌حل موقت"),V("agree","agree","توافق کردن","verb"),V("priority","priority","اولویت"),V("backup","backup","پشتیبان / گزینه دوم"),V("resolve","resolve","حل کردن","verb")],
"utterances":[U("issue","The main issue is that the delivery won't arrive before the event.","مشکل اصلی اینه که تحویل قبل از رویداد نمی‌رسه.","define_problem",["issue"],1),U("suggest","Why don't we borrow the equipment for one day instead?","چرا به جاش تجهیزات رو برای یک روز قرض نگیریم؟","suggest_solution",["suggest","alternative"],1),U("could","We could use the smaller room if the main hall isn't available.","اگر سالن اصلی آزاد نبود می‌تونیم از اتاق کوچیک‌تر استفاده کنیم.","offer_alternative",["alternative"],1),U("workaround","As a temporary workaround, we can send the documents manually.","به‌عنوان راه‌حل موقت می‌تونیم اسناد رو دستی بفرستیم.","offer_workaround",["workaround"],2),U("priority","Our priority is to keep the customer informed, even if the final fix takes longer.","اولویتمون اینه که مشتری رو در جریان نگه داریم، حتی اگر حل نهایی بیشتر طول بکشه.","set_priority",["priority"],2),U("if","If we move the deadline by one day, the team can finish without rushing.","اگر مهلت رو یک روز عقب ببریم، تیم بدون عجله می‌تونه تموم کنه.","evaluate_condition",["practical"],2),U("backup","Let's agree on a backup plan in case the first option fails.","بیاید برای حالتی که گزینه اول جواب نداد روی یک برنامه پشتیبان توافق کنیم.","create_backup",["backup","agree"],3),U("resolve","That sounds practical. Let's do that and review the situation tomorrow.","عملی به نظر میاد. همین کار رو انجام بدیم و فردا وضعیت رو دوباره بررسی کنیم.","accept_solution",["practical","resolve"],3)],
"grammar":[G("suggestions","Suggestion forms","Use could, why don't we, how about + -ing, and let's to suggest options with different levels of directness.","برای پیشنهاد راه‌حل از could، why don't we، how about + ing و let's استفاده می‌کنیم.",[("We could call them.","می‌تونیم بهشون زنگ بزنیم."),("How about moving the meeting online?","چطوره جلسه رو آنلاین کنیم؟")],1),G("conditional","First conditional for solutions","Use if + present to test realistic options and likely results.","برای بررسی گزینه‌های واقعی و نتیجه احتمالی از شرط نوع اول استفاده می‌کنیم.",[("If we leave now, we'll avoid traffic.","اگر الان راه بیفتیم از ترافیک دور می‌مونیم."),("If that doesn't work, we can try plan B.","اگر جواب نداد، می‌تونیم برنامه دوم رو امتحان کنیم.")],2),G("agreement","Reaching agreement","Use phrases such as That sounds practical, I can work with that, or Let's go with… to close a problem-solving discussion.","برای جمع‌بندی و توافق از عبارت‌هایی مثل That sounds practical، I can work with that و Let's go with استفاده می‌کنیم.",[("Let's go with the second option.","بریم با گزینه دوم."),("I can work with that.","با اون می‌تونم کنار بیام.")],3)],
"dialogues":[D("delivery","Late delivery","office",["Amir","Ella"],[T("Amir","The chairs won't arrive before Friday's event.","صندلی‌ها قبل از رویداد جمعه نمی‌رسن."),T("Ella","Could we rent some locally for one day?","می‌تونیم برای یک روز محلی اجاره کنیم؟"),T("Amir","That's more expensive, but it would solve the problem.","گرون‌تره، ولی مشکل رو حل می‌کنه."),T("Ella","Then let's compare two rental companies today.","پس امروز دو شرکت اجاره رو مقایسه کنیم.")],1),D("room","No meeting room","office",["Ravi","Mina"],[T("Ravi","The main meeting room is booked all afternoon.","اتاق جلسه اصلی کل بعدازظهر رزروه."),T("Mina","How about moving the workshop online?","چطوره کارگاه رو آنلاین کنیم؟"),T("Ravi","Some activities need to be in person.","بعضی فعالیت‌ها باید حضوری باشه."),T("Mina","Then we could use two smaller rooms and split the group.","پس می‌تونیم از دو اتاق کوچیک‌تر استفاده کنیم و گروه رو تقسیم کنیم.")],2),D("backup","Agreeing on a backup","video call",["Chloe","Adam"],[T("Chloe","What if the supplier cancels again?","اگر تأمین‌کننده دوباره لغو کرد چی؟"),T("Adam","We should have a backup supplier ready.","باید یک تأمین‌کننده پشتیبان آماده داشته باشیم."),T("Chloe","Agreed. I'll contact the second company today.","موافقم. امروز با شرکت دوم تماس می‌گیرم."),T("Adam","Great. That gives us a practical backup.","عالیه. این یک برنامه پشتیبان عملی بهمون می‌ده.")],3)],
"fill":["If the main hall isn't available, we ___ use the smaller room.",["could","did","mustn't","had"],"could"]
},
{
"slug":"b1-complaints-solutions","file":"b1-complaints-solutions-v1.json","topic":"requests","lessons":3,
"vocab":[V("complaint","complaint","شکایت"),V("faulty","faulty","معیوب","adjective"),V("replacement","replacement","جایگزین"),V("refund","refund","بازپرداخت"),V("inconvenience","inconvenience","دردسر / مزاحمت"),V("resolve","resolve","حل کردن","verb"),V("receipt","receipt","رسید"),V("warranty","warranty","ضمانت"),V("apologize","apologize","عذرخواهی کردن","verb"),V("acceptable","acceptable","قابل‌قبول","adjective")],
"utterances":[U("problem","I'm calling because the laptop I bought last week has stopped charging.","تماس گرفتم چون لپ‌تاپی که هفته پیش خریدم دیگه شارژ نمی‌شه.","open_complaint",["complaint","faulty"],1),U("history","I've only used it three times, so this isn't what I expected.","فقط سه بار ازش استفاده کردم، پس این چیزی نیست که انتظار داشتم.","give_relevant_detail",["faulty"],1),U("receipt","I still have the receipt and the product is under warranty.","هنوز رسید رو دارم و محصول تحت ضمانته.","provide_proof",["receipt","warranty"],1),U("request","I'd like a replacement rather than another repair attempt.","ترجیح می‌دم جایگزین بگیرم تا اینکه دوباره تعمیرش کنید.","request_solution",["replacement"],2,"polite"),U("refund","If a replacement isn't available, I'd like to request a refund.","اگر جایگزین موجود نیست، می‌خوام درخواست بازپرداخت بدم.","request_refund",["refund"],2,"polite"),U("apology","We apologize for the inconvenience and we'll arrange a replacement today.","برای دردسر پیش‌آمده عذرخواهی می‌کنیم و امروز جایگزین رو هماهنگ می‌کنیم.","respond_to_complaint",["apologize","inconvenience","replacement"],2),U("passive","The item will be collected from your address tomorrow morning.","کالا فردا صبح از آدرستون جمع‌آوری می‌شه.","explain_service_step",["resolve"],3),U("acceptable","That solution is acceptable, as long as I don't have to pay for shipping.","اون راه‌حل قابل‌قبوله، به شرطی که هزینه ارسال ندم.","accept_conditionally",["acceptable"],3)],
"grammar":[G("current_problem","Present perfect for a current problem","Use present perfect when a recent problem has a result that is still true now.","وقتی مشکل اخیر نتیجه‌ای دارد که هنوز ادامه دارد از present perfect استفاده می‌کنیم.",[("The screen has stopped working.","صفحه از کار افتاده."),("I've lost the receipt.","رسید رو گم کرده‌ام.")],1),G("polite_requests","Polite complaint requests","Use I'd like…, Could you…?, and Would it be possible…? to request a solution firmly but politely.","برای درخواست راه‌حل مؤدبانه ولی قاطع از I'd like، Could you و Would it be possible استفاده می‌کنیم.",[("I'd like a replacement, please.","لطفاً جایگزین می‌خوام."),("Could you check the warranty?","می‌شه ضمانت رو بررسی کنید؟")],2),G("passive_intro","Passive voice introduction","Use be + past participle when the action or process matters more than who performs it.","وقتی خود فرایند مهم‌تر از انجام‌دهنده است از be + قسمت سوم فعل استفاده می‌کنیم.",[("The item will be collected tomorrow.","کالا فردا جمع‌آوری می‌شه."),("The repair was completed yesterday.","تعمیر دیروز تمام شد.")],3)],
"dialogues":[D("laptop","Faulty laptop complaint","support call",["Maya","Daniel"],[T("Maya","The laptop I bought last week has stopped charging.","لپ‌تاپی که هفته پیش خریدم دیگه شارژ نمی‌شه."),T("Daniel","I'm sorry about that. Do you still have the receipt?","متأسفم. هنوز رسید رو دارید؟"),T("Maya","Yes, and it's under warranty.","آره، و تحت ضمانته."),T("Daniel","Then we can arrange a replacement or repair.","پس می‌تونیم جایگزین یا تعمیر رو هماهنگ کنیم.")],1),D("hotel","A hotel complaint","hotel desk",["Hana","Noah"],[T("Hana","I'm afraid the air conditioning in my room still isn't working.","متأسفانه تهویه اتاقم هنوز کار نمی‌کنه."),T("Noah","I apologize. We sent someone up earlier.","عذر می‌خوام. قبلاً کسی رو فرستادیم بالا."),T("Hana","Yes, but the problem hasn't been fixed.","آره، ولی مشکل حل نشده."),T("Noah","I'll move you to another room immediately.","فوراً شما رو به اتاق دیگه منتقل می‌کنم.")],2),D("solution","Agreeing on a solution","service desk",["Sofia","Omar"],[T("Sofia","A replacement would be fine if it can arrive this week.","جایگزین خوبه اگر این هفته برسه."),T("Omar","We can deliver one by Thursday.","می‌تونیم تا پنجشنبه تحویل بدیم."),T("Sofia","And the faulty one will be collected?","و کالای خراب جمع‌آوری می‌شه؟"),T("Omar","Yes, at no extra cost.","آره، بدون هزینه اضافه.")],3)],
"fill":["The item will be ___ tomorrow morning.",["collected","collect","collecting","collection"],"collected"]
},
{
"slug":"b1-shopping-decisions","file":"b1-shopping-decisions-v1.json","topic":"shopping","lessons":3,
"vocab":[V("durability","durability","دوام"),V("review","review","نظر کاربران / نقد"),V("suitable","suitable","مناسب","adjective"),V("feature","feature","ویژگی"),V("warranty","warranty","ضمانت"),V("budget","budget","بودجه"),V("value","value","ارزش خرید"),V("brand","brand","برند"),V("efficient","efficient","کارآمد","adjective"),V("recommendation","recommendation","پیشنهاد")],
"utterances":[U("need","I need a laptop that's light enough to carry every day but powerful enough for video editing.","لپ‌تاپی می‌خوام که آن‌قدر سبک باشه که هر روز حملش کنم ولی برای تدوین ویدئو هم به‌اندازه کافی قوی باشه.","describe_need",["suitable","feature"],1),U("review","Most reviews say the battery is excellent, but the keyboard feels cheap.","بیشتر نظرها می‌گن باتری عالیه، ولی کیبورد حس ارزون بودن می‌ده.","summarize_reviews",["review"],1),U("warranty","This model comes with a two-year warranty, which is better than the cheaper one.","این مدل ضمانت دوساله داره که از مدل ارزون‌تر بهتره.","compare_warranty",["warranty"],1),U("durability","I'd rather pay more for better durability if I'm going to use it every day.","اگر قراره هر روز استفاده کنم ترجیح می‌دم برای دوام بیشتر پول بیشتری بدم.","weigh_durability",["durability"],2),U("efficient","The newer model is more energy-efficient, so it should cost less to run.","مدل جدید کم‌مصرف‌تره، پس هزینه استفاده‌اش باید کمتر باشه.","evaluate_efficiency",["efficient"],2),U("budget","It's slightly over my budget, but the extra features may be worth it.","کمی از بودجه‌م بالاتره، ولی شاید امکانات اضافه ارزشش رو داشته باشه.","weigh_budget",["budget","feature","value"],2),U("relative","I'm looking for a brand that has reliable customer support.","دنبال برندی هستم که پشتیبانی مشتری قابل‌اعتماد داشته باشه.","state_requirement",["brand"],3),U("decision","Given the warranty, reviews, and price, this one seems like the best overall value.","با توجه به ضمانت، نظرها و قیمت، این یکی بهترین ارزش خرید کلی رو داره.","make_purchase_decision",["recommendation","value"],3)],
"grammar":[G("relative","Defining relative clauses","Use who/that/which to define the person or thing you mean.","برای مشخص کردن دقیق شخص یا چیز از who/that/which استفاده می‌کنیم.",[("I want a phone that has a good camera.","گوشی‌ای می‌خوام که دوربین خوبی داشته باشه."),("She's the salesperson who helped me yesterday.","اون فروشنده‌ایه که دیروز کمکم کرد.")],1),G("too_enough","too / enough","Use too + adjective for more than acceptable and adjective + enough for a sufficient degree.","برای بیشتر از حد مناسب از too + صفت و برای حد کافی از adjective + enough استفاده می‌کنیم.",[("It's too heavy to carry every day.","برای حمل روزانه زیادی سنگینه."),("The screen is bright enough outside.","صفحه بیرون به‌اندازه کافی روشنه.")],2),G("comparison_degree","Degree in comparisons","Use slightly, much, far, or a lot to make comparisons more precise.","برای دقیق‌تر کردن مقایسه از slightly، much، far یا a lot استفاده می‌کنیم.",[("It's slightly cheaper.","کمی ارزون‌تره."),("This model is far more reliable.","این مدل خیلی قابل‌اعتمادتره.")],3)],
"dialogues":[D("laptop","Choosing a laptop","electronics store",["Lina","Ben"],[T("Lina","I need something light enough for commuting but powerful enough for editing.","چیزی می‌خوام که برای رفت‌وآمد سبک باشه ولی برای تدوین هم کافی قوی باشه."),T("Ben","This model is popular with people who travel a lot.","این مدل بین کسانی که زیاد سفر می‌کنند محبوبه."),T("Lina","How's the battery life?","عمر باتریش چطوره؟"),T("Ben","Most reviews say it lasts around ten hours.","بیشتر نظرها می‌گن حدود ده ساعت دوام میاره.")],1),D("appliance","Comparing appliances","home store",["Amir","Ella"],[T("Amir","This washing machine is cheaper.","این ماشین لباسشویی ارزون‌تره."),T("Ella","Yes, but the other one is much more energy-efficient.","آره، ولی اون یکی خیلی کم‌مصرف‌تره."),T("Amir","Do you think the difference is worth the price?","فکر می‌کنی تفاوتش ارزش قیمت رو داره؟"),T("Ella","If you keep it for years, probably.","اگر سال‌ها نگهش داری، احتمالاً آره.")],2),D("final","Making the purchase","store counter",["Ravi","Mina"],[T("Ravi","So which one are you getting?","پس کدوم رو می‌گیری؟"),T("Mina","The mid-range model with the longer warranty.","مدل میان‌رده با ضمانت طولانی‌تر."),T("Ravi","Even though it's over budget?","با اینکه از بودجه بالاتره؟"),T("Mina","A little, but I think it's better value overall.","کمی، ولی فکر می‌کنم در مجموع ارزش خرید بهتری داره.")],3)],
"fill":["I need a phone that's light ___ to carry all day.",["enough","too","so","very"],"enough"]
},
{
"slug":"b1-services-returns","file":"b1-services-returns-v1.json","topic":"shopping","lessons":3,
"vocab":[V("repair","repair","تعمیر"),V("technician","technician","تکنسین"),V("estimate","estimate","برآورد قیمت"),V("fault","fault","خرابی"),V("replace","replace","تعویض کردن","verb"),V("service","service","سرویس"),V("diagnose","diagnose","عیب‌یابی کردن","verb"),V("appointment","appointment","وقت"),V("charge","charge","هزینه گرفتن","verb"),V("covered","covered","تحت پوشش","adjective")],
"utterances":[U("fault","The technician said the fault is probably in the power supply.","تکنسین گفت خرابی احتمالاً از منبع تغذیه است.","report_diagnosis",["technician","fault","diagnose"],1),U("estimate","Could you give me an estimate before you start the repair?","می‌شه قبل از شروع تعمیر برآورد هزینه بدید؟","request_estimate",["estimate","repair"],1,"polite"),U("covered","The replacement part is covered by the warranty, but labor isn't.","قطعه جایگزین تحت ضمانته، ولی دستمزد نیست.","explain_coverage",["covered","replace"],1),U("done","I'm getting my phone screen replaced tomorrow afternoon.","فردا بعدازظهر صفحه گوشیم رو تعویض می‌کنم.","arrange_service",["replace","appointment"],2),U("charge","They charged me for the inspection, even though they couldn't fix the problem.","برای بررسی ازم هزینه گرفتند، با اینکه نتونستند مشکل رو حل کنند.","report_service_issue",["charge","service"],2),U("passive","The device was inspected this morning and the part has already been ordered.","دستگاه امروز صبح بررسی شد و قطعه از قبل سفارش داده شده.","report_process",["service"],2),U("reported","They told me it should be ready by Thursday.","گفتند باید تا پنجشنبه آماده باشه.","relay_service_info",["appointment"],3),U("outcome","If the repair costs more than the estimate, please call me before continuing.","اگر هزینه تعمیر از برآورد بیشتر شد، لطفاً قبل از ادامه باهام تماس بگیرید.","set_service_condition",["estimate","repair"],3)],
"grammar":[G("have_get_done","have/get something done","Use have/get + object + past participle when you arrange for someone else to perform a service.","وقتی ترتیب می‌دیم شخص دیگری کاری را انجام دهد از have/get + مفعول + قسمت سوم فعل استفاده می‌کنیم.",[("I'm getting my screen replaced.","دارم صفحه گوشیم رو تعویض می‌کنم."),("We had the air conditioner serviced.","کولر رو سرویس کردیم.")],1),G("passive","Passive for service processes","Use the passive when the process matters more than the person doing it.","در توضیح فرایند سرویس وقتی انجام‌دهنده مهم نیست از passive استفاده می‌کنیم.",[("The part has been ordered.","قطعه سفارش داده شده."),("The device was inspected yesterday.","دستگاه دیروز بررسی شد.")],2),G("reported_chunks","Reporting service information","Use told me / said that / explained that to relay information from staff.","برای انتقال اطلاعات کارکنان از told me، said that و explained that استفاده می‌کنیم.",[("They told me it would take two days.","گفتند دو روز طول می‌کشه."),("She explained that labor wasn't covered.","توضیح داد دستمزد تحت پوشش نیست.")],3)],
"dialogues":[D("repair","Getting an estimate","repair shop",["Chloe","Adam"],[T("Chloe","Could you give me an estimate before you repair it?","می‌شه قبل از تعمیر برآورد هزینه بدید؟"),T("Adam","Of course. We need to inspect it first.","حتماً. اول باید بررسیش کنیم."),T("Chloe","Is there a charge for the inspection?","برای بررسی هزینه‌ای هست؟"),T("Adam","Only if you decide not to continue with the repair.","فقط اگر تصمیم بگیرید تعمیر رو ادامه ندید.")],1),D("phone","Screen replacement","phone shop",["Maya","Leo"],[T("Maya","I'm getting my screen replaced tomorrow.","فردا صفحه گوشیم رو تعویض می‌کنم."),T("Leo","How long will it take?","چقدر طول می‌کشه؟"),T("Maya","They said it should be ready in about two hours.","گفتند حدود دو ساعت دیگه آماده می‌شه."),T("Leo","That's faster than I expected.","از چیزی که انتظار داشتم سریع‌تره.")],2),D("update","Repair status update","support call",["Hana","Daniel"],[T("Hana","I'm calling to check on repair number 4821.","برای پیگیری تعمیر شماره ۴۸۲۱ تماس گرفتم."),T("Daniel","The device was inspected this morning.","دستگاه امروز صبح بررسی شد."),T("Hana","Has the replacement part arrived yet?","قطعه جایگزین رسیده؟"),T("Daniel","Not yet, but it's expected tomorrow.","هنوز نه، ولی فردا انتظار می‌ره برسه.")],3)],
"fill":["I'm getting my phone screen ___ tomorrow.",["replaced","replace","replacing","replacement"],"replaced"]
}
]

def main():
    OUT.mkdir(parents=True,exist_ok=True); w=[]
    for s in UNITS:
        p=OUT/s["file"]; p.write_text(json.dumps(build(s),ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); w.append(p.name)
    print(json.dumps({"written":len(w),"files":w},ensure_ascii=False,indent=2))
if __name__=="__main__": main()
