#!/usr/bin/env python3
from __future__ import annotations
import json
from scripts.generate_b1_batch import V,U,G,D,T,build,OUT

UNITS=[
{
"slug":"b1-invitations-hosting","file":"b1-invitations-hosting-v1.json","topic":"polite-language","lessons":3,
"vocab":[V("host","host","میزبان شدن","verb"),V("guest","guest","مهمان"),V("bring","bring","آوردن","verb"),V("help_yourself","help yourself","بفرمایید / خودتون بردارید","phrase"),V("make_yourself_at_home","make yourself at home","راحت باشید","phrase"),V("dietary","dietary","مربوط به رژیم غذایی","adjective"),V("appreciate","appreciate","قدردانی کردن","verb"),V("decline","decline","رد کردن","verb"),V("drop_by","drop by","سر زدن","phrasal_verb"),V("arrange","arrange","هماهنگ کردن","verb")],
"utterances":[U("invite","Would you like to come over for dinner on Saturday?","دوست داری شنبه برای شام بیای خونه ما؟","invite_home",["host"],1,"polite"),U("detail","We're planning to eat around seven, but feel free to come a little earlier.","قرار گذاشتیم حدود هفت شام بخوریم، ولی اگر خواستی کمی زودتر بیا.","give_hosting_details",["arrange"],1),U("bring","Can I bring anything, or do you have everything covered?","چیزی بیارم یا همه‌چی رو آماده کردی؟","offer_to_bring",["bring"],1,"polite"),U("dietary","Do you have any dietary restrictions I should know about?","محدودیت غذایی خاصی داری که باید بدونم؟","ask_dietary_needs",["dietary"],2,"polite"),U("home","Make yourself at home, and help yourself to anything on the table.","راحت باش و هرچی روی میزه خواستی بردار.","welcome_guest",["make_yourself_at_home","help_yourself"],2),U("decline","I'd love to, but I already have plans that evening.","خیلی دوست دارم، ولی اون شب از قبل برنامه دارم.","decline_politely",["decline"],2,"polite"),U("appreciate","Thanks for having us. We really appreciate it.","ممنون که دعوتمون کردید. واقعاً قدردانیم.","thank_host",["appreciate","guest"],3),U("drop","If you're in the neighborhood next week, feel free to drop by.","اگر هفته بعد اطراف اینجا بودی، راحت سر بزن.","open_invitation",["drop_by"],3)],
"grammar":[G("polite_modals","Would / could for social politeness","Use would and could to make invitations, offers, and requests sound less direct.","برای مؤدبانه‌تر کردن دعوت، پیشنهاد و درخواست از would و could استفاده می‌کنیم.",[("Would you like another drink?","نوشیدنی دیگه‌ای می‌خوای؟"),("Could you pass the bread?","می‌شه نون رو بدی؟")],1),G("indirect_questions","Indirect questions introduction","Use phrases such as Do you know…? or Could you tell me…? followed by statement word order.","در سؤال غیرمستقیم از عبارت‌هایی مثل Do you know و Could you tell me استفاده می‌کنیم و بعد ترتیب جمله خبری می‌آید.",[("Do you know what time Sam is arriving?","می‌دونی سام چه ساعتی می‌رسه؟"),("Could you tell me where I should put this?","می‌شه بگی این رو کجا بذارم؟")],2),G("offers","Offers with shall / can / let me","Use can I, shall I, or let me to offer practical help naturally.","برای پیشنهاد کمک عملی از can I، shall I یا let me استفاده می‌کنیم.",[("Can I help with the dishes?","می‌تونم برای ظرف‌ها کمک کنم؟"),("Let me take your coat.","بذار کتت رو بگیرم.")],3)],
"dialogues":[D("invite","Inviting friends over","phone call",["Maya","Leo"],[T("Maya","Would you and Hana like to come over for dinner Saturday?","تو و هانا دوست دارید شنبه برای شام بیاید؟"),T("Leo","We'd love to. What time should we come?","خیلی دوست داریم. چه ساعتی بیایم؟"),T("Maya","Around six-thirty would be great.","حدود شش‌ونیم عالیه."),T("Leo","Perfect. Can we bring anything?","عالیه. چیزی بیاریم؟")],1),D("arrival","Welcoming guests","apartment",["Sofia","Omar"],[T("Sofia","Come in! Make yourself at home.","بیا تو! راحت باش."),T("Omar","Thanks. This smells amazing.","ممنون. بوش فوق‌العاده‌ست."),T("Sofia","Help yourself to the snacks. Dinner will be ready soon.","از خوراکی‌ها بردار. شام به‌زودی آماده می‌شه."),T("Omar","Can I help with anything?","کاری هست کمک کنم؟")],2),D("decline","Declining and suggesting another day","text messages",["Lina","Ben"],[T("Lina","We're having a few people over Friday. Want to join us?","جمعه چند نفر میان خونه‌مون. دوست داری بیای؟"),T("Ben","I'd love to, but I'm working late Friday.","خیلی دوست دارم، ولی جمعه دیر وقت کار می‌کنم."),T("Lina","No problem. Maybe you can drop by Sunday afternoon instead.","مشکلی نیست. شاید به جاش یکشنبه بعدازظهر سر بزنی."),T("Ben","Sunday sounds great.","یکشنبه عالیه.")],3)],
"fill":["Could you tell me what time the guests ___ arriving?",["are","do","will","did"],"are"]
},
{
"slug":"b1-opinions-reasons","file":"b1-opinions-reasons-v1.json","topic":"likes-dislikes","lessons":3,
"vocab":[V("point_of_view","point of view","دیدگاه"),V("advantage","advantage","مزیت"),V("disadvantage","disadvantage","عیب"),V("evidence","evidence","شاهد / مدرک"),V("in_my_view","in my view","از نظر من","phrase"),V("although","although","با اینکه","conjunction"),V("overall","overall","در مجموع","adverb"),V("reasonable","reasonable","منطقی","adjective"),V("argument","argument","استدلال"),V("factor","factor","عامل")],
"utterances":[U("view","In my view, flexible hours are more useful than a completely remote schedule.","از نظر من ساعت کاری منعطف از برنامه کاملاً دورکاری مفیدتره.","state_opinion",["in_my_view"],1),U("reason","The main reason is that people have different responsibilities outside work.","دلیل اصلی اینه که آدم‌ها بیرون از کار مسئولیت‌های متفاوتی دارند.","give_reason",["factor"],1),U("example","For example, parents may need more control over when they start and finish.","مثلاً والدین ممکنه نیاز داشته باشند روی ساعت شروع و پایان کنترل بیشتری داشته باشند.","give_example",["argument"],1),U("advantage","One clear advantage is that employees can avoid rush-hour traffic.","یک مزیت واضح اینه که کارمندها می‌تونن از ترافیک ساعت شلوغی دوری کنند.","give_advantage",["advantage"],2),U("contrast","Although remote work is convenient, it can sometimes feel isolating.","با اینکه دورکاری راحته، گاهی می‌تونه حس انزوا بده.","qualify_opinion",["although","disadvantage"],2),U("evidence","I haven't seen strong evidence that one schedule works for everyone.","شاهد محکمی ندیدم که یک نوع برنامه برای همه جواب بده.","refer_to_evidence",["evidence"],2),U("reasonable","A reasonable compromise would be two office days and three flexible days.","یک سازش منطقی می‌تونه دو روز دفتر و سه روز منعطف باشه.","propose_balanced_view",["reasonable"],3),U("overall","Overall, I think choice matters more than one fixed policy.","در مجموع فکر می‌کنم حق انتخاب از یک سیاست ثابت مهم‌تره.","summarize_opinion",["overall"],3)],
"grammar":[G("opinion_frames","Developing an opinion","Use frames such as In my view, The main reason is…, and For example… to structure an opinion clearly.","برای ساختار دادن نظر از عباراتی مثل In my view، The main reason is و For example استفاده می‌کنیم.",[("In my view, the change is positive.","از نظر من این تغییر مثبته."),("The main reason is cost.","دلیل اصلی هزینه است.")],1),G("reason_links","because / since / as","Use because, since, or as to connect a claim with a reason; because is usually the most direct.","برای وصل کردن ادعا و دلیل از because، since یا as استفاده می‌کنیم؛ because مستقیم‌تر است.",[("I prefer the train because it's more reliable.","قطار رو ترجیح می‌دم چون قابل‌اعتمادتره."),("Since we have time, let's compare both options.","چون وقت داریم، هر دو گزینه رو مقایسه کنیم.")],2),G("concession","although / even though","Use although or even though to acknowledge a contrasting fact before keeping your main position.","با although یا even though یک نکته مخالف رو می‌پذیریم ولی موضع اصلی رو حفظ می‌کنیم.",[("Although it's expensive, it's very durable.","با اینکه گرونه، خیلی بادوامه."),("Even though I disagree, I understand the concern.","با اینکه مخالفم، نگرانی رو درک می‌کنم.")],3)],
"dialogues":[D("remote","Discussing remote work","lunch room",["Amir","Ella"],[T("Amir","Do you think everyone should be allowed to work from home?","فکر می‌کنی همه باید اجازه دورکاری داشته باشند؟"),T("Ella","Not everyone, but I think most office jobs should offer some flexibility.","نه همه، ولی فکر می‌کنم بیشتر کارهای اداری باید کمی انعطاف داشته باشند."),T("Amir","What's the main advantage for you?","مزیت اصلیش برای تو چیه؟"),T("Ella","Time. I save almost an hour when I don't commute.","زمان. وقتی رفت‌وآمد ندارم تقریباً یک ساعت ذخیره می‌کنم.")],1),D("city","Opinions about city transport","bus stop",["Ravi","Mina"],[T("Ravi","In my view, the city needs more frequent buses.","از نظر من شهر به اتوبوس‌های پرتعدادتر نیاز داره."),T("Mina","I agree, although the subway is already pretty good.","موافقم، با اینکه مترو همین الان هم خوبه."),T("Ravi","True, but not everyone lives near a station.","درسته، ولی همه نزدیک ایستگاه زندگی نمی‌کنند."),T("Mina","That's a fair point.","نکته منصفانه‌ایه.")],2),D("summary","Finding a balanced view","meeting",["Chloe","Adam"],[T("Chloe","So what's your overall view?","پس نظر کلیت چیه؟"),T("Adam","I support the change, but only if we review it after six months.","از تغییر حمایت می‌کنم، ولی فقط اگر بعد از شش ماه بررسیش کنیم."),T("Chloe","That sounds reasonable.","منطقیه."),T("Adam","We need evidence before making it permanent.","قبل از دائمی کردنش به شواهد نیاز داریم.")],3)],
"fill":["___ it's convenient, remote work can feel isolating.",["Although","Because","So","Therefore"],"Although"]
},
{
"slug":"b1-agree-disagree","file":"b1-agree-disagree-v1.json","topic":"likes-dislikes","lessons":3,
"vocab":[V("completely","completely","کاملاً","adverb"),V("partly","partly","تا حدی","adverb"),V("fair_point","fair point","نکته منصفانه","phrase"),V("not_necessarily","not necessarily","لزومی نداره / نه لزوماً","phrase"),V("however","however","با این حال","adverb"),V("whereas","whereas","در حالی که","conjunction"),V("respectfully","respectfully","با احترام","adverb"),V("perspective","perspective","دیدگاه"),V("convince","convince","قانع کردن","verb"),V("soften","soften","ملایم کردن","verb")],
"utterances":[U("agree","I completely agree that the current system is too complicated.","کاملاً موافقم که سیستم فعلی زیادی پیچیده است.","agree_strongly",["completely"],1),U("partial","I partly agree, but I don't think cost is the only issue.","تا حدی موافقم، ولی فکر نمی‌کنم هزینه تنها مشکل باشه.","agree_partly",["partly"],1),U("fair","That's a fair point, although I see the situation a little differently.","نکته منصفانه‌ایه، با اینکه من موقعیت رو کمی متفاوت می‌بینم.","acknowledge_then_disagree",["fair_point","perspective"],1),U("notnecessarily","Not necessarily. Some people are more productive with fewer meetings.","نه لزوماً. بعضی‌ها با جلسه‌های کمتر بهره‌ورترند.","challenge_claim",["not_necessarily"],2),U("however","The idea is simple. However, it could be difficult to apply fairly.","ایده ساده است. با این حال ممکنه اجرای منصفانه‌اش سخت باشه.","add_contrast",["however"],2),U("whereas","I prefer working early, whereas my teammate does her best work in the evening.","من کار کردن صبح زود رو ترجیح می‌دم، در حالی که هم‌تیمی‌م عصرها بهترین عملکردش رو داره.","contrast_preferences",["whereas"],2),U("soften","I may be wrong, but I don't think that solution addresses the main problem.","ممکنه اشتباه کنم، ولی فکر نمی‌کنم اون راه‌حل مشکل اصلی رو حل کنه.","soften_disagreement",["soften"],3),U("respect","I respect that perspective, even though it hasn't convinced me.","به اون دیدگاه احترام می‌ذارم، با اینکه هنوز من رو قانع نکرده.","disagree_respectfully",["respectfully","convince"],3)],
"grammar":[G("so_neither","so / neither for agreement","Use So + auxiliary + subject to agree with a positive statement and Neither + auxiliary + subject for a negative one.","برای موافقت با جمله مثبت از So + فعل کمکی + فاعل و برای جمله منفی از Neither استفاده می‌کنیم.",[("I enjoy it. So do I.","من دوستش دارم. من هم همین‌طور."),("I don't drive. Neither do I.","من رانندگی نمی‌کنم. من هم نمی‌کنم.")],1),G("contrast","Contrast markers","Use however, whereas, while, and on the other hand to compare opposing points clearly.","برای مقایسه دیدگاه‌های مخالف از however، whereas، while و on the other hand استفاده می‌کنیم.",[("It's cheaper; however, it's less reliable.","ارزان‌تره؛ با این حال کمتر قابل‌اعتماده."),("I work early, whereas she works late.","من زود کار می‌کنم، در حالی که او دیر کار می‌کنه.")],2),G("softening","Softening disagreement","Use phrases such as I see your point, but…, I'm not sure…, or I may be wrong, but… to disagree politely.","برای مخالفت مؤدبانه از عبارت‌هایی مثل I see your point, but، I'm not sure و I may be wrong, but استفاده می‌کنیم.",[("I see your point, but I still disagree.","حرفت رو می‌فهمم، ولی هنوز مخالفم."),("I'm not sure that's the best option.","مطمئن نیستم اون بهترین گزینه باشه.")],3)],
"dialogues":[D("meetings","Too many meetings","office",["Maya","Leo"],[T("Maya","I think we have too many meetings.","فکر می‌کنم جلسه‌هامون خیلی زیاده."),T("Leo","I completely agree. Half of them could be emails.","کاملاً موافقم. نصفشون می‌تونست ایمیل باشه."),T("Maya","Exactly. We need more uninterrupted work time.","دقیقاً. به زمان کاری بدون وقفه بیشتری نیاز داریم."),T("Leo","So do I, especially in the mornings.","منم همین‌طور، مخصوصاً صبح‌ها.")],1),D("cars","Cars in the city center","cafe",["Hana","Noah"],[T("Hana","I think cars should be banned from the city center.","فکر می‌کنم ماشین‌ها باید از مرکز شهر ممنوع بشن."),T("Noah","I see your point, but not everyone can use public transportation.","حرفت رو می‌فهمم، ولی همه نمی‌تونن از حمل‌ونقل عمومی استفاده کنند."),T("Hana","That's fair. Maybe residents could get special permits.","منصفانه‌ست. شاید ساکن‌ها بتونن مجوز ویژه بگیرن."),T("Noah","I'd support that compromise.","من از اون سازش حمایت می‌کنم.")],2),D("policy","A respectful disagreement","team meeting",["Sofia","Omar"],[T("Sofia","I don't think this policy will reduce costs.","فکر نمی‌کنم این سیاست هزینه‌ها رو کم کنه."),T("Omar","Really? I think it could save us money over time.","جدی؟ فکر می‌کنم در طول زمان می‌تونه پول ذخیره کنه."),T("Sofia","Possibly, but I'm not convinced by the current numbers.","ممکنه، ولی اعداد فعلی من رو قانع نکرده."),T("Omar","Fair enough. Let's review the data again.","باشه. دوباره داده‌ها رو بررسی کنیم.")],3)],
"fill":["I see your point, ___ I still disagree.",["but","because","so","unless"],"but"]
},
{
"slug":"b1-choices-tradeoffs","file":"b1-choices-tradeoffs-v1.json","topic":"prices","lessons":3,
"vocab":[V("trade_off","trade-off","بده‌بستان / مصالحه"),V("priority","priority","اولویت"),V("affordable","affordable","مقرون‌به‌صرفه","adjective"),V("reliable","reliable","قابل‌اعتماد","adjective"),V("convenient","convenient","راحت / مناسب","adjective"),V("feature","feature","ویژگی"),V("sacrifice","sacrifice","فدا کردن","verb"),V("benefit","benefit","مزیت"),V("drawback","drawback","نقطه‌ضعف"),V("rather","rather","ترجیحاً","adverb")],
"utterances":[U("priority","For me, reliability is a higher priority than having the newest features.","برای من قابل‌اعتماد بودن اولویت بالاتری از داشتن جدیدترین قابلیت‌هاست.","state_priority",["priority","reliable","feature"],1),U("tradeoff","The main trade-off is price: the cheaper model has a shorter warranty.","بده‌بستان اصلی قیمته: مدل ارزان‌تر ضمانت کوتاه‌تری داره.","identify_tradeoff",["trade_off","affordable"],1),U("hand","On the one hand, living downtown is convenient; on the other hand, it's much more expensive.","از یک طرف زندگی مرکز شهر راحته؛ از طرف دیگه خیلی گرون‌تره.","weigh_sides",["convenient","drawback"],1),U("benefit","The biggest benefit of the longer route is that it's more reliable during rush hour.","بزرگ‌ترین مزیت مسیر طولانی‌تر اینه که در ساعت شلوغی قابل‌اعتمادتره.","state_benefit",["benefit","reliable"],2),U("sacrifice","I'm willing to sacrifice some space if the apartment is closer to work.","حاضرم کمی فضا رو فدا کنم اگر آپارتمان به کار نزدیک‌تر باشه.","state_compromise",["sacrifice"],2),U("rather","I'd rather pay a little more for something that will last longer.","ترجیح می‌دم کمی بیشتر پول بدم برای چیزی که بیشتر دوام بیاره.","state_preference",["rather"],2),U("compare","Neither option is perfect, so we need to decide which disadvantage matters less.","هیچ‌کدوم بی‌نقص نیست، پس باید تصمیم بگیریم کدوم عیب کمتر مهمه.","evaluate_tradeoffs",["drawback"],3),U("decision","Given our budget and priorities, the mid-range option makes the most sense.","با توجه به بودجه و اولویت‌هامون، گزینه میان‌رده منطقی‌تره.","reach_choice",["priority","affordable"],3)],
"grammar":[G("two_sides","on the one hand / on the other hand","Use these paired expressions to organize two competing sides of a decision.","برای مرتب کردن دو طرف یک تصمیم از on the one hand و on the other hand استفاده می‌کنیم.",[("On the one hand, it's cheap; on the other hand, it's slow.","از یک طرف ارزونه؛ از طرف دیگه کنده."),("On the one hand, I want more space; on the other hand, location matters more.","از یک طرف فضای بیشتر می‌خوام؛ از طرف دیگه موقعیت مهم‌تره.")],1),G("prefer_rather","prefer / would rather","Use prefer + noun/-ing or would rather + base verb to compare preferences.","برای ترجیح از prefer + اسم/ing یا would rather + فعل پایه استفاده می‌کنیم.",[("I prefer taking the train.","قطار رو ترجیح می‌دم."),("I'd rather wait until tomorrow.","ترجیح می‌دم تا فردا صبر کنم.")],2),G("comparisons","More complex comparisons","Use much/a little/far before comparatives to show the size of a difference.","برای نشان دادن اندازه تفاوت قبل از صفت تفضیلی از much، a little یا far استفاده می‌کنیم.",[("This one is much more reliable.","این یکی خیلی قابل‌اعتمادتره."),("The second option is a little cheaper.","گزینه دوم کمی ارزون‌تره.")],3)],
"dialogues":[D("apartment","Choosing an apartment","cafe",["Lina","Ben"],[T("Lina","The downtown apartment is smaller, but the commute is ten minutes.","آپارتمان مرکز شهر کوچیک‌تره، ولی رفت‌وآمد ده دقیقه‌ست."),T("Ben","The other one is much bigger and cheaper.","اون یکی خیلی بزرگ‌تر و ارزون‌تره."),T("Lina","True, but I'd rather have less space than spend an hour commuting.","درسته، ولی ترجیح می‌دم فضای کمتر داشته باشم تا اینکه یک ساعت رفت‌وآمد کنم."),T("Ben","Then location is clearly your top priority.","پس موقعیت واضحاً اولویت اصلیته.")],1),D("phone","Comparing phones","store",["Amir","Ella"],[T("Amir","This model has a better camera, but it's two hundred dollars more.","این مدل دوربین بهتری داره، ولی دویست دلار گرون‌تره."),T("Ella","Do you actually need the better camera?","واقعاً به دوربین بهتر نیاز داری؟"),T("Amir","Probably not. Battery life matters more to me.","احتمالاً نه. عمر باتری برای من مهم‌تره."),T("Ella","Then the cheaper one seems like the better trade-off.","پس مدل ارزون‌تر بده‌بستان بهتریه.")],2),D("route","Choosing a commute","office",["Ravi","Mina"],[T("Ravi","The highway is faster when traffic is light.","بزرگراه وقتی ترافیک کمه سریع‌تره."),T("Mina","But the train is more reliable at rush hour.","ولی قطار در ساعت شلوغی قابل‌اعتمادتره."),T("Ravi","I'd rather know exactly when I'll arrive.","ترجیح می‌دم دقیق بدونم کی می‌رسم."),T("Mina","Same. Reliability beats speed for me.","منم همین‌طور. برای من قابل‌اعتماد بودن از سرعت مهم‌تره.")],3)],
"fill":["I'd rather ___ a little more for better quality.",["pay","paying","to pay","paid"],"pay"]
},
{
"slug":"b1-advice-decisions","file":"b1-advice-decisions-v1.json","topic":"requests","lessons":3,
"vocab":[V("advice","advice","توصیه"),V("option","option","گزینه"),V("consequence","consequence","پیامد"),V("recommend","recommend","پیشنهاد کردن","verb"),V("consider","consider","در نظر گرفتن","verb"),V("risk","risk","ریسک"),V("decision","decision","تصمیم"),V("regret","regret","پشیمان شدن","verb"),V("ought_to","ought to","بهتر است","modal_phrase"),V("if_i_were_you","if I were you","اگر جای تو بودم","phrase")],
"utterances":[U("ask","I'm not sure whether to accept the offer. What would you do?","مطمئن نیستم پیشنهاد رو قبول کنم یا نه. تو چی کار می‌کردی؟","ask_advice",["advice","option"],1),U("if","If I were you, I'd ask for a few more days before deciding.","اگر جای تو بودم، قبل از تصمیم چند روز بیشتر وقت می‌خواستم.","give_personal_advice",["if_i_were_you","decision"],1),U("ought","You ought to compare the long-term benefits, not just the salary.","بهتره مزایای بلندمدت رو مقایسه کنی، نه فقط حقوق رو.","give_advice",["ought_to","benefit"],1),U("consider","Have you considered how the change would affect your commute?","در نظر گرفتی این تغییر چه اثری روی رفت‌وآمدت می‌ذاره؟","raise_factor",["consider"],2),U("risk","The biggest risk is that the new role may involve much longer hours.","بزرگ‌ترین ریسک اینه که نقش جدید ممکنه ساعت کاری خیلی بیشتری داشته باشه.","identify_risk",["risk"],2),U("consequence","If you take the job, you'll probably have less free time at first.","اگر کار رو قبول کنی، احتمالاً اوایل وقت آزاد کمتری داری.","predict_consequence",["consequence"],2),U("recommend","My manager recommended talking to someone who already does the role.","مدیرم پیشنهاد کرد با کسی که همین نقش رو داره حرف بزنم.","report_recommendation",["recommend"],3),U("decision","I've decided to accept it because the learning opportunity matters more to me.","تصمیم گرفتم قبولش کنم چون فرصت یادگیری برای من مهم‌تره.","explain_decision",["decision"],3)],
"grammar":[G("should_ought","should / ought to","Use should or ought to for advice; ought to is slightly less common and can sound a little more formal.","برای توصیه از should یا ought to استفاده می‌کنیم؛ ought to کمی رسمی‌تر و کم‌کاربردتر است.",[("You should sleep on it.","بهتره یک شب روش فکر کنی."),("You ought to read the contract carefully.","بهتره قرارداد رو دقیق بخونی.")],1),G("if_i_were","If I were you…","Use If I were you, I'd… to give advice from another person's perspective.","برای توصیه از دید طرف مقابل از If I were you, I'd… استفاده می‌کنیم.",[("If I were you, I'd wait.","اگر جای تو بودم صبر می‌کردم."),("If I were you, I wouldn't rush the decision.","اگر جای تو بودم برای تصمیم عجله نمی‌کردم.")],2),G("conditional_result","First conditional for consequences","Use if + present and will/may/might to discuss likely consequences of a real future choice.","برای پیامدهای محتمل یک تصمیم واقعی آینده از if + present و will/may/might استفاده می‌کنیم.",[("If you move, you'll save time commuting.","اگر نقل مکان کنی، در رفت‌وآمد وقت ذخیره می‌کنی."),("If you wait too long, the offer might disappear.","اگر خیلی صبر کنی، ممکنه پیشنهاد از بین بره.")],3)],
"dialogues":[D("job","A job offer decision","park",["Maya","Leo"],[T("Maya","I got the job offer, but the commute is almost an hour.","پیشنهاد کار رو گرفتم، ولی رفت‌وآمد تقریباً یک ساعته."),T("Leo","What matters more to you: the role or the location?","برات کدوم مهم‌تره: خود نقش یا موقعیت؟"),T("Maya","The role is much better for my career.","خود نقش برای مسیر شغلیم خیلی بهتره."),T("Leo","Then I'd seriously consider accepting it, at least for a year.","پس من جدی قبول کردنش رو در نظر می‌گرفتم، حداقل برای یک سال.")],1),D("course","Choosing a course","library",["Hana","Noah"],[T("Hana","Should I take the intensive course or the evening course?","دوره فشرده رو بردارم یا دوره عصر؟"),T("Noah","If I were you, I'd choose the evening one.","اگر جای تو بودم دوره عصر رو انتخاب می‌کردم."),T("Hana","Why?","چرا؟"),T("Noah","You'll have more time to practice between classes.","بین کلاس‌ها وقت بیشتری برای تمرین داری.")],2),D("final","Explaining a decision","cafe",["Sofia","Omar"],[T("Sofia","So, did you decide about the apartment?","پس درباره آپارتمان تصمیم گرفتی؟"),T("Omar","Yes. I'm taking the smaller one near work.","آره. اون کوچیک‌تره نزدیک کار رو می‌گیرم."),T("Sofia","Even though it's more expensive?","با اینکه گرون‌تره؟"),T("Omar","Yes. I think I'll regret spending two hours commuting every day.","آره. فکر می‌کنم از روزی دو ساعت رفت‌وآمد پشیمون می‌شم.")],3)],
"fill":["If I ___ you, I'd ask for more time.",["were","was","am","be"],"were"]
}
]

def main():
    OUT.mkdir(parents=True,exist_ok=True); written=[]
    for spec in UNITS:
        p=OUT/spec["file"]; p.write_text(json.dumps(build(spec),ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); written.append(p.name)
    print(json.dumps({"written":len(written),"files":written},ensure_ascii=False,indent=2))
if __name__=="__main__": main()
