#!/usr/bin/env python3
from __future__ import annotations
import json
from scripts.generate_b1_batch import V,U,G,D,T,build,OUT

UNITS=[
{
"slug":"b1-local-experiences","file":"b1-local-experiences-v1.json","topic":"places-town","lessons":3,
"vocab":[V("recommend","recommend","پیشنهاد کردن","verb"),V("neighborhood","neighborhood","محله"),V("local","local","محلی","adjective"),V("touristy","touristy","خیلی توریستی","adjective"),V("reservation","reservation","رزرو"),V("walking_distance","walking distance","فاصله پیاده"),V("hidden_gem","hidden gem","جای کمترشناخته‌شده عالی"),V("crowded","crowded","شلوغ","adjective"),V("authentic","authentic","اصیل","adjective"),V("concierge","concierge","مسئول راهنمای مهمان")],
"utterances":[U("ask","Could you recommend somewhere local for dinner that isn't too touristy?","می‌شه یک جای محلی برای شام پیشنهاد بدید که خیلی توریستی نباشه؟","ask_local_recommendation",["recommend","local","touristy"],1,"polite"),U("distance","Is there anything interesting within walking distance of the hotel?","جای جالبی در فاصله پیاده از هتل هست؟","ask_nearby",["walking_distance"],1),U("gem","There's a small jazz club nearby that's a real hidden gem.","نزدیک اینجا یک کلاب جاز کوچیک هست که واقعاً جای فوق‌العاده‌ایه.","give_recommendation",["hidden_gem"],1),U("crowd","The market gets very crowded after noon, so I'd go early.","بازار بعد از ظهر خیلی شلوغ می‌شه، پس من زود می‌رفتم.","give_local_advice",["crowded"],2),U("authentic","If you want something more authentic, try the family-run restaurant on Oak Street.","اگر جای اصیل‌تری می‌خواید، رستوران خانوادگی خیابون اوک رو امتحان کنید.","recommend_authentic_place",["authentic"],2),U("booking","Do we need a reservation, or can we just walk in?","نیاز به رزرو داریم یا می‌تونیم همین‌طوری بریم؟","ask_booking_need",["reservation"],2),U("indirect","Do you know whether the museum is open late on Thursdays?","می‌دونید موزه پنجشنبه‌ها تا دیر وقت بازه یا نه؟","ask_indirect_question",["local"],3),U("choice","I'd rather explore one neighborhood properly than rush around the whole city.","ترجیح می‌دم یک محله رو درست بگردم تا اینکه کل شهر رو با عجله ببینم.","state_local_travel_preference",["neighborhood"],3)],
"grammar":[G("indirect_questions","Indirect questions","Use Do you know…? / Could you tell me…? with statement word order for polite information requests.","برای درخواست مؤدبانه اطلاعات از Do you know یا Could you tell me و ترتیب جمله خبری استفاده می‌کنیم.",[("Do you know where the station is?","می‌دونید ایستگاه کجاست؟"),("Could you tell me when the market closes?","می‌شه بگید بازار کی بسته می‌شه؟")],1),G("relative_places","Relative clauses for places","Use that/which/where to identify or describe places.","برای مشخص کردن یا توصیف مکان از that، which یا where استفاده می‌کنیم.",[("It's a cafe where locals meet after work.","کافه‌ایه که محلی‌ها بعد کار می‌رن."),("The museum that opened last year is free.","موزه‌ای که پارسال باز شد رایگانه.")],2),G("recommend_modals","Modals for recommendations","Use should, could, and I'd + base form to recommend with different strength.","برای پیشنهاد با شدت متفاوت از should، could و I'd استفاده می‌کنیم.",[("You should book ahead.","بهتره از قبل رزرو کنید."),("You could take the river walk.","می‌تونید مسیر کنار رودخونه رو برید.")],3)],
"dialogues":[D("hotel","Asking the concierge","hotel lobby",["Maya","Daniel"],[T("Maya","Could you recommend a local restaurant that isn't too touristy?","می‌شه یک رستوران محلی پیشنهاد بدید که خیلی توریستی نباشه؟"),T("Daniel","There's a family-run place two blocks away that's excellent.","دو بلوک اون‌طرف‌تر یک رستوران خانوادگی عالی هست."),T("Maya","Do we need a reservation?","رزرو لازم داریم؟"),T("Daniel","Tonight, yes. I can call them for you.","امشب آره. می‌تونم براتون تماس بگیرم.")],1),D("market","Planning a local morning","breakfast room",["Hana","Noah"],[T("Hana","I want to visit the market today.","امروز می‌خوام بازار رو ببینم."),T("Noah","Go before noon if you can. It gets packed later.","اگر می‌تونی قبل از ظهر برو. بعداً خیلی شلوغ می‌شه."),T("Hana","Anything else nearby?","جای دیگه‌ای نزدیکش هست؟"),T("Noah","There's a small museum across the square that's worth visiting.","آن طرف میدان یک موزه کوچک هست که ارزش دیدن داره.")],2),D("evening","Choosing an evening activity","hotel lounge",["Sofia","Omar"],[T("Sofia","Do you know if there's live music nearby tonight?","می‌دونی امشب نزدیک اینجا موسیقی زنده هست؟"),T("Omar","The hotel mentioned a small jazz club on Pine Street.","هتل یک کلاب جاز کوچیک در خیابون پاین گفت."),T("Sofia","Sounds better than another tourist attraction.","از یک جاذبه توریستی دیگه بهتر به نظر میاد."),T("Omar","Agreed. Let's try it after dinner.","موافقم. بعد شام امتحانش کنیم.")],3)],
"fill":["Could you tell me where the market ___?",["is","does","be","it is"],"is"]
},
{
"slug":"b1-work-responsibilities","file":"b1-work-responsibilities-v1.json","topic":"jobs","lessons":3,
"vocab":[V("responsibility","responsibility","مسئولیت"),V("deadline","deadline","مهلت"),V("priority","priority","اولویت"),V("progress","progress","پیشرفت"),V("task","task","وظیفه"),V("overdue","overdue","عقب‌افتاده","adjective"),V("coordinate","coordinate","هماهنگ کردن","verb"),V("complete","complete","تکمیل کردن","verb"),V("update","update","گزارش وضعیت"),V("workload","workload","حجم کار")],
"utterances":[U("role","My main responsibility is coordinating the weekly release with three different teams.","مسئولیت اصلی من هماهنگ کردن انتشار هفتگی با سه تیم مختلفه.","describe_responsibility",["responsibility","coordinate"],1),U("deadline","The report has to be finished by Thursday because the client reviews it Friday morning.","گزارش باید تا پنجشنبه تموم بشه چون مشتری جمعه صبح بررسیش می‌کنه.","explain_deadline",["deadline","complete"],1),U("priority","Right now, fixing the payment issue is our highest priority.","الان حل مشکل پرداخت بالاترین اولویت ماست.","state_priority",["priority"],1),U("progress","We've completed most of the testing, but two important cases are still open.","بیشتر تست‌ها رو تموم کردیم، ولی دو مورد مهم هنوز بازه.","give_progress_update",["progress","complete"],2),U("overdue","One task is overdue because we're waiting for data from another team.","یک کار عقب افتاده چون منتظر داده از تیم دیگه‌ایم.","explain_delay",["overdue","task"],2),U("workload","My workload is heavier this week, so I need to move one non-urgent task to next week.","حجم کارم این هفته بیشتره، پس باید یک کار غیرضروری رو بندازم هفته بعد.","manage_workload",["workload","task"],2),U("until","I'll keep working on the draft until the numbers are confirmed.","تا وقتی اعداد تأیید بشن روی پیش‌نویس کار می‌کنم.","state_work_until_condition",["update"],3),U("summary","By the end of today, I expect to have the first version ready for review.","تا آخر امروز انتظار دارم نسخه اول برای بررسی آماده باشه.","forecast_progress",["progress","deadline"],3)],
"grammar":[G("obligation_work","have to / need to for responsibilities","Use have to and need to for work obligations and required next steps.","برای الزام‌های کاری و قدم بعدی لازم از have to و need to استفاده می‌کنیم.",[("I have to submit it by Friday.","باید تا جمعه تحویلش بدم."),("We need to check the numbers again.","باید اعداد رو دوباره چک کنیم.")],1),G("perfect_progress","Present perfect for progress","Use present perfect for completed progress that matters to the current task.","برای پیشرفتی که انجام شده و به کار فعلی ربط دارد از present perfect استفاده می‌کنیم.",[("We've finished the first phase.","مرحله اول رو تموم کردیم."),("I haven't received the data yet.","هنوز داده رو نگرفتم.")],2),G("deadline_time","by / until","Use by for a deadline before or at a point; use until for an activity continuing up to a point.","برای مهلت از by و برای ادامه کار تا یک زمان از until استفاده می‌کنیم.",[("Finish it by Friday.","تا جمعه تمومش کن."),("I'll work until six.","تا شش کار می‌کنم.")],3)],
"dialogues":[D("update","Daily progress update","team call",["Amir","Ella"],[T("Ella","How's the testing going?","تست‌ها چطور پیش می‌ره؟"),T("Amir","We've finished most of it, but two cases are still open.","بیشترش تموم شده، ولی دو مورد هنوز بازه."),T("Ella","Will that affect Thursday's deadline?","روی مهلت پنجشنبه اثر می‌ذاره؟"),T("Amir","Not if we get the missing data today.","اگر امروز داده گمشده رو بگیریم نه.")],1),D("priority","Changing priorities","office",["Ravi","Mina"],[T("Ravi","I was going to finish the dashboard today.","قرار بود امروز داشبورد رو تموم کنم."),T("Mina","The payment issue is more urgent now.","الان مشکل پرداخت فوری‌تره."),T("Ravi","Should I move the dashboard to tomorrow?","داشبورد رو ببرم فردا؟"),T("Mina","Yes. Fixing payments is the top priority.","آره. حل پرداخت‌ها اولویت اصلیه.")],2),D("deadline","Planning around a deadline","meeting",["Chloe","Adam"],[T("Chloe","The client needs the draft by Monday morning.","مشتری تا دوشنبه صبح پیش‌نویس رو می‌خواد."),T("Adam","Then I need the final numbers by Friday afternoon.","پس من تا جمعه بعدازظهر اعداد نهایی رو لازم دارم."),T("Chloe","I'll follow up with finance today.","امروز با مالی پیگیری می‌کنم."),T("Adam","Great. I'll keep the document ready until then.","عالیه. تا اون موقع سند رو آماده نگه می‌دارم.")],3)],
"fill":["The report has to be finished ___ Thursday.",["by","until","since","during"],"by"]
},
{
"slug":"b1-meetings-teamwork","file":"b1-meetings-teamwork-v1.json","topic":"jobs","lessons":3,
"vocab":[V("agenda","agenda","دستور جلسه"),V("update","update","گزارش وضعیت"),V("suggestion","suggestion","پیشنهاد"),V("action_point","action point","کار بعدی مشخص"),V("owner","owner","مسئول کار"),V("follow_up","follow-up","پیگیری"),V("concern","concern","نگرانی"),V("clarify","clarify","شفاف کردن","verb"),V("decision","decision","تصمیم"),V("contribute","contribute","مشارکت کردن","verb")],
"utterances":[U("agenda","Before we start, can we quickly review today's agenda?","قبل شروع می‌شه سریع دستور جلسه امروز رو مرور کنیم؟","open_meeting",["agenda"],1),U("update","Here's a quick update: the design is finished, but development is two days behind.","یک گزارش کوتاه: طراحی تموم شده، ولی توسعه دو روز عقبه.","give_meeting_update",["update"],1),U("concern","My main concern is that we don't have enough time for final testing.","نگرانی اصلی من اینه که برای تست نهایی وقت کافی نداریم.","raise_concern",["concern"],1),U("suggestion","How about moving one developer from the reporting feature to testing for two days?","چطوره یک توسعه‌دهنده رو برای دو روز از بخش گزارش به تست منتقل کنیم؟","make_suggestion",["suggestion"],2),U("clarify","Just to clarify, are we changing the launch date or only the testing plan?","فقط برای شفاف شدن، تاریخ لانچ رو عوض می‌کنیم یا فقط برنامه تست رو؟","clarify_meeting_point",["clarify"],2),U("decision","So we've agreed to keep the launch date and add extra testing support.","پس توافق کردیم تاریخ لانچ حفظ بشه و کمک اضافه برای تست بدیم.","summarize_decision",["decision"],2),U("action","The first action point is for me to update the testing schedule by this afternoon.","اولین کار بعدی برای منه که تا بعدازظهر برنامه تست رو به‌روز کنم.","assign_action",["action_point","owner"],3),U("follow","I'll follow up tomorrow and confirm whether the extra support is available.","فردا پیگیری می‌کنم و تأیید می‌کنم کمک اضافه موجوده یا نه.","commit_followup",["follow_up"],3)],
"grammar":[G("suggestions_meeting","Meeting suggestion forms","Use how about + -ing, we could, and I'd suggest + -ing to contribute ideas naturally.","برای پیشنهاد در جلسه از how about + ing، we could و I'd suggest + ing استفاده می‌کنیم.",[("How about moving the deadline?","چطوره مهلت رو جابه‌جا کنیم؟"),("I'd suggest testing this first.","پیشنهاد می‌کنم اول این رو تست کنیم.")],1),G("reported_points","Reporting meeting points","Use said that / mentioned that / explained that to relay another person's point.","برای انتقال نکته‌های دیگران در جلسه از said that، mentioned that و explained that استفاده می‌کنیم.",[("Maya said that the client had approved it.","مایا گفت مشتری تأیید کرده."),("Leo mentioned that testing was delayed.","لئو گفت تست عقب افتاده.")],2),G("conditional_planning","Conditionals for team planning","Use if + present with will/can/could to explore practical team consequences.","برای بررسی پیامدهای عملی برنامه تیم از if + present همراه will/can/could استفاده می‌کنیم.",[("If we add one person, we can finish Friday.","اگر یک نفر اضافه کنیم، جمعه تموم می‌کنیم."),("If we delay testing, the launch could be risky.","اگر تست رو عقب بندازیم، لانچ می‌تونه ریسکی باشه.")],3)],
"dialogues":[D("status","Weekly team meeting","meeting room",["Maya","Leo"],[T("Maya","Let's start with a quick progress update.","با یک گزارش کوتاه پیشرفت شروع کنیم."),T("Leo","Development is almost done, but testing hasn't started yet.","توسعه تقریباً تمومه، ولی تست هنوز شروع نشده."),T("Maya","Is that likely to affect the launch?","احتمالاً روی لانچ اثر می‌ذاره؟"),T("Leo","Only if we find a major issue this week.","فقط اگر این هفته مشکل بزرگی پیدا کنیم.")],1),D("suggest","Solving a staffing issue","meeting",["Hana","Noah"],[T("Hana","We don't have enough testers for Friday.","برای جمعه تستر کافی نداریم."),T("Noah","How about borrowing someone from the support team for two days?","چطوره دو روز از تیم پشتیبانی یک نفر بگیریم؟"),T("Hana","That could work if their manager agrees.","اگر مدیرشون موافق باشه می‌تونه جواب بده."),T("Noah","I'll ask after this meeting.","بعد جلسه می‌پرسم.")],2),D("actions","Closing a meeting","video call",["Sofia","Omar"],[T("Sofia","Before we finish, let's confirm the action points.","قبل پایان کارهای بعدی رو تأیید کنیم."),T("Omar","I'll update the schedule and contact support.","من برنامه رو به‌روز می‌کنم و با پشتیبانی تماس می‌گیرم."),T("Sofia","And I'll send the client the revised timeline.","و من زمان‌بندی جدید رو برای مشتری می‌فرستم."),T("Omar","Great. Let's follow up tomorrow afternoon.","عالیه. فردا بعدازظهر پیگیری کنیم.")],3)],
"fill":["How about ___ one developer to testing?",["moving","move","to move","moved"],"moving"]
},
{
"slug":"b1-job-search","file":"b1-job-search-v1.json","topic":"jobs","lessons":3,
"vocab":[V("vacancy","vacancy","فرصت شغلی"),V("qualification","qualification","صلاحیت / مدرک"),V("experience","experience","تجربه"),V("responsibility","responsibility","مسئولیت"),V("achievement","achievement","دستاورد"),V("strength","strength","نقطه قوت"),V("candidate","candidate","متقاضی"),V("interview","interview","مصاحبه"),V("apply","apply","درخواست دادن","verb"),V("requirement","requirement","شرط / نیازمندی")],
"utterances":[U("vacancy","I found a vacancy that matches most of my experience, although I don't meet every requirement.","یک فرصت شغلی پیدا کردم که با بیشتر تجربه‌م جور درمیاد، با اینکه همه شرایط رو ندارم.","evaluate_vacancy",["vacancy","experience","requirement"],1),U("apply","I've applied for three roles this month, but this is the one I'm most interested in.","این ماه برای سه نقش درخواست دادم، ولی این یکی بیشتر از همه برام جذابه.","describe_job_search",["apply"],1),U("experience","I've worked in customer support for four years and led a small team for the last year.","چهار سال در پشتیبانی مشتری کار کردم و یک سال اخیر یک تیم کوچک رو هدایت کردم.","describe_experience",["experience","responsibility"],1),U("achievement","One achievement I'm proud of is reducing response time by about twenty percent.","یکی از دستاوردهایی که بهش افتخار می‌کنم کم کردن زمان پاسخ حدود بیست درصده.","describe_achievement",["achievement"],2),U("strength","My main strength is staying calm and organized when several problems happen at once.","نقطه قوت اصلی من آروم و منظم موندن وقتی چند مشکل هم‌زمان پیش میاد است.","describe_strength",["strength"],2),U("relative","I'm looking for a role where I can take on more responsibility.","دنبال نقشی هستم که بتونم مسئولیت بیشتری بگیرم.","state_career_goal",["responsibility"],2),U("interview","Could you tell me more about what success looks like in the first six months?","می‌شه بیشتر توضیح بدید موفقیت در شش ماه اول چه شکلیه؟","ask_interview_question",["interview"],3,"polite"),U("fit","I think my experience fits the role because I've handled similar projects independently.","فکر می‌کنم تجربه‌م با نقش جور درمیاد چون پروژه‌های مشابه رو مستقل مدیریت کردم.","explain_fit",["candidate","experience"],3)],
"grammar":[G("perfect_experience","Present perfect for experience","Use present perfect to summarize experience up to now, then past simple for finished examples.","برای خلاصه تجربه تا حال از present perfect و برای مثال تمام‌شده از past simple استفاده می‌کنیم.",[("I've worked in support for four years.","چهار ساله در پشتیبانی کار می‌کنم."),("I led a migration last year.","پارسال یک مهاجرت رو هدایت کردم.")],1),G("relative_jobs","Relative clauses in job talk","Use who/that/where to define people, roles, or workplaces.","برای مشخص کردن افراد، نقش‌ها یا محیط کار از who/that/where استفاده می‌کنیم.",[("I want a role where I can grow.","نقشی می‌خوام که بتونم رشد کنم."),("We need someone who can work independently.","کسی می‌خوایم که مستقل کار کنه.")],2),G("interview_examples","Structured interview examples","Use situation + action + result language to make examples clear and relevant.","برای مثال مصاحبه از ساختار موقعیت + اقدام + نتیجه استفاده می‌کنیم.",[("We had a delay, so I reorganized the schedule and we finished on time.","تأخیر داشتیم، پس برنامه رو تغییر دادم و به موقع تموم کردیم."),("A client complained; I listened, fixed the issue, and they renewed.","مشتری شکایت کرد؛ گوش دادم، مشکل رو حل کردم و تمدید کرد.")],3)],
"dialogues":[D("vacancy","Discussing a job ad","cafe",["Lina","Ben"],[T("Lina","This vacancy looks interesting, but I don't have all the listed qualifications.","این فرصت جالبه، ولی همه شرایط نوشته‌شده رو ندارم."),T("Ben","Do you meet the main requirements?","شرایط اصلی رو داری؟"),T("Lina","Yes, and I have four years of related experience.","آره، و چهار سال تجربه مرتبط دارم."),T("Ben","Then I'd apply. Job ads often describe the ideal candidate.","پس درخواست می‌دادم. آگهی‌ها معمولاً متقاضی ایده‌آل رو توصیف می‌کنند.")],1),D("interview","Interview experience question","interview room",["Amir","Claire"],[T("Claire","Could you tell me about your current responsibilities?","می‌تونید درباره مسئولیت‌های فعلیتون بگید؟"),T("Amir","I coordinate customer support for two product teams and train new staff.","پشتیبانی مشتری دو تیم محصول رو هماهنگ می‌کنم و نیروی جدید آموزش می‌دم."),T("Claire","What's an achievement you're particularly proud of?","به کدوم دستاوردتون بیشتر افتخار می‌کنید؟"),T("Amir","Last year I helped reduce our response time by twenty percent.","پارسال کمک کردم زمان پاسخ‌مون بیست درصد کم بشه.")],2),D("questions","Candidate questions","interview room",["Ravi","Priya"],[T("Ravi","I have one question about the first few months in the role.","یک سؤال درباره ماه‌های اول نقش دارم."),T("Priya","Of course.","حتماً."),T("Ravi","What would you expect the successful candidate to achieve in the first six months?","انتظار دارید متقاضی موفق در شش ماه اول به چه چیزی برسه؟"),T("Priya","The main goal would be taking ownership of two client accounts.","هدف اصلی گرفتن مسئولیت دو حساب مشتریه.")],3)],
"fill":["I've worked in customer support ___ four years.",["for","since","ago","during"],"for"]
},
{
"slug":"b1-study-strategies","file":"b1-study-strategies-v1.json","topic":"school-study","lessons":3,
"vocab":[V("strategy","strategy","روش / راهبرد"),V("focus","focus","تمرکز"),V("review","review","مرور کردن","verb"),V("memorize","memorize","حفظ کردن","verb"),V("deadline","deadline","مهلت"),V("procrastinate","procrastinate","کار را عقب انداختن","verb"),V("feedback","feedback","بازخورد"),V("effective","effective","موثر","adjective"),V("practice","practice","تمرین"),V("improve","improve","بهبود دادن","verb")],
"utterances":[U("strategy","The most effective strategy for me is reviewing new material in short sessions over several days.","موثرترین روش برای من مرور مطالب جدید در جلسه‌های کوتاه طی چند روزه.","describe_study_strategy",["strategy","review","effective"],1),U("memorize","I stopped trying to memorize whole pages and started testing myself instead.","دیگه سعی نکردم صفحه‌های کامل رو حفظ کنم و به جاش خودم رو امتحان کردم.","describe_strategy_change",["memorize","practice"],1),U("focus","I focus better when I study somewhere without notifications or background noise.","وقتی جایی بدون اعلان و صدای پس‌زمینه درس می‌خونم تمرکز بهتری دارم.","describe_focus_condition",["focus"],1),U("procrastinate","If I leave a big task until the deadline, I usually end up rushing it.","اگر یک کار بزرگ رو تا مهلت آخر بذارم، معمولاً آخرش با عجله انجامش می‌دم.","describe_procrastination_result",["procrastinate","deadline"],2),U("breakdown","Breaking a project into smaller tasks makes it easier to start.","تقسیم پروژه به کارهای کوچک‌تر شروع کردن رو راحت‌تر می‌کنه.","recommend_strategy",["strategy"],2),U("feedback","I improve faster when I get specific feedback instead of just a score.","وقتی بازخورد مشخص می‌گیرم به‌جای فقط نمره، سریع‌تر پیشرفت می‌کنم.","describe_feedback_value",["feedback","improve"],2),U("conditional","If I review these notes tonight, I'll feel much more prepared tomorrow.","اگر امشب این یادداشت‌ها رو مرور کنم، فردا خیلی آماده‌ترم.","plan_study_action",["review"],3),U("evaluate","A study method is only effective if you can use it consistently.","یک روش مطالعه فقط وقتی موثره که بتونی مداوم ازش استفاده کنی.","evaluate_strategy",["effective","strategy"],3)],
"grammar":[G("gerund_inf_study","Gerunds and infinitives in study talk","Learn common patterns such as avoid doing, keep doing, decide to do, and plan to do.","الگوهای رایج مثل avoid doing، keep doing، decide to do و plan to do را به شکل ترکیب یاد می‌گیریم.",[("I avoid studying late at night.","از شب‌دیر درس خوندن پرهیز می‌کنم."),("I plan to review tomorrow.","قصد دارم فردا مرور کنم.")],1),G("advice_study","Advice language","Use should, ought to, try + -ing, and it might help to for practical study advice.","برای توصیه مطالعه از should، ought to، try + ing و it might help to استفاده می‌کنیم.",[("Try testing yourself.","خودت رو امتحان کن."),("It might help to study in shorter sessions.","شاید کمک کنه در جلسه‌های کوتاه‌تر درس بخونی.")],2),G("conditional_study","First conditional for study results","Use if + present and will/can to connect a realistic study action to a future result.","برای وصل کردن اقدام مطالعه واقعی به نتیجه آینده از شرط نوع اول استفاده می‌کنیم.",[("If you review regularly, you'll remember more.","اگر منظم مرور کنی، بیشتر یادت می‌مونه."),("If I start now, I can finish before dinner.","اگر الان شروع کنم، قبل شام تموم می‌کنم.")],3)],
"dialogues":[D("revision","Changing a revision strategy","library",["Maya","Leo"],[T("Maya","I keep rereading my notes, but I don't remember much later.","مدام یادداشت‌هام رو دوباره می‌خونم، ولی بعداً زیاد یادم نمی‌مونه."),T("Leo","Have you tried testing yourself without looking at them?","سعی کردی بدون نگاه کردن خودت رو امتحان کنی؟"),T("Maya","Not really.","نه واقعاً."),T("Leo","It might feel harder, but it usually shows what you actually know.","ممکنه سخت‌تر حس بشه، ولی معمولاً نشون می‌ده واقعاً چی بلدی.")],1),D("deadline","Avoiding procrastination","study room",["Hana","Noah"],[T("Hana","I have a paper due Friday and I haven't started.","جمعه مقاله تحویل دارم و هنوز شروع نکردم."),T("Noah","Break it into three smaller tasks and do the first one tonight.","به سه کار کوچک تقسیمش کن و اولی رو امشب انجام بده."),T("Hana","That sounds less overwhelming.","این کمتر ترسناک به نظر میاد."),T("Noah","Exactly. Starting is usually the hardest part.","دقیقاً. شروع کردن معمولاً سخت‌ترین قسمته.")],2),D("feedback","Using feedback","campus cafe",["Sofia","Omar"],[T("Sofia","My teacher said my ideas are good, but my structure is unclear.","معلم گفت ایده‌هام خوبه، ولی ساختارم واضح نیست."),T("Omar","That's useful feedback. What are you going to change?","بازخورد مفیدیه. چی رو می‌خوای عوض کنی؟"),T("Sofia","I'm going to outline each paragraph before I write it.","قبل نوشتن هر پاراگراف طرحش رو می‌نویسم."),T("Omar","If you do that consistently, your writing should improve quickly.","اگر مداوم این کار رو بکنی، نوشتنت باید سریع بهتر بشه.")],3)],
"fill":["I avoid ___ until the last minute.",["waiting","wait","to wait","waited"],"waiting"]
}
]

def main():
    OUT.mkdir(parents=True,exist_ok=True); w=[]
    for s in UNITS:
        p=OUT/s["file"]; p.write_text(json.dumps(build(s),ensure_ascii=False,indent=2)+"\n",encoding="utf-8"); w.append(p.name)
    print(json.dumps({"written":len(w),"files":w},ensure_ascii=False,indent=2))
if __name__=="__main__": main()
