#!/usr/bin/env python3
"""Generate the approved English A2 production batches for curriculum units 17-36.

The content specs below are hand-authored. This script only converts them into the
canonical batch-v2 structure so the 20 remaining units stay structurally consistent.
"""
from __future__ import annotations

try:
    from scripts.english_content_enrichment import enrich_batch
except ModuleNotFoundError:
    from english_content_enrichment import enrich_batch

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "content" / "production" / "en" / "A2"


def V(key, en, fa, pos="noun"):
    return {"key": key, "en": en, "fa": fa, "pos": pos}


def U(key, en, fa, intent, refs, lesson=1, register="neutral"):
    return {"key": key, "en": en, "fa": fa, "intent": intent, "refs": refs, "lesson": lesson, "register": register}


def G(key, title, rule, fa, examples, lesson=1):
    return {"key": key, "title": title, "rule": rule, "fa": fa, "examples": examples, "lesson": lesson}


def D(key, title, setting, chars, turns, lesson=1):
    return {"key": key, "title": title, "setting": setting, "chars": chars, "turns": turns, "lesson": lesson}


def T(speaker, en, fa):
    return {"speaker": speaker, "en": en, "fa": fa}


UNITS = [
{
"slug":"a2-compare-products","file":"a2-compare-products-v1.json","topic":"shopping","lessons":3,
"vocab":[V("cheaper","cheaper","ارزان‌تر","adjective"),V("lighter","lighter","سبک‌تر","adjective"),V("durable","durable","بادوام","adjective"),V("battery","battery","باتری"),V("screen","screen","صفحه‌نمایش"),V("model","model","مدل")],
"utterances":[U("cheaper","This model is cheaper than the other one.","این مدل از آن یکی ارزان‌تر است.","compare_price",["cheaper","model"],1),U("lighter","Which one is lighter?","کدام یکی سبک‌تر است؟","compare_weight",["lighter"],1),U("battery","The blue one has a better battery.","مدل آبی باتری بهتری دارد.","compare_feature",["battery"],2),U("screen","This screen is bigger, but that one is brighter.","این صفحه بزرگ‌تر است، ولی آن یکی روشن‌تر است.","compare_features",["screen"],2),U("prefer","I prefer the smaller one because it's easier to carry.","مدل کوچک‌تر را ترجیح می‌دهم چون حملش راحت‌تر است.","state_preference",["model"],3),U("durable","The more expensive one looks more durable.","مدل گران‌تر بادوام‌تر به نظر می‌رسد.","compare_quality",["durable"],3)],
"grammar":[G("comparatives","Comparatives with than","Use comparative forms plus than to compare two things.","برای مقایسه دو چیز از صفت تفضیلی همراه than استفاده می‌کنیم.",[("This phone is cheaper than that one.","این گوشی از آن یکی ارزان‌تر است."),("The tablet is more useful than the old model.","تبلت از مدل قدیمی کاربردی‌تر است.")],1),G("one_ones","one / ones","Use one or ones to avoid repeating a countable noun.","برای تکرار نکردن اسم قابل‌شمارش از one یا ones استفاده می‌کنیم.",[("I like the black one.","مدل مشکی را دوست دارم."),("The smaller ones are cheaper.","مدل‌های کوچک‌تر ارزان‌ترند.")],2)],
"dialogues":[D("headphones","Choosing headphones","electronics store",["Maya","Leo"],[T("Maya","These headphones are cheaper.","این هدفون‌ها ارزان‌ترند."),T("Leo","Yes, but the other ones have a better battery.","بله، ولی آن یکی‌ها باتری بهتری دارند."),T("Maya","Which pair is lighter?","کدام جفت سبک‌تر است؟"),T("Leo","The black ones. I think they're the better choice.","مدل‌های مشکی. فکر می‌کنم انتخاب بهتری هستند.")],1),D("laptop","Comparing two laptops","computer shop",["Hana","Noah"],[T("Hana","This laptop has a bigger screen.","این لپ‌تاپ صفحه بزرگ‌تری دارد."),T("Noah","True, but the smaller one is lighter.","درسته، ولی مدل کوچک‌تر سبک‌تره."),T("Hana","I travel a lot, so I prefer the lighter one.","من زیاد سفر می‌کنم، پس مدل سبک‌تر را ترجیح می‌دهم."),T("Noah","That makes sense.","منطقیه.")],3)],
"fill":["This model is ___ than the other one.",["cheaper","cheap","cheapest","more cheap"],"cheaper"],
},
{
"slug":"a2-best-choice","file":"a2-best-choice-v1.json","topic":"prices","lessons":2,
"vocab":[V("best","best","بهترین","adjective"),V("easiest","easiest","آسان‌ترین","adjective"),V("useful","useful","کاربردی","adjective"),V("option","option","گزینه"),V("recommend","recommend","پیشنهاد کردن","verb"),V("value","value","ارزش خرید")],
"utterances":[U("best","This is the best option for a small kitchen.","این بهترین گزینه برای یک آشپزخانه کوچک است.","recommend_option",["best","option"],1),U("easiest","Which app is the easiest to use?","کار کردن با کدام اپ از همه آسان‌تر است؟","ask_superlative",["easiest"],1),U("value","The middle one is the best value for the price.","مدل وسط نسبت به قیمتش بهترین ارزش خرید را دارد.","evaluate_value",["value"],1),U("recommend","I'd recommend the one with the longer battery life.","مدلی را پیشنهاد می‌کنم که باتری بیشتری دوام می‌آورد.","recommend",["recommend"],2),U("useful","For me, the most useful feature is offline mode.","برای من کاربردی‌ترین قابلیت حالت آفلاین است.","state_best_feature",["useful"],2)],
"grammar":[G("superlatives","Superlatives","Use the + superlative to compare one item with a group.","برای مقایسه یک مورد با کل گروه از the + صفت عالی استفاده می‌کنیم.",[("This is the cheapest option.","این ارزان‌ترین گزینه است."),("That route is the most convenient.","آن مسیر راحت‌ترین است.")],1),G("one_with","the one with ...","Use the one with + noun phrase to identify an option by a feature.","برای مشخص کردن یک گزینه با ویژگی‌اش از the one with استفاده می‌کنیم.",[("Choose the one with the larger screen.","مدلی را انتخاب کن که صفحه بزرگ‌تری دارد."),("I prefer the one with free delivery.","مدلی را ترجیح می‌دهم که ارسال رایگان دارد.")],2)],
"dialogues":[D("coffee_maker","Choosing a coffee maker","home store",["Sofia","Omar"],[T("Sofia","Which one is the easiest to clean?","تمیز کردن کدام یکی از همه آسان‌تر است؟"),T("Omar","This small one is the easiest.","این مدل کوچک از همه آسان‌تره."),T("Sofia","Is it also the cheapest?","ارزان‌ترین هم هست؟"),T("Omar","No, but I think it's the best value.","نه، ولی فکر می‌کنم بهترین ارزش خرید رو داره.")],1),D("plan","Recommending a plan","phone shop",["Lina","Ben"],[T("Lina","Which plan would you recommend?","کدام طرح را پیشنهاد می‌کنی؟"),T("Ben","The one with unlimited messages.","مدلی که پیام نامحدود دارد."),T("Lina","Why that one?","چرا آن یکی؟"),T("Ben","It's the most useful for your needs.","برای نیازهای تو کاربردی‌ترینه.")],2)],
"fill":["This is the ___ option for me.",["best","better","good","most good"],"best"],
},
{
"slug":"a2-trip-planning","file":"a2-trip-planning-v1.json","topic":"transport","lessons":3,
"vocab":[V("destination","destination","مقصد"),V("book","book","رزرو کردن","verb"),V("budget","budget","بودجه"),V("flight","flight","پرواز"),V("stay","stay","اقامت کردن","verb"),V("prefer","prefer","ترجیح دادن","verb")],
"utterances":[U("destination","Where would you like to go this summer?","دوست داری این تابستان کجا بروی؟","discuss_destination",["destination"],1),U("budget","We have a budget of about five hundred dollars.","حدود پانصد دلار بودجه داریم.","state_budget",["budget"],1),U("flight","The morning flight is cheaper than the evening one.","پرواز صبح از پرواز عصر ارزان‌تر است.","compare_flights",["flight"],2),U("book","Let's book the hotel before prices go up.","بیا قبل از بالا رفتن قیمت‌ها هتل را رزرو کنیم.","suggest_booking",["book"],2),U("stay","We're going to stay for three nights.","قرار است سه شب بمانیم.","state_trip_length",["stay"],3),U("prefer","I'd prefer to travel by train if it's not too expensive.","اگر خیلی گران نباشد ترجیح می‌دهم با قطار سفر کنم.","state_travel_preference",["prefer"],3)],
"grammar":[G("would_like","would like for preferences","Use would like to talk politely about a desired plan.","برای بیان مؤدبانه چیزی که دوست داریم انجام دهیم از would like استفاده می‌کنیم.",[("I'd like to visit Chicago.","دوست دارم شیکاگو را ببینم."),("Where would you like to stay?","دوست داری کجا اقامت داشته باشی؟")],1),G("going_to","going to for trip plans","Use be going to for intentions and planned actions.","برای قصدها و برنامه‌های سفر از be going to استفاده می‌کنیم.",[("We're going to stay for two nights.","قرار است دو شب بمانیم."),("I'm going to book the tickets tonight.","قرار است امشب بلیت‌ها را رزرو کنم.")],3)],
"dialogues":[D("weekend","Planning a weekend trip","cafe",["Amir","Ella"],[T("Amir","Where would you like to go next month?","دوست داری ماه بعد کجا بریم؟"),T("Ella","I'd like to go somewhere near the mountains.","دوست دارم جایی نزدیک کوه‌ها بریم."),T("Amir","Should we drive or take the train?","با ماشین بریم یا قطار؟"),T("Ella","Let's compare the prices first.","اول قیمت‌ها رو مقایسه کنیم.")],1),D("booking","Booking the plan","living room",["Ravi","Mina"],[T("Ravi","The morning flight is forty dollars cheaper.","پرواز صبح چهل دلار ارزان‌تره."),T("Mina","Great. Let's book that one.","عالیه. همون رو رزرو کنیم."),T("Ravi","How long are we going to stay?","چند روز قرار است بمانیم؟"),T("Mina","Three nights should be enough.","سه شب باید کافی باشه.")],3)],
"fill":["We're going to ___ for three nights.",["stay","stays","stayed","staying"],"stay"],
},
{
"slug":"a2-tickets-timetables","file":"a2-tickets-timetables-v1.json","topic":"transport","lessons":3,
"vocab":[V("platform","platform","سکو"),V("departure","departure","حرکت / زمان حرکت"),V("arrival","arrival","رسیدن / زمان رسیدن"),V("round_trip","round trip","رفت‌وبرگشت","noun_phrase"),V("single","one-way ticket","بلیت یک‌طرفه","noun_phrase"),V("schedule","schedule","برنامه زمانی")],
"utterances":[U("platform","Which platform does the train leave from?","قطار از کدام سکو حرکت می‌کند؟","ask_platform",["platform"],1),U("departure","The next departure is at 10:25.","حرکت بعدی ساعت ۱۰:۲۵ است.","state_departure",["departure"],1),U("arrival","What time does it arrive in Boston?","چه ساعتی به بوستون می‌رسد؟","ask_arrival",["arrival"],2),U("round","I'd like a round-trip ticket to New York, please.","یک بلیت رفت‌وبرگشت به نیویورک می‌خواهم، لطفاً.","buy_ticket",["round_trip"],2,"polite"),U("one_way","Is a one-way ticket cheaper?","بلیت یک‌طرفه ارزان‌تر است؟","compare_ticket",["single"],2),U("schedule","According to the schedule, the bus leaves every thirty minutes.","طبق برنامه، اتوبوس هر سی دقیقه حرکت می‌کند.","read_schedule",["schedule"],3)],
"grammar":[G("leave_arrive","leave / arrive + time and place","Use leave and arrive with appropriate time and place expressions.","برای زمان حرکت و رسیدن از leave و arrive همراه عبارت‌های زمان و مکان استفاده می‌کنیم.",[("The train leaves at nine.","قطار ساعت نه حرکت می‌کند."),("It arrives in Boston at eleven.","ساعت یازده به بوستون می‌رسد.")],1),G("ticket_language","one-way and round-trip tickets","Use one-way for a ticket in one direction and round trip for going and returning.","برای بلیت فقط رفت از one-way و برای رفت‌وبرگشت از round trip استفاده می‌کنیم.",[("A one-way ticket, please.","یک بلیت یک‌طرفه لطفاً."),("Two round-trip tickets to Miami.","دو بلیت رفت‌وبرگشت به میامی.")],2)],
"dialogues":[D("station","At the train station","train station",["Nia","Tom"],[T("Nia","Excuse me, which platform is for the 9:40 train?","ببخشید، قطار ۹:۴۰ از کدام سکوست؟"),T("Tom","Platform six.","سکوی شش."),T("Nia","What time does it arrive downtown?","چه ساعتی به مرکز شهر می‌رسد؟"),T("Tom","At 10:15, if it's on time.","اگر سر وقت باشه، ساعت ۱۰:۱۵.")],1),D("ticket_counter","At the ticket counter","ticket office",["Chloe","Yusuf"],[T("Chloe","I'd like a round-trip ticket to Portland, please.","یک بلیت رفت‌وبرگشت به پورتلند می‌خواهم لطفاً."),T("Yusuf","When are you coming back?","کی برمی‌گردید؟"),T("Chloe","Sunday evening.","یکشنبه عصر."),T("Yusuf","Okay. The return train leaves at 6:20.","باشه. قطار برگشت ساعت ۶:۲۰ حرکت می‌کند.")],2)],
"fill":["The train ___ at 10:25.",["leaves","leave","leaving","left"],"leaves"],
},
{
"slug":"a2-accommodation","file":"a2-accommodation-v1.json","topic":"places-town","lessons":3,
"vocab":[V("reservation","reservation","رزرو"),V("check_in","check in","پذیرش شدن / ورود به هتل","phrasal_verb"),V("key_card","key card","کارت اتاق","noun_phrase"),V("breakfast","breakfast","صبحانه"),V("wifi","Wi-Fi","وای‌فای"),V("checkout","check-out","تحویل اتاق")],
"utterances":[U("reservation","I have a reservation under the name Rahimi.","یک رزرو به نام رحیمی دارم.","state_reservation",["reservation"],1),U("checkin","What time can we check in?","چه ساعتی می‌توانیم اتاق را تحویل بگیریم؟","ask_checkin",["check_in"],1),U("wifi","Is Wi-Fi included in the room price?","وای‌فای در قیمت اتاق حساب شده؟","ask_facility",["wifi"],2),U("breakfast","What time is breakfast served?","صبحانه چه ساعتی سرو می‌شود؟","ask_breakfast",["breakfast"],2),U("key","My key card isn't working.","کارت اتاقم کار نمی‌کند.","report_problem",["key_card"],3),U("checkout","Could I have a late check-out?","می‌شود اتاق را دیرتر تحویل بدهم؟","make_request",["checkout"],3,"polite")],
"grammar":[G("is_there","Is there / Are there","Use Is there or Are there to ask about hotel facilities.","برای پرسیدن درباره امکانات محل اقامت از Is there یا Are there استفاده می‌کنیم.",[("Is there a gym?","باشگاه ورزشی هست؟"),("Are there any rooms with a balcony?","اتاقی با بالکن هست؟")],2),G("could_i","Could I ...? for polite requests","Use Could I ...? to make a polite request at a hotel.","برای درخواست مؤدبانه در هتل از Could I ...? استفاده می‌کنیم.",[("Could I get another towel?","می‌شود یک حوله دیگر بگیرم؟"),("Could I check out later?","می‌شود دیرتر اتاق را تحویل بدهم؟")],3)],
"dialogues":[D("checkin","Hotel check-in","hotel reception",["Priya","Daniel"],[T("Priya","Hi, I have a reservation under Patel.","سلام، یک رزرو به نام پاتل دارم."),T("Daniel","Yes, I found it. May I see your ID?","بله، پیداش کردم. می‌توانم کارت شناسایی‌تان را ببینم؟"),T("Priya","Sure. Is breakfast included?","حتماً. صبحانه شامل می‌شود؟"),T("Daniel","Yes, from seven to ten.","بله، از هفت تا ده.")],1),D("problem","A room request","hotel reception",["Fatima","Marco"],[T("Fatima","My key card isn't working.","کارت اتاقم کار نمی‌کند."),T("Marco","I'm sorry. I'll make you a new one.","متأسفم. یک کارت جدید براتون می‌سازم."),T("Fatima","Thanks. Could I also get an extra towel?","ممنون. می‌شود یک حوله اضافه هم بگیرم؟"),T("Marco","Of course.","حتماً.")],3)],
"fill":["I have a ___ under the name Rahimi.",["reservation","platform","schedule","receipt"],"reservation"],
},
{
"slug":"a2-travel-problems","file":"a2-travel-problems-v1.json","topic":"transport","lessons":3,
"vocab":[V("delayed","delayed","با تأخیر","adjective"),V("miss","miss","از دست دادن","verb"),V("connection","connection","وسیله بعدی / اتصال سفر"),V("lost","lost","گم‌شده","adjective"),V("route","route","مسیر"),V("help_desk","help desk","بخش راهنمایی","noun_phrase")],
"utterances":[U("delay","My flight is delayed by two hours.","پروازم دو ساعت تأخیر دارد.","report_delay",["delayed"],1),U("miss","I missed my connection because the first train was late.","به قطار بعدی نرسیدم چون قطار اول دیر کرد.","explain_missed_connection",["miss","connection"],1),U("lost","I think I left my bag on the bus.","فکر کنم کیفم را داخل اتوبوس جا گذاشتم.","report_lost_item",["lost"],2),U("route","I got on the wrong train. How do I get back to this route?","سوار قطار اشتباهی شدم. چطور به این مسیر برگردم؟","ask_route_help",["route"],2),U("desk","You should ask at the help desk near gate twelve.","بهتره از بخش راهنمایی نزدیک گیت دوازده بپرسی.","give_travel_advice",["help_desk"],3),U("have_to","Do I have to buy a new ticket?","باید بلیت جدید بخرم؟","ask_requirement",["connection"],3)],
"grammar":[G("should","should for solutions","Use should to suggest a sensible next step.","برای پیشنهاد یک کار مناسب از should استفاده می‌کنیم.",[("You should talk to the agent.","بهتره با مسئول صحبت کنی."),("You should keep your receipt.","بهتره رسیدت را نگه داری.")],3),G("have_to","have to for requirements","Use have to for something that is necessary.","برای کاری که انجامش لازم است از have to استفاده می‌کنیم.",[("I have to change trains.","باید قطار عوض کنم."),("Do we have to pay again?","باید دوباره پول بدهیم؟")],3)],
"dialogues":[D("connection","A missed connection","airport service desk",["Dina","Adam"],[T("Dina","My first flight was late, and I missed my connection.","پرواز اولم دیر بود و به پرواز بعدی نرسیدم."),T("Adam","Let me check the next available flight.","بذارید پرواز بعدی موجود رو چک کنم."),T("Dina","Do I have to pay for a new ticket?","باید برای بلیت جدید پول بدم؟"),T("Adam","No, we'll move you to the next flight.","نه، شما را به پرواز بعدی منتقل می‌کنیم.")],1),D("lost_bag","A lost bag","bus terminal",["Roya","Sam"],[T("Roya","I think I left my bag on bus 24.","فکر کنم کیفم رو اتوبوس ۲۴ جا گذاشتم."),T("Sam","When did you get off the bus?","کی از اتوبوس پیاده شدی؟"),T("Roya","About twenty minutes ago.","حدود بیست دقیقه پیش."),T("Sam","You should report it at the help desk.","بهتره در بخش راهنمایی گزارشش بدی.")],2)],
"fill":["My flight is ___ by two hours.",["delayed","delay","delaying","later"],"delayed"],
},
{
"slug":"a2-detailed-directions","file":"a2-detailed-directions-v1.json","topic":"directions","lessons":3,
"vocab":[V("intersection","intersection","تقاطع"),V("block","block","بلوک / یک فاصله شهری"),V("across","across from","روبروی","preposition"),V("past","past","از کنار / بعد از","preposition"),V("until","until","تا","preposition"),V("transfer","transfer","عوض کردن خط","verb")],
"utterances":[U("blocks","Go straight for two blocks.","دو بلوک مستقیم برو.","give_direction",["block"],1),U("intersection","Turn right at the second intersection.","در دومین تقاطع به راست بپیچ.","give_turn",["intersection"],1),U("across","The pharmacy is across from the library.","داروخانه روبروی کتابخانه است.","locate_place",["across"],2),U("past","Walk past the bank and you'll see the station.","از بانک رد شو و ایستگاه را می‌بینی.","give_landmark_direction",["past"],2),U("until","Stay on this bus until Central Square.","تا میدان مرکزی داخل همین اتوبوس بمان.","give_transit_direction",["until"],3),U("transfer","Transfer to the green line at Park Street.","در پارک استریت به خط سبز عوض کن.","give_transfer",["transfer"],3)],
"grammar":[G("imperatives","Imperatives for directions","Use the base verb to give clear step-by-step directions.","برای دادن مسیر مرحله‌به‌مرحله از شکل پایه فعل به‌صورت امری استفاده می‌کنیم.",[("Turn left at the light.","سر چراغ به چپ بپیچ."),("Walk past the cafe.","از کافه رد شو.")],1),G("until_past_across","until, past, across from","Use these location words to connect directions to landmarks and endpoints.","از until، past و across from برای وصل کردن مسیر به نشانه‌های مکانی و مقصد استفاده می‌کنیم.",[("Keep going until you reach the bridge.","تا پل برو."),("It's across from the bank.","روبروی بانک است.")],2)],
"dialogues":[D("museum","Finding the museum","street corner",["Ava","Jon"],[T("Ava","Excuse me, how do I get to the city museum?","ببخشید، چطور به موزه شهر برسم؟"),T("Jon","Go straight for two blocks, then turn left at the intersection.","دو بلوک مستقیم برو، بعد در تقاطع به چپ بپیچ."),T("Ava","Is it far from there?","از آنجا دوره؟"),T("Jon","No. It's across from the public library.","نه. روبروی کتابخانه عمومی است.")],1),D("subway","Using the subway","subway entrance",["Yuki","Owen"],[T("Yuki","Can I take this line to Harbor Station?","می‌تونم با این خط به ایستگاه هاربر برم؟"),T("Owen","Not directly. Stay on until Park Street.","مستقیم نه. تا پارک استریت ادامه بده."),T("Yuki","Then what?","بعدش چی؟"),T("Owen","Transfer to the green line.","به خط سبز عوض کن.")],3)],
"fill":["The pharmacy is ___ from the library.",["across","until","past","between to"],"across"],
},
{
"slug":"a2-work-duties","file":"a2-work-duties-v1.json","topic":"jobs","lessons":3,
"vocab":[V("shift","shift","شیفت"),V("customer","customer","مشتری"),V("report","report","گزارش"),V("uniform","uniform","لباس فرم"),V("schedule","schedule","برنامه کاری"),V("responsibility","responsibility","مسئولیت")],
"utterances":[U("shift","My morning shift starts at seven.","شیفت صبح من ساعت هفت شروع می‌شود.","describe_schedule",["shift"],1),U("customers","I usually help customers at the front desk.","معمولاً در میز پذیرش به مشتری‌ها کمک می‌کنم.","describe_duty",["customer"],1),U("report","I have to send the report before I leave.","قبل از رفتن باید گزارش را بفرستم.","state_requirement",["report"],2),U("uniform","We have to wear a uniform on weekdays.","روزهای کاری باید لباس فرم بپوشیم.","state_rule",["uniform"],2),U("dont","You don't have to work on Sunday.","لازم نیست یکشنبه کار کنی.","state_no_requirement",["schedule"],3),U("responsibility","One of my responsibilities is checking orders.","یکی از مسئولیت‌های من بررسی سفارش‌هاست.","describe_responsibility",["responsibility"],3)],
"grammar":[G("have_to","have to / don't have to","Use have to for a requirement and don't have to when something is not necessary.","برای الزام از have to و برای کاری که لازم نیست از don't have to استفاده می‌کنیم.",[("I have to arrive by eight.","باید تا هشت برسم."),("You don't have to wear a tie.","لازم نیست کراوات بزنی.")],2),G("can_rules","can / can't at work","Use can and can't for permission or workplace rules.","برای اجازه یا محدودیت‌های محیط کار از can و can't استفاده می‌کنیم.",[("You can take your break now.","الان می‌تونی استراحت کنی."),("Staff can't use this door.","کارکنان نمی‌توانند از این در استفاده کنند.")],3)],
"dialogues":[D("first_day","A first day at work","office",["Mei","David"],[T("Mei","What time does my shift start tomorrow?","شیفتم فردا چه ساعتی شروع می‌شه؟"),T("David","At eight. Please arrive ten minutes early.","ساعت هشت. لطفاً ده دقیقه زودتر برس."),T("Mei","Do I have to wear a uniform?","باید لباس فرم بپوشم؟"),T("David","No, but you have to wear your ID badge.","نه، ولی باید کارت شناسایی‌ات را داشته باشی.")],1),D("duties","Talking about duties","break room",["Iris","Theo"],[T("Iris","What do you usually do in the afternoon?","معمولاً بعدازظهرها چه کار می‌کنی؟"),T("Theo","I check orders and answer customer emails.","سفارش‌ها را بررسی می‌کنم و ایمیل مشتری‌ها را جواب می‌دهم."),T("Iris","Do you have to write reports too?","باید گزارش هم بنویسی؟"),T("Theo","Only on Fridays.","فقط جمعه‌ها.")],3)],
"fill":["We ___ wear a uniform on weekdays.",["have to","has to","having to","have"],"have to"],
},
{
"slug":"a2-study-habits","file":"a2-study-habits-v1.json","topic":"school-study","lessons":3,
"vocab":[V("deadline","deadline","مهلت"),V("review","review","مرور کردن","verb"),V("notes","notes","یادداشت‌ها"),V("concentrate","concentrate","تمرکز کردن","verb"),V("practice","practice","تمرین کردن","verb"),V("improve","improve","بهبود دادن","verb")],
"utterances":[U("review","I review my notes after every class.","بعد از هر کلاس یادداشت‌هایم را مرور می‌کنم.","describe_study_habit",["review","notes"],1),U("deadline","The project deadline is next Thursday.","مهلت پروژه پنجشنبه بعد است.","state_deadline",["deadline"],1),U("concentrate","I can't concentrate when my phone is next to me.","وقتی گوشی کنارم است نمی‌توانم تمرکز کنم.","describe_difficulty",["concentrate"],2),U("practice","You should practice speaking for ten minutes every day.","بهتره هر روز ده دقیقه مکالمه تمرین کنی.","give_study_advice",["practice"],2),U("need","I need to finish this chapter tonight.","باید امشب این فصل را تمام کنم.","state_need",["deadline"],3),U("improve","What can I do to improve my listening?","برای بهتر کردن شنیدارم چه کار می‌توانم بکنم؟","ask_advice",["improve"],3)],
"grammar":[G("should","should for study advice","Use should to give a helpful suggestion.","برای پیشنهاد مفید در مورد درس خواندن از should استفاده می‌کنیم.",[("You should review your notes.","بهتره یادداشت‌هایت را مرور کنی."),("You should take short breaks.","بهتره استراحت‌های کوتاه داشته باشی.")],2),G("need_to","need to","Use need to when an action is necessary for a goal or deadline.","وقتی انجام کاری برای هدف یا مهلت لازم است از need to استفاده می‌کنیم.",[("I need to study tonight.","باید امشب درس بخونم."),("She needs to submit the form tomorrow.","او باید فردا فرم را تحویل بدهد.")],3)],
"dialogues":[D("exam","Preparing for an exam","library",["Noura","Luca"],[T("Noura","I have an exam on Monday, but I can't concentrate.","دوشنبه امتحان دارم ولی نمی‌تونم تمرکز کنم."),T("Luca","You should put your phone away for thirty minutes.","بهتره سی دقیقه گوشیت رو کنار بذاری."),T("Noura","Good idea. I also need to review my notes.","فکر خوبیه. باید یادداشت‌هام رو هم مرور کنم."),T("Luca","Start with the hardest chapter.","از سخت‌ترین فصل شروع کن.")],2),D("speaking","Improving speaking","classroom",["Ari","Paul"],[T("Ari","How can I improve my speaking?","چطور می‌تونم مکالمه‌ام رو بهتر کنم؟"),T("Paul","Try to practice a little every day.","سعی کن هر روز کمی تمرین کنی."),T("Ari","Should I record myself?","بهتره صدای خودم رو ضبط کنم؟"),T("Paul","Yes. That can help a lot.","بله. خیلی می‌تونه کمک کنه.")],3)],
"fill":["You ___ practice speaking every day.",["should","should to","shoulds","are should"],"should"],
},
{
"slug":"a2-abilities-skills","file":"a2-abilities-skills-v1.json","topic":"common-actions","lessons":2,
"vocab":[V("skill","skill","مهارت"),V("repair","repair","تعمیر کردن","verb"),V("type","type","تایپ کردن","verb"),V("swim","swim","شنا کردن","verb"),V("learn","learn","یاد گرفتن","verb"),V("well","well","خوب","adverb")],
"utterances":[U("type","I can type pretty quickly now.","الان می‌تونم نسبتاً سریع تایپ کنم.","describe_present_ability",["type"],1),U("repair","My brother can repair bicycles.","برادرم می‌تونه دوچرخه تعمیر کنه.","describe_ability",["repair"],1),U("could","I couldn't swim when I was six.","وقتی شش سالم بود نمی‌تونستم شنا کنم.","describe_past_inability",["swim"],1),U("learn","I'm learning to use a new design program.","دارم کار با یک برنامه طراحی جدید رو یاد می‌گیرم.","describe_learning",["learn"],2),U("well","She can speak English well, but she wants to get better.","او می‌تواند خوب انگلیسی صحبت کند، ولی می‌خواهد بهتر شود.","describe_skill_level",["well"],2)],
"grammar":[G("can_could","can and could for ability","Use can for present ability and could for general ability in the past.","برای توانایی حال از can و برای توانایی کلی در گذشته از could استفاده می‌کنیم.",[("I can drive.","می‌تونم رانندگی کنم."),("I could read when I was five.","وقتی پنج سالم بود می‌تونستم بخونم.")],1),G("well_better","well and better","Use well to describe how someone does an action; better is the comparative form.","برای گفتن اینکه کسی کاری را چگونه انجام می‌دهد از well و برای مقایسه از better استفاده می‌کنیم.",[("She sings well.","او خوب آواز می‌خونه."),("He cooks better than I do.","او از من بهتر آشپزی می‌کنه.")],2)],
"dialogues":[D("skills","Talking about skills","community center",["Sora","Jack"],[T("Sora","Can you fix a bike?","می‌تونی دوچرخه تعمیر کنی؟"),T("Jack","A little. I can change a tire, but that's about it.","یه کم. می‌تونم لاستیک عوض کنم، ولی تقریباً همین."),T("Sora","That's more than I can do.","همین هم بیشتر از چیزیه که من بلدم."),T("Jack","I learned from my dad.","از پدرم یاد گرفتم.")],1),D("past","Skills then and now","office",["Kate","Jae"],[T("Kate","Could you use spreadsheets before this job?","قبل از این کار بلد بودی با صفحه‌گسترده کار کنی؟"),T("Jae","Not very well.","نه خیلی خوب."),T("Kate","You're much faster now.","الان خیلی سریع‌تر شدی."),T("Jae","I've practiced a lot.","خیلی تمرین کردم.")],2)],
"fill":["I ___ swim when I was six.",["couldn't","can't","don't can","wasn't can"],"couldn't"],
},
{
"slug":"a2-symptoms-pharmacy","file":"a2-symptoms-pharmacy-v1.json","topic":"basic-health","lessons":3,
"vocab":[V("cough","cough","سرفه"),V("sore_throat","sore throat","گلودرد","noun_phrase"),V("fever","fever","تب"),V("medicine","medicine","دارو"),V("dose","dose","دوز"),V("rest","rest","استراحت","noun")],
"utterances":[U("cough","I've had a bad cough since yesterday.","از دیروز سرفه شدیدی دارم.","describe_symptom",["cough"],1),U("throat","I have a sore throat and a slight fever.","گلودرد و کمی تب دارم.","describe_symptoms",["sore_throat","fever"],1),U("medicine","Do you have something for a cough?","چیزی برای سرفه دارید؟","ask_pharmacy_help",["medicine","cough"],2,"polite"),U("dose","How often should I take this medicine?","این دارو را هر چند وقت یک‌بار باید بخورم؟","ask_dosage",["dose","medicine"],2),U("rest","You should drink plenty of water and get some rest.","بهتره آب زیاد بخوری و کمی استراحت کنی.","give_health_advice",["rest"],3),U("warning","If the fever gets worse, you should see a doctor.","اگر تب بدتر شد، بهتره دکتر بری.","give_warning",["fever"],3)],
"grammar":[G("have_symptom","have + symptom","Use have with common symptom nouns such as a cough, a fever, or a sore throat.","برای بیان علائم رایج از have همراه اسم علامت استفاده می‌کنیم.",[("I have a headache.","سردرد دارم."),("She has a fever.","او تب دارد.")],1),G("should_health","should for basic health advice","Use should to give simple non-emergency advice.","برای توصیه ساده و روزمره سلامتی از should استفاده می‌کنیم.",[("You should rest.","بهتره استراحت کنی."),("You should talk to a doctor if it gets worse.","اگر بدتر شد بهتره با دکتر صحبت کنی.")],3)],
"dialogues":[D("pharmacy","At the pharmacy","pharmacy",["Zoe","Drake"],[T("Zoe","Hi. Do you have something for a sore throat?","سلام. چیزی برای گلودرد دارید؟"),T("Drake","Do you have a fever too?","تب هم دارید؟"),T("Zoe","A little, but mostly my throat hurts.","یه کم، ولی بیشتر گلو درد دارم."),T("Drake","This may help. Follow the directions on the label.","این ممکنه کمک کنه. دستور روی برچسب رو دنبال کنید.")],2),D("dose","Medicine instructions","pharmacy counter",["Rita","Emre"],[T("Rita","How often should I take this?","هر چند وقت یک‌بار باید این رو مصرف کنم؟"),T("Emre","One dose every eight hours.","هر هشت ساعت یک دوز."),T("Rita","Should I take it with food?","بهتره همراه غذا بخورم؟"),T("Emre","Yes, and drink plenty of water.","بله، و آب زیاد بنوشید.")],3)],
"fill":["I have a sore ___ .",["throat","medicine","dose","rest"],"throat"],
},
{
"slug":"a2-appointments-advice","file":"a2-appointments-advice-v1.json","topic":"basic-health","lessons":2,
"vocab":[V("appointment","appointment","وقت ملاقات"),V("available","available","خالی / در دسترس","adjective"),V("reschedule","reschedule","تغییر زمان دادن","verb"),V("dentist","dentist","دندان‌پزشک"),V("urgent","urgent","فوری","adjective"),V("advice","advice","توصیه")],
"utterances":[U("appointment","I'd like to make an appointment for this week.","می‌خواهم برای این هفته وقت بگیرم.","make_appointment",["appointment"],1,"polite"),U("available","Is the dentist available on Friday morning?","دندان‌پزشک جمعه صبح وقت خالی دارد؟","ask_availability",["dentist","available"],1),U("reschedule","I need to reschedule my appointment.","باید زمان وقتم را عوض کنم.","reschedule",["reschedule","appointment"],1),U("urgent","It's not urgent, but I'd like to come in soon.","فوری نیست، ولی دوست دارم زود بیام.","describe_urgency",["urgent"],2),U("advice","You should avoid very cold drinks today.","بهتره امروز نوشیدنی خیلی سرد نخوری.","give_advice",["advice"],2)],
"grammar":[G("should_shouldnt","should / shouldn't","Use should and shouldn't for everyday advice.","برای توصیه مثبت و منفی از should و shouldn't استفاده می‌کنیم.",[("You should rest today.","بهتره امروز استراحت کنی."),("You shouldn't drive if you feel dizzy.","اگر سرگیجه داری بهتره رانندگی نکنی.")],2),G("time_expressions","Appointment time expressions","Use on for days and dates and at for exact times.","برای روز و تاریخ از on و برای ساعت دقیق از at استفاده می‌کنیم.",[("On Tuesday at three.","سه‌شنبه ساعت سه."),("My appointment is on May 12.","وقتم دوازدهم می است.")],1)],
"dialogues":[D("make","Making an appointment","clinic phone call",["Hana","Daniel"],[T("Hana","Hi, I'd like to make an appointment with Dr. Lee.","سلام، می‌خواهم با دکتر لی وقت بگیرم."),T("Daniel","She's available Thursday afternoon or Friday morning.","پنجشنبه بعدازظهر یا جمعه صبح وقت دارد."),T("Hana","Friday morning works better for me.","جمعه صبح برای من بهتره."),T("Daniel","How about 9:30?","ساعت ۹:۳۰ چطوره؟")],1),D("change","Changing an appointment","clinic phone call",["Noor","David"],[T("Noor","I need to reschedule my appointment tomorrow.","باید وقت فردام رو عوض کنم."),T("David","No problem. Is next Monday okay?","مشکلی نیست. دوشنبه بعد خوبه؟"),T("Noor","Yes. Do I have to come at the same time?","بله. باید همان ساعت بیام؟"),T("David","No, we also have an afternoon time available.","نه، بعدازظهر هم وقت خالی داریم.")],2)],
"fill":["I need to ___ my appointment.",["reschedule","available","urgent","dentist"],"reschedule"],
},
{
"slug":"a2-personality-appearance","file":"a2-personality-appearance-v1.json","topic":"people","lessons":3,
"vocab":[V("friendly","friendly","خوش‌برخورد","adjective"),V("patient","patient","صبور","adjective"),V("quiet","quiet","کم‌حرف / آرام","adjective"),V("curly","curly hair","موی فر","noun_phrase"),V("beard","beard","ریش"),V("tall","tall","قدبلند","adjective")],
"utterances":[U("looks","What does your new manager look like?","مدیر جدیدت چه شکلیه؟","ask_appearance",["tall"],1),U("tall","He's tall and has short curly hair.","قدبلنده و موهای کوتاه و فر داره.","describe_appearance",["tall","curly"],1),U("beard","The man with the beard is my uncle.","مرد ریش‌دار عموی من است.","identify_person",["beard"],1),U("like","What's she like?","اخلاقش چطوره؟","ask_personality",["friendly"],2),U("friendly","She's friendly and very patient with new people.","خوش‌برخورد است و با آدم‌های جدید خیلی صبوره.","describe_personality",["friendly","patient"],2),U("quiet","I'm quieter than my sister, but she's more patient than me.","من از خواهرم کم‌حرف‌ترم، ولی او از من صبورتره.","compare_personality",["quiet","patient"],3)],
"grammar":[G("look_like","look like vs be like","Use What does ... look like? for appearance and What's ... like? for personality or general character.","برای ظاهر از What does ... look like? و برای شخصیت از What's ... like? استفاده می‌کنیم.",[("What does he look like?","ظاهرش چطوره؟"),("What's he like?","اخلاقش چطوره؟")],1),G("person_comparatives","Comparing people","Use comparative adjectives to compare appearance or personality.","برای مقایسه ظاهر یا شخصیت افراد از صفت تفضیلی استفاده می‌کنیم.",[("She's taller than me.","از من قدبلندتره."),("He's more patient than his brother.","از برادرش صبورتره.")],3)],
"dialogues":[D("manager","The new manager","office kitchen",["Claire","Jonas"],[T("Claire","Have you met our new manager?","مدیر جدیدمون رو دیدی؟"),T("Jonas","Not yet. What does she look like?","هنوز نه. چه شکلیه؟"),T("Claire","She's tall, with curly dark hair.","قدبلنده و موهای تیره و فر داره."),T("Jonas","What's she like?","اخلاقش چطوره؟"),T("Claire","Very friendly and patient.","خیلی خوش‌برخورد و صبوره.")],1),D("siblings","Comparing siblings","family dinner",["Lena","Lucas"],[T("Lena","You and your brother look very different.","تو و برادرت خیلی متفاوت به نظر می‌رسید."),T("Lucas","Yeah. He's taller and has a beard.","آره. اون قدبلندتره و ریش داره."),T("Lena","Are you similar in personality?","از نظر شخصیت شبیهید؟"),T("Lucas","A little. I'm quieter, but we're both friendly.","یه کم. من کم‌حرف‌ترم، ولی هر دومون خوش‌برخوردیم.")],3)],
"fill":["What's she ___? She's friendly and patient.",["like","look","looks","liking"],"like"],
},
{
"slug":"a2-describe-places","file":"a2-describe-places-v1.json","topic":"places-town","lessons":3,
"vocab":[V("crowded","crowded","شلوغ","adjective"),V("peaceful","peaceful","آرام","adjective"),V("historic","historic","تاریخی","adjective"),V("modern","modern","مدرن","adjective"),V("convenient","convenient","راحت / مناسب","adjective"),V("view","view","منظره")],
"utterances":[U("crowded","Downtown is lively, but it gets very crowded at night.","مرکز شهر پرجنب‌وجوشه، ولی شب‌ها خیلی شلوغ می‌شه.","describe_place",["crowded"],1),U("peaceful","The neighborhood is quieter and more peaceful than the city center.","این محله از مرکز شهر ساکت‌تر و آرام‌تره.","compare_places",["peaceful"],1),U("historic","The old town has several historic buildings.","بافت قدیمی چند ساختمان تاریخی دارد.","describe_feature",["historic"],2),U("modern","The new part of the city is more modern.","بخش جدید شهر مدرن‌تره.","compare_area",["modern"],2),U("convenient","Living near the subway is more convenient for me.","زندگی نزدیک مترو برای من راحت‌تره.","state_place_preference",["convenient"],3),U("view","The best thing about the apartment is the view of the river.","بهترین چیز آپارتمان منظره رودخانه است.","describe_best_feature",["view"],3)],
"grammar":[G("place_comparatives","Comparatives for places","Use comparatives to explain differences between familiar places.","برای توضیح تفاوت بین مکان‌ها از صفت تفضیلی استفاده می‌کنیم.",[("This area is quieter than downtown.","این منطقه از مرکز شهر ساکت‌تره."),("The subway is more convenient here.","مترو اینجا در دسترس‌تره.")],1),G("place_superlatives","Superlatives for place features","Use superlatives to identify the strongest feature in a group.","برای مشخص کردن برجسته‌ترین ویژگی بین چند گزینه از صفت عالی استفاده می‌کنیم.",[("It's the busiest street in town.","شلوغ‌ترین خیابان شهره."),("This park has the best view.","این پارک بهترین منظره رو داره.")],3)],
"dialogues":[D("neighborhoods","Choosing a neighborhood","apartment search",["Maya","Rami"],[T("Maya","Do you like the Riverside area?","منطقه ریورساید رو دوست داری؟"),T("Rami","Yes. It's more peaceful than downtown.","آره. از مرکز شهر آرام‌تره."),T("Maya","But downtown is more convenient for work.","ولی مرکز شهر برای کار راحت‌تره."),T("Rami","True. It depends on what matters most to you.","درسته. بستگی داره چی برات مهم‌تره.")],1),D("visit","A place to visit","tourist information desk",["Sofia","Marco"],[T("Sofia","What's the most interesting part of the city?","جالب‌ترین بخش شهر کجاست؟"),T("Marco","The old town, if you like historic buildings.","اگر ساختمان تاریخی دوست دارید، بافت قدیمی."),T("Sofia","Is it crowded?","شلوغه؟"),T("Marco","On weekends, yes. Weekday mornings are much quieter.","آخر هفته‌ها بله. صبح روزهای کاری خیلی خلوت‌تره.")],3)],
"fill":["This neighborhood is more ___ than downtown.",["peaceful","peacefully","most peaceful","peace"],"peaceful"],
},
{
"slug":"a2-experiences","file":"a2-experiences-v1.json","topic":"hobbies","lessons":3,
"vocab":[V("ever","ever","تا حالا","adverb"),V("never","never","هرگز","adverb"),V("abroad","abroad","خارج از کشور","adverb"),V("try","try","امتحان کردن","verb"),V("ride","ride","سوار شدن","verb"),V("experience","experience","تجربه")],
"utterances":[U("ever","Have you ever traveled abroad?","تا حالا به خارج از کشور سفر کردی؟","ask_experience",["ever","abroad"],1),U("never","I've never been to Canada.","هیچ‌وقت کانادا نرفتم.","state_no_experience",["never"],1),U("try","Have you ever tried Korean food?","تا حالا غذای کره‌ای امتحان کردی؟","ask_experience",["ever","try"],2),U("detail","Yes, I tried it last year in Seattle.","بله، پارسال در سیاتل امتحانش کردم.","give_past_detail",["try"],2),U("ride","I've ridden a horse once, but it was a long time ago.","یک بار اسب‌سواری کردم، ولی خیلی وقت پیش بود.","state_experience",["ride"],3),U("best","That was one of my favorite travel experiences.","آن یکی از تجربه‌های سفر موردعلاقه‌ام بود.","evaluate_experience",["experience"],3)],
"grammar":[G("present_perfect","Present perfect for life experience","Use have/has + past participle to ask or state whether an experience has happened at any time up to now.","برای پرسیدن یا گفتن تجربه‌های زندگی تا زمان حال از have/has + قسمت سوم فعل استفاده می‌کنیم.",[("Have you ever seen snow?","تا حالا برف دیدی؟"),("I've never flown alone.","هیچ‌وقت تنها پرواز نکردم.")],1),G("past_followup","Past simple for details","After mentioning an experience, use past simple to ask or give details about a finished time.","بعد از اشاره به تجربه، برای جزئیات مربوط به زمان تمام‌شده از گذشته ساده استفاده می‌کنیم.",[("When did you go?","کی رفتی؟"),("I went in 2024.","سال ۲۰۲۴ رفتم.")],2)],
"dialogues":[D("travel","Travel experiences","lunch break",["Amir","Ella"],[T("Amir","Have you ever traveled abroad alone?","تا حالا تنها به خارج از کشور سفر کردی؟"),T("Ella","Yes, once.","بله، یک بار."),T("Amir","Where did you go?","کجا رفتی؟"),T("Ella","I went to Mexico City two years ago.","دو سال پیش مکزیکوسیتی رفتم.")],1),D("food","Trying something new","restaurant",["Nia","Yusuf"],[T("Nia","Have you ever tried this dish?","تا حالا این غذا رو امتحان کردی؟"),T("Yusuf","No, never. Is it spicy?","نه، هیچ‌وقت. تنده؟"),T("Nia","A little. I had it here last month.","یه کم. ماه پیش همین‌جا خوردمش."),T("Yusuf","Okay, I'll try it.","باشه، امتحانش می‌کنم.")],2)],
"fill":["Have you ___ traveled abroad?",["ever","never","yet to","did"],"ever"],
},
{
"slug":"a2-phone-messages","file":"a2-phone-messages-v1.json","topic":"simple-messages","lessons":3,
"vocab":[V("voicemail","voicemail","پیام صوتی"),V("message","message","پیام"),V("call_back","call back","تماس برگشتی گرفتن","phrasal_verb"),V("hold","hold","پشت خط ماندن","verb"),V("line","line","خط تلفن"),V("spell","spell","هجی کردن","verb")],
"utterances":[U("hold","Could you hold for a moment, please?","ممکنه یک لحظه پشت خط بمونید؟","ask_hold",["hold"],1,"polite"),U("line","The line is bad. Could you say that again?","خط خوب نیست. می‌شه دوباره بگید؟","handle_bad_connection",["line"],1,"polite"),U("message","Can I leave a message for Ms. Carter?","می‌تونم برای خانم کارتر پیام بذارم؟","leave_message",["message"],2,"polite"),U("callback","Please ask him to call me back after four.","لطفاً ازش بخواهید بعد از چهار با من تماس بگیره.","request_callback",["call_back"],2),U("spell","Could you spell your last name for me?","ممکنه نام خانوادگی‌تون رو برام هجی کنید؟","confirm_detail",["spell"],3,"polite"),U("voicemail","I left you a voicemail this morning.","امروز صبح برات پیام صوتی گذاشتم.","refer_to_message",["voicemail"],3)],
"grammar":[G("could_phone","Could you ...? on the phone","Use Could you ...? for polite requests during a call.","برای درخواست مؤدبانه در تماس تلفنی از Could you ...? استفاده می‌کنیم.",[("Could you repeat that?","می‌شه دوباره بگید؟"),("Could you hold for a moment?","می‌شه یک لحظه پشت خط بمونید؟")],1),G("object_pronouns","Object pronouns in messages","Use me, him, her, us, and them after verbs and prepositions.","بعد از فعل‌ها و حروف اضافه از ضمیرهای مفعولی مثل me، him و her استفاده می‌کنیم.",[("Please call me back.","لطفاً دوباره با من تماس بگیرید."),("Can you give her the message?","می‌تونی پیام رو بهش بدی؟")],2)],
"dialogues":[D("office","Taking a message","office phone",["Rosa","Daniel"],[T("Rosa","Hello, could I speak to Mr. Green?","سلام، می‌تونم با آقای گرین صحبت کنم؟"),T("Daniel","I'm sorry, he's in a meeting.","متأسفم، جلسه است."),T("Rosa","Can I leave a message?","می‌تونم پیام بذارم؟"),T("Daniel","Of course. What's your name?","حتماً. اسمتون چیه؟")],2),D("connection","A difficult phone connection","phone call",["Lina","Tom"],[T("Lina","Hello? Tom? The line is really bad.","الو؟ تام؟ خط خیلی بده."),T("Tom","I can hear you now.","الان صدات رو می‌شنوم."),T("Lina","Could you say the address again?","می‌شه آدرس رو دوباره بگی؟"),T("Tom","Sure. It's 214 Pine Street.","حتماً. ۲۱۴ پاین استریت.")],1)],
"fill":["Please ask him to call me ___.",["back","again to","returning","behind"],"back"],
},
{
"slug":"a2-online-communication","file":"a2-online-communication-v1.json","topic":"simple-messages","lessons":2,
"vocab":[V("confirm","confirm","تأیید کردن","verb"),V("update","update","به‌روزرسانی / خبر جدید"),V("attachment","attachment","فایل پیوست"),V("link","link","لینک"),V("reply","reply","پاسخ دادن","verb"),V("send","send","فرستادن","verb")],
"utterances":[U("confirm","Just confirming our meeting for 3 p.m. tomorrow.","فقط دارم جلسه فردا ساعت سه رو تأیید می‌کنم.","confirm_plan",["confirm"],1),U("attachment","I've attached the file you asked for.","فایلی که خواسته بودی رو پیوست کردم.","send_attachment",["attachment"],1),U("link","Here's the link to the form.","این هم لینک فرم.","share_link",["link"],1),U("update","Quick update: the class starts thirty minutes later today.","یک خبر سریع: کلاس امروز سی دقیقه دیرتر شروع می‌شه.","send_update",["update"],2),U("reply","Sorry for the late reply. I was at work.","ببخشید دیر جواب دادم. سر کار بودم.","explain_late_reply",["reply"],2),U("send","I'll send you the address when I get home.","وقتی برسم خونه آدرس رو برات می‌فرستم.","promise_message",["send"],2)],
"grammar":[G("tense_review","Tense choice in practical messages","Use present for current facts, past for completed reasons, and future forms for later actions.","در پیام‌های کاربردی برای وضعیت فعلی از حال، برای دلیل تمام‌شده از گذشته و برای کار بعدی از آینده استفاده می‌کنیم.",[("I'm at the station now.","الان ایستگاهم."),("I'll send the link tonight.","امشب لینک رو می‌فرستم.")],2),G("linkers","Short linking words","Use and, but, so, and because to make short messages clearer.","برای وصل کردن اطلاعات کوتاه در پیام از and، but، so و because استفاده می‌کنیم.",[("I'm late because the bus stopped.","دیرم شده چون اتوبوس توقف کرد."),("The cafe is full, so let's meet outside.","کافه پره، پس بیرون همدیگه رو ببینیم.")],2)],
"dialogues":[D("group","A group chat update","group chat",["Ivy","Sam"],[T("Ivy","Quick update: the meeting room changed.","یک خبر سریع: اتاق جلسه عوض شد."),T("Sam","Thanks. Which room is it now?","ممنون. الان کدام اتاقه؟"),T("Ivy","Room 204. I'll send the map link too.","اتاق ۲۰۴. لینک نقشه رو هم می‌فرستم."),T("Sam","Perfect. See you there.","عالیه. اونجا می‌بینمت.")],1),D("file","Sending a file","direct message",["Mei","Owen"],[T("Mei","Did you get my email?","ایمیلم رو گرفتی؟"),T("Owen","Yes, but I don't see the attachment.","بله، ولی فایل پیوست رو نمی‌بینم."),T("Mei","Sorry! I'll send it again now.","ببخشید! الان دوباره می‌فرستمش."),T("Owen","No problem. Thanks.","مشکلی نیست. ممنون.")],2)],
"fill":["I've ___ the file you asked for.",["attached","attach","attaching","attachment"],"attached"],
},
{
"slug":"a2-opinions-reasons","file":"a2-opinions-reasons-v1.json","topic":"likes-dislikes","lessons":3,
"vocab":[V("opinion","opinion","نظر"),V("agree","agree","موافق بودن","verb"),V("disagree","disagree","مخالف بودن","verb"),V("reason","reason","دلیل"),V("prefer","prefer","ترجیح دادن","verb"),V("either","either","هم / نیز در جمله منفی","adverb")],
"utterances":[U("think","I think the earlier train is better because it's less crowded.","فکر می‌کنم قطار زودتر بهتره چون خلوت‌تره.","give_opinion",["opinion","reason"],1),U("agree","I agree. It also arrives before lunch.","موافقم. قبل از ناهار هم می‌رسه.","agree",["agree"],1),U("disagree","I don't really agree because the later train is cheaper.","خیلی موافق نیستم چون قطار دیرتر ارزون‌تره.","disagree",["disagree","reason"],2),U("prefer","I'd prefer the quieter restaurant.","رستوران آرام‌تر رو ترجیح می‌دم.","state_preference",["prefer"],2),U("too","I like the first design too.","من هم طرح اول رو دوست دارم.","agree_positive",["agree"],3),U("either","I don't like the second one either.","من هم طرح دوم رو دوست ندارم.","agree_negative",["either"],3)],
"grammar":[G("because_so","because and so","Use because to give a reason and so to give a result.","برای بیان دلیل از because و برای بیان نتیجه از so استفاده می‌کنیم.",[("I chose it because it's cheaper.","انتخابش کردم چون ارزون‌تره."),("It's raining, so let's stay inside.","بارون میاد، پس داخل بمونیم.")],1),G("too_either","too and either","Use too after a positive agreement and either after a negative statement.","برای همراهی با جمله مثبت از too و با جمله منفی از either استفاده می‌کنیم.",[("I like it too.","من هم دوستش دارم."),("I don't want it either.","من هم نمی‌خوامش.")],3)],
"dialogues":[D("movie","Choosing a movie","living room",["Ravi","Priya"],[T("Ravi","I think the comedy looks better.","فکر می‌کنم فیلم کمدی بهتره."),T("Priya","I agree. The other one looks too serious.","موافقم. اون یکی خیلی جدی به نظر می‌رسه."),T("Ravi","And this one starts earlier.","این یکی هم زودتر شروع می‌شه."),T("Priya","Good. Let's watch it.","خوبه. همین رو ببینیم.")],1),D("cafe","Different opinions","street",["Ben","Noura"],[T("Ben","I'd prefer the cafe on King Street.","کافه خیابان کینگ رو ترجیح می‌دم."),T("Noura","I don't really agree. It's always crowded.","خیلی موافق نیستم. همیشه شلوغه."),T("Ben","That's true, but the coffee is better.","درسته، ولی قهوه‌اش بهتره."),T("Noura","Okay. That's a good reason.","باشه. دلیل خوبیه.")],2)],
"fill":["I chose it ___ it's cheaper.",["because","so","either","too"],"because"],
},
{
"slug":"a2-everyday-problems","file":"a2-everyday-problems-v1.json","topic":"requests","lessons":3,
"vocab":[V("broken","broken","خراب","adjective"),V("receipt","receipt","رسید"),V("replace","replace","تعویض کردن","verb"),V("refund","refund","پس دادن پول / بازپرداخت"),V("borrow","borrow","قرض گرفتن","verb"),V("fix","fix","تعمیر کردن","verb")],
"utterances":[U("broken","This charger is broken. It stopped working yesterday.","این شارژر خرابه. دیروز از کار افتاد.","explain_problem",["broken"],1),U("receipt","I still have the receipt.","هنوز رسید رو دارم.","provide_purchase_info",["receipt"],1),U("replace","Could you replace it with a new one?","می‌شه با یک مدل جدید عوضش کنید؟","request_solution",["replace"],2,"polite"),U("refund","If you don't have another one, could I get a refund?","اگر یکی دیگه ندارید، می‌تونم پولم رو پس بگیرم؟","request_refund",["refund"],2,"polite"),U("borrow","Can I borrow your charger until tomorrow?","می‌تونم تا فردا شارژرت رو قرض بگیرم؟","ask_help",["borrow"],3),U("fix","You could try restarting it before you take it in for repair.","می‌تونی قبل از بردنش برای تعمیر یک بار ری‌استارتش کنی.","suggest_solution",["fix"],3)],
"grammar":[G("could_solution","could for suggestions and polite solutions","Use could to suggest an option or make a polite request.","برای پیشنهاد یک راه یا درخواست مؤدبانه از could استفاده می‌کنیم.",[("You could try another cable.","می‌تونی یک کابل دیگه امتحان کنی."),("Could you replace this?","می‌شه این رو تعویض کنید؟")],2),G("if_intro","if for a simple condition","Use if to introduce a simple condition and what to do in that situation.","برای بیان یک شرط ساده و کاری که در آن حالت انجام می‌شود از if استفاده می‌کنیم.",[("If it doesn't work, bring it back.","اگر کار نکرد، برگردونش."),("If they can't fix it, ask for a refund.","اگر نمی‌تونن تعمیرش کنن، پولت رو پس بخواه.")],3)],
"dialogues":[D("store","Returning a broken charger","electronics store",["Chloe","Adam"],[T("Chloe","Hi. I bought this charger here, but it's broken.","سلام. این شارژر رو از اینجا خریدم ولی خرابه."),T("Adam","Do you have the receipt?","رسید رو دارید؟"),T("Chloe","Yes. Could you replace it?","بله. می‌شه تعویضش کنید؟"),T("Adam","Sure. We have the same model in stock.","حتماً. همین مدل موجوده.")],1),D("help","Finding a temporary solution","office",["Ella","Marco"],[T("Ella","My laptop charger stopped working.","شارژر لپ‌تاپم از کار افتاده."),T("Marco","You could borrow mine for the meeting.","می‌تونی برای جلسه مال من رو قرض بگیری."),T("Ella","Thanks. I'll buy a new one after work.","ممنون. بعد از کار یک جدید می‌خرم."),T("Marco","Try the shop downstairs. They usually have them.","فروشگاه پایین رو امتحان کن. معمولاً دارن.")],3)],
"fill":["Could you ___ it with a new one?",["replace","refund","receipt","broken"],"replace"],
},
{
"slug":"a2-integrated-capstone","file":"a2-integrated-capstone-v1.json","topic":"simple-messages","lessons":4,
"vocab":[V("plan","plan","برنامه"),V("delay","delay","تأخیر"),V("reservation","reservation","رزرو"),V("choice","choice","انتخاب"),V("message","message","پیام"),V("solution","solution","راه‌حل"),V("direction","direction","مسیر / جهت"),V("experience","experience","تجربه")],
"utterances":[U("past","My train was delayed, so I arrived an hour late.","قطارم تأخیر داشت، پس یک ساعت دیر رسیدم.","report_past_problem",["delay"],1),U("reservation","I have a reservation, but I need to change the check-in time.","رزرو دارم، ولی باید زمان تحویل اتاق رو عوض کنم.","manage_reservation",["reservation"],1),U("choice","The bus is cheaper, but the subway is faster.","اتوبوس ارزون‌تره، ولی مترو سریع‌تره.","compare_choices",["choice"],2),U("direction","Take the green line and transfer at Central Station.","خط سبز رو بگیر و در ایستگاه مرکزی خط عوض کن.","give_direction",["direction"],2),U("message","I'll send Maya a message and tell her we're running late.","برای مایا پیام می‌فرستم و می‌گم دیر می‌رسیم.","coordinate_by_message",["message"],3),U("plan","We're going to meet at the museum at four.","قرار است ساعت چهار جلوی موزه همدیگر را ببینیم.","state_plan",["plan"],3),U("solution","If the museum is closed, we could go to the market instead.","اگر موزه بسته بود، می‌تونیم به جاش بازار بریم.","suggest_backup",["solution"],4),U("experience","I've never visited this city before, but I'm enjoying it so far.","قبلاً هیچ‌وقت این شهر رو ندیده بودم، ولی تا اینجا دارم لذت می‌برم.","reflect_experience",["experience"],4)],
"grammar":[G("past_present","Past event + present need","Connect a completed past event to a present situation using simple linking words.","یک اتفاق تمام‌شده گذشته را با وضعیت فعلی با کلمات ربط ساده وصل می‌کنیم.",[("The bus was late, so I'm still at the station.","اتوبوس دیر کرد، پس هنوز ایستگاهم."),("I lost my key, so I need help.","کلیدم رو گم کردم، پس کمک لازم دارم.")],1),G("compare_plan","Compare choices before a plan","Use comparatives plus because/but/so to choose between familiar options.","برای انتخاب بین گزینه‌های آشنا از مقایسه همراه because، but یا so استفاده می‌کنیم.",[("The train is faster, but the bus is cheaper.","قطار سریع‌تره ولی اتوبوس ارزون‌تره."),("This route is easier, so let's take it.","این مسیر راحت‌تره، پس همین رو بریم.")],2),G("if_backup","if + could for a backup solution","Use if for a simple possible problem and could for an alternative solution.","برای یک مشکل احتمالی ساده از if و برای راه‌حل جایگزین از could استفاده می‌کنیم.",[("If it's full, we could try the cafe next door.","اگر پر بود، می‌تونیم کافه کناری رو امتحان کنیم."),("If we miss the bus, we could take a taxi.","اگر اتوبوس رو از دست دادیم، می‌تونیم تاکسی بگیریم.")],4)],
"dialogues":[D("arrival","Late arrival","hotel reception",["Maya","Daniel"],[T("Maya","Hi. My train was delayed, so I'm checking in later than planned.","سلام. قطارم تأخیر داشت، برای همین دیرتر از برنامه اتاق رو تحویل می‌گیرم."),T("Daniel","No problem. What's the name on the reservation?","مشکلی نیست. رزرو به چه نامیه؟"),T("Maya","Maya Chen.","مایا چن."),T("Daniel","I found it. Your room is ready.","پیداش کردم. اتاقتون آماده‌ست.")],1),D("city","Choosing how to get there","hotel lobby",["Maya","Leo"],[T("Maya","The museum is three miles away. Should we take the bus?","موزه سه مایل فاصله داره. اتوبوس بگیریم؟"),T("Leo","The bus is cheaper, but the subway is faster.","اتوبوس ارزون‌تره، ولی مترو سریع‌تره."),T("Maya","Let's take the subway, then.","پس مترو بریم."),T("Leo","Okay. We need to transfer at Central Station.","باشه. باید ایستگاه مرکزی خط عوض کنیم.")],2),D("backup","Changing the afternoon plan","text messages",["Maya","Priya"],[T("Maya","We're running about twenty minutes late.","حدود بیست دقیقه دیر می‌رسیم."),T("Priya","No worries. I'll wait near the museum entrance.","مشکلی نیست. نزدیک ورودی موزه منتظر می‌مونم."),T("Maya","If it's closed when we arrive, we could go to the market instead.","اگر وقتی رسیدیم بسته بود، می‌تونیم به جاش بازار بریم."),T("Priya","Sounds good. I've never been there.","خوبه. من هیچ‌وقت اونجا نرفتم.")],4)],
"fill":["If the museum is closed, we ___ go to the market instead.",["could","did","have","are"],"could"],
"extra_exercises":True,
}
]


def build(spec):
    prefix = spec["slug"].replace("-", "_")
    items = []
    concept_slugs = {}
    for i, v in enumerate(spec["vocab"], 1):
        lesson = ((i - 1) % spec["lessons"]) + 1
        slug = f"{prefix}_{v['key']}"
        concept_slugs[v["key"]] = slug
        items.append({"kind":"concept","external_id":f"c_{prefix}_{v['key']}","data":{"slug":slug,"lesson_key":f"{spec['slug']}-{lesson:02d}","concept_type":"lexical","forms":{"en":v["en"]},"translations":{"fa":v["fa"]},"cefr":"A2","topic":spec["topic"],"status":"approved"}})
        lx = f"lx_{prefix}_{v['key']}"
        items.append({"kind":"lexeme","external_id":lx,"data":{"lesson_key":f"{spec['slug']}-{lesson:02d}","lemma":v["en"],"language":"en","language_variant":"en-US","part_of_speech":v["pos"],"concept_refs":[slug],"cefr":"A2","status":"approved"}})
        items.append({"kind":"word_form","external_id":f"wf_{prefix}_{v['key']}","data":{"lesson_key":f"{spec['slug']}-{lesson:02d}","lexeme_ref":lx,"surface_form":v["en"],"grammatical_features":{"form":"base"},"cefr":"A2","status":"approved"}})

    for u in spec["utterances"]:
        refs = [concept_slugs[r] for r in u["refs"] if r in concept_slugs]
        items.append({"kind":"utterance","external_id":f"u_{prefix}_{u['key']}","data":{"lesson_key":f"{spec['slug']}-{u['lesson']:02d}","text":{"en":u["en"]},"translations":{"fa":u["fa"]},"intent":u["intent"],"concept_refs":refs,"cefr":"A2","topic":spec["topic"],"register":u["register"],"status":"approved"}})

    for g in spec["grammar"]:
        items.append({"kind":"grammar_point","external_id":f"g_{prefix}_{g['key']}","data":{"lesson_key":f"{spec['slug']}-{g['lesson']:02d}","slug":f"{spec['slug']}-{g['key'].replace('_','-')}","title":g["title"],"rule_summary":g["rule"],"explanation":{"fa":g["fa"]},"examples":[{"en":a,"fa":b} for a,b in g["examples"]],"cefr":"A2","status":"approved"}})

    for d in spec["dialogues"]:
        items.append({"kind":"dialogue","external_id":f"d_{prefix}_{d['key']}","data":{"lesson_key":f"{spec['slug']}-{d['lesson']:02d}","title":d["title"],"setting":d["setting"],"cefr":"A2","topic":spec["topic"],"characters":d["chars"],"turns":[{"order":i+1,"speaker":t["speaker"],"text":t["en"],"translation_fa":t["fa"]} for i,t in enumerate(d["turns"])],"status":"approved"}})

    # Six varied exercises per unit, grounded in the authored utterances.
    u = spec["utterances"]
    fill_prompt, fill_options, fill_answer = spec["fill"]
    items.append({"kind":"exercise","external_id":f"ex_{prefix}_fill","data":{"lesson_key":f"{spec['slug']}-01","exercise_type":"fill_blank","prompt":{"text":fill_prompt},"options":fill_options,"answer":{"value":fill_answer},"difficulty":2,"cefr":"A2","status":"approved"}})
    items.append({"kind":"exercise","external_id":f"ex_{prefix}_listen","data":{"lesson_key":f"{spec['slug']}-{u[1]['lesson']:02d}","exercise_type":"listening","prompt":{"instruction_fa":"گوش کن و معنی درست را انتخاب کن.","audio_text":u[1]["en"]},"options":[u[1]["fa"],u[0]["fa"],"هیچ‌کدام از این‌ها درست نیست.","اطلاعات کافی نیست."],"answer":{"value":u[1]["fa"]},"difficulty":2,"cefr":"A2","status":"approved"}})
    items.append({"kind":"exercise","external_id":f"ex_{prefix}_speak","data":{"lesson_key":f"{spec['slug']}-{u[2]['lesson']:02d}","exercise_type":"speaking","prompt":{"instruction_fa":f"این جمله را به انگلیسی بگو: {u[2]['fa']}"},"answer":{"expected_text":u[2]["en"]},"difficulty":2,"cefr":"A2","status":"approved"}})
    tokens = u[3]["en"].split()
    items.append({"kind":"exercise","external_id":f"ex_{prefix}_build","data":{"lesson_key":f"{spec['slug']}-{u[3]['lesson']:02d}","exercise_type":"sentence_building","prompt":{"fa":u[3]["fa"],"tokens":list(reversed(tokens))},"answer":{"tokens":tokens,"text":u[3]["en"]},"difficulty":2,"cefr":"A2","status":"approved"}})
    items.append({"kind":"exercise","external_id":f"ex_{prefix}_meaning","data":{"lesson_key":f"{spec['slug']}-{u[4]['lesson']:02d}","exercise_type":"multiple_choice","prompt":{"fa":"معنی درست جمله کدام است؟","text":u[4]["en"]},"options":[u[4]["fa"],u[2]["fa"],u[0]["fa"],u[1]["fa"]],"answer":{"value":u[4]["fa"]},"difficulty":2,"cefr":"A2","status":"approved"}})
    items.append({"kind":"exercise","external_id":f"ex_{prefix}_listen2","data":{"lesson_key":f"{spec['slug']}-{u[-1]['lesson']:02d}","exercise_type":"listening","prompt":{"instruction_fa":"گوش کن و مفهوم جمله را انتخاب کن.","audio_text":u[-1]["en"]},"options":[u[-1]["fa"],u[0]["fa"],u[1]["fa"],u[2]["fa"]],"answer":{"value":u[-1]["fa"]},"difficulty":2,"cefr":"A2","status":"approved"}})

    if spec.get("extra_exercises"):
        items.append({"kind":"exercise","external_id":f"ex_{prefix}_capstone_dialogue","data":{"lesson_key":f"{spec['slug']}-04","exercise_type":"dialogue_comprehension","prompt":{"fa":"اگر موزه بسته باشد، پیشنهاد جایگزین چیست؟"},"options":["رفتن به بازار","برگشتن به هتل","رفتن به فرودگاه","لغو سفر"],"answer":{"value":"رفتن به بازار"},"difficulty":3,"cefr":"A2","status":"approved"}})
        items.append({"kind":"exercise","external_id":f"ex_{prefix}_capstone_speak","data":{"lesson_key":f"{spec['slug']}-04","exercise_type":"speaking","prompt":{"instruction_fa":"یک راه‌حل جایگزین پیشنهاد بده: «اگر موزه بسته باشد، می‌توانیم به بازار برویم.»"},"answer":{"expected_text":"If the museum is closed, we could go to the market."},"difficulty":3,"cefr":"A2","status":"approved"}})

    return enrich_batch({
        "batch_id": f"en-us-{spec['slug']}-v1",
        "course": "fa-en-us",
        "learner_language": "fa",
        "learner_variant": "fa-IR",
        "target_language": "en",
        "target_variant": "en-US",
        "cefr": "A2",
        "curriculum_unit": spec["slug"],
        "generator": "gpt-5.6-sol:golden-dataset-v2",
        "items": items,
    })


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    written = []
    for spec in UNITS:
        path = OUT / spec["file"]
        path.write_text(json.dumps(build(spec), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        written.append(path.name)
    print(json.dumps({"written": len(written), "files": written}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
