#!/usr/bin/env python3
"""Generate German C2 production units from compact hand-authored specs.

Batch 1 is bootstrapped from the canonical specs embedded here so the first
German C2 build can be reproduced from a clean checkout. Later batches use the
same external-spec convention as B2/C1.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from generate_german_b2_batch import build_unit as build_b2_unit

ROOT = Path(__file__).resolve().parents[1]

BATCH1_SPECS = [
    {
        "slug":"implicit-stance-subtext","topic":"simple-messages","title":"Implizite Haltung und Subtext entschlüsseln",
        "objective":"موضع پنهان، پیش‌فرض‌ها و فاصله‌گذاری گوینده را از لحن و انتخاب واژگان تشخیص دادن و بدون بیش‌تفسیر، برداشت را با شواهد زبانی توجیه کردن.",
        "vocab":[["unterton","der Unterton","زیرلحن / معنای ضمنی","noun",1,"masculine"],["implikation","die Implikation","دلالت ضمنی","noun",1,"feminine"],["voraussetzung","die Voraussetzung","پیش‌فرض","noun",2,"feminine"],["andeuten","andeuten","تلویحاً نشان دادن","verb",2],["distanzieren","sich distanzieren","فاصله‌گذاری کردن","verb",3],["ambivalent","ambivalent","دوپهلو / دوسویه","adjective",3]],
        "utterances":[["u1","Die Formulierung wirkt vordergründig neutral, trägt aber einen deutlich skeptischen Unterton.","این عبارت در ظاهر خنثی است، اما زیرلحن آشکارا شکاکانه‌ای دارد.","read_subtext",["unterton"],1],["u2","Die Implikation entsteht weniger durch das Gesagte als durch das, was bewusst offenbleibt.","دلالت ضمنی بیشتر از چیزهایی شکل می‌گیرد که عمداً ناگفته می‌مانند تا از خود گفته‌ها.","infer_implication",["implikation"],1],["u3","Die Aussage setzt voraus, dass beide Seiten denselben Maßstab für Erfolg teilen.","این گفته پیش‌فرض می‌گیرد که هر دو طرف معیار یکسانی برای موفقیت دارند.","surface_assumption",["voraussetzung"],2],["u4","Mit der Bemerkung deutet sie Zweifel an, ohne die Entscheidung frontal anzugreifen.","او با این جمله تردیدش را تلویحاً نشان می‌دهد، بدون اینکه مستقیم به تصمیم حمله کند.","identify_hint",["andeuten"],2],["u5","Der Sprecher distanziert sich erkennbar von der Behauptung, obwohl er sie nicht ausdrücklich zurückweist.","گوینده به‌روشنی از این ادعا فاصله می‌گیرد، هرچند آن را صریح رد نمی‌کند.","track_distance",["distanzieren"],3],["u6","Die Passage bleibt bewusst ambivalent: Zustimmung und Vorbehalt werden gleichzeitig signalisiert.","بخش موردنظر عمداً دوپهلو می‌ماند؛ هم‌زمان هم موافقت و هم تحفظ را منتقل می‌کند.","interpret_ambiguity",["ambivalent"],3]],
        "grammar":[["g1","weniger ... als vielmehr ...","Use this pattern to reweight two interpretations and identify the more precise one.","از این ساختار برای کم‌رنگ کردن یک برداشت و برجسته کردن برداشت دقیق‌تر استفاده می‌شود.",[["Es geht weniger um Ablehnung als vielmehr um Vorsicht.","مسئله کمتر رد کردن است و بیشتر احتیاط."],["Der Ton wirkt weniger kühl als vielmehr kontrolliert.","لحن کمتر سرد است و بیشتر کنترل‌شده."]],1],["g2","als wäre / als ob + Konjunktiv II","Use als wäre/als ob to describe an implied stance without presenting it as fact.","با als wäre / als ob می‌توان حالت ضمنی را بیان کرد بدون اینکه آن را واقعیت قطعی دانست.",[["Er spricht, als wäre die Sache längst entschieden.","طوری حرف می‌زند انگار موضوع مدت‌هاست قطعی شده."],["Sie reagiert, als ob der Einwand nebensächlich wäre.","طوری واکنش نشان می‌دهد انگار ایراد اهمیتی ندارد."]],2],["g3","nicht zuletzt dadurch, dass ...","Use this formal pattern to point to an important linguistic cue among several possible cues.","از این ساختار رسمی برای برجسته کردن یکی از نشانه‌های مهم در میان چند نشانه استفاده می‌شود.",[["Die Distanz entsteht nicht zuletzt dadurch, dass er nur indirekt zustimmt.","فاصله‌گذاری تا حد زیادی از این ناشی می‌شود که او فقط غیرمستقیم موافقت می‌کند."],["Der Unterton wird nicht zuletzt dadurch deutlich, dass zentrale Begriffe in Anführungszeichen stehen.","زیرلحن تا حد زیادی از این روشن می‌شود که واژه‌های اصلی داخل گیومه آمده‌اند."]],3]],
        "dialogues":[["Was sagt der Ton wirklich?","Textanalyse",[["Anna","Der Satz klingt höflich, aber für mich nicht wirklich zustimmend.","جمله مؤدبانه است، اما به نظرم واقعاً موافق نیست."],["Max","Sehe ich auch so. Der Vorbehalt steckt eher im Unterton als im Wortlaut.","من هم همین‌طور می‌بینم. تحفظ بیشتر در زیرلحن است تا در خود واژه‌ها."],["Anna","Dann sollten wir die Distanz markieren, ohne ihm offene Ablehnung zu unterstellen.","پس باید فاصله‌گذاری را نشان بدهیم بدون اینکه رد صریح به او نسبت بدهیم."],["Max","Genau. Wir beschreiben das Signal und trennen es von unserer Interpretation.","دقیقاً. خود نشانه را توصیف می‌کنیم و از تفسیرمان جدا نگه می‌داریم."]],1],["Eine Voraussetzung sichtbar machen","Fachgespräch",[["Sofia","Die Empfehlung klingt logisch, aber irgendetwas daran stört mich.","پیشنهاد منطقی به نظر می‌رسد، اما یک چیزی در آن آزارم می‌دهد."],["Emil","Sie setzt stillschweigend voraus, dass Zeit wichtiger ist als Genauigkeit.","به‌طور ناگفته پیش‌فرض می‌گیرد که زمان از دقت مهم‌تر است."],["Sofia","Stimmt. Wenn dieser Maßstab nicht geteilt wird, ändert sich die ganze Bewertung.","درست است. اگر این معیار مشترک نباشد، کل ارزیابی عوض می‌شود."],["Emil","Genau deshalb sollten wir die Voraussetzung explizit machen.","دقیقاً به همین دلیل باید پیش‌فرض را صریح کنیم."]],2],["Ambivalenz sauber benennen","Redaktionsrunde",[["Nina","Ist das jetzt Zustimmung oder Kritik?","این الان موافقت است یا انتقاد؟"],["Lukas","Beides ein Stück weit. Die Passage ist bewusst ambivalent formuliert.","تا حدی هر دو. این بخش عمداً دوپهلو نوشته شده."],["Nina","Dann wäre eine eindeutige Paraphrase eigentlich verfälschend.","پس بازگویی کاملاً قطعی در واقع تحریف‌کننده می‌شود."],["Lukas","Ja. Auf C2-Niveau müssen wir Mehrdeutigkeit manchmal erhalten statt sie wegzuerklären.","بله. در سطح C2 گاهی باید ابهام را حفظ کنیم، نه اینکه با توضیح از بین ببریم."]],3]]
    },
    {
        "slug":"rhetorical-strategy-diagnostics","topic":"simple-messages","title":"Rhetorische Strategien diagnostizieren",
        "objective":"فریم‌سازی، حذف گزینشی، برجسته‌سازی و سؤال‌های القایی را در استدلال شناسایی کردن و اثر آن‌ها را جدا از درستی محتوای ادعا تحلیل کردن.",
        "vocab":[["framing","das Framing","چارچوب‌بندی","noun",1,"neuter"],["zuspitzung","die Zuspitzung","تشدید و تیزکردن بیان","noun",1,"feminine"],["auslassung","die Auslassung","حذف گزینشی","noun",2,"feminine"],["gegenfolie","die Gegenfolie","نمونه متضاد برای برجسته‌سازی","noun",2,"feminine"],["vereinnahmen","vereinnahmen","به نفع خود مصادره کردن","verb",3],["suggestiv","suggestiv","القایی","adjective",3]],
        "utterances":[["u1","Das Framing lenkt die Aufmerksamkeit auf Kosten und lässt den langfristigen Nutzen in den Hintergrund treten.","این چارچوب‌بندی توجه را به هزینه‌ها می‌برد و فایده بلندمدت را به حاشیه می‌راند.","diagnose_frame",["framing"],1],["u2","Die Zuspitzung erhöht die Dringlichkeit, macht die Alternativen aber künstlich extremer.","تشدید بیان حس فوریت را بالا می‌برد، اما گزینه‌ها را به‌طور مصنوعی افراطی‌تر نشان می‌دهد.","detect_intensification",["zuspitzung"],1],["u3","Die Wirkung beruht auch auf einer auffälligen Auslassung: Gegenbeispiele werden gar nicht erwähnt.","اثرگذاری همچنین بر یک حذف چشمگیر تکیه دارد: مثال‌های نقض اصلاً ذکر نمی‌شوند.","detect_omission",["auslassung"],2],["u4","Als Gegenfolie wird ein Extremfall gewählt, damit die eigene Position automatisch vernünftiger erscheint.","یک مورد افراطی به‌عنوان نمونه متضاد انتخاب می‌شود تا موضع خودشان خودبه‌خود منطقی‌تر به نظر برسد.","identify_contrast",["gegenfolie"],2],["u5","Die Rede vereinnahmt den Begriff Verantwortung, obwohl unterschiedliche Gruppen ihn verschieden definieren.","سخنرانی مفهوم مسئولیت را به نفع خود مصادره می‌کند، در حالی که گروه‌های مختلف تعریف متفاوتی از آن دارند.","spot_appropriation",["vereinnahmen"],3],["u6","Die Frage ist suggestiv gestellt und enthält die gewünschte Antwort bereits in ihrer Voraussetzung.","سؤال به‌شکل القایی مطرح شده و پاسخ مطلوب را از قبل در پیش‌فرض خود دارد.","spot_suggestion",["suggestiv"],3]],
        "grammar":[["g1","indem + Nebensatz","Use indem to make the mechanism of a rhetorical effect explicit.","با indem می‌توان سازوکار دقیق ایجاد یک اثر بلاغی را روشن کرد.",[["Der Text erzeugt Druck, indem er nur zwei extreme Optionen nennt.","متن با ذکر فقط دو گزینه افراطی فشار ایجاد می‌کند."],["Die Rede schafft Nähe, indem sie ständig von wir spricht.","سخنرانی با استفاده مداوم از «ما» حس نزدیکی می‌سازد."]],1],["g2","nicht etwa ..., sondern ...","Use this contrast to correct a plausible but inaccurate reading.","از این تقابل برای اصلاح یک برداشت قابل‌فهم اما نادقیق استفاده می‌شود.",[["Die Passage informiert nicht etwa neutral, sondern rahmt das Problem bereits politisch.","این بخش صرفاً خنثی اطلاع‌رسانی نمی‌کند، بلکه مسئله را از قبل سیاسی چارچوب‌بندی می‌کند."],["Die Frage prüft nicht etwa offen, sondern lenkt auf eine bestimmte Antwort.","سؤال واقعاً باز بررسی نمی‌کند، بلکه به سمت پاسخ مشخص هدایت می‌کند."]],2],["g3","so ..., dass ...","Use so ... dass to describe the degree and consequence of a rhetorical choice.","از so ... dass برای بیان شدت یک انتخاب بلاغی و پیامد آن استفاده می‌شود.",[["Der Gegensatz wird so stark zugespitzt, dass Zwischenpositionen verschwinden.","تضاد آن‌قدر شدید می‌شود که مواضع میانی ناپدید می‌شوند."],["Der Begriff wird so weit gefasst, dass fast jede Handlung darunterfällt.","مفهوم آن‌قدر گسترده تعریف می‌شود که تقریباً هر عملی زیر آن قرار می‌گیرد."]],3]],
        "dialogues":[["Framing statt Fakt?","Medienanalyse",[["Clara","Der Beitrag nennt fast nur die Kosten. Ist das schon manipulativ?","گزارش تقریباً فقط هزینه‌ها را می‌گوید. آیا این خودش دستکاری است؟"],["Noah","Nicht automatisch. Aber das Framing ist klar, weil Nutzen und Vergleichswerte fehlen.","نه لزوماً. اما چارچوب‌بندی روشن است چون فایده‌ها و ارقام مقایسه‌ای غایب‌اند."],["Clara","Dann sollten wir Wirkung und Absicht auseinanderhalten.","پس باید اثر و نیت را از هم جدا کنیم."],["Noah","Genau. Wir können die Strategie diagnostizieren, ohne eine Absicht zu erfinden.","دقیقاً. می‌توانیم راهبرد را تشخیص دهیم بدون اینکه نیتی بسازیم."]],1],["Was wurde weggelassen?","Analysegespräch",[["Lea","Die Argumentation klingt geschlossen, aber fast zu geschlossen.","استدلال منسجم به نظر می‌رسد، حتی بیش از حد منسجم."],["Jonas","Weil die Gegenbeispiele fehlen. Die Auslassung macht die Linie sauberer, als die Daten sind.","چون مثال‌های نقض حذف شده‌اند. این حذف استدلال را تمیزتر از داده‌های واقعی نشان می‌دهد."],["Lea","Das heißt, wir kritisieren nicht die Schlussfolgerung allein, sondern die Auswahl der Evidenz.","یعنی فقط نتیجه را نقد نمی‌کنیم، بلکه انتخاب شواهد را هم نقد می‌کنیم."],["Jonas","Genau. Das ist die präzisere Diagnose.","دقیقاً. این تشخیص دقیق‌تر است."]],2],["Suggestive Fragen erkennen","Debattenvorbereitung",[["Mia","Wie würdest du auf die Frage reagieren: Warum blockiert ihr die notwendige Reform?","به سؤال «چرا جلوی اصلاح ضروری را می‌گیرید؟» چطور جواب می‌دهی؟"],["Leon","Zuerst die Voraussetzung zurückweisen: Dass die Reform notwendig ist, steht ja gerade zur Debatte.","اول پیش‌فرض را رد می‌کنم: اینکه اصلاح ضروری است دقیقاً موضوع بحث است."],["Mia","Also nicht in der vorgegebenen Logik antworten.","یعنی در منطق تحمیل‌شده سؤال جواب ندهیم."],["Leon","Richtig. Sonst übernimmt man das Framing schon mit der ersten Antwort.","درست است. وگرنه از همان پاسخ اول چارچوب سؤال را پذیرفته‌ایم."]],3]]
    },
    {
        "slug":"lexical-precision-collocation","topic":"simple-messages","title":"Lexikalische Präzision und Kollokationen beherrschen",
        "objective":"بین واژه‌های نزدیک از نظر معنا تفاوت دقیق گذاشتن، هم‌آیندی طبیعی و بار معنایی را سنجیدن و عبارتی انتخاب کردن که هم دقیق و هم در آلمانی طبیعی باشد.",
        "vocab":[["treffgenauigkeit","die Treffgenauigkeit","دقت انتخاب واژه","noun",1,"feminine"],["kollokation","die Kollokation","هم‌آیندی واژگانی","noun",1,"feminine"],["konnotation","die Konnotation","بار معنایی","noun",2,"feminine"],["abgrenzung","die Abgrenzung","مرزبندی معنایی","noun",2,"feminine"],["nuancieren","nuancieren","ظریف‌تر و دقیق‌تر کردن","verb",3],["idiomatisch","idiomatisch","طبیعی و اصطلاحی","adjective",3]],
        "utterances":[["u1","Auf C2-Niveau zählt nicht nur Verständlichkeit, sondern auch die Treffgenauigkeit der Wortwahl.","در سطح C2 فقط قابل‌فهم بودن مهم نیست؛ دقت انتخاب واژه هم مهم است.","choose_precisely",["treffgenauigkeit"],1],["u2","Grammatisch wäre die Verbindung möglich, als Kollokation klingt sie jedoch ungewöhnlich.","از نظر دستوری این ترکیب ممکن است، اما به‌عنوان هم‌آیندی طبیعی غیرعادی به گوش می‌رسد.","judge_collocation",["kollokation"],1],["u3","Beide Wörter bezeichnen Kritik, tragen aber eine unterschiedliche Konnotation.","هر دو واژه به انتقاد اشاره دارند، اما بار معنایی متفاوتی دارند.","compare_connotation",["konnotation"],2],["u4","Die Abgrenzung zwischen skeptisch und misstrauisch verändert die Haltung des ganzen Satzes.","مرزبندی بین «شکاک» و «بدگمان» موضع کل جمله را تغییر می‌دهد.","draw_boundary",["abgrenzung"],2],["u5","Wir sollten die Aussage nuancieren, statt einfach ein stärkeres Synonym einzusetzen.","بهتر است گفته را ظریف‌تر کنیم، نه اینکه فقط یک مترادف قوی‌تر جایگزین کنیم.","nuance_wording",["nuancieren"],3],["u6","Die Formulierung ist korrekt, aber noch nicht ganz idiomatisch.","عبارت درست است، اما هنوز کاملاً طبیعی و اصطلاحی نیست.","judge_idiomaticity",["idiomatisch"],3]],
        "grammar":[["g1","im Unterschied zu + Dativ","Use this pattern to draw a precise semantic or pragmatic boundary.","از این ساختار برای مرزبندی دقیق معنایی یا کاربردی استفاده می‌شود.",[["Im Unterschied zu Zweifel klingt Misstrauen persönlicher.","برخلاف تردید، بدگمانی شخصی‌تر به گوش می‌رسد."],["Im Unterschied zu deutlich ist ausdrücklich stärker auf Absicht bezogen.","برخلاف «روشن»، «صریح» بیشتر به قصد گوینده مربوط است."]],1],["g2","je nachdem, ob ...","Use je nachdem, ob to show that lexical choice depends on context or intended stance.","با je nachdem, ob می‌توان نشان داد انتخاب واژه به بافت یا موضع موردنظر بستگی دارد.",[["Je nachdem, ob Nähe oder Distanz gemeint ist, passt ein anderes Verb.","بسته به اینکه نزدیکی یا فاصله مدنظر باشد، فعل متفاوتی مناسب است."],["Je nachdem, ob der Ton neutral bleiben soll, wäre die stärkere Variante zu wertend.","بسته به اینکه لحن باید خنثی بماند یا نه، گزینه قوی‌تر شاید بیش از حد ارزش‌گذار باشد."]],2],["g3","sofern + Nebensatz","Use sofern to state the condition under which a wording choice is appropriate.","از sofern برای بیان شرطی استفاده می‌شود که تحت آن یک انتخاب زبانی مناسب است.",[["Die Wendung passt, sofern ein formeller Ton gewünscht ist.","این عبارت مناسب است، به شرط اینکه لحن رسمی مدنظر باشد."],["Das Verb ist treffend, sofern keine Absicht unterstellt werden soll.","این فعل دقیق است، به شرط اینکه نخواهیم قصدی را به کسی نسبت دهیم."]],3]],
        "dialogues":[["Fast gleich ist nicht gleich","Sprachberatung",[["Anna","Kann ich hier überzeugt durch sicher ersetzen?","می‌توانم اینجا «متقاعد» را با «مطمئن» عوض کنم؟"],["Emil","Nicht ohne Bedeutungsverschiebung. Sicher beschreibt Gewissheit, überzeugt eher eine begründete Haltung.","نه بدون تغییر معنا. «مطمئن» بیشتر یقین را می‌گوید، «متقاعد» موضعی مبتنی بر دلیل را."],["Anna","Dann wäre sicher zu stark und außerdem etwas anders fokussiert.","پس «مطمئن» هم قوی‌تر است و هم تمرکز معنایی متفاوتی دارد."],["Emil","Genau. C2 heißt oft, solche kleinen Verschiebungen bewusst zu steuern.","دقیقاً. C2 اغلب یعنی همین جابه‌جایی‌های کوچک را آگاهانه کنترل کنی."]],1],["Korrekt, aber unnatürlich","Lektoratsgespräch",[["Sofia","Der Satz ist grammatisch richtig, trotzdem klingt er übersetzt.","جمله از نظر دستوری درست است، ولی هنوز ترجمه‌ای به گوش می‌رسد."],["Max","Die Kollokation ist das Problem. Man würde hier eher eine Entscheidung treffen als eine Entscheidung machen.","مشکل هم‌آیندی است. اینجا طبیعی‌تر است بگوییم «تصمیم گرفتن» نه ساختار تحت‌اللفظی دیگر."],["Sofia","Also reicht Grammatikprüfung allein nicht.","پس بررسی دستور زبان به‌تنهایی کافی نیست."],["Max","Genau. Idiomatik ist auf diesem Niveau ein eigener Qualitätsmaßstab.","دقیقاً. طبیعی بودن زبان در این سطح خودش یک معیار کیفیت مستقل است."]],2],["Konnotation kontrollieren","Redaktion",[["Nina","Ich habe geschrieben: Die Leitung behauptet, dass ... Ist das neutral genug?","نوشته‌ام «مدیریت ادعا می‌کند که...» آیا به‌اندازه کافی خنثی است؟"],["Noah","Nicht ganz. Behaupten kann Zweifel an der Aussage mitschwingen lassen.","نه کاملاً. «ادعا کردن» می‌تواند تردید نسبت به گفته را منتقل کند."],["Nina","Dann wäre erklärt oder sagt je nach Kontext neutraler.","پس بسته به بافت «توضیح می‌دهد» یا «می‌گوید» خنثی‌تر است."],["Noah","Richtig. Die Konnotation entscheidet hier über journalistische Distanz.","درست است. اینجا بار معنایی تعیین می‌کند فاصله‌گذاری روزنامه‌نگارانه چطور باشد."]],3]]
    },
    {
        "slug":"register-social-positioning","topic":"polite-language","title":"Registerwechsel und soziale Positionierung steuern",
        "objective":"لحن را با نقش، فاصله اجتماعی و ریسک موقعیت هماهنگ کردن، بدون از دست دادن شخصیت زبانی بین رسمی، حرفه‌ای و صمیمی جابه‌جا شدن و اثر هر انتخاب را آگاهانه کنترل کردن.",
        "vocab":[["distanzgrad","der Distanzgrad","میزان فاصله اجتماعی","noun",1,"masculine"],["adressatenbezug","der Adressatenbezug","تناسب با مخاطب","noun",1,"masculine"],["rollenbewusstsein","das Rollenbewusstsein","آگاهی از نقش","noun",2,"neuter"],["abfedern","abfedern","نرم و کم‌تنش کردن","verb",2],["markieren","markieren","نشانه‌گذاری کردن","verb",3],["salopp","salopp","خودمانی و غیررسمی","adjective",3]],
        "utterances":[["u1","Der passende Distanzgrad hängt nicht nur vom Status, sondern auch von der Beziehungsgeschichte ab.","میزان فاصله مناسب فقط به جایگاه بستگی ندارد؛ سابقه رابطه هم مهم است.","calibrate_distance",["distanzgrad"],1],["u2","Guter Adressatenbezug bedeutet, denselben Inhalt für verschiedene Gruppen unterschiedlich zu rahmen.","تناسب خوب با مخاطب یعنی همان محتوا را برای گروه‌های مختلف به‌شکل متفاوت چارچوب‌بندی کنیم.","adapt_audience",["adressatenbezug"],1],["u3","Rollenbewusstsein verhindert, dass persönliche Nähe versehentlich professionelle Grenzen verwischt.","آگاهی از نقش مانع می‌شود صمیمیت شخصی ناخواسته مرزهای حرفه‌ای را محو کند.","manage_role",["rollenbewusstsein"],2],["u4","Die Kritik lässt sich sprachlich abfedern, ohne ihren Kern unklar zu machen.","می‌توان انتقاد را از نظر زبانی نرم‌تر کرد بدون اینکه هسته آن مبهم شود.","soften_without_blur",["abfedern"],2],["u5","Mit dieser Anrede markiert sie bewusst mehr Distanz als im bisherigen Austausch.","او با این خطاب عمداً فاصله بیشتری نسبت به گفت‌وگوی قبلی نشان می‌دهد.","mark_distance",["markieren"],3],["u6","Die Formulierung wäre im Teamchat passend, in einer Beschwerde an die Behörde aber zu salopp.","این عبارت در چت تیمی مناسب است، اما برای شکایت به اداره بیش از حد خودمانی است.","judge_register",["salopp"],3]],
        "grammar":[["g1","wäre ... angebracht","Use this modal formulation to recommend register choices without sounding categorical.","از این ساختار برای پیشنهاد انتخاب لحن بدون لحن دستوری و قطعی استفاده می‌شود.",[["In diesem Schreiben wäre mehr Distanz angebracht.","در این نامه فاصله بیشتری مناسب است."],["Gegenüber der Kundin wäre eine klarere Entschuldigung angebracht.","در برابر مشتری، عذرخواهی روشن‌تر مناسب‌تر است."]],1],["g2","es empfiehlt sich, ... zu ...","Use this impersonal structure for professional style guidance.","این ساختار غیرشخصی برای توصیه حرفه‌ای درباره سبک و لحن مناسب است.",[["Es empfiehlt sich, die Bitte etwas direkter zu formulieren.","بهتر است درخواست کمی مستقیم‌تر بیان شود."],["Es empfiehlt sich, interne Abkürzungen zu vermeiden.","بهتر است از مخفف‌های داخلی پرهیز شود."]],2],["g3","je ... desto ...","Use this correlative structure to express how register changes with context.","از این ساختار برای بیان رابطه تغییر لحن با تغییر بافت استفاده می‌شود.",[["Je formeller der Rahmen, desto expliziter sollten Zuständigkeiten benannt werden.","هرچه فضا رسمی‌تر باشد، مسئولیت‌ها باید صریح‌تر نام برده شوند."],["Je vertrauter die Beziehung, desto natürlicher kann der Ton werden.","هرچه رابطه صمیمی‌تر باشد، لحن می‌تواند طبیعی‌تر و خودمانی‌تر شود."]],3]],
        "dialogues":[["Zu formell oder genau richtig?","Kommunikationsberatung",[["Clara","Die Mail ist korrekt, aber sie klingt plötzlich viel distanzierter als sonst.","ایمیل درست است، اما ناگهان خیلی دورتر از همیشه به نظر می‌رسد."],["Jonas","Dann ist nicht Grammatik, sondern der Distanzgrad das Problem.","پس مشکل دستور زبان نیست، میزان فاصله است."],["Clara","Ich passe Anrede und Modalität an, lasse aber die klare Bitte stehen.","خطاب و وجه بیان را تنظیم می‌کنم، اما درخواست روشن را نگه می‌دارم."],["Jonas","Genau. Registerwechsel heißt nicht, den Inhalt abzuschwächen.","دقیقاً. تغییر لحن یعنی نه اینکه محتوا را ضعیف کنیم."]],1],["Kritik professionell abfedern","Teamleitung",[["Lea","Ich will klar sagen, dass die Qualität nicht reicht, ohne die Person vorzuführen.","می‌خواهم روشن بگویم کیفیت کافی نیست، بدون اینکه فرد را خجالت‌زده کنم."],["Lukas","Dann trenn Beobachtung und Bewertung und fedre nur den Ton ab.","پس مشاهده و ارزیابی را جدا کن و فقط لحن را نرم‌تر کن."],["Lea","Also: Zwei Kriterien sind noch nicht erfüllt, statt Das ist unbrauchbar.","یعنی بگویم «دو معیار هنوز برآورده نشده» به‌جای «این به درد نمی‌خورد»."],["Lukas","Genau. Präzise bleibt es trotzdem.","دقیقاً. همچنان دقیق می‌ماند."]],2],["Nähe ohne Grenzverlust","Beratungssituation",[["Mia","Wir duzen uns inzwischen. Kann ich die ganze Kommunikation lockerer machen?","حالا همدیگر را «تو» خطاب می‌کنیم. می‌توانم کل ارتباط را خودمانی‌تر کنم؟"],["Leon","Teilweise. Die Anrede kann nah sein, aber deine professionelle Rolle bleibt bestehen.","تا حدی. خطاب می‌تواند صمیمی باشد، اما نقش حرفه‌ای تو همچنان باقی است."],["Mia","Dann darf der Ton wärmer werden, Zuständigkeiten aber nicht verschwimmen.","پس لحن می‌تواند گرم‌تر شود، ولی مسئولیت‌ها نباید مبهم شوند."],["Leon","Genau. Das ist Rollenbewusstsein, nicht Kälte.","دقیقاً. این آگاهی از نقش است، نه سردی."]],3]]
    },
    {
        "slug":"irony-indirect-critique","topic":"polite-language","title":"Ironie, Untertreibung und indirekte Kritik verstehen",
        "objective":"طعنه، کم‌گویی، کنایه و نقد غیرمستقیم را از نشانه‌های بافتی تشخیص دادن، شدت واقعی پیام را درست ارزیابی کردن و در بازگویی، لحن اصلی را نه اغراق و نه خنثی کردن.",
        "vocab":[["ironie","die Ironie","طعنه / وارونه‌گویی","noun",1,"feminine"],["untertreibung","die Untertreibung","کم‌گویی عمدی","noun",1,"feminine"],["spitze","die Spitze","کنایه تند و کوتاه","noun",2,"feminine"],["doppeldeutigkeit","die Doppeldeutigkeit","دوپهلو بودن","noun",2,"feminine"],["durchblickenlassen","durchblicken lassen","تلویحاً فهماندن","verb",3],["augenzwinkernd","augenzwinkernd","با طنز و چشمک‌گونه","adjective",3]],
        "utterances":[["u1","Die Ironie funktioniert nur, weil der wörtliche Sinn offensichtlich nicht zur Situation passt.","طعنه فقط به این دلیل کار می‌کند که معنای تحت‌اللفظی آشکارا با موقعیت جور نیست.","identify_irony",["ironie"],1],["u2","Das ist eine gezielte Untertreibung: ziemlich unpraktisch meint hier faktisch unbrauchbar.","این یک کم‌گویی عمدی است؛ «نسبتاً غیرعملی» اینجا عملاً یعنی «غیرقابل استفاده»." ,"decode_understatement",["untertreibung"],1],["u3","Die Spitze richtet sich weniger gegen den Vorschlag als gegen die Art, wie er präsentiert wurde.","کنایه تند کمتر خود پیشنهاد را هدف گرفته و بیشتر شیوه ارائه آن را.","locate_barb",["spitze"],2],["u4","Die Doppeldeutigkeit erlaubt Kritik, ohne dass sie vollständig explizit werden muss.","دوپهلو بودن اجازه می‌دهد انتقاد منتقل شود بدون اینکه کاملاً صریح شود.","read_double_meaning",["doppeldeutigkeit"],2],["u5","Mit dem Kommentar lässt er deutlich durchblicken, dass er die Erklärung nicht überzeugend findet.","با این نظر به‌وضوح می‌فهماند که توضیح را قانع‌کننده نمی‌داند.","infer_indirect_critique",["durchblickenlassen"],3],["u6","Der Satz ist augenzwinkernd gemeint und wäre als wörtlicher Vorwurf missverstanden.","جمله با طنز گفته شده و اگر تحت‌اللفظی به‌عنوان سرزنش فهمیده شود، بدفهمی ایجاد می‌کند.","preserve_tone",["augenzwinkernd"],3]],
        "grammar":[["g1","als ob + Konjunktiv II","Use als ob to recognize or reproduce ironic comparison and distance.","از als ob می‌توان برای شناخت یا بازسازی مقایسه طعنه‌آمیز و فاصله‌گذاری استفاده کرد.",[["Er tut so, als ob der Fehler eine Überraschung wäre.","طوری رفتار می‌کند انگار خطا واقعاً غافلگیرکننده بوده."],["Sie klingt, als ob drei Stunden Verspätung kaum der Rede wert wären.","طوری حرف می‌زند انگار سه ساعت تأخیر اصلاً مهم نیست."]],1],["g2","nicht gerade + Adjektiv","Use nicht gerade as a common understatement whose pragmatic force can be much stronger than its literal form.","ساختار nicht gerade اغلب کم‌گویی است و نیروی واقعی آن می‌تواند خیلی قوی‌تر از معنای ظاهری باشد.",[["Die Lösung ist nicht gerade elegant.","راه‌حل واقعاً چندان ظریف نیست / عملاً بدقواره است."],["Seine Erklärung war nicht gerade überzeugend.","توضیحش واقعاً قانع‌کننده نبود."]],2],["g3","kaum ..., ohne dass ...","Use this structure to describe an implication that is difficult to avoid.","از این ساختار برای بیان دلالتی استفاده می‌شود که تقریباً نمی‌توان از آن اجتناب کرد.",[["Man kann den Satz kaum lesen, ohne dass Ironie mitschwingt.","تقریباً نمی‌توان جمله را خواند و طعنه را حس نکرد."],["Die Bemerkung lässt sich kaum wiedergeben, ohne dass die Spitze verloren geht.","تقریباً نمی‌توان این جمله را بازگفت بدون اینکه کنایه آن از بین برود."]],3]],
        "dialogues":[["Wörtlich gemeint?","Gesprächsanalyse",[["Anna","Er sagt: Großartig, noch eine zusätzliche Freigaberunde. Das ist doch kein Lob, oder?","می‌گوید: «عالیه، یک مرحله تأیید اضافه دیگر.» این که تعریف نیست، نه؟"],["Noah","Nein. Der Kontext macht die Ironie ziemlich eindeutig.","نه. بافت طعنه را تقریباً کاملاً روشن می‌کند."],["Anna","Dann sollte die Übersetzung auch den genervten Unterton erhalten.","پس ترجمه هم باید زیرلحن کلافه را حفظ کند."],["Noah","Genau, ohne daraus einen offenen Angriff zu machen.","دقیقاً، بدون اینکه آن را به حمله صریح تبدیل کند."]],1],["Untertreibung richtig gewichten","Redaktion",[["Sofia","Sie nennt den Ausfall ein kleines Problem, obwohl der ganze Betrieb stillstand.","او خرابی را «یک مشکل کوچک» می‌نامد، در حالی که کل کار متوقف شده بود."],["Emil","Dann ist klein hier keine sachliche Größenangabe, sondern Untertreibung.","پس «کوچک» اینجا اندازه واقعی را نمی‌گوید، بلکه کم‌گویی است."],["Sofia","Eine wortgetreue Übertragung würde die Aussage also verfälschen.","پس ترجمه تحت‌اللفظی عملاً پیام را تحریف می‌کند."],["Emil","Ja. Die pragmatische Stärke muss erhalten bleiben.","بله. شدت کاربردی پیام باید حفظ شود."]],2],["Eine Spitze nicht überdrehen","Mediationsvorbereitung",[["Nina","Der Kommentar war spitz. Soll ich ihn als Beleidigung zusammenfassen?","نظرش کنایه‌دار بود. باید آن را توهین خلاصه کنم؟"],["Max","Das wäre zu stark. Eine Spitze kann verletzend sein, ohne eine direkte Beleidigung zu sein.","این زیادی قوی است. کنایه می‌تواند آزاردهنده باشد بدون اینکه توهین مستقیم باشد."],["Nina","Dann beschreibe ich Wirkung und Form getrennt.","پس شکل بیان و اثرش را جداگانه توصیف می‌کنم."],["Max","Genau. So bleibt die Einordnung fair.","دقیقاً. این‌طوری ارزیابی منصفانه می‌ماند."]],3]]
    },
    {
        "slug":"argument-premises-fallacies","topic":"simple-messages","title":"Prämissen, Fehlschlüsse und Argumentlogik prüfen",
        "objective":"پیش‌فرض‌های استدلال را آشکار کردن، جهش منطقی، دور باطل و دوگانه کاذب را تشخیص دادن و به‌جای برچسب‌زنی، دقیقاً نشان دادن کدام پیوند استدلالی مشکل دارد.",
        "vocab":[["praemisse","die Prämisse","مقدمه / پیش‌فرض استدلال","noun",1,"feminine"],["zirkelschluss","der Zirkelschluss","استدلال دوری","noun",1,"masculine"],["scheindilemma","das Scheindilemma","دوگانه کاذب","noun",2,"neuter"],["beweislast","die Beweislast","بار اثبات","noun",2,"feminine"],["widerlegen","widerlegen","رد کردن با دلیل","verb",3],["folgerichtig","folgerichtig","منطقی و سازگار با مقدمات","adjective",3]],
        "utterances":[["u1","Die Schlussfolgerung trägt nur, wenn die zentrale Prämisse tatsächlich akzeptiert wird.","نتیجه فقط وقتی پابرجاست که مقدمه اصلی واقعاً پذیرفته شود.","test_premise",["praemisse"],1],["u2","Der Zirkelschluss versteckt sich darin, dass die Behauptung letztlich mit sich selbst begründet wird.","دور باطل در این است که ادعا در نهایت با خودش توجیه می‌شود.","spot_circularity",["zirkelschluss"],1],["u3","Die Darstellung erzeugt ein Scheindilemma, weil mehrere realistische Zwischenoptionen fehlen.","این بیان یک دوگانه کاذب می‌سازد چون چند گزینه میانی واقع‌بینانه حذف شده‌اند.","spot_false_dilemma",["scheindilemma"],2],["u4","Wer eine starke Tatsachenbehauptung aufstellt, trägt zunächst die Beweislast.","کسی که ادعای واقعیتِ قوی مطرح می‌کند، در ابتدا بار اثبات را بر عهده دارد.","assign_burden",["beweislast"],2],["u5","Ein Gegenbeispiel kann die allgemeine Behauptung widerlegen, ohne eine Gegenbehauptung zu beweisen.","یک مثال نقض می‌تواند ادعای کلی را رد کند بدون اینکه ادعای مخالف را ثابت کند.","separate_refutation",["widerlegen"],3],["u6","Der Gedankengang ist folgerichtig, aber nur innerhalb seiner umstrittenen Ausgangsannahmen.","روند استدلال منطقی است، اما فقط در چارچوب پیش‌فرض‌های اولیه بحث‌برانگیزش.","qualify_logic",["folgerichtig"],3]],
        "grammar":[["g1","selbst wenn ...","Use selbst wenn to grant a premise while testing whether the conclusion still follows.","با selbst wenn می‌توان یک مقدمه را موقتاً پذیرفت و بررسی کرد آیا نتیجه همچنان از آن به دست می‌آید یا نه.",[["Selbst wenn die Kosten steigen, folgt daraus nicht automatisch, dass das Projekt scheitert.","حتی اگر هزینه‌ها بالا بروند، از آن خودبه‌خود نتیجه نمی‌شود پروژه شکست می‌خورد."],["Selbst wenn die Quelle irrt, ist die Gegenposition damit noch nicht bewiesen.","حتی اگر منبع اشتباه کند، موضع مخالف هنوز ثابت نشده است."]],1],["g2","daraus folgt nicht (zwingend), dass ...","Use this phrase to block an invalid inferential jump.","از این عبارت برای جلوگیری از جهش استدلالی نامعتبر استفاده می‌شود.",[["Die Zahlen sind niedrig; daraus folgt nicht zwingend, dass kein Problem besteht.","اعداد پایین‌اند؛ از این الزاماً نتیجه نمی‌شود که مشکلی وجود ندارد."],["Zwei Fälle ähneln sich; daraus folgt nicht, dass die Ursachen identisch sind.","دو مورد شبیه‌اند؛ از آن نتیجه نمی‌شود علت‌ها یکسان‌اند."]],2],["g3","nur dann, wenn ...","Use nur dann, wenn to state a necessary condition precisely.","از nur dann, wenn برای بیان دقیق شرط لازم استفاده می‌شود.",[["Die Folgerung gilt nur dann, wenn beide Gruppen vergleichbar sind.","نتیجه فقط وقتی معتبر است که دو گروه قابل مقایسه باشند."],["Der Einwand widerlegt die These nur dann, wenn das Gegenbeispiel wirklich einschlägig ist.","ایراد فقط وقتی نظریه را رد می‌کند که مثال نقض واقعاً مرتبط باشد."]],3]],
        "dialogues":[["Wo steckt die Prämisse?","Argumentanalyse",[["Clara","Das klingt schlüssig: Wenn Leistung messbar ist, sollten wir nur nach Zahlen entscheiden.","منطقی به نظر می‌رسد: اگر عملکرد قابل اندازه‌گیری است، باید فقط با عدد تصمیم بگیریم."],["Leon","Da steckt eine zusätzliche Prämisse drin: dass nur Messbares relevant ist.","یک مقدمه اضافه پنهان است: اینکه فقط چیزهای قابل اندازه‌گیری مهم‌اند."],["Clara","Stimmt. Genau diese Annahme müsste erst begründet werden.","درست است. اول باید همین فرض توجیه شود."],["Leon","Dann prüfen wir die Argumentkette statt nur das Ergebnis.","پس زنجیره استدلال را بررسی می‌کنیم، نه فقط نتیجه را."]],1],["Zwei Optionen reichen nicht","Debattenanalyse",[["Lea","Der Redner sagt: Entweder wir stimmen heute zu oder wir wollen gar keine Lösung.","سخنران می‌گوید: یا امروز موافقت می‌کنیم یا اصلاً راه‌حل نمی‌خواهیم."],["Jonas","Das ist ein klassisches Scheindilemma. Verschiebung oder Änderung wären weitere Optionen.","این یک دوگانه کاذب کلاسیک است. تعویق یا اصلاح هم گزینه‌های دیگری هستند."],["Lea","Dann benenne ich die ausgelassenen Alternativen konkret.","پس گزینه‌های حذف‌شده را مشخص نام می‌برم."],["Jonas","Genau. Das ist stärker als nur Fehlschluss zu rufen.","دقیقاً. این خیلی بهتر از صرفاً گفتن «مغالطه» است."]],2],["Was wurde wirklich widerlegt?","Forschungsrunde",[["Mia","Ein Gegenbeispiel zeigt, dass die ursprüngliche These falsch ist. Also stimmt das Gegenteil.","یک مثال نقض نشان می‌دهد نظریه اصلی غلط است. پس عکس آن درست است."],["Lukas","Der erste Schritt kann stimmen, der zweite nicht. Widerlegung ist noch kein Beweis des Gegenteils.","گام اول ممکن است درست باشد، دومی نه. رد یک ادعا هنوز اثبات عکس آن نیست."],["Mia","Dann muss die Gegenposition ihre eigene Beweislast tragen.","پس موضع مخالف باید بار اثبات خودش را داشته باشد."],["Lukas","Genau. So bleibt die Logik sauber.","دقیقاً. این‌طوری منطق تمیز می‌ماند."]],3]]
    },
    {
        "slug":"systems-causality-feedback","topic":"simple-messages","title":"Systemische Kausalität und Rückkopplungen erklären",
        "objective":"در سامانه‌های پیچیده علت‌های چندگانه، حلقه‌های بازخورد، وابستگی به مسیر و اثر مداخله را تحلیل کردن و از روایت‌های تک‌علتی بیش از حد ساده پرهیز کردن.",
        "vocab":[["rueckkopplung","die Rückkopplung","حلقه بازخورد","noun",1,"feminine"],["wechselwirkung","die Wechselwirkung","تعامل دوطرفه","noun",1,"feminine"],["pfadabhaengigkeit","die Pfadabhängigkeit","وابستگی به مسیر گذشته","noun",2,"feminine"],["intervenieren","intervenieren","مداخله کردن","verb",2],["entkoppeln","entkoppeln","از هم جدا کردن اثرها","verb",3],["gegenlaeufig","gegenläufig","در جهت مخالف","adjective",3]],
        "utterances":[["u1","Die Rückkopplung verstärkt den ursprünglichen Effekt, sobald eine bestimmte Schwelle überschritten ist.","حلقه بازخورد پس از عبور از یک آستانه، اثر اولیه را تقویت می‌کند.","explain_feedback",["rueckkopplung"],1],["u2","Zwischen Vertrauen und Beteiligung besteht eine Wechselwirkung; beide können Ursache und Folge zugleich sein.","بین اعتماد و مشارکت یک تعامل دوطرفه وجود دارد؛ هر دو می‌توانند هم علت و هم معلول باشند.","explain_interaction",["wechselwirkung"],1],["u3","Die heutige Struktur ist teilweise durch Pfadabhängigkeit erklärbar und nicht allein durch aktuelle Anreize.","ساختار امروز تا حدی با وابستگی به مسیر گذشته توضیح داده می‌شود، نه فقط مشوق‌های فعلی.","explain_path_dependence",["pfadabhaengigkeit"],2],["u4","Wenn wir an einem Punkt intervenieren, können sich Effekte an anderer Stelle zeitverzögert zeigen.","اگر در یک نقطه مداخله کنیم، اثرها ممکن است با تأخیر در جای دیگری ظاهر شوند.","trace_intervention",["intervenieren"],2],["u5","Um die Ursachen zu entkoppeln, brauchen wir Vergleichsfälle mit unterschiedlichen Rahmenbedingungen.","برای جدا کردن علت‌ها از هم، به موارد مقایسه‌ای با شرایط متفاوت نیاز داریم.","separate_causes",["entkoppeln"],3],["u6","Zwei gegenläufige Mechanismen können dazu führen, dass der Gesamteffekt zunächst klein aussieht.","دو سازوکار در جهت مخالف می‌توانند باعث شوند اثر کلی در ابتدا کوچک به نظر برسد.","explain_opposing_effects",["gegenlaeufig"],3]],
        "grammar":[["g1","wäre ... ausgeblieben, hätte ...","Use the past counterfactual to test how a system might have evolved without one factor.","از خلاف‌واقع گذشته برای بررسی این استفاده می‌شود که بدون یک عامل، سامانه چگونه ممکن بود پیش برود.",[["Wäre die Förderung ausgeblieben, hätte sich der Markt vermutlich langsamer entwickelt.","اگر حمایت وجود نداشت، بازار احتمالاً آهسته‌تر رشد می‌کرد."],["Wäre der Engpass früher erkannt worden, hätte sich die Rückkopplung abschwächen lassen.","اگر گلوگاه زودتر شناسایی شده بود، می‌شد حلقه بازخورد را ضعیف‌تر کرد."]],1],["g2","unter der Annahme, dass ...","Use this formal phrase to keep system explanations conditional on explicit assumptions.","از این ساختار رسمی برای مشروط نگه داشتن توضیح سامانه به یک فرض صریح استفاده می‌شود.",[["Unter der Annahme, dass die Nachfrage stabil bleibt, dominiert der Kosteneffekt.","با فرض ثابت ماندن تقاضا، اثر هزینه غالب می‌شود."],["Unter der Annahme, dass beide Mechanismen unabhängig sind, lassen sie sich getrennt schätzen.","با فرض مستقل بودن دو سازوکار، می‌توان آن‌ها را جداگانه برآورد کرد."]],2],["g3","zumal + Nebensatz","Use zumal to add a reinforcing reason that matters in a multi-causal explanation.","از zumal برای افزودن یک دلیل تقویت‌کننده در توضیح چندعلتی استفاده می‌شود.",[["Eine einfache Ursache ist unwahrscheinlich, zumal mehrere Effekte zeitgleich einsetzen.","یک علت ساده بعید است، به‌ویژه چون چند اثر هم‌زمان شروع می‌شوند."],["Die Intervention sollte vorsichtig erfolgen, zumal Nebenwirkungen verzögert auftreten können.","مداخله باید محتاطانه باشد، به‌ویژه چون عوارض جانبی ممکن است با تأخیر ظاهر شوند."]],3]],
        "dialogues":[["Eine Ursache reicht nicht","Systemanalyse",[["Anna","Die Beteiligung sank direkt nach der Regeländerung. Dann ist die Regel doch die Ursache.","مشارکت درست بعد از تغییر قانون پایین آمد. پس قانون علت بوده، نه؟"],["Max","Vielleicht ein Faktor. Gleichzeitig stiegen Kosten und die Kommunikation brach ein.","شاید یکی از عوامل. هم‌زمان هزینه‌ها بالا رفت و ارتباط هم مختل شد."],["Anna","Also sollten wir Wechselwirkungen und zeitliche Rückkopplungen prüfen.","پس باید تعامل‌ها و بازخوردهای زمانی را بررسی کنیم."],["Max","Genau. Die zeitliche Reihenfolge allein reicht für ein Systemmodell nicht.","دقیقاً. ترتیب زمانی به‌تنهایی برای یک مدل سیستمی کافی نیست."]],1],["Pfadabhängigkeit erklären","Strategierunde",[["Sofia","Warum bleibt der alte Prozess bestehen, obwohl die neue Lösung objektiv günstiger ist?","چرا فرایند قدیمی می‌ماند، با اینکه راه‌حل جدید واقعاً ارزان‌تر است؟"],["Noah","Weil frühere Investitionen, Gewohnheiten und Schnittstellen den Wechsel verteuern. Das ist Pfadabhängigkeit.","چون سرمایه‌گذاری‌های قبلی، عادت‌ها و رابط‌ها تغییر را گران می‌کنند. این وابستگی به مسیر است."],["Sofia","Dann erklärt der aktuelle Preis nur einen Teil der Entscheidung.","پس قیمت فعلی فقط بخشی از تصمیم را توضیح می‌دهد."],["Noah","Genau. Geschichte wird selbst zu einer Rahmenbedingung.","دقیقاً. تاریخ خودش تبدیل به یک شرط زمینه‌ای می‌شود."]],2],["Gegenläufige Effekte","Forschungsbesprechung",[["Nina","Der Gesamteffekt ist fast null. Heißt das, die Maßnahme wirkt nicht?","اثر کلی تقریباً صفر است. یعنی اقدام اثری ندارد؟"],["Emil","Nicht zwingend. Ein positiver und ein negativer Mechanismus könnten sich gegenseitig aufheben.","نه لزوماً. ممکن است یک سازوکار مثبت و یک سازوکار منفی همدیگر را خنثی کنند."],["Nina","Dann müssen wir die Mechanismen entkoppeln, nicht nur den Mittelwert anschauen.","پس باید سازوکارها را از هم جدا کنیم، نه اینکه فقط میانگین را نگاه کنیم."],["Emil","Genau. Sonst verschwindet die Dynamik in einer einzigen Zahl.","دقیقاً. وگرنه پویایی در یک عدد واحد گم می‌شود."]],3]]
    },
    {
        "slug":"polyphonic-source-synthesis","topic":"simple-messages","title":"Mehrstimmige Quellen synthetisieren, ohne sie zu glätten",
        "objective":"چند منبع با چارچوب و منافع متفاوت را در یک جمع‌بندی منسجم کنار هم قرار دادن، اختلاف واقعی را حفظ کردن و از تبدیل چند صدای متفاوت به یک نتیجه مصنوعی و یکدست پرهیز کردن.",
        "vocab":[["stimmenvielfalt","die Stimmenvielfalt","تنوع صداها و دیدگاه‌ها","noun",1,"feminine"],["deutungsrahmen","der Deutungsrahmen","چارچوب تفسیری","noun",1,"masculine"],["spannungsverhaeltnis","das Spannungsverhältnis","تنش میان دو دیدگاه","noun",2,"neuter"],["verdichten","verdichten","فشرده و منسجم کردن","verb",2],["gegenlesen","gegenlesen","در برابر منبع دیگر خواندن","verb",3],["ueberblenden","überblenden","روی هم انداختن و محو تفاوت‌ها","verb",3]],
        "utterances":[["u1","Eine gute Synthese erhält die Stimmenvielfalt, statt alle Quellen auf eine gemeinsame Position zu reduzieren.","یک سنتز خوب تنوع دیدگاه‌ها را حفظ می‌کند، نه اینکه همه منابع را به یک موضع مشترک تقلیل دهد.","preserve_voices",["stimmenvielfalt"],1],["u2","Die Quellen widersprechen sich nicht nur in den Fakten, sondern bereits in ihrem Deutungsrahmen.","منابع فقط در واقعیت‌ها اختلاف ندارند؛ از همان چارچوب تفسیری هم متفاوت‌اند.","compare_frames",["deutungsrahmen"],1],["u3","Das Spannungsverhältnis zwischen Effizienz und Teilhabe sollte in der Zusammenfassung sichtbar bleiben.","تنش میان کارایی و مشارکت باید در جمع‌بندی قابل‌دیدن بماند.","preserve_tension",["spannungsverhaeltnis"],2],["u4","Wir können die Ergebnisse verdichten, ohne abweichende Bewertungen zu löschen.","می‌توان نتایج را فشرده کرد بدون اینکه ارزیابی‌های متفاوت را حذف کنیم.","condense_fairly",["verdichten"],2],["u5","Die Selbstdarstellung der Organisation sollte man systematisch gegen externe Berichte gegenlesen.","روایت خود سازمان را باید به‌طور نظام‌مند در برابر گزارش‌های بیرونی خواند.","cross_read",["gegenlesen"],3],["u6","Wenn wir die Positionen zu stark überblenden, entsteht ein Konsens, den keine Quelle tatsächlich vertritt.","اگر دیدگاه‌ها را بیش از حد روی هم بیندازیم، اجماعی ساخته می‌شود که هیچ منبعی واقعاً آن را ندارد.","avoid_false_consensus",["ueberblenden"],3]],
        "grammar":[["g1","während X ..., lässt Y ...","Use contrasting clauses to keep different source perspectives active in one synthesis.","از جمله‌های متقابل برای فعال نگه داشتن دیدگاه‌های متفاوت در یک سنتز واحد استفاده می‌شود.",[["Während Quelle A vor Kosten warnt, lässt Quelle B langfristige Einsparungen erwarten.","در حالی که منبع A درباره هزینه هشدار می‌دهد، منبع B صرفه‌جویی بلندمدت را محتمل می‌داند."],["Während der Bericht Fortschritte betont, lässt die Befragung weiterhin Misstrauen erkennen.","در حالی که گزارش بر پیشرفت تأکید می‌کند، نظرسنجی همچنان بی‌اعتمادی را نشان می‌دهد."]],1],["g2","sowohl ... als auch ..., ohne ... zu ...","Use this combination to integrate multiple findings while explicitly preserving a limit.","این ترکیب برای کنار هم آوردن چند یافته همراه با حفظ یک محدودیت صریح به کار می‌رود.",[["Die Analyse berücksichtigt sowohl Kosten als auch Akzeptanz, ohne beide gleichzusetzen.","تحلیل هم هزینه و هم پذیرش را در نظر می‌گیرد بدون اینکه آن‌ها را برابر بداند."],["Die Synthese zeigt sowohl Übereinstimmungen als auch Konflikte, ohne sie künstlich aufzulösen.","سنتز هم توافق‌ها و هم تعارض‌ها را نشان می‌دهد بدون اینکه مصنوعی حلشان کند."]],2],["g3","in dem Maße, in dem ...","Use this proportional structure to qualify how strongly one source supports a conclusion.","از این ساختار نسبتی برای درجه‌بندی میزان پشتیبانی یک منبع از نتیجه استفاده می‌شود.",[["Die Aussage ist in dem Maße belastbar, in dem die beiden Datensätze vergleichbar sind.","این ادعا به همان میزان قابل اتکاست که دو مجموعه داده قابل مقایسه باشند."],["Der Konsens trägt in dem Maße, in dem die Interessen tatsächlich überlappen.","اجماع به همان میزان پایدار است که منافع واقعاً هم‌پوشانی داشته باشند."]],3]],
        "dialogues":[["Kein künstlicher Konsens","Recherche",[["Clara","Drei Quellen nennen ähnliche Probleme. Kann ich schreiben, sie seien sich im Kern einig?","سه منبع مشکلات مشابهی می‌گویند. می‌توانم بنویسم در اصل موافق‌اند؟"],["Lukas","Nur teilweise. Sie erklären die Probleme unterschiedlich und empfehlen Gegensätzliches.","فقط تا حدی. علت‌ها را متفاوت توضیح می‌دهند و پیشنهادهای متضاد دارند."],["Clara","Dann formuliere ich gemeinsame Beobachtung, aber getrennte Deutungsrahmen.","پس مشاهده مشترک را می‌گویم، اما چارچوب‌های تفسیری را جدا نگه می‌دارم."],["Lukas","Genau. So entsteht Synthese ohne falschen Konsens.","دقیقاً. این‌طوری سنتز داریم بدون اجماع مصنوعی."]],1],["Quellen gegeneinander lesen","Analysewerkstatt",[["Lea","Der interne Bericht klingt sehr positiv.","گزارش داخلی خیلی مثبت به نظر می‌رسد."],["Leon","Dann lies ihn gegen die Befragung und die externen Zahlen. Wo stimmen die Ebenen überein?","پس آن را در برابر نظرسنجی و اعداد بیرونی بخوان. کجا سطوح مختلف با هم هم‌خوان‌اند؟"],["Lea","Bei der Nutzung ja, bei der Zufriedenheit nicht.","در استفاده بله، در رضایت نه."],["Leon","Genau dieses Spannungsverhältnis gehört in die Synthese.","دقیقاً همین تنش باید وارد سنتز شود."]],2],["Verdichten ohne Verlust","Briefing",[["Mia","Ich muss sechs Seiten auf einen Absatz verdichten. Dabei gehen zwangsläufig Unterschiede verloren.","باید شش صفحه را در یک پاراگراف فشرده کنم. ناچار تفاوت‌ها از بین می‌روند."],["Jonas","Details ja, zentrale Konflikte nicht. Ordne nach gemeinsamen Fragen statt nach Quellen.","جزئیات بله، اما تعارض‌های اصلی نه. بر اساس پرسش‌های مشترک مرتب کن نه بر اساس منابع."],["Mia","Dann kann jede Frage mehrere Stimmen enthalten.","پس هر پرسش می‌تواند چند دیدگاه را در خود داشته باشد."],["Jonas","Genau. Das ist dichter und zugleich fairer.","دقیقاً. هم فشرده‌تر است و هم منصفانه‌تر."]],3]]
    },
    {
        "slug":"high-stakes-discursive-intervention","topic":"polite-language","title":"In heiklen Gesprächen präzise intervenieren",
        "objective":"در گفت‌وگوهای پرتنش لحظه مناسب مداخله را تشخیص دادن، تنش را بدون پاک کردن اختلاف پایین آوردن، حفظ آبرو و مسئولیت‌پذیری را هم‌زمان مدیریت کردن و مسیر گفت‌وگو را دوباره قابل‌کار کردن.",
        "vocab":[["eingriffspunkt","der Eingriffspunkt","نقطه مناسب مداخله","noun",1,"masculine"],["eskalationsrisiko","das Eskalationsrisiko","ریسک تشدید تنش","noun",1,"neuter"],["gesichtswahrung","die Gesichtswahrung","حفظ آبرو و شأن","noun",2,"feminine"],["umdeuten","umdeuten","بازچارچوب‌بندی کردن","verb",2],["deeskalieren","deeskalieren","تنش‌زدایی کردن","verb",3],["verbindlich","verbindlich","روشن و تعهدآور","adjective",3]],
        "utterances":[["u1","Der beste Eingriffspunkt ist oft erreicht, bevor sich Positionen öffentlich verhärten.","بهترین نقطه مداخله اغلب قبل از آن است که مواضع در جمع سخت و غیرقابل‌انعطاف شوند.","choose_intervention",["eingriffspunkt"],1],["u2","Das Eskalationsrisiko steigt, sobald Kritik als Angriff auf die Person formuliert wird.","ریسک تشدید تنش وقتی بالا می‌رود که انتقاد به‌شکل حمله به شخص بیان شود.","assess_escalation",["eskalationsrisiko"],1],["u3","Gesichtswahrung bedeutet nicht, Verantwortung zu vermeiden, sondern Korrektur ohne Demütigung zu ermöglichen.","حفظ آبرو یعنی نه فرار از مسئولیت، بلکه امکان اصلاح بدون تحقیر.","protect_face",["gesichtswahrung"],2],["u4","Wir können den Konflikt umdeuten: weg von Schuld, hin zu widersprüchlichen Anforderungen.","می‌توانیم تعارض را بازچارچوب‌بندی کنیم: از تقصیر به سمت الزامات متناقض.","reframe_conflict",["umdeuten"],2],["u5","Eine kurze Zusammenfassung kann deeskalieren, wenn sie beiden Seiten erkennbar gerecht wird.","یک جمع‌بندی کوتاه می‌تواند تنش را پایین بیاورد، اگر هر دو طرف احساس کنند منصفانه بازنمایی شده‌اند.","deescalate",["deeskalieren"],3],["u6","Am Ende braucht es eine verbindliche Vereinbarung darüber, was als Nächstes konkret passiert.","در پایان به یک توافق روشن و تعهدآور درباره گام بعدی نیاز است.","close_concretely",["verbindlich"],3]],
        "grammar":[["g1","bevor + Nebensatz","Use bevor to intervene prospectively, before escalation becomes harder to reverse.","از bevor برای مداخله پیشگیرانه، قبل از سخت شدن بازگشت از تنش، استفاده می‌شود.",[["Bevor wir über Schuld sprechen, sollten wir den Ablauf rekonstruieren.","قبل از صحبت درباره تقصیر، بهتر است روند اتفاق را بازسازی کنیم."],["Bevor die Positionen weiter verhärten, möchte ich einen Punkt zusammenfassen.","قبل از اینکه مواضع سخت‌تر شوند، می‌خواهم یک نکته را جمع‌بندی کنم."]],1],["g2","ohne dass + Nebensatz","Use ohne dass to formulate a repair that avoids an unwanted interpersonal consequence.","از ohne dass برای بیان راه‌حلی استفاده می‌شود که پیامد بین‌فردی نامطلوبی ایجاد نکند.",[["Wir müssen den Fehler korrigieren, ohne dass jemand öffentlich bloßgestellt wird.","باید خطا را اصلاح کنیم بدون اینکه کسی جلوی جمع تحقیر شود."],["Die Grenze lässt sich klar benennen, ohne dass das Gespräch abbricht.","می‌توان مرز را روشن گفت بدون اینکه گفت‌وگو قطع شود."]],2],["g3","was ... angeht, ...","Use this topic-fronting structure to separate issues and reduce conflict overload.","از این ساختار برای جدا کردن موضوع‌ها و کم کردن انباشت تعارض استفاده می‌شود.",[["Was die Verantwortung angeht, sollten wir zwischen Entscheidung und Umsetzung unterscheiden.","درباره مسئولیت، باید بین تصمیم و اجرا فرق بگذاریم."],["Was den nächsten Schritt angeht, brauchen wir heute eine verbindliche Zusage.","درباره گام بعدی، امروز به یک تعهد روشن نیاز داریم."]],3]],
        "dialogues":[["Früh genug eingreifen","Krisensitzung",[["Anna","Die beiden reden inzwischen nur noch darüber, wer angefangen hat.","این دو نفر دیگر فقط درباره این حرف می‌زنند که چه کسی شروع کرده."],["Emil","Dann ist jetzt der Eingriffspunkt: Ablauf klären, bevor die Schuldfrage alles blockiert.","پس الان نقطه مداخله است: روند را روشن کنیم قبل از اینکه بحث تقصیر همه‌چیز را قفل کند."],["Anna","Ich fasse erst die unstrittigen Fakten zusammen.","اول واقعیت‌های بدون اختلاف را جمع‌بندی می‌کنم."],["Emil","Gut. Das senkt das Eskalationsrisiko, ohne den Konflikt kleinzureden.","خوب است. این ریسک تشدید را کم می‌کند بدون اینکه تعارض را کوچک جلوه دهد."]],1],["Gesicht wahren, Verantwortung behalten","Mediation",[["Sofia","Wenn ich den Fehler direkt benenne, fühlt er sich vor allen bloßgestellt.","اگر خطا را مستقیم بگویم، جلوی همه احساس تحقیر می‌کند."],["Max","Dann trenn Person und Entscheidung. Verantwortung kann klar bleiben, ohne Demütigung.","پس شخص و تصمیم را جدا کن. مسئولیت می‌تواند روشن بماند بدون تحقیر."],["Sofia","Ich kritisiere also den Prozessschritt und vereinbare die Korrektur separat.","پس گام فرایند را نقد می‌کنم و اصلاح را جداگانه توافق می‌کنم."],["Max","Genau. Das schützt Gesicht und Ergebnis zugleich.","دقیقاً. هم آبرو را حفظ می‌کند هم نتیجه را."]],2],["Konflikt neu rahmen","Verhandlung",[["Nina","Beide Seiten sagen, die andere sei unzuverlässig.","هر دو طرف می‌گویند طرف مقابل قابل اعتماد نیست."],["Noah","Versuch es umzudeuten: Beide reagieren auf unklare Übergaben und unterschiedliche Fristen.","بازچارچوب‌بندی کن: هر دو به تحویل‌های مبهم و مهلت‌های متفاوت واکنش نشان می‌دهند."],["Nina","Dann wird aus einem Charakterkonflikt ein lösbares Koordinationsproblem.","پس تعارض شخصیتی تبدیل می‌شود به مشکل هماهنگی قابل‌حل."],["Noah","Genau. Und danach braucht es eine verbindliche neue Übergabe-Regel.","دقیقاً. بعدش هم یک قاعده جدید و تعهدآور برای تحویل لازم است."]],3]]
    },
    {
        "slug":"interpret-reframe-position-capstone","topic":"simple-messages","title":"C2-Capstone: Interpretieren, reframen und präzise Position beziehen",
        "objective":"زیرمتن، راهبرد بلاغی، دقت واژگانی، منطق استدلال و چندصدایی منابع را در یک تحلیل یکپارچه ترکیب کردن، سپس موضعی دقیق، منصفانه و متناسب با مخاطب ارائه دادن.",
        "vocab":[["gesamtdeutung","die Gesamtdeutung","تفسیر کلی و یکپارچه","noun",1,"feminine"],["perspektivwechsel","der Perspektivwechsel","تغییر زاویه دید","noun",1,"masculine"],["begruendungstiefe","die Begründungstiefe","عمق استدلال و توجیه","noun",2,"feminine"],["einordnen","einordnen","در جایگاه مناسب قرار دادن","verb",2],["rekalibrieren","rekalibrieren","دوباره دقیق تنظیم کردن","verb",3],["stimmig","stimmig","منسجم و متناسب","adjective",3]],
        "utterances":[["u1","Die Gesamtdeutung muss Wortlaut, Unterton, Kontext und Interessen gleichzeitig berücksichtigen.","تفسیر کلی باید هم‌زمان متن صریح، زیرلحن، بافت و منافع را در نظر بگیرد.","integrate_interpretation",["gesamtdeutung"],1],["u2","Ein Perspektivwechsel kann zeigen, warum dieselbe Formulierung für zwei Gruppen unterschiedlich wirkt.","تغییر زاویه دید می‌تواند نشان دهد چرا یک عبارت برای دو گروه اثر متفاوتی دارد.","shift_perspective",["perspektivwechsel"],1],["u3","Die Begründungstiefe zeigt sich daran, ob auch Gegenargumente und Grenzen der eigenen Position verarbeitet werden.","عمق استدلال از این معلوم می‌شود که آیا ضد استدلال‌ها و محدودیت‌های موضع خودمان هم پردازش شده‌اند یا نه.","deepen_reasoning",["begruendungstiefe"],2],["u4","Wir sollten die Einzelbefunde einordnen, bevor wir daraus eine übergreifende Bewertung ableiten.","باید یافته‌های جزئی را در جایگاهشان قرار دهیم قبل از اینکه از آن‌ها ارزیابی کلی بسازیم.","contextualize_findings",["einordnen"],2],["u5","Nach dem Einwand müssen wir die Empfehlung rekalibrieren, nicht komplett aufgeben.","بعد از این ایراد باید پیشنهاد را دوباره دقیق تنظیم کنیم، نه اینکه کامل کنار بگذاریم.","recalibrate_position",["rekalibrieren"],3],["u6","Eine stimmige Position ist präzise genug für Kritik und flexibel genug für neue Evidenz.","یک موضع منسجم آن‌قدر دقیق است که قابل نقد باشد و آن‌قدر منعطف که شواهد تازه را بپذیرد.","state_position",["stimmig"],3]],
        "grammar":[["g1","unter Einbeziehung von + Dativ","Use this formal phrase to signal which dimensions have been integrated into a judgment.","از این عبارت رسمی برای نشان دادن ابعادی استفاده می‌شود که وارد داوری شده‌اند.",[["Unter Einbeziehung der Gegenargumente fällt die Bewertung vorsichtiger aus.","با در نظر گرفتن ضد استدلال‌ها، ارزیابی محتاطانه‌تر می‌شود."],["Unter Einbeziehung des Kontexts wirkt die Äußerung deutlich weniger neutral.","با در نظر گرفتن بافت، گفته بسیار کمتر خنثی به نظر می‌رسد."]],1],["g2","weder ... noch ..., sondern ...","Use this pattern to reject two inadequate framings and replace them with a better one.","از این ساختار برای رد دو چارچوب ناکافی و جایگزین کردن یک چارچوب دقیق‌تر استفاده می‌شود.",[["Es geht weder um Zustimmung noch um Ablehnung, sondern um eine konditionale Unterstützung.","مسئله نه موافقت کامل است نه مخالفت، بلکه حمایت مشروط است."],["Der Konflikt ist weder rein sachlich noch rein persönlich, sondern institutionell mitbedingt.","تعارض نه صرفاً موضوعی است نه صرفاً شخصی، بلکه عوامل نهادی هم در آن نقش دارند."]],2],["g3","sofern ... zugleich ...","Use this combined conditional structure to formulate a position that depends on multiple requirements at once.","از این ساختار شرطی ترکیبی برای موضعی استفاده می‌شود که هم‌زمان به چند شرط وابسته است.",[["Die Empfehlung bleibt tragfähig, sofern die Kosten begrenzt und zugleich die Kontrollen verstärkt werden.","پیشنهاد قابل دفاع می‌ماند، به شرط محدود شدن هزینه و هم‌زمان تقویت کنترل‌ها."],["Die Formulierung ist passend, sofern sie Distanz wahrt und zugleich Verantwortung klar benennt.","عبارت مناسب است، به شرط حفظ فاصله و هم‌زمان نام بردن روشن از مسئولیت."]],3]],
        "dialogues":[["Vom Detail zur Gesamtdeutung","Abschlussanalyse",[["Clara","Wir haben Unterton, Framing und Logik einzeln geprüft. Wie bringen wir das jetzt zusammen?","زیرلحن، چارچوب و منطق را جدا بررسی کردیم. حالا چطور همه را کنار هم بگذاریم؟"],["Jonas","Indem wir fragen, welches Gesamtbild durch alle drei Ebenen gestützt wird und wo Spannungen bleiben.","با این سؤال که کدام تصویر کلی از هر سه سطح پشتیبانی می‌شود و کجا تنش باقی می‌ماند."],["Clara","Also keine Liste von Befunden, sondern eine begründete Gesamtdeutung.","پس نه فهرست یافته‌ها، بلکه یک تفسیر کلی استدلال‌شده."],["Jonas","Genau. Und Unsicherheit bleibt sichtbar, wo die Ebenen nicht zusammenpassen.","دقیقاً. و هرجا سطوح جور نیستند، عدم‌قطعیت باید دیده شود."]],1],["Position nach Kritik rekalibrieren","Entscheidungsrunde",[["Lea","Der Einwand trifft einen echten Schwachpunkt unserer Empfehlung.","این ایراد واقعاً به یک نقطه‌ضعف پیشنهاد ما می‌زند."],["Lukas","Dann müssen wir sie rekalibrieren, aber nicht zwangsläufig verwerfen.","پس باید دوباره تنظیمش کنیم، اما لزوماً نه اینکه کنار بگذاریم."],["Lea","Ich mache die Empfehlung enger und knüpfe sie an zwei zusätzliche Bedingungen.","پیشنهاد را محدودتر می‌کنم و به دو شرط اضافه وابسته می‌کنم."],["Lukas","Damit wird die Position sogar belastbarer, weil sie den Einwand verarbeitet.","این‌طوری موضع حتی قابل‌دفاع‌تر می‌شود چون ایراد را در خودش پردازش کرده."]],2],["C2 heißt bewegliche Präzision","Capstone",[["Mia","Ich dachte immer, C2 bedeutet vor allem kompliziertere Wörter und Sätze.","فکر می‌کردم C2 بیشتر یعنی واژه‌ها و جمله‌های پیچیده‌تر."],["Leon","Eher: präzise lesen, flexibel formulieren und die eigene Position unter neuen Informationen sauber verändern.","بیشتر یعنی دقیق خواندن، منعطف بیان کردن و موضع خود را با اطلاعات تازه به‌درستی تغییر دادن."],["Mia","Also nicht maximal kompliziert, sondern maximal kontrolliert.","یعنی نه حداکثر پیچیدگی، بلکه حداکثر کنترل."],["Leon","Genau. Wenn Sprache, Logik, Register und Kontext zusammenpassen, ist sie stimmig.","دقیقاً. وقتی زبان، منطق، لحن و بافت با هم جور باشند، بیان منسجم است."]],3]]
    }
]


def convert_level(value):
    if isinstance(value, dict):
        return {k: convert_level(v) for k, v in value.items()}
    if isinstance(value, list):
        return [convert_level(v) for v in value]
    if isinstance(value, str):
        return value.replace("B2", "C2").replace("b2", "c2")
    return value


def german_key_alias(value: str) -> str:
    return value.lower().replace("ä", "ae").replace("ö", "oe").replace("ü", "ue").replace("ß", "ss")


def normalize_vocab_refs(spec: dict) -> dict:
    keys = {row[0] for row in spec["vocab"]}
    aliases = {german_key_alias(key): key for key in keys}
    for row in spec["utterances"]:
        normalized = []
        for ref in row[4]:
            if ref in keys:
                normalized.append(ref)
                continue
            resolved = aliases.get(german_key_alias(ref))
            if resolved is None:
                raise ValueError(f"Unknown vocab ref {ref!r} in {spec['slug']}; expected one of {sorted(keys)}")
            normalized.append(resolved)
        row[4] = normalized
    return spec


def ensure_batch1_specs() -> None:
    spec_dir = ROOT / "content" / "specs" / "de" / "C2" / "batch-01"
    spec_dir.mkdir(parents=True, exist_ok=True)
    for index, spec in enumerate(BATCH1_SPECS, start=1):
        path = spec_dir / f"{index:02d}-{spec['slug']}.json"
        if not path.exists():
            path.write_text(json.dumps(spec, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")


def build_unit(spec: dict) -> dict:
    spec = normalize_vocab_refs(spec)
    batch = convert_level(build_b2_unit(spec))
    batch["generator"] = "gpt-5.6-sol:german-c2-batch-v1"
    for item in batch["items"]:
        if item.get("kind") == "exercise":
            item.get("data", {})["difficulty"] = 5
    return batch


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--batch", type=int, required=True)
    args = parser.parse_args()
    if args.batch == 1:
        ensure_batch1_specs()
    spec_dir = ROOT / "content" / "specs" / "de" / "C2" / f"batch-{args.batch:02d}"
    out_dir = ROOT / "content" / "production" / "de" / "C2"
    paths = sorted(spec_dir.glob("*.json"))
    if not 1 <= len(paths) <= 10:
        raise SystemExit(f"Expected 1-10 specs in {spec_dir}, found {len(paths)}")
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for path in paths:
        spec = json.loads(path.read_text(encoding="utf-8"))
        batch = build_unit(spec)
        out = out_dir / f"c2-de-{spec['slug']}-v1.json"
        out.write_text(json.dumps(batch, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        written.append({"file": out.name, "items": len(batch["items"])})
    print(json.dumps({"level":"C2","batch":args.batch,"units":len(written),"written":written}, ensure_ascii=False))


if __name__ == "__main__":
    main()
