#!/usr/bin/env python3
from scripts.generate_c1_support import V, U, make_spec, write_units

UNITS = [
make_spec(index=11, slug="c1-persuasion-concession", topic="requests", title="Persuasion & Concession",
    vocab=[V("persuasive","persuasive","قانع‌کننده","adjective"),V("concession","concession","پذیرش بخشی از نظر مقابل"),V("counterargument","counterargument","استدلال مخالف"),V("credibility","credibility","اعتبار"),V("appeal","appeal","جذابیت / تکیه استدلالی"),V("acknowledge","acknowledge","پذیرفتن / به رسمیت شناختن","verb"),V("compelling","compelling","بسیار قانع‌کننده","adjective"),V("objection","objection","ایراد / اعتراض")],
    utterances=[
        U("ack","A persuasive case becomes stronger when it acknowledges the most reasonable objection rather than pretending none exists.","یک استدلال قانع‌کننده وقتی قوی‌تر می‌شه که منطقی‌ترین ایراد رو بپذیره، نه اینکه وانمود کنه ایرادی وجود نداره.","acknowledge_objection",["persuasive","acknowledge","objection"],1),
        U("concession","I would make one concession here: the proposal is costly in the short term, even if the longer-term case remains compelling.","اینجا یک نکته رو می‌پذیرم: پیشنهاد در کوتاه‌مدت پرهزینه‌ست، حتی اگر استدلال بلندمدتش همچنان خیلی قانع‌کننده باشه.","make_concession",["concession","compelling"],1),
        U("counter","The strongest counterargument is not that the goal is wrong, but that the proposed mechanism may create a new problem.","قوی‌ترین استدلال مخالف این نیست که هدف غلطه، بلکه اینه که سازوکار پیشنهادی ممکنه مشکل جدیدی ایجاد کنه.","state_counterargument",["counterargument","objection"],2),
        U("credibility","Our credibility depends on distinguishing what we know from what we merely hope will happen.","اعتبار ما به این بستگی داره که چیزی رو که می‌دونیم از چیزی که فقط امیدواریم اتفاق بیفته جدا کنیم.","protect_credibility",["credibility"],2),
        U("appeal","An emotional appeal may attract attention, but it should not replace evidence where the decision has serious consequences.","استدلال احساسی ممکنه توجه جلب کنه، ولی جایی که تصمیم پیامد جدی داره نباید جای شواهد رو بگیره.","evaluate_appeal",["appeal","credibility"],3),
        U("frame","I would frame the recommendation around the shared objective, then explain why this option handles the trade-offs better.","توصیه رو حول هدف مشترک قاب‌بندی می‌کنم و بعد توضیح می‌دم چرا این گزینه تعارض‌ها رو بهتر مدیریت می‌کنه.","frame_persuasion",["persuasive","compelling"],3),
        U("limit","The case is compelling within these constraints; I would avoid presenting it as universally applicable.","در این محدودیت‌ها استدلال خیلی قانع‌کننده‌ست؛ ولی به‌عنوان نسخه‌ای برای همه جا مطرحش نمی‌کنم.","limit_claim",["compelling","concession"],3),
        U("close","If we address the objection directly, the audience can disagree with our judgment without doubting that we have considered the alternatives.","اگر مستقیم به ایراد پاسخ بدیم، مخاطب می‌تونه با قضاوت ما مخالف باشه بدون اینکه فکر کنه گزینه‌های دیگه رو ندیده‌ایم.","close_persuasion",["objection","credibility"],3),
    ], grammar=["concession_rebuttal","stance_markers","rhetorical_questions"], fill=["A strong argument should ___ the most reasonable objection.",["acknowledge","dismiss","overstate","signal"],"acknowledge"]),

make_spec(index=12, slug="c1-negotiating-tradeoffs", topic="requests", title="Negotiating Complex Trade-offs",
    vocab=[V("tradeoff","trade-off","بده‌بستان / مصالحه بین دو مزیت"),V("constraint","constraint","محدودیت"),V("leverage","leverage","اهرم مذاکره"),V("compromise","compromise","مصالحه"),V("nonnegotiable","non-negotiable","غیرقابل مذاکره","adjective"),V("offset","offset","جبران کردن","verb"),V("priority","priority","اولویت"),V("workable","workable","عملی / قابل اجرا","adjective")],
    utterances=[
        U("tradeoff","The real trade-off is between speed and reversibility: the faster option leaves us less room to correct mistakes.","بده‌بستان واقعی بین سرعت و امکان برگشت‌پذیریه؛ گزینه سریع‌تر فضای کمتری برای اصلاح اشتباه می‌ذاره.","identify_tradeoff",["tradeoff","constraint"],1),
        U("nonneg","Our deadline is flexible by a few days, but the security requirement is non-negotiable.","موعدمون چند روز قابل انعطافه، ولی الزام امنیتی قابل مذاکره نیست.","state_boundary",["nonnegotiable","constraint"],1),
        U("leverage","If we can offer a longer contract, that may give us enough leverage to negotiate the setup fee down.","اگر قرارداد طولانی‌تر پیشنهاد بدیم شاید اهرم کافی داشته باشیم که هزینه راه‌اندازی رو پایین بیاریم.","use_leverage",["leverage","compromise"],2),
        U("offset","We could accept the higher price if the supplier offsets it with stronger support and a clearer service guarantee.","می‌تونیم قیمت بالاتر رو قبول کنیم اگر تأمین‌کننده با پشتیبانی قوی‌تر و تضمین خدمات روشن‌تر جبرانش کنه.","conditional_offer",["offset","workable"],2),
        U("priority","Before bargaining over details, we should agree which priority we are least willing to sacrifice.","قبل از چانه‌زنی روی جزئیات باید مشخص کنیم کدوم اولویت رو کمتر از همه حاضریم قربانی کنیم.","rank_priority",["priority","tradeoff"],3),
        U("compromise","A workable compromise does not split every difference in half; it protects what matters most to each side.","مصالحه عملی این نیست که هر اختلافی رو نصف کنیم؛ باید چیزهای مهم برای هر طرف رو حفظ کنه.","define_compromise",["compromise","workable"],3),
        U("package","Rather than negotiating each item separately, I would package the terms so concessions in one area can offset demands in another.","به‌جای مذاکره جدا روی هر مورد، شرایط رو به‌صورت بسته‌ای می‌چینم تا امتیاز در یک بخش خواسته‌های بخش دیگه رو جبران کنه.","package_terms",["offset","leverage"],3),
        U("close","If that arrangement is workable for you, we can document the remaining constraints and move to implementation.","اگر این چیدمان برای شما عملی باشه، محدودیت‌های باقی‌مونده رو ثبت می‌کنیم و می‌ریم سراغ اجرا.","close_negotiation",["workable","constraint"],3),
    ], grammar=["mixed_conditionals","diplomatic_language","complex_prepositions"], fill=["The security requirement is ___, although the deadline has some flexibility.",["non-negotiable","workable","offset","compromise"],"non-negotiable"]),

make_spec(index=13, slug="c1-chairing-discussions", topic="jobs", title="Chairing Discussions",
    vocab=[V("agenda","agenda","دستور جلسه"),V("facilitate","facilitate","تسهیل کردن","verb"),V("summarize","summarize","جمع‌بندی کردن","verb"),V("consensus","consensus","اجماع"),V("defer","defer","به تعویق انداختن","verb"),V("tangent","tangent","بحث فرعی"),V("allocate","allocate","اختصاص دادن","verb"),V("action_point","action point","اقدام مشخص")],
    utterances=[
        U("agenda","Before we begin, I want to clarify the agenda and the decision we need to leave the room with.","قبل از شروع می‌خوام دستور جلسه و تصمیمی که باید باهاش از جلسه بیرون بیایم روشن کنم.","set_agenda",["agenda","facilitate"],1),
        U("tangent","That is relevant, but it is becoming a tangent; can we capture it and return to the decision in front of us?", "این نکته مرتبطه، ولی داره تبدیل به بحث فرعی می‌شه؛ می‌تونیم ثبتش کنیم و برگردیم به تصمیم اصلی؟","manage_tangent",["tangent","defer"],1),
        U("allocate","We have twenty minutes left, so I am going to allocate ten to the unresolved risk and ten to the recommendation.","بیست دقیقه وقت داریم، پس ده دقیقه رو به ریسک حل‌نشده و ده دقیقه رو به توصیه نهایی اختصاص می‌دم.","manage_time",["allocate","agenda"],2),
        U("consensus","I am hearing broad consensus on the objective, but not yet on who should own the implementation.","دارم اجماع کلی روی هدف می‌شنوم، ولی هنوز روی مسئول اجرای کار توافق نداریم.","test_consensus",["consensus","summarize"],2),
        U("invite","We have heard from the same three people several times; I would like to bring in anyone who sees the issue differently.","چند بار از همون سه نفر شنیدیم؛ می‌خوام کسانی که مسئله رو متفاوت می‌بینن هم وارد بحث بشن.","broaden_participation",["facilitate"],3),
        U("summary","Let me summarize where we are before we choose between the two remaining options.","قبل از انتخاب بین دو گزینه باقی‌مونده بذارید جمع‌بندی کنم کجا ایستادیم.","summarize_discussion",["summarize","consensus"],3),
        U("defer","I suggest we defer the technical detail to a smaller group rather than let it block the main decision.","پیشنهاد می‌کنم جزئیات فنی رو به گروه کوچک‌تری بسپاریم و نذاریم تصمیم اصلی رو متوقف کنه.","defer_detail",["defer","tangent"],3),
        U("action","To close, I want one clear action point, one owner, and a date for checking progress.","برای پایان، یک اقدام روشن، یک مسئول و یک تاریخ برای بررسی پیشرفت می‌خوام.","close_meeting",["action_point","allocate"],3),
    ], grammar=["discourse_management","cleft_sentences","formal_subjunctive"], fill=["Let us ___ that technical detail until the main decision is made.",["defer","allocate","facilitate","summarize"],"defer"]),

make_spec(index=14, slug="c1-turn-taking-interruption", topic="jobs", title="Turn-taking & Interruption",
    vocab=[V("interject","interject","میان حرف وارد شدن","verb"),V("floor","floor","نوبت صحبت"),V("overlap","overlap","هم‌پوشانی در صحبت"),V("yield","yield","واگذار کردن نوبت","verb"),V("interrupt","interrupt","قطع کردن صحبت","verb"),V("resume","resume","از سر گرفتن","verb"),V("signal","signal","علامت دادن","verb"),V("elaborate","elaborate","بیشتر توضیح دادن","verb")],
    utterances=[
        U("interject","Could I briefly interject before we move on? There is one assumption that affects the rest of the argument.","می‌تونم قبل از ادامه خیلی کوتاه وارد بحث بشم؟ یک فرض هست که روی بقیه استدلال اثر می‌ذاره.","interject_politely",["interject","floor"],1),
        U("yield","I will finish this sentence and then yield the floor, because I want to hear the operational perspective.","این جمله رو تموم می‌کنم و بعد نوبت رو واگذار می‌کنم چون می‌خوام دیدگاه عملیاتی رو بشنوم.","yield_floor",["yield","floor"],1),
        U("overlap","A little overlap is natural in an engaged discussion, but repeated interruption can prevent quieter participants from entering.","کمی هم‌پوشانی توی بحث پرانرژی طبیعیه، ولی قطع مداوم می‌تونه جلوی ورود افراد کم‌حرف‌تر رو بگیره.","evaluate_overlap",["overlap","interrupt"],2),
        U("resume","Sorry, I cut across you there. Please resume the point you were making about implementation risk.","ببخشید حرفت رو قطع کردم. لطفاً نکته‌ای رو که درباره ریسک اجرا می‌گفتی ادامه بده.","repair_interruption",["interrupt","resume"],2),
        U("signal","If you signal that you have one quick clarification, the chair can usually bring you in without derailing the speaker.","اگر علامت بدی فقط یک روشن‌سازی کوتاه داری، معمولاً مدیر جلسه می‌تونه بدون به‌هم زدن جریان صحبت واردت کنه.","signal_entry",["signal","floor"],3),
        U("elaborate","Before anyone responds, I would like Maya to elaborate on what she means by a 'temporary' exception.","قبل از پاسخ بقیه می‌خوام مایا بیشتر توضیح بده منظورش از «استثنای موقت» چیه.","protect_speaker_turn",["elaborate","floor"],3),
        U("direct","I am going to interrupt only because the factual premise has changed since yesterday and affects the decision.","فقط به این دلیل حرف رو قطع می‌کنم که مبنای واقعی از دیروز تغییر کرده و روی تصمیم اثر می‌ذاره.","justify_interruption",["interrupt","interject"],3),
        U("balance","Good turn-taking is less about rigid rules than about making sure disagreement does not silence participation.","نوبت‌دهی خوب کمتر درباره قوانین خشک و بیشتر درباره اینه که اختلاف نظر باعث ساکت شدن مشارکت نشه.","summarize_turn_taking",["yield","overlap"],3),
    ], grammar=["diplomatic_language","discourse_management","register_shift"], fill=["Please ___ your point; I interrupted before you had finished.",["resume","yield","overlap","signal"],"resume"]),

make_spec(index=15, slug="c1-conflict-deescalation", topic="polite-language", title="Conflict De-escalation",
    vocab=[V("deescalate","de-escalate","تنش‌زدایی کردن","verb"),V("trigger","trigger","محرک تنش"),V("defuse","defuse","خنثی کردن تنش","verb"),V("friction","friction","اصطکاک / تنش"),V("accusation","accusation","اتهام"),V("reframe","reframe","بازقاب‌بندی کردن","verb"),V("boundary","boundary","مرز"),V("acknowledge","acknowledge","به رسمیت شناختن","verb")],
    utterances=[
        U("trigger","The immediate trigger was the email, but the friction had been building for weeks around unclear ownership.","محرک فوری ایمیل بود، ولی تنش چند هفته بود به خاطر مالکیت نامشخص کار جمع می‌شد.","identify_trigger",["trigger","friction"],1),
        U("accusation","If we respond to the accusation with another accusation, we will probably escalate the part of the conflict that is easiest to avoid.","اگر به اتهام با اتهام جواب بدیم، احتمالاً همون بخشی از درگیری رو تشدید می‌کنیم که راحت‌تر می‌شه ازش جلوگیری کرد.","avoid_escalation",["accusation","deescalate"],1),
        U("ack","I can acknowledge that the delay caused real pressure without accepting the claim that anyone acted in bad faith.","می‌تونم بپذیرم تأخیر فشار واقعی ایجاد کرده، بدون اینکه ادعای بدرفتاری عمدی رو قبول کنم.","acknowledge_impact",["acknowledge","accusation"],2),
        U("reframe","I would reframe the issue from 'who failed' to 'which handoff broke and how we prevent a repeat.'", "مسئله رو از «چه کسی شکست خورد» به «کدوم تحویل کار خراب شد و چطور تکرارش نکنیم» تغییر می‌دم.","reframe_conflict",["reframe","defuse"],2),
        U("boundary","De-escalation does not mean tolerating personal attacks; a clear boundary can make the conversation safer and more productive.","تنش‌زدایی یعنی حمله شخصی رو تحمل کنیم نیست؛ مرز روشن می‌تونه گفتگو رو امن‌تر و سازنده‌تر کنه.","set_boundary",["boundary","deescalate"],3),
        U("defuse","A specific apology can defuse tension more effectively than a vague attempt to move on quickly.","یک عذرخواهی مشخص می‌تونه خیلی مؤثرتر از تلاش مبهم برای زود عبور کردن، تنش رو خنثی کنه.","defuse_tension",["defuse","acknowledge"],3),
        U("pause","If the conversation becomes too heated to interpret each other fairly, pausing may be more constructive than pushing for immediate agreement.","اگر بحث اون‌قدر داغ بشه که همدیگه رو منصفانه نفهمیم، مکث کردن شاید سازنده‌تر از فشار برای توافق فوری باشه.","pause_conflict",["friction","deescalate"],3),
        U("close","The goal is not to erase disagreement but to lower the emotional temperature enough to solve the actual problem.","هدف حذف اختلاف نیست؛ هدف اینه که دمای احساسی رو اون‌قدر پایین بیاریم که بشه مشکل واقعی رو حل کرد.","state_deescalation_goal",["deescalate","reframe"],3),
    ], grammar=["diplomatic_language","concession_rebuttal","reformulation"], fill=["I would ___ the issue around the broken process rather than personal blame.",["reframe","trigger","accuse","boundary"],"reframe"]),

make_spec(index=16, slug="c1-critical-feedback", topic="jobs", title="Critical Feedback",
    vocab=[V("specific","specific","مشخص","adjective"),V("actionable","actionable","قابل اقدام","adjective"),V("constructive","constructive","سازنده","adjective"),V("pattern","pattern","الگو"),V("impact","impact","اثر"),V("expectation","expectation","انتظار"),V("improve","improve","بهبود دادن","verb"),V("defensive","defensive","دفاعی","adjective")],
    utterances=[
        U("specific","The feedback needs to be specific enough that the person can identify the behavior rather than guess what you disliked.","بازخورد باید اون‌قدر مشخص باشه که فرد رفتار موردنظر رو تشخیص بده، نه اینکه حدس بزنه چی رو دوست نداشتی.","make_feedback_specific",["specific","constructive"],1),
        U("impact","I would describe the impact before judging the intention: the late changes forced two teams to redo work.","قبل از قضاوت درباره نیت، اثر رو توضیح می‌دم: تغییرات دیرهنگام دو تیم رو مجبور کرد کار رو دوباره انجام بدن.","describe_impact",["impact","pattern"],1),
        U("pattern","One missed update would not concern me; what I want to discuss is the repeated pattern across the last three projects.","یک آپدیت از دست‌رفته نگرانم نمی‌کرد؛ چیزی که می‌خوام درباره‌ش حرف بزنم الگوی تکراری در سه پروژه اخیره.","identify_pattern",["pattern","specific"],2),
        U("actionable","To make this actionable, I would like the risk to be raised as soon as the deadline is likely to move, not after it has already moved.","برای اینکه قابل اقدام باشه، می‌خوام به‌محض اینکه احتمال جابه‌جایی موعد هست ریسک مطرح بشه، نه بعد از جابه‌جایی.","set_actionable_change",["actionable","expectation"],2),
        U("defensive","If the other person becomes defensive, repeating the criticism more forcefully usually reduces the chance of learning anything useful.","اگر طرف دفاعی بشه، تکرار شدیدتر انتقاد معمولاً شانس یادگیری مفید رو کمتر می‌کنه.","respond_to_defensiveness",["defensive","constructive"],3),
        U("expectation","The expectation is not perfection; it is earlier communication when uncertainty begins to affect other people.","انتظار بی‌نقص بودن نیست؛ انتظار اطلاع‌رسانی زودتره وقتی عدم قطعیت روی بقیه اثر می‌ذاره.","clarify_expectation",["expectation","impact"],3),
        U("balance","I would also name what is working, not to soften the message artificially but to make the evaluation accurate.","چیزهایی که خوب کار می‌کنن رو هم می‌گم، نه برای مصنوعی نرم کردن پیام، برای اینکه ارزیابی دقیق باشه.","balance_feedback",["constructive","specific"],3),
        U("improve","The conversation has succeeded if both sides leave with a shared understanding of what should improve and how progress will be noticed.","گفتگو وقتی موفقه که هر دو طرف با درک مشترک از چیزی که باید بهتر بشه و نحوه تشخیص پیشرفت بیرون بیان.","close_feedback",["improve","actionable"],3),
    ], grammar=["cleft_sentences","diplomatic_language","emphasis_adverbs"], fill=["Useful feedback should be specific and ___.",["actionable","defensive","ambiguous","anecdotal"],"actionable"]),

make_spec(index=17, slug="c1-strategic-priorities", topic="jobs", title="Strategic Priorities",
    vocab=[V("strategic","strategic","راهبردی","adjective"),V("priority","priority","اولویت"),V("allocate","allocate","اختصاص دادن","verb"),V("capacity","capacity","ظرفیت"),V("initiative","initiative","ابتکار / برنامه"),V("alignment","alignment","هم‌راستایی"),V("deprioritize","deprioritize","کاهش اولویت دادن","verb"),V("outcome","outcome","نتیجه")],
    utterances=[
        U("strategic","A strategic priority should explain what we will not do as clearly as what we intend to pursue.","اولویت راهبردی باید همون‌قدر روشن بگه چه کاری نمی‌کنیم که چه کاری رو دنبال می‌کنیم.","define_priority",["strategic","priority"],1),
        U("capacity","Our capacity is fixed for this quarter, so adding a new initiative means explicitly deprioritizing something else.","ظرفیت این فصل ثابته، پس اضافه کردن برنامه جدید یعنی باید صریحاً اولویت یک کار دیگه رو پایین بیاریم.","surface_capacity_constraint",["capacity","initiative","deprioritize"],1),
        U("alignment","The teams are busy, but activity is not the same as alignment; several projects are pulling toward different outcomes.","تیم‌ها مشغولن، ولی فعالیت با هم‌راستایی یکی نیست؛ چند پروژه به سمت نتیجه‌های متفاوت می‌کشن.","assess_alignment",["alignment","outcome"],2),
        U("allocate","I would allocate additional capacity only where it changes the probability of the strategic outcome, not simply where demand is loudest.","ظرفیت اضافه رو فقط جایی اختصاص می‌دم که احتمال نتیجه راهبردی رو عوض کنه، نه صرفاً جایی که تقاضا بلندتره.","allocate_capacity",["allocate","capacity","strategic"],2),
        U("initiative","This initiative is valuable, but I am not convinced it belongs in the top three priorities right now.","این برنامه ارزشمنده، ولی قانع نیستم الان باید جزو سه اولویت اول باشه.","rank_initiative",["initiative","priority"],3),
        U("deprioritize","Deprioritizing a project is a decision, not a failure; the mistake is pretending everything remains equally urgent.","کم کردن اولویت یک پروژه تصمیمه، شکست نیست؛ اشتباه اینه که وانمود کنیم همه‌چیز همچنان به یک اندازه فوریه.","normalize_deprioritization",["deprioritize","priority"],3),
        U("outcome","The discussion should stay anchored in outcomes rather than becoming a competition between departments for resources.","بحث باید به نتیجه‌ها وصل بمونه، نه اینکه تبدیل به رقابت واحدها برای منابع بشه.","anchor_outcomes",["outcome","alignment"],3),
        U("close","If we agree on the priorities, the allocation decisions become difficult but at least internally consistent.","اگر روی اولویت‌ها توافق کنیم، تصمیم‌های تخصیص هنوز سختن ولی حداقل از نظر داخلی سازگار می‌شن.","close_priority_discussion",["priority","allocate"],3),
    ], grammar=["cleft_sentences","nominalisation","complex_prepositions"], fill=["Adding a new initiative means we may need to ___ something else.",["deprioritize","allocate","align","outcome"],"deprioritize"]),

make_spec(index=18, slug="c1-risk-contingency", topic="jobs", title="Risk & Contingency",
    vocab=[V("contingency","contingency","سناریوی جایگزین / برنامه اضطراری"),V("exposure","exposure","میزان در معرض ریسک بودن"),V("mitigate","mitigate","کاهش دادن ریسک","verb"),V("likelihood","likelihood","احتمال"),V("impact","impact","اثر"),V("dependency","dependency","وابستگی"),V("threshold","threshold","آستانه"),V("fallback","fallback","گزینه پشتیبان")],
    utterances=[
        U("risk","I would separate likelihood from impact, because an unlikely event can still deserve attention if the consequences are severe.","احتمال رو از اثر جدا می‌کنم چون یک اتفاق کم‌احتمال هم اگر پیامد شدید داشته باشه ارزش توجه داره.","separate_risk_dimensions",["likelihood","impact"],1),
        U("dependency","Our largest exposure comes from a single dependency that has no tested fallback.","بزرگ‌ترین ریسک ما از یک وابستگی واحد میاد که هیچ گزینه پشتیبان تست‌شده‌ای نداره.","identify_exposure",["exposure","dependency","fallback"],1),
        U("mitigate","We cannot remove the risk entirely, but we can mitigate it by reducing how much of the launch depends on one supplier.","نمی‌تونیم ریسک رو کامل حذف کنیم، ولی می‌تونیم با کم کردن وابستگی عرضه به یک تأمین‌کننده کاهش بدیمش.","mitigate_risk",["mitigate","dependency"],2),
        U("threshold","We need a threshold that triggers the contingency plan before the original plan has already failed.","یک آستانه لازم داریم که برنامه جایگزین رو قبل از شکست کامل برنامه اصلی فعال کنه.","set_trigger_threshold",["threshold","contingency"],2),
        U("fallback","A fallback is useful only if people know when to use it and it has been tested under realistic conditions.","گزینه پشتیبان فقط وقتی مفیده که آدم‌ها بدونن کی باید ازش استفاده کنن و در شرایط واقعی تست شده باشه.","evaluate_fallback",["fallback","contingency"],3),
        U("exposure2","If the dependency failed tomorrow, our current exposure would affect customer support before core service availability.","اگر وابستگی فردا از کار بیفته، ریسک فعلی اول پشتیبانی مشتری رو تحت‌تأثیر می‌ذاره نه دسترسی سرویس اصلی رو.","trace_risk_impact",["dependency","exposure"],3),
        U("trade","Every mitigation has a cost, so the question is whether the reduction in exposure justifies that cost.","هر کاهش ریسک هزینه‌ای داره، پس سؤال اینه که کاهش در معرض بودن ارزش اون هزینه رو داره یا نه.","weigh_mitigation",["mitigate","exposure"],3),
        U("close","The contingency should be simple enough to execute under pressure, not merely impressive in a planning document.","برنامه جایگزین باید اون‌قدر ساده باشه که زیر فشار اجرا بشه، نه فقط روی کاغذ برنامه‌ریزی قشنگ باشه.","close_contingency",["contingency","fallback"],3),
    ], grammar=["mixed_conditionals","advanced_hedging","nominalisation"], fill=["A tested ___ gives the team another option if the main dependency fails.",["fallback","threshold","exposure","impact"],"fallback"]),

make_spec(index=19, slug="c1-professional-networking", topic="jobs", title="Professional Networking",
    vocab=[V("rapport","rapport","رابطه و هماهنگی خوب"),V("mutual","mutual","متقابل","adjective"),V("introduce","introduce","معرفی کردن","verb"),V("follow_up","follow up","پیگیری کردن","phrasal_verb"),V("context","context","زمینه"),V("referral","referral","معرفی حرفه‌ای"),V("relevant","relevant","مرتبط","adjective"),V("reciprocal","reciprocal","دوطرفه","adjective")],
    utterances=[
        U("rapport","Good networking starts with rapport and genuine curiosity, not with finding the fastest route to ask for a favor.","شبکه‌سازی خوب با رابطه و کنجکاوی واقعی شروع می‌شه، نه پیدا کردن سریع‌ترین راه برای درخواست لطف.","build_rapport",["rapport","mutual"],1),
        U("context","When introducing two people, I try to give enough context that each understands why the connection may be relevant.","وقتی دو نفر رو معرفی می‌کنم، اون‌قدر زمینه می‌دم که هرکدوم بفهمه چرا این ارتباط می‌تونه مرتبط باشه.","make_introduction",["introduce","context","relevant"],1),
        U("follow","A brief follow-up works better when it refers to something specific from the conversation rather than sounding automated.","پیگیری کوتاه وقتی بهتر جواب می‌ده که به نکته مشخصی از گفتگو اشاره کنه، نه اینکه خودکار به نظر بیاد.","follow_up_naturally",["follow_up","context"],2),
        U("referral","I would ask for a referral only when the person has enough knowledge of my work to make the introduction credible.","فقط وقتی درخواست معرفی حرفه‌ای می‌کنم که طرف به اندازه کافی کارم رو بشناسه تا معرفی‌اش معتبر باشه.","ask_for_referral",["referral","relevant"],2),
        U("mutual","The relationship becomes more durable when the value is mutual, even if the exchange is not immediate or symmetrical.","رابطه وقتی ماندگارتر می‌شه که ارزش متقابل باشه، حتی اگر مبادله فوری یا کاملاً برابر نباشه.","describe_mutual_value",["mutual","reciprocal"],3),
        U("reciprocal","Reciprocal does not mean keeping score; it means remaining alert to ways you can be useful as well.","دوطرفه بودن یعنی حساب‌وکتاب امتیازها نه؛ یعنی حواست باشه تو هم کجا می‌تونی مفید باشی.","clarify_reciprocity",["reciprocal","rapport"],3),
        U("exit","If there is no obvious professional fit, I would still close warmly rather than forcing a connection that is not relevant.","اگر تناسب حرفه‌ای واضحی نیست، باز هم گرم گفتگو رو می‌بندم به‌جای اینکه ارتباط نامربوط رو به زور بسازم.","close_networking_exchange",["relevant","rapport"],3),
        U("longterm","The strongest networks are usually built through repeated low-pressure contact rather than one highly strategic conversation.","قوی‌ترین شبکه‌ها معمولاً با ارتباط‌های کم‌فشار و تکرارشونده ساخته می‌شن، نه یک گفتگوی خیلی حساب‌شده.","reflect_on_networking",["mutual","follow_up"],3),
    ], grammar=["register_shift","reduced_relatives","diplomatic_language"], fill=["A good introduction gives enough ___ for both people to understand the connection.",["context","rapport","referral","mutual"],"context"]),

make_spec(index=20, slug="c1-leadership-interviews", topic="jobs", title="Leadership Interviews",
    vocab=[V("leadership","leadership","رهبری"),V("accountability","accountability","پاسخ‌گویی"),V("delegate","delegate","واگذار کردن","verb"),V("stakeholder","stakeholder","ذی‌نفع"),V("judgment","judgment","قضاوت حرفه‌ای"),V("ownership","ownership","مسئولیت‌پذیری"),V("uncertainty","uncertainty","عدم قطعیت"),V("outcome","outcome","نتیجه")],
    utterances=[
        U("example","A useful leadership example should show the decision, the uncertainty around it, and what you personally owned.","مثال خوب از رهبری باید تصمیم، عدم قطعیت اطرافش و چیزی رو که خودت مسئولش بودی نشون بده.","frame_leadership_example",["leadership","uncertainty","ownership"],1),
        U("delegate","I delegated the implementation but retained accountability for the outcome and the communication with stakeholders.","اجرا رو واگذار کردم ولی پاسخ‌گویی نسبت به نتیجه و ارتباط با ذی‌نفع‌ها رو نگه داشتم.","describe_delegation",["delegate","accountability","stakeholder"],1),
        U("judgment","The difficult judgment was deciding when to act with incomplete information rather than waiting for certainty we were unlikely to get.","قضاوت سخت این بود که کی با اطلاعات ناقص اقدام کنیم، به‌جای انتظار برای اطمینانی که احتمالاً هیچ‌وقت نمی‌رسید.","explain_judgment",["judgment","uncertainty"],2),
        U("ownership","I would not present the success as mine alone; my ownership was creating the conditions in which the team could make the decision quickly.","موفقیت رو فقط مال خودم نمی‌دونم؛ مسئولیت من ساختن شرایطی بود که تیم بتونه سریع تصمیم بگیره.","show_ownership_without_overclaim",["ownership","leadership"],2),
        U("failure","When the first approach failed, I told the stakeholders early, explained what we had learned, and reset the expected outcome.","وقتی رویکرد اول شکست خورد، زود به ذی‌نفع‌ها گفتم، چیزی رو که یاد گرفته بودیم توضیح دادم و انتظار نسبت به نتیجه رو تنظیم کردم.","describe_failure_response",["stakeholder","outcome","accountability"],3),
        U("delegate2","Delegating well meant being explicit about the decision boundary, not disappearing after assigning the task.","واگذاری خوب یعنی مرز تصمیم رو صریح کنم، نه اینکه بعد از سپردن کار ناپدید بشم.","clarify_delegation",["delegate","accountability"],3),
        U("reflection","In hindsight, I would have involved one stakeholder earlier because their objection exposed a risk we had underestimated.","حالا که نگاه می‌کنم، یک ذی‌نفع رو زودتر وارد می‌کردم چون ایرادش ریسکی رو آشکار کرد که دست‌کم گرفته بودیم.","reflect_on_leadership",["stakeholder","judgment"],3),
        U("close","For me, leadership is less about having the answer than creating enough clarity and accountability for good decisions to happen.","برای من رهبری کمتر درباره داشتن جواب و بیشتر درباره ساختن شفافیت و پاسخ‌گویی کافیه تا تصمیم خوب ممکن بشه.","define_leadership",["leadership","accountability"],3),
    ], grammar=["counterfactual_past","cleft_sentences","nominalisation"], fill=["I delegated the task but retained ___ for the outcome.",["accountability","uncertainty","stakeholder","judgment"],"accountability"]),
]

if __name__ == "__main__":
    write_units(UNITS)
