-- Generated by nova/tts/nova_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to turns.audio_url and turns.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
CREATE TEMPORARY TABLE nova_turn_audio_updates (
  cefr_level VARCHAR(8) NOT NULL,
  module_order INT UNSIGNED NOT NULL,
  chapter_order INT UNSIGNED NOT NULL,
  lesson_order INT UNSIGNED NOT NULL,
  turn_order INT UNSIGNED NOT NULL,
  character_name VARCHAR(120) NOT NULL,
  turn_role VARCHAR(16) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL,
  PRIMARY KEY (cefr_level,module_order,chapter_order,lesson_order,turn_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_turn_audio_updates (cefr_level,module_order,chapter_order,lesson_order,turn_order,character_name,turn_role,text_sha256,audio_url,audio_duration_ms) VALUES
('ST',1,1,1,1,'Noah','character','6df599a4febe0873ca6409f80ab7d6e69e892adec43690dc6f2abe577f3d2f9c','nova/audio/turns/en-fa/ST/m01/c01/l01/t01-noah-749fe39ee0c7.mp3',1068),
('ST',1,1,1,2,'Mina','learner','48773d891056c30b987051c8df6143dde4eda1278f3730b45ee7072cd5565c55','nova/audio/turns/en-fa/ST/m01/c01/l01/t02-mina-22d11e4949a4.mp3',929),
('ST',1,1,1,3,'Noah','character','69022306d1d601e76385764a2a7bc0be5cf527ef3e3bc09209e376d6627125d2','nova/audio/turns/en-fa/ST/m01/c01/l01/t03-noah-1dd217e5804b.mp3',604),
('ST',1,1,1,4,'Mina','learner','ceb11e8c902b741aa80b580b3e468c087d50cb8b718ead4609b5a098e6d7a03b','nova/audio/turns/en-fa/ST/m01/c01/l01/t04-mina-2dc34512a91c.mp3',929),
('ST',1,1,2,1,'Noah','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m01/c01/l02/t01-noah-09d3409590f7.mp3',697),
('ST',1,1,2,2,'Mina','learner','7ece891b3313fa6f0fe325e0d3d472b919a4d20d5a92e0d55e8cee9a80f30f73','nova/audio/turns/en-fa/ST/m01/c01/l02/t02-mina-13da8facc630.mp3',882),
('ST',1,1,2,3,'Noah','character','e1334459649844666e910dcc273dbde5a37a83e8cd12b6c7ea9ee1d20ada4637','nova/audio/turns/en-fa/ST/m01/c01/l02/t03-noah-a0603968b2bb.mp3',697),
('ST',1,1,2,4,'Mina','learner','1ff49d1ec768fc4281841972b015a1175b17d24ca9a965fd6b934e13e9b590bd','nova/audio/turns/en-fa/ST/m01/c01/l02/t04-mina-a232ba288d00.mp3',1068),
('ST',1,1,3,1,'Noah','character','6df599a4febe0873ca6409f80ab7d6e69e892adec43690dc6f2abe577f3d2f9c','nova/audio/turns/en-fa/ST/m01/c01/l03/t01-noah-749fe39ee0c7.mp3',1068),
('ST',1,1,3,2,'Mina','learner','48773d891056c30b987051c8df6143dde4eda1278f3730b45ee7072cd5565c55','nova/audio/turns/en-fa/ST/m01/c01/l03/t02-mina-8bb05e3f1f8d.mp3',1254),
('ST',1,1,3,3,'Noah','character','b75fdf798d6c6f47026249fb5e45ffac54a5872575ecbd772ba9467c9ada0a2b','nova/audio/turns/en-fa/ST/m01/c01/l03/t03-noah-76842ca8541c.mp3',511),
('ST',1,1,3,4,'Mina','learner','68082b613e502a457bcdc6b5309ac444ff6b1e90d9cde45d8c5d3d4a41c1b7d6','nova/audio/turns/en-fa/ST/m01/c01/l03/t04-mina-3912944f3f59.mp3',650),
('ST',1,1,3,5,'Noah','character','a0d7ce8c360ce42ca16394929f14c0fcb116bae1a05f6f9c23ae7815f6ae7de7','nova/audio/turns/en-fa/ST/m01/c01/l03/t05-noah-3eed6b717a98.mp3',325),
('ST',1,1,3,6,'Mina','learner','8aff5108a050bcfab25817bf86c37c2660c09db0c5cbea06cb49565c6644e7d2','nova/audio/turns/en-fa/ST/m01/c01/l03/t06-mina-cb00a6d46776.mp3',697),
('ST',1,1,4,1,'Noah','character','e1334459649844666e910dcc273dbde5a37a83e8cd12b6c7ea9ee1d20ada4637','nova/audio/turns/en-fa/ST/m01/c01/l04/t01-noah-52532acf3a2a.mp3',650),
('ST',1,1,4,2,'Mina','learner','1ff49d1ec768fc4281841972b015a1175b17d24ca9a965fd6b934e13e9b590bd','nova/audio/turns/en-fa/ST/m01/c01/l04/t02-mina-23b5669735e6.mp3',836),
('ST',1,1,4,3,'Noah','character','47c1d6734534aed4b1591793d4e21f3d3cd915a31dc1984fb7dbb232870120d6','nova/audio/turns/en-fa/ST/m01/c01/l04/t03-noah-56beb99f2d40.mp3',789),
('ST',1,1,4,4,'Mina','learner','47c1d6734534aed4b1591793d4e21f3d3cd915a31dc1984fb7dbb232870120d6','nova/audio/turns/en-fa/ST/m01/c01/l04/t04-mina-d678f24cb694.mp3',929);

DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_turn_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='en' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova en-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_turn_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order,
           COUNT(c.id) AS matched_rows
    FROM nova_turn_audio_updates AS u
    LEFT JOIN levels AS lv
      ON lv.course_id=v_course AND lv.cefr_level=u.cefr_level
    LEFT JOIN modules AS m
      ON m.level_id=lv.id AND m.sort_order=u.module_order
    LEFT JOIN chapters AS ch
      ON ch.module_id=m.id AND ch.sort_order=u.chapter_order
    LEFT JOIN lessons AS l
      ON l.chapter_id=ch.id AND l.sort_order=u.lesson_order
    LEFT JOIN turns AS t
      ON t.lesson_id=l.id AND t.sort_order=u.turn_order
     AND t.role=u.turn_role AND SHA2(t.text,256)=u.text_sha256
    LEFT JOIN characters AS c
      ON c.id=t.character_id AND c.course_id=v_course AND c.name=u.character_name
    GROUP BY u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order
    HAVING COUNT(c.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Turn locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE turns AS t
  JOIN lessons AS l ON l.id=t.lesson_id
  JOIN chapters AS ch ON ch.id=l.chapter_id
  JOIN modules AS m ON m.id=ch.module_id
  JOIN levels AS lv ON lv.id=m.level_id AND lv.course_id=v_course
  JOIN characters AS c ON c.id=t.character_id AND c.course_id=v_course
  JOIN nova_turn_audio_updates AS u
    ON u.cefr_level=lv.cefr_level
   AND u.module_order=m.sort_order
   AND u.chapter_order=ch.sort_order
   AND u.lesson_order=l.sort_order
   AND u.turn_order=t.sort_order
   AND u.character_name=c.name
   AND u.turn_role=t.role
   AND u.text_sha256=SHA2(t.text,256)
  SET t.audio_url=u.audio_url,
      t.audio_duration_ms=u.audio_duration_ms;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_turns, v_changed AS changed_turns;
END$$
DELIMITER ;
CALL apply_nova_turn_audio();
DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
