-- Generated by nova/tts/nova_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to turns.audio_url and turns.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
CREATE TEMPORARY TABLE nova_turn_audio_updates (
  cefr_level VARCHAR(8) NOT NULL,
  module_order INT UNSIGNED NOT NULL,
  chapter_order INT UNSIGNED NOT NULL,
  lesson_order INT UNSIGNED NOT NULL,
  turn_order INT UNSIGNED NOT NULL,
  character_name VARCHAR(120) NOT NULL,
  turn_role VARCHAR(16) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL,
  PRIMARY KEY (cefr_level,module_order,chapter_order,lesson_order,turn_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_turn_audio_updates (cefr_level,module_order,chapter_order,lesson_order,turn_order,character_name,turn_role,text_sha256,audio_url,audio_duration_ms) VALUES
('ST',1,1,1,1,'Noah','character','6df599a4febe0873ca6409f80ab7d6e69e892adec43690dc6f2abe577f3d2f9c','nova/audio/turns/en-fa/ST/m01/c01/l01/t01-noah-749fe39ee0c7.mp3',1068),
('ST',1,1,1,2,'Mina','learner','48773d891056c30b987051c8df6143dde4eda1278f3730b45ee7072cd5565c55','nova/audio/turns/en-fa/ST/m01/c01/l01/t02-mina-22d11e4949a4.mp3',929),
('ST',1,1,1,3,'Noah','character','69022306d1d601e76385764a2a7bc0be5cf527ef3e3bc09209e376d6627125d2','nova/audio/turns/en-fa/ST/m01/c01/l01/t03-noah-1dd217e5804b.mp3',604),
('ST',1,1,1,4,'Mina','learner','ceb11e8c902b741aa80b580b3e468c087d50cb8b718ead4609b5a098e6d7a03b','nova/audio/turns/en-fa/ST/m01/c01/l01/t04-mina-2dc34512a91c.mp3',929),
('ST',1,1,2,1,'Noah','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m01/c01/l02/t01-noah-09d3409590f7.mp3',697),
('ST',1,1,2,2,'Mina','learner','7ece891b3313fa6f0fe325e0d3d472b919a4d20d5a92e0d55e8cee9a80f30f73','nova/audio/turns/en-fa/ST/m01/c01/l02/t02-mina-13da8facc630.mp3',882),
('ST',1,1,2,3,'Noah','character','e1334459649844666e910dcc273dbde5a37a83e8cd12b6c7ea9ee1d20ada4637','nova/audio/turns/en-fa/ST/m01/c01/l02/t03-noah-a0603968b2bb.mp3',697),
('ST',1,1,2,4,'Mina','learner','1ff49d1ec768fc4281841972b015a1175b17d24ca9a965fd6b934e13e9b590bd','nova/audio/turns/en-fa/ST/m01/c01/l02/t04-mina-a232ba288d00.mp3',1068),
('ST',1,1,3,1,'Noah','character','6df599a4febe0873ca6409f80ab7d6e69e892adec43690dc6f2abe577f3d2f9c','nova/audio/turns/en-fa/ST/m01/c01/l03/t01-noah-749fe39ee0c7.mp3',1068),
('ST',1,1,3,2,'Mina','learner','48773d891056c30b987051c8df6143dde4eda1278f3730b45ee7072cd5565c55','nova/audio/turns/en-fa/ST/m01/c01/l03/t02-mina-8bb05e3f1f8d.mp3',1254),
('ST',1,1,3,3,'Noah','character','b75fdf798d6c6f47026249fb5e45ffac54a5872575ecbd772ba9467c9ada0a2b','nova/audio/turns/en-fa/ST/m01/c01/l03/t03-noah-76842ca8541c.mp3',511),
('ST',1,1,3,4,'Mina','learner','68082b613e502a457bcdc6b5309ac444ff6b1e90d9cde45d8c5d3d4a41c1b7d6','nova/audio/turns/en-fa/ST/m01/c01/l03/t04-mina-3912944f3f59.mp3',650),
('ST',1,1,3,5,'Noah','character','a0d7ce8c360ce42ca16394929f14c0fcb116bae1a05f6f9c23ae7815f6ae7de7','nova/audio/turns/en-fa/ST/m01/c01/l03/t05-noah-3eed6b717a98.mp3',325),
('ST',1,1,3,6,'Mina','learner','8aff5108a050bcfab25817bf86c37c2660c09db0c5cbea06cb49565c6644e7d2','nova/audio/turns/en-fa/ST/m01/c01/l03/t06-mina-cb00a6d46776.mp3',697),
('ST',1,1,4,1,'Noah','character','e1334459649844666e910dcc273dbde5a37a83e8cd12b6c7ea9ee1d20ada4637','nova/audio/turns/en-fa/ST/m01/c01/l04/t01-noah-52532acf3a2a.mp3',650),
('ST',1,1,4,2,'Mina','learner','1ff49d1ec768fc4281841972b015a1175b17d24ca9a965fd6b934e13e9b590bd','nova/audio/turns/en-fa/ST/m01/c01/l04/t02-mina-23b5669735e6.mp3',836),
('ST',1,1,4,3,'Noah','character','47c1d6734534aed4b1591793d4e21f3d3cd915a31dc1984fb7dbb232870120d6','nova/audio/turns/en-fa/ST/m01/c01/l04/t03-noah-56beb99f2d40.mp3',789),
('ST',1,1,4,4,'Mina','learner','47c1d6734534aed4b1591793d4e21f3d3cd915a31dc1984fb7dbb232870120d6','nova/audio/turns/en-fa/ST/m01/c01/l04/t04-mina-d678f24cb694.mp3',929),
('ST',1,2,1,1,'Noah','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m01/c02/l01/t01-noah-09d3409590f7.mp3',697),
('ST',1,2,1,2,'Mina','learner','7ece891b3313fa6f0fe325e0d3d472b919a4d20d5a92e0d55e8cee9a80f30f73','nova/audio/turns/en-fa/ST/m01/c02/l01/t02-mina-b4bdea4a4872.mp3',975),
('ST',1,2,1,3,'Noah','character','56e8908ad76682304d68ca9cd055ca9d6b96ff2f8077d1041567dde66aed9724','nova/audio/turns/en-fa/ST/m01/c02/l01/t03-noah-1e92ecd824bb.mp3',836),
('ST',1,2,1,4,'Mina','learner','998dc661044d32a813dd5638440e680983f31bad4c356cfccdc82256ccef66be','nova/audio/turns/en-fa/ST/m01/c02/l01/t04-mina-1b2e6b0bf9a8.mp3',1858),
('ST',1,2,2,1,'Noah','character','814c29328946fc569d568a31c767c4090658e9bcfa53cee1a828c1edf7779afa','nova/audio/turns/en-fa/ST/m01/c02/l02/t01-noah-6ff8923f8bb4.mp3',882),
('ST',1,2,2,2,'Mina','learner','3aa91661bdc96e4951cf372eef1e309a472e2c45e63f461298efb3067967b0c1','nova/audio/turns/en-fa/ST/m01/c02/l02/t02-mina-9205ea967080.mp3',1393),
('ST',1,2,2,3,'Noah','character','b75fdf798d6c6f47026249fb5e45ffac54a5872575ecbd772ba9467c9ada0a2b','nova/audio/turns/en-fa/ST/m01/c02/l02/t03-noah-bd0fdc3e30cd.mp3',418),
('ST',1,2,2,4,'Mina','learner','68082b613e502a457bcdc6b5309ac444ff6b1e90d9cde45d8c5d3d4a41c1b7d6','nova/audio/turns/en-fa/ST/m01/c02/l02/t04-mina-1f9ffe8acdfa.mp3',975),
('ST',1,2,3,1,'Noah','character','14db5876511fe026bf3feb7d8f70285cd885424001a634a83b2ff91e3c1d2d39','nova/audio/turns/en-fa/ST/m01/c02/l03/t01-noah-dbffa4a1db1b.mp3',697),
('ST',1,2,3,2,'Mina','learner','cc07850c5e9229139005fd230419a5d512fb253e67cf4cfd4d58100b9d016a20','nova/audio/turns/en-fa/ST/m01/c02/l03/t02-mina-29ebc1868f94.mp3',1207),
('ST',1,2,3,3,'Noah','character','eaca3758421a2668e0e21a4789fec299f6fb1e9359f5f989cc29fc9104883b68','nova/audio/turns/en-fa/ST/m01/c02/l03/t03-noah-77fad820be60.mp3',557),
('ST',1,2,3,4,'Mina','learner','7ece891b3313fa6f0fe325e0d3d472b919a4d20d5a92e0d55e8cee9a80f30f73','nova/audio/turns/en-fa/ST/m01/c02/l03/t04-mina-03b99a0d9a1d.mp3',929),
('ST',1,2,4,1,'Noah','character','5dcee9bdca119172f74efe0a5d17eb255f5e6f5d9081287ac6d7f47f434f32ec','nova/audio/turns/en-fa/ST/m01/c02/l04/t01-noah-e6a2b55958f6.mp3',1022),
('ST',1,2,4,2,'Mina','learner','998dc661044d32a813dd5638440e680983f31bad4c356cfccdc82256ccef66be','nova/audio/turns/en-fa/ST/m01/c02/l04/t02-mina-8de043adbf8c.mp3',1022),
('ST',1,2,4,3,'Noah','character','eaca3758421a2668e0e21a4789fec299f6fb1e9359f5f989cc29fc9104883b68','nova/audio/turns/en-fa/ST/m01/c02/l04/t03-noah-aa5e5aba5d57.mp3',697),
('ST',1,2,4,4,'Mina','learner','1ff49d1ec768fc4281841972b015a1175b17d24ca9a965fd6b934e13e9b590bd','nova/audio/turns/en-fa/ST/m01/c02/l04/t04-mina-4dcfd8e22a3b.mp3',975),
('ST',1,3,1,1,'Ava','character','9c290689510ed939b883047afbb65d7015b5cc62e7cb1245f8455f488e7609b7','nova/audio/turns/en-fa/ST/m01/c03/l01/t01-ava-bbb39771dc55.mp3',1068),
('ST',1,3,1,2,'Mina','learner','48773d891056c30b987051c8df6143dde4eda1278f3730b45ee7072cd5565c55','nova/audio/turns/en-fa/ST/m01/c03/l01/t02-mina-03dfc8bbb664.mp3',1300),
('ST',1,3,1,3,'Ava','character','39954823f73a76e35ec7280de44b2eb4b26399ecdc00a2b3640db22375d3a4b3','nova/audio/turns/en-fa/ST/m01/c03/l01/t03-ava-726c1e4fa216.mp3',1022),
('ST',1,3,1,4,'Mina','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/ST/m01/c03/l01/t04-mina-3d7622ff3cfc.mp3',1161),
('ST',1,3,2,1,'Ava','character','cb9175be3e2b4ecd64fa4bd046be938690cf3d7dad0b3efaed3a8a60092a58fa','nova/audio/turns/en-fa/ST/m01/c03/l02/t01-ava-1c1acb22cfb0.mp3',1115),
('ST',1,3,2,2,'Mina','learner','998dc661044d32a813dd5638440e680983f31bad4c356cfccdc82256ccef66be','nova/audio/turns/en-fa/ST/m01/c03/l02/t02-mina-e9821e0a1a7f.mp3',1115),
('ST',1,3,2,3,'Ava','character','378407b03a6e216ba6c8f8cc6a265624ec939300006d643be20a03b061b9f2a0','nova/audio/turns/en-fa/ST/m01/c03/l02/t03-ava-a1876babd692.mp3',650),
('ST',1,3,2,4,'Mina','learner','39954823f73a76e35ec7280de44b2eb4b26399ecdc00a2b3640db22375d3a4b3','nova/audio/turns/en-fa/ST/m01/c03/l02/t04-mina-36fe058ef8ad.mp3',1115),
('ST',1,3,2,5,'Ava','character','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/ST/m01/c03/l02/t05-ava-a1b62a9337e2.mp3',1022),
('ST',1,3,2,6,'Mina','learner','3d5d79652dc4770b0bc1ffbad055c6c5cd4fb1657d1d70e70af25776128590af','nova/audio/turns/en-fa/ST/m01/c03/l02/t06-mina-a770d6bb9dc9.mp3',1022),
('ST',1,3,3,1,'Ava','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m01/c03/l03/t01-ava-ba9fc0a47ff9.mp3',743),
('ST',1,3,3,2,'Mina','learner','7cb19a4db62e98160544af71a8e5423119fc3ee93da67f6066dc16eefc5ed62f','nova/audio/turns/en-fa/ST/m01/c03/l03/t02-mina-6a7f0b29c86d.mp3',1022),
('ST',1,3,3,3,'Ava','character','378407b03a6e216ba6c8f8cc6a265624ec939300006d643be20a03b061b9f2a0','nova/audio/turns/en-fa/ST/m01/c03/l03/t03-ava-582c1d161fbf.mp3',697),
('ST',1,3,3,4,'Mina','learner','88534a0e309e1d4c339dd6522984866a7b9e93fc9f4b15bd38a2b355b79659ee','nova/audio/turns/en-fa/ST/m01/c03/l03/t04-mina-7d3c436aeca4.mp3',697),
('ST',1,3,3,5,'Ava','character','39954823f73a76e35ec7280de44b2eb4b26399ecdc00a2b3640db22375d3a4b3','nova/audio/turns/en-fa/ST/m01/c03/l03/t05-ava-dd02f84f2d79.mp3',882),
('ST',1,3,3,6,'Mina','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/ST/m01/c03/l03/t06-mina-3d7622ff3cfc.mp3',1161),
('ST',1,3,4,1,'Ava','character','9c290689510ed939b883047afbb65d7015b5cc62e7cb1245f8455f488e7609b7','nova/audio/turns/en-fa/ST/m01/c03/l04/t01-ava-bbb39771dc55.mp3',1068),
('ST',1,3,4,2,'Mina','learner','48773d891056c30b987051c8df6143dde4eda1278f3730b45ee7072cd5565c55','nova/audio/turns/en-fa/ST/m01/c03/l04/t02-mina-8b287ec7fd97.mp3',1068),
('ST',1,3,4,3,'Ava','character','1df274edd580538a78b22db2830ff0c678df2d6ab91ea86bd356ede74810ef8b','nova/audio/turns/en-fa/ST/m01/c03/l04/t03-ava-a8893955546f.mp3',1115),
('ST',1,3,4,4,'Mina','learner','29cba7161b4a2e0334249261c3630eb9c9a74f97c73165d8e013a65851854b80','nova/audio/turns/en-fa/ST/m01/c03/l04/t04-mina-a6657485687f.mp3',1300),
('ST',1,4,1,1,'Ava','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m01/c04/l01/t01-ava-ba9fc0a47ff9.mp3',743),
('ST',1,4,1,2,'Mina','learner','7cb19a4db62e98160544af71a8e5423119fc3ee93da67f6066dc16eefc5ed62f','nova/audio/turns/en-fa/ST/m01/c04/l01/t02-mina-3b390fecde6b.mp3',882),
('ST',1,4,1,3,'Ava','character','68514b65884697a4725d4b231dd376aa745abfd4feb3cf9aaa21e4194e2b8acc','nova/audio/turns/en-fa/ST/m01/c04/l01/t03-ava-eaa680ba923f.mp3',789),
('ST',1,4,1,4,'Mina','learner','b730320655ef331c86a45159cbcee93018d4076409350ad9ec2482ea8e38db55','nova/audio/turns/en-fa/ST/m01/c04/l01/t04-mina-261a14b4a42a.mp3',1207),
('ST',1,4,2,1,'Ava','character','68514b65884697a4725d4b231dd376aa745abfd4feb3cf9aaa21e4194e2b8acc','nova/audio/turns/en-fa/ST/m01/c04/l02/t01-ava-fc55ff9d0cd8.mp3',975),
('ST',1,4,2,2,'Mina','learner','b730320655ef331c86a45159cbcee93018d4076409350ad9ec2482ea8e38db55','nova/audio/turns/en-fa/ST/m01/c04/l02/t02-mina-1938ae7b2655.mp3',1486),
('ST',1,4,2,3,'Ava','character','3765ea16037b1bc3a463f8fe8b02e133ab6d3eb72d7cb4748dacec664684bc1f','nova/audio/turns/en-fa/ST/m01/c04/l02/t03-ava-9ee4f9cf07ee.mp3',418),
('ST',1,4,2,4,'Mina','learner','1aa7b1c1d5fb1fd6d299eae251a665c7898baeb43d48fb6b8a5b76da6c6ef739','nova/audio/turns/en-fa/ST/m01/c04/l02/t04-mina-95ce83d91487.mp3',743),
('ST',1,4,3,1,'Ava','character','69022306d1d601e76385764a2a7bc0be5cf527ef3e3bc09209e376d6627125d2','nova/audio/turns/en-fa/ST/m01/c04/l03/t01-ava-93c8123ec7f2.mp3',743),
('ST',1,4,3,2,'Mina','learner','b033b5adb451a8d9f27d0ee1abda06a211a490623fa848195dfa326fba103579','nova/audio/turns/en-fa/ST/m01/c04/l03/t02-mina-3767822c2c20.mp3',1022),
('ST',1,4,3,3,'Ava','character','68514b65884697a4725d4b231dd376aa745abfd4feb3cf9aaa21e4194e2b8acc','nova/audio/turns/en-fa/ST/m01/c04/l03/t03-ava-5db6eb539738.mp3',836),
('ST',1,4,3,4,'Mina','learner','c35ab2074f8a3df26da8a1b6379b1681f33aa7664241070920497208286e1a6d','nova/audio/turns/en-fa/ST/m01/c04/l03/t04-mina-c6cca628a752.mp3',1161),
('ST',1,4,4,1,'Ava','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m01/c04/l04/t01-ava-4ac4e7a7d99e.mp3',789),
('ST',1,4,4,2,'Mina','learner','b033b5adb451a8d9f27d0ee1abda06a211a490623fa848195dfa326fba103579','nova/audio/turns/en-fa/ST/m01/c04/l04/t02-mina-06819cdd6d63.mp3',743),
('ST',1,4,4,3,'Ava','character','68514b65884697a4725d4b231dd376aa745abfd4feb3cf9aaa21e4194e2b8acc','nova/audio/turns/en-fa/ST/m01/c04/l04/t03-ava-9f64b25e7824.mp3',1207),
('ST',1,4,4,4,'Mina','learner','1daca7c3572711a0a158fc1e21305eee8bc658761447a4440bbaf34b038093ab','nova/audio/turns/en-fa/ST/m01/c04/l04/t04-mina-ba1636d22738.mp3',2276),
('ST',1,4,4,5,'Ava','character','3e67e2821cdebe3708f9a5388ba59dbed8dd82e3f8befa978078a3f5730a563f','nova/audio/turns/en-fa/ST/m01/c04/l04/t05-ava-265f200d218e.mp3',836),
('ST',1,4,4,6,'Mina','learner','3d5d79652dc4770b0bc1ffbad055c6c5cd4fb1657d1d70e70af25776128590af','nova/audio/turns/en-fa/ST/m01/c04/l04/t06-mina-40c24021718d.mp3',975),
('ST',1,5,1,1,'Ava','character','68514b65884697a4725d4b231dd376aa745abfd4feb3cf9aaa21e4194e2b8acc','nova/audio/turns/en-fa/ST/m01/c05/l01/t01-ava-fc55ff9d0cd8.mp3',975),
('ST',1,5,1,2,'Mina','learner','b730320655ef331c86a45159cbcee93018d4076409350ad9ec2482ea8e38db55','nova/audio/turns/en-fa/ST/m01/c05/l01/t02-mina-23b325bb16b8.mp3',1347),
('ST',1,5,1,3,'Ava','character','e1334459649844666e910dcc273dbde5a37a83e8cd12b6c7ea9ee1d20ada4637','nova/audio/turns/en-fa/ST/m01/c05/l01/t03-ava-ac27103f3b67.mp3',743),
('ST',1,5,1,4,'Mina','learner','3d5d79652dc4770b0bc1ffbad055c6c5cd4fb1657d1d70e70af25776128590af','nova/audio/turns/en-fa/ST/m01/c05/l01/t04-mina-54e3ecda5bf5.mp3',1022),
('ST',1,5,2,1,'Ava','character','e1334459649844666e910dcc273dbde5a37a83e8cd12b6c7ea9ee1d20ada4637','nova/audio/turns/en-fa/ST/m01/c05/l02/t01-ava-f3d5c0ec2a66.mp3',836),
('ST',1,5,2,2,'Mina','learner','3d5d79652dc4770b0bc1ffbad055c6c5cd4fb1657d1d70e70af25776128590af','nova/audio/turns/en-fa/ST/m01/c05/l02/t02-mina-578c7ccf6259.mp3',882),
('ST',1,5,2,3,'Ava','character','6fa5881a15601e1a2a6c8d084f1f99637261f3ae5172a5963d2ff06fd4e77bc6','nova/audio/turns/en-fa/ST/m01/c05/l02/t03-ava-e5857e2904f6.mp3',836),
('ST',1,5,2,4,'Mina','learner','6fa5881a15601e1a2a6c8d084f1f99637261f3ae5172a5963d2ff06fd4e77bc6','nova/audio/turns/en-fa/ST/m01/c05/l02/t04-mina-ebc46cd42f44.mp3',975),
('ST',1,5,3,1,'Ava','character','57ab71dcb79904419832f8d4c8810b99b79d9bc2af94a733c1fdd2a57d47f874','nova/audio/turns/en-fa/ST/m01/c05/l03/t01-ava-f5a209a14a7b.mp3',650),
('ST',1,5,3,2,'Mina','learner','57ab71dcb79904419832f8d4c8810b99b79d9bc2af94a733c1fdd2a57d47f874','nova/audio/turns/en-fa/ST/m01/c05/l03/t02-mina-fca56a4c60f2.mp3',929),
('ST',1,5,3,3,'Ava','character','6fa5881a15601e1a2a6c8d084f1f99637261f3ae5172a5963d2ff06fd4e77bc6','nova/audio/turns/en-fa/ST/m01/c05/l03/t03-ava-65a35bb6547b.mp3',650),
('ST',1,5,3,4,'Mina','learner','1cb7b221b7adda1cf4c4724b32369394580480c84ab835795d608ac59aa13002','nova/audio/turns/en-fa/ST/m01/c05/l03/t04-mina-56b9ad67fd22.mp3',743),
('ST',1,5,4,1,'Ava','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m01/c05/l04/t01-ava-4ac4e7a7d99e.mp3',789),
('ST',1,5,4,2,'Mina','learner','b033b5adb451a8d9f27d0ee1abda06a211a490623fa848195dfa326fba103579','nova/audio/turns/en-fa/ST/m01/c05/l04/t02-mina-06819cdd6d63.mp3',743),
('ST',1,5,4,3,'Ava','character','68514b65884697a4725d4b231dd376aa745abfd4feb3cf9aaa21e4194e2b8acc','nova/audio/turns/en-fa/ST/m01/c05/l04/t03-ava-35807e03f548.mp3',836),
('ST',1,5,4,4,'Mina','learner','b730320655ef331c86a45159cbcee93018d4076409350ad9ec2482ea8e38db55','nova/audio/turns/en-fa/ST/m01/c05/l04/t04-mina-b104b6a1acb6.mp3',1300),
('ST',1,5,4,5,'Ava','character','8df96722ea691f709876899e4ba7d047e1f5c20891a34120f4506dfb65a536f1','nova/audio/turns/en-fa/ST/m01/c05/l04/t05-ava-798a4f50094e.mp3',929),
('ST',1,5,4,6,'Mina','learner','f36c2a849a252c7ff7b82ae7b5a7c556b5614365a95e1474be26538f59505fa4','nova/audio/turns/en-fa/ST/m01/c05/l04/t06-mina-9be006aaaa86.mp3',1300),
('ST',2,1,1,1,'Liam','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m02/c01/l01/t01-liam-8f3f50e1ee3e.mp3',743),
('ST',2,1,1,2,'Mina','learner','a1afe70ec169c43d53a95cabc746415f7e0897e58897e0d618940f3fab5a9058','nova/audio/turns/en-fa/ST/m02/c01/l01/t02-mina-bb3c99d8b86f.mp3',743),
('ST',2,1,1,3,'Liam','character','b7f28b09afe416287024cabcba27e176d8516368662a2cd99e283e4ad219e46b','nova/audio/turns/en-fa/ST/m02/c01/l01/t03-liam-f7c964a4f71e.mp3',929),
('ST',2,1,1,4,'Mina','learner','f940f5e58060c0ca507347c69ea6617ab5900fdb3d8251dee1b67766bc8ec831','nova/audio/turns/en-fa/ST/m02/c01/l01/t04-mina-2c1992394189.mp3',1161),
('ST',2,1,2,1,'Liam','character','b7f28b09afe416287024cabcba27e176d8516368662a2cd99e283e4ad219e46b','nova/audio/turns/en-fa/ST/m02/c01/l02/t01-liam-cfc0febf2871.mp3',1300),
('ST',2,1,2,2,'Mina','learner','ff1f53284e870ac45425587dc10b9383bbdc998463576a70af00e2b67fdb4d1c','nova/audio/turns/en-fa/ST/m02/c01/l02/t02-mina-890903608acd.mp3',1765),
('ST',2,1,2,3,'Liam','character','0a6529df373614ec131116fd48ff8d06b43a07d8e9b5f94d82f5aa62afebc6ce','nova/audio/turns/en-fa/ST/m02/c01/l02/t03-liam-151527e1badd.mp3',464),
('ST',2,1,2,4,'Mina','learner','85eba099ccf118e35f95a4c7826599b05d77e07cbe11c234912be49955cc43e3','nova/audio/turns/en-fa/ST/m02/c01/l02/t04-mina-ae50a09897ed.mp3',1207),
('ST',2,1,3,1,'Liam','character','f940f5e58060c0ca507347c69ea6617ab5900fdb3d8251dee1b67766bc8ec831','nova/audio/turns/en-fa/ST/m02/c01/l03/t01-liam-d9527ffcbf1a.mp3',975),
('ST',2,1,3,2,'Mina','learner','b7f28b09afe416287024cabcba27e176d8516368662a2cd99e283e4ad219e46b','nova/audio/turns/en-fa/ST/m02/c01/l03/t02-mina-82c21aa2646c.mp3',1207),
('ST',2,1,3,3,'Liam','character','f2382183b19e3ad7b787a31ba504693b595feafbcde9000c4dc3bbb84f80e26a','nova/audio/turns/en-fa/ST/m02/c01/l03/t03-liam-3e4ed9cf10f0.mp3',1115),
('ST',2,1,3,4,'Mina','learner','1eff8a6a46836f5346b81a89acdf445b5f71aa4c528072bc7a782c0774653823','nova/audio/turns/en-fa/ST/m02/c01/l03/t04-mina-a5dc815bb368.mp3',743),
('ST',2,1,4,1,'Liam','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m02/c01/l04/t01-liam-8f3f50e1ee3e.mp3',743),
('ST',2,1,4,2,'Mina','learner','a1afe70ec169c43d53a95cabc746415f7e0897e58897e0d618940f3fab5a9058','nova/audio/turns/en-fa/ST/m02/c01/l04/t02-mina-bb3c99d8b86f.mp3',743),
('ST',2,1,4,3,'Liam','character','b7f28b09afe416287024cabcba27e176d8516368662a2cd99e283e4ad219e46b','nova/audio/turns/en-fa/ST/m02/c01/l04/t03-liam-3cdc776db9db.mp3',836),
('ST',2,1,4,4,'Mina','learner','f2382183b19e3ad7b787a31ba504693b595feafbcde9000c4dc3bbb84f80e26a','nova/audio/turns/en-fa/ST/m02/c01/l04/t04-mina-91a50e336c37.mp3',1022),
('ST',2,1,4,5,'Liam','character','918f9ba11e6c62d393f4b9f2501bab5b5edf5c291bf2e1cf94c097194c9f1e98','nova/audio/turns/en-fa/ST/m02/c01/l04/t05-liam-0682776bce5e.mp3',1254),
('ST',2,1,4,6,'Mina','learner','69da1a01cb3aaef7f578354b90c357abe635c4c8630f96cd58c7c30fc1af0ed4','nova/audio/turns/en-fa/ST/m02/c01/l04/t06-mina-e91f1603d8f3.mp3',2043),
('ST',2,2,1,1,'Liam','character','734411ae67654b1938925bd44a57acb9978fde736dc62f666f769035153a02ed','nova/audio/turns/en-fa/ST/m02/c02/l01/t01-liam-8f3f50e1ee3e.mp3',743),
('ST',2,2,1,2,'Mina','learner','a1afe70ec169c43d53a95cabc746415f7e0897e58897e0d618940f3fab5a9058','nova/audio/turns/en-fa/ST/m02/c02/l01/t02-mina-315a40fd5839.mp3',882),
('ST',2,2,1,3,'Liam','character','b84096f3657a6ef5166af4809e8ea34259bd6d7d596b943f1f9b693357473169','nova/audio/turns/en-fa/ST/m02/c02/l01/t03-liam-a3b35cee4980.mp3',882),
('ST',2,2,1,4,'Mina','learner','5dfce23c275fa6fab08233cefbad28edad8515795b3e7d9e445c869c89469fe1','nova/audio/turns/en-fa/ST/m02/c02/l01/t04-mina-e67652ccb8ef.mp3',1254),
('ST',2,2,2,1,'Liam','character','68995f59b44453a4ef08d5133fc8bf8c7ef47e8384e092479db25b0385993213','nova/audio/turns/en-fa/ST/m02/c02/l02/t01-liam-5d305f191213.mp3',1393),
('ST',2,2,2,2,'Mina','learner','5bb5269d147552d6284c174b1308821cb62267580b4b5c5bd5c9fbd279fefc01','nova/audio/turns/en-fa/ST/m02/c02/l02/t02-mina-4e05d9671367.mp3',1300),
('ST',2,2,2,3,'Liam','character','78e0ed4d2dca3888e3aadbe00b22e7908660e7bd2dedc728e7f4394aa8b05b08','nova/audio/turns/en-fa/ST/m02/c02/l02/t03-liam-47b6129e94cf.mp3',975),
('ST',2,2,2,4,'Mina','learner','722f2b1e47499f559dda8254453c95403e428098f67a57475f8215418785ac9d','nova/audio/turns/en-fa/ST/m02/c02/l02/t04-mina-e7dafc5e90ae.mp3',1950),
('ST',2,2,3,1,'Liam','character','a21b37d2e1bd7013748e01f87fa07c75c5edf2216384887cff4fa72fb878e896','nova/audio/turns/en-fa/ST/m02/c02/l03/t01-liam-81f7449a8a73.mp3',1068),
('ST',2,2,3,2,'Mina','learner','abfe2994e15657511c36e09d039634b683d5c4d781eebb243ae812aee76358db','nova/audio/turns/en-fa/ST/m02/c02/l03/t02-mina-610595815009.mp3',1440),
('ST',2,2,3,3,'Liam','character','e01c712c2b1ca66b21a046e988c2cd714c348d8d153117b87c01fbcaa304f292','nova/audio/turns/en-fa/ST/m02/c02/l03/t03-liam-a3e09c82c379.mp3',975),
('ST',2,2,3,4,'Mina','learner','76f268b9c699badb56916e10010262354b246cf73bedefe262c2b24966a4d34d','nova/audio/turns/en-fa/ST/m02/c02/l03/t04-mina-8465df8a1d32.mp3',1300),
('ST',2,2,4,1,'Liam','character','4e72384a272b1985be882c5c91bfa122e21e4da1d623a325f6bdfc6f4dd15dcf','nova/audio/turns/en-fa/ST/m02/c02/l04/t01-liam-aaa8b902bd5e.mp3',929),
('ST',2,2,4,2,'Mina','learner','cb27a343e5199c79b1a22ee236b6df25df7960a5a2f34d1e5351b5e7edd7ebb7','nova/audio/turns/en-fa/ST/m02/c02/l04/t02-mina-ba4ab44d8ac2.mp3',1533),
('ST',2,2,4,3,'Liam','character','b84096f3657a6ef5166af4809e8ea34259bd6d7d596b943f1f9b693357473169','nova/audio/turns/en-fa/ST/m02/c02/l04/t03-liam-52788ea3f7f8.mp3',789),
('ST',2,2,4,4,'Mina','learner','e33645160e1bb79fb4e7ea7f32346b9dce589d3a98beac3259241060ebbdc8a8','nova/audio/turns/en-fa/ST/m02/c02/l04/t04-mina-2f88d051cd18.mp3',2043),
('ST',2,2,4,5,'Liam','character','1eff8a6a46836f5346b81a89acdf445b5f71aa4c528072bc7a782c0774653823','nova/audio/turns/en-fa/ST/m02/c02/l04/t05-liam-e111ab586975.mp3',511),
('ST',2,2,4,6,'Mina','learner','1aa7b1c1d5fb1fd6d299eae251a665c7898baeb43d48fb6b8a5b76da6c6ef739','nova/audio/turns/en-fa/ST/m02/c02/l04/t06-mina-55cdaca56c5f.mp3',743);

DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_turn_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='en' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova en-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_turn_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order,
           COUNT(c.id) AS matched_rows
    FROM nova_turn_audio_updates AS u
    LEFT JOIN levels AS lv
      ON lv.course_id=v_course AND lv.cefr_level=u.cefr_level
    LEFT JOIN modules AS m
      ON m.level_id=lv.id AND m.sort_order=u.module_order
    LEFT JOIN chapters AS ch
      ON ch.module_id=m.id AND ch.sort_order=u.chapter_order
    LEFT JOIN lessons AS l
      ON l.chapter_id=ch.id AND l.sort_order=u.lesson_order
    LEFT JOIN turns AS t
      ON t.lesson_id=l.id AND t.sort_order=u.turn_order
     AND t.role=u.turn_role AND SHA2(t.text,256)=u.text_sha256
    LEFT JOIN characters AS c
      ON c.id=t.character_id AND c.course_id=v_course AND c.name=u.character_name
    GROUP BY u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order
    HAVING COUNT(c.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Turn locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE turns AS t
  JOIN lessons AS l ON l.id=t.lesson_id
  JOIN chapters AS ch ON ch.id=l.chapter_id
  JOIN modules AS m ON m.id=ch.module_id
  JOIN levels AS lv ON lv.id=m.level_id AND lv.course_id=v_course
  JOIN characters AS c ON c.id=t.character_id AND c.course_id=v_course
  JOIN nova_turn_audio_updates AS u
    ON u.cefr_level=lv.cefr_level
   AND u.module_order=m.sort_order
   AND u.chapter_order=ch.sort_order
   AND u.lesson_order=l.sort_order
   AND u.turn_order=t.sort_order
   AND u.character_name=c.name
   AND u.turn_role=t.role
   AND u.text_sha256=SHA2(t.text,256)
  SET t.audio_url=u.audio_url,
      t.audio_duration_ms=u.audio_duration_ms;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_turns, v_changed AS changed_turns;
END$$
DELIMITER ;
CALL apply_nova_turn_audio();
DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
