-- Generated by nova/tts/nova_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to turns.audio_url and turns.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
CREATE TEMPORARY TABLE nova_turn_audio_updates (
  cefr_level VARCHAR(8) NOT NULL,
  module_order INT UNSIGNED NOT NULL,
  chapter_order INT UNSIGNED NOT NULL,
  lesson_order INT UNSIGNED NOT NULL,
  turn_order INT UNSIGNED NOT NULL,
  character_name VARCHAR(120) NOT NULL,
  turn_role VARCHAR(16) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL,
  PRIMARY KEY (cefr_level,module_order,chapter_order,lesson_order,turn_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_turn_audio_updates (cefr_level,module_order,chapter_order,lesson_order,turn_order,character_name,turn_role,text_sha256,audio_url,audio_duration_ms) VALUES
('A1',1,1,1,1,'Maya','character','334d016f755cd6dc58c53a86e183882f8ec14f52fb05345887c8a5edd42c87b7','nova/audio/turns/en-fa/A1/m01/c01/l01/t01-maya-04ddec83187e.mp3',604),
('A1',1,1,1,2,'Arman','learner','334d016f755cd6dc58c53a86e183882f8ec14f52fb05345887c8a5edd42c87b7','nova/audio/turns/en-fa/A1/m01/c01/l01/t02-arman-fed8102b13e2.mp3',557),
('A1',1,1,1,3,'Maya','character','6e80969179614a3c8c885b181e439b6f021081bc6e49c671f4fef4f222f1409a','nova/audio/turns/en-fa/A1/m01/c01/l01/t03-maya-77303d7649fa.mp3',650),
('A1',1,1,1,4,'Arman','learner','1de632efd6f69b42780d8e7fc6bfb303960675c21167c92ce1858af116cad5ba','nova/audio/turns/en-fa/A1/m01/c01/l01/t04-arman-9ce8f27681bd.mp3',1625),
('A1',1,1,1,5,'Maya','character','39954823f73a76e35ec7280de44b2eb4b26399ecdc00a2b3640db22375d3a4b3','nova/audio/turns/en-fa/A1/m01/c01/l01/t05-maya-cf4ea8ea491f.mp3',1207),
('A1',1,1,1,6,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c01/l01/t06-arman-e9a0f2eae369.mp3',2322),
('A1',1,1,1,7,'Maya','character','c0821f4872ce8f94a7a4d48b1ea6bb77e0a0dd13473cae67bc1d59986d37b612','nova/audio/turns/en-fa/A1/m01/c01/l01/t07-maya-da971d37a7b4.mp3',1486),
('A1',1,1,1,8,'Arman','learner','8569efc4ed5a6273140c2b6ec0ab8d99f4398210808fbb7c0cbbae4fbcc21350','nova/audio/turns/en-fa/A1/m01/c01/l01/t08-arman-b05774c8a302.mp3',1022),
('A1',1,1,2,1,'Maya','character','f1308ce0cf77aa9d2d72e967d7cc38a03c6739ced96cd965c79f54efc98093f1','nova/audio/turns/en-fa/A1/m01/c01/l02/t01-maya-23685a3db536.mp3',836),
('A1',1,1,2,2,'Arman','learner','a1a854e8fa345919ea0299c545db2d43f3c01793e54b3095ba1c7d3203bf7ce0','nova/audio/turns/en-fa/A1/m01/c01/l02/t02-arman-27a4546ed5c6.mp3',1904),
('A1',1,1,2,3,'Maya','character','2dd7f3db0bf5a3f71152337e49f4bc1fc214278591cba476a530ba7fb38ba446','nova/audio/turns/en-fa/A1/m01/c01/l02/t03-maya-18288dea0e93.mp3',1950),
('A1',1,1,2,4,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c01/l02/t04-arman-a89a8c76d7e9.mp3',1904),
('A1',1,1,2,5,'Maya','character','733a3a434cd947515440a9a0d1095db01aca40664f3133476c8d71931d367732','nova/audio/turns/en-fa/A1/m01/c01/l02/t05-maya-8872fef4a88d.mp3',1440),
('A1',1,1,2,6,'Arman','learner','50b47fecf1f61dcc0988c9920f41bd092ff55d57e142df875b0e99379471bb66','nova/audio/turns/en-fa/A1/m01/c01/l02/t06-arman-fed1a002b488.mp3',2276),
('A1',1,1,2,7,'Maya','character','ad19b8cc2deb82c31378eef9b6262d5f620332381cdc995f470ec3a2c82585f2','nova/audio/turns/en-fa/A1/m01/c01/l02/t07-maya-ec1291e94eb9.mp3',464),
('A1',1,1,2,8,'Arman','learner','8569efc4ed5a6273140c2b6ec0ab8d99f4398210808fbb7c0cbbae4fbcc21350','nova/audio/turns/en-fa/A1/m01/c01/l02/t08-arman-597db3044056.mp3',1068),
('A1',1,1,3,1,'Maya','character','df287dfc1406ed2b692e1c2c783bb5cec97eac53151ee1d9810397aa0afa0d89','nova/audio/turns/en-fa/A1/m01/c01/l03/t01-maya-35a1f8bb1ff9.mp3',743),
('A1',1,1,3,2,'Arman','learner','95baae5c00575349eccc8f700741fd305588c38d0e9596e89abd6129f8c7cd5a','nova/audio/turns/en-fa/A1/m01/c01/l03/t02-arman-a5da913fd312.mp3',1950),
('A1',1,1,3,3,'Maya','character','2c33dcef91e066247cc05cc403f99dcf572e5bb8f45656fec462270e689916b6','nova/audio/turns/en-fa/A1/m01/c01/l03/t03-maya-624d6cdd97be.mp3',372),
('A1',1,1,3,4,'Arman','learner','0c1c23dc335e76d0716be6f8fbd4a526dc6f58a39960621dd893929e7dcc1bd8','nova/audio/turns/en-fa/A1/m01/c01/l03/t04-arman-b82f6e003f98.mp3',1718),
('A1',1,1,3,5,'Maya','character','9768a1d3c05b0b0ae534915c2c13d56fbe150eaacd5f89c8dc842a69c4c2b21b','nova/audio/turns/en-fa/A1/m01/c01/l03/t05-maya-dccd77743574.mp3',1068),
('A1',1,1,3,6,'Arman','learner','ad19b8cc2deb82c31378eef9b6262d5f620332381cdc995f470ec3a2c82585f2','nova/audio/turns/en-fa/A1/m01/c01/l03/t06-arman-e5dd5b759027.mp3',1115),
('A1',1,1,3,7,'Maya','character','c75befc64765c13ec62f9db96a3bbe70e39f62d23915b6896d4363a90b2a543f','nova/audio/turns/en-fa/A1/m01/c01/l03/t07-maya-fc25d744c585.mp3',511),
('A1',1,1,3,8,'Arman','learner','5f9a2b795615ba6a3d5455fd5624d773fbca5bcd16249c421fd37411dc9837da','nova/audio/turns/en-fa/A1/m01/c01/l03/t08-arman-fa204a0d6b39.mp3',882),
('A1',1,1,4,1,'Maya','character','f5643263c263b7447c40b3d464b1e0262865cebff84c47ec775f846534e39f73','nova/audio/turns/en-fa/A1/m01/c01/l04/t01-maya-b52f74ccf126.mp3',882),
('A1',1,1,4,2,'Arman','learner','334d016f755cd6dc58c53a86e183882f8ec14f52fb05345887c8a5edd42c87b7','nova/audio/turns/en-fa/A1/m01/c01/l04/t02-arman-8e9d220b3cb5.mp3',650),
('A1',1,1,4,3,'Maya','character','f1308ce0cf77aa9d2d72e967d7cc38a03c6739ced96cd965c79f54efc98093f1','nova/audio/turns/en-fa/A1/m01/c01/l04/t03-maya-cb4e049be09b.mp3',789),
('A1',1,1,4,4,'Arman','learner','a1a854e8fa345919ea0299c545db2d43f3c01793e54b3095ba1c7d3203bf7ce0','nova/audio/turns/en-fa/A1/m01/c01/l04/t04-arman-99a7040839fc.mp3',1811),
('A1',1,1,4,5,'Maya','character','f62f5a5e3a4cdb8f099e9ac7df8aefd679d7bacff5b09c523a9ccce1acbdcbb8','nova/audio/turns/en-fa/A1/m01/c01/l04/t05-maya-516896606644.mp3',1440),
('A1',1,1,4,6,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c01/l04/t06-arman-4ae307de24ba.mp3',2322),
('A1',1,1,4,7,'Maya','character','5e9a6acbcb3d2712efdd179b2ef753a0f68f5fd62d86addcb6bcdf92c74425e9','nova/audio/turns/en-fa/A1/m01/c01/l04/t07-maya-604797cd0123.mp3',1300),
('A1',1,1,4,8,'Arman','learner','1cb7b221b7adda1cf4c4724b32369394580480c84ab835795d608ac59aa13002','nova/audio/turns/en-fa/A1/m01/c01/l04/t08-arman-f4aaf8ea6c71.mp3',1022),
('A1',1,2,1,1,'Maya','character','4cb0d79154e71344f5ece72b33ab3ee241fa99f72ceb09344211e1d40c7fb41f','nova/audio/turns/en-fa/A1/m01/c02/l01/t01-maya-0d510141b5d7.mp3',836),
('A1',1,2,1,2,'Arman','learner','f0399e3dc4021a153d672663fda09ebd2512f736c65c77effd6f5287ac6986d3','nova/audio/turns/en-fa/A1/m01/c02/l01/t02-arman-573ad4daaa88.mp3',1347),
('A1',1,2,1,3,'Maya','character','63265a79774350462d4ce11d5a90687ff8e6f2511bb512e0409be568b6be7046','nova/audio/turns/en-fa/A1/m01/c02/l01/t03-maya-7b86880d24f0.mp3',697),
('A1',1,2,1,4,'Arman','learner','5dfce23c275fa6fab08233cefbad28edad8515795b3e7d9e445c869c89469fe1','nova/audio/turns/en-fa/A1/m01/c02/l01/t04-arman-23d8618b4284.mp3',1672),
('A1',1,2,1,5,'Maya','character','6684d1d06ac106658427631eabebcd059808a280dc034d22ec4a2e73fdf102e9','nova/audio/turns/en-fa/A1/m01/c02/l01/t05-maya-5efb57fa0669.mp3',1533),
('A1',1,2,1,6,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c02/l01/t06-arman-9cd78f273448.mp3',2090),
('A1',1,2,1,7,'Maya','character','c0821f4872ce8f94a7a4d48b1ea6bb77e0a0dd13473cae67bc1d59986d37b612','nova/audio/turns/en-fa/A1/m01/c02/l01/t07-maya-da971d37a7b4.mp3',1486),
('A1',1,2,1,8,'Arman','learner','8569efc4ed5a6273140c2b6ec0ab8d99f4398210808fbb7c0cbbae4fbcc21350','nova/audio/turns/en-fa/A1/m01/c02/l01/t08-arman-b05774c8a302.mp3',1022),
('A1',1,2,2,1,'Maya','character','63265a79774350462d4ce11d5a90687ff8e6f2511bb512e0409be568b6be7046','nova/audio/turns/en-fa/A1/m01/c02/l02/t01-maya-54a1bae9c9b1.mp3',743),
('A1',1,2,2,2,'Arman','learner','5dfce23c275fa6fab08233cefbad28edad8515795b3e7d9e445c869c89469fe1','nova/audio/turns/en-fa/A1/m01/c02/l02/t02-arman-d5b947876948.mp3',1858),
('A1',1,2,2,3,'Maya','character','1a87f42479fea92ef47c26eb741e899a68959fc69975e1a9d5e5082bcd54ab93','nova/audio/turns/en-fa/A1/m01/c02/l02/t03-maya-f1dc2fa87557.mp3',650),
('A1',1,2,2,4,'Arman','learner','8aa468df3414f4f9e2842fee0893ef16c4b8d2b0d952b815325613df7b280f9d','nova/audio/turns/en-fa/A1/m01/c02/l02/t04-arman-494a79896ec0.mp3',2647),
('A1',1,2,2,5,'Maya','character','521bf69b4bffec6abdc7df6d99da406ff80497355dd5fcbac7b1cd48caa5e8af','nova/audio/turns/en-fa/A1/m01/c02/l02/t05-maya-58e6eeab176b.mp3',1486),
('A1',1,2,2,6,'Arman','learner','08db07b08be6a55cb131e075104d4fc3f635a3e621256cf9bd4e6c585c9117b9','nova/audio/turns/en-fa/A1/m01/c02/l02/t06-arman-ba166ba7b2a3.mp3',2740),
('A1',1,2,2,7,'Maya','character','ad19b8cc2deb82c31378eef9b6262d5f620332381cdc995f470ec3a2c82585f2','nova/audio/turns/en-fa/A1/m01/c02/l02/t07-maya-c82e71f23d21.mp3',511),
('A1',1,2,2,8,'Arman','learner','8569efc4ed5a6273140c2b6ec0ab8d99f4398210808fbb7c0cbbae4fbcc21350','nova/audio/turns/en-fa/A1/m01/c02/l02/t08-arman-597db3044056.mp3',1068),
('A1',1,2,3,1,'Maya','character','cb9175be3e2b4ecd64fa4bd046be938690cf3d7dad0b3efaed3a8a60092a58fa','nova/audio/turns/en-fa/A1/m01/c02/l03/t01-maya-673394af2da5.mp3',929),
('A1',1,2,3,2,'Arman','learner','a1a854e8fa345919ea0299c545db2d43f3c01793e54b3095ba1c7d3203bf7ce0','nova/audio/turns/en-fa/A1/m01/c02/l03/t02-arman-9a26f7568847.mp3',1718),
('A1',1,2,3,3,'Maya','character','63265a79774350462d4ce11d5a90687ff8e6f2511bb512e0409be568b6be7046','nova/audio/turns/en-fa/A1/m01/c02/l03/t03-maya-ececc93fe069.mp3',1068),
('A1',1,2,3,4,'Arman','learner','5dfce23c275fa6fab08233cefbad28edad8515795b3e7d9e445c869c89469fe1','nova/audio/turns/en-fa/A1/m01/c02/l03/t04-arman-6c96ba69640c.mp3',1533),
('A1',1,2,3,5,'Maya','character','39954823f73a76e35ec7280de44b2eb4b26399ecdc00a2b3640db22375d3a4b3','nova/audio/turns/en-fa/A1/m01/c02/l03/t05-maya-dab9452c4c1f.mp3',1115),
('A1',1,2,3,6,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c02/l03/t06-arman-f5dafc0acabd.mp3',1858),
('A1',1,2,3,7,'Maya','character','3e09fa7d1d47e83815829273edda0607807df42d45b103536c98fb4c78964ef1','nova/audio/turns/en-fa/A1/m01/c02/l03/t07-maya-2238cc2bab31.mp3',975),
('A1',1,2,3,8,'Arman','learner','1cb7b221b7adda1cf4c4724b32369394580480c84ab835795d608ac59aa13002','nova/audio/turns/en-fa/A1/m01/c02/l03/t08-arman-52ce41623e04.mp3',1068),
('A1',1,2,4,1,'Maya','character','6b30abce6d2d70c0ca773bf46d2f26ffbc83d59d633877c67a45a900e20e4abe','nova/audio/turns/en-fa/A1/m01/c02/l04/t01-maya-a7cab986047e.mp3',1533),
('A1',1,2,4,2,'Arman','learner','09930b2fa7d6b78d896f90b1880791ebc3467dfd7ecc8357eff9fc98e321ccce','nova/audio/turns/en-fa/A1/m01/c02/l04/t02-arman-f7dac187ac1d.mp3',2136),
('A1',1,2,4,3,'Maya','character','63265a79774350462d4ce11d5a90687ff8e6f2511bb512e0409be568b6be7046','nova/audio/turns/en-fa/A1/m01/c02/l04/t03-maya-783a3ee7e895.mp3',650),
('A1',1,2,4,4,'Arman','learner','5dfce23c275fa6fab08233cefbad28edad8515795b3e7d9e445c869c89469fe1','nova/audio/turns/en-fa/A1/m01/c02/l04/t04-arman-fa6dec8e7a7d.mp3',1765),
('A1',1,2,4,5,'Maya','character','f62f5a5e3a4cdb8f099e9ac7df8aefd679d7bacff5b09c523a9ccce1acbdcbb8','nova/audio/turns/en-fa/A1/m01/c02/l04/t05-maya-0bd4f01feed4.mp3',1625),
('A1',1,2,4,6,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c02/l04/t06-arman-09cc0bad1a2d.mp3',2415),
('A1',1,2,4,7,'Maya','character','e241648df8201db40cfa1ce813b22b2e6cbca72fa044ca3d6093b75773d1992c','nova/audio/turns/en-fa/A1/m01/c02/l04/t07-maya-57f22d06e154.mp3',650),
('A1',1,2,4,8,'Arman','learner','1cb7b221b7adda1cf4c4724b32369394580480c84ab835795d608ac59aa13002','nova/audio/turns/en-fa/A1/m01/c02/l04/t08-arman-d8a4ef3c071b.mp3',929),
('A1',1,3,1,1,'Maya','character','c231eaa57287fa7f5929a9a016bf4bd25bee87d4ac1e3a00654d17130e704b16','nova/audio/turns/en-fa/A1/m01/c03/l01/t01-maya-2cc070076508.mp3',836),
('A1',1,3,1,2,'Arman','learner','832e8c6c05cd425478105efc2829349ed804bd6a2e9a95a9efe23d50d4769981','nova/audio/turns/en-fa/A1/m01/c03/l01/t02-arman-4081f904222f.mp3',1393),
('A1',1,3,1,3,'Maya','character','8a38c81b46381d2693666843c8bd213c5d9be3cb02fd1cf73bba5ae9f84b05de','nova/audio/turns/en-fa/A1/m01/c03/l01/t03-maya-856ed033796c.mp3',697),
('A1',1,3,1,4,'Arman','learner','ce504c119eb8ba2cb8f4ca4f83ae6e052af11bb9999c1bb34d4f915f46f3e61c','nova/audio/turns/en-fa/A1/m01/c03/l01/t04-arman-fb2d0e2ae7af.mp3',1997),
('A1',1,3,1,5,'Maya','character','a8cfdb71869956728cfded22891bd16467181bd6d342037e4bd96a262bc2eda9','nova/audio/turns/en-fa/A1/m01/c03/l01/t05-maya-98a675572848.mp3',929),
('A1',1,3,1,6,'Arman','learner','7697c99ed752ed0728450371498e6e1f3a4635ca86bf50843ea625d1bd940cab','nova/audio/turns/en-fa/A1/m01/c03/l01/t06-arman-51e406e88fdc.mp3',2276),
('A1',1,3,1,7,'Maya','character','a2a5545ed08fb6386085717249bccf580d92e06abf3195eb1f6d7fec6b00279b','nova/audio/turns/en-fa/A1/m01/c03/l01/t07-maya-ea322d65a56a.mp3',836),
('A1',1,3,1,8,'Arman','learner','8569efc4ed5a6273140c2b6ec0ab8d99f4398210808fbb7c0cbbae4fbcc21350','nova/audio/turns/en-fa/A1/m01/c03/l01/t08-arman-55f9a26b3209.mp3',975),
('A1',1,3,2,1,'Maya','character','8a38c81b46381d2693666843c8bd213c5d9be3cb02fd1cf73bba5ae9f84b05de','nova/audio/turns/en-fa/A1/m01/c03/l02/t01-maya-5d9131ee1c41.mp3',697),
('A1',1,3,2,2,'Arman','learner','ce504c119eb8ba2cb8f4ca4f83ae6e052af11bb9999c1bb34d4f915f46f3e61c','nova/audio/turns/en-fa/A1/m01/c03/l02/t02-arman-400a5ab53c4e.mp3',1950),
('A1',1,3,2,3,'Maya','character','b3b4d67ecaa492e37f544755260ada8c3e2c637b94150e1d60c3b59943c72846','nova/audio/turns/en-fa/A1/m01/c03/l02/t03-maya-e61c7128b8af.mp3',650),
('A1',1,3,2,4,'Arman','learner','93bfd4edefb5d8679b74dc2f3ee7ef419f33de61c26179d24804c8d57c0cdee7','nova/audio/turns/en-fa/A1/m01/c03/l02/t04-arman-51014dbe8ed0.mp3',2183),
('A1',1,3,2,5,'Maya','character','2c33dcef91e066247cc05cc403f99dcf572e5bb8f45656fec462270e689916b6','nova/audio/turns/en-fa/A1/m01/c03/l02/t05-maya-f2c4e2862372.mp3',418),
('A1',1,3,2,6,'Arman','learner','c710e73fbbc3235d45ff6d322b0136eb9d0101c2804891df4a3ae919d1857a2f','nova/audio/turns/en-fa/A1/m01/c03/l02/t06-arman-71d25e8858ac.mp3',1718),
('A1',1,3,2,7,'Maya','character','4e4495f787213f61b90f50906dde23625814927c8c852435e1eaf144218cbbb3','nova/audio/turns/en-fa/A1/m01/c03/l02/t07-maya-4fa52033e6ca.mp3',882),
('A1',1,3,2,8,'Arman','learner','f51bead488e14b656af3a13e33eb1d6fa9580832cbb9d7a20061f84c4b1c160f','nova/audio/turns/en-fa/A1/m01/c03/l02/t08-arman-426cfb086b62.mp3',882),
('A1',1,3,3,1,'Maya','character','63265a79774350462d4ce11d5a90687ff8e6f2511bb512e0409be568b6be7046','nova/audio/turns/en-fa/A1/m01/c03/l03/t01-maya-54a1bae9c9b1.mp3',743),
('A1',1,3,3,2,'Arman','learner','5dfce23c275fa6fab08233cefbad28edad8515795b3e7d9e445c869c89469fe1','nova/audio/turns/en-fa/A1/m01/c03/l03/t02-arman-99d0895338e6.mp3',1765),
('A1',1,3,3,3,'Maya','character','8a38c81b46381d2693666843c8bd213c5d9be3cb02fd1cf73bba5ae9f84b05de','nova/audio/turns/en-fa/A1/m01/c03/l03/t03-maya-d91eeb569a68.mp3',836),
('A1',1,3,3,4,'Arman','learner','ce504c119eb8ba2cb8f4ca4f83ae6e052af11bb9999c1bb34d4f915f46f3e61c','nova/audio/turns/en-fa/A1/m01/c03/l03/t04-arman-3a08132395f1.mp3',1997),
('A1',1,3,3,5,'Maya','character','1dd9831b7139b70cb1db22aed9376f3790fc9de1b921aae0e95ffa35acaa43ba','nova/audio/turns/en-fa/A1/m01/c03/l03/t05-maya-69d9077fcec3.mp3',1765),
('A1',1,3,3,6,'Arman','learner','b843a315fac423a27332436f74a3f9d7be2982de1381a2fa27ebb00ab4c83166','nova/audio/turns/en-fa/A1/m01/c03/l03/t06-arman-e556b89918c7.mp3',2554),
('A1',1,3,3,7,'Maya','character','39954823f73a76e35ec7280de44b2eb4b26399ecdc00a2b3640db22375d3a4b3','nova/audio/turns/en-fa/A1/m01/c03/l03/t07-maya-506ffecdc4c5.mp3',1161),
('A1',1,3,3,8,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c03/l03/t08-arman-f2d1ddba098d.mp3',1904),
('A1',1,3,4,1,'Maya','character','5dcee9bdca119172f74efe0a5d17eb255f5e6f5d9081287ac6d7f47f434f32ec','nova/audio/turns/en-fa/A1/m01/c03/l04/t01-maya-422f4176b27a.mp3',1300),
('A1',1,3,4,2,'Arman','learner','a1a854e8fa345919ea0299c545db2d43f3c01793e54b3095ba1c7d3203bf7ce0','nova/audio/turns/en-fa/A1/m01/c03/l04/t02-arman-f7973f932edc.mp3',1533),
('A1',1,3,4,3,'Maya','character','63265a79774350462d4ce11d5a90687ff8e6f2511bb512e0409be568b6be7046','nova/audio/turns/en-fa/A1/m01/c03/l04/t03-maya-ececc93fe069.mp3',1068),
('A1',1,3,4,4,'Arman','learner','5dfce23c275fa6fab08233cefbad28edad8515795b3e7d9e445c869c89469fe1','nova/audio/turns/en-fa/A1/m01/c03/l04/t04-arman-99d0895338e6.mp3',1765),
('A1',1,3,4,5,'Maya','character','8a38c81b46381d2693666843c8bd213c5d9be3cb02fd1cf73bba5ae9f84b05de','nova/audio/turns/en-fa/A1/m01/c03/l04/t05-maya-d91eeb569a68.mp3',836),
('A1',1,3,4,6,'Arman','learner','ce504c119eb8ba2cb8f4ca4f83ae6e052af11bb9999c1bb34d4f915f46f3e61c','nova/audio/turns/en-fa/A1/m01/c03/l04/t06-arman-76fe707aee9d.mp3',1858),
('A1',1,3,4,7,'Maya','character','f62f5a5e3a4cdb8f099e9ac7df8aefd679d7bacff5b09c523a9ccce1acbdcbb8','nova/audio/turns/en-fa/A1/m01/c03/l04/t07-maya-349eafd84feb.mp3',1625),
('A1',1,3,4,8,'Arman','learner','ba2fccea610d6ca54ed626ae12cae853e623a129e3f810cd022e7494ca551b2a','nova/audio/turns/en-fa/A1/m01/c03/l04/t08-arman-f50178e1790b.mp3',1718);

DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_turn_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='en' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova en-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_turn_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order,
           COUNT(c.id) AS matched_rows
    FROM nova_turn_audio_updates AS u
    LEFT JOIN levels AS lv
      ON lv.course_id=v_course AND lv.cefr_level=u.cefr_level
    LEFT JOIN modules AS m
      ON m.level_id=lv.id AND m.sort_order=u.module_order
    LEFT JOIN chapters AS ch
      ON ch.module_id=m.id AND ch.sort_order=u.chapter_order
    LEFT JOIN lessons AS l
      ON l.chapter_id=ch.id AND l.sort_order=u.lesson_order
    LEFT JOIN turns AS t
      ON t.lesson_id=l.id AND t.sort_order=u.turn_order
     AND t.role=u.turn_role AND SHA2(t.text,256)=u.text_sha256
    LEFT JOIN characters AS c
      ON c.id=t.character_id AND c.course_id=v_course AND c.name=u.character_name
    GROUP BY u.cefr_level,u.module_order,u.chapter_order,u.lesson_order,u.turn_order
    HAVING COUNT(c.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Turn locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE turns AS t
  JOIN lessons AS l ON l.id=t.lesson_id
  JOIN chapters AS ch ON ch.id=l.chapter_id
  JOIN modules AS m ON m.id=ch.module_id
  JOIN levels AS lv ON lv.id=m.level_id AND lv.course_id=v_course
  JOIN characters AS c ON c.id=t.character_id AND c.course_id=v_course
  JOIN nova_turn_audio_updates AS u
    ON u.cefr_level=lv.cefr_level
   AND u.module_order=m.sort_order
   AND u.chapter_order=ch.sort_order
   AND u.lesson_order=l.sort_order
   AND u.turn_order=t.sort_order
   AND u.character_name=c.name
   AND u.turn_role=t.role
   AND u.text_sha256=SHA2(t.text,256)
  SET t.audio_url=u.audio_url,
      t.audio_duration_ms=u.audio_duration_ms;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_turns, v_changed AS changed_turns;
END$$
DELIMITER ;
CALL apply_nova_turn_audio();
DROP PROCEDURE IF EXISTS apply_nova_turn_audio;
DROP TEMPORARY TABLE IF EXISTS nova_turn_audio_updates;
