-- Generated by nova/tts/nova_word_tts.py. Do not edit by hand.
-- The generator never connected to the database.
-- Persistent changes are limited to words.audio_url and words.audio_duration_ms.
SET NAMES utf8mb4;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
CREATE TEMPORARY TABLE nova_word_audio_updates (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL,
  audio_url VARCHAR(1024) NOT NULL,
  audio_duration_ms INT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
CREATE TEMPORARY TABLE nova_word_audio_exclusions (
  word_key CHAR(64) NOT NULL PRIMARY KEY,
  lemma VARCHAR(180) NOT NULL,
  display_form VARCHAR(180) NOT NULL,
  part_of_speech VARCHAR(48) NOT NULL,
  translation VARCHAR(255) NOT NULL,
  text_sha256 CHAR(64) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO nova_word_audio_updates (word_key,lemma,display_form,part_of_speech,translation,text_sha256,audio_url,audio_duration_ms) VALUES
('50fcdd8ed2cc23fd0228925001ada427ac62aa5f1d8f795ff88bf0fceab64602','a','a','determiner','یک','ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb','nova/audio/words/en-fa/50/a-399cd5a40aed.mp3',697),
('2d94bad0a39be74bee9df2ce35792dd53db6a663c003825798dd9c7ec4dd757e','address','address','noun','نشانی','d80c9bf910f144738ef983724bc04bd6bd3f17c5c83ed57bedee1b1b9278e811','nova/audio/words/en-fa/2d/address-207f6b60ec6c.mp3',1022),
('c5fd6429b4686d3aa7c8e0e913305d7d4553505d0c7d00834ec07d175cff5557','after','after','adverb','پس از','f39592393ef0859cb196a52693d2cea00fb2df784b3c04ae54aa7cadb8e562f8','nova/audio/words/en-fa/c5/after-9555db03c306.mp3',929),
('6f646693f61abb6f7fec243254223e734caeca680143b2268bbd8d020ac336ef','afternoon','afternoon','noun','بعدازظهر','c8e07c1ac268eae0661eb98fed3e0ea7516b43805af7c6473a83222c78209cad','nova/audio/words/en-fa/6f/afternoon-95dd44bda71b.mp3',1068),
('4c4ce98244c3ff312d574df24dcb1101dc2c720898af44b89ef45261d3d41898','and','and','function_word','و','6201111b83a0cb5b0922cb37cc442b9a40e24e3b1ce100a4bb204f4c63fd2ac0','nova/audio/words/en-fa/4c/and-9460d75dba36.mp3',789),
('3314c89f65402b34f6db131de62d3f8414113490cb5be4c52f3a8230139be3a8','another','another','determiner','هر','ae448ac86c4e8e4dec645729708ef41873ae79c6dff84eff73360989487f08e5','nova/audio/words/en-fa/33/another-199324ee6bf5.mp3',975),
('fe4ec4255f7ad429417b2367ebf7d829e20803e9814be263b2965f7d1124b838','arman','arman','noun','آرمان','e644df618fef9fdd44dd7f26f1077051e49538f1b70603631cdf0de7c69fb469','nova/audio/words/en-fa/fe/arman-cc32ef27eaaa.mp3',836),
('c66dca8f2587f18c80b760bf1b7f9fc70164b53d57a462087d41b6ee9a8d3aeb','arrive','arrive','verb','رسیدن','6dc09a300747b82d8bfe9d509ede4fb228e3c27204185e8c5e6188340904d9e0','nova/audio/words/en-fa/c6/arrive-65f5dda72789.mp3',975),
('fcb12555793cca0dccfa9d7e7aef03bd609aa084573445d0c69013792986df32','at','at','adverb','در ساعت','b1d6b91b67c2afa5e322988d9462638d354ddf8a1ef79dba987f815c22b4baee','nova/audio/words/en-fa/fc/at-14f2e3ea5283.mp3',604),
('d49ef806c273fa5677bf9eafbe9649402d949b8afb7a7baa456e2c008c7b53fb','bag','bag','noun','کیف','c018019b6a8b01ab5868cf4be8db327a7549ae03202548b9ffcd2671c4c2b624','nova/audio/words/en-fa/d4/bag-1d5307873db7.mp3',836),
('0de7667002fc84abdc0b665a4be42abc3270374063a40ea4030ed9b380586950','be','be','verb','بودن','46599c5bb5c33101f80cea8438e2228085513dbbb19b2f5ce97bd68494d3344d','nova/audio/words/en-fa/0d/be-c11bef294ba8.mp3',604),
('c6eb1a4adcb7c1354f3754dc40fd4b3eac74f72913f1d5bae834862fd98da807','before','before','adverb','پیش از','6db7d803e74f1ffa7d8f5adc0bf95b3e15bf4c8373fffadf546227cc6c6742cb','nova/audio/words/en-fa/c6/before-81d4cfbae0dc.mp3',975),
('48500f7fa9426632d33e14530006552cf3c84c2cf5a7895eac403d4a405e9cf2','break','break','noun','استراحت','14ebe56a5008e7c251101e9e1fdbe281ab0a82bd6fa00a5cef746b9ee0dd31d1','nova/audio/words/en-fa/48/break-8788e01a59fa.mp3',882),
('ca2029d3c0f048c540831c554ea16c9e277c5c043d7e652baa49fdcbc5e86e12','breakfast','breakfast','noun','صبحانه','7c58ea253628feed6583e78db4fd9fab131e0016ade168b4c200eb41d6aa93b1','nova/audio/words/en-fa/ca/breakfast-c95d77184849.mp3',1022),
('50afac2ace74d60275ef208e19b8d41caad05bd6128e4fd6b6019f6818a64398','brother','brother','noun','برادر','0b4bd77cec705cf5df016344c0fc673fb3c2240078e6af572b2c5c6fa76114af','nova/audio/words/en-fa/50/brother-6cdd7eaaa59c.mp3',975),
('a33eb07f51719f6f822e892c5363f2f4ee99738b41197d8298de345b5538c42b','busy','busy','adjective','پرمشغله','c9bc072f4fa8189466c2a8f2c36a56a4ef1e60a2ffa4986ba2f155cd176c128b','nova/audio/words/en-fa/a3/busy-ebf8ffddcbfc.mp3',929),
('6bfa705c4e728680a62ad81213c02c520d9027a8c39fed96c82d97136216361f','cafe','cafe','noun','کافه','a860b858265b22dad3aaf1165cfc2936daf1d3d86e0b7b77e3cc07f59f96858f','nova/audio/words/en-fa/6b/cafe-bb3048fc1bff.mp3',1022),
('f19821ae62a33da1182efc39aac3110b67eddc59a056e4bfa4e3474ed197eed8','can','can','verb','توانستن','9f584196e7fe6de85d3898bc0b11c78b1d0a1d49530ee5eaf7c26c3939cf043d','nova/audio/words/en-fa/f1/can-3d57d8c55a04.mp3',929),
('33816cc493b6683c7a4fa5bfb6573b9c2423a7ce720a1e50f3b23e284032af34','city','city','noun','شهر','11a62c23412b77477a71481aa2dc7323bcc61d076c8449076c4c58a8356c1bb1','nova/audio/words/en-fa/33/city-46f95d8c60c3.mp3',836),
('a8adee28a64184f3e5f4f8c034432535bf6c1583fbefde627b6147a81eeec02c','class','class','noun','کلاس','0889113e04d3203f0c401c17c0fd8b352b740dc607433779d3edcaa13320b001','nova/audio/words/en-fa/a8/class-5d6577539192.mp3',1022),
('58a0ffc2b65da22903a0d6ec2a228a6419478d5477e92f1fc6501904535047df','classmate','classmate','noun','هم کلاسی','66f9b98dde76ccbacebabd344bf5244fd6bb4a6a5ac62ababfea82d3fcc650b1','nova/audio/words/en-fa/58/classmate-ea4ac13d9fbc.mp3',1161),
('fde1340d46776f3401899f374629db3ac6f76a1c084b6b164e918003450ec210','coffee','coffee','noun','قهوه','37290d74ac4d186e3a8e5785d259d2ec04fac91ae28092e7620ec8bc99e830aa','nova/audio/words/en-fa/fd/coffee-93909dd805b0.mp3',1022),
('01eccb9a121c47dde872082a6791d18283fa97b8191c287afcd25170619635a5','colleague','colleague','noun','همکار','7fdbbefdb4a4607cd42ae8e5fe81b951aa3cd19273a35ef207e36d7cc8339e8d','nova/audio/words/en-fa/01/colleague-dd9d00affefe.mp3',1022),
('207ebfbc42edd03f91b807b535caa0f5f5c6551a6e2ade7c1399c7d5502d7952','correct','correct','adjective','درست','15a596e3c98c407e043751ff3b21ff0358a1bdfdf3fe948b1523893a8e5de2e8','nova/audio/words/en-fa/20/correct-af9d9e881198.mp3',1115),
('67e05db02c0fb38d17b73e65587eeb22b371169da1fff16ded003fb48f40e79f','country','country','noun','کشور','aff64e4fd520bd185cb01adab98d2d20060f621c62d5cad5204712cfa2294ef7','nova/audio/words/en-fa/67/country-e20d56f744ca.mp3',882),
('ab1107fbda479b72287ac30a3dc0d4255025d809b272b512af100b22886cfa17','customer','customer','noun','مشتری','b6c45863875e34487ca3c155ed145efe12a74581e27befec5aa661b8ee8ca6dd','nova/audio/words/en-fa/ab/customer-1f63eb429ee3.mp3',1115),
('e42f5b877eb478a638ced17c91380bfc0203a9c539092bf285bbda2af29bfaa9','daniel','daniel','noun','دنیل','bd3dae5fb91f88a4f0978222dfd58f59a124257cb081486387cbae9df11fb879','nova/audio/words/en-fa/e4/daniel-baa2a6304237.mp3',975),
('af5e584d824a6f56d5015cd6735e8e1b833ed80a9379b00534e97257e0b605fe','day','day','noun','روز','944c27e5b97ab7793e4b6e9ff29384890ece0c7c04d2e2bf81c5f763469cc66b','nova/audio/words/en-fa/af/day-c0cd49748b9c.mp3',836),
('f4fd5cb00ab619facef2df52219105246016e01239697ca9e14e2e6599c3e2da','dinner','dinner','noun','شام','dda209044ad44962b012ececcc2cb2f7efd35c72d22465586e294b6493bc21c1','nova/audio/words/en-fa/f4/dinner-f1420b78339d.mp3',882),
('d3b2d8eb286dbbe68d841a954e13134fefc17afc7dd8f2e0fc8544ce38fce64b','do','do','function_word','فعل کمکی پرسشی','ac0b52a2ae6ef99999bc08fb31e19188bf0085a4614204068e677e140e1458be','nova/audio/words/en-fa/d3/do-d5e2b71ddfd3.mp3',743),
('768266957fc186564a4af7f6c589b1fec9b5f85b366a7147d6a83834edb8fd51','doctor','doctor','noun','پزشک','72f4be89d6ebab1496e21e38bcd7c8ca0a68928af3081ad7dff87e772eb350c2','nova/audio/words/en-fa/76/doctor-05585b051d29.mp3',1115),
('b74a6196b1defffda2a459911227c863110516bab019da516a11c4a67862d867','drink','drink','verb','نوشیدن','218ae6b44966c8a9913e78ef950ea5d047ac7c3d73341f9867d760cc38c3fc1f','nova/audio/words/en-fa/b7/drink-36e730db8de0.mp3',836),
('9978550816b25b79c53248509770f244dff89122e86a273bbe86534e84601c8e','driver','driver','noun','راننده','b4def8217cadae26d4da633fd2a4e58e326cbb5d570afdc3989484da07af3579','nova/audio/words/en-fa/99/driver-d23a0a486444.mp3',975),
('819780e4874ac1061696bdf9b52b0ea84a4bda9dc759b19e0c4761e34a317086','each','each','determiner','هر','bec1687971e36be51a298f172aa898ab48a465012ae40e6292825c432d7d82b8','nova/audio/words/en-fa/81/each-f29da0609114.mp3',836),
('b6df3389e7a30d9861820f93fcf3d138f5a905884930f64484a286ec04e0b5db','early','early','adjective','زود','f408830bcc7fab370819172244aa32e3ba66a848835911c02629d9a4dff77992','nova/audio/words/en-fa/b6/early-bd6b7b629bf4.mp3',882),
('cd01741479d7d1c8ace4560fc61e18e18bb575897bcba6e8315607e4d8a23f9e','eat','eat','verb','خوردن','e57bd924047ef39d2a206c8bc5c06a0ed38baa918c5054859f5e8ffd23037371','nova/audio/words/en-fa/cd/eat-2acbcbca87bf.mp3',789),
('c14c0deb77ccfc871073178b6afe2e682aa543fb76fd9762d9aa11bfb6025e70','eight','eight','noun','هشت','c195d2d8756234367242ba7616c5c60369bc25ced2dcb5b92808d31b58ef217a','nova/audio/words/en-fa/c1/eight-fe7f0e711e4a.mp3',789),
('5c19e2a53d9c87571c0ea5a3ef6860b61afda3d9400e1cb7d6e99f49bf1d7875','email','email','noun','ایمیل','82244417f956ac7c599f191593f7e441a4fafa20a4158fd52e154f1dc4c8ed92','nova/audio/words/en-fa/5c/email-dfae68fbe719.mp3',929),
('b4843c146b0a11e2550c68d25c6b38dd55ffd171a3fd7f6848d1037e65b60c2f','evening','evening','noun','عصر','e5bd0801d10e5965354604c20443ddf47fdfc375115151277a525467ad4816a3','nova/audio/words/en-fa/b4/evening-32ed86659b2d.mp3',1161),
('923ff7e6f4d13a7403a55bedb85e62272ca7904c97350ef94dc944fb0a3badee','every','every','determiner','هر','66a424a9a958b152c1c3ba65a2ac6c33ad03333e2e41e7d770b5758d46dd3ef5','nova/audio/words/en-fa/92/every-98085055919f.mp3',929),
('8872f6f875591d92f55284b49573021508d5477dfb8a3a932a4a67667c93f7f4','exit','exit','noun','خروجی','e596899f114b5162402325dfb31fdaa792fabed718628336cc7a35a24f38eaa9','nova/audio/words/en-fa/88/exit-37871d5b57bf.mp3',836),
('51a10188af25dafba6551d497b1b4762878a6afd8baf119c2f2315a559dc9319','family','family','noun','خانواده','d34a569ab7aaa54dacd715ae64953455d86b768846cd0085ef4e9e7471489b7b','nova/audio/words/en-fa/51/family-6c3e9b0e13e8.mp3',1022),
('7594f705148a617f527b04be7d76b4b4f4fd1a9238588cf673eb70d95f727fa9','father','father','noun','پدر','88a1881f0025cf7117501d07aefc5d4be6696656790d765678df8bc48ca52687','nova/audio/words/en-fa/75/father-efc9d15257f3.mp3',929),
('abf3b5b37a79d6273efd9fac497d0a0981e917903a515af2ccbb7f2c824346f9','fine','fine','adjective','خوب','d14a58bae804a2b80b5b76a010239c88ffca1fc7951a90f8e9131beda1e23c1b','nova/audio/words/en-fa/ab/fine-43db7c09670e.mp3',1022),
('2f4de9306dbae5292299c7057014e58ce91889895789c592a49644f0470bd44d','finish','finish','verb','تمام شدن','42af43e3616eba4a133a755540a88e6c61085dfe66c6e49e6ab8eaf9daf0c0da','nova/audio/words/en-fa/2f/finish-5f2a3f21d1c6.mp3',836),
('e94b6d5da4085d00103ca50a2cb912561247092a1e942946375a8d170cd0f927','first','first','adjective','اول','a7937b64b8caa58f03721bb6bacf5c78cb235febe0e70b1b84cd99541461a08e','nova/audio/words/en-fa/e9/first-c4fc2fef4546.mp3',882),
('bfa44a363f42eb5d38ed97d27e134acd0c684f677d044e58285d2555bc368b52','five','five','noun','پنج','222b0bd51fcef7e65c2e62db2ed65457013bab56be6fafeb19ee11d453153c80','nova/audio/words/en-fa/bf/five-e8394524704f.mp3',882),
('9b8877ff3398d337229a4ca57b7e82a80e7bd2895aa8f06e7a0cc827e9590f4c','four','four','noun','چهار','04efaf080f5a3e74e1c29d1ca6a48569382cbbcd324e8d59d2b83ef21c039f00','nova/audio/words/en-fa/9b/four-0778e8ff2d29.mp3',882),
('8878c5e7be9708779809bfdc4b92141ee2d7ed8a92a88a9c0ae6a7f2969e18da','free','free','adjective','آزاد','ad95d5fa651ba86d8923fe1238d24a4f1988a752acfe426ac72ac7c04471bc17','nova/audio/words/en-fa/88/free-899cc220cf59.mp3',882),
('e148171f786550a457043775187b307552c79180fafb8cf36fae5446c5a7044d','friday','Friday','noun','جمعه','e21f3f372a46d4be7b49f6809fc91baefeadae004af06485518e124a142c0271','nova/audio/words/en-fa/e1/friday-7701924d60d6.mp3',929),
('3a9ef1c2cbff54087ae967416c952c65755ffa759fde458b1491af7a78b5a0da','friend','friend','noun','دوست','cde48537ca2c28084ff560826d0e6388b7c57a51497a6cb56f397289e52ff41b','nova/audio/words/en-fa/3a/friend-e5e133fd7224.mp3',929),
('4ceb1dc8ff90833b2c8e31247a48512128d16686f89e00042b0516f1da86aff0','from','from','adverb','از','75857a45899985be4c4d941e90b6b396d6c92a4c7437aaf0bf102089fe21379d','nova/audio/words/en-fa/4c/from-522be2cc6c75.mp3',1022),
('4c1856435b01b65d393d2b6bb857cfa6818047740d9db293891318cf0b3428be','get','get','verb','گرفتن','2998b3232d29e8dc5a78d97a32ce83f556f3ed31b057077503df05641dd79158','nova/audio/words/en-fa/4c/get-ef32cbbb91e0.mp3',743),
('282f5f07f8146f8de4d0df25646bf990bca3bc7536072597e66fc59904db1a51','good','good','adjective','خوب','770e607624d689265ca6c44884d0807d9b054d23c473c106c72be9de08b7376c','nova/audio/words/en-fa/28/good-5f687d11b722.mp3',975),
('b3d29d5dbaeb6ed15242a4b6aaafb0843a42472316967d68142e1356bf946972','great','great','adjective','عالی','87765da6ccf0668238c1d27c35692e11b4cee9c0e5cd5713a3f6e462d48e9730','nova/audio/words/en-fa/b3/great-0264b0d405b8.mp3',789),
('8c0f0b4848839fdd1a399194b7896abad7e11383058a7f6af870ab60a36fd33c','guest','guest','noun','مهمان','84983c60f7daadc1cb8698621f802c0d9f9a3c3c295c810748fb048115c186ec','nova/audio/words/en-fa/8c/guest-6a86930fd8a1.mp3',975),
('c1251d08449353159ef7447aa52b6a42db8bd5ca6d7cb4a7bcef3f134ccbb43e','guide','guide','noun','راهنما','83ca68be6227af2feb15f227485ed18aff8ecae99416a4bd6df3be1b5e8059b4','nova/audio/words/en-fa/c1/guide-098e3989a126.mp3',1115),
('56b5e89ebab7fe0ccb922b6dccae82c1a2024b8599666516156c5ececd7f4b14','he','he','pronoun','او برای مرد','372f7e2fd2d01ce2a1d71dc072acbba4c6fd25a1087cd7f153f4ec0ce37e1ede','nova/audio/words/en-fa/56/he-ce1d55d6112c.mp3',836),
('d32182ea56349084c90dbe314d9bf8ac307b52f455b5c1854efa2d4d2ee2b8ee','hello','hello','interjection','سلام','2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824','nova/audio/words/en-fa/d3/hello-db4cb3e6e54d.mp3',1022),
('70b43c618c8cc065c63ad08ca7fc5ea64e548067d4821c9112ebbc8b74d28376','help','help','verb','کمک','106a5842fc5fce6f663176285ed1516dbb1e3d15c05abab12fdca46d60b539b7','nova/audio/words/en-fa/70/help-a14136fb11cd.mp3',882),
('e853fb61c47023c5975ac191ab50d012b9d4093254a05c0b338b512a8f0b13ad','here','here','adverb','اینجا','fcec91509759ad995c2cd14bcb26b2720993faf61c29d379b270d442d92290eb','nova/audio/words/en-fa/e8/here-a9170235bc08.mp3',882),
('c28ee506714a530b66c0964b59894097714da5c1a8c6f15f5e29c74315133a1f','holiday','Holiday','noun','تعطیلات','992b3299061eb2b2e226baccfbb2ba6c122d1e0a85c66a1b9aee3bac5f9c76b3','nova/audio/words/en-fa/c2/holiday-c3857ed0e2a3.mp3',975),
('bf30f68bf96acd44dc6d710647a86e7b70469f2f4f8b9ef1fdd0850905e3a214','home','home','noun','خانه','4ea140588150773ce3aace786aeef7f4049ce100fa649c94fbbddb960f1da942','nova/audio/words/en-fa/bf/home-0b258396f863.mp3',882),
('68880bd304f1ad6045b156d5629a63291857d7fda9b816fab30b6678953c3d9e','how','how','adverb','چطور','8044aae1f86875d993f20d7fe3815306b640d6e039c4512cd7a2f8453207b4cd','nova/audio/words/en-fa/68/how-11fafd4dbee4.mp3',882),
('e6e614022945cabc47c1296c031053de46c95a73847af784d30a6cdce6d858b6','i','i','pronoun','من','de7d1b721a1e0632b7cf04edf5032c8ecffa9f9a08492152b926f1a5a7e765d7','nova/audio/words/en-fa/e6/i-8b24ae3eb3fd.mp3',650),
('0ac1c6e0e604fecff09ba8f5566d7c16e6691c9bc6d5787c3dee43114c82939f','in','in','adverb','در','582967534d0f909d196b97f9e6921342777aea87b46fa52df165389db1fb8ccf','nova/audio/words/en-fa/0a/in-1027ff46c930.mp3',743),
('d5d509459a94d872044bc8532169c00a1e55cbd2f33dcb8eb612597575789a2f','introduce','introduce','verb','معرفی کردن','0fee7196f6817d6f81e75cac8e2d3d0b11987caa6b71d91d0657b638b093f54b','nova/audio/words/en-fa/d5/introduce-446572061a65.mp3',1068),
('2f9a971b4d8e70b537495682702d250f9174f1bdcdcd131df19a1a6eda49f6f4','iran','iran','noun','ایران','d4328f17fc46dfde5a0a2cbc09fd28abab29b0e63dba80133a212e2403361cf4','nova/audio/words/en-fa/2f/iran-8edfe7ef4dc3.mp3',882),
('d220c9faa97d0e3014dbbe417bdb776a8e6954fbd27b587fc7c5c7f40edae755','it','it','pronoun','آن','2ad8a7049d7c5511ac254f5f51fe70a046ebd884729056f0fe57f5160d467153','nova/audio/words/en-fa/d2/it-a5bb18219c17.mp3',697),
('60faca82304a27a1dc2c6497c7996043592fe1387266b5bd2f06728c197f8932','king','king','noun','کینگ','e81dfe69841ad2f7b5790b63e998f0febaf3b29acd732881975130761b98e2c7','nova/audio/words/en-fa/60/king-f5559a2dc9b7.mp3',975),
('4d0a0484123e1e42076f63bb1a9c8f4103b6f9d4eb8d0179175937377e729137','kitchen','kitchen','noun','آشپزخانه','3171d89ad00530ffa19a244f040e9401a657903cbbbca724996b90a56df2c189','nova/audio/words/en-fa/4d/kitchen-aa0f17b979c5.mp3',975),
('8f915dbf503f931e907053008c8b933cc27811a32bccc1ecbfb3471eaee748fb','know','know','verb','شناختن','cd1bb3012bcfaa0c50e954d03634f33c883c2478584e96f03d0d4b984bc6eadc','nova/audio/words/en-fa/8f/know-7de2f59c6990.mp3',836),
('e7db272cd7a2245a672dc990375cdbbb75570b3b9f748a090504a9c77facb4d2','last','last','adjective','آخر','3547cb112ac4489af2310c0626cdba6f3097a2ad5a3b42ddd3b59c76c7a079a3','nova/audio/words/en-fa/e7/last-669878edc635.mp3',975),
('44d2c75363fc2e07e312e1f7154c3a4318741b11e32ad451df505ab4444b3f0d','late','late','adjective','دیر','089001a35679a33ef3db0ca350db9b9a2f0136e0e327577b04b3b98127470961','nova/audio/words/en-fa/44/late-f489fe4aef48.mp3',836),
('d263ab454c8d3a9c68bb758d94d224dad8e2eff76964672bf1736ade8673be20','leave','leave','verb','رفتن','af193190b8d3cd14103e20e900378a2b76414ff6428065f3f8539b3577b22fdf','nova/audio/words/en-fa/d2/leave-e06377e7c4a5.mp3',929),
('d9d191d1b74fcb085831b719b7cec8d99d286bc1d61efaed6b578a3276c38eb3','left','left','adverb','چپ','360f84035942243c6a36537ae2f8673485e6c04455a0a85a0db19690f2541480','nova/audio/words/en-fa/d9/left-349f1d42f8dd.mp3',929),
('c68ec905b437249603115a5356e2ab7e49b31c2d87e9163b9558238d24d0d0f6','little','little','adverb','کمی','180ca01b95f0dfdd36fbb600e51cf6e46c8ef468de56b017847886fefaf7b6f9','nova/audio/words/en-fa/c6/little-25b34084f94b.mp3',836),
('06d98444c73c6c3d67cb9929de9b5aea2acf0425ab92c96f46a4890810f95444','live','live','verb','زندگی کردن','247610f4dedd4ab7247d07dbda19c81ca9817f85820742cad49d407ffae9e4ed','nova/audio/words/en-fa/06/live-7af9df819a15.mp3',882),
('9f59694fcda6c55e26d45fe4ae8b9199e0154ac66b745a656a8cdb1a98878253','london','london','noun','لندن','6089854c94ca5454b76be6752c562901a985f64c9a946f62976aeab593b83161','nova/audio/words/en-fa/9f/london-bcf199fc0f35.mp3',1022),
('c4e428c4d9425ad325c2b9446344d6b59c4d51999f238c5a61e020daaa72fe32','long','long','adjective','طولانی','fc66f021c67d064c1490a12b5a4d4d2f5167ca692a16ca12f1f3a4cda29a6fa9','nova/audio/words/en-fa/c4/long-37e153638dc1.mp3',1022),
('0173acd24e374f167f076fbd80d955e3151709325f3b0a26bdcf68bae0e3448c','lunch','lunch','noun','ناهار','f3bb79e48a7a8af1d028f6acb7fa34b0c7f75da596fc205907d2a708fe28ebef','nova/audio/words/en-fa/01/lunch-12f47c63b3c4.mp3',929),
('20896b9b997496840e253942af0c5cd8c739c211f08b41a4b4c3609145593851','make','make','verb','ساختن','d05aa2a15fb3c40efeeb03bec445393f00074484cf01c8fb2da90ca6695a5531','nova/audio/words/en-fa/20/make-eb23b1974319.mp3',836),
('ba5aec9f62358a1e2043432b456370172da1dec954f857c9e5ade10d6979a117','man','man','noun','مرد','48b676e2b107da679512b793d5fd4cc4329f0c7c17a97cf6e0e3d1005b600b03','nova/audio/words/en-fa/ba/man-57578a4f34f4.mp3',929),
('e5aa01da2b10911173280d92aafba04b6ae9b31bc7f9bf8a35599b29f6c6d018','manager','manager','noun','مدیر','6ee4a469cd4e91053847f5d3fcb61dbcc91e8f0ef10be7748da4c4a1ba382d17','nova/audio/words/en-fa/e5/manager-46601e65a01e.mp3',975),
('d8d686e8ed45d4f3c83a6396e5a4853f13106b56bfdd3f7a58c21e3ede816d31','married','married','adjective','متاهل','f9ce3beb80492facbec3586308e6590ef4b543c570a119d1e9b575f3b12ce197','nova/audio/words/en-fa/d8/married-a3356d84e6c9.mp3',975),
('919ace51c065b50a793987ebf1a3b49489e4c8f8b1f78ca4d42b8c09d275317a','maya','maya','noun','مایا','a95db5b0ac159e4384ff55ef91c94a98dc563d66a88e7b027fcd5190c0f5bed5','nova/audio/words/en-fa/91/maya-f1cca91729e2.mp3',975),
('533a7f92628d2007f6e363da33c8b9638423d2e9c5d72dd42fac7839ee582198','me','me','pronoun','من را','2744ccd10c7533bd736ad890f9dd5cab2adb27b07d500b9493f29cdc420cb2e0','nova/audio/words/en-fa/53/me-ace8e4d69c46.mp3',929),
('62df6e760b67e7f716b6902eedff91fd6ba39f22d747b0369f32eba48bdc9c39','meal','meal','noun','وعده غذایی','aec6c3d03f013562eb39fd3ad0808d90e73252130bd695f676dfb96174139098','nova/audio/words/en-fa/62/meal-543240e3d1eb.mp3',882),
('7d43f44407e0fe53fd124585b6045743d75a11ac22c1f7eed74e2cce098d7118','meet','meet','verb','آشنا شدن','8ccb033c0e48b27ff91e1ab948367e3bbc6921487c97624ed7ad064025e3dc99','nova/audio/words/en-fa/7d/meet-65e3fe612cc8.mp3',836),
('b5546fcd6f67e1ba213dcc6a18e527fd6bf4441e7af97208f16388543beb1214','meeting','meeting','noun','جلسه','0fd924362117d03662f0e86e580ab01c70d3fa88dbffce4224017e86e5fbad52','nova/audio/words/en-fa/b5/meeting-c16ccd023330.mp3',929),
('420a5a2470c663a423f7901422c228377f62ac0a0378f61fc1f218afeb1732ec','monday','Monday','noun','دوشنبه','6a00dfc1dc867e8454c2c8856e1512d9bf02a76710e3411c0972aec886c76c61','nova/audio/words/en-fa/42/monday-99bf2ae73dc0.mp3',882),
('816888a5689ec4461533923478bbb065444e9ae27a434be2b7ba0cbb3e3fb829','morning','morning','noun','صبح','c23b31a0179b550f8a18fb06bc52a26e32333540369073d646da5c84a4dc341f','nova/audio/words/en-fa/81/morning-80850991e4f1.mp3',929),
('914092d4f1efe542834d4a12e1b9fc5d65d3234726349404511dbd15bfa7c2c2','mother','mother','noun','مادر','cf0622ef2a661cd2f11b0b644e40e4e00eb962918424a8c8ba53842fdf290235','nova/audio/words/en-fa/91/mother-3a95e7912308.mp3',929),
('1043faf6246303b4576849656565ca515b830e0900318551318ce02c5ff6f1f7','music','music','noun','موسیقی','80f189984e5ca70287d13342f6daa0db45cba3c131c4e46dc81360f3a4c4f690','nova/audio/words/en-fa/10/music-19c941cd945a.mp3',882),
('51fae114a08733f727ec9003a9ac80f00f61da2a5ca62dea8f2dd6da84a7d84f','my','my','determiner','مال من','038468518ad8122e13112743f890c7ba96ac5665b71de548eceb23e9ef237805','nova/audio/words/en-fa/51/my-bbf6341d8cfd.mp3',604),
('27edb390033d1d8b34b461c66f387a87e9a9849d36083226a64662fe4119a671','name','name','noun','نام','82a3537ff0dbce7eec35d69edc3a189ee6f17d82f353a553f9aa96cb0be3ce89','nova/audio/words/en-fa/27/name-bebd0d2d3aa5.mp3',836),
('e24a57aa883b51c9c322788b82cef644dffc5fe6ef2fbe5e776d4d9007782f84','need','need','verb','لازم داشتن','be8dff00b0d468b29d804886729be5b430163ad625b1b621d943c2f80005281a','nova/audio/words/en-fa/e2/need-abb1f5b1dacf.mp3',789),
('418173c862a13bd050f665eece95ca0b9dee7921019366ebf893ca1a8afd6d14','neighbor','neighbor','noun','همسایه','c65f1ed1c4f4bf1bc265e62b6cff6963111633a18b8fd798ee2a467150171750','nova/audio/words/en-fa/41/neighbor-afdb219af041.mp3',975),
('16af3f32bfc27b95a09e7aacf379fca0b67576396f925116c399458a4efe4109','new','new','adjective','جدید','11507a0e2f5e69d5dfa40a62a1bd7b6ee57e6bcd85c67c9b8431b36fff21c437','nova/audio/words/en-fa/16/new-9c9a5cf1272f.mp3',836),
('8462e8984928ff4ea82b431ddfa79c59daeb4fe1d5c60dec7fa276ee99f30975','nice','nice','adjective','خوشایند','e186022d0931afe9fe0690857e32f85e50165e7fbe0966d49609ef1981f920c6','nova/audio/words/en-fa/84/nice-e1f5c3a115c2.mp3',789),
('d3250637e06cc4c50ea35fbf4a4f9a27909d54106d9f33000da3da4c0a413346','night','night','noun','شب','176473d7313395b6e209bc6b1d57aa160b628706860aa0554d7af60a1d40ab87','nova/audio/words/en-fa/d3/night-6211d38769da.mp3',789),
('360bbe2cd6e2c38ddadaeda2c058e6e8a70d1469c55dd47ed4f9cf65d5d7e948','nine','nine','noun','نه','edcd8e701a2df0cd66a39bae6aa156cf16fe2b9653ef65f7d31742e2352421e4','nova/audio/words/en-fa/36/nine-f3e67dc16cd9.mp3',836),
('5ddca08709d3ec32505e0e55fe2c226090df99a733df7203af9f62091b577c0c','no','no','interjection','نه','9390298f3fb0c5b160498935d79cb139aef28e1c47358b4bbba61862b9c26e59','nova/audio/words/en-fa/5d/no-02734665a1de.mp3',836),
('bb23c39e53a82f7a3fddc0279dcbfb5bea244fd965e92c4d29810233ffa70978','nora','nora','noun','نورا','b21ec07effd3fe307782e2a1782ae771e601b303cef1548723a76c539f98f383','nova/audio/words/en-fa/bb/nora-d20326ca673d.mp3',882),
('00d710f42b40958148796ba71d861ee1ce3e99866318154d229063b3904997c8','now','now','adverb','حالا','ed5eb9a37e2d8231af3388319b941995f6dc8755c56043d0cc52b5fe405a87de','nova/audio/words/en-fa/00/now-a01ffe27f0cb.mp3',975),
('0bc2ca5c3559f29eb26db5a9d9e548eed4af6a7d9ebacdbfb6eb419b5c8eda9b','number','number','noun','شماره','12886f9d00055adf24c40579e22d31b2b45f2023f892954ffd5567beb60825f8','nova/audio/words/en-fa/0b/number-f130b29b776c.mp3',929),
('b445631368126bfcc21d78019d54c0f6fa447c9736d900e0f918b4962fd14a11','office','office','noun','دفتر','5cc3f82838ba7260203e4590ce03d00e1663d41f6a5167144f5c95d6be2166a0','nova/audio/words/en-fa/b4/office-700ddf828f02.mp3',882),
('fd2abf7c98387ea4bab25beb9574936fe467545e386e4ff40e7186241d48f388','okay','okay','interjection','باشه','6a581ee901185606598bbd5369794c46dcf21ebf95955a46fb4a6244bb89e79f','nova/audio/words/en-fa/fd/okay-691d53dab721.mp3',836),
('a6244c1f39c094d83396187352977fd477f74ff95f4ba84d496e4c9b4f8eb76c','old','old','adjective','ساله','cba06b5736faf67e54b07b561eae94395e774c517a7d910a54369e1263ccfbd4','nova/audio/words/en-fa/a6/old-0ba9b36e00be.mp3',789),
('1f0292d21e2bb703f4d561d5b70ab9c8e99c71956179824729d19046607d68c3','on','on','adverb','روی','b8d31e852725afb1e26d53bab6095b2bff1749c9275be13ed1c05a56ed31ec09','nova/audio/words/en-fa/1f/on-fe08e8fa789a.mp3',743),
('a4b35c7244bc5242d39b99bd422c82711eb4cca72cbf3207f9eca5c54768d5c3','one','one','noun','یک','7692c3ad3540bb803c020b3aee66cd8887123234ea0c6e7143c0add73ff431ed','nova/audio/words/en-fa/a4/one-6f9b178cd961.mp3',743),
('31aff9d8f281c61f93502869624c9f2644875fbca5244ad98446a8c7b7587a0a','person','person','noun','شخص','38a81e87e79631e602bf5fbd307ce2fcd382b1670c585ea09032aac778a80531','nova/audio/words/en-fa/31/person-111ee10ead52.mp3',1022),
('f6d2ffefde1dff0c325e5fd7138833e97f2be895f6533dd25150d0de99857a27','phone','phone','noun','تلفن','45569da57f4b7bf472d7a864ef4781451cae6383fee9fb0ae40c59aa1ce475b7','nova/audio/words/en-fa/f6/phone-2f539a94a774.mp3',975),
('c46176b36dbb40565ccf0852fcb8990744eacea7be868886f3433ea9b3344499','please','please','interjection','لطفا','56ccc4dcfc96534b06fc0c08a301be24f13b491484d5d984953cc0dba9bbb89a','nova/audio/words/en-fa/c4/please-61802bc96020.mp3',1022),
('929e70881d9c6d2add0232f5b6348867cd0b22c7cdebde93e460eabc14c7c930','profile','profile','noun','پروفایل','1900eab6c028483d7126599ee6f50de0d27907b5c65fa90524580b4b0f9852b0','nova/audio/words/en-fa/92/profile-ee869da1f32d.mp3',1115),
('2d7caa8b8a81672ed2b973c2c60004839d40761cd15ac942b0ffc19f8b446cea','rahimi','rahimi','noun','رحیمی','1427baf9a991ef9db6aceecf01f7ca57c9b0474b1ce22053f7140cbd3e8e6491','nova/audio/words/en-fa/2d/rahimi-806b70d6dc88.mp3',1254),
('9048cc18ad71717fc6c65d7f94d8ff9e0ec1d5230c8945d9c651ef048dc4cec4','read','read','verb','خواندن کردن','3316348dbadfb7b11c7c2ea235949419e23f9fa898ad2c198f999617912a9925','nova/audio/words/en-fa/90/read-888da9878479.mp3',929),
('6446bc645282ce0aa9b060162bfbff162f46131dfd291761ebf3bb12219ef5f7','ready','ready','adjective','آماده','b24d6d33736ecd5604a4b17bc9c6481039fac362bb7df044ef1c10a2bfd21db6','nova/audio/words/en-fa/64/ready-e0f6bdf2f446.mp3',975),
('7889b085855d02f681edc372e99322d165e99a94ccdd21683a219002724b3eec','remember','remember','verb','به یاد داشتن','35379d9c009e290d702b72abf3f5f9bdbaa7e00a63fc37b5174fc3825c8095e3','nova/audio/words/en-fa/78/remember-500662ce3129.mp3',1161),
('2910f3c2a73cecac36bc01f89a2bce6e2ddcfd97ff7453cac4cf45988f43af1d','repeat','repeat','verb','تکرار کردن','25e2b6b106523880e27763084ffa6a0756335be0d7106022535365b9ad39b4b1','nova/audio/words/en-fa/29/repeat-114b057ca7e8.mp3',929),
('a4f0ba1bb7381bf6178efcaa003437ccdebf336a18281b058c01f0cc5f915cd6','roommate','roommate','noun','هم اتاقی','8e14091d9f705d36498151763a4ce908368f633162bcb62fd3ea5ff7d0812a5e','nova/audio/words/en-fa/a4/roommate-69e07e05283a.mp3',1022),
('ef1b8e26cc4310ed4845eed3d7eaa372039654439cc6cd6ef3d0202a9c2e1baa','saturday','Saturday','noun','شنبه','dbe35c7363c2f7ec747b902fb240907fc58ae00b98f107be2d4c7b9cd7f6226e','nova/audio/words/en-fa/ef/saturday-1855cd37fc0c.mp3',1068),
('28870a0ad22698a1f17766d6af5ec4bc4f76a6484a96075696c86e53147f7969','schedule','schedule','noun','برنامه','5f72005e81c4ecbd5aa3588e80e3daf0df068ce0cf5638944508a0165fea609a','nova/audio/words/en-fa/28/schedule-453870c3e8d6.mp3',1068),
('4ecb2483c8ddb517602fd6a588208073df78b757ede718677c3366dad8d83b7d','seven','seven','noun','هفت','3ba8d02b16fd2a01c1a8ba1a1f036d7ce386ed953696fa57331c2ac48a80b255','nova/audio/words/en-fa/4e/seven-40c3d72890a5.mp3',929),
('6b6ae86865558abed83e91970d0785c7235503a68c708f98490ac38c9cffd758','she','she','pronoun','او برای زن','2cda85e504e155f30a40f1f1cc4e83f3f8ec178033f6b6170cc9381f5e4f9d3d','nova/audio/words/en-fa/6b/she-79456ed21520.mp3',836),
('33ac9fe708719afd96858c946caa46f92f27432336fe80c731ffbc127cc05a9e','short','short','adjective','کوتاه','f9b0078b5df596d2ea19010c001bbd009e651de2c57e8fb7e355f31eb9d3f739','nova/audio/words/en-fa/33/short-4c2fd3d2d5fe.mp3',789),
('738468ee37de7a1cc82690c8724b11faa758a6cb9d45b4ea204fa60be53c632b','single','single','adjective','مجرد','947f187506f7629c81c81879a2cb2256455038e4ac770091d897fa0a8b945e3b','nova/audio/words/en-fa/73/single-a6443dfd6060.mp3',929),
('047e10f8a421580f5c0e9052e00993e3b8b5a9b6bdffa2eba3564807daade5a6','sister','sister','noun','خواهر','1980d3927f07fec9c8d727f187ddde727da7e45247dbb71c7555e5ae0eca66d5','nova/audio/words/en-fa/04/sister-73f8c46b8e04.mp3',1022),
('12077f36f67c23d42549212e796bba6f31fa0b5cfdf73771e2a4beb8e8a871dc','sit','sit','verb','نشستن کردن','584178e5e3517ddcebc66340917adc3a27ce4be359a29aa827563d481ff5d67a','nova/audio/words/en-fa/12/sit-186353bdc23f.mp3',789),
('b894128ad5d126c32c7f67cf90610260d42d51b2d946d35804773da0d28bb658','six','six','noun','شش','44778d82365e4af681c40d5f0eef5cf6f5899d3f0ac335050a7ed6779cf3f674','nova/audio/words/en-fa/b8/six-537c7a334dfa.mp3',882),
('81e2db8b7d21c121282cee55eaaccf5f5d4f43b5f9c43b0c06623d9a6d3a60c5','slowly','slowly','adverb','آهسته','793080bb3a187fcaeac15b1797045cda6103b8fbc8836642def618ccc41cf96a','nova/audio/words/en-fa/81/slowly-130da38f1f0b.mp3',1022),
('8ffb9602a63351b6c958b8ba735b59ab764137cd5691c43091d0d4286ed0b115','soup','soup','noun','سوپ','9014fac8184d7ba9e1dcd80b8c1e1aa2906af8a01fc1e6e9092e575eabf7b80d','nova/audio/words/en-fa/8f/soup-be05db81d5b6.mp3',836),
('6af021495d62804c18516dc571176a588de4a2fd148c655fe25420c2463f90af','speak','speak','verb','صحبت کردن','21e5205f73d9edbf72bc29b5ffcb4631cfc95e8f287c4d68e73d17ad72eb5eb3','nova/audio/words/en-fa/6a/speak-cd9e228146ad.mp3',836),
('f73d17c30e28354959c3319cb2535a76f67f02967e06fdb181427dda6a5879a3','spell','spell','verb','هجی کردن','8f4a0aaa62c4ceef88578b1b674070e6b8d9405b80729d5c7af2f353543b2f89','nova/audio/words/en-fa/f7/spell-76bc5b76b502.mp3',882),
('4cc1132624dc02fb709702a6079077ab165645b87a534b97767a1ac46d29d5c8','start','start','verb','شروع شدن','cced28c6dc3f99c2396a5eaad732bf6b28142335892b1cd0e6af6cdb53f5ccfa','nova/audio/words/en-fa/4c/start-a1e9e0f738b0.mp3',882),
('94b71bf5fc8eacf43bb73b46a49989c6444d26c8d085d207c4c0e81d7d9692be','street','street','noun','خیابان','6008c26f4452392acb19374bc12a5ec0c360ae17356bce8b786fb128c8720951','nova/audio/words/en-fa/94/street-21c943397787.mp3',882),
('fa3341f1e3be04380a1a9af37229788578a042ba5d4111a91b19608df12d9698','student','student','noun','دانشجو','264c8c381bf16c982a4e59b0dd4c6f7808c51a05f64c35db42cc78a2a72875bb','nova/audio/words/en-fa/fa/student-699c51864352.mp3',975),
('f9922c6f25a6a37dfe6044cc3623e3d68804210fd01f76d93d5562a93a10e75d','study','study','verb','درس خواندن','0c87ed818fb90f3f88faa6b362cf1e99025f3c1248f8fe513cdb38d03d9dce65','nova/audio/words/en-fa/f9/study-f3ee2b8b5c32.mp3',929),
('ac3f9bddc39889ba0d9a82f21e1d2360ed049b46ce6d5fa23e7f27378b0cc681','sunday','Sunday','noun','یکشنبه','873fef760e5d001ba0a843bf1846713fd92538699f323ef00d51f97a2ad2756c','nova/audio/words/en-fa/ac/sunday-fc610091f6da.mp3',882),
('bc5c3a9a06921e62cf86c3596431d42e5a5ad192e1966faa090bb5a60340c94e','surname','surname','noun','نام خانوادگی','655c32fb8455e927ccbd1057380081081024572b9c285d116213a426a0ee3747','nova/audio/words/en-fa/bc/surname-2a5e7ae6642f.mp3',1068),
('1b0caa4aef139981e3eaf699677de1b34d60c200f2f47eb3191bbd21884eb480','tea','tea','noun','چای','a9f74d1ec36ebdeb2da3f6e5868090cd2a2d20b3dcca7b62f60304b1d3d9ef42','nova/audio/words/en-fa/1b/tea-6c58cf226907.mp3',882),
('c7f3d4f5c82f958a9ee6eb92ec8fc09868cabb40bcf65877cf8092eb73867d74','teacher','teacher','noun','معلم','1057a9604e04b274da5a4de0c8f4b4868d9b230989f8c8c6a28221143cc5a755','nova/audio/words/en-fa/c7/teacher-a6f35c5673e9.mp3',882),
('df355eeae1ab7649e8b99faf887cff0a9fdd1cdd261174f94ff57932fa3c1307','team','team','noun','تیم','ca8b22d0db83a22db163b560b3e4e51527e533d31d067b614a0c33c4d2df8432','nova/audio/words/en-fa/df/team-1e5fd2c46edc.mp3',882),
('be204ff9711132720b49b0f900348febd63298a4704f48fa2b41c108f1095d36','ten','ten','noun','ده','e4432baa90819aaef51d2a7f8e148bf7e679610f3173752fabb4dcb2d0f418d3','nova/audio/words/en-fa/be/ten-ea52f4002f3a.mp3',975),
('07e1ed62cae2adfc1626816341c5214f7e8ec2109c5df85f12144a9bf16d5897','thank','thank','verb','تشکر کردن','e67fd73a84918e64c84f082cdc04e34435eb98acc712c8e8384268a7e7c5e208','nova/audio/words/en-fa/07/thank-0059e64be70b.mp3',882),
('7e7d53624fffb14403351d40ad33e432d4d57c2d67a394847e7feeca5bb72a6b','thanks','thanks','interjection','ممنون','a6a2729cbf6bcadce577a31f7f76201d5ce63c57d6c53318000d67714bb354ef','nova/audio/words/en-fa/7e/thanks-93b4a11f94cf.mp3',1022),
('b015d29c743b33dc460b65e5ca92670c55eaa2a0aa631151f534e7f268ee4011','the','the','determiner','حرف تعریف','b9776d7ddf459c9ad5b0e1d6ac61e27befb5e99fd62446677600d7cacef544d0','nova/audio/words/en-fa/b0/the-285f5d62fb5a.mp3',789),
('01bc2b30aa9ef36bf6c6dd808261fcad0d4abca4b3508aaa899a2b3232f5ead3','there','there','adverb','آنجا','e244f187f696561d5fd7e00f618e7ba641dc52e3c137380f6fa23a854b773aac','nova/audio/words/en-fa/01/there-84efc9803e2a.mp3',1068),
('0fde3ec94ab7004deae397c7e6564a498645a2103d0832b1cca4dd39ce9225b5','they','they','pronoun','آنها','151e58a831306903b282edb477bb6c4b713887cdd2b0353c84aff6f43da8e95d','nova/audio/words/en-fa/0f/they-d5497c682542.mp3',975),
('58c8fe3d14e456a4a10bc212bd435c282cbd8e94e27a052b56825dd54241bf64','thirty','thirty','number','سی','aca5fb59db69e5dffeda36ff0bd65205f16720b7fa1893c4557e9216dfc276d5','nova/audio/words/en-fa/58/thirty-9e8637984772.mp3',882),
('820dd642b710d566bdf2680698e9398336d704e7f296f7b7f63424fa8c5397a9','this','this','pronoun','این','1eb79602411ef02cf6fe117897015fff89f80face4eccd50425c45149b148408','nova/audio/words/en-fa/82/this-0e5c0a81838c.mp3',882),
('f9541f51c6ed7a81a9f584998933affbb344f4ef47a9da724c402c49d0980d39','three','three','noun','سه','8b5b9db0c13db24256c829aa364aa90c6d2eba318b9232a4ab9313b954d3555f','nova/audio/words/en-fa/f9/three-e137fba44897.mp3',1115),
('5e43250d71bd357f6343eb3dd035042a6ed83c31a19bfa1a48a8f5ad295e3caf','thursday','Thursday','noun','پنجشنبه','fc2662062ffdef9610020183ea2b087c21d71150d78a7c7463be8a9050bd3ac9','nova/audio/words/en-fa/5e/thursday-0db8e1cad2e7.mp3',1022),
('ad038c9eed13b83f3b2f4daa0173b563e1774e6a988006db5f6d9e9a1ad151b8','time','time','noun','زمان','336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e','nova/audio/words/en-fa/ad/time-54f404967ed0.mp3',1068),
('b4203baa2158cdff3c1ef7acc2e75b86ca79be06ee10b6019fa51632624fdefa','tired','tired','adjective','خسته','c405760daf9bc32b76f4a57e9c823c39de4645e3ba3dea73d671eee07e152b5d','nova/audio/words/en-fa/b4/tired-e0b112b24ed3.mp3',929),
('c71d167ede0d716b5a9e3993fc14d708e8ed97891bec11655f99c9e6355b03e8','to','to','adverb','به','663ea1bfffe5038f3f0cf667f14c4257eff52d77ce7f2a218f72e9286616ea39','nova/audio/words/en-fa/c7/to-7bd3358a7279.mp3',975),
('50233be2123f1472e24a0e0693bdf82e593507c035260ed4595e849959370d7f','today','today','adverb','امروز','e0f4f767ac88a9303e7317843ac20be980665a36f52397e5b26d4cc2bf54011d','nova/audio/words/en-fa/50/today-a7cb1bca19ab.mp3',929),
('97c366949289b60f03494d31c87923cb125152a3292a73419702248f8fd08c5a','together','together','adverb','با هم','0c24734d7bf5954f08e5bfe4820b0b2f63da8d658df37c9d50080485e034b721','nova/audio/words/en-fa/97/together-f6d1db06d3e5.mp3',1068),
('075c4804ed05e184d0415c4993251e54f58c3f93a2394342507898df3d4b4f21','tomorrow','tomorrow','adverb','فردا','bafd151a86f9a573b153e76e3a8a0053b3340ce304a301a5354288fb18bce848','nova/audio/words/en-fa/07/tomorrow-acdc79908461.mp3',1068),
('2c330f2a4d721671a0b5878b7f9a48a316f446399602f3b6ce5153d66af569f5','too','too','adverb','هم','94c05f1c45a1d1a913e041748ad9444083e9e398fc5719e02a4fc4874169a038','nova/audio/words/en-fa/2c/too-264ce78b0f7a.mp3',836),
('828a60e2f76ccab104dee617f46fa6e6d4ff4d4147771c9d6732551c5cc226d1','tuesday','Tuesday','noun','سه شنبه','7d8af1de1262f150187d5938bf649d6c35726970685f916d1ec6392a801b9762','nova/audio/words/en-fa/82/tuesday-2e851d214c01.mp3',1115),
('15a6a3aa066a61eb8b3632b25de4ae3f4022575befc1edca14e845e857393915','two','two','noun','دو','3fc4ccfe745870e2c0d99f71f30ff0656c8dedd41cc1d7d3d376b0dbe685e2f3','nova/audio/words/en-fa/15/two-1b95fa148240.mp3',789),
('430f48e1df371f1d364570565b2d90898de45d94fc952b0a9ebc5ba79a7e5f0d','wake','wake','verb','بیدار شدن','51391bf0ab33e8272bcfca0d61b5ab242391822f331fe51ac5930b58da8e5b25','nova/audio/words/en-fa/43/wake-c1b29e81d239.mp3',836),
('337592339eeb82a23cd2c92ba7bda88c790c7d1a8b3e1a236fbdea3ce439a859','we','we','pronoun','ما','dc7c811b9561739d9b75bb3e9e1715970a868834e62251b0b9ca02e74d0f42c9','nova/audio/words/en-fa/33/we-a217577e117b.mp3',789),
('9ce6107772e5ea9722842f9b1ec933aefb025f6c89581407e6879b94e4a40c1f','wednesday','Wednesday','noun','چهارشنبه','c0a6cc829cd08735294765c75938a7da2b0f222d52e98bff13cb237cd99deaac','nova/audio/words/en-fa/9c/wednesday-1f7624b50557.mp3',1068),
('0d3f05c780b82ff05753f76443ba89fec5222e407b9bef24bd866a4cecf5270e','weekend','Weekend','noun','آخر هفته','25014bff5f1f0a1bed626a81a5db5f88e52cb809aa47624b38df9dd538fac14c','nova/audio/words/en-fa/0d/weekend-bfc001bac553.mp3',1022),
('2736c511d0ee733df7f48a54e166a4942063b0cb66dc3edfd7af5f935509d8f3','welcome','welcome','interjection','خوش آمدن','280d44ab1e9f79b5cce2dd4f58f5fe91f0fbacdac9f7447dffc318ceb79f2d02','nova/audio/words/en-fa/27/welcome-ea72d2b4c418.mp3',1207),
('a4076001175042d01f54d729abbe415f2570a7cc5594b60f7333de1ac59da207','what','what','pronoun','چه','749ab2c0d06c42ae3b841b79e79875f02b3a042e43c92378cd28bd444c04d284','nova/audio/words/en-fa/a4/what-4526542edcf8.mp3',836),
('cbc70c77d6f3218f399bf2b25c2ad097b067d746f217eef67a34301593f11b33','when','when','adverb','چه زمانی','15eaa75240aed625be3e142205df3adbbb7051802b32f450e40276be8582b6d8','nova/audio/words/en-fa/cb/when-fa8743467304.mp3',882),
('0b1794b159bdb42d066f84b10b83b21506e9a31b1a83ac0f9cc136a905be3941','where','where','adverb','کجا','b48111c10c65fc119368edafb19f97451759ee90b3f44647368135ca47aa4753','nova/audio/words/en-fa/0b/where-6648160193c4.mp3',929),
('1805ed2d570644d2968a61714fbe5f576004140f1a8c43ef45c7c74977230734','who','who','pronoun','چه کسی','6ed0337140bd32b4adc5000f76333bd8ca6b2b2c9e0bc354335cf341456290e8','nova/audio/words/en-fa/18/who-460eda2c13d3.mp3',882),
('b045b8ee91b3b92e9bca8f31ae532ba3ab6014db834696257512237cebc1290d','with','with','adverb','با','0695b563acde461fc2f8d9aebccf35c7596ac458b8d8e067c602fb7b4e5f1578','nova/audio/words/en-fa/b0/with-c66cbb076ba7.mp3',743),
('5d152ddc72a65d1f833e2dea86397fcfd333dcd766e970f8b6bf0f5ad50b4e44','woman','woman','noun','زن','cf2e5bff1ef03dcd20d1a0b18ef7d89fc80a3554434165753672f6f40fde1d25','nova/audio/words/en-fa/5d/woman-718239c98950.mp3',882),
('ffbf98a7ce9d066b922b0a1e8fb40e2306ce9b7cc10960980e0b67b9294c04cb','work','work','noun','محل کار','00e13ed7af55b27622f1d6eab5bec0147e68efe28dc2b12461117afa1a5ed40e','nova/audio/words/en-fa/ff/work-ec2adcbda266.mp3',789),
('001020bf52267c04192bc6df8fc34b3817d792fe0a23531822ab3df79b177aae','work','work','verb','کار کردن','00e13ed7af55b27622f1d6eab5bec0147e68efe28dc2b12461117afa1a5ed40e','nova/audio/words/en-fa/00/work-ec2adcbda266.mp3',789),
('d049be9b5b0d3a6498437665c286e8efe84f749855c2f31530ae5a2eb735b754','yes','yes','interjection','بله','8a798890fe93817163b10b5f7bd2ca4d25d84c52739a645a889c173eee7d9d3d','nova/audio/words/en-fa/d0/yes-f0b54ff0977f.mp3',836),
('b15595b7ee2cdf2decdddee50d417073c4f9c8168b1f56abdab9e0f03c3545d2','you','you','pronoun','تو','bb0347a468d97e98a9c00e37cebec1ab930f6f1221cae0f1fbb92b07e1900ba2','nova/audio/words/en-fa/b1/you-2cc4bc175c70.mp3',697),
('7e99ee47eb0b42c78b82d3e32b976b82f00a5d9d169107c22ec75016ffbe28ca','your','your','determiner','مال تو','4d040d3f6466018c568aadf69a666d4257e5bb350a8e06f7198aedb6b12386fe','nova/audio/words/en-fa/7e/your-83c0605b9826.mp3',929),
('700213bf973f0251d3be441ac0a1be0edd774eb573da81c87d4d6eb5c1049ebc','zero','zero','noun','صفر','f9194e73f9e9459e3450ea10a179cdf77aafa695beecd3b9344a98d111622243','nova/audio/words/en-fa/70/zero-062f29561e6f.mp3',975);

DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DELIMITER $$
CREATE PROCEDURE apply_nova_word_audio()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_changed INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_expected INT UNSIGNED DEFAULT 0;
  DECLARE v_excluded_invalid INT UNSIGNED DEFAULT 0;
  DECLARE v_cleared INT UNSIGNED DEFAULT 0;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    ROLLBACK;
    RESIGNAL;
  END;

  SELECT id INTO v_course FROM courses
  WHERE learning_language='en' AND base_language='fa' ORDER BY id LIMIT 1;
  IF v_course IS NULL THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Nova en-fa course not found.';
  END IF;

  SELECT COUNT(*) INTO v_expected FROM nova_word_audio_updates;
  SELECT COUNT(*) INTO v_invalid
  FROM (
    SELECT u.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_updates AS u
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY u.lemma
     AND BINARY w.display_form=BINARY u.display_form
     AND BINARY w.part_of_speech=BINARY u.part_of_speech
     AND BINARY w.translation=BINARY u.translation
     AND SHA2(w.display_form,256)=u.text_sha256
    GROUP BY u.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_updates;
  IF v_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio update aborted: one or more Word locators did not match exactly once.';
  END IF;

  SELECT COUNT(*) INTO v_excluded_expected FROM nova_word_audio_exclusions;
  SELECT COUNT(*) INTO v_excluded_invalid
  FROM (
    SELECT x.word_key,COUNT(w.id) AS matched_rows
    FROM nova_word_audio_exclusions AS x
    LEFT JOIN words AS w
      ON w.course_id=v_course
     AND BINARY w.lemma=BINARY x.lemma
     AND BINARY w.display_form=BINARY x.display_form
     AND BINARY w.part_of_speech=BINARY x.part_of_speech
     AND BINARY w.translation=BINARY x.translation
     AND SHA2(w.display_form,256)=x.text_sha256
    GROUP BY x.word_key
    HAVING COUNT(w.id)<>1
  ) AS invalid_exclusions;
  IF v_excluded_invalid<>0 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT='Audio cleanup aborted: one or more excluded Word locators did not match exactly once.';
  END IF;

  START TRANSACTION;
  UPDATE words AS w
  JOIN nova_word_audio_exclusions AS x
    ON BINARY x.lemma=BINARY w.lemma
   AND BINARY x.display_form=BINARY w.display_form
   AND BINARY x.part_of_speech=BINARY w.part_of_speech
   AND BINARY x.translation=BINARY w.translation
   AND x.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=NULL,
      w.audio_duration_ms=NULL
  WHERE w.course_id=v_course
    AND (w.audio_url IS NOT NULL OR w.audio_duration_ms IS NOT NULL);
  SET v_cleared=ROW_COUNT();

  UPDATE words AS w
  JOIN nova_word_audio_updates AS u
    ON BINARY u.lemma=BINARY w.lemma
   AND BINARY u.display_form=BINARY w.display_form
   AND BINARY u.part_of_speech=BINARY w.part_of_speech
   AND BINARY u.translation=BINARY w.translation
   AND u.text_sha256=SHA2(w.display_form,256)
  SET w.audio_url=u.audio_url,
      w.audio_duration_ms=u.audio_duration_ms
  WHERE w.course_id=v_course;
  SET v_changed=ROW_COUNT();
  COMMIT;
  SELECT v_expected AS verified_words, v_changed AS changed_words,
         v_excluded_expected AS excluded_words, v_cleared AS cleared_words;
END$$
DELIMITER ;
CALL apply_nova_word_audio();
DROP PROCEDURE IF EXISTS apply_nova_word_audio;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_updates;
DROP TEMPORARY TABLE IF EXISTS nova_word_audio_exclusions;
