-- NOVA v9.0 / B1 SERIES 103 / Wenn es nicht besser wird, komme ich wieder
-- Requires canonical v9.0 and validated Series 102. No schema DDL.
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS import_nova_series_103_v9;
DELIMITER $$
CREATE PROCEDURE import_nova_series_103_v9()
BEGIN
  DECLARE v_course BIGINT UNSIGNED DEFAULT NULL; DECLARE v_level BIGINT UNSIGNED DEFAULT NULL; DECLARE v_module BIGINT UNSIGNED DEFAULT NULL; DECLARE v_chapter BIGINT UNSIGNED DEFAULT NULL; DECLARE v_count INT DEFAULT 0;
  DECLARE v_c_mia BIGINT UNSIGNED DEFAULT NULL; DECLARE v_c_sara BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_001 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_002 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_003 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_004 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_005 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_006 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_007 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_008 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_009 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_010 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_011 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_012 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_013 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_014 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_015 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_016 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_017 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_018 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_019 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_020 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_021 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_022 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_023 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_024 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_025 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_026 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_027 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_028 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_029 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_030 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_031 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_032 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_033 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_034 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_035 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_036 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_037 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_038 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_039 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_040 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_041 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_042 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_043 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_044 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_045 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_046 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_047 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_048 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_049 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_050 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_051 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_052 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_053 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_054 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_055 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_056 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_057 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_058 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_059 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_060 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_061 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_062 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_063 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_064 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_065 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_066 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_067 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_068 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_069 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_070 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_071 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_072 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_073 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_074 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_075 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_076 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_077 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_078 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_079 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_080 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_081 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_082 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_083 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_084 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_085 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_w_086 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_1 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_2 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_3 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_l_4 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_1 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_2 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_3 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_4 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_5 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_6 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_7 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_8 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_9 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_10 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_11 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_12 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_13 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_14 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_15 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_16 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_17 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_18 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_19 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_20 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_21 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_22 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_23 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE v_t_24 BIGINT UNSIGNED DEFAULT NULL;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;
  SELECT id INTO v_course FROM courses WHERE learning_language='de' AND base_language='fa' ORDER BY id LIMIT 1; IF v_course IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Canonical de-fa Course missing.'; END IF;
  SELECT id INTO v_level FROM levels WHERE course_id=v_course AND cefr_level='B1' AND sort_order=3 ORDER BY id LIMIT 1;
  SELECT id INTO v_module FROM modules WHERE level_id=v_level AND sort_order=5 ORDER BY id LIMIT 1; IF v_level IS NULL OR v_module IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='B1 dependency missing.'; END IF;
  SELECT COUNT(*) INTO v_count FROM chapters c JOIN modules m ON m.id=c.module_id WHERE m.level_id=v_level AND c.title='Der Arzt hat gesagt, dass ich mich ausruhen soll' AND c.status IN ('validated','complete'); IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 102 must be validated.'; END IF;
  SELECT COUNT(*) INTO v_count FROM lessons WHERE storyline_key='mia-sara-b1-health-routine'; IF v_count<>8 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Health storyline must contain exactly eight prior lessons.'; END IF;
  SELECT id INTO v_chapter FROM chapters WHERE module_id=v_module AND sort_order=3 ORDER BY id LIMIT 1; IF v_chapter IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 103 chapter missing.'; END IF;
  SELECT COUNT(*) INTO v_count FROM chapters WHERE id=v_chapter AND title='Wenn es nicht besser wird, komme ich wieder' AND title_translation='اگه بهتر نشه دوباره میام'; IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 103 canonical title mismatch.'; END IF;
  SELECT COUNT(*) INTO v_count FROM lessons WHERE chapter_id=v_chapter; IF v_count<>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 103 chapter must be empty.'; END IF;
  SELECT id INTO v_c_mia FROM characters WHERE course_id=v_course AND name='Mia' AND gender='female' LIMIT 1; SELECT id INTO v_c_sara FROM characters WHERE course_id=v_course AND name='Sara' AND gender='female' LIMIT 1;
  IF v_c_mia IS NULL OR v_c_sara IS NULL OR v_c_mia=v_c_sara THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Distinct Characters missing.'; END IF;
  SELECT id INTO v_w_001 FROM words WHERE course_id=v_course AND lemma='aber' AND part_of_speech='conjunction' AND translation='اما' ORDER BY id LIMIT 1;
  IF v_w_001 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: aber | conjunction'; END IF;
  SELECT id INTO v_w_002 FROM words WHERE course_id=v_course AND lemma='an' AND part_of_speech='preposition' AND translation='در / در روز' ORDER BY id LIMIT 1;
  IF v_w_002 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: an | preposition'; END IF;
  SELECT id INTO v_w_003 FROM words WHERE course_id=v_course AND lemma='anrufen' AND part_of_speech='verb' AND translation='زنگ زدن / تماس گرفتن' ORDER BY id LIMIT 1;
  IF v_w_003 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: anrufen | verb'; END IF;
  SELECT id INTO v_w_004 FROM words WHERE course_id=v_course AND lemma='Arzt' AND part_of_speech='noun' AND translation='دکتر' ORDER BY id LIMIT 1;
  IF v_w_004 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Arzt | noun'; END IF;
  SELECT id INTO v_w_005 FROM words WHERE course_id=v_course AND lemma='befolgen' AND part_of_speech='verb' AND translation='پیروی کردن / انجام دادن' ORDER BY id LIMIT 1;
  IF v_w_005 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'befolgen','befolgen','verb','پیروی کردن / انجام دادن',54,'{"type":"verb"}','[{"text":"warten","translation":"منتظر ماندن"},{"text":"fragen","translation":"پرسیدن"},{"text":"lernen","translation":"یاد گرفتن"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_005=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_006 FROM words WHERE course_id=v_course AND lemma='bekommen' AND part_of_speech='verb' AND translation='گرفتن / دچار شدن' ORDER BY id LIMIT 1;
  IF v_w_006 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'bekommen','bekommen','verb','گرفتن / دچار شدن',54,'{"type":"verb"}','[{"text":"warten","translation":"منتظر ماندن"},{"text":"fragen","translation":"پرسیدن"},{"text":"lernen","translation":"یاد گرفتن"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_006=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_007 FROM words WHERE course_id=v_course AND lemma='Beschwerde' AND part_of_speech='noun' AND translation='شکایت' ORDER BY id LIMIT 1;
  IF v_w_007 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Beschwerde | noun'; END IF;
  SELECT id INTO v_w_008 FROM words WHERE course_id=v_course AND lemma='besonders' AND part_of_speech='adverb' AND translation='مخصوصا' ORDER BY id LIMIT 1;
  IF v_w_008 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: besonders | adverb'; END IF;
  SELECT id INTO v_w_009 FROM words WHERE course_id=v_course AND lemma='bis' AND part_of_speech='conjunction' AND translation='تا' ORDER BY id LIMIT 1;
  IF v_w_009 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'bis','bis','conjunction','تا',54,'{"type":"conjunction"}','[{"text":"ruhig","translation":"آرام"},{"text":"teuer","translation":"گران"},{"text":"direkt","translation":"مستقیم"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_009=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_010 FROM words WHERE course_id=v_course AND lemma='bisschen' AND part_of_speech='noun' AND translation='کمی' ORDER BY id LIMIT 1;
  IF v_w_010 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'bisschen','bisschen','noun','کمی',54,'{"type":"noun"}','[{"text":"Zimmer","translation":"اتاق"},{"text":"Fenster","translation":"پنجره"},{"text":"Straße","translation":"خیابان"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_010=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_011 FROM words WHERE course_id=v_course AND lemma='brauchen' AND part_of_speech='verb' AND translation='نیاز داشتن / لازم داشتن' ORDER BY id LIMIT 1;
  IF v_w_011 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: brauchen | verb'; END IF;
  SELECT id INTO v_w_012 FROM words WHERE course_id=v_course AND lemma='da' AND part_of_speech='adverb' AND translation='آنجا' ORDER BY id LIMIT 1;
  IF v_w_012 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: da | adverb'; END IF;
  SELECT id INTO v_w_013 FROM words WHERE course_id=v_course AND lemma='damit' AND part_of_speech='conjunction' AND translation='تا / برای اینکه' ORDER BY id LIMIT 1;
  IF v_w_013 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'damit','damit','conjunction','تا / برای اینکه',54,'{"type":"conjunction"}','[{"text":"ruhig","translation":"آرام"},{"text":"teuer","translation":"گران"},{"text":"direkt","translation":"مستقیم"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_013=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_014 FROM words WHERE course_id=v_course AND lemma='dann' AND part_of_speech='adverb' AND translation='بعد / سپس' ORDER BY id LIMIT 1;
  IF v_w_014 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: dann | adverb'; END IF;
  SELECT id INTO v_w_015 FROM words WHERE course_id=v_course AND lemma='das' AND part_of_speech='pronoun' AND translation='این / آن' ORDER BY id LIMIT 1;
  IF v_w_015 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: das | pronoun'; END IF;
  SELECT id INTO v_w_016 FROM words WHERE course_id=v_course AND lemma='dass' AND part_of_speech='conjunction' AND translation='که' ORDER BY id LIMIT 1;
  IF v_w_016 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: dass | conjunction'; END IF;
  SELECT id INTO v_w_017 FROM words WHERE course_id=v_course AND lemma='dein' AND part_of_speech='determiner' AND translation='مال تو / تو' ORDER BY id LIMIT 1;
  IF v_w_017 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: dein | determiner'; END IF;
  SELECT id INTO v_w_018 FROM words WHERE course_id=v_course AND lemma='der' AND part_of_speech='article' AND translation='حرف تعریف' ORDER BY id LIMIT 1;
  IF v_w_018 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: der | article'; END IF;
  SELECT id INTO v_w_019 FROM words WHERE course_id=v_course AND lemma='du' AND part_of_speech='pronoun' AND translation='تو' ORDER BY id LIMIT 1;
  IF v_w_019 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: du | pronoun'; END IF;
  SELECT id INTO v_w_020 FROM words WHERE course_id=v_course AND lemma='ein' AND part_of_speech='article' AND translation='یک / حرف تعریف نامعین' ORDER BY id LIMIT 1;
  IF v_w_020 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: ein | article'; END IF;
  SELECT id INTO v_w_021 FROM words WHERE course_id=v_course AND lemma='es' AND part_of_speech='pronoun' AND translation='آن / این / ضمیر خنثی' ORDER BY id LIMIT 1;
  IF v_w_021 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: es | pronoun'; END IF;
  SELECT id INTO v_w_022 FROM words WHERE course_id=v_course AND lemma='etwas' AND part_of_speech='pronoun' AND translation='چیزی / یک چیزی' ORDER BY id LIMIT 1;
  IF v_w_022 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: etwas | pronoun'; END IF;
  SELECT id INTO v_w_023 FROM words WHERE course_id=v_course AND lemma='Fieber' AND part_of_speech='noun' AND translation='تب' ORDER BY id LIMIT 1;
  IF v_w_023 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Fieber | noun'; END IF;
  SELECT id INTO v_w_024 FROM words WHERE course_id=v_course AND lemma='fragen' AND part_of_speech='verb' AND translation='پرسیدن' ORDER BY id LIMIT 1;
  IF v_w_024 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: fragen | verb'; END IF;
  SELECT id INTO v_w_025 FROM words WHERE course_id=v_course AND lemma='gehen' AND part_of_speech='verb' AND translation='رفتن' ORDER BY id LIMIT 1;
  IF v_w_025 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: gehen | verb'; END IF;
  SELECT id INTO v_w_026 FROM words WHERE course_id=v_course AND lemma='genau' AND part_of_speech='adverb' AND translation='دقیقا' ORDER BY id LIMIT 1;
  IF v_w_026 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: genau | adverb'; END IF;
  SELECT id INTO v_w_027 FROM words WHERE course_id=v_course AND lemma='gleich' AND part_of_speech='adverb' AND translation='همین الان' ORDER BY id LIMIT 1;
  IF v_w_027 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: gleich | adverb'; END IF;
  SELECT id INTO v_w_028 FROM words WHERE course_id=v_course AND lemma='gut' AND part_of_speech='adjective' AND translation='خوب' ORDER BY id LIMIT 1;
  IF v_w_028 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: gut | adjective'; END IF;
  SELECT id INTO v_w_029 FROM words WHERE course_id=v_course AND lemma='haben' AND part_of_speech='verb' AND translation='داشتن' ORDER BY id LIMIT 1;
  IF v_w_029 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: haben | verb'; END IF;
  SELECT id INTO v_w_030 FROM words WHERE course_id=v_course AND lemma='heute' AND part_of_speech='adverb' AND translation='امروز' ORDER BY id LIMIT 1;
  IF v_w_030 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: heute | adverb'; END IF;
  SELECT id INTO v_w_031 FROM words WHERE course_id=v_course AND lemma='Hilfe' AND part_of_speech='noun' AND translation='کمک' ORDER BY id LIMIT 1;
  IF v_w_031 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Hilfe | noun'; END IF;
  SELECT id INTO v_w_032 FROM words WHERE course_id=v_course AND lemma='Ich weiß, wann ich wieder zum Arzt gehen muss.' AND part_of_speech='phrase' AND translation='می‌دانم چه زمانی باید دوباره پیش دکتر بروم.' ORDER BY id LIMIT 1;
  IF v_w_032 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Ich weiß, wann ich wieder zum Arzt gehen muss.','Ich weiß, wann ich wieder zum Arzt gehen muss.','phrase','می‌دانم چه زمانی باید دوباره پیش دکتر بروم.',54,'{"type":"phrase"}','[{"text":"ruhig","translation":"آرام"},{"text":"teuer","translation":"گران"},{"text":"direkt","translation":"مستقیم"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":false}'); SET v_w_032=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_033 FROM words WHERE course_id=v_course AND lemma='ich' AND part_of_speech='pronoun' AND translation='من' ORDER BY id LIMIT 1;
  IF v_w_033 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: ich | pronoun'; END IF;
  SELECT id INTO v_w_034 FROM words WHERE course_id=v_course AND lemma='in' AND part_of_speech='preposition' AND translation='در / داخل' ORDER BY id LIMIT 1;
  IF v_w_034 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: in | preposition'; END IF;
  SELECT id INTO v_w_035 FROM words WHERE course_id=v_course AND lemma='Ja, damit ich nicht lange warten muss.' AND part_of_speech='phrase' AND translation='بله، تا مجبور نباشم زیاد منتظر بمانم.' ORDER BY id LIMIT 1;
  IF v_w_035 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Ja, damit ich nicht lange warten muss.','Ja, damit ich nicht lange warten muss.','phrase','بله، تا مجبور نباشم زیاد منتظر بمانم.',54,'{"type":"phrase"}','[{"text":"ruhig","translation":"آرام"},{"text":"teuer","translation":"گران"},{"text":"direkt","translation":"مستقیم"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":false}'); SET v_w_035=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_036 FROM words WHERE course_id=v_course AND lemma='Ja, ich möchte morgen untersucht werden.' AND part_of_speech='phrase' AND translation='بله، می‌خواهم فردا معاینه شوم.' ORDER BY id LIMIT 1;
  IF v_w_036 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Ja, ich möchte morgen untersucht werden.','Ja, ich möchte morgen untersucht werden.','phrase','بله، می‌خواهم فردا معاینه شوم.',54,'{"type":"phrase"}','[{"text":"ruhig","translation":"آرام"},{"text":"teuer","translation":"گران"},{"text":"direkt","translation":"مستقیم"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":false}'); SET v_w_036=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_037 FROM words WHERE course_id=v_course AND lemma='ja' AND part_of_speech='interjection' AND translation='بله / آره' ORDER BY id LIMIT 1;
  IF v_w_037 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: ja | interjection'; END IF;
  SELECT id INTO v_w_038 FROM words WHERE course_id=v_course AND lemma='kommen' AND part_of_speech='verb' AND translation='آمدن' ORDER BY id LIMIT 1;
  IF v_w_038 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: kommen | verb'; END IF;
  SELECT id INTO v_w_039 FROM words WHERE course_id=v_course AND lemma='können' AND part_of_speech='verb' AND translation='توانستن / بتوان' ORDER BY id LIMIT 1;
  IF v_w_039 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: können | verb'; END IF;
  SELECT id INTO v_w_040 FROM words WHERE course_id=v_course AND lemma='Kopfschmerz' AND part_of_speech='noun' AND translation='سردرد' ORDER BY id LIMIT 1;
  IF v_w_040 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Kopfschmerz | noun'; END IF;
  SELECT id INTO v_w_041 FROM words WHERE course_id=v_course AND lemma='lang' AND part_of_speech='adjective' AND translation='طولانی / بلند' ORDER BY id LIMIT 1;
  IF v_w_041 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: lang | adjective'; END IF;
  SELECT id INTO v_w_042 FROM words WHERE course_id=v_course AND lemma='machen' AND part_of_speech='verb' AND translation='انجام دادن' ORDER BY id LIMIT 1;
  IF v_w_042 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: machen | verb'; END IF;
  SELECT id INTO v_w_043 FROM words WHERE course_id=v_course AND lemma='mein' AND part_of_speech='determiner' AND translation='مال من / من' ORDER BY id LIMIT 1;
  IF v_w_043 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: mein | determiner'; END IF;
  SELECT id INTO v_w_044 FROM words WHERE course_id=v_course AND lemma='messen' AND part_of_speech='verb' AND translation='اندازه گرفتن' ORDER BY id LIMIT 1;
  IF v_w_044 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'messen','messen','verb','اندازه گرفتن',54,'{"type":"verb"}','[{"text":"warten","translation":"منتظر ماندن"},{"text":"fragen","translation":"پرسیدن"},{"text":"lernen","translation":"یاد گرفتن"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_044=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_045 FROM words WHERE course_id=v_course AND lemma='mögen' AND part_of_speech='verb' AND translation='خواستن / دوست داشتن' ORDER BY id LIMIT 1;
  IF v_w_045 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: mögen | verb'; END IF;
  SELECT id INTO v_w_046 FROM words WHERE course_id=v_course AND lemma='morgen' AND part_of_speech='adverb' AND translation='فردا' ORDER BY id LIMIT 1;
  IF v_w_046 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: morgen | adverb'; END IF;
  SELECT id INTO v_w_047 FROM words WHERE course_id=v_course AND lemma='Morgen' AND part_of_speech='noun' AND translation='صبح' ORDER BY id LIMIT 1;
  IF v_w_047 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Morgen | noun'; END IF;
  SELECT id INTO v_w_048 FROM words WHERE course_id=v_course AND lemma='müde' AND part_of_speech='adjective' AND translation='خسته' ORDER BY id LIMIT 1;
  IF v_w_048 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: müde | adjective'; END IF;
  SELECT id INTO v_w_049 FROM words WHERE course_id=v_course AND lemma='müssen' AND part_of_speech='verb' AND translation='مجبور بودن / باید' ORDER BY id LIMIT 1;
  IF v_w_049 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: müssen | verb'; END IF;
  SELECT id INTO v_w_050 FROM words WHERE course_id=v_course AND lemma='nach' AND part_of_speech='preposition' AND translation='پس از / به' ORDER BY id LIMIT 1;
  IF v_w_050 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: nach | preposition'; END IF;
  SELECT id INTO v_w_051 FROM words WHERE course_id=v_course AND lemma='Nachmittag' AND part_of_speech='noun' AND translation='بعدازظهر' ORDER BY id LIMIT 1;
  IF v_w_051 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Nachmittag | noun'; END IF;
  SELECT id INTO v_w_052 FROM words WHERE course_id=v_course AND lemma='neu' AND part_of_speech='adjective' AND translation='جدید / تازه' ORDER BY id LIMIT 1;
  IF v_w_052 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: neu | adjective'; END IF;
  SELECT id INTO v_w_053 FROM words WHERE course_id=v_course AND lemma='nicht' AND part_of_speech='adverb' AND translation='نه / نیست' ORDER BY id LIMIT 1;
  IF v_w_053 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: nicht | adverb'; END IF;
  SELECT id INTO v_w_054 FROM words WHERE course_id=v_course AND lemma='noch' AND part_of_speech='adverb' AND translation='هنوز' ORDER BY id LIMIT 1;
  IF v_w_054 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: noch | adverb'; END IF;
  SELECT id INTO v_w_055 FROM words WHERE course_id=v_course AND lemma='plötzlich' AND part_of_speech='adverb' AND translation='ناگهان' ORDER BY id LIMIT 1;
  IF v_w_055 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: plötzlich | adverb'; END IF;
  SELECT id INTO v_w_056 FROM words WHERE course_id=v_course AND lemma='Praxis' AND part_of_speech='noun' AND translation='مطب' ORDER BY id LIMIT 1;
  IF v_w_056 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Praxis','Praxis','noun','مطب',54,'{"type":"noun"}','[{"text":"Zimmer","translation":"اتاق"},{"text":"Fenster","translation":"پنجره"},{"text":"Straße","translation":"خیابان"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_056=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_057 FROM words WHERE course_id=v_course AND lemma='Rat' AND part_of_speech='noun' AND translation='توصیه / راهنمایی' ORDER BY id LIMIT 1;
  IF v_w_057 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Rat | noun'; END IF;
  SELECT id INTO v_w_058 FROM words WHERE course_id=v_course AND lemma='sagen' AND part_of_speech='verb' AND translation='گفتن' ORDER BY id LIMIT 1;
  IF v_w_058 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sagen | verb'; END IF;
  SELECT id INTO v_w_059 FROM words WHERE course_id=v_course AND lemma='schlafen' AND part_of_speech='verb' AND translation='خوابیدن' ORDER BY id LIMIT 1;
  IF v_w_059 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: schlafen | verb'; END IF;
  SELECT id INTO v_w_060 FROM words WHERE course_id=v_course AND lemma='sein' AND part_of_speech='verb' AND translation='بودن' ORDER BY id LIMIT 1;
  IF v_w_060 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sein | verb'; END IF;
  SELECT id INTO v_w_061 FROM words WHERE course_id=v_course AND lemma='selbst' AND part_of_speech='pronoun' AND translation='خود / خودم' ORDER BY id LIMIT 1;
  IF v_w_061 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: selbst | pronoun'; END IF;
  SELECT id INTO v_w_062 FROM words WHERE course_id=v_course AND lemma='sich ausruhen' AND part_of_speech='verb' AND translation='استراحت کردن' ORDER BY id LIMIT 1;
  IF v_w_062 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sich ausruhen | verb'; END IF;
  SELECT id INTO v_w_063 FROM words WHERE course_id=v_course AND lemma='sie' AND part_of_speech='pronoun' AND translation='او / آن ها' ORDER BY id LIMIT 1;
  IF v_w_063 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sie | pronoun'; END IF;
  SELECT id INTO v_w_064 FROM words WHERE course_id=v_course AND lemma='sofort' AND part_of_speech='adverb' AND translation='فورا / همین الان' ORDER BY id LIMIT 1;
  IF v_w_064 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sofort | adverb'; END IF;
  SELECT id INTO v_w_065 FROM words WHERE course_id=v_course AND lemma='sollen' AND part_of_speech='verb' AND translation='باید / قرار است' ORDER BY id LIMIT 1;
  IF v_w_065 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: sollen | verb'; END IF;
  SELECT id INTO v_w_066 FROM words WHERE course_id=v_course AND lemma='Telefon' AND part_of_speech='noun' AND translation='تلفن' ORDER BY id LIMIT 1;
  IF v_w_066 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Telefon','Telefon','noun','تلفن',54,'{"type":"noun"}','[{"text":"Zimmer","translation":"اتاق"},{"text":"Fenster","translation":"پنجره"},{"text":"Straße","translation":"خیابان"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_066=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_067 FROM words WHERE course_id=v_course AND lemma='Temperatur' AND part_of_speech='noun' AND translation='دما / درجه حرارت' ORDER BY id LIMIT 1;
  IF v_w_067 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Temperatur','Temperatur','noun','دما / درجه حرارت',54,'{"type":"noun"}','[{"text":"Zimmer","translation":"اتاق"},{"text":"Fenster","translation":"پنجره"},{"text":"Straße","translation":"خیابان"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":true}'); SET v_w_067=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_068 FROM words WHERE course_id=v_course AND lemma='Termin' AND part_of_speech='noun' AND translation='قرار / وقت' ORDER BY id LIMIT 1;
  IF v_w_068 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Termin | noun'; END IF;
  SELECT id INTO v_w_069 FROM words WHERE course_id=v_course AND lemma='trinken' AND part_of_speech='verb' AND translation='نوشیدن' ORDER BY id LIMIT 1;
  IF v_w_069 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: trinken | verb'; END IF;
  SELECT id INTO v_w_070 FROM words WHERE course_id=v_course AND lemma='und' AND part_of_speech='conjunction' AND translation='و' ORDER BY id LIMIT 1;
  IF v_w_070 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: und | conjunction'; END IF;
  SELECT id INTO v_w_071 FROM words WHERE course_id=v_course AND lemma='untersuchen' AND part_of_speech='verb' AND translation='معاینه کردن' ORDER BY id LIMIT 1;
  IF v_w_071 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: untersuchen | verb'; END IF;
  SELECT id INTO v_w_072 FROM words WHERE course_id=v_course AND lemma='vereinbaren' AND part_of_speech='verb' AND translation='توافق کردن / تعیین کردن' ORDER BY id LIMIT 1;
  IF v_w_072 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: vereinbaren | verb'; END IF;
  SELECT id INTO v_w_073 FROM words WHERE course_id=v_course AND lemma='viel' AND part_of_speech='determiner' AND translation='زیاد / مقدار زیاد' ORDER BY id LIMIT 1;
  IF v_w_073 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: viel | determiner'; END IF;
  SELECT id INTO v_w_074 FROM words WHERE course_id=v_course AND lemma='vorher' AND part_of_speech='adverb' AND translation='قبلش / پیش از آن' ORDER BY id LIMIT 1;
  IF v_w_074 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: vorher | adverb'; END IF;
  SELECT id INTO v_w_075 FROM words WHERE course_id=v_course AND lemma='wann' AND part_of_speech='adverb' AND translation='کی / چه زمانی' ORDER BY id LIMIT 1;
  IF v_w_075 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wann | adverb'; END IF;
  SELECT id INTO v_w_076 FROM words WHERE course_id=v_course AND lemma='warten' AND part_of_speech='verb' AND translation='منتظر ماندن / صبر کردن' ORDER BY id LIMIT 1;
  IF v_w_076 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: warten | verb'; END IF;
  SELECT id INTO v_w_077 FROM words WHERE course_id=v_course AND lemma='was' AND part_of_speech='pronoun' AND translation='چی / چه' ORDER BY id LIMIT 1;
  IF v_w_077 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: was | pronoun'; END IF;
  SELECT id INTO v_w_078 FROM words WHERE course_id=v_course AND lemma='Wasser' AND part_of_speech='noun' AND translation='آب' ORDER BY id LIMIT 1;
  IF v_w_078 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: Wasser | noun'; END IF;
  SELECT id INTO v_w_079 FROM words WHERE course_id=v_course AND lemma='weiter' AND part_of_speech='adverb' AND translation='ادامه / بیشتر' ORDER BY id LIMIT 1;
  IF v_w_079 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: weiter | adverb'; END IF;
  SELECT id INTO v_w_080 FROM words WHERE course_id=v_course AND lemma='Wenn es nicht besser wird, komme ich wieder.' AND part_of_speech='phrase' AND translation='اگر بهتر نشود، دوباره می‌آیم.' ORDER BY id LIMIT 1;
  IF v_w_080 IS NULL THEN INSERT INTO words(course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,audio_url,audio_duration_ms,metadata) VALUES(v_course,'Wenn es nicht besser wird, komme ich wieder.','Wenn es nicht besser wird, komme ich wieder.','phrase','اگر بهتر نشود، دوباره می‌آیم.',54,'{"type":"phrase"}','[{"text":"ruhig","translation":"آرام"},{"text":"teuer","translation":"گران"},{"text":"direkt","translation":"مستقیم"}]','Wenn es nicht besser wird, komme ich wieder','اگه بهتر نشه دوباره میام',NULL,NULL,'{"cefr":"B1","introducedInSeries":103,"wordAudioEligible":false}'); SET v_w_080=LAST_INSERT_ID(); END IF;
  SELECT id INTO v_w_081 FROM words WHERE course_id=v_course AND lemma='wenn' AND part_of_speech='conjunction' AND translation='اگر / وقتی' ORDER BY id LIMIT 1;
  IF v_w_081 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wenn | conjunction'; END IF;
  SELECT id INTO v_w_082 FROM words WHERE course_id=v_course AND lemma='werden' AND part_of_speech='verb' AND translation='شدن / خواهد' ORDER BY id LIMIT 1;
  IF v_w_082 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: werden | verb'; END IF;
  SELECT id INTO v_w_083 FROM words WHERE course_id=v_course AND lemma='wie' AND part_of_speech='adverb' AND translation='چطور / چگونه' ORDER BY id LIMIT 1;
  IF v_w_083 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wie | adverb'; END IF;
  SELECT id INTO v_w_084 FROM words WHERE course_id=v_course AND lemma='wieder' AND part_of_speech='adverb' AND translation='دوباره' ORDER BY id LIMIT 1;
  IF v_w_084 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wieder | adverb'; END IF;
  SELECT id INTO v_w_085 FROM words WHERE course_id=v_course AND lemma='wissen' AND part_of_speech='verb' AND translation='دانستن' ORDER BY id LIMIT 1;
  IF v_w_085 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: wissen | verb'; END IF;
  SELECT id INTO v_w_086 FROM words WHERE course_id=v_course AND lemma='zu' AND part_of_speech='preposition' AND translation='به / به سمت' ORDER BY id LIMIT 1;
  IF v_w_086 IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Required canonical tuple missing: zu | preposition'; END IF;
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'Am nächsten Morgen','صبح روز بعد','Sara fragt nach Mias Zustand; Mia vergleicht ihre Beschwerden mit dem Vortag und nennt den Plan des Arztes.','سارا دربارهٔ حال میا می‌پرسد؛ میا نشانه‌هایش را با روز قبل مقایسه می‌کند و برنامهٔ دکتر را می‌گوید.','story','mia-sara-b1-health-routine',9,54,180,1,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"check-recovery"}'); SET v_l_1=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_sara,1,'character','Wie geht es dir heute Morgen?','امروز صبح حالت چطور است؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Wie","lemma":"wie","translation":"چطور / چگونه","partOfSpeech":"adverb"},{"surface":"geht","lemma":"gehen","translation":"رفتن","partOfSpeech":"verb"},{"surface":"es","lemma":"es","translation":"آن / این / ضمیر خنثی","partOfSpeech":"pronoun"},{"surface":"dir","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"heute","lemma":"heute","translation":"امروز","partOfSpeech":"adverb"},{"surface":"Morgen","lemma":"Morgen","translation":"صبح","partOfSpeech":"noun","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_1=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_mia,2,'learner','Etwas besser, aber ich bin noch müde.','کمی بهترم، اما هنوز خسته‌ام.',54,NULL,NULL,'etwas besser aber ich bin noch müde',NULL,'[{"surface":"Etwas","lemma":"etwas","translation":"چیزی / یک چیزی","partOfSpeech":"pronoun"},{"surface":"besser","lemma":"gut","translation":"خوب","partOfSpeech":"adjective","suffix":","},{"surface":"aber","lemma":"aber","translation":"اما","partOfSpeech":"conjunction"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"bin","lemma":"sein","translation":"بودن","partOfSpeech":"verb"},{"surface":"noch","lemma":"noch","translation":"هنوز","partOfSpeech":"adverb"},{"surface":"müde","lemma":"müde","translation":"خسته","partOfSpeech":"adjective","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_2=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_sara,3,'character','Hast du den Rat des Arztes befolgt?','توصیهٔ دکتر را انجام دادی؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Hast","lemma":"haben","translation":"داشتن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"den","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Rat","lemma":"Rat","translation":"توصیه / راهنمایی","partOfSpeech":"noun"},{"surface":"des","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Arztes","lemma":"Arzt","translation":"دکتر","partOfSpeech":"noun"},{"surface":"befolgt","lemma":"befolgen","translation":"پیروی کردن / انجام دادن","partOfSpeech":"verb","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_3=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_mia,4,'learner','Ja, ich habe viel geschlafen und Wasser getrunken.','بله، زیاد خوابیدم و آب نوشیدم.',54,NULL,NULL,'ja ich habe viel geschlafen und wasser getrunken',NULL,'[{"surface":"Ja","lemma":"ja","translation":"بله / آره","partOfSpeech":"interjection","suffix":","},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"habe","lemma":"haben","translation":"داشتن","partOfSpeech":"verb"},{"surface":"viel","lemma":"viel","translation":"زیاد / مقدار زیاد","partOfSpeech":"determiner"},{"surface":"geschlafen","lemma":"schlafen","translation":"خوابیدن","partOfSpeech":"verb"},{"surface":"und","lemma":"und","translation":"و","partOfSpeech":"conjunction"},{"surface":"Wasser","lemma":"Wasser","translation":"آب","partOfSpeech":"noun"},{"surface":"getrunken","lemma":"trinken","translation":"نوشیدن","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_4=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_sara,5,'character','Was machst du, wenn es nicht besser wird?','اگر بهتر نشود چه کار می‌کنی؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Was","lemma":"was","translation":"چی / چه","partOfSpeech":"pronoun"},{"surface":"machst","lemma":"machen","translation":"انجام دادن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun","suffix":","},{"surface":"wenn","lemma":"wenn","translation":"اگر / وقتی","partOfSpeech":"conjunction"},{"surface":"es","lemma":"es","translation":"آن / این / ضمیر خنثی","partOfSpeech":"pronoun"},{"surface":"nicht","lemma":"nicht","translation":"نه / نیست","partOfSpeech":"adverb"},{"surface":"besser","lemma":"gut","translation":"خوب","partOfSpeech":"adjective"},{"surface":"wird","lemma":"werden","translation":"شدن / خواهد","partOfSpeech":"verb","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_5=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_1,v_c_mia,6,'learner','Wenn es nicht besser wird, komme ich wieder.','اگر بهتر نشود، دوباره می‌آیم.',54,NULL,NULL,'wenn es nicht besser wird komme ich wieder',NULL,'[{"surface":"Wenn","lemma":"wenn","translation":"اگر / وقتی","partOfSpeech":"conjunction"},{"surface":"es","lemma":"es","translation":"آن / این / ضمیر خنثی","partOfSpeech":"pronoun"},{"surface":"nicht","lemma":"nicht","translation":"نه / نیست","partOfSpeech":"adverb"},{"surface":"besser","lemma":"gut","translation":"خوب","partOfSpeech":"adjective"},{"surface":"wird","lemma":"werden","translation":"شدن / خواهد","partOfSpeech":"verb","suffix":","},{"surface":"komme","lemma":"kommen","translation":"آمدن","partOfSpeech":"verb"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"wieder","lemma":"wieder","translation":"دوباره","partOfSpeech":"adverb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_6=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_083,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_025,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_021,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_019,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_030,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_047,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_022,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_028,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_001,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_033,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_060,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_054,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_048,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_029,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_018,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_057,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_004,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_005,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_037,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_073,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_059,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_070,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_078,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_069,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_077,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_042,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_081,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_053,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_082,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_038,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_084,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_1,v_w_080,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'new_word',1,NULL,v_w_080,'عبارت کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'new_word',2,NULL,v_w_005,'واژهٔ کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'listen',3,v_t_1,NULL,'به جملهٔ سارا گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'speak',4,v_t_2,NULL,'پاسخ میا را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'listen',5,v_t_5,NULL,'به جملهٔ بعدی گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'speak',6,v_t_6,NULL,'پاسخ را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'meaning_choice',7,NULL,v_w_005,'معنی واژهٔ کلیدی را انتخاب کن',NULL,54,'{"mode":"word_translation","question":"befolgen در این درس چه معنی دارد؟","choices":["پیروی کردن / انجام دادن","رزرو قطار","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_1,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,54,'{"source":"lesson_story","question":"اگر حال میا بهتر نشود چه می‌کند؟","choices":["دوباره پیش دکتر می‌رود","به سفر می‌رود","بیشتر کار می‌کند"],"correctIndex":0}','{"cefr":"B1","series":103}');
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'Beschwerden beobachten','بررسی نشانه‌ها','Mia beobachtet Kopfschmerzen und Temperatur und bereitet einen möglichen Praxisbesuch vor.','میا سردرد و دمای بدنش را بررسی می‌کند و برای مراجعهٔ احتمالی به مطب آماده می‌شود.','story','mia-sara-b1-health-routine',10,54,180,2,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"monitor-symptoms"}'); SET v_l_2=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_sara,1,'character','Hast du noch Kopfschmerzen?','هنوز سردرد داری؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Hast","lemma":"haben","translation":"داشتن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"noch","lemma":"noch","translation":"هنوز","partOfSpeech":"adverb"},{"surface":"Kopfschmerzen","lemma":"Kopfschmerz","translation":"سردرد","partOfSpeech":"noun","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_7=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_mia,2,'learner','Ein bisschen, besonders am Nachmittag.','کمی، به‌خصوص بعدازظهر.',54,NULL,NULL,'ein bisschen besonders am nachmittag',NULL,'[{"surface":"Ein","lemma":"ein","translation":"یک / حرف تعریف نامعین","partOfSpeech":"article"},{"surface":"bisschen","lemma":"bisschen","translation":"کمی","partOfSpeech":"noun","suffix":","},{"surface":"besonders","lemma":"besonders","translation":"مخصوصا","partOfSpeech":"adverb"},{"surface":"am","lemma":"an","translation":"در / در روز","partOfSpeech":"preposition"},{"surface":"Nachmittag","lemma":"Nachmittag","translation":"بعدازظهر","partOfSpeech":"noun","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_8=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_sara,3,'character','Dann solltest du deine Temperatur messen.','پس بهتر است دمای بدنت را اندازه بگیری.',54,NULL,NULL,NULL,NULL,'[{"surface":"Dann","lemma":"dann","translation":"بعد / سپس","partOfSpeech":"adverb"},{"surface":"solltest","lemma":"sollen","translation":"باید / قرار است","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"deine","lemma":"dein","translation":"مال تو / تو","partOfSpeech":"determiner"},{"surface":"Temperatur","lemma":"Temperatur","translation":"دما / درجه حرارت","partOfSpeech":"noun"},{"surface":"messen","lemma":"messen","translation":"اندازه گرفتن","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_9=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_mia,4,'learner','Ja, ich messe sie gleich.','بله، همین حالا آن را اندازه می‌گیرم.',54,NULL,NULL,'ja ich messe sie gleich',NULL,'[{"surface":"Ja","lemma":"ja","translation":"بله / آره","partOfSpeech":"interjection","suffix":","},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"messe","lemma":"messen","translation":"اندازه گرفتن","partOfSpeech":"verb"},{"surface":"sie","lemma":"sie","translation":"او / آن ها","partOfSpeech":"pronoun"},{"surface":"gleich","lemma":"gleich","translation":"همین الان","partOfSpeech":"adverb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_10=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_sara,5,'character','Rufst du vorher in der Praxis an?','قبلش به مطب زنگ می‌زنی؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Rufst","lemma":"anrufen","translation":"زنگ زدن / تماس گرفتن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"vorher","lemma":"vorher","translation":"قبلش / پیش از آن","partOfSpeech":"adverb"},{"surface":"in","lemma":"in","translation":"در / داخل","partOfSpeech":"preposition"},{"surface":"der","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Praxis","lemma":"Praxis","translation":"مطب","partOfSpeech":"noun"},{"surface":"an","lemma":"anrufen","translation":"زنگ زدن / تماس گرفتن","partOfSpeech":"verb","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_11=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_2,v_c_mia,6,'learner','Ja, damit ich nicht lange warten muss.','بله، تا مجبور نباشم زیاد منتظر بمانم.',54,NULL,NULL,'ja damit ich nicht lange warten muss',NULL,'[{"surface":"Ja","lemma":"ja","translation":"بله / آره","partOfSpeech":"interjection","suffix":","},{"surface":"damit","lemma":"damit","translation":"تا / برای اینکه","partOfSpeech":"conjunction"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"nicht","lemma":"nicht","translation":"نه / نیست","partOfSpeech":"adverb"},{"surface":"lange","lemma":"lang","translation":"طولانی / بلند","partOfSpeech":"adjective"},{"surface":"warten","lemma":"warten","translation":"منتظر ماندن / صبر کردن","partOfSpeech":"verb"},{"surface":"muss","lemma":"müssen","translation":"مجبور بودن / باید","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_12=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_029,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_019,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_054,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_040,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_020,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_010,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_008,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_002,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_051,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_014,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_065,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_017,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_067,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_044,'new',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_037,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_033,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_063,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_027,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_003,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_074,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_034,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_018,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_056,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_013,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_053,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_041,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_076,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_049,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_2,v_w_035,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'new_word',1,NULL,v_w_035,'عبارت کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'new_word',2,NULL,v_w_067,'واژهٔ کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'listen',3,v_t_7,NULL,'به جملهٔ سارا گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'speak',4,v_t_8,NULL,'پاسخ میا را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'listen',5,v_t_11,NULL,'به جملهٔ بعدی گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'speak',6,v_t_12,NULL,'پاسخ را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'meaning_choice',7,NULL,v_w_067,'معنی واژهٔ کلیدی را انتخاب کن',NULL,54,'{"mode":"word_translation","question":"Temperatur در این درس چه معنی دارد؟","choices":["دما / درجه حرارت","رزرو قطار","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_2,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,54,'{"source":"lesson_story","question":"میا چه چیزی را اندازه می‌گیرد؟","choices":["دمای بدنش","قدش","فشار لاستیک"],"correctIndex":0}','{"cefr":"B1","series":103}');
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'In der Praxis anrufen','تماس با مطب','Mia übt, ihre anhaltenden Beschwerden am Telefon zu erklären und einen neuen Termin zu vereinbaren.','میا تمرین می‌کند نشانه‌های ادامه‌دارش را تلفنی توضیح دهد و وقت تازه‌ای بگیرد.','story','mia-sara-b1-health-routine',11,54,180,3,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"call-practice"}'); SET v_l_3=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_sara,1,'character','Was sagst du am Telefon?','پشت تلفن چه می‌گویی؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Was","lemma":"was","translation":"چی / چه","partOfSpeech":"pronoun"},{"surface":"sagst","lemma":"sagen","translation":"گفتن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"am","lemma":"an","translation":"در / در روز","partOfSpeech":"preposition"},{"surface":"Telefon","lemma":"Telefon","translation":"تلفن","partOfSpeech":"noun","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_13=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_mia,2,'learner','Ich sage, dass meine Beschwerden noch da sind.','می‌گویم که نشانه‌هایم هنوز وجود دارند.',54,NULL,NULL,'ich sage dass meine beschwerden noch da sind',NULL,'[{"surface":"Ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"sage","lemma":"sagen","translation":"گفتن","partOfSpeech":"verb","suffix":","},{"surface":"dass","lemma":"dass","translation":"که","partOfSpeech":"conjunction"},{"surface":"meine","lemma":"mein","translation":"مال من / من","partOfSpeech":"determiner"},{"surface":"Beschwerden","lemma":"Beschwerde","translation":"شکایت","partOfSpeech":"noun"},{"surface":"noch","lemma":"noch","translation":"هنوز","partOfSpeech":"adverb"},{"surface":"da","lemma":"da","translation":"آنجا","partOfSpeech":"adverb"},{"surface":"sind","lemma":"sein","translation":"بودن","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_14=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_sara,3,'character','Fragst du nach einem neuen Termin?','برای یک وقت تازه درخواست می‌کنی؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Fragst","lemma":"fragen","translation":"پرسیدن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"nach","lemma":"nach","translation":"پس از / به","partOfSpeech":"preposition"},{"surface":"einem","lemma":"ein","translation":"یک / حرف تعریف نامعین","partOfSpeech":"article"},{"surface":"neuen","lemma":"neu","translation":"جدید / تازه","partOfSpeech":"adjective"},{"surface":"Termin","lemma":"Termin","translation":"قرار / وقت","partOfSpeech":"noun","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_15=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_mia,4,'learner','Ja, ich möchte morgen untersucht werden.','بله، می‌خواهم فردا معاینه شوم.',54,NULL,NULL,'ja ich möchte morgen untersucht werden',NULL,'[{"surface":"Ja","lemma":"ja","translation":"بله / آره","partOfSpeech":"interjection","suffix":","},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"möchte","lemma":"mögen","translation":"خواستن / دوست داشتن","partOfSpeech":"verb"},{"surface":"morgen","lemma":"morgen","translation":"فردا","partOfSpeech":"adverb"},{"surface":"untersucht","lemma":"untersuchen","translation":"معاینه کردن","partOfSpeech":"verb"},{"surface":"werden","lemma":"werden","translation":"شدن / خواهد","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_16=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_sara,5,'character','Kannst du den Termin selbst vereinbaren?','خودت می‌توانی وقت بگیری؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Kannst","lemma":"können","translation":"توانستن / بتوان","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"den","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Termin","lemma":"Termin","translation":"قرار / وقت","partOfSpeech":"noun"},{"surface":"selbst","lemma":"selbst","translation":"خود / خودم","partOfSpeech":"pronoun"},{"surface":"vereinbaren","lemma":"vereinbaren","translation":"توافق کردن / تعیین کردن","partOfSpeech":"verb","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_17=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_3,v_c_mia,6,'learner','Ja, ich rufe gleich in der Praxis an.','بله، همین حالا به مطب زنگ می‌زنم.',54,NULL,NULL,'ja ich rufe gleich in der praxis an',NULL,'[{"surface":"Ja","lemma":"ja","translation":"بله / آره","partOfSpeech":"interjection","suffix":","},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"rufe","lemma":"anrufen","translation":"زنگ زدن / تماس گرفتن","partOfSpeech":"verb"},{"surface":"gleich","lemma":"gleich","translation":"همین الان","partOfSpeech":"adverb"},{"surface":"in","lemma":"in","translation":"در / داخل","partOfSpeech":"preposition"},{"surface":"der","lemma":"der","translation":"حرف تعریف","partOfSpeech":"article"},{"surface":"Praxis","lemma":"Praxis","translation":"مطب","partOfSpeech":"noun"},{"surface":"an","lemma":"anrufen","translation":"زنگ زدن / تماس گرفتن","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_18=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_077,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_058,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_019,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_002,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_066,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_033,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_016,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_043,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_007,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_054,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_012,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_060,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_024,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_050,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_020,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_052,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_068,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_037,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_045,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_046,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_071,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_082,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_039,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_018,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_061,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_072,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_003,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_027,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_034,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_056,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_3,v_w_036,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'new_word',1,NULL,v_w_036,'عبارت کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'new_word',2,NULL,v_w_056,'واژهٔ کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'listen',3,v_t_13,NULL,'به جملهٔ سارا گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'speak',4,v_t_14,NULL,'پاسخ میا را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'listen',5,v_t_17,NULL,'به جملهٔ بعدی گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'speak',6,v_t_18,NULL,'پاسخ را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'meaning_choice',7,NULL,v_w_056,'معنی واژهٔ کلیدی را انتخاب کن',NULL,54,'{"mode":"word_translation","question":"Praxis در این درس چه معنی دارد؟","choices":["مطب","رزرو قطار","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_3,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,54,'{"source":"lesson_story","question":"میا از مطب چه می‌خواهد؟","choices":["یک وقت تازه","بلیط قطار","سفارش غذا"],"correctIndex":0}','{"cefr":"B1","series":103}');
  INSERT INTO lessons(chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES(v_chapter,v_c_sara,v_c_mia,'Der sichere nächste Schritt','گام بعدی مطمئن','Sara und Mia klären, wann Mia sofort Hilfe braucht und wann sie weiter ruhen kann.','سارا و میا روشن می‌کنند چه زمانی میا به کمک فوری نیاز دارد و چه زمانی می‌تواند به استراحت ادامه دهد.','story','mia-sara-b1-health-routine',12,54,180,4,'validated','{"relationship":"friends","context":"health-routine","cefr":"B1","storyArc":"safe-next-step"}'); SET v_l_4=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_sara,1,'character','Und wenn du plötzlich Fieber bekommst?','اگر ناگهان تب کنی چه؟',54,NULL,NULL,NULL,NULL,'[{"surface":"Und","lemma":"und","translation":"و","partOfSpeech":"conjunction"},{"surface":"wenn","lemma":"wenn","translation":"اگر / وقتی","partOfSpeech":"conjunction"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"plötzlich","lemma":"plötzlich","translation":"ناگهان","partOfSpeech":"adverb"},{"surface":"Fieber","lemma":"Fieber","translation":"تب","partOfSpeech":"noun"},{"surface":"bekommst","lemma":"bekommen","translation":"گرفتن / دچار شدن","partOfSpeech":"verb","suffix":"?"}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_19=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_mia,2,'learner','Dann warte ich nicht bis morgen.','آن‌وقت تا فردا صبر نمی‌کنم.',54,NULL,NULL,'dann warte ich nicht bis morgen',NULL,'[{"surface":"Dann","lemma":"dann","translation":"بعد / سپس","partOfSpeech":"adverb"},{"surface":"warte","lemma":"warten","translation":"منتظر ماندن / صبر کردن","partOfSpeech":"verb"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"nicht","lemma":"nicht","translation":"نه / نیست","partOfSpeech":"adverb"},{"surface":"bis","lemma":"bis","translation":"تا","partOfSpeech":"conjunction"},{"surface":"morgen","lemma":"morgen","translation":"فردا","partOfSpeech":"adverb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_20=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_sara,3,'character','Genau, dann brauchst du sofort Hilfe.','دقیقاً، آن‌وقت فوراً به کمک نیاز داری.',54,NULL,NULL,NULL,NULL,'[{"surface":"Genau","lemma":"genau","translation":"دقیقا","partOfSpeech":"adverb","suffix":","},{"surface":"dann","lemma":"dann","translation":"بعد / سپس","partOfSpeech":"adverb"},{"surface":"brauchst","lemma":"brauchen","translation":"نیاز داشتن / لازم داشتن","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"sofort","lemma":"sofort","translation":"فورا / همین الان","partOfSpeech":"adverb"},{"surface":"Hilfe","lemma":"Hilfe","translation":"کمک","partOfSpeech":"noun","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_21=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_mia,4,'learner','Ich weiß, wann ich wieder zum Arzt gehen muss.','می‌دانم چه زمانی باید دوباره پیش دکتر بروم.',54,NULL,NULL,'ich weiß wann ich wieder zum arzt gehen muss',NULL,'[{"surface":"Ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"weiß","lemma":"wissen","translation":"دانستن","partOfSpeech":"verb","suffix":","},{"surface":"wann","lemma":"wann","translation":"کی / چه زمانی","partOfSpeech":"adverb"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"wieder","lemma":"wieder","translation":"دوباره","partOfSpeech":"adverb"},{"surface":"zum","lemma":"zu","translation":"به / به سمت","partOfSpeech":"preposition"},{"surface":"Arzt","lemma":"Arzt","translation":"دکتر","partOfSpeech":"noun"},{"surface":"gehen","lemma":"gehen","translation":"رفتن","partOfSpeech":"verb"},{"surface":"muss","lemma":"müssen","translation":"مجبور بودن / باید","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_22=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_sara,5,'character','Gut, dann kannst du dich weiter ausruhen.','خوب، پس می‌توانی به استراحت ادامه بدهی.',54,NULL,NULL,NULL,NULL,'[{"surface":"Gut","lemma":"gut","translation":"خوب","partOfSpeech":"adjective","suffix":","},{"surface":"dann","lemma":"dann","translation":"بعد / سپس","partOfSpeech":"adverb"},{"surface":"kannst","lemma":"können","translation":"توانستن / بتوان","partOfSpeech":"verb"},{"surface":"du","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"dich","lemma":"du","translation":"تو","partOfSpeech":"pronoun"},{"surface":"weiter","lemma":"weiter","translation":"ادامه / بیشتر","partOfSpeech":"adverb"},{"surface":"ausruhen","lemma":"sich ausruhen","translation":"استراحت کردن","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_23=LAST_INSERT_ID();
  INSERT INTO turns(lesson_id,character_id,sort_order,role,text,translation,difficulty,audio_url,audio_duration_ms,speech_target,speech_alternatives,tokens,grammar_title,grammar_note,grammar_data,metadata) VALUES(v_l_4,v_c_mia,6,'learner','Das mache ich, bis es mir besser geht.','همین کار را می‌کنم تا حالم بهتر شود.',54,NULL,NULL,'das mache ich bis es mir besser geht',NULL,'[{"surface":"Das","lemma":"das","translation":"این / آن","partOfSpeech":"pronoun"},{"surface":"mache","lemma":"machen","translation":"انجام دادن","partOfSpeech":"verb"},{"surface":"ich","lemma":"ich","translation":"من","partOfSpeech":"pronoun","suffix":","},{"surface":"bis","lemma":"bis","translation":"تا","partOfSpeech":"conjunction"},{"surface":"es","lemma":"es","translation":"آن / این / ضمیر خنثی","partOfSpeech":"pronoun"},{"surface":"mir","lemma":"ich","translation":"من","partOfSpeech":"pronoun"},{"surface":"besser","lemma":"gut","translation":"خوب","partOfSpeech":"adjective"},{"surface":"geht","lemma":"gehen","translation":"رفتن","partOfSpeech":"verb","suffix":"."}]','Bedingungen mit wenn und medizinische Schritte','با wenn شرط واقعی بیان می‌شود؛ در جملهٔ وابسته فعل در پایان می‌آید و جملهٔ اصلی اقدام بعدی را مشخص می‌کند.','{"focus":"wenn_health_followup","structures":["wenn clause","reported symptoms","passive with werden","temporal bis clause"]}','{"cefr":"B1","course":"de-fa","series":103}'); SET v_t_24=LAST_INSERT_ID();
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_070,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_081,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_019,'review',0,4);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_055,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_023,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_006,'new',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_014,'review',0,3);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_076,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_033,'review',0,5);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_053,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_009,'new',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_046,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_026,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_011,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_064,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_031,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_085,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_075,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_084,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_086,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_004,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_025,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_049,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_028,'review',0,2);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_039,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_079,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_062,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_015,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_042,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_021,'review',0,1);
  INSERT INTO lesson_words(lesson_id,word_id,learning_role,is_target,exposure_count) VALUES(v_l_4,v_w_032,'new',1,1);
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'new_word',1,NULL,v_w_032,'عبارت کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'new_word',2,NULL,v_w_064,'واژهٔ کلیدی درس',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'listen',3,v_t_19,NULL,'به جملهٔ سارا گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'speak',4,v_t_20,NULL,'پاسخ میا را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'listen',5,v_t_23,NULL,'به جملهٔ بعدی گوش کن',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'speak',6,v_t_24,NULL,'پاسخ را با صدای بلند بگو',NULL,54,NULL,'{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'meaning_choice',7,NULL,v_w_064,'معنی واژهٔ کلیدی را انتخاب کن',NULL,54,'{"mode":"word_translation","question":"sofort در این درس چه معنی دارد؟","choices":["فورا / همین الان","رزرو قطار","تعمیر خانه"],"correctIndex":0}','{"cefr":"B1","series":103}');
  INSERT INTO activities(lesson_id,activity_type,sort_order,turn_id,word_id,prompt,instruction,difficulty,config,metadata) VALUES(v_l_4,'reading_comprehension',8,NULL,NULL,'مکالمه را بخوان و پاسخ بده',NULL,54,'{"source":"lesson_story","question":"اگر میا ناگهان تب کند چه می‌کند؟","choices":["تا فردا صبر نمی‌کند","سر کار می‌رود","ورزش می‌کند"],"correctIndex":0}','{"cefr":"B1","series":103}');
  SELECT COUNT(*) INTO v_count FROM lessons WHERE chapter_id=v_chapter; IF v_count<>4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 103 requires four lessons.'; END IF;
  SELECT COUNT(*) INTO v_count FROM turns t JOIN lessons l ON l.id=t.lesson_id WHERE l.chapter_id=v_chapter; IF v_count<>24 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 103 requires 24 turns.'; END IF;
  SELECT COUNT(*) INTO v_count FROM turns t JOIN lessons l ON l.id=t.lesson_id WHERE l.chapter_id=v_chapter AND t.role='learner' AND (t.speech_target IS NULL OR CHAR_LENGTH(TRIM(t.speech_target))=0); IF v_count<>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Every learner Turn needs speech_target.'; END IF;
  SELECT COUNT(*) INTO v_count FROM activities a JOIN lessons l ON l.id=a.lesson_id WHERE l.chapter_id=v_chapter; IF v_count<>32 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Series 103 requires 32 activities.'; END IF;
  SELECT COUNT(*) INTO v_count FROM lessons WHERE chapter_id=v_chapter AND prompt_character_id<>learner_character_id AND storyline_key='mia-sara-b1-health-routine' AND storyline_order BETWEEN 9 AND 12 AND status='validated'; IF v_count<>4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Continuity failure.'; END IF;
  SELECT COUNT(*) INTO v_count FROM (SELECT lw.lesson_id,lw.word_id,COUNT(*) n FROM lesson_words lw JOIN lessons l ON l.id=lw.lesson_id WHERE l.chapter_id=v_chapter GROUP BY lw.lesson_id,lw.word_id HAVING COUNT(*)>1)d; IF v_count<>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Duplicate lesson_words tuple.'; END IF;
  UPDATE chapters SET planned_lesson_count=4,status='validated' WHERE id=v_chapter; COMMIT;
END$$
DELIMITER ;
CALL import_nova_series_103_v9();
DROP PROCEDURE IF EXISTS import_nova_series_103_v9;
