-- SERIES 3
SET NAMES utf8mb4;
DROP PROCEDURE IF EXISTS nova_en_v3_s003;
DELIMITER $$
CREATE PROCEDURE nova_en_v3_s003()
BEGIN
  DECLARE v_count INT DEFAULT 0;
  DECLARE v_course BIGINT UNSIGNED; DECLARE v_level BIGINT UNSIGNED; DECLARE v_module BIGINT UNSIGNED; DECLARE v_chapter BIGINT UNSIGNED;
  DECLARE v_c_arman BIGINT UNSIGNED; DECLARE v_c_maya BIGINT UNSIGNED;
  DECLARE v_l_1 BIGINT UNSIGNED; DECLARE v_l_2 BIGINT UNSIGNED; DECLARE v_l_3 BIGINT UNSIGNED; DECLARE v_l_4 BIGINT UNSIGNED;
  DECLARE v_u_1 BIGINT UNSIGNED; DECLARE v_u_2 BIGINT UNSIGNED; DECLARE v_u_3 BIGINT UNSIGNED; DECLARE v_u_4 BIGINT UNSIGNED; DECLARE v_u_5 BIGINT UNSIGNED; DECLARE v_u_6 BIGINT UNSIGNED;
  DECLARE v_ev BIGINT UNSIGNED;
  DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END;
  START TRANSACTION;
  SELECT COUNT(*),MIN(id) INTO v_count,v_course FROM courses WHERE learning_language='en' AND base_language='fa';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='en-fa course identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_level FROM levels WHERE course_id=v_course AND cefr_level='A1';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='en-fa A1 missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_module FROM modules WHERE level_id=v_level AND sort_order=1;
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='en-fa module 1 missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_c_arman FROM characters WHERE course_id=v_course AND name='Arman' AND gender='male';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Arman identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_c_maya FROM characters WHERE course_id=v_course AND name='Maya' AND gender='female';
  IF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Maya identity missing or not unique'; END IF;
  SELECT COUNT(*),MIN(id) INTO v_count,v_chapter FROM chapters WHERE module_id=v_module AND sort_order=3;
  IF v_count=0 THEN
    INSERT INTO chapters (module_id,title,title_translation,description,description_translation,planned_lesson_count,difficulty_min,difficulty_max,sort_order,status,metadata) VALUES (v_module,'Where Do You Live?','کجا زندگی می‌کنی؟','Arman learns to say where he lives and separates residence from origin.','آرمان یاد می‌گیرد محل زندگی‌اش را بگوید و آن را از مبدأ جدا کند.',4,1,1,3,'validated',JSON_OBJECT('series',3,'contractVersion','3.0.0','level','A1','generatedStatus','locally_validated')); SET v_chapter=LAST_INSERT_ID();
    INSERT INTO words (course_id,lemma,display_form,part_of_speech,translation,difficulty,grammar,distractors,example_text,example_translation,metadata) VALUES
      (v_course,'live','live','verb','زندگی کردن',1,JSON_OBJECT('cefr','A1','sense','reside'),CAST('["آمدن","دیدن","خواستن"]' AS JSON),'I live in London.','من در لندن زندگی می‌کنم.',JSON_OBJECT('sourceSeries',3,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:live:reside')),
      (v_course,'in','in','preposition','در',1,JSON_OBJECT('cefr','A1','sense','place'),CAST('["از","با","برای"]' AS JSON),'I live in London.','من در لندن زندگی می‌کنم.',JSON_OBJECT('sourceSeries',3,'course','en-fa','definitionComplete',TRUE,'semanticUnitKey','en:a1:in:place'));
    INSERT INTO learning_units (course_id,unit_type,unit_key,display_form,translation,description_fa,cefr_level,difficulty,data,metadata) VALUES
      (v_course,'chunk','en:a1:where-do-you-live','Where do you live?','کجا زندگی می‌کنی؟','پرسیدن محل زندگی','A1',1,JSON_OBJECT('function','ask_residence'),JSON_OBJECT('series',3)),
      (v_course,'chunk','en:a1:i-live-in','I live in ...','من در ... زندگی می‌کنم','گفتن محل زندگی','A1',1,JSON_OBJECT('function','state_residence'),JSON_OBJECT('series',3)),
      (v_course,'word_sense','en:a1:live:reside','live','زندگی کردن','live در معنی سکونت داشتن','A1',1,JSON_OBJECT('pos','verb','sense','reside'),JSON_OBJECT('series',3)),
      (v_course,'word_sense','en:a1:in:place','in','در','in برای مکان','A1',1,JSON_OBJECT('pos','preposition','sense','place'),JSON_OBJECT('series',3)),
      (v_course,'grammar','en:a1:present-simple-i-live','I live in ...','من در ... زندگی می‌کنم','present simple با I برای واقعیت شخصی پایه','A1',1,JSON_OBJECT('pattern','I + base verb'),JSON_OBJECT('series',3)),
      (v_course,'pronunciation','en:a1:pron:w-vs-v-intro','where — /w/ onset',NULL,'شروع تشخیص /w/ در where بدون تبدیل به /v/','A1',1,JSON_OBJECT('target','w_vs_v'),JSON_OBJECT('series',3));
    SELECT id INTO v_u_1 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:where-do-you-live';
    SELECT id INTO v_u_2 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:i-live-in';
    SELECT id INTO v_u_3 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:live:reside';
    SELECT id INTO v_u_4 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:in:place';
    SELECT id INTO v_u_5 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:present-simple-i-live';
    SELECT id INTO v_u_6 FROM learning_units WHERE course_id=v_course AND unit_key='en:a1:pron:w-vs-v-intro';
    INSERT INTO curriculum_outcomes (course_id,cefr_level,outcome_key,outcome_type,title,description_fa,required,status,evidence) VALUES
      (v_course,'A1','can_do:state_residence','can_do','State where you live','گفتن محل زندگی',1,'in_progress',JSON_ARRAY()),
      (v_course,'A1','grammar:present-simple-basic','grammar','Present simple with I','حال ساده پایه با I',1,'in_progress',JSON_ARRAY()),
      (v_course,'A1','lexical:home-routine-residence','lexical','Residence chunks','عبارت‌های پایه محل زندگی',1,'in_progress',JSON_ARRAY()),
      (v_course,'A1','pron:w-vs-v','pronunciation','Distinguish initial w','تشخیص /w/ آغازین',1,'in_progress',JSON_ARRAY()),
      (v_course,'A1','listening:key-place-info','listening','Catch place information','تشخیص اطلاعات مکان در شنیدار',1,'in_progress',JSON_ARRAY())
      ON DUPLICATE KEY UPDATE status='in_progress';
    INSERT INTO lessons (chapter_id,prompt_character_id,learner_character_id,title,title_translation,description,description_translation,lesson_type,storyline_key,storyline_order,difficulty,estimated_duration_sec,sort_order,status,metadata) VALUES
      (v_chapter,v_c_maya,v_c_arman,'Where Do You Live?','کجا زندگی می‌کنی؟','Maya asks about Arman''s home in London.','مایا درباره محل زندگی آرمان در لندن می‌پرسد.','story','london_new_start',9,1,420,1,'validated',JSON_OBJECT('pedagogicalRole','exposure')),
      (v_chapter,v_c_maya,v_c_arman,'I Live in London','من در لندن زندگی می‌کنم','Arman learns the residence pattern.','آرمان الگوی گفتن محل زندگی را یاد می‌گیرد.','story','london_new_start',10,1,420,2,'validated',JSON_OBJECT('pedagogicalRole','explicit_form')),
      (v_chapter,v_c_maya,v_c_arman,'From Iran, in London','اهل ایران، ساکن لندن','Arman separates origin from residence.','آرمان تفاوت مبدأ و محل زندگی فعلی را تمرین می‌کند.','story','london_new_start',11,1,420,3,'validated',JSON_OBJECT('pedagogicalRole','retrieval')),
      (v_chapter,v_c_maya,v_c_arman,'A Full Short Introduction','یک معرفی کوتاه کامل','Arman combines name, origin and residence.','آرمان نام، مبدأ و محل زندگی را در یک معرفی کوتاه ترکیب می‌کند.','story','london_new_start',12,1,420,4,'validated',JSON_OBJECT('pedagogicalRole','mastery'));
    SELECT id INTO v_l_1 FROM lessons WHERE chapter_id=v_chapter AND sort_order=1; SELECT id INTO v_l_2 FROM lessons WHERE chapter_id=v_chapter AND sort_order=2; SELECT id INTO v_l_3 FROM lessons WHERE chapter_id=v_chapter AND sort_order=3; SELECT id INTO v_l_4 FROM lessons WHERE chapter_id=v_chapter AND sort_order=4;
    INSERT INTO turns (lesson_id,character_id,sort_order,role,text,translation,difficulty,speech_target,speech_alternatives,tokens,metadata) VALUES
      (v_l_1,v_c_maya,1,'character','Hi, Arman!','سلام آرمان!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,2,'learner','Hi, Maya!','سلام مایا!',1,'Hi, Maya!',JSON_ARRAY('Hi, Maya!','Hello, Maya!'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_maya,3,'character','Where do you live?','کجا زندگی می‌کنی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,4,'learner','I live in London.','من در لندن زندگی می‌کنم.',1,'I live in London.',JSON_ARRAY('I live in London.','I live in London now.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_maya,5,'character','Are you from London?','اهل لندن هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,6,'learner','No, I''m from Iran.','نه، من اهل ایران هستم.',1,'No, I''m from Iran.',JSON_ARRAY('No, I''m from Iran.','No. I''m from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_maya,7,'character','Nice. Welcome!','خوبه. خوش آمدی!',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_1,v_c_arman,8,'learner','Thank you.','ممنون.',1,'Thank you.',JSON_ARRAY('Thank you.','Thanks.'),JSON_ARRAY(),JSON_OBJECT()),
      (v_l_2,v_c_maya,1,'character','Where do you live?','کجا زندگی می‌کنی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,2,'learner','I live in London.','من در لندن زندگی می‌کنم.',1,'I live in London.',JSON_ARRAY('I live in London.','I live in London now.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_maya,3,'character','In London?','در لندن؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,4,'learner','Yes, in London.','بله، در لندن.',1,'Yes, in London.',JSON_ARRAY('Yes, in London.','Yes. I live in London.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_maya,5,'character','Good.','خوبه.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,6,'learner','I like London.','لندن را دوست دارم.',1,'I like London.',JSON_ARRAY('I like London.','London is nice.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_maya,7,'character','Welcome again.','دوباره خوش آمدی.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_2,v_c_arman,8,'learner','Thanks.','ممنون.',1,'Thanks.',JSON_ARRAY('Thanks.','Thank you.'),JSON_ARRAY(),JSON_OBJECT()),
      (v_l_3,v_c_maya,1,'character','Where are you from?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,2,'learner','I''m from Iran.','من اهل ایران هستم.',1,'I''m from Iran.',JSON_ARRAY('I''m from Iran.','I am from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_maya,3,'character','Where do you live?','کجا زندگی می‌کنی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,4,'learner','I live in London.','من در لندن زندگی می‌کنم.',1,'I live in London.',JSON_ARRAY('I live in London.','I live in London now.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_maya,5,'character','So, from Iran and in London.','پس اهل ایران هستی و در لندن زندگی می‌کنی.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,6,'learner','Yes, that''s right.','بله، درست است.',1,'Yes, that''s right.',JSON_ARRAY('Yes, that''s right.','Yes.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_maya,7,'character','Nice to meet you.','از آشنایی با تو خوشحالم.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_3,v_c_arman,8,'learner','Nice to meet you too.','من هم از آشنایی با تو خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT()),
      (v_l_4,v_c_maya,1,'character','Hello! What''s your name?','سلام! اسمت چیه؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,2,'learner','My name is Arman.','اسم من آرمان است.',1,'My name is Arman.',JSON_ARRAY('My name is Arman.','I''m Arman.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_maya,3,'character','Where are you from?','اهل کجا هستی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,4,'learner','I''m from Iran.','من اهل ایران هستم.',1,'I''m from Iran.',JSON_ARRAY('I''m from Iran.','I am from Iran.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_maya,5,'character','Where do you live?','کجا زندگی می‌کنی؟',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,6,'learner','I live in London.','من در لندن زندگی می‌کنم.',1,'I live in London.',JSON_ARRAY('I live in London.','I live in London now.'),JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_maya,7,'character','Nice to meet you, Arman.','از آشنایی با تو خوشحالم آرمان.',1,NULL,NULL,JSON_ARRAY(),JSON_OBJECT()),(v_l_4,v_c_arman,8,'learner','Nice to meet you too.','من هم از آشنایی با تو خوشحالم.',1,'Nice to meet you too.',JSON_ARRAY('Nice to meet you too.','Nice to meet you.'),JSON_ARRAY(),JSON_OBJECT());
    INSERT INTO activities (lesson_id,activity_type,sort_order,prompt,instruction,difficulty,config,metadata) VALUES
      (v_l_1,'listen',1,'Where do you live?','اول فقط گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'new_word',2,'I live in ...','الگوی محل زندگی را یک تکه یاد بگیر.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:i-live-in","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',3,'where','به /w/ آغازین دقت کن.',1,CAST('{"mode":"sound_notice","target":"w_vs_v","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',4,'I live in London.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["I live in London.","I live in London now."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',5,'بگو در لندن زندگی می‌کنی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بگو در لندن زندگی می‌کنی.","accepted":["I live in London.","I live in London now."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'meaning_choice',6,'I live ___ London.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["in","from","to"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'reading_comprehension',7,'Arman: I''m from Iran. I live in London.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Arman: I''m from Iran. I live in London.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'reading_comprehension',8,'Where does Arman live?','اطلاعات را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["London","Iran","Maya"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'word_order',9,'London in live I','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["I","live","in","London"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',10,'یک نفر تازه از محل زندگی‌ات می‌پرسد. پاسخ بده.','در موقعیت تازه پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"یک نفر تازه از محل زندگی‌ات می‌پرسد. پاسخ بده.","accepted_intents":["I live in London.","I live in London now."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_1,'listen',11,'I''m from Iran.','گوش کن و مبدأ را از محل زندگی جدا کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_1,'speak',12,'I live in London.','مستقل بگو.',1,CAST('{"mode":"short_response","accepted":["I live in London.","I live in London now."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
      (v_l_2,'listen',1,'I live in London.','اول گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'new_word',2,'live','معنی live در این context را یاد بگیر.',1,CAST('{"mode":"word_teach","unit_key":"en:a1:live:reside","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'new_word',3,'I + live','ساختار ساده را ببین.',1,CAST('{"mode":"micro_grammar","unit_key":"en:a1:present-simple-i-live","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',4,'Where do you live?','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["Where do you live?","Where do you live"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',5,'بپرس کجا زندگی می‌کنی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بپرس کجا زندگی می‌کنی.","accepted":["Where do you live?","Where do you live"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'meaning_choice',6,'Where ___ you live?','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["do","are","is"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'reading_comprehension',7,'Maya: Where do you live? Arman: I live in London.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Maya: Where do you live? Arman: I live in London.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'reading_comprehension',8,'What city does Arman say?','اطلاعات را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["London","Iran","Arman"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'word_order',9,'live you do Where','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["Where","do","you","live"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',10,'از یک نفر تازه بپرس کجا زندگی می‌کند.','در موقعیت تازه پاسخ بده.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"از یک نفر تازه بپرس کجا زندگی می‌کند.","accepted_intents":["Where do you live?","Where do you live"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_2,'listen',11,'I live in London.','گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_2,'speak',12,'Where do you live?','پرسش را مستقل بگو.',1,CAST('{"mode":"short_response","accepted":["Where do you live?","Where do you live"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
      (v_l_3,'listen',1,'I''m from Iran. I live in London.','تفاوت مبدأ و محل زندگی را بشنو.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'new_word',2,'I''m from ... / I live in ...','دو chunk را کنار هم مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:i-live-in","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',3,'where','به /w/ دقت کن.',1,CAST('{"mode":"sound_notice","target":"w_vs_v","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',4,'I''m from Iran. I live in London.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["I''m from Iran. I live in London.","I am from Iran. I live in London."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',5,'مبدأ و محل زندگی‌ات را بگو.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"مبدأ و محل زندگی‌ات را بگو.","accepted":["I''m from Iran. I live in London.","I am from Iran. I live in London."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'meaning_choice',6,'I''m ___ Iran. I live ___ London.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["from / in","in / from","to / from"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'reading_comprehension',7,'Arman: Hello. I''m from Iran, but I live in London.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Arman: Hello. I''m from Iran, but I live in London.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'reading_comprehension',8,'Where is Arman from?','مبدأ را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["Iran","London","Maya"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'word_order',9,'London in live I','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["I","live","in","London"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',10,'در یک آشنایی تازه نام، مبدأ و محل زندگی‌ات را بگو.','انتقال مستقل.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"در یک آشنایی تازه نام، مبدأ و محل زندگی‌ات را بگو.","accepted_intents":["I''m Arman. I''m from Iran. I live in London.","My name is Arman. I am from Iran. I live in London."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_3,'listen',11,'Nice to meet you.','مرور عبارت قبلی.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_3,'speak',12,'Nice to meet you too.','مستقل پاسخ بده.',1,CAST('{"mode":"short_response","accepted":["Nice to meet you too.","Nice to meet you."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),
      (v_l_4,'listen',1,'Hello. I''m Arman. I''m from Iran. I live in London.','کل معرفی را گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'new_word',2,'Where do you live?','پرسش محل زندگی را مرور کن.',1,CAST('{"mode":"chunk_teach","unit_key":"en:a1:where-do-you-live","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',3,'where','به /w/ آغازین دقت کن.',1,CAST('{"mode":"sound_notice","target":"w_vs_v","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',4,'I live in London.','تکرار کن.',1,CAST('{"mode":"repeat_visible","accepted":["I live in London.","I live in London now."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',5,'بدون دیدن پاسخ بگو کجا زندگی می‌کنی.','از حافظه بگو.',1,CAST('{"mode":"recall_hidden","cue_fa":"بدون دیدن پاسخ بگو کجا زندگی می‌کنی.","accepted":["I live in London.","I live in London now."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'meaning_choice',6,'I ___ in London.','گزینه درست را انتخاب کن.',1,CAST('{"mode":"sentence_blank","options":["live","from","name"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'reading_comprehension',7,'Hello! My name is Arman. I''m from Iran. I live in London.','متن را بخوان.',1,CAST('{"mode":"reading_input","text":"Hello! My name is Arman. I''m from Iran. I live in London.","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'reading_comprehension',8,'Where does Arman live?','محل زندگی را پیدا کن.',1,CAST('{"mode":"reading_inference","options":["London","Iran","Hello"],"answer_index":0,"input":"tap_choice","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'word_order',9,'London in live I','کلمات را مرتب کن.',1,CAST('{"mode":"word_order","tokens":["I","live","in","London"],"input":"tap_tokens","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',10,'بدون راهنما یک معرفی کوتاه کامل انجام بده: نام، مبدأ و محل زندگی.','آزمون mastery.',1,CAST('{"mode":"scenario_transfer","scenario_fa":"بدون راهنما یک معرفی کوتاه کامل انجام بده: نام، مبدأ و محل زندگی.","accepted_intents":["I''m Arman. I''m from Iran. I live in London.","My name is Arman. I am from Iran. I live in London."],"input":"speech","scored":true}' AS JSON),JSON_OBJECT()),(v_l_4,'listen',11,'Goodbye!','پایان تعامل را گوش کن.',1,CAST('{"mode":"audio_first","input":"none","scored":false}' AS JSON),JSON_OBJECT()),(v_l_4,'speak',12,'Goodbye!','پایان تعامل را مستقل بگو.',1,CAST('{"mode":"short_response","accepted":["Goodbye!","Bye!"],"input":"speech","scored":true}' AS JSON),JSON_OBJECT());
    INSERT INTO lesson_learning_units (lesson_id,learning_unit_id,learning_role,is_target,exposure_count,metadata) VALUES
      (v_l_1,v_u_1,'new',1,2,JSON_OBJECT('series',3)),(v_l_1,v_u_2,'new',1,2,JSON_OBJECT('series',3)),(v_l_1,v_u_3,'new',1,2,JSON_OBJECT('series',3)),(v_l_1,v_u_4,'new',1,2,JSON_OBJECT('series',3)),(v_l_1,v_u_5,'new',1,2,JSON_OBJECT('series',3)),(v_l_1,v_u_6,'new',1,2,JSON_OBJECT('series',3)),
      (v_l_4,v_u_1,'mastery',1,2,JSON_OBJECT('series',3)),(v_l_4,v_u_2,'mastery',1,2,JSON_OBJECT('series',3)),(v_l_4,v_u_3,'mastery',1,2,JSON_OBJECT('series',3)),(v_l_4,v_u_4,'mastery',1,2,JSON_OBJECT('series',3)),(v_l_4,v_u_5,'mastery',1,2,JSON_OBJECT('series',3)),(v_l_4,v_u_6,'mastery',1,2,JSON_OBJECT('series',3));
    SELECT id INTO v_ev FROM activities WHERE lesson_id=v_l_3 AND JSON_UNQUOTE(JSON_EXTRACT(config,'$.mode'))='scenario_transfer' ORDER BY sort_order LIMIT 1;
    UPDATE review_obligations SET status='fulfilled',fulfilled_chapter_id=v_chapter,evidence_activity_id=v_ev,metadata=JSON_OBJECT('evidence','retrieval_transfer','series',3) WHERE course_id=v_course AND due_series=3 AND status='due';
    INSERT INTO review_obligations (course_id,learning_unit_id,origin_chapter_id,due_series,spacing_offset,status,metadata)
      SELECT v_course,x.unit_id,v_chapter,3+x.off,x.off,'due',JSON_OBJECT('sourceSeries',3) FROM (
        SELECT v_u_1 unit_id,1 off UNION ALL SELECT v_u_1,2 UNION ALL SELECT v_u_1,4 UNION ALL SELECT v_u_1,8 UNION ALL SELECT v_u_1,16 UNION ALL
        SELECT v_u_2,1 UNION ALL SELECT v_u_2,2 UNION ALL SELECT v_u_2,4 UNION ALL SELECT v_u_2,8 UNION ALL SELECT v_u_2,16 UNION ALL
        SELECT v_u_3,1 UNION ALL SELECT v_u_3,2 UNION ALL SELECT v_u_3,4 UNION ALL SELECT v_u_3,8 UNION ALL SELECT v_u_3,16 UNION ALL
        SELECT v_u_4,1 UNION ALL SELECT v_u_4,2 UNION ALL SELECT v_u_4,4 UNION ALL SELECT v_u_4,8 UNION ALL SELECT v_u_4,16 UNION ALL
        SELECT v_u_5,1 UNION ALL SELECT v_u_5,2 UNION ALL SELECT v_u_5,4 UNION ALL SELECT v_u_5,8 UNION ALL SELECT v_u_5,16 UNION ALL
        SELECT v_u_6,1 UNION ALL SELECT v_u_6,2 UNION ALL SELECT v_u_6,4 UNION ALL SELECT v_u_6,8 UNION ALL SELECT v_u_6,16
      ) x ON DUPLICATE KEY UPDATE due_series=VALUES(due_series);
    UPDATE curriculum_outcomes SET evidence=JSON_ARRAY_APPEND(COALESCE(evidence,JSON_ARRAY()),'$','EN-CH-0003'),status='in_progress' WHERE course_id=v_course AND cefr_level='A1' AND outcome_key IN ('can_do:state_residence','grammar:present-simple-basic','lexical:home-routine-residence','pron:w-vs-v','reading:short_identity','listening:key-place-info');
  ELSEIF v_count<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='chapter identity not unique'; END IF;
  COMMIT;
END$$
DELIMITER ;
CALL nova_en_v3_s003();
DROP PROCEDURE IF EXISTS nova_en_v3_s003;
